### ISSUE TITLE
建议工具类中新增CSS和Xpath选择器

### ISSUE THREAD

**Issue by pibigstar** [gogf/gf#100]
有时候并没有API接口，只有网页URL，返回的不是JSON数据，而是网页的html内容，这时候如果想获取里面特定的内容就会非常麻烦，只能通过正则去获取，参考到Python中Scrapy框架中的CSS选择器和Xpath选择器，可快速定位到网页中具体的内容。

大概是这样：
```go
css，err := css.New("#content > div.name > ul")
nodes := css.Select("网页内容")

xpath,err := xpath.New("//*[@id="content"]/div[1]")
nodes: = xpath.Select("网页内容")
```

**Comment by johngcn** [comment]
@pibigstar 你想要的或许是[goquery](https://github.com/PuerkitoBio/goquery)？

**Comment by pibigstar** [comment]
@johngcn  没用过这个，简单看了下他们的demo，确实是css选择器
