### ISSUE TITLE
gf 1.14.3 orm   update出错

### ISSUE THREAD

**Issue by jinmao88** [gogf/gf#1000]
gf 1.14.3
gfcli 1.14.3

用cli生成的orm

update
报错
Error: sql: expected 16 arguments, got 17

**Comment by LonelySally** [comment]
核对字段数.错误提示16个字段给了17个值

**Comment by jinmao88** [comment]
1.42.2 正常的

**Comment by jinmao88** [comment]
就是cli生成的orm里 filed 里 参数 换一下

**Comment by LonelySally** [comment]
> 就是cli生成的orm里 filed 里 参数 换一下

贴下mysql的dll跟cli生成的entity

**Comment by chenghonour** [comment]
同样的问题，使用cli生成的entity文件下的update、delete方法都是报参数超出的错：Error: sql: expected 1 arguments, got 2 
![image](https://user-images.githubusercontent.com/16969987/99627830-fc720780-2a6f-11eb-8acf-5d9d0d027a0a.png)

**Comment by tiger1103** [comment]
确实有这个问题 使用entity的update 和delete 方法报错Error: sql: expected xxx arguments, got xxx+1

**Comment by housemecn** [comment]
> 确实有这个问题 使用entity的update 和delete 方法报错Error: sql: expected xxx arguments, got xxx+1
> 1.14.4同样存在

建议把代码贴出来！

**Comment by tiger1103** [comment]
> > 确实有这个问题 使用entity的update 和delete 方法报错Error: sql: expected xxx arguments, got xxx+1
> > 1.14.4同样存在
> 
> 建议把代码贴出来！

翻看了下gf源码发现代码生成的entity文件中：
```
// Update does "UPDATE...WHERE..." statement for updating current object from table.
// It updates the record if there's already another same record in the table
// (it checks using primary key or unique index).
func (r *Entity) Update() (result sql.Result, err error) {
	return Model.Data(r).Where(gdb.GetWhereConditionOfStruct(r)).Update()
}

// Delete does "DELETE FROM...WHERE..." statement for deleting current object from table.
func (r *Entity) Delete() (result sql.Result, err error) {
	return Model.Where(gdb.GetWhereConditionOfStruct(r)).Delete()
}
```
GetWhereConditionOfStruct此方法返回三个值，最后一个err   where接收时把err当args了。

**Comment by gqcn** [comment]
@tiger1103 @chenghonour @LonelySally @jinmao88 @housemecn 嗯，这里的cli自动生成的方法有点问题，大家可以把Entity的那几个操作方法删掉，使用`Model`来操作吧，未来不建议使用`Entity`下封装的那几个方法了。不过我也已经修复了cli的这个问题，依旧会保持兼容，大家使用`gf update`更新一下cli再运行下`gf gen model`重新生成entity文件就好了，试试呢。
