### ISSUE TITLE
CPU 占用居高不下 

### ISSUE THREAD

**Issue by mir355** [gogf/gf#1004]
Build Detail:
  Go Version:  go1.13.4
  GF Version:  v1.13.1
  Git Commit:  1db1828b35c15b4a92cd144c33e636eb52d7ec07
  Build Time:  2020-06-14 21:01:20

今日进行代码漏洞扫描，指标如下：
```
2个并发请求
250ms请求延迟
```
1、持续5分钟后，系统4核CPU全部占满，
2、7分钟后，应用服务响应变慢， 
3、扫描结束30分钟后，CPU资源仍未释放

![20201119163428](https://user-images.githubusercontent.com/33676095/99641416-313c8980-2a85-11eb-9539-be20d8810244.png)

![profile001](https://user-images.githubusercontent.com/33676095/99641453-3e597880-2a85-11eb-92dc-a2c93004b0e3.png)

**Comment by gqcn** [comment]
@mir355 哥，你这Top10，还有你这图，连一个gf包的影子都没有啊，你需要我怎么帮助你啊？😅

**Comment by mir355** [comment]
我也是看不懂这个图了，竟然找不到入手点，所以才向大佬求助

**Comment by gqcn** [comment]
> 我也是看不懂这个图了，竟然找不到入手点，所以才向大佬求助。
> 1、为啥pprof 里没有gf包的影子，是不是埋点有问题？
> 2、这几个较高的runtime 方法，可能被触发的原因是啥？
> 我感觉导致其一直hold CPU 资源不放的原因是在某个位置的代码触go的内部死循环了，帮我分析下切入点呗，大佬。

你如果使用gf的pprof或者net/http的pprof功能，那么埋点不会有问题的。你得从你代码入口入手，判断下哪里可能会有性能问题。初步看了下是不是你引用了其他的第三方引起的？

**Comment by mir355** [comment]
今日又跟踪了一下，发现是这个包 “github.com/json-iterator” 大量报错导致fmt频繁内存操作导致CPU飙高。但问题仍未解决，请大佬帮忙解决问题。

分析gf源码，如下文件引用了这个包

```
nternal/json/json.go
```
我代码单独引用该包只用了如下两个方法
```
json.Unmarshal
json.Marshal
```
pprof 截图如下

![1606818316(1)](https://user-images.githubusercontent.com/33676095/100728505-99368c80-3402-11eb-8452-9c9a692805d4.jpg)

![profile001](https://user-images.githubusercontent.com/33676095/100728380-74dab000-3402-11eb-871e-aac223b27755.png)

**Comment by gqcn** [comment]
@mir355 你好，我初步看了没看出什么缘由来，要不你去 `github.com/json-iterator/go` 问问看，这个包好像也是国人开发的。

**Comment by mir355** [comment]
这个包在gf 框架中使用了很多，我没看出我的哪种错误姿势引发了这个问题。另我自己方法的err 里也没有明显的报错信息。
已在对方的项目提交issue 
https://github.com/json-iterator/go/issues/516
感谢大佬帮忙跟进

**Comment by mir355** [comment]
@gqcn 大佬，对方的项目似乎没人维护啊，你确定一直用这个包做你json 的解析吗? 我代码里该包引用的方法我都去掉了，问题仍然存在，我确认应该是gf 框架里方法引用导致的。
https://github.com/gogf/gf/blob/master/internal/json/json.go 这个文件有说明方法可以调试

**Comment by gqcn** [comment]
> @gqcn 大佬，对方的项目似乎没人维护啊，你确定一直用这个包做你json 的解析吗? 我代码里该包引用的方法我都去掉了，问题仍然存在，我确认应该是gf 框架里方法引用导致的。
> 请协助解决，或告知 https://github.com/gogf/gf/blob/master/internal/json/json.go 这个文件有什么方法可以调试

@mir355 这个有专门封装的，切换/去掉都很容易，我特意创建了一个分支，去掉了这个包的使用，你试试`go get -u github.com/gogf/gf@1e7f795c6993be992865042943e476da17ee8dae` 再试试还有没问题？

**Comment by BlackCodes** [comment]
我们把这个库，通过extension的方式，深度定制了一次，看到大佬们的问题，心里有点慌了，期待大佬们的最终解决方式。

**Comment by mir355** [comment]
@gqcn 大佬出手立竿见影，以前压测CPU每次都爆，换新版本后10%都用不上。

**Comment by gqcn** [comment]
@mir355 这么看这个第三方包是有点问题，我先去掉吧。
