### ISSUE TITLE
希望加解密模块支持 argon2/scrypt/bcrypt 算法

### ISSUE THREAD

**Issue by yimingsir** [gogf/gf#1009]
算法实现：https://godoc.org/golang.org/x/crypto

因为目前MD5和SHA1算法已被证明为不安全的算法，在密码的存储中，已不再被建议使用。希望gf集成 argon2/scrypt/bcrypt 算法。

密码安全相关参考：https://medium.com/analytics-vidhya/password-hashing-pbkdf2-scrypt-bcrypt-and-argon2-e25aaf41598e

**Comment by gqcn** [comment]
@yimingsir 不错的建议，不过引入新的特性需要保证：
1. 不要引入过于复杂的第三方包。
1. 不能引入CGO特性。
1. 完整的单元测试。

这块可以等待其他同学来贡献吧。如果你感兴趣也非常欢迎PR。
