### ISSUE TITLE
多次调用grand.RandLetters或grand.RandStr后，随机字符串会变成zzzz....

### ISSUE THREAD

**Issue by praynise** [gogf/gf#101]
您好，我在我的工具中，使用了grand.RandStr(32)用来生成随机的临时文件名，但是工具在运行一段时间后，文件名变成了32个z，且从某一时间点后，所有的随机生成字符串均变成了32个z，不再具有随机性。改为grand.RandLetters也一样
go版本为1.12.1，系统版本redhat6.5

**Comment by johngcn** [comment]
@praynise `grand`近期出现一个BUG，请更新最新框架代码。
