### ISSUE TITLE
建议gf web框架加入或集成安全模块，防范常见web攻击

### ISSUE THREAD

**Issue by yimingsir** [gogf/gf#1010]
希望gf web框架可以加入对 xss/csrf/clickjacking 等常见web攻击手段的安全防护模块

参考项目：https://github.com/unrolled/secure

**Comment by gqcn** [comment]
@yimingsir 不错的建议，这个对接很简单。

**Comment by yimingsir** [comment]
@gqcn 
crsf 防御可以集成 https://github.com/gorilla/csrf 
希望gf越来越安全，谢谢大神

**Comment by arieslee** [comment]
> @gqcn
> crsf 防御可以集成 https://github.com/gorilla/csrf
> 希望gf越来越安全，谢谢大神



> @yimingsir 不错的建议，这个对接很简单。

目前gf中不是有csrf的功能吗?

**Comment by yimingsir** [comment]
> > @gqcn
> > crsf 防御可以集成 https://github.com/gorilla/csrf
> > 希望gf越来越安全，谢谢大神
> 
> > @yimingsir 不错的建议，这个对接很简单。
> 
> 目前gf中不是有csrf的功能吗?

gf 哪里可以配置？我没有看到

**Comment by arieslee** [comment]
> > > @gqcn
> > > crsf 防御可以集成 https://github.com/gorilla/csrf
> > > 希望gf越来越安全，谢谢大神
> > 
> > 
> > > @yimingsir 不错的建议，这个对接很简单。
> > 
> > 
> > 目前gf中不是有csrf的功能吗?
> 
> gf 可配置跨域cors，但我没找到csrf相关的文档。请问gf怎么配置csrf？

前几天翻源码的时候还看见来着，现在找不到了。。。

**Comment by yimingsir** [comment]
> > > > @gqcn
> > > > crsf 防御可以集成 https://github.com/gorilla/csrf
> > > > 希望gf越来越安全，谢谢大神
> > > 
> > > 
> > > > @yimingsir 不错的建议，这个对接很简单。
> > > 
> > > 
> > > 目前gf中不是有csrf的功能吗?
> > 
> > 
> > gf 可配置跨域cors，但我没找到csrf相关的文档。请问gf怎么配置csrf？
> 
> #451

看到了，已在开发计划中，谢谢提醒。在echo的csrf实现中，没有看到SameSite属性，可以参考gorilla的csrf实现，加入进去。

**Comment by hailaz** [comment]
> > > > > @gqcn
> > > > > crsf 防御可以集成 https://github.com/gorilla/csrf
> > > > > 希望gf越来越安全，谢谢大神
> > > > 
> > > > 
> > > > > @yimingsir 不错的建议，这个对接很简单。
> > > > 
> > > > 
> > > > 目前gf中不是有csrf的功能吗?
> > > 
> > > 
> > > gf 可配置跨域cors，但我没找到csrf相关的文档。请问gf怎么配置csrf？
> > 
> > 
> > #451
> 
> 看到了，已在开发计划中，谢谢提醒。在echo的csrf实现中，没有看到SameSite属性，可以参考gorilla的csrf实现，加入进去。

csrf很早就加好了，看起来是忘记发布
https://github.com/gogf/csrf

SameSite属性，可以自己改造，然后给提个pr，造福大家

**Comment by gqcn** [comment]
@hailaz 亮仔，要不你把CSRF的文档写到这里：https://itician.org/pages/viewpage.action?pageId=1114499

**Comment by hailaz** [comment]
CSRF的文档
https://itician.org/pages/viewpage.action?pageId=3671975

**Comment by hailaz** [comment]
> > > > > @gqcn
> > > > > crsf 防御可以集成 https://github.com/gorilla/csrf
> > > > > 希望gf越来越安全，谢谢大神
> > > > 
> > > > 
> > > > > @yimingsir 不错的建议，这个对接很简单。
> > > > 
> > > > 
> > > > 目前gf中不是有csrf的功能吗?
> > > 
> > > 
> > > gf 可配置跨域cors，但我没找到csrf相关的文档。请问gf怎么配置csrf？
> > 
> > 
> > #451
> 
> 看到了，已在开发计划中，谢谢提醒。在echo的csrf实现中，没有看到SameSite属性，可以参考gorilla的csrf实现，加入进去。

@yimingsir https://github.com/gogf/csrf/blob/master/README.MD
文档例子添加了如何自定义samesite
