### ISSUE TITLE
Oracle数据库, 时间类型的字段没有使用TO_DATE()函数转换,造成SQL执行失败

### ISSUE THREAD

**Issue by joseph-bing-han** [gogf/gf#1014]
### 1. What version of `Go` and system type/arch are you using?

go version go1.15.5 linux/amd64

### 2. What version of `GoFrame` are you using?

v1.14.5

### 3. Can this issue be reproduced with the latest release?

Yes

### 4. What did you do?

```go
package user

type Entity struct {
	Id        int64       `orm:"id"         json:"id"`         //
	Email     string      `orm:"email"      json:"email"`      //
	Password  string      `orm:"password"   json:"password"`   //
	Name      string      `orm:"name"       json:"name"`       //
	Avatar    string      `orm:"avatar"     json:"avatar"`     //
	CreatedAt *gtime.Time `orm:"created_at" json:"created_at"` //
	UpdatedAt *gtime.Time `orm:"updated_at" json:"updated_at"` //
}

func Save(p *user.SaveReq) (user.VO, error) {
	bean   user.Entity
	 _ = gconv.Struct(p, &bean)
	id := bean.Id
	bean.Id = 0
	bean.Email = "test@test.com"
	bean.Name = "Test"
	bean.Avatar = "avatar1.png"
	 _, err = user.Model.OmitEmpty().Update(bean, g.Map{"id=?": id})
 	
	......
}
```

### 5. What did you expect to see?
转换成正确的SQL: 
```sql
UPDATE USERS SET updated_at=to_date('2020-11-25 01:03:05','yyyy-MM-dd HH:MI:SS'),email='test@test.com',name='Test',avatar='avatar1.png' WHERE id=1
```

### 6. What did you see instead?

```log
2020-11-25 01:03:05.641 [ERRO] [ 70 ms] [default] UPDATE USERS SET updated_at='2020-11-25 01:03:05',email='test@test.com',name='Test',avatar='avatar1.png' WHERE id=1
Error: ORA-01861: literal does not match format string

```

**Comment by gqcn** [comment]
@joseph-bing-han 你好，我这没有Oracle环境，如果字符串不行的话，除了`TO_DATE`这种方式还有没其他方式可以赋值？

**Comment by joseph-bing-han** [comment]
@gqcn 如果用字符串的话, 就得用TO_DATE转换, 我觉得比较好的方案是把时间戳类型的字段都直接传time值, 不用字符串

目前针对这个bug, 我自己的解决方案是给Oracle加了个自定义驱动, 进行一次SQL的过滤, 把时间字符串都转成数值, 然后再传给原始的OracleDriver

```go
func (d *MyOracleDriver) HandleSqlBeforeCommit(link gdb.Link, sql string, args []interface{}) (string, []interface{}) {
	for i, v := range args {
		// 将字符串类型的时间转成数值
		if reflect.TypeOf(v).Kind() == reflect.String {
			val := gconv.String(v)
			if gregex.IsMatchString(`^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$`, val) {
				args[i] = gconv.Time(val, "2006-01-02 15:04:05")
			}
		}
	}
	return d.DriverOracle.HandleSqlBeforeCommit(link, sql, args)
}
```

**Comment by gqcn** [comment]
> @gqcn 如果用字符串的话, 就得用TO_DATE转换, 我觉得比较好的方案是把时间戳类型的字段都直接传time值, 不用字符串
> 
> 目前针对这个bug, 我自己的解决方案是给Oracle加了个自定义驱动, 进行一次SQL的过滤, 把时间字符串都转成数值, 然后再传给原始的OracleDriver
> 
> ```go
> func (d *MyOracleDriver) HandleSqlBeforeCommit(link gdb.Link, sql string, args []interface{}) (string, []interface{}) {
> 	for i, v := range args {
> 		// 将字符串类型的时间转成数值
> 		if reflect.TypeOf(v).Kind() == reflect.String {
> 			val := gconv.String(v)
> 			if gregex.IsMatchString(`^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$`, val) {
> 				args[i] = gconv.Time(val, "2006-01-02 15:04:05")
> 			}
> 		}
> 	}
> 	return d.DriverOracle.HandleSqlBeforeCommit(link, sql, args)
> }
> ```

好的，是个好建议。我们尝试着改进下。另外你那能方便提供下可供外网连接的oracle地址么，我可以测试一下。我的微信是 389961817.

**Comment by gqcn** [comment]
@joseph-bing-han 其实这里有两种做法：
1. 使用`time.Time`类型替代`gtime.Time`类型，这样参数会不经过任何转换传递给底层的driver处理，但是往往底层的driver可能会对时间参数做时区转换，具体可查阅下第三方的oci8 driver说明。
2. 第二种方式如你那样，底层对时间参数做一下转换处理，不过不是特别严谨。我已经改进了一下orm模块，随着下一个版本发布，如果想要提前使用可以通过`go get -u github.com/gogf/gf@9592fb099f052e9aa9d3224341db57b04624a7b3`更新。
