### ISSUE TITLE
gproc.send 在快速交互下的使用问题

### ISSUE THREAD

**Issue by mopsky** [gogf/gf#1019]
gproc.Send发送和gproc.Receive接收，在两个进程快速启停的时候，经常找不到端口
```
could not find port for pid: 24299
```

看了下代码，gproc会在/tmp/gproc下写进程ID的端口信息，如果一个进程启动后立即发送或者接收，会出现找不到端口，或者收不到包情况，怀疑是进程启动后，文件写入还没这么及时，导致另外个进程找不到端口，我目前在程序里使用sleep等待1秒，总感觉怪怪的，而且性能也很低，不知道我理解对不对，还有没有其他的解决方案？

**Comment by mopsky** [comment]
Sleep等待偶尔也会出现问题，发送端发了三个包，接后端只收到两个，第一个包丢了

发送端：
```
2020/11/26 10:39:57 接收到子进程消息 25798 {"CMD": "REG", "Data": {"process_id": 102, "process_name": "CFBalance", "pid": 25798}}
2020/11/26 10:39:57 收到子进程注册命令
2020/11/26 10:40:00 发送。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。
2020/11/26 10:40:03 发送。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。
2020/11/26 10:40:06 发送。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。
```

接收端：
```
2020/11/26 10:39:57 确认守护进程 25762
2020/11/26 10:40:03 {"CMD":"REG_CONFIRM","Data":{"err_code":10,"err_msg":"进程注册成功！！"}}
2020/11/26 10:40:06 {"CMD":"REG_CONFIRM","Data":{"err_code":10,"err_msg":"进程注册成功！！"}}
```

**Comment by mopsky** [comment]
子进程的代码，是启动后先发送注册命令到守护进程，然后再Receive，但是我看pid端口文件是在Receive里才开始写入的，所有有时间差：
```
![image](https://user-images.githubusercontent.com/18085384/100302841-24b0b780-2fd6-11eb-9dd2-65e8cd493414.png)

```

**Comment by gqcn** [comment]
@mopsky 是的，对方进程要监听才会写pid文件。进程通信这块是实验性特性，这块其实使用率并并不高，因此没有继续改进。有好建议欢迎提。
![image](https://user-images.githubusercontent.com/26347176/100355705-2f4a6b80-302d-11eb-8911-77a9f5d39fe2.png)

**Comment by mopsky** [comment]
嗯，不好意思，今天才看到已经被答复了，谢谢~ 
我的想法是这个端口号能否在gproc初始化的时候自己指定？如果自己设置端口，就不写pid文件，如果没有指定还是按以前的设计流程

**Comment by gqcn** [comment]
@mopsky 其实你这个问题并不是在于有没有找到端口号，而在于对方有没有准备好接受你的请求，进程调用`Receive`方法才会写`pid`文件，表示准备好了可以接受数据。启动+准备接受数据，这个操作一般是在毫秒以内（具体看系统端口号分配时间开销）。所以这种通信方式会在程序启动的时候有一定延迟。你的场景也算比较特殊。后续这块看有没更优雅的方式吧，比如pipe之类的。

**Comment by mopsky** [comment]
@gqcn 收到，谢谢，我现在的做法调整了下，进程启动的时候先去go grpoc.Receive，进程等待1s再发送数据交互，这样基本没有什么问题，问题我先关闭，万分感谢
