### ISSUE TITLE
web设计模板引擎里内置函数是否有字符替换功能

### ISSUE THREAD

**Issue by qq1196** [gogf/gf#102]
https://goframe.org/os/gview/funcs
类似于php的字符替换，
strtr()和str_repalce()

在模板中字符替换应该用的应该比较广泛，

在模板里面，AddSlashes，StripSlashes   这两个用的也比较多吧，

**Comment by johngcn** [comment]
@qq1196 模板函数其实应当尽可能少，因为模板仅作展示，尽量有业务逻辑的处理放到控制器中处理。你有在其他模板引擎中见到有这些方法吗？

**Comment by johngcn** [comment]
@qq1196 已增加`replace`模板方法，将会在`v1.10`版本发布：
![image](https://user-images.githubusercontent.com/26347176/68391047-a3576e80-01a1-11ea-8788-a3c386cc1909.png)

**Comment by johngcn** [comment]
@qq1196 请更新到最新的`v1.10.0`试试
