### ISSUE TITLE
以后可以不可以加入对protobuf协议的支持，类似gin的bind这种方式绑定到pb.go文件上

### ISSUE THREAD

**Issue by ayamzh** [gogf/gf#1020]
以后可以不可以加入对protobuf协议的支持，类似gin的bind这种方式绑定到pb.go文件上。现在越来越多的项目选用pb作为数据协议了

**Comment by gqcn** [comment]
@ayamzh 有这方面计划，我还不知道gin支持proto协议，能否详细描述下你的想法。

**Comment by ayamzh** [comment]
@gqcn func startClient() {
  r := &pb.ReqEcho{
    Id:   1,
    Data: "111111111111111111",
  }
  data, er := proto.Marshal(r)
  if er != nil {
    log.Fatal(er)
    return
  }
  reader := strings.NewReader(string(data))
  resp, err := http.Post("http://127.0.0.1:8889/pb", "application/x-protobuf", reader)
  if err != nil {
    log.Println(err)
    return
  }
  defer func() {
    _ = resp.Body.Close()
  }()

  body, err := ioutil.ReadAll(resp.Body)
  if err != nil {
    log.Println(err)
    return
  }
  echo := &pb.AckEcho{}
  _ = proto.UnmarshalMerge(body, echo)
  log.Println(echo)
}

func main() {
  {
    time.AfterFunc(time.Second, func() {
      go startClient()
    })
    engine := gin.Default()
    engine.POST("/pb", func(c *gin.Context) {
      r := &pb.ReqEcho{}
      err := c.Bind(r)
      if err != nil {
        return
      }
      r1 := &pb.AckEcho{
        Code: 2,
        Data: "22222222222222222",
      }
      c.ProtoBuf(http.StatusOK, r1)
    })
    engine.Run(":8889")
  }
}

**Comment by ayamzh** [comment]
@gqcn 用起来大概就是这么个意思，可以再框架里内置protoc-gen-go  可以用gf命令编译proto文件

**Comment by gqcn** [comment]
@ayamzh OK. 我大概明白你的意思了，这个gf目前应该是支持的，通过`r.Parse`即可将请求参数转换为pb协议对象，你可以试试。不过proto文件生成pb协议对象是需要通过第三方二进制工具来实现，独立使用。

**Comment by ayamzh** [comment]
@gqcn 强哥 能在官方文档增加一个 接收客户端发来的pb和输出给客户端pb的示例么

**Comment by gqcn** [comment]
@ayamzh 你把proto文件贴上来。

**Comment by ayamzh** [comment]
```
syntax = "proto3";
package pb;
option go_package = ".;pb";
message HelloRequest{
    string Hello = 1;
}

message HelloResponse{
    uint32 Code = 1;
    string Hello = 2;
}

```

**Comment by ayamzh** [comment]
@gqcn

**Comment by housemecn** [comment]
> @ayamzh 你把proto文件贴上来。

期待哦

**Comment by houseme** [comment]
https://github.com/gogf/gf/issues/1164
