### ISSUE TITLE
自从升级到 gf 1.14.3 以上（包括）后，先用findOne()查出对象，然后调用Update()方法就报错。

### ISSUE THREAD

**Issue by arden** [gogf/gf#1022]
从gf 1.14.3 版本开始，我下面的代码在 userLottery.Update()方法的时候就报错了，以前的版本一直是正常的，这个bug很严重，gf一升级到新版本就出现了严重致命的错误。

```
    userLottery, err := user_lottery.Model.FindOne("lid = ? and uid = ?", lid, uid)
    if err != nil {
	glog.Error(err)
	continue
    }
    userLottery.Award = award
    userLottery.IsAward = 1
    _, err := userLottery.Update()
    if err != nil {
	glog.Error(err.Error())
	return
    }

```

2020-11-26 15:17:44.323 [ERRO] [  0 ms] [default] UPDATE `c_user_lottery` SET `id`=548958086,`is_award`=1,`award`=0,`qrcode_path`='',`type`=0,`code`='',`uid`=52242830,`lid`=4308137,`is_address`=0,`time`=1606370318 WHERE `id` IN (548958086)
Error: sql: expected 11 arguments, got 12 
Stack:
1.  github.com/gogf/gf/database/gdb.(*Core).writeSqlToLogger
    /data/dev/gopath/pkg/mod/github.com/gogf/gf@v1.14.3/database/gdb/gdb_core.go:814
2.  github.com/gogf/gf/database/gdb.(*Core).DoExec
    /data/dev/gopath/pkg/mod/github.com/gogf/gf@v1.14.3/database/gdb/gdb_core.go:110
3.  github.com/gogf/gf/database/gdb.(*Core).DoUpdate
    /data/dev/gopath/pkg/mod/github.com/gogf/gf@v1.14.3/database/gdb/gdb_core.go:721
4.  github.com/gogf/gf/database/gdb.(*Model).Update
    /data/dev/gopath/pkg/mod/github.com/gogf/gf@v1.14.3/database/gdb/gdb_model_update.go:85
5.  open-lottery/app/model/user_lottery.(*Entity).Update
    /data/webapp/open/open-lottery/app/model/user_lottery/user_lottery_entity.go:60
6.  open-lottery/app/service/lottery_service.UpdateOneAwardUserStatus
    /data/webapp/open/open-lottery/app/service/lottery_service/open_lottery.go:148
7.  open-lottery/app/service/lottery_service.UpdateAwardUserStatus
    /data/webapp/open/open-lottery/app/service/lottery_service/open_lottery.go:200
8.  open-lottery/app/open.(*OpenLottery).OpenRandAwardUsers
    /data/webapp/open/open-lottery/app/open/open_lottery_algorithm_rand.go:35
9.  open-lottery/app/open.(*OpenLottery).Open
    /data/webapp/open/open-lottery/app/open/open_lottery.go:205
10. open-lottery/app/open.(*OpenLottery).Start
    /data/webapp/open/open-lottery/app/open/open_lottery.go:106

2020-11-26 15:17:44.324 [ERRO] /data/webapp/open/open-lottery/app/service/lottery_service/open_lottery.go:150: sql: expected 11 arguments, got 12, UPDATE `c_user_lottery` SET `id`=548958086,`is_award`=1,`award`=0,`qrcode_path`='',`type`=0,`code`='',`uid`=52242830,`lid`=4308137,`is_address`=0,`time`=1606370318 WHERE `id` IN (548958086)
Stack:
1.  open-lottery/app/service/lottery_service.UpdateOneAwardUserStatus
    /data/webapp/open/open-lottery/app/service/lottery_service/open_lottery.go:150
2.  open-lottery/app/service/lottery_service.UpdateAwardUserStatus
    /data/webapp/open/open-lottery/app/service/lottery_service/open_lottery.go:200
3.  open-lottery/app/open.(*OpenLottery).OpenRandAwardUsers
    /data/webapp/open/open-lottery/app/open/open_lottery_algorithm_rand.go:35
4.  open-lottery/app/open.(*OpenLottery).Open
    /data/webapp/open/open-lottery/app/open/open_lottery.go:205
5.  open-lottery/app/open.(*OpenLottery).Start
    /data/webapp/open/open-lottery/app/open/open_lottery.go:106

**Comment by gqcn** [comment]
@arden 使用最新的`gf-cli`重新生成下`model`吧，这个没办法做到兼容。

**Comment by xushushun** [comment]
> @Arden 是`cli`生成的`model`有点问题，使用最新的`gf-cli`重新生成下`model`吧，这个没办法做到兼容.未来也不推荐直接用`Entity`对象的方法了，不好扩展.
好的我了解了
