### ISSUE TITLE
http: superfluous response.WriteHeader call

### ISSUE THREAD

**Issue by qinyuguang** [gogf/gf#1023]
go version: v1.15
gf verison: v1.14.5

注册prometheus路由，访问该页面时报错，原因是注册的这个路由中已经WriteHeader

@gqcn  gf的ResponseWriter是否能加个方法，标记已发过header?

代码
![image](https://user-images.githubusercontent.com/6872629/100322574-70c42200-2fff-11eb-8fe5-225b5484a62a.png)

报错
![image](https://user-images.githubusercontent.com/6872629/100322658-8df8f080-2fff-11eb-8cc6-174e5a96de99.png)

**Comment by gqcn** [comment]
@qinyuguang 直接用`r.Response.ResponseWriter`可以吗？

**Comment by qinyuguang** [comment]
@gqcn 感谢，直接用这个是没有问题的
