### ISSUE TITLE
 *ghttp.Request.Response.WriteExit("随时随地输出并退出该次请求")，不能随时随地退出 ，求支持随时随地退出

### ISSUE THREAD

**Issue by yuyu888** [gogf/gf#1025]
### 1. What version of `Go` and system type/arch are you using?
go version go1.14.4 darwin/amd64

### 2. What version of `GoFrame` are you using?
gf v1.14.0

### 3. Can this issue be reproduced with the latest release?

yes

### 4. What did you do?
https://github.com/gogf/gf/blob/master/frame/gmvc/controller.go

`    // 在init中加c.Response.WriteExit 无法即时退出

    func (c *Controller) Init(r *ghttp.Request) {
        c.Request = r
        c.Response = r.Response
        c.Server = r.Server
        c.View = NewView(r.Response)
        c.Cookie = r.Cookie
        c.Session = r.Session
        c.Response.WriteExit("不会完全退出， 还会执行后继路由中映射的方法")
    }
`

我业务层controller继承	gmvc.Controller 后业务层里继路由中映射的方法依旧会被执行

### 5. What did you expect to see?
 我希望      c.Response.WriteExit("不会完全退出， 还会执行后继路由中映射的方法") 这个执行后就能退出
最终的目的是写一个basecontroller 在init里去执行一些校验逻辑，有问题就退出， 具体业务的controller继承basecontroller；虽然路由表里的中间件也能解决这个问题
但是希望使用面向对象的方式， 把业务层的逻辑校验放在basecontroller里， 中间件只做一些系统级别的逻辑

### 6. What did you see instead?
我业务层controller继承	gmvc.Controller 后业务层里继路由中映射的方法依旧会被执行

**Comment by gqcn** [comment]
@yuyu888 
```go
c.Response.Write("xxx")
c.ExitAll()
```
