### ISSUE TITLE
🧐[Request] r.Parse/ParseForm/Parsexxx.... 增加 可选忽略的校验规则

### ISSUE THREAD

**Issue by BeanWei** [gogf/gf#1030]
### 1. What did you expect to see?
```
r.ParseForm(&data, "required", "length")
```
@gqcn 这个我觉得不是一个很通用的需求，如果gf框架不做支持的话。个人实现的话有什么好的建议吗

不行的话就只能把gf里面的这层自己挑出来做下实现了。

ps:
@gqcn 这个issue可以随时关闭，我感觉估计没有人和我有类似的这种需求了。。。

**Comment by LonelySally** [comment]
是一个接口下的某个参数字段根据不同情况做不同的验证规则吗?如果是的话可以用go struct的继承特性去覆盖
~~~
type Info struct {
	Test string `p:"test" v:"required"`
}

type Data struct {
        Info 
	Test string `p:"test"`
}
~~~

**Comment by BeanWei** [comment]
@LonelySally 感谢回复，我需要不是这种，我的结构体都是自动生成的，所以需要能按照设定的条件去选择性的做检验。

**Comment by BeanWei** [comment]
@LonelySally 我可以说下我现在做的场景，一个low code的应用，controller dao model service都是由前台设计表单后生成的。整个应用的core层已经差不多了，现在在做工作流，它是可插拔的，所以我才提出上面的这种需求，工作流在不同的阶段类似于分布表单，所以想把检验给分开但是又不干预原来的model结构

**Comment by LonelySally** [comment]
> @LonelySally 我可以说下我现在做的场景，一个low code的应用，controller dao model service都是由前台设计表单后生成的。整个应用的core层已经差不多了，现在在做工作流，它是可插拔的，所以我才提出上面的这种需求，工作流在不同的阶段类似于分布表单，所以想把检验给分开但是又不干预原来的model结构

如果我没理解错的话,那只能在自动生成的地方做tag动态化配置.

**Comment by BeanWei** [comment]
> > @LonelySally 我可以说下我现在做的场景，一个low code的应用，controller dao model service都是由前台设计表单后生成的。整个应用的core层已经差不多了，现在在做工作流，它是可插拔的，所以我才提出上面的这种需求，工作流在不同的阶段类似于分布表单，所以想把检验给分开但是又不干预原来的model结构
> 
> 如果我没理解错的话,那只能在自动生成的地方做tag动态化配置.还有一种办法就是用自己实现一个gvalid的上层封装(独立使用Check方法),去解析tag然后循环规则,如果是忽略的`continue`掉.


@LonelySally  所以我才说 `不行的话就只能把gf里面的这层自己挑出来做下实现了。`  我只能把gvalid那层的解析自行处理，

**Comment by gqcn** [comment]
@BeanWei @LonelySally 这种需求确实不通用。`ParseXXX`的校验都是通过结构体标签实现的，都是实现约定好的，当然你也可以`GetStruct/GetMap`之后动态给定参数去校验，校验规则可以动态设置的，具体可以看下文档上的`gvalid`章节。

**Comment by BeanWei** [comment]
> @BeanWei @LonelySally 这种需求确实不通用。`ParseXXX`的校验都是通过结构体标签实现的，都是实现约定好的，当然你也可以`GetStruct/GetMap`之后动态给定参数去校验，校验规则可以动态设置的，具体可以看下文档上的`gvalid`章节。

@gqcn  好的了解，感谢！ @gqcn  @LonelySally
