### ISSUE TITLE
探讨入参是否能被自动类型转换

### ISSUE THREAD

**Issue by loyipsing** [gogf/gf#1032]
type GetItemReq struct {
	ItemId int `v:"item_id@integer|required|min:1"`
}

入参 "item_id":"11.1"

不被拦截，且 GetItemReq.ItemId = 11 (被自动转换了)

**Comment by LonelySally** [comment]
问题不是出在规则上而是类型.ItemId为int,当params解析到ItemId上时会被强制转换成int,这个时候11.1已经变成了11.

**Comment by loyipsing** [comment]
> 问题不是出在规则上而是类型.ItemId为int,当params解析到ItemId上时会被强制转换成int,这个时候11.1已经变成了11.解决办法:int改为string或者interface,在使用的时候做转换,另外required验证对于数值类型要生效必须使用指针,例如*int .

十分感谢，已经找到文档里面关于这个的说明了

另外想讨论一下，其实为什么gf要做这层转换，感觉有点违背了静态类型语言的定义

**Comment by loyipsing** [comment]
是否能在GetRequestStruct
![image](https://user-images.githubusercontent.com/34824811/100828783-dcdcd500-349a-11eb-87de-6a03f0c1d88f.png)
这个地方替换掉gconv.Struct，比如说来个gconv.StructStrict，通过server去配置这个转换方法的严格模式

client输入的参数其实不应该被改变，如果涉及到金钱交易的话，可能会有风险

**Comment by LonelySally** [comment]
> > 问题不是出在规则上而是类型.ItemId为int,当params解析到ItemId上时会被强制转换成int,这个时候11.1已经变成了11.解决办法:int改为string或者interface,在使用的时候做转换,另外required验证对于数值类型要生效必须使用指针,例如*int .
> 
> 十分感谢，已经找到文档里面关于这个的说明了
> 
> 另外想讨论一下，其实为什么gf要做这层转换，感觉有点违背了静态类型语言的定义

不是gf要转换而是取决于定义的类型,假设传入是string设定类型是int,直接赋值上去直接panic.要想原样保留直接用interface.是你绕弯路了.

**Comment by gqcn** [comment]
@loyipsing 哈哈，感谢 @LonelySally ！正如所说，就是这样的。😅
