### ISSUE TITLE
只引入gjson等框架子包时，能否不运行非必要的协程？

### ISSUE THREAD

**Issue by 8923052** [gogf/gf#1034]
### 1. What version of `Go` and system type/arch are you using?

go version go1.15.5 windows/amd64

### 2. What version of `GoFrame` are you using?

1.14.5
目前主要用了gjson包，gjson非常好用

### 3. Can this issue be reproduced with the latest release?

yes

### 4. What did you do?

```
package main

import (
	"fmt"
	_ "github.com/gogf/gf/encoding/gjson"
	"net/http"
	_ "net/http/pprof"
)

func main() {
	srv := &http.Server{Addr: ":8800", Handler: nil}
	fmt.Println(srv.ListenAndServe())
}
```

### 5. What did you expect to see?
http://127.0.0.1:8800/debug/pprof/goroutine?debug=1

```
1 @ 0x2ddb1a 0x2a5d1a 0x2a5ab5 0x4adc36 0x3116a1
#	0x4adc35	github.com/gogf/gf/util/grand.asyncProducingRandomBufferBytesLoop+0x75	D:/server/www/share/golang/pkg/mod/github.com/gogf/gf@v1.14.5/util/grand/grand_buffer.go:45

1 @ 0x2ddb1a 0x2a69fa 0x2a662b 0x5207d0 0x3116a1
#	0x5207cf	github.com/gogf/gf/os/gtimer.(*wheel).start.func1+0x6f	D:/server/www/share/golang/pkg/mod/github.com/gogf/gf@v1.14.5/os/gtimer/gtimer_loop.go:21

……

实际项目中还会有
github.com/gogf/gf@v1.14.5/container/gqueue/gqueue.go:72
github.com/gogf/gf@v1.14.5/container/gqueue/gqueue.go:113
github.com/gogf/gf@v1.14.5/os/gfsnotify/gfsnotify_watcher_loop.go:18
```

### 6. What did you see instead?

只是引入了gjson包，但却开启了几个看起来gjson本身不需要的，长时间运行的协程（是否gjson必须？），是否能在只引入框架子包时，不去初始化非必要的协程或者内存。

**Comment by gqcn** [comment]
@8923052 你好。一个`goroutine`原因是`gjson`会依赖`gstr`字符串包，字符串包中有个`Shuffle`方法会依赖`grand`包的随机数生成。`grand`采用了缓冲区的设计来提高随机数读取效率，因此会有一个异步的`goroutine`队列不断通过随机数函数读取数据，写入到缓冲区中，另一边不断从缓存区读取数据，按照4字节为单位，读一个补一个。另一个`goroutine`没有深究，不过你的这两个goroutine都是提高效率所需要的，并且都非常轻量级，会给你的项目带来性能上的提升。
