### ISSUE TITLE
这个官方示例为什么跑不通呢？

### ISSUE THREAD

**Issue by xiaxichen** [gogf/gf#1036]
github.com/gogf/gf v1.14.5
go version 1.14.10

demo address https://goframe.org/util/gconv/unmarshalvalue

61 line
```
err := gconv.Struct(p1.Marshal(), &p2) 
```
error : panic: convert params to map failed: [9 0 210 99 72 136 49 50 51]

**Comment by sanrentai** [comment]
感觉p2的声明有问题，改成这样就可以了 p2 := Pkg{}

**Comment by xiaxichen** [comment]
> 感觉p2的声明有问题，改成这样就可以了 p2 := Pkg{}

ok了谢谢老哥~

**Comment by gqcn** [comment]
@sanrentai @xiaxichen 其实这是一个BUG😅，单测没有覆盖到，我花了3个小时修复了，下个版本发布。
