### ISSUE TITLE
模板解析tpl里的中文，gfile 生成出来是乱码

### ISSUE THREAD

**Issue by 15951836388** [gogf/gf#1037]
![image](https://user-images.githubusercontent.com/14047483/101116189-949aef80-361f-11eb-9792-995d8bc8932f.png)

tpl里
![image](https://user-images.githubusercontent.com/14047483/101116237-a8465600-361f-11eb-941b-79cd2aa6e0b4.png)

生成的
![image](https://user-images.githubusercontent.com/14047483/101116258-b6947200-361f-11eb-9385-cd87e2843381.png)

**Comment by gqcn** [comment]
@15951836388 Golang统一都是UTF-8编码，你检查tpl模板文件内容的编码是什么？如果仍旧有问题，提交可复现问题的最小代码。

**Comment by 15951836388** [comment]
我的测试是，只要tpl里加了中文， gview.Parse 出来的的数据，就不是utf8了。

判断方法

func ValidUTF8(buf []byte) bool {
	nBytes := 0
	for i := 0; i < len(buf); i++ {
		if nBytes == 0 {
			if (buf[i] & 0x80) != 0 { //与操作之后不为0，说明首位为1
				for (buf[i] & 0x80) != 0 {
					buf[i] <<= 1 //左移一位
					nBytes++     //记录字符共占几个字节
				}

				if nBytes < 2 || nBytes > 6 { //因为UTF8编码单字符最多不超过6个字节
					return false
				}

				nBytes-- //减掉首字节的一个计数
			}
		} else { //处理多字节字符
			if buf[i]&0xc0 != 0x80 { //判断多字节后面的字节是否是10开头
				return false
			}
			nBytes--
		}
	}
	return nBytes == 0
}

**Comment by gqcn** [comment]
@15951836388 我试了一下没复现你所说的问题。

**Comment by 15951836388** [comment]
[test2.zip](https://github.com/gogf/gf/files/5650167/test2.zip)
上传demo了

**Comment by gqcn** [comment]
> [test2.zip](https://github.com/gogf/gf/files/5650167/test2.zip)
> 上传demo了

看了，你的文件编码是GBK，所以使用UTF-8编码转换后就乱码了，你改下文件编码就好了。
