### ISSUE TITLE
[ghttp]  Parse 方法目前无法解析基本数据类型外的拓展类型

### ISSUE THREAD

**Issue by FWangZil** [gogf/gf#1038]
### 1. What version of `Go` and system type/arch are you using?

go version go1.15.5 darwin/amd64

### 2. What version of `GoFrame` are you using?

v1.14.5

### 3. Can this issue be reproduced with the latest release?

yes

### 4. What did you do?

1.定义了一个结构体，其中有一个 decimal.Decimal 的成员。
2.通过 Http Post 方法 传入 json 
3.ghttp.Parse 解析失败

### 5. What did you expect to see?

请求被顺利处理

### 6. What did you see instead?

Error: reflect.Value.Convert: value of type float64 cannot be converted to type decimal.Decimal

**Comment by gqcn** [comment]
@FWangZil `decimal.Decimal`是自己定义还是用的第三方包的类型。非基本类型只要实现了`UnmashalValue`或者`UnmashalText`都可以被成功转换，你看看这个类型有没实现。

**Comment by FWangZil** [comment]
> @FWangZil `decimal.Decimal`是自己定义还是用的第三方包的类型。非基本类型只要实现了`UnmashalValue`或者`UnmashalText`都可以被成功转换，你看看这个类型有没实现。

明白了谢谢。

**Comment by FWangZil** [comment]
> @FWangZil `decimal.Decimal`是自己定义还是用的第三方包的类型。非基本类型只要实现了`UnmashalValue`或者`UnmashalText`都可以被成功转换，你看看这个类型有没实现。

不好意思请问这两个方法的函数签名该是什么样子的呢？

**Comment by gqcn** [comment]
> > @FWangZil `decimal.Decimal`是自己定义还是用的第三方包的类型。非基本类型只要实现了`UnmashalValue`或者`UnmashalText`都可以被成功转换，你看看这个类型有没实现。
> 
> 不好意思请问这两个方法的函数签名该是什么样子的呢？

```go
// apiUnmarshalValue is the interface for custom defined types customizing value assignment.
// Note that only pointer can implement interface apiUnmarshalValue.
type apiUnmarshalValue interface {
	UnmarshalValue(interface{}) error
}

// apiUnmarshalText is the interface for custom defined types customizing value assignment.
// Note that only pointer can implement interface apiUnmarshalText.
type apiUnmarshalText interface {
	UnmarshalText(text []byte) error
}
```

**Comment by FWangZil** [comment]
> ```go
> interface
> ```

好的感谢。
