### ISSUE TITLE
ORM数据库insert常量、计算及函数类型的写法问题[MYSQL]

### ISSUE THREAD

**Issue by mopsky** [gogf/gf#1041]
```
data := g.Map{
		"column_str": "test",
		"column_int" : 100,
		"column_time" : "now()",
		"column_calc" : "column_int + 1 - column...",
		......
	}

Table("test").Insert(data)
```

类似这种时间常量now()，还有计算其他字段的 a + b - c，及其他的函数这些要在gmap中如何体现，用字符串测试了肯定不行

**Comment by gqcn** [comment]
@mopsky 增加了新功能`gdb.Raw`，目前在develop测试中，近期发布：

![image](https://user-images.githubusercontent.com/26347176/101519193-d9c37680-39bd-11eb-93e6-ec1df8a811db.png)

**Comment by mopsky** [comment]
@gqcn 哎呀，太好了，谢谢

**Comment by mopsky** [comment]
@gqcn 老大，大概什么时候发布，急着用，谢谢

**Comment by gqcn** [comment]
@mopsky 你可以用`master`分支， `go get -u github.com/gogf/gf@master`。
