### ISSUE TITLE
建议gf实现web端口复用，以便于支持多种传输协议

### ISSUE THREAD

**Issue by Jerry-fmcheng** [gogf/gf#1043]
1、版本：
go version 1.11.4
gf version 1.13.1

2、需求描述
gf能否实现web端口复用，以便于在同一个端口上面同时支持rpc、http/websocket等协议。
业界已有成熟的方案，可以参考：
1、github.com/soheilhy/cmux
2、github.com/grpc-ecosystem/grpc-gateway

针对第一个，可以和gin web框架相结合，而针对于gf框架，当前似乎无法注入自定义的net.Listener对象。
请评估一下实现的可能性和价值。

**Comment by Jerry-fmcheng** [comment]
cmux demo链接：https://github.com/soheilhy/cmux
其实现思路：
1、启动tcp监听，不管是http、websocket、rpc、gRPC都是基于tcp之上的
2、调用CMux.Match()根据不同的规则匹配payload中的信息，从而将请求分发到不同协议的处理逻辑中去
3、针对http与gin结合的处理，可以参考：https://www.v2ex.com/t/610233

这个推荐使用到gf框架中。

**Comment by gqcn** [comment]
看了下原理挺简单的，不过感觉使用场景不是很多，大家可以一起谈谈想法。

**Comment by Jerry-fmcheng** [comment]
看了下ghttp包代码，目前是通过getNetListner()方法拿到net.Listener对象，如果能从外部注入这个net.Listener对象，应该就可以实现端口复用了。不知道分析的对不对？
// getNetListener retrieves and returns the wrapped net.Listener.
func (s *gracefulServer) getNetListener() (net.Listener, error) {
	var ln net.Listener
	var err error
	if s.fd > 0 {
		f := os.NewFile(s.fd, "")
		ln, err = net.FileListener(f)
		if err != nil {
			err = fmt.Errorf("%d: net.FileListener error: %v", gproc.Pid(), err)
			return nil, err
		}
	} else {
		ln, err = net.Listen("tcp", s.httpServer.Addr)
		if err != nil {
			err = fmt.Errorf("%d: net.Listen error: %v", gproc.Pid(), err)
		}
	}
	return ln, err
}

**Comment by gqcn** [comment]
> 看了下ghttp包代码，目前是通过getNetListner()方法拿到net.Listener对象，如果能从外部注入这个net.Listener对象，应该就可以实现端口复用了。不知道分析的对不对？
> 
> ```go
> // getNetListener retrieves and returns the wrapped net.Listener.
> func (s *gracefulServer) getNetListener() (net.Listener, error) {
> 	var ln net.Listener
> 	var err error
> 	if s.fd > 0 {
> 		f := os.NewFile(s.fd, "")
> 		ln, err = net.FileListener(f)
> 		if err != nil {
> 			err = fmt.Errorf("%d: net.FileListener error: %v", gproc.Pid(), err)
> 			return nil, err
> 		}
> 	} else {
> 		ln, err = net.Listen("tcp", s.httpServer.Addr)
> 		if err != nil {
> 			err = fmt.Errorf("%d: net.Listen error: %v", gproc.Pid(), err)
> 		}
> 	}
> 	return ln, err
> }
> ```

好像不需要这么麻烦，我看v2ex有小伙伴写了个例子：
```go
func main() {
	http.ListenAndServeTLS(port, "server.crt", "server.key",
		http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if r.ProtoMajor != 2 {
				mux.ServeHTTP(w, r)
				return
			}
			if strings.Contains(
				r.Header.Get("Content-Type"), "application/grpc",
			) {
				grpcServer.ServeHTTP(w, r) // gRPC Server
				return
			}

			mux.ServeHTTP(w, r)
			return
		}),
	)
}
```

**Comment by Jerry-fmcheng** [comment]
如果能把gRPC引入进来那就太好了，这样的话我们的服务对外就走http，对内就走rpc，我相信会有很多小伙伴有这样的诉求。

**Comment by dabuge** [comment]
有需求，我们现在 grpc 用的是其他的框架，gf 专门做 web相关的项目

**Comment by 15951836388** [comment]
确实也有 端口 复用的需求

gf估计不会支持

暂时用https://github.com/soheilhy/cmux 来实现吧

**Comment by ruanlianjun** [comment]
有木有实现的demo可以给看一下吗

**Comment by housemecn** [comment]
有过实战的经验的兄弟，来提一个pr吧

**Comment by houseme** [comment]
https://github.com/gogf/gf/pull/1683
