### ISSUE TITLE
g.Cfg()配置管理的CPU占用问题

### ISSUE THREAD

**Issue by mopsky** [gogf/gf#1048]
```
package main

import (
	"github.com/gogf/gf/frame/g"
	"time"
)

func main() {
	g.Cfg()
	for {
		time.Sleep(time.Hour)
	}
}
```

为什么使用了g.Cfg()配置模块，CPU占用在0.7%-1%左右，如果去掉，基本不占用CPU

**Comment by gqcn** [comment]
@mopsky 因为框架内部有个比较核心的`gtimer`定时器在运行，时间轮每`50ms`运行一次，我本地会占用`0.3%`左右的CPU。嗯，我调长一些到`100ms`吧。

**Comment by mopsky** [comment]
@gqcn 这个gtimer用来做什么的，监控配置文件更新？能显式的关掉么

**Comment by gqcn** [comment]
> @gqcn 这个gtimer用来做什么的，监控配置文件更新？能显式的关掉么

有几个地方在用，比如缓存模块，并且是隐式初始化创建的，不能显示关掉，新版本我会把定时器间隔调小点。

**Comment by mopsky** [comment]
@gqcn 是不是在master主干已经改了，我刚刚拉了master分支，cpu还是差不多，自己做了下测试，就算改到500ms，CPU也会有0.3%的占用(当然根据机器的配置不同差异会明显了)，这个比mysqld,httpd,nginx静止状态下耗的CPU还高，感觉有些不太合理，我只是进程初始化的时候读取下配置，根本不需要去浪费这轮巡的CPU，是不是底层设计的有些不合理

**Comment by gqcn** [comment]
> @gqcn 是不是在master主干已经改了，我刚刚拉了master分支，cpu还是差不多，自己做了下测试，就算改到500ms，CPU也会有0.3%的占用(当然根据机器的配置不同差异会明显了)，这个比mysqld,httpd,nginx静止状态下耗的CPU还高，感觉有些不太合理，我只是进程初始化的时候读取下配置，根本不需要去浪费这轮巡的CPU，是不是底层设计的有些不合理

其实具体CPU占用在这个地方`time.NewTicker`：
![image](https://user-images.githubusercontent.com/26347176/102206188-2c91b680-3f07-11eb-8cbd-9e4a792f4f3f.png)

有的模块依赖定时器，并且是在程序启动的时候隐式初始化的，以保证在运行时提供更好的性能。不用太在意这么点CPU占用。
