### ISSUE TITLE
orm 能否加下 decimal 支持

### ISSUE THREAD

**Issue by shengdoushi** [gogf/gf#1049]
毕竟金钱什么的， 好些是用 decimal 设计的，在计算时， 用 float64 加减乘除不太好

**Comment by mark-jiang-gp** [comment]
金钱还是应该存 int

**Comment by gqcn** [comment]
> 毕竟金钱什么的， 好些是用 decimal 设计的，在计算时， 用 float64 加减乘除不太好

数据库的`decimal`类型转换为`Golang`的`float64`类型有什么问题吗？或者有什么好建议吗？

**Comment by shengdoushi** [comment]
> > 毕竟金钱什么的， 好些是用 decimal 设计的，在计算时， 用 float64 加减乘除不太好
> 
> 数据库的`decimal`类型转换为`Golang`的`float64`类型有什么问题吗？或者有什么好建议吗？

可以在 gf 工具中添加下参数，让生成的model文件中 decimal 用 string 类型表示。 比如 

 gf gen model app/model/ --decimalAsString -t tablename

**Comment by shengdoushi** [comment]
> > 毕竟金钱什么的， 好些是用 decimal 设计的，在计算时， 用 float64 加减乘除不太好
> 
> 数据库的`decimal`类型转换为`Golang`的`float64`类型有什么问题吗？或者有什么好建议吗？

数据库的 decimal 转为 float64, 倒没什么问题。 现在我在go中是先将 float64 转成 decimal(第三方库的），然后做计算。

像 gorm 他就可以用 decimal 直接表示:

```
type User struct {
Money decimal.Decimal
}
```

**Comment by mopsky** [comment]
我们一般涉及金钱的，数据库都设计成int，单位为厘 或 分，这样比较方便

**Comment by gqcn** [comment]
@shengdoushi 好的，我先排个期，研究一下哈

**Comment by gqcn** [comment]
> 我们一般涉及金钱的，数据库都设计成int，单位为厘 或 分，这样比较方便

你是对的。不过`float64`的精度确实是个问题，我们也可以想办法改进一下。

**Comment by shengdoushi** [comment]
> 我们一般涉及金钱的，数据库都设计成int，单位为厘 或 分，这样比较方便

是的 目前数据库设计上基本上对金额设计分成两派： 存整数分， 或存decimal.   两派都有不少人

**Comment by sanrentai** [comment]
不涉及计算的用float64简单粗暴。涉及计算就麻烦了
1是数据库存整数分，程序在显示时做转换。2是数据库存decimal，程序用float64需要用第三方库做运算

**Comment by hinego** [comment]
> 我们一般涉及金钱的，数据库都设计成int，单位为厘 或 分，这样比较方便

数字货币的最大值都是 int256 （智能合约的默认值）

int也存不下呀 除了decimal都没办法
