### ISSUE TITLE
php代码转Go Frame，所有逻辑都相同，但最后输出值不同，哪里问题？

### ISSUE THREAD

**Issue by qq1196** [gogf/gf#105]
$data ="中国";
$dict="no";
$key = md5($dict);
    $x  = 0;
    $len = strlen($data);
    $l  = strlen($key);
    $char = $str = '';
    for($i = 0;$i < $len;++$i) {
        if($x == $l) {
            $x = 0;
        }
        $char .= $key{$x};
        $x++;
    }
    for($i = 0;$i < $len;++$i) {
        $str .= chr(ord(substr($data, $i, 1)) + (ord(substr($char, $i, 1))) % 256);
    }    	
	$result = base64_encode($str);
echo $result;
最终输出值是  Gx4OGP30

Go Frame代码  最终输出值是  xJvEnsSOxJjDvcO0   不知道问题出在哪了，请作者指导一下，谢谢。

package main

import (
	"fmt"
	"github.com/gogf/gf/g/crypto/gmd5"
	"github.com/gogf/gf/g/encoding/gbase64"
	"github.com/gogf/gf/g/text/gstr"
)
func main() {
	data := "中国"
	dict := "no"
	key := gmd5.EncryptString(dict)
	x := 0
	lenb := len(data)
	l := len(key)
	char := ""
	strb := ""
	for i := 0; i < lenb; i++ {
		if x == l {
			x = 0
		}
		char += key[x : x+1]
		x++
	}
	for i := 0; i < lenb; i++ {
		strb +=gstr.Chr((gstr.Ord(data[i:i+1]) + gstr.Ord(char[i:i+1]) % 256) )
	}
	result := gbase64.Encode(strb)
	fmt.Println(result)
}

**Comment by johngcn** [comment]
@qq1196 你逐步调试一下看各个方法返回的值是否是一致的，特别是`md5`。

**Comment by qq1196** [comment]
@johngcn 
md5是一致的，gstr.Ord也是一致的，
这一步 gstr.Chr   这个不一致，

**Comment by johngcn** [comment]
@qq1196 感谢反馈，这有点小问题，已经修复，下一个小版本发布。

**Comment by johngcn** [comment]
@qq1196 已发布，请更新最新框架代码再试试。
