### ISSUE TITLE
If the middleware process orders can be controlled by users?

### ISSUE THREAD

**Issue by kim709394** [gogf/gf#1050]
### 1. What version of `Go` and system type/arch are you using?
v1.14.5

go 1.15, windows10

### 2. What version of `GoFrame` are you using?

v1.14.5
### 3. Can this issue be reproduced with the latest release?
yes

### 4. What did you do?

i used middlewares ,  but i  want to control their process orders by myself,   would it come true?

**Comment by gqcn** [comment]
@kim709394 中间件的执行顺序请参考文档：https://goframe.org/net/ghttp/router/middleware 你可以通过注册顺序来控制中间件执行顺序。
