### ISSUE TITLE
no 405 even though a request method no match

### ISSUE THREAD

**Issue by kim709394** [gogf/gf#1052]
### 1. What version of `Go` and system type/arch are you using?
go 1.15

go 1.15    windows10

### 2. What version of `GoFrame` are you using?
v1.14.5

### 3. Can this issue be reproduced with the latest release?

yes

### 4. What did you do?

i runed a  http server ,which has a "POST" method api , but i request my server by method of "GET" ,my server return "404 not found" .It should return 405

**Comment by kim709394** [comment]
my server return a http code "200"  even though a request method no match if there are middlewares inside the server

**Comment by gqcn** [comment]
@gqcn That is really .. a good improvement proposal, but not urgent.
