### ISSUE TITLE
gf 1.14.5 版本GetQueryMap 方法失效

### ISSUE THREAD

**Issue by mir355** [gogf/gf#1054]
### 1. What version of `Go` and system type/arch are you using?
centos 7

### 2. What version of `GoFrame` are you using?

老版本 v1.13.7
新版本 v1.14.5

今日测试功能升级了gf 版本为v1.14.5，发现get  ghttp 的 GetQueryMap方法无法获取请求参数。
代码中一直使用 ghttp 的 GetQueryMap方法获取请求参数。
通过新版本的  GetRaw 及 GetRequestMap 方法确认get 参数已经被正确传送本并可以解析，但是 GetQueryMap 返回的则是空。

**Comment by gqcn** [comment]
@mir355 `GetQueryMap`仅用于获取URL中的Query String参数。
