### ISSUE TITLE
how to load multiple config file? 怎么加载多个配置文件?

### ISSUE THREAD

**Issue by Golong-me** [gogf/gf#1057]
how to load multiple config file in gf?
怎么加载多个配置文件?

until now，i found gf only can load one config，and not find related content in doc
目前我发现，只能加载一个配置文件，在官方文档里也没有发现

**Comment by Golong-me** [comment]
我的意思是，当config.toml的配置多了起来，不好管理。
假如我现在想单独拆分MySQL的配置文件出来。
官方提供的  g.cfg("MySQL")这种方式，并不能解决，因为使用了这个，config便失效了

**Comment by gqcn** [comment]
> 我的意思是，当config.toml的配置多了起来，不好管理。
> 假如我现在想单独拆分MySQL的配置文件出来。
> 官方提供的 g.cfg("MySQL")这种方式，并不能解决，因为使用了这个，config便失效了

你确定 `官方提供的 g.cfg("MySQL")这种方式，并不能解决，因为使用了这个，config便失效了` 吗？你尝试过吗？

**Comment by Golong-me** [comment]
@gqcn  
谢谢你的提醒,经过了再次测试,发现了toml格式的是可以的,但是yaml格式不行,

`	g.Cfg().SetFileName("config.yaml")
	//**去掉yaml后缀也不行**,此时会报Stack错误
	fmt.Println(g.Cfg("mysql.yaml").Get("aa"))`

![image](https://user-images.githubusercontent.com/72813193/102011534-b5a8c200-3d3c-11eb-9afe-c250611e6e27.png)

**Comment by Golong-me** [comment]
> > 我的意思是，当config.toml的配置多了起来，不好管理。
> > 假如我现在想单独拆分MySQL的配置文件出来。
> > 官方提供的 g.cfg("MySQL")这种方式，并不能解决，因为使用了这个，config便失效了
> 
> 你确定 `官方提供的 g.cfg("MySQL")这种方式，并不能解决，因为使用了这个，config便失效了` 吗？你尝试过吗？

经过了再次的测试,我发现,TOML格式可以,但是**yaml格式不行**

```
	//cfg指定的name是yaml格式的时候,获取不到文件
	//去掉.yaml后缀也是一样
	g.Cfg("mysql.yaml").Get("aa")
```
我的目录
![image](https://user-images.githubusercontent.com/72813193/102015734-383d7b80-3d55-11eb-84b0-1fe8ad8c42ac.png)

**Comment by gqcn** [comment]
> > > 我的意思是，当config.toml的配置多了起来，不好管理。
> > > 假如我现在想单独拆分MySQL的配置文件出来。
> > > 官方提供的 g.cfg("MySQL")这种方式，并不能解决，因为使用了这个，config便失效了
> > 
> > 
> > 你确定 `官方提供的 g.cfg("MySQL")这种方式，并不能解决，因为使用了这个，config便失效了` 吗？你尝试过吗？
> 
> 经过了再次的测试,我发现,TOML格式可以,但是**yaml格式不行**
> 
> ```
> 	//cfg指定的name是yaml格式的时候,获取不到文件
> 	//去掉.yaml后缀也是一样
> 	g.Cfg("mysql.yaml").Get("aa")
> ```
> 
> 我的目录
> ![image](https://user-images.githubusercontent.com/72813193/102015734-383d7b80-3d55-11eb-84b0-1fe8ad8c42ac.png)

我明白了，我来改进一下。

**Comment by gOODiDEA2002** [comment]
目录下有config.yaml,config-game.yaml,config-login.yaml, 如何能同时加载 config.yaml 和 config-game.yaml?

**Comment by LanceAdd** [comment]
> 目录下有config.yaml,config-game.yaml,config-login.yaml, 如何能同时加载 config.yaml 和 config-game.yaml?

`config.yaml`可以直接g.Cfg()或者g.Cfg("config"), `config-game.yaml`就直接g.Cfg("config-game")就行了
