### ISSUE TITLE
如何在执行更新操作的时候,如何自动清空缓存?How do I automatically clear the cache when I perform an update operation?

### ISSUE THREAD

**Issue by Golong-me** [gogf/gf#1059]
如何在每次执行update的时候自动清空缓存?而无需写Cache(-1,"xxx")

希望数据库能支持全局查询缓存.和mybatils的二级缓存一样.在执行select的时候会自动缓存
在执行update的时候会自动让缓存失效

```

    // 执行2次查询并将查询结果缓存1小时，并可执行缓存名称(可选)
    for i := 0; i < 2; i++ {
        r, _ := db.Table("user").Cache(time.Hour, "vip-user").Where("uid", 1).One()
        g.Log().Print(r.Map())
    }

    // 执行更新操作，并清理指定名称的查询缓存
    _, err := db.Table("user").Cache(-1, "vip-user").Data(gdb.Map{"name": "smith"}).Where("uid", 1).Update()
    if err != nil {
        g.Log().Fatal(err)
    }

```

**Comment by LonelySally** [comment]
链式的Cache的key是非必填,默认生成规则是cacheKey = sql + ", @PARAMS:" + gconv.String(args).在这里做文章.

**Comment by gqcn** [comment]
@Golong-me 给一个`Cache`链式方法的目的就是为了让开发自己定义名称来方便管理缓存，为保证业务数据的一致性，并不是所有查询都需要缓存的。如果你确有这样的需求，你可以按照 @LonelySally 的建议来自己实现缓存管理，可以自定义实现一个驱动类型对象，驱动编写参考文档。
