### ISSUE TITLE
GoLand IDE: Unresolved reference 'Ctx'

### ISSUE THREAD

**Issue by ApowersoftDev** [gogf/gf#1062]
### 1. What version of `Go` and system type/arch are you using?

go version
go version go1.15 darwin/amd64

### 2. What version of `GoFrame` are you using?

GoFrame CLI Tool v1.14.5, https://goframe.org
Install Path: /usr/local/bin/gf
Build Detail:
  Go Version:  go1.15.5
  GF Version:  v1.14.5
  Git Commit:  e5b914deae021f465f018cdd164b4fcf8cd4d4f6
  Build Time:  2020-12-14 23:06:09

### 3. Can this issue be reproduced with the latest release?
Yes

### 4. What did you do?

```golang
func (m *arModel) Ctx(ctx context.Context) *arModel {
	return &arModel{m.M.Ctx(ctx)}
}
// GoLand IDE shows an error: Unresolved reference 'Ctx'
```
Here is the screenshot: https://tinyurl.com/y6wzcumw

### 5. What did you expect to see?
Fix this error.

**Comment by preey-wang** [comment]
这个问题怎么解决的呢?

**Comment by gqcn** [comment]
@ApowersoftDev @preey-wang 这是因为`cli`生成的代码和项目使用的`gf`版本不一致造成的，`Ctx`是新版本增加的方法，用于传递链路跟踪信息。
