### ISSUE TITLE
gen 生成的模型代码中非链式安全的问题

### ISSUE THREAD

**Issue by Golong-me** [gogf/gf#1066]
这是我原本的做法.当id不为0.则按id查询.但ID为0.则查询全部.
但是2者的条件是相互独立的,也就是链式安全的.所以现在我需要非链式安全.
![image](https://user-images.githubusercontent.com/72813193/102196569-fb3dca00-3eb7-11eb-9d62-1aec43b06547.png)

所以我这么做了.我把Where返回的对象(链式)放到了外部,然后构建完where语句后重新放入.这种在DB方式中这是可行的(每次返回*Model).
但是生成器方式生成的模型类并不行.因为PmsCategoryDao被放到了internal包里.(后面我改了包名,但是很麻烦)
![image](https://user-images.githubusercontent.com/72813193/102196936-6daeaa00-3eb8-11eb-9590-53173d0300aa.png)

最终为了解决问题,我采用了这么做.但是这种很不方便
请问,是gen生成的模型代码有问题.还是有什么技巧我还没找到吗?
![image](https://user-images.githubusercontent.com/72813193/102197232-c0886180-3eb8-11eb-8543-3fc2c95c1164.png)

clone按道理也可以解决,但是clone返回的是*Model,并不是生成器方式生成的模型类

**Comment by gqcn** [comment]
@Golong-me 你把ORM操作返回的对象赋值给一个新的Model就可以了，不是一定要用非链式安全的做法，这里统一是链式安全的，就是不想给开发者造成混淆。
