### ISSUE TITLE
openim 分布式推送(IM)服务

### ISSUE THREAD

**Issue by xinjiayu** [gogf/gf#1067]
openim是分布式推送(IM)服务，完全基于websocket封装，围绕topic进行sub/pub 自身实现订阅管理服务，无需依赖redis

基于GF开发。

https://github.com/xinjiayu/openim

**Comment by gqcn** [comment]
@xinjiayu 感谢贡献丰富框架生态，不过请将您的案例集中提交到这里 https://github.com/gogf/gf/issues/168 ，后续我会专门整理到WIKi上。
