### ISSUE TITLE
Memory leak with gf log when benchmark

### ISSUE THREAD

**Issue by phper-chen** [gogf/gf#1069]
### 1. What version of `Go` and system type/arch are you using?
go 1.4, linux/amd64

### 2. Can this issue be reproduced with the latest release?

yes

### 3. What did you do?

After the stress test, the memory keeps rising. After removing the log function of GF, the memory leak problem disappeared

### 4. What did you expect to see?

nothing，just a bug report

**Comment by gqcn** [comment]
@phper-chen Please paste the benchmark codes along with your operation procedures that can reproduce this issue.

**Comment by phper-chen** [comment]
> @phper-chen Please paste the benchmark codes along with your operation procedures that can reproduce this issue.

We do a pressure test on the API. There are many functions in the API that use the log provided by the framework to log. If you have the opportunity to try it yourself, we will not have this problem after we changed to zap logger.

**Comment by gqcn** [comment]
@phper-chen Which GoFrame version are you using? As I know there's a memory leak bug in certain version of v1.13.x but was fixed soon.

**Comment by phper-chen** [comment]
> @phper-chen Which GoFrame version are you using? As I know there's a memory leak bug in certain version of v1.13.x but was fixed soon.

I can't remember the exact version，maybe ur new version is resolved
