### ISSUE TITLE
Support SetContext method on *ghttp.Request to intergrate with opentelementry 

### ISSUE THREAD

**Issue by isword123** [gogf/gf#1070]
### 1. What version of `Go` and system type/arch are you using?
`go 1.14, linux/amd64`

### 2. What version of `GoFrame` are you using?
v1.14.5

### 3. Can this issue be reproduced with the latest release?
yes

### 4. What did you do?
I want to use opentracing or opentelementry with goframe

### 5. What did you expect to see?
I want to implement a middleware intergrated with opentelementry, but context of `ghttp.Request` can not be assigned by generated new ctx, so when we try to begin a new tracing context like 
```
ctx := r.Context() // r is *ghttp.Request
ctx = global.TextMapPropagator().Extract(ctx, &metadataSupplier{
        metadata: metadata,
    })
```
how can we pass the new context to following handler methods?

I hope, `ghttp.Request`  can provided a public method like 
```
func (r *Request) SetContext(ctx context.Context) {
	r.context = ctx
}
```
If so, the tracing context can be passed to following handler methods

### 6. What did you see instead?
context of `ghttp.Request` can not be assigned directly, it's really hard to intergrate opentelementry with goframe, the context usage is different from others like in gRPC or other frameworks

**Comment by gqcn** [comment]
@isword123 The `ghttp.Request` is inherited from `net/http.Request`, so you can use `r.Request = r.WithContext(ctx)` change its underlying conetxt. Thanks for your proposal, I'll add a new method `r.SetCtx` for convenience.

**Comment by isword123** [comment]
Thank you for your advice. I'll try with this method.
