### ISSUE TITLE
g.Server 静态文件服务器，是否支持拦截器

### ISSUE THREAD

**Issue by botsphp** [gogf/gf#1073]
现在想在静态文件加鉴权，现在试了一下，Middleware不对静态文件生效 。

**Comment by botsphp** [comment]
大量 `ServeFile` 是否会影响性能？

```golang
	s := g.Server()

	s.BindMiddleware("/:file", func(c *ghttp.Request) {
		auth := Auth{
		}

		if code, err := auth.AuthCheck(); code != 200 {
			c.Response.WriteStatusExit(code, err)
		} else {
			c.Response.ServeFile(auth.fileName)
		}
	})

	s.SetPort(8199)
	s.Run()
```

**Comment by IGGAbc** [comment]
你这个 "/:file" 可以支持吗? 我测试是不支持的啊!!

**Comment by gqcn** [comment]
@botsphp 中间件不支持静态请求，`HOOK`支持。你的代码那样自己通过路由来维护也可以。

**Comment by botsphp** [comment]
> 你这个 "/:file" 可以支持吗? 我测试是不支持的啊!!

我发的代码就是可以跑的哦。

**Comment by botsphp** [comment]
> @botsphp 中间件不支持静态请求，`HOOK`支持。你的代码那样自己通过路由来维护也可以。

我想了解一下 `ServeFile` 在性能上有没有需要注意的地方。

**Comment by gqcn** [comment]
> > @botsphp 中间件不支持静态请求，`HOOK`支持。你的代码那样自己通过路由来维护也可以。
> 
> 我想了解一下 `ServeFile` 在性能上有没有需要注意的地方。

`ServeFile`其实底层是调用的标准库`net/http`的`ServeContent`方法，具体可以看下源码。性能上标准库还是能保证的。
