### ISSUE TITLE
gf gen生成模型中的One方法出现异常的情况

### ISSUE THREAD

**Issue by francisxie** [gogf/gf#1074]
golang版本: go version go1.15.6 linux/amd64

goframe版本:  v1.14.6
当数据库中不存在对应的记录会出现崩溃
``` golang
auth, err := server_authorization.Model.Where(g.Map{server_authorization.Columns.AuthKey: data.AuthKey,
		server_authorization.Columns.Secret: data.Secret}).One()
	if err != nil {
		return nil, err
	}
```
出现问题:
```
//runtime error: invalid memory address or nil pointer dereference
```

**Comment by gqcn** [comment]
@francisxie 请检查下你的`data`变量是否为空指针。

**Comment by francisxie** [comment]
@gqcn 
![image](https://user-images.githubusercontent.com/22124363/103130881-7766b780-46d9-11eb-9c9c-41714ae1192f.png)
是gf命令(gf gen model)生成的模型方法里面没有判断.
254行应该判断一下one是不是nil.
