### ISSUE TITLE
客户端提交过来的json格式的字符串如何转换到结构体啊？

### ISSUE THREAD

**Issue by joyoes** [gogf/gf#1075]
我如何将客户端提交map类型的参数内容绑定到我想要的request里面的内容里啊？这个问题干了四个小时了都没干出来，求大神指点一下，谢谢！
![20201221-1](https://user-images.githubusercontent.com/16605854/102778826-36fff480-43ce-11eb-8d81-78f683d452fd.png)
![20201221-2](https://user-images.githubusercontent.com/16605854/102778834-38c9b800-43ce-11eb-8a08-88c33812381d.png)
![20201221-3](https://user-images.githubusercontent.com/16605854/102778835-39fae500-43ce-11eb-8253-7d71aee65940.png)
我的action代码是：
```go
func (action *Action) Save(r *ghttp.Request){
request:=new(digital.Request)
a:=gconv.Bytes(r.GetQueryMap()["data"])
glog.Printf("%T",a)
glog.Println(a)
err:=gjson.DecodeTo(a,&request)
if err!=nil{
base.Fail(r,"error")
}
glog.Println(request)
}
```
我的service里的结构体为
```go
type Request struct{
digital.Entity
Id int `form:"id" json:"id"`
ProjectId string `form:"projectId" json:"projectId"`
CompleteScore float64 `form:"completeScore" json:"completeScore"`
}
```

**Comment by francisxie** [comment]
```
type Request  struct {
	Id          int   	`json:"idx"`         
	ProjectId 	string 	`json:"projectId"`
}

func (action *Action) Save(r *ghttp.Request){
	var data *Request
	if err := r.Parse(&data); err != nil {
		glog.Println("解析失败")
	}
	else
	{
		glog.Println("解析成功")
	}
}
```
有不懂的可以先看看文档和demo,里面都有具体实现.

**Comment by joyoes** [comment]
@francisxie 我就是按照官网上和你发给我的例子测试的，结果还是没有值呢
![2020122-3](https://user-images.githubusercontent.com/16605854/102843578-68b3a280-4444-11eb-8f0d-2d822702dbc1.png)
![20201222-1](https://user-images.githubusercontent.com/16605854/102843582-6b15fc80-4444-11eb-9e81-2f27fa13ab5e.png)
![20201222-2](https://user-images.githubusercontent.com/16605854/102843583-6bae9300-4444-11eb-8466-39c485c5c5de.png)
![20201222-4](https://user-images.githubusercontent.com/16605854/102843585-6c472980-4444-11eb-8a87-a0f25a2b7a9c.png)

**Comment by joyoes** [comment]
```go
type Request  struct {
	Id          int   	`json:"idx"`         
	ProjectId 	string 	`json:"projectId"`
}

func (action *Action) Save(r *ghttp.Request){
	var data *Request
	if err := r.Parse(&data); err != nil {
		glog.Println("解析失败")
	}
	else
	{
		glog.Println(data)
	}
}
```

**Comment by housemecn** [comment]
> ```go
> type Request  struct {
> 	Id          int   	`json:"idx"`         
> 	ProjectId 	string 	`json:"projectId"`
> }
> 
> func (action *Action) Save(r *ghttp.Request){
> 	var data *Request
> 	if err := r.Parse(&data); err != nil {
> 		glog.Println("解析失败")
> 	}
> 	else
> 	{
> 		glog.Println(data)
> 	}
> }
> ```

console 没有打印出来？

**Comment by francisxie** [comment]
> @francisxie 我就是按照官网上和你发给我的例子测试的，结果还是没有值呢
> ![2020122-3](https://user-images.githubusercontent.com/16605854/102843578-68b3a280-4444-11eb-8f0d-2d822702dbc1.png)
> ![20201222-1](https://user-images.githubusercontent.com/16605854/102843582-6b15fc80-4444-11eb-9e81-2f27fa13ab5e.png)
> ![20201222-2](https://user-images.githubusercontent.com/16605854/102843583-6bae9300-4444-11eb-8466-39c485c5c5de.png)
> ![20201222-4](https://user-images.githubusercontent.com/16605854/102843585-6c472980-4444-11eb-8a87-a0f25a2b7a9c.png)
> 
> 确实提示解析到成功了，但是没有值！

你使用的什么工具发送的?用调试模式看看局构体体里面属性存的什么值.

**Comment by gqcn** [comment]
@joyoes 给个完整可运行代码。

**Comment by joyoes** [comment]
@gqcn 我查出问题了，是客户端json格式的问题！不关服务器端的事情！

**Comment by joyoes** [comment]
@gqcn 我本来都非常希望能加入团队，贡献点力量，只是我的工作实在太忙太忙了！白天要开会，晚上要加班干业务！真的好羡慕你们专研技术！

**Comment by gqcn** [comment]
> @gqcn 我本来都非常希望能加入团队，贡献点力量，只是我的工作实在太忙太忙了！白天要开会，晚上要加班干业务！真的好羡慕你们专研技术！

时间都是挤出来的，只要你感兴趣就不需要找理由。 -- 现在是凌晨01:46

**Comment by joyoes** [comment]
@gqcn 好的！我尽量把时间安排好！
