### ISSUE TITLE
gvalid: invalid_rule cannot be outputed in the gvalid.Error.String()

### ISSUE THREAD

**Issue by MTTMTTMTT** [gogf/gf#1077]
### 1. What version of `Go` and system type/arch are you using?
go version go1.14.9 windows/amd64

### 2. What version of `GoFrame` are you using?
1.14.5

### 3. Can this issue be reproduced with the latest release?
Yes

### 4. What did you do?

I defined a wrong validation tag and gvalid catches the error as an invalid rule.
I need to handler occasions when sometimes tags are incorrect.
```go
type a struct {
Name string `v:"hh"`
}
aa := a{Name: "2"}
err := gvalid.CheckStruct(&aa, nil)
fmt.Println(err.String())
```

### 5. What did you expect to see?
error string as: 
invalid rule: hh

### 6. What did you see instead?
err.String() == ""

### Possible Cause
util\gvalid\gvalid_check.go   line149-line171
```
	// Handle the char '|' in the rule,
	// which makes this rule separated into multiple rules.
	ruleItems := strings.Split(strings.TrimSpace(rules), "|")
	for i := 0; ; {
		array := strings.Split(ruleItems[i], ":")
		_, ok := allSupportedRules[array[0]]
		if !ok && customRuleFuncMap[array[0]] == nil {
			if i > 0 && ruleItems[i-1][:5] == "regex" {
				ruleItems[i-1] += "|" + ruleItems[i]
				ruleItems = append(ruleItems[:i], ruleItems[i+1:]...)
			} else {
				return newErrorStr(
					"invalid_rules",
					"invalid rules: "+rules,
				)
			}
		} else {
			i++
		}
		if i == len(ruleItems) {
			break
		}
	}
```

the unknown validation tag will return a new error map, key = "invalid_rules", value = "invalid rules: "+rules
the key will be used in the code below, when formatting the error string.

util\gvalid\gvalid_error.go   line150-line180
```
// Strings returns all error messages as string array.
func (e *Error) Strings() (errs []string) {
	if e == nil {
		return []string{}
	}
	errs = make([]string, 0)
	// By sequence.
	if len(e.rules) > 0 {
		for _, v := range e.rules {
			name, rule, _ := parseSequenceTag(v)
			if m, ok := e.errors[name]; ok {
				for _, rule := range strings.Split(rule, "|") {
					array := strings.Split(rule, ":")
					rule = strings.TrimSpace(array[0])
					if err, ok := m[rule]; ok {
						errs = append(errs, err)
					}
				}
			}
		}
		return errs
	}
	// No sequence.
	for _, m := range e.errors {
		for _, err := range m {
			errs = append(errs, err)
		}
	}
	return
}
```
the code below will match the rule with the error map
```
if err, ok := m[rule]; ok {
errs = append(errs, err)
}
```
the wrong rule can't match the key: invalid_rule
![image](https://user-images.githubusercontent.com/45574959/102858706-af65c480-4465-11eb-831f-00c6c9c7e5f3.png)
so the invalid error is ignored and can't be outputed as error string.
I thought it might be part of the concern that gf should ignore the tag that it can't parse, making the framework more flexible.
What if I need to handle the invalid rule error?
I thought the change below might handle my problem.
```
return newErrorStr(
  array[0],
  "invalid rules: "+rules,
)
```

**Comment by MTTMTTMTT** [comment]
err := gvalid.CheckStruct(&aa, nil)
err != nil,  so I need to handler, but the err.String() shows nothings.
Currently I can only use the err.Maps(), and check if the map[string]map[string]interface has second key == "invalid_rule"
This might not be the best practice.

**Comment by gqcn** [comment]
@MTTMTTMTT `go get -u github.com/gogf/gf@master` and try again.

**Comment by MTTMTTMTT** [comment]
Exaclty as I expected.
So I should use version >= 1.14.7 after released?
Thanks for patience
