### ISSUE TITLE
project init error

### ISSUE THREAD

**Issue by jossion** [gogf/gf#1078]
### 1. What version of `Go` and system type/arch are you using?
$ gf -v
GoFrame CLI Tool v1.14.5, https://goframe.org
Install Path: C:\Go\bin\gf.exe
Build Detail:
  Go Version:  go1.15.5
  GF Version:  v1.14.6
  Git Commit:  eaa167b3ba2e3dfca93686c455ce24d12fc61b09
  Build Time:  2020-12-20 22:07:26

### 3. Can this issue be reproduced with the latest release?
$ gf init uxgf
initializing...
Error: get the project zip md5 failed: Get "https://goframe.org/cli/project/md5": EOF

**Comment by gqcn** [comment]
@jossion The domain DNS of `goframe.org` is switching. Please try again later.
