### ISSUE TITLE
gfile.ReadLines 若兑奖大量的文件内容会出现重读的情况

### ISSUE THREAD

**Issue by JamesWuChina** [gogf/gf#1082]
Build Detail:
  Go Version:  go1.14
  GF Version:  v1.13.7
  Git Commit:  b80426a2a3fb256626baafdb2844dd71afff719b
  Build Time:  2020-10-15 11:35:28

**Comment by danvinhe** [comment]
line:  7534   oDHi7bKiRudbODIPaZVEIcjR2r63MhwF
 Duplicate Index:  oDHi7bKiRudbODIPaZVEIcjR2r63MhwF {{2020-12-29 17:01:24.145524 +0800 CST m=+0.032384829}} {{2020-12-29 17:01:24.167306 +0800 CST m=+0.054175283}}
 line:  7535   wxcEKsgmTvTTyxodwUumDK8itYZVGltS

**Comment by JamesWuChina** [comment]
问题已经解决，感谢。
