### ISSUE TITLE
数据校验默认值

### ISSUE THREAD

**Issue by davveo** [gogf/gf#1085]
前端提交的数据，如果未传递，校验的时候，可否给一个默认值选项，而不是默认空串或者0

**Comment by gqcn** [comment]
@davveo 校验当然只做校验的事情，其实在`HTTP Server`中的`Request`对象是带有默认值标记特性的，使用`d`的`struct tag`实现，只是文档上没说明，下一个版本文档上我更新一下。

**Comment by davveo** [comment]
好的

**Comment by gqcn** [comment]
@davveo https://itician.org/pages/viewpage.action?pageId=3671922

**Comment by davveo** [comment]
thx
