### ISSUE TITLE
gframe的0值更新问题有解决方案吗?

### ISSUE THREAD

**Issue by Golong-me** [gogf/gf#1087]
我目前的方案是用**先查询出老的数据.**
再利用copier直接把传入的对象的值**复制到老的数据里,然后复制的时候忽略空值**.
**请问gframe的orm有什么操作能让0值不更新到数据库?官方文档并没有提及到**
![image](https://user-images.githubusercontent.com/72813193/103174852-6ba3fe00-485d-11eb-94e0-5a58c2281b44.png)

**Comment by gqcn** [comment]
@Golong-me https://itician.org/pages/viewpage.action?pageId=1114229#id-%E5%AD%97%E6%AE%B5%E8%BF%87%E6%BB%A4-OmitEmpty%E7%A9%BA%E5%80%BC%E8%BF%87%E6%BB%A4
![image](https://user-images.githubusercontent.com/26347176/103176457-9f5a4480-48ac-11eb-94ad-856e8987018a.png)
