### ISSUE TITLE
是否考虑把ssdb库集成到gdb里

### ISSUE THREAD

**Issue by qq1196** [gogf/gf#109]
http://ssdb.io/docs/zh_cn/clients.html#go

**Comment by johngcn** [comment]
@qq1196 

`gdb`是关系型数据库管理模块，`ssdb`和`redis`类似是`nosql`数据库，两者是不一样的，肯定不能集成到`gdb`。可以作为第三方包来使用，我看官方页面提供参考的第三方就挺多的。如果想方便配置管理，可以自行封装一下`gcfg`和`ssdb`客户端。

我们公司也在用`ssdb`，坑比较多。未来会淘汰`ssdb`。
