### ISSUE TITLE
where查询feature

### ISSUE THREAD

**Issue by davveo** [gogf/gf#1090]
```golang
type User struct {
    Id       int                `c:"eq"`  // 查询的时候，转换为id=xxx
    UserName string  `c:"like"` //查询的时候，转换为 username like ?
    job []string            `c:"in"` // 查询的时候转换为 job in []
}
// SELECT * FROM user WHERE uid =1 AND name like '%john%' and job in (a, b, c) LIMIT 1
r, err := db.Table("user").Where(User{ Id : 1, UserName : "john"}).One()
````
能否支持上述feature

**Comment by danvinhe** [comment]
// SELECT * FROM user WHERE age>18 AND name like '%john%'
r, err := db.Table("user").Where("age>? AND name like ?", g.Slice{18, "%john%"}).All()

**Comment by BeanWei** [comment]
这种不应该交给框架来做，可以自行封装一个公共组件来处理数据 去喂给dao层。

**Comment by davveo** [comment]
> 这种不应该交给框架来做，可以自行封装一个公共组件来处理数据 去喂给dao层。

好滴。🙏

**Comment by gqcn** [comment]
@davveo 你好，`gf`的`orm`一直不是很推荐复杂化`tag`的方式来实现一些`feature`，这个也是如此，这样虽然能实现一些`feature`，但是会将`struct`变得臃肿复杂，增加后期维护成本。按照@danvinhe写的那样，通过方法传递参数实现吧。
