### ISSUE TITLE
模板引擎，eq函数 多参数时存在问题

### ISSUE THREAD

**Issue by sanrentai** [gogf/gf#1095]
### 1. What version of `Go` and system type/arch are you using?

go1.15.5 windows/amd64

### 2. What version of `GoFrame` are you using?

v1.14.6

### 3. Can this issue be reproduced with the latest release?

yes

### 4. What did you do?

```go
content := `name is ${if eq .name "gf" "tt"} gf or tt ${else} not gf and not tt ${end} , version: ${.version}`
data := g.Map{"name": "gf", "version": "1.10.0"}
result, err := view.ParseContent(content, data)
fmt.Println(result)
```

### 5. What did you expect to see?

name is  gf or tt  , version: 1.10.0

### 6. What did you see instead?

name is  not gf and not tt  , version: 1.10.0

按照文档https://itician.org/pages/viewpage.action?pageId=1114147 的理解
eq 多个参数是 或 的关系
```
{{eq arg1 arg2 arg3 arg4}}
```
相当于
```
arg1==arg2 || arg1==arg3 || arg1==arg4 
```
经过测试  ${eq .name "gf" "tt"} 输出的是 false

**Comment by gqcn** [comment]
@sanrentai `go get -u github.com/gogf/gf@master` 再试试。
