### ISSUE TITLE
路由注册/:table/test 通配符后，r.get("table")能获取到值，模版解析函数{{.Request.table}}无法获取到

### ISSUE THREAD

**Issue by 35598253** [gogf/gf#1101]
go : 1.15.5
gf : 1.15.0
路由注册/:table/test 通配符，访问 /news/test 后    r.get("table")能获取到值， 模版解析函数{{.Request}}无法获取到
测试代码如下：
func Test(r *ghttp.Request) {
	content := `r.get table is "{{.table}}"`

	r.Response.WriteTplContent(content, g.Map{
		"table":  r.Get("table"),
	})
	content2 := `         Request table is {{.Request.table}}`
	r.Response.WriteTplContent(content2,nil)

}

func main() {
	s := g.Server()
	s.BindHandler("/:table/test", Test)

	s.SetPort(8199)
	s.Run()

}

输出 ：r.get table is "news"         Request table is 

 {{.Request}} 为空

**Comment by gqcn** [comment]
@35598253 试试最新的`master`分支。
