### ISSUE TITLE
orm中ScanList方法没有正确地把数据解析到struct

### ISSUE THREAD

**Issue by qinyuguang** [gogf/gf#1104]
### 1. What version of `Go` and system type/arch are you using?
go 1.15

### 2. What version of `GoFrame` are you using?
gf v1.15.0

我通过gf gen dao生成了model和dao，并对model中的struct进行了扩充如下

```go
type Test struct {
    *internal.Test
    Setting *TestSetting `orm:"extra_setting"`
}

type TestSetting struct {
    Enable1 bool `json:"enable1"`
    Enable2 bool `json:"enable2"`
}
```

数据库中extra_setting字段，存储的是json数据

当我使用FindOne和FindAll读数据时，extra_setting内容可以正确解析到Test.Setting中

但使用ScanList进行关联读取时，Test.Setting就总是nil了

@gqcn 有空请看下哈，是否ScanList少做了结构转换的操作

**Comment by qinyuguang** [comment]
另外还有个问题，像这样对model中的结构进行扩展，在创建Test实例时，因为Test继承了internal里的结构，就没法使用下边的方式了
```go
test := &model.Test{
    internal.Test: &internal.Test{
        Id: "123",
    },
}
```

只能用这样的方法
```go
test := &model.Test{]
test.Id = 123
```

字段多的时候不美观，请问下有什么更好的方法来实现吗？

**Comment by gqcn** [comment]
> 另外还有个问题，像这样对model中的结构进行扩展，在创建Test实例时，因为Test继承了internal里的结构，就没法使用下边的方式了
> 
> ```go
> test := &model.Test{
>     internal.Test: &internal.Test{
>         Id: "123",
>     },
> }
> ```
> 
> 只能用这样的方法
> 
> ```go
> test := &model.Test{]
> test.Id = 123
> ```
> 
> 字段多的时候不美观，请问下有什么更好的方法来实现吗？

那个`internal`包的类型主要是由工具来自动管理的，自动生成代码的时候会自动覆盖。你也可以不嵌入里面的结构，自行将里面的结构复制出来到`model`中，不过随后就得自己维护这个结构了。

**Comment by gqcn** [comment]
@qinyuguang 你的第一个关于`ScanList`的问题你把可复现问题的最小化代码贴上来，这样我解决问题会高效很多。

**Comment by qinyuguang** [comment]
明白了。。第一个问题里，我在model扩展的字段后，只加了orm的tag，没加json，所以ScanList没扫进去。加上json标签后就没有问题了

**Comment by gqcn** [comment]
> 明白了。。第一个问题里，我在model扩展的字段后，只加了orm的tag，没加json，所以ScanList没扫进去。加上json标签后就没有问题了

除非你的字段和你的属性无法按照默认规则映射匹配才会出现这样的情况：https://itician.org/pages/viewpage.action?pageId=3670167#id-%E7%B1%BB%E5%9E%8B%E8%BD%AC%E6%8D%A2Struct%E8%BD%AC%E6%8D%A2-%E8%BD%AC%E6%8D%A2%E8%A7%84%E5%88%99
