### ISSUE TITLE
grand 建议 用int64作为参数

### ISSUE THREAD

**Issue by 15951836388** [gogf/gf#1105]
满足不了，需要传入int64类型的情况。
强转int传入，担心某些32位平台丢失精度。

**Comment by gqcn** [comment]
`int`绝大多数场景都适用了，你需要这么大的随机数啊，什么场景啊？

**Comment by 15951836388** [comment]
游戏啊，作为库，应该尽量满足各种情况吧。int64的需求是存在的，你看官方数学库的参数也全部都是int64的

**Comment by 15951836388** [comment]
鉴于用int的比较多，可以封装添加一组int64的api
![image](https://user-images.githubusercontent.com/14047483/103963641-c6f6ba00-5194-11eb-8d23-9ddc39b0e3d3.png)

**Comment by gqcn** [comment]
> 游戏啊，作为库，应该尽量满足各种情况吧。int64的需求是存在的，你看官方数学库的参数也全部都是int64的

主要从实用性和易用性考虑的。我猜测你只是需要一个`int64`类型，并不是真正数值需要这么大的范围，对吧？

**Comment by 15951836388** [comment]
是有可能真的能用到int64的。（虽然一般情况不会用到，就像产品策划拍着胸脯说这个功能不会改了，后面还是要改）
