### ISSUE TITLE
使用grpool.add添加进程时，如何传入带参数的函数呢？

### ISSUE THREAD

**Issue by yeshxm** [gogf/gf#1106]
### 1. What version of `Go` and system type/arch are you using?

Go Version:  go1.15.5

### 2. What version of `GoFrame` are you using?

  GF Version:  v1.14.6

### 3. Can this issue be reproduced with the latest release?
i do not know

### 4. What did you do?

gpool . Add(func (snlist string) {
})(test)

### 5. What did you expect to see?
怎么才能向进程条用的函数传递参数

### 6. What did you see instead?
添加
C AddSave( cannot use
(func(snlist string) literal) (value of type func(snlist
snlist := string)) as func() value in argument to pool . Add compiler

**Comment by yeshxm** [comment]
The author has been contacted to solve the problem

**Comment by dabuge** [comment]
在外面定义变量，在匿名函数里面使用就好了，给你个例子：
```
                 //匿名函数里面需要使用的变量
		em := eventMessage
		_ = pool.Add(func() {
			//第一步，保存事件到 mongodb
			ud, err := SaveEvent(&em)
		})
```

**Comment by gqcn** [comment]
@yeshxm 楼上大佬说的对。你也可以参考下文档：https://itician.org/pages/viewpage.action?pageId=1114246
