### ISSUE TITLE
用gf gen model生成代码时可以设置让entity里的json使用的命名规范

### ISSUE THREAD

**Issue by yeshxm** [gogf/gf#1107]
### 1. What version of `Go` and system type/arch are you using?
Go Version:  go1.15.5

### 2. What version of `GoFrame` are you using?
GF Version:  v1.14.6

### 3. Can this issue be reproduced with the latest release?
yes

### 4. What did you do?
```go
type Entity struct {
    ID         uint64      `orm:"ID,primary" json:"id"`                  
    Sn         string      `orm:"Sn"         json:"sn"`                   
    Key        string      `orm:"Key"        json:"key"`               
    Sim        string      `orm:"Sim"        json:"sim"`           
    Name       string      `orm:"Name"       json:"name"`       
    CreateTime *gtime.Time `orm:"CreateTime" json:"create_time"`    
}
```

### 5. What did you expect to see?

可以设置不采用这种下划线的命名方式，比如采用驼峰或者字段原名的方式

### 6. What did you see instead?
```go
CreateTime *gtime.Time `orm:"CreateTime" json:"create_time"`    
```

**Comment by gqcn** [comment]
@yeshxm 请参考`jsonCase`配置：https://itician.org/display/gf/gen+dao
