### ISSUE TITLE
ORM 添加位操作

### ISSUE THREAD

**Issue by shengdoushi** [gogf/gf#1109]
类似 gdb.Counter, 如当前有个字段是位标志的， 要更新状态:

```sql
update article set state = state | 1;
```

ORM 可以添加类似 gdb.Counter 的东东: 

```go

oper := &gdb.BitOper{
	Field: "state",
        Op: gdb.BIT_OR,
	Value: 1,
}
updateData := g.Map{
	"state": oper,
}
// UPDATE `article` SET `state `=`state `|1 WHERE `id`=1
result, err := db.Update("article", updateData, "id", 1)
```

**Comment by gqcn** [comment]
@shengdoushi `Counter`主要用于常见的增减操作，你这个场景其实可以考虑使用`Raw`：https://itician.org/pages/viewpage.action?pageId=1114238#id-%E6%9B%B4%E6%96%B0%E5%88%A0%E9%99%A4-RawSQL%E8%AF%AD%E5%8F%A5%E5%B5%8C%E5%85%A5
```go
updateData := g.Map{
	"state": gdb.Raw("`state`|1"),
}
// UPDATE `article` SET `state `=`state `|1 WHERE `id`=1
result, err := db.Update("article", updateData, "id", 1)
```

**Comment by shengdoushi** [comment]
> @shengdoushi `Counter`主要用于常见的增减操作，你这个场景其实可以考虑使用`Raw`：https://itician.org/pages/viewpage.action?pageId=1114238#id-%E6%9B%B4%E6%96%B0%E5%88%A0%E9%99%A4-RawSQL%E8%AF%AD%E5%8F%A5%E5%B5%8C%E5%85%A5
> 
> ```go
> updateData := g.Map{
> 	"state": gdb.Raw("`state`|1"),
> }
> // UPDATE `article` SET `state `=`state `|1 WHERE `id`=1
> result, err := db.Update("article", updateData, "id", 1)
> ```

明白，现在我就是这样做的。只是提下建议，不加这个功能也可以

**Comment by gqcn** [comment]
@shengdoushi 功能尽可能精简、简洁，不能提供过多相同功能的实现逻辑，避免开发者混淆，减轻开发者心智负担，提高使用体验。

**Comment by wufeiyueGit** [comment]
> > [@shengdoushi](https://github.com/shengdoushi) `Counter`主要用于常见的增减操作，你这个场景其实可以考虑使用`Raw`：https://itician.org/pages/viewpage.action?pageId=1114238#id-%E6%9B%B4%E6%96%B0%E5%88%A0%E9%99%A4-RawSQL%E8%AF%AD%E5%8F%A5%E5%B5%8C%E5%85%A5
> > updateData := g.Map{
> > 	"state": gdb.Raw("`state`|1"),
> > }
> > // UPDATE `article` SET `state `=`state `|1 WHERE `id`=1
> > result, err := db.Update("article", updateData, "id", 1)
> 
> 明白，现在我就是这样做的。只是提下建议，不加这个功能也可以

这样做如何解决Sql注入问题  gdb.Raw 似乎没有？
为何不将Counter定义的通用一些 ，中间运算符自己定义？
