### ISSUE TITLE
平滑关闭

### ISSUE THREAD

**Issue by lepoch** [gogf/gf#1111]
### 1. What version of `Go` and system type/arch are you using?

go version go1.15.5 linux/amd64

### 2. What version of `GoFrame` are you using?

v1.14.6-0.20201207123952-60ec59fa4a5c

### 3. Can this issue be reproduced with the latest release?

不能

### 4. What did you do?

k8s的部署完成后会发送 SIGTERM 信号给老的pods，gf框架对此处理是直接关闭，导致一部分请求直接失败。
```bash
kill -SIGTERM 38635
```

### 5. What did you expect to see?

`kill -SIGTERM`  也能平滑关闭，比如调用shutdown，或者最多等个一十二秒啥的。

**Comment by gqcn** [comment]
@lepoch 已改进提交到了`master`分支。
