### ISSUE TITLE
need "\r\n" support in glog on windows

### ISSUE THREAD

**Issue by shen1l** [gogf/gf#1112]
### 1. What version of `Go` and system type/arch are you using?
go version go1.15.5 windows/amd64

### 2. What version of `GoFrame` are you using?

1.15.1

### 3. Can this issue be reproduced with the latest release?
yes

### 4. What did you do?

glog.info("123")

### 5. What did you expect to see?
![image](https://user-images.githubusercontent.com/10751634/103859099-6dd74980-50f4-11eb-8d57-e55812d2d228.png)

### 6. What did you see instead?
![image](https://user-images.githubusercontent.com/10751634/103859065-6021c400-50f4-11eb-8898-c4ccd4bd2458.png)

- I am having an issue opening a log file on windows 7 using notepad, it could not recognize the "\n" as line ending.
- the below image shows the issue located in the code project
![image](https://user-images.githubusercontent.com/10751634/103859845-ba6f5480-50f5-11eb-8c7a-4256869f6134.png)
- I am now using a log hooker to fix it temporarily but would be better if there is a way to use "\r\n"
```
	glog.SetWriter(win.CreateNewLineFixer(logger))
```

```
type newLineFixer struct {
	logger *glog.Logger
}

func (Self *newLineFixer) Write(p []byte) (n int, err error) {
	s := string(p)
	if s[len(s)-1] == '\n' {
		s = s[:len(s)-1] + "\r"
	}
	Self.logger.Header(false).Print(s)
	return len(p), nil
}

func CreateNewLineFixer(logger *glog.Logger) *newLineFixer {
	return &newLineFixer{logger: logger}
}
```

**Comment by gqcn** [comment]
@shen1l Sorry, it should use '\n' as a standard new line character. Do not use integrated notepad viewing the log content on windows.
