### ISSUE TITLE
Hope to add redis cluster and mongodb to the framework, thank you

### ISSUE THREAD

**Issue by zhangyiyou5** [gogf/gf#1114]

**Comment by dabuge** [comment]
我们也有这需求，redis cluster 我们用了 go-redis 这个库解决了，mongodb 用的mongo 官方的go驱动包，我还没有吃透官方的g.object ，晚点再研究研究，研究透了，看看把 mongodb 搞成 g.mongo 再提个 pr

**Comment by gqcn** [comment]
@dabuge @zhangyiyou5 Hi, guys, it would be better making mongo a community package or just use it as a third-party package, other than integrated it into `gf`. So does `go-redis`, but there's a plan we'll wrap `go-redis` as a community package for `goframe`.
