### ISSUE TITLE
gconv.String 和error类型 在 glog+g.Map时的优化

### ISSUE THREAD

**Issue by 15951836388** [gogf/gf#1122]
glog.Info("BatchIndexs", g.Map{"dbKey": dbKey, "msgs": msgs, "err": err.Error(), "result": result})

其中g.Map里， "err": err.Error()，才能打印出来。 "err": err，是打印不出内容的

看源码，是gconv.String里没有判断error类型，希望改进下

**Comment by gqcn** [comment]
@15951836388 已对`gerror.Error`增加了`MarshalJSON`的支持，标准库的`errors`不支持没办法。

**Comment by 15951836388** [comment]
err := errors.New("xxx")
	glog.Debug(err)
	glog.Debug(err.Error())
	glog.Debug(g.Map{"err": err}) //打印不出来
	glog.Debug(g.Map{"err tpe": err.Error()})
	glog.Debug(reflect.TypeOf(err))
	gerr := gerror.New("yyyy")
	glog.Debug(gerr)
	glog.Debug(gerr.Error())
	glog.Debug(g.Map{"gerr": gerr}) //gerr 也 打印不出来。。。。。
	glog.Debug(g.Map{"gerr tpe": gerr.Error()})
	glog.Debug(reflect.TypeOf(gerr))

**Comment by gqcn** [comment]
@15951836388 用`master`分支
