### ISSUE TITLE
gf gen 建议把模板暴露出来这样可以不需要修改源码就能自定义模板了

### ISSUE THREAD

**Issue by rxrddd** [gogf/gf#1123]
建议gf gen把模板暴露出来这样可以不需要修改源码就能自定义模板了

建议gf出一个类似与go-zero的`template init` 命令 默认把模板初始化到一个`~/.gf `目录下 然后可以进行自定义也可以复制到项目里面,在项目里面执行gf gen的时候直接读取项目的模板这样可以支持不同项目自定义不同的模板
模板优先级可以是执行目录->初始化目录->gf-cli的源码模板

**Comment by gqcn** [comment]
@rxrddd 功能已完成，文档待更新。
