### ISSUE TITLE
gfile.Search() 方法希望支持目录内递归查找

### ISSUE THREAD

**Issue by dabuge** [gogf/gf#1125]
```
// Search searches file by name <name> in following paths with priority:
// prioritySearchPaths, Pwd()、SelfDir()、MainPkgPath().
// It returns the absolute file path of <name> if found, or en empty string if not found.
func Search(name string, prioritySearchPaths ...string) (realPath string, err error) {
	。。。
	// Do the searching.
	array.RLockFunc(func(array []string) {
		path := ""
		for _, v := range array {
			path = RealPath(v + Separator + name)
			if path != "" {
				realPath = path
				break
			}
		}
	})
	。。。
	return
}
```

目前只支持在传入的目录查找文件，希望可以递归，在传入的目录的子目录里面也查找文件。因为只在传入的目录里面查找文件的话，我将目录和文件拼接，然后用 gfile.IsFile() 方法更容易理解。

现在暂时使用了 filepath.Walk 来查找，感觉有点浪费，gfile.Search() 支持递归查找就完美了

**Comment by gqcn** [comment]
@dabuge 其实你可以使用`ScanDirFileFunc`：
```go
// ScanDirFileFunc returns all sub-files with absolute paths of given <path>,
// It scans directory recursively if given parameter <recursive> is true.
//
// The pattern parameter <pattern> supports multiple file name patterns, using the ','
// symbol to separate multiple patterns.
//
// The parameter <recursive> specifies whether scanning the <path> recursively, which
// means it scans its sub-files and appends the files path to result array if the sub-file
// is also a folder. It is false in default.
//
// The parameter <handler> specifies the callback function handling each sub-file path of
// the <path> and its sub-folders. It ignores the sub-file path if <handler> returns an empty
// string, or else it appends the sub-file path to result slice.
//
// Note that the parameter <path> for <handler> is not a directory but a file.
// It returns only files, exclusive of directories.
func ScanDirFileFunc(path string, pattern string, recursive bool, handler func(path string) string) ([]string, error)
```

**Comment by dabuge** [comment]
> @dabuge 其实你可以使用`ScanDirFileFunc`：
> 
> ```go
> // ScanDirFileFunc returns all sub-files with absolute paths of given <path>,
> // It scans directory recursively if given parameter <recursive> is true.
> //
> // The pattern parameter <pattern> supports multiple file name patterns, using the ','
> // symbol to separate multiple patterns.
> //
> // The parameter <recursive> specifies whether scanning the <path> recursively, which
> // means it scans its sub-files and appends the files path to result array if the sub-file
> // is also a folder. It is false in default.
> //
> // The parameter <handler> specifies the callback function handling each sub-file path of
> // the <path> and its sub-folders. It ignores the sub-file path if <handler> returns an empty
> // string, or else it appends the sub-file path to result slice.
> //
> // Note that the parameter <path> for <handler> is not a directory but a file.
> // It returns only files, exclusive of directories.
> func ScanDirFileFunc(path string, pattern string, recursive bool, handler func(path string) string) ([]string, error)
> ```

也对，没注意还有这个方法
