### ISSUE TITLE
完善gtime模块的format自定义时间格式化标识符支持

### ISSUE THREAD

**Issue by johngcn** [gogf/gf#113]
参考：https://www.php.net/manual/zh/function.date.php

需要增加的`format`标识符为：

format | 说明 | 返回值例子
-- | -- | --
**日** | --- | ---
N | ISO-8601 格式数字表示的星期中的第几天 | 1（表示星期一）到 7（表示星期天）
S | 每月天数后面的英文后缀，2 个字符 | st，nd，rd 或者 th。可以和 j 一起用
z | 年份中的第几天 | 0 到 365
**星期** | --- | ---
W | ISO-8601 格式年份中的第几周，每周从星期一开始|例如：42（当年的第 42 周）
**月** | --- | ---
t | 指定的月份有几天 | 28 到 31
**时区** | --- | ---
e | 时区标识 | 例如：UTC，GMT，Atlantic/Azores

**Comment by jroam** [comment]
功能已完成，请关闭。

**Comment by johngcn** [comment]
好的，辛苦了，由于文档我还没更新，先留着，等文档更新后再关。
