### ISSUE TITLE
【feature】orm中查询使用并列的OR

### ISSUE THREAD

**Issue by Hareis** [gogf/gf#1131]
目前ORM 可生成下面截图的SQL语句
![image](https://user-images.githubusercontent.com/11290701/105013415-31073d00-5a7a-11eb-81f7-8976d50831d7.png)

不支持能否支持 下图的这种方式
![image](https://user-images.githubusercontent.com/11290701/105013465-411f1c80-5a7a-11eb-86da-ec5cae8ed989.png)

**Comment by gqcn** [comment]
初步的想法是增加一个新的参数类型，参考`gdb.Raw`和`gdb.Counter`的类似实现。
