### ISSUE TITLE
不带where的update，没能正确执行

### ISSUE THREAD

**Issue by marswj** [gogf/gf#1135]
### 1. What version of `Go` and system type/arch are you using?

go 1.13, linux/amd64

### 2. What version of `GoFrame` are you using?

1.15.1

### 4. What did you do?

	 db.Table("user_role").Data(g.Map{
	 	"bacpo": 0,
	 }).Update()

1.15.1不能正确执行。
在1.14.2是可以的。

**Comment by tangjoin** [comment]
为了误操作, 大多的框架都有这个功能,    必须全部更新的话, 加个Where("1",1)

**Comment by marswj** [comment]
文档里面是有这样的用法的
https://itician.org/pages/viewpage.action?pageId=1114238

// UPDATE `user` SET `status`=1
r, err := db.Table("user").Data("status=1").Update()
r, err := db.Table("user").Data("status", 1).Update()
r, err := db.Table("user").Data(g.Map{"status" : 1}).Update()

**Comment by gqcn** [comment]
@marswj 反写反馈，文档已更新
