### ISSUE TITLE
duplicated route registry message is not correct

### ISSUE THREAD

**Issue by skanger** [gogf/gf#1139]
### 1. What version of `Go` and system type/arch are you using?

go version go1.14.4 darwin/amd64

### 2. What version of `GoFrame` are you using?

github.com/gogf/gf v1.13.2

### 3. Can this issue be reproduced with the latest release?

maybe

### 4. What did you do?

duplicated route registry

### 5. What did you expect to see?

duplicated route registry message could point the correct line.

### 6. What did you see instead?

2021-01-25 17:18:02.326 [FATA] duplicated route registry "POST:/module/spot_quantity/runningStatusReset@default" at /Users/xxx//xxx/xxx/router/router.go:35 , already registered at /Users/xxx/xxx/xxx/router/router.go:35 

two register func, one is at line 35, one is at line 37, but message says that they are together at line 35.

中文: 重复注册的路由，一个在35行， 一个在37行，但是错误信息都说在35行。

**Comment by gqcn** [comment]
@skanger Please try the latest version. If this issue still exists, please submit the codes that can reproduce the issue.
