### ISSUE TITLE
gf 与 git fetch  重名

### ISSUE THREAD

**Issue by tphyhFighting** [gogf/gf#1140]

**Comment by sth4me** [comment]
alias git fetch commond like `alias gft=git fetch` `alias gf=gf` to change zsh default alias 
or rename gf binary file to other like `mv path_to_gf/gf path_to_gf/gfa`, then you can use it like gfa update.

使用alias命令 换掉zsh的默认alais， `alias gft=git fetch`  `alias gf=gf` 。
或者直接重命名你的gf命令，但可能影响 gf update.

**Comment by xflcx1991** [comment]
原来zsh有的默认alias，学习到了，通过`alias`命令看到了zsh背后做了大量的预alias。
