### ISSUE TITLE
建议优化模板 模板函数-内置函数中的 or 和 and   能不能优化到  "" nil 0 [] ...都为空

### ISSUE THREAD

**Issue by tangjoin** [gogf/gf#1144]
建议优化模板 模板函数-内置函数中的or  和and  这个用的多,    现在模板中的不为空,这个空只能是nil,        
能不能优化到  "" nil 0 [] ...都为空

```go
func  MyOr(str ...interface{}) string {
	for _, v := range str {
		tempStr := cast.ToString(v)
		if tempStr != "" {
			return tempStr
		}

	}
	return ""
}
```

**Comment by gqcn** [comment]
@tangjoin 很不错的建议！为何不来个PR？内部可以用`empty.IsEmpty`方法来做空值判断。内置函数编写，参考：https://github.com/gogf/gf/blob/master/os/gview/gview_buildin.go
