### ISSUE TITLE
希望gorm链式操作支持hint属性配置

### ISSUE THREAD

**Issue by slxgsy** [gogf/gf#1146]
在使用云数据库的项目中，云厂商已经有数据库代理层做读写分离。使用gorm现有的master和slave模式，主节点只能写不能读，有点浪费性能。如果链式操作函数支持hint语法，在拼接生成SQL语句前加入指定的hint内容，会更灵活。

阿里云hint语法说明：
支持在SQL语句前加上/*FORCE_MASTER*/或/*FORCE_SLAVE*/强制指定这条SQL的路由方向。
例如select * from test默认会路由到只读节点，改为/*FORCE_MASTER*/ select * from test就会路由到主节点。

支持在SQL语句前加上/*force_node='<节点ID>'*/强制指定在某节点执行某查询命令。
例如/*force_node='pi-bpxxxxxxxx'*/ show processlist，该show processlist命令只在pi-bpxxxxxxxx节点执行。如果该节点发生故障，则返回报错force hint server node is not found, please check.。

支持在SQL语句前加上/*force_proxy_internal*/set force_node = '<节点ID>'强制指定在某节点执行所有查询命令。
例如/*force_proxy_internal*/set force_node = 'pi-bpxxxxxxxx'，执行该命令后，后续所有查询命令只发往pi-bpxxxxxxxx节点，如果该节点发生故障，则返回报错set force node 'rr-bpxxxxx' is not found, please check.。

**Comment by gqcn** [comment]
@slxgsy 你这个似乎是数据库服务商提供的功能，不是标准数据库语法，ORM似乎不应该做这种事情。
