### ISSUE TITLE
1.15.3版本在debug模式下获取不到config/config.toml配置文件

### ISSUE THREAD

**Issue by dangwy** [gogf/gf#1153]
主要应该还是gcfg.go中的filePath改动导致。
![image](https://user-images.githubusercontent.com/1247168/106389131-d3c99f00-641c-11eb-93ef-59707713892f.png)

**Comment by gqcn** [comment]
@dangwy 什么是`debug`的获取不到？能详细描述一下吗？

**Comment by zuozhehao** [comment]
@gqcn 单元测试都找不到 `config/config.toml`

**Comment by gqcn** [comment]
@zuozhehao 你的可能是当前工作目录pwd下没有这个文件。
