### ISSUE TITLE
脚手架gf-cli工具在运行gf pack -p ="" 是会在根目录下多加一个/ 导致 项目运行加载找不到该目录

### ISSUE THREAD

**Issue by zhangbao138208** [gogf/gf#1156]
![image](https://user-images.githubusercontent.com/56329790/106558972-ab968900-655f-11eb-9a61-e62d7423a612.png)

**Comment by iamtheoneyf** [comment]
> ![Uploading image.png…]()

**Comment by tangjoin** [comment]
看了包源码,   建议目录连接 , 使用path.join()  更好的合理化目录

**Comment by gqcn** [comment]
@zhangbao138208 麻烦把复现问题的步骤阐述一下。

**Comment by gqcn** [comment]
> 看了包源码, 建议目录连接 , 使用path.join() 更好的合理化目录

资源管理器中统一使用的是`/`符号作为内存文件系统的分隔符号
