### ISSUE TITLE
orm模块where和or条件一起使用导致deleted_at is null 不生效

### ISSUE THREAD

**Issue by swift-fs** [gogf/gf#1157]
### 1. What version of `Go` and system type/arch are you using?
golang 1.15

### 2. What version of `GoFrame` are you using?

1.15.1

### 3. Can this issue be reproduced with the latest release?
orm模块`g.DB().Table().Where(...).Or(...)`后`deleted_at IS NULL`不再生效。

**Comment by shengdoushi** [comment]
嗯 我也发现这个问题了

g.DB().Table(a).Where(c1, 1).Or(c2, 2) 生成的sql大概是这样:

**Comment by shengdoushi** [comment]
看来or还是要慎用才行， 尤其在有软删除 deleted_at 字段的查询中
