### ISSUE TITLE
when run go methods for test, can't find config.toml.

### ISSUE THREAD

**Issue by arden** [gogf/gf#1160]
env:
go 1.15.3、windows 10、goland 2020.3、gf 1.15.3

go run main.go
no problem

but run test have problem, can't find config.toml

and my config.toml in work project dir that config/config.toml

![image](https://user-images.githubusercontent.com/11365/106836279-d30e6280-66d3-11eb-81de-1cf66d97743f.png)

**Comment by gqcn** [comment]
@arden The Goland automatically sets the working directory to the temporary folder of current system. Please change your working directory manually in your IDE, like this:
![image](https://user-images.githubusercontent.com/26347176/107018426-61214080-67db-11eb-982d-f8c481b3f531.png)
