### ISSUE TITLE
关于httpclient的一个问题

### ISSUE THREAD

**Issue by osgochina** [gogf/gf#1163]
### 1. What version of `Go` and system type/arch are you using?

go version go1.15.6 linux/amd64

### 2. What version of `GoFrame` are you using?

github.com/gogf/gf v1.15.3

### 3. Can this issue be reproduced with the latest release?
yes

### 4. What did you do?

不晓得这算不算bug，不过总的来说是影响使用的。代码如下：
```
    httpclient := g.Client()
    SetHeader("Host","example.com")
    response, _ := httpclient.Get("http://127.0.0.1:80/api/get_config")
```
这种情况下，Host参数没有起作用，跟进代码，发现
```
	// It's necessary set the req.Host if you want to custom the host value of the request.
	// It uses the "Host" value from header if it's not set in the request.
	if host := req.Header.Get("Host"); host != "" && req.Host == "" {
		req.Host = host
	}
```
这个代码发现了`req.Host == "" ` 这个判断，因为在`DoRequest`的时候已经根据域名生成了`req.Host`，造成`req.Host = host`这个逻辑永远执行不到。
不晓得我理解是不是有误，还是说有其他的使用方法，望回复！

**Comment by gqcn** [comment]
@osgochina 感谢反馈，确实可以改进一下。
