### ISSUE TITLE
配置管理页面，注意事项中的示例代码没有达到预期。

### ISSUE THREAD

**Issue by chenkby** [gogf/gf#1166]
### 1. What version of `Go` and system type/arch are you using?

go version go1.15.8 darwin/amd64

### 2. What version of `GoFrame` are you using?

GoFrame CLI Tool v1.15.0, https://goframe.org
Install Path: /usr/local/bin/gf
Build Detail:
  Go Version:  go1.15.5
  GF Version:  v1.15.1

### 3. Can this issue be reproduced with the latest release?

Y

### 4. What did you do?

[https://goframe.org/pages/viewpage.action?pageId=1114668](https://goframe.org/pages/viewpage.action?pageId=1114668)

此页面注意事项中的示例代码，在本地运行结果不一致。
```
code:
	content := `{"map":{"key":"value"}, "slice":[59,90]}`
	gcfg.SetContent(content)
	defer gcfg.RemoveContent()

	m := g.Cfg().GetMap("map")
	fmt.Println(m)

	s := g.Cfg().GetArray("slice")
	fmt.Println(s)

        fmt.Println(gcfg.GetContent())
```

```
output:

map[]
[]
{"map":{"key":"value"}, "slice":[59,90]}

```

**Comment by gqcn** [comment]
@chenkby 我试了最新版本，没这个问题。
