### ISSUE TITLE
About deleted soft and hard deletions

### ISSUE THREAD

**Issue by SliverHorn** [gogf/gf#1169]
### 1. What version of `Go` and system type/arch are you using?

`go version go1.14.14 darwin/amd64`

### 2. What version of `GoFrame` are you using?

`github.com/gogf/gf v1.15.3`

### 3. Can this issue be reproduced with the latest release?

yes

### 4. What did you do?

nil

### 5. What did you expect to see?

I want to delete a piece of data by passing parameters of the function or calling another method chained when I use Delete () to delete a piece of data when using gf's orm.

### 6. What did you see instead?

nil

### 7. Working with scen
- On a model object, there is a deleted_at field. The object can only be deleted softly by using the `delete 'function, but there is no api to call if you want to delete hard, and the document cannot be found.
```go
package model

import (
	"gorm.io/gorm"
	"time"
)

type Authority struct {
	CreatedAt time.Time      `orm:"created_at" json:"CreatedAt"`
	UpdatedAt time.Time      `orm:"updated_at" json:"UpdatedAt"`
	DeletedAt gorm.DeletedAt `orm:"deleted_at" json:"-" gorm:"index"`

	ParentId      string `json:"parentId" gorm:"comment:父角色ID"`
	AuthorityId   string `json:"authorityId" gorm:"not null;unique;primary_key;comment:角色ID;size:90"`
	AuthorityName string `json:"authorityName" gorm:"comment:角色名"`
	DefaultRouter string `json:"defaultRouter" gorm:"comment:默认菜单;default:dashboard"`

	Menus         []Menu      `orm:"-" json:"menus" gorm:"many2many:authorities_menus;foreignKey:AuthorityId;joinForeignKey:AuthorityId;References:ID;JoinReferences:MenuID"`
	Children      []Authority `orm:"-" json:"children" gorm:"-"`
	DataAuthority []Authority `orm:"-" json:"dataAuthorityId" gorm:"many2many:data_authorities;foreignKey:AuthorityId;joinForeignKey:AuthorityId;References:AuthorityId;JoinReferences:DataAuthority"`
}
```

### 8. Suggestion
- You can refer to gorm's idea of soft and hard deletion. [delete](https://gorm.io/zh_CN/docs/delete.html)
![image](https://user-images.githubusercontent.com/45428434/108086197-147a1700-70b1-11eb-98e3-aca4adf00373.png)

**Comment by SliverHorn** [comment]
![image](https://user-images.githubusercontent.com/45428434/108332810-325b8f00-720b-11eb-8456-862e482d20ec.png)
![image](https://user-images.githubusercontent.com/45428434/108332850-3ab3ca00-720b-11eb-9fd8-4e2ff43732ef.png)

**Comment by gqcn** [comment]
@SliverHorn https://goframe.org/pages/viewpage.action?pageId=1114139#ORM%E9%93%BE%E5%BC%8F%E6%93%8D%E4%BD%9C%E6%97%B6%E9%97%B4%E7%BB%B4%E6%8A%A4-Unscoped%E5%BF%BD%E7%95%A5%E6%97%B6%E9%97%B4%E7%89%B9%E6%80%A7
![image](https://user-images.githubusercontent.com/26347176/108847617-e0f03d00-761a-11eb-8221-ecb1005cdf26.png)

**Comment by SliverHorn** [comment]
> @SliverHorn https://goframe.org/pages/viewpage.action?pageId=1114139#ORM%E9%93%BE%E5%BC%8F%E6%93%8D%E4%BD%9C%E6%97%B6%E9%97%B4%E7%BB%B4%E6%8A%A4-Unscoped%E5%BF%BD%E7%95%A5%E6%97%B6%E9%97%B4%E7%89%B9%E6%80%A7
> ![image](https://user-images.githubusercontent.com/26347176/108847617-e0f03d00-761a-11eb-8221-ecb1005cdf26.png)

think you!
