### ISSUE TITLE
g.Config("test.toml") can not work

### ISSUE THREAD

**Issue by zjfsdnu** [gogf/gf#117]
### 1. What version of `Go` and system type/arch are you using?

go version go1.12 windows/amd64

### 2. What version of `GoFrame` are you using?

1.6.5
1.6.6

### 3. Can this issue be reproduced with the latest release?

yes

### 4. What did you do?

fmt.Println(g.Config("test.toml").GetFileName())

### 5. What did you expect to see?

test.toml

### 6. What did you see instead?

config.toml

**Comment by zjfsdnu** [comment]
In goframe V1.5.23 it works fine

**Comment by johngcn** [comment]
@zjfsdnu 从1.6开始是指定单例对象的名称，不是配置文件名称了，因为增加了可自定义配置内容的特性

**Comment by zjfsdnu** [comment]
1.6开始应该这样使用了
`g.Config("test").SetFileName("test.toml")`

**Comment by zjfsdnu** [comment]
1.6开始应该这样使用了
g.Config("test").SetFileName("test.toml")
