### ISSUE TITLE
希望封装 ghttp.Post json

### ISSUE THREAD

**Issue by 15951836388** [gogf/gf#1170]
ghttp.Post json 时，每次都要先手动转换成json再发送，比较繁琐

希望能封装下，直接传入数据 ,方法内自动json化，然后发送

```
		bs, err := gparser.VarToJson(map[string]string{
			"accountID": m.Account,
			"pwd":       m.Pwd,
		})
		if err != nil {
			glog.Error("err", err.Error())
			return
		}
		r, e := ghttp.Post(conf.Server.LoginUrl, string(bs))
```

**Comment by gqcn** [comment]
@15951836388 https://goframe.org/pages/viewpage.action?pageId=1114277
![image](https://user-images.githubusercontent.com/26347176/108628214-a5c40180-7494-11eb-9df4-ffbe5006c911.png)
