### ISSUE TITLE
请问goframe是否存在最小化方案？

### ISSUE THREAD

**Issue by lizhuoqi** [gogf/gf#1171]
### 1. What version of `Go` and system type/arch are you using?

go 1.16

### 2. What version of `GoFrame` are you using?

require (
	github.com/gogf/gf v1.15.3
	github.com/mattn/go-runewidth v0.0.10 // indirect
)

### 3.我的问题：`goframe 有最小化方案吗？`
我在windows按照文档的那个helloworld例子，编译出来的exe有17M。
我是不是可以理解为，里面打包了很多框架的内容？

那如果我只是用gf来写一些微服务的业务逻辑的，有些webserver的模块都可以不需要，这个时候如何精简？

**Comment by LonelySally** [comment]
虽说是按需打包,其实框架web内核部分还是有调用其它模块的东西(像gconv) 只要被引用到就会被打包进来.建议用golang自身的web组件然后调用自己需要的goframe模块功能.

**Comment by gqcn** [comment]
@lizhuoqi @LonelySally `ghttp`本身功能比较多，依赖的包也比较多。一般的业务项目编译下来16-30MB。

**Comment by housemecn** [comment]
> ### 1. What version of `Go` and system type/arch are you using?
> go 1.16
> 
> ### 2. What version of `GoFrame` are you using?
> require (
> github.com/gogf/gf v1.15.3
> github.com/mattn/go-runewidth v0.0.10 // indirect
> )
> 
> ### 3.我的问题：`goframe 有最小化方案吗？`
> 我在windows按照文档的那个helloworld例子，编译出来的exe有17M。
> 我是不是可以理解为，里面打包了很多框架的内容？
> 
> 那如果我只是用gf来写一些微服务的业务逻辑的，有些webserver的模块都可以不需要，这个时候如何精简？

go 1.16 版本打包会更小，原来1.15及一下的版本一般比1.1.6的大几兆，同样的代码

**Comment by 888go** [comment]
实测了下, 文件大小初始运行内存没关系, gin 15m, gf也是15m , 之前我还觉得编译后文件大, 应该占用更大的内存.
