### ISSUE TITLE
[bug]g.Client().GetVar().Scan()无法转换float64

### ISSUE THREAD

**Issue by orchie** [gogf/gf#1172]
### 1. What version of `Go` and system type/arch are you using?
1.15.5
### 2. What version of `GoFrame` are you using?
1.15.3

### 3. Can this issue be reproduced with the latest release?
api的json数据为
```
[
    {
        "indexPrice": "5.2"
    }
]
```
code为
```
type res struct{
    IndexPrice      float64
}
var pr []*res 
g.Client().GetVar(apiUrl).Scan(&pr)
```
打印出来 pr 拿不到值. 
但如果 type 里 IndexPrice      类型为 string 就可以拿到值  
所以这里缺少一个根据struct字段类型自动转换的功能.

### 5. What did you expect to see?

如果能自动把string转换为 float64 就完美了!(其他类型同理)

**Comment by gqcn** [comment]
@orchie 那是因为底层其实使用的是标准库的`json`包，标准库不支持。
```go
package main

import (
	"fmt"
	"github.com/gogf/gf/internal/json"
	_ "github.com/gogf/gf/net/ghttp"
)

func main() {
	s := `[{"indexPrice":"5.2"}]`
	type res struct {
		IndexPrice float64
	}
	var pr []*res
	json.Unmarshal([]byte(s), &pr)
	fmt.Println(pr[0].IndexPrice)
}
```
大家可以一起看看，你也可以研究下提个pr最好。

**Comment by gqcn** [comment]
@orchie 此外，你可以这里也可以考虑使用泛型满足你的要求，例子：
```go
package main

import (
	"fmt"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/internal/json"
	_ "github.com/gogf/gf/net/ghttp"
)

func main() {
	s := `[{"indexPrice":"5.2"}]`
	type res struct {
		IndexPrice g.Var
	}
	var pr []*res
	json.Unmarshal([]byte(s), &pr)
	fmt.Println(pr[0].IndexPrice.Float64())
}
```

**Comment by orchie** [comment]
> @orchie 此外，你可以这里也可以考虑使用泛型满足你的要求，例子：
> 
> ```go
> package main
> 
> import (
> 	"fmt"
> 	"github.com/gogf/gf/frame/g"
> 	"github.com/gogf/gf/internal/json"
> 	_ "github.com/gogf/gf/net/ghttp"
> )
> 
> func main() {
> 	s := `[{"indexPrice":"5.2"}]`
> 	type res struct {
> 		IndexPrice g.Var
> 	}
> 	var pr []*res
> 	json.Unmarshal([]byte(s), &pr)
> 	fmt.Println(pr[0].IndexPrice.Float64())
> }
> ```

感谢!
另外我在orm的结果scan时发现了类似的情况
```
	// res := []g.MapStrStr{}
        // res:=[]*CustomerStruct
	res := []g.Var{}
	model.Fields("money").Order("`timestamp` desc").Limit(2000).Scan(&res)
```
其中 struct 与 gvar都是可以扫描到的
但是map不行 .
当然实现方式是可以用var 和 struct 去代替的

但有的地方 如果可以用 map的话 会更方便一些
希望可以的话 实现这个功能 👍

**Comment by gqcn** [comment]
@orchie 好建议，一起考虑进去。
