### ISSUE TITLE
建议websocket 增加protobuf 协议支持 ,

### ISSUE THREAD

**Issue by fzqk9** [gogf/gf#1173]
,建议websocket 增加protobuf 协议支持  ,   很多场景应用会使用protobuf 做通讯 

可以参考　　 https://studygolang.com/articles/27999   　<<Vue 使用websocket + json + protobuf 与后端交互golang>>

**Comment by gqcn** [comment]
@fzqk9 `protobuf`本来就支持数据的序列化和反序列化，还需要女朋友做什么呢？
```go
// 使用protobuf解析
pbr := &pb.ChatRequest{}
err = proto.Unmarshal(message, pbr)
if err != nil {
    log.Fatalf("proto 解析失败 %v", err)
    break
}
```

**Comment by zjfsdnu** [comment]
他是想在文档里增加个演示示例吧

**Comment by housemecn** [comment]
正好需要，游戏走起
