### ISSUE TITLE
Update condition is not delete_at IS NULL

### ISSUE THREAD

**Issue by Desdemo** [gogf/gf#1175]
### 1. What version of `Go` and system type/arch are you using?
go version go1.14.14 windows/amd64

### 2. What version of `GoFrame` are you using?

v1.15.3

### 3. Can this issue be reproduced with the latest release?
i don't know
### 4. What did you do?
```go
type Item struct {
	Id        int64
	Name      string
	DeletedAt *gtime.Time `orm:"deleted_at"          json:"deleted_at"` // 删除时间
}

db.SetDebug(true)

	item := &Item{
		Name: "测试",
	}
	result, err := db.Table("item").Where(`name = "D222222222"`).Update(item)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(result)

```

### 5. What did you expect to see?
```sql
UPDATE `item` SET `deleted_at`=null,`id`=0,`name`='测试' WHERE name = "D222222222" AND `deleted_at` IS NULL
```

### 6. What did you see instead?

// 2021-02-23 14:23:03.927 [DEBU] [  6 ms] [default] SHOW FULL COLUMNS FROM `item`
// 2021-02-23 14:23:03.945 [DEBU] [  7 ms] [default] UPDATE `item` SET `deleted_at`=null,`id`=0,`name`='测试' WHERE name = "D222222222"

**Comment by gqcn** [comment]
@Desdemo Do you expect 
```
UPDATE `item` SET `id`=0,`name`='测试' WHERE name = "D222222222" AND `deleted_at` IS NULL
```

**Comment by Desdemo** [comment]
Yes, I know the query has this
```
`deleted_at` IS NULL
```

**Comment by Desdemo** [comment]
> @Desdemo Do you expect
> 
> ```sql
> UPDATE `item` SET `id`=0,`name`='测试' WHERE name = "D222222222" AND `deleted_at` IS NULL
> ```

**Comment by Desdemo** [comment]
@gqcn 
So now I can only add  delete conditions manually?
ex:
```go 
model = model.Where("DeletedAt IS NULL")
```

**Comment by gqcn** [comment]
@Desdemo Try this:
```go
db.Model("item").Where(g.Map{
    `name`:       `D222222222`,
    `deleted_at`: nil,
}).FieldsEx(`deleted_at`).Update(item)
```

**Comment by gqcn** [comment]
@Desdemo Try this:
```go
db.Model("item").Where(g.Map{
    `name`:       `D222222222`,
    `deleted_at`: nil,
}).FieldsEx(`deleted_at`).Update(item)
```
