### ISSUE TITLE
普通类型至struct类型转换不成功

### ISSUE THREAD

**Issue by magicostly** [gogf/gf#1178]
### 1. What version of `Go` and system type/arch are you using?

go version go1.14.6 windows/amd64

### 2. What version of `GoFrame` are you using?

gf v1.15.3

### 4. What did you do?

```go
func main() {
    var v g.Var

    v.Set("123")

    fmt.Println(v.Val())

    // struct转换
    type Score struct {
        Value int
    }
    s := new(Score)
    v.Struct(s)
    fmt.Println(s)
}
```

### 5. What did you expect to see?

文档表示输出
```
123
&{123}
```

### 6. What did you see instead?
但实际输出为：
```
123
&{0}
```

**Comment by gqcn** [comment]
@magicostly 你好，从某个版本开始，为保证转换的严谨性，这种不带属性名称的`struct`转换已经不支持了，示例代码没有来得及更新，感谢反馈。
