### ISSUE TITLE
Parse ，get 请求时，无法成功

### ISSUE THREAD

**Issue by 15951836388** [gogf/gf#1179]
![image](https://user-images.githubusercontent.com/14047483/109128498-84ac2b00-778a-11eb-8750-9a46d5d1fddf.png)

客户发送的是json
文档里说get是可以的，折腾了半天

**Comment by gqcn** [comment]
@15951836388 没看懂呢，能详细描述一下吗？

**Comment by 15951836388** [comment]
group.get()时，r.parse，解析出来的是空值。 post（）是可以正常解析的

**Comment by gqcn** [comment]
> g.Client().ContentJson().get
> group.get()时，r.parse，解析出来的是空值。
> 
> g.Client().ContentJson().Post
> group.post（）是可以正常解析的

`Get`只支持`Query String`，你没发提交`JSON`内容哦。

**Comment by 15951836388** [comment]
我的意思，get时，发来的json，解析出来的是空值。

是故意这样设计的，还是bug？

**Comment by gqcn** [comment]
> 我的意思，get时，发来的json，解析出来的是空值。
> 
> 是故意这样设计的，还是bug？

因为一些特殊原因，近期`github`老是打不开，你的回复我尝试了n次都失败了。你这个问题是因为`get`请求无法提交`json`内容参数的。不过你骚等，我做下兼容你再试试。

**Comment by gqcn** [comment]
@15951836388 再试试

**Comment by 15951836388** [comment]
v1.15.4 依然不行

**Comment by LonelySally** [comment]
> v1.15.4 依然不行

拉master
