### ISSUE TITLE
执行go build的时候无法打包。环境windows goland

### ISSUE THREAD

**Issue by dotcool** [gogf/gf#118]
main.go:4:2: cannot find package "github.com/gogf/gf-demos/boot" in any of:

**Comment by johngcn** [comment]
你要启用`go modules`功能，参考开发文档：https://goframe.org/prepare/gomodule

**Comment by dotcool** [comment]
好的，还有一个问题。你们这个可以支持分布式 微服务么。我看基本功能很完善，但是么有分布式这方面的东西

**Comment by johngcn** [comment]
@dotcool 
嗯，确实没有微服务的相关组件。

其实微服务核心的是架构部署这套东西，因为未来的微服务架构是容器化编排部署的架构，`Kubernetes`那套东西可以很方便的实现服务注册发现，`Istio`可以很方便地实现对流量的管理。所以我要推的并不是传统的微服务架构，而是未来的容器化架构。现在再做传统微服务架构没有意义，未来三至五年后就会被淘汰。

其次是RPC通信这块，如果使用`grpc`/`thrift`的话官方也提供了相应的服务端，这种情况下主流的`Web`框架也失去了意义，而`GF`可以作为一个强大的工具集来使用。另外如果是`HTTP/RESTful`这套的话可以通过`GF`很方便实现。

**Comment by dotcool** [comment]
好的。点赞
