### ISSUE TITLE
http.BindHandler 为什么 不加上  get post，现在默认是all

### ISSUE THREAD

**Issue by 15951836388** [gogf/gf#1180]
rt

**Comment by gqcn** [comment]
@15951836388 具体请查看文档：https://goframe.org/pages/viewpage.action?pageId=1114257

**Comment by 15951836388** [comment]
我的意思是，BindHandler 也提供 可以调用的get post方法，而不是用这样的字符串 "GET:/{table}/list/{page}.html"

**Comment by gqcn** [comment]
> 我的意思是，BindHandler 也提供 可以调用的get post方法，而不是用这样的字符串 "GET:/{table}/list/{page}.html"

你好，`BindHandler`只是最原始路由绑定方式，更便捷的路由注册建议使用分组路由方式：https://goframe.org/pages/viewpage.action?pageId=1114517

**Comment by 15951836388** [comment]
不想用group时，也想简单get和post。好的框架不是应该让用户自由点，不处处受限制吗？
为何要人为的限制用户怎么用？这里似乎也没什么别的好处啊？
