### ISSUE TITLE
orm ScanList关联查询在数据匹配时可能存在问题。

### ISSUE THREAD

**Issue by Tiller-Mu** [gogf/gf#1181]
### 1. What version of `Go` and system type/arch are you using?
go 1.15.6

### 2. What version of `GoFrame` are you using?
github.com/gogf/gf v1.15.3

### 3. Can this issue be reproduced with the latest release?
是的

### 4. What did you do?
在使用`ScanList`做关联查询时， 疑似`gf orm`存在问题，当查询第一个表只有单条记录情况下，查询关联表没有得到数据，数据关联时，会返回`Error sql: no rows in result set`。
如果查询第一个表有多条记录，查询第二个关联表有部分记录可以与第一次的结果匹配，那么没有报这个错误。
```go
var list []model.RecordAndMedicationList
if err := dao.DB.Table("comm_medical_record").Page((req.Page-1)*req.Limit, req.Limit).Where(dao.genCond(req)).Order("create_time desc").
ScanList(&list, "Record"); err != nil {
g.Log().Ctx(ctx).Warning("查询病例记录失败:", err, req)
return nil, 500
}

if err := dao.DB.Table("comm_medications").
Where("Medic_Record_Id", gdb.ListItemValuesUnique(list, "Record", "RecordId")).
ScanList(&list, "Medications", "Record", "medic_record_id:RecordId"); err != nil {
g.Log().Ctx(ctx).Warning("查询病例记录关联的用药记录失败:", err, req)
// return nil, 500 暂时注释掉

}

return &list, 200
```

### 5. What did you expect to see?
希望`ScanList`在没有查询到关联结果时，返回`nil`，仅仅由于字段不匹配、数据库连接错误等问题再返回error

**Comment by gqcn** [comment]
@Tiller-Mu 我仔细看看确认下哈。

**Comment by gqcn** [comment]
@Tiller-Mu 我试了没复现呢，要不你用`master`分支再试试，如果问题依旧请提交一下可复现此问题的代码我运行试试。

**Comment by Tiller-Mu** [comment]
多谢啦，gf版本更新到1.15.4，问题就没有复现了。
