### ISSUE TITLE
ORM原生方法不支持slice

### ISSUE THREAD

**Issue by yanllllk** [gogf/gf#1182]
### 1. What version of `Go` and system type/arch are you using?
go 1.16, windows/amd64

### 2. What version of `GoFrame` are you using?

1.15.3

### 3. Can this issue be reproduced with the latest release?

yes

### 4. What did you do?

g.DB().GetValue("select * from tbl where dept_id in (?)",g.slice{1,2,3,4,5}) 出错

### 5. What did you expect to see?
type: unsupported type []interface {}, a slice of interface,

**Comment by yanllllk** [comment]
https://github.com/gogf/gf/issues/125
 说是在1.8就支持此特性,但目前并没有

**Comment by gqcn** [comment]
@yanllllk Let me have a check.
