### ISSUE TITLE
是否有可能将所有依赖包都转为支持gomodule？

### ISSUE THREAD

**Issue by lurise** [gogf/gf#1184]
### 1. What version of `Go` and system type/arch are you using?
go 1.15，windows

### 2. What version of `GoFrame` are you using?

1.15.3

### 3. Can this issue be reproduced with the latest release?
是的

### 4. What did you do?

公司属于内网开发，使用athens作为goproxy代理服务器，我将gf插件转入内网的时候，也同步将依赖包全部转入athens缓存中，这样各位同事开发时，可以很方便的形成可开发环境。但在测试gf的过程中，发现gf框架的一个依赖包为github.com/olekukonko/tablewriter v0.0.1，这个版本的tablewriter是未使用gomodules的，所以go mod会直接请求代理地址来找寻tablewriter所依赖的github.com/mattn/go-runewidth最新依赖包，进而对于内网开发而言形成了一场灾难，导致内网无法正常使用。

### 5. What did you expect to see?
是想了解下，是否有可能将其实不太多的依赖都使用gomodules的版本。其实对于github.com/olekukonko/tablewriter这个库而言，自2019年5月就已经加入了gomodules支持，即从v0.0.2版本开始就支持gomodules了，不知道该版本是否支持gf框架使用，如果支持的话，是否可以更新为这个版本呢？这样我们内网支持起来将会更方便一些，万分感谢！

### 6. What did you see instead?
目前因为tablewriter的v0.0.1版本不支持gomodules，导致目前内网开发在不修改任何内容的情况下无法正常使用。

**Comment by gqcn** [comment]
@lurise 抱歉，最近github大姨妈，搭上梯子才处理到你这个问题，目前已升级`tablewriter`版本为最新版，欢迎使用最新的`gf`版本试试。

**Comment by lurise** [comment]
> @lurise 抱歉，最近github大姨妈，搭上梯子才处理到你这个问题，目前已升级`tablewriter`版本为最新版，欢迎使用最新的`gf`版本试试。

万分感谢
