### ISSUE TITLE
希望在gorm的model定义的struct中提供gtime的支持

### ISSUE THREAD

**Issue by sleepreading** [gogf/gf#1186]
```
type User struct {
	CreatedAt     gtime.Time
}
```

**Comment by gqcn** [comment]
@sleepreading 现在支持的呀，你遇到什么问题么？

**Comment by gqcn** [comment]
@sleepreading 现在支持的呀，你遇到什么问题么？

**Comment by sleepreading** [comment]
像上面的代码, 进行 `AutoMigrate()` 调用的时候, 会报错哦. 换用`time.Time`就可以了.
之所以不想用 `time.Time` 是因为在返回json时(复用该结构体), 其时间格式不好看.
具体的报错信息我没有保存了, 应该可以模拟出来的.
后来我修改了下gtime,问题不存在了

而且`gtime`要想支持gorm还至少需要增加以下实现吧:
```
func (o Time) Value() (driver.Value, error) {
}
func (o *Time) Scan(v interface{}) error {
}
```
