### ISSUE TITLE
请问你们这个框架是否会一直更新或者技术支持呢

### ISSUE THREAD

**Issue by dotcool** [gogf/gf#119]
如果使用你们框架后期做东西如果遇到问题希望得到官方的支持哦。还有就是你们有实例么

**Comment by dotcool** [comment]
比如jwt，我们主要做移动端的api服务

**Comment by johngcn** [comment]
@dotcool 
若有问题请先查阅开发文档 https://goframe.org ，介绍得比较详细。JWT的话有个插件你可以看下 https://github.com/gogf/gf-jwt 。

文档解决不了的问题请提`issue`咨询。
