### ISSUE TITLE
测试找不到配置文件

### ISSUE THREAD

**Issue by fengzhongyun1992** [gogf/gf#1190]
### 1. What version of `Go` and system type/arch are you using?

go version go1.16 windows/amd64

### 2. What version of `GoFrame` are you using?
gf  v1.15.3

### 3. 数据库
sqlite3

### 4. 测试报错,找不到配置文件

```
panic: configuration file "config.toml" not found, did you miss the configuration file or the file name setting?

```
（手动复制配置文件到测试文件目录可以成功）

**Comment by fengzhongyun1992** [comment]
升级到 gf v1.15.4 问题并没有解决，
发现  gcfg.go 80行
```
	// Dir path of main package.
		if mainPath := gfile.MainPkgPath(); mainPath != "" && gfile.Exists(mainPath) {
			if err := c.AddPath(mainPath); err != nil {
				intlog.Error(err)
			
```
 Dir path of main package,  没有找到文件夹，gfile_source.go **MainPkgPath** 函数返回为空

gf 1.15.1  （没有问题）
![image](https://user-images.githubusercontent.com/20684744/110431503-da68c780-80e8-11eb-9d5c-1f81f79b9636.png)

gf 1.15.4 （有问题）

![image](https://user-images.githubusercontent.com/20684744/110431584-f0768800-80e8-11eb-8902-e24abef0c977.png)


只会在当前文件夹或系统临时文件夹寻找配置文件，最终导致找不到配置文件

**Comment by dangwy** [comment]
是还有问题！

**Comment by gqcn** [comment]
@fengzhongyun1992 因为`MainPkgPath`无法从`init`包初始化方法中获取，细节不多讲了。你可以在测试程序的最前面清空并设置一下配置文件的目录路径，例如在你的`test`包中加上一个`init`方法，并通过配置单例对象设置一下配置文件的路径。
