### ISSUE TITLE
"go.opentelemetry.io/otel/label" v0.18.0 版本修改了包名，导致引入 gredis 不能编译

### ISSUE THREAD

**Issue by DukeAnn** [gogf/gf#1193]
详情 https://github.com/open-telemetry/opentelemetry-go/pull/1635

如果执行 `go get -u` 就会失败，官方骚气的同大版本不兼容写法

**Comment by GuihaiHU** [comment]
请问怎么解决呢

**Comment by DukeAnn** [comment]
> 请问怎么解决呢

执行 `go get go.opentelemetry.io/otel/label@v0.17.0`

**Comment by housemecn** [comment]
> 请问怎么解决呢

可以go get -u -v github.com/gogf/gf@master 
不要在项目下执行go get -u all 
默认会升级到 go.opentelemetry.io/otel/label@v0.19.0 现在0.18.0 和0.19.0有差别

**Comment by gqcn** [comment]
@housemecn @GuihaiHU @DukeAnn 主要原因是由于`otel`不稳定造成的，并且`go get -u all`命令会更新所有依赖包的版本，项目依赖的包版本尽量别随意升级。`gf`已经更新兼容了最新`0.19.0`版本的`otel`版本，不过未来可能会随时保持和`otel`版本的升级。

**Comment by DukeAnn** [comment]
> @housemecn @GuihaiHU @DukeAnn 主要原因是由于`otel`不稳定造成的，并且`go get -u all`命令会更新所有依赖包的版本，项目依赖的包版本尽量别随意升级。`gf`已经更新兼容了最新`0.19.0`版本的`otel`版本，不过未来可能会随时保持和`otel`版本的升级。

好的感谢大佬，问题先关了。
