### ISSUE TITLE
ghttp client supports io.Reader in Post

### ISSUE THREAD

**Issue by bohea** [gogf/gf#1195]
### 1. What version of `Go` and system type/arch are you using?

go 1.15   darwin/amd64

### 2. What version of `GoFrame` are you using?

github.com/gogf/gf v1.15.0

### 5. What did you expect to see?

ghttp.Client  support not only local files but also io.reader upload

becuase sometimes,  files are already in memory as []byte for example, it make no sense to save them as tempfiles before post 

### 6. What did you see instead?

add func PostFiles in ghttp.Client, so ghttp client can post file like object directly 

```
type FormFile struct {
	Key string
	Name string
	FileReader io.Reader
}

func (c *Client)PostFiles(url string, files *[]FormFile, data ...interface{}) (*ClientResponse, error) {
	return DoRequestWithFiles("POST", url, files, data...)
}


func (c *Client)DoRequestWithFiles(method, url string, files *[]FormFile, data ...interface{}) (resp *ClientResponse, err error) {
	if len(*files) > 0 {
		for _, vf := range *files {
			if file, err := writer.CreateFormFile(vf.Key, vf.Name); err == nil {
				if _, err = io.Copy(file, vf.FileReader); err != nil {
					return nil, err
				}
			} else {
				return nil, err
			}
		}

	}
	return nil, nil
}

```

user's code: 

```
var b = []byte{'1', '2', '3'}

var vfile = FormFile{
	Key: "vfile",
	Name: "abc.png",
	FileReader: bytes.NewReader(b),
}

var files = &[]FormFile{vfile}

var r, err = g.Client().PostFiles(url, files)

```

**Comment by Rebellioncry** [comment]
@gqcn 这个功能做的怎么样了？不能直接传文件流太不合理了吧 
How is this feature doing? It doesn't make sense not to stream files directly
