### ISSUE TITLE
gf1.15.4 用到的opentelemetry库版本太老

### ISSUE THREAD

**Issue by dangwy** [gogf/gf#1198]
gf1.15.4 用到的opentelemetry库版本太老：

..\..\pkg\mod\github.com\gogf\gf@v1.15.4\net\gtrace\gtrace.go:16:2: no required module provides package go.opentelemetry.io/otel/label; to add it:
	go get go.opentelemetry.io/otel/label

**Comment by housemecn** [comment]
go get -u github.com/gogf/gf@master

已经更新到了v0.18.0 https://github.com/gogf/gf/commit/6a24b595f0de17d2c217fc3af4ac82e46fa93b1f

**Comment by dangwy** [comment]
修复了。
