### ISSUE TITLE
MySQL数据初始化问题！

### ISSUE THREAD

**Issue by snail007** [gogf/gf#120]
即使我不配置MySQL，gf也会默认初始化MySQL驱动，调用sql.open，导致使用第三方MySQL库，sql驱动报错，重复的open调用。

**Comment by johngcn** [comment]
@snail007 准确的说会自动调用`sql.Register`注册数据库引擎接口，能否提供复现问题的代码？
![image](https://user-images.githubusercontent.com/26347176/57118922-f4bd1600-6d98-11e9-930b-4d6380a99656.png)

**Comment by johngcn** [comment]
@snail007 不用给我测试代码了，我已做了完美的处理，你更新最新的`v1.6.7`再试试。

**Comment by snail007** [comment]
OK，有空试一下，辛苦:smile:

**Comment by snail007** [comment]
已经验证没问题.
