### ISSUE TITLE
`gf gen dao` will generate a field with int when the field is tinyint(1) in mysql

### ISSUE THREAD

**Issue by GuihaiHU** [gogf/gf#1200]
### 1. What version of `Go` and system type/arch are you using?
go version go1.15.6 darwin/amd64

### 2. What version of `GoFrame` are you using?
github.com/gogf/gf v1.15.4

### 3. Can this issue be reproduced with the latest release?
Yes

### 4. What did you do?

I run`gf gen dao` and `gf` generate a field with type `int` when the field is `tinyint(1)` in mysql. For Example, Field `IsActive` is generated as type `int`

```sql

CREATE TABLE IF NOT EXISTS `auth_user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `is_active` tinyint default 0 ,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```

``` go
type User struct {
	Id          uint        `orm:"id,primary"      json:"id"`          //
	Username    string      `orm:"username,unique" json:"username"`    //
	Password    string      `orm:"password"        json:"password"`    //
	IsActive      int        `orm:"is_active"          json:"isActive"` 
}
```

### 5. What did you expect to see?
How do I generate `IsActive` with type`bool` by `gf`

**Comment by housemecn** [comment]
How does the Boolean type identify these three states?

**Comment by GuihaiHU** [comment]
> How does the Boolean type identify these three states?

sorry for error comment

**Comment by GuihaiHU** [comment]
I got the answer.

If I want to override the field type generate by `gf gen dao`, I just need to write in `/model/user.go` like this
```

type User struct {
	internal.User
	IsActive bool `orm:"is_active"       json:"isActive"` //
}

```
