### ISSUE TITLE
r.Router.Uri方法在全局中间件和局部中间件获取到的值不一致

### ISSUE THREAD

**Issue by develop1024** [gogf/gf#1206]
![微信图片_20210328135739](https://user-images.githubusercontent.com/52775415/112743873-9bce7a80-8fcd-11eb-8c88-bd1c7b8a2a38.png)

**Comment by LonelySally** [comment]
顺序关系就是如此.全局中间件->路由解析->局部中间件->控制器->局部后置中间件->全局后置中间件->响应

**Comment by gqcn** [comment]
@develop1024 我想你需要的是分组路由中间件，建议你再看看全局中间件和分组路由中间件的区别：https://goframe.org/pages/viewpage.action?pageId=1114315
