### ISSUE TITLE
orm能否增加Scopes功能

### ISSUE THREAD

**Issue by 1307super** [gogf/gf#1207]
在查询数据的时候,经常会用到同一个逻辑,比如根据数据权限查询
能否增加一个Scopes方法, 如: https://www.kancloud.cn/sliver_horn/gorm/1861182 一样

**Comment by gqcn** [comment]
@1307super 这个建议可以，我先排期吧，也欢迎贡献PR。

**Comment by gqcn** [comment]
https://goframe.org/pages/viewpage.action?pageId=20087340
