### ISSUE TITLE
gcfg遍历问题

### ISSUE THREAD

**Issue by snail007** [gogf/gf#121]
例如有如下配置文件,nodes.toml
[hk]
hk01="10.0.0.1"
hk02="10.0.0.2"
[cn]
cn01="10.0.0.1"
cn02="10.0.0.2"

如何遍历得到,hk和cn,以及他们下面的key(hk01,hk01,cn01,cn02)和对应的key值.

**Comment by johngcn** [comment]
@snail007 
首先你可以使用数组类型，推荐这么做，`toml`类型是支持数组的，随后通过`GetArray`方法可以获得数组列表。
如果实在是不想用数组，那么你可以通过`pattern`参数传递适当的键名/索引数值即可，如：`Get(fmt.Sprintf("cn.cn0%d", index))`，当然效率会稍微低一些。

此外，`gcfg`/`gconv`是支持配置文件数据到`struct`对象的映射转换的（也可以只获取某部分），可以考虑定义特定模块的配置对象，直接映射到对象属性中。
