### ISSUE TITLE
gf v1.15.6中的gtimer误差太大了

### ISSUE THREAD

**Issue by widon1104** [gogf/gf#1210]
### 1. What version of `Go` and system type/arch are you using?
➜  ~ go version
go version go1.14.4 linux/amd64

### 2. What version of `GoFrame` are you using?

require github.com/gogf/gf v1.15.6

### 3. Can this issue be reproduced with the latest release?
yes

### 4. What did you do?

写了一个简单的程序，gtimer回调会跑10次，结果误差达到了0.4s，感觉误差太大了
```
func main() {
	fmt.Println("main begin", time.Now())
	var count = 1
	gtimer.Add(time.Second, func() {
		fmt.Println("time gtimer:", count, time.Now())
		count++
	})
	time.Sleep(10 * time.Second)
}
```
运行结果如下：
main begin 2021-04-05 15:26:00.202529061 +0800 CST m=+0.000344531
time gtimer: 1 2021-04-05 15:26:01.162751013 +0800 CST m=+0.960566487
time gtimer: 2 2021-04-05 15:26:02.122736295 +0800 CST m=+1.920551774
time gtimer: 3 2021-04-05 15:26:03.082685179 +0800 CST m=+2.880500660
time gtimer: 4 2021-04-05 15:26:04.042703171 +0800 CST m=+3.840518648
time gtimer: 5 2021-04-05 15:26:05.002694612 +0800 CST m=+4.800510102
time gtimer: 6 2021-04-05 15:26:05.962769642 +0800 CST m=+5.760585120
time gtimer: 7 2021-04-05 15:26:06.922763894 +0800 CST m=+6.720579381
time gtimer: 8 2021-04-05 15:26:07.882711793 +0800 CST m=+7.680527269
time gtimer: 9 2021-04-05 15:26:08.84271205 +0800 CST m=+8.640527529
time gtimer: 10 2021-04-05 15:26:09.802777667 +0800 CST m=+**9.600593139**

### 5. What did you expect to see?

误差应该很小才对

### 6. What did you see instead?

跑10次，误差就达到了0.4s

**Comment by widon1104** [comment]
又用time包的ticker写了一个程序，这个误差就非常小了，误差只有0.000x s
func main() {
	ticker1 := time.NewTicker(1 * time.Second)
	// 一定要调用Stop()，回收资源
	defer ticker1.Stop()
	var count = 1
	fmt.Println("begin main", time.Now())
	go func(t *time.Ticker) {
		for {
			<-t.C
			fmt.Println("Ticker:", count, time.Now())
			count++
		}
	}(ticker1)
	time.Sleep(10 * time.Second)
	fmt.Println("ok")
}

运行结果：
begin main 2021-04-05 15:36:16.537437869 +0800 CST m=+0.000086660
Ticker: 1 2021-04-05 15:36:17.537482789 +0800 CST m=+1.000131592
Ticker: 2 2021-04-05 15:36:18.537496773 +0800 CST m=+2.000145587
Ticker: 3 2021-04-05 15:36:19.537483459 +0800 CST m=+3.000132273
Ticker: 4 2021-04-05 15:36:20.537528898 +0800 CST m=+4.000177712
Ticker: 5 2021-04-05 15:36:21.537489228 +0800 CST m=+5.000138050
Ticker: 6 2021-04-05 15:36:22.537536762 +0800 CST m=+6.000185579
Ticker: 7 2021-04-05 15:36:23.537532197 +0800 CST m=+7.000181012
Ticker: 8 2021-04-05 15:36:24.537486215 +0800 CST m=+8.000135022
Ticker: 9 2021-04-05 15:36:25.537522417 +0800 CST m=+9.000171222
Ticker: 10 2021-04-05 15:36:26.537526466 +0800 CST m=+10.000175283

**Comment by housemecn** [comment]
我这边是越转越快了，每秒一次，最后是相隔900多毫秒就开始了

**Comment by hailaz** [comment]
按文档中所说的设计，gtimer不是一个高精度（<1ms）的定时器。
https://goframe.org/pages/viewpage.action?pageId=1114363

**Comment by gqcn** [comment]
@widon1104 请使用最新版本的`gtimer`试试。
