### ISSUE TITLE
gdb will lost accuracy which type is timestamp

### ISSUE THREAD

**Issue by jiuker** [gogf/gf#1212]
### 1. What version of `Go` and system type/arch are you using?

go version go1.16 linux/amd64

### 2. What version of `GoFrame` are you using?

main branch

### 3. Can this issue be reproduced with the latest release?
yes
### 4. What did you do?
https://github.com/gogf/gf/blob/master/database/gdb/gdb_core_structure.go 
line 102 
case timestamp
input is 'xxxx-xx-xx xx:xx:xx.yyyyyy'
out is 'xxxx-xx-xx xx:xx:xx'

### 5. What did you expect to see?

out is 'xxxx-xx-xx xx:xx:xx.yyyyyy'

### 6. What did you see instead?

out is 'xxxx-xx-xx xx:xx:xx'

**Comment by gqcn** [comment]
@jiuker Would you please given some codes that can reproduce this issue?

**Comment by gqcn** [comment]
Close issue as it's no active for more than 5 months.
