### ISSUE TITLE
hope add a global configuration that adds caching for queries by default

### ISSUE THREAD

**Issue by Golong-me** [gogf/gf#1216]
hope add a global configuration that adds caching for queries by default
希望添加一个全局配置,默认为查询添加缓存

**Comment by housemecn** [comment]
在boot/boot.go文件里添加一个默认配置

**Comment by gqcn** [comment]
@Golong-me 查询缓存功能是有的，具体请查看文档：https://goframe.org/pages/viewpage.action?pageId=1114346
