### ISSUE TITLE
请问gdb何时可以支持pgsql

### ISSUE THREAD

**Issue by iedwin** [gogf/gf#122]
在gdb的GoDoc中看到type目前仅支持mysql，请问有计划支持pgsql吗?

**Comment by johngcn** [comment]
@iedwin 你好，是支持`pgsql`的，请查看开发文档：https://goframe.org/database/gdb/database

**Comment by iedwin** [comment]
@johngcn 太好了！
我看到https://goframe.org/database/gdb/config里面的描述已经被改过来了，非常感谢！
