### ISSUE TITLE
bug in converting when there're same tags in struct

### ISSUE THREAD

**Issue by xushushun** [gogf/gf#1229]
```go
type Cs struct {
	Id  string `json:"id"`
	Pid string `json:"pid"`
	Ids string `json:"id"`
}

func Test_(t *testing.T) {
	params := g.Map{
		"id":  "im,id",
		"pid": "im,pid",
		"ids": "im,ids",
	}
	var cc *Cs
	gconv.Struct(params, &cc)
	g.Dump(cc)
}
```
以上是测试代码运行结果为 
```
{
	"pid": "im,pid"
}
```
不是预期的结果

**Comment by zcool321** [comment]
可以填写一下预期效果

**Comment by zcool321** [comment]
你看到的打印，不是实际结构
建议将    g.Dump(cc)   改为   fmt.Printf("%+v\n", cc)

实际赋值效果是&{Id: Pid:im,pid Ids:im,id}   
因为两个tag的id一样，覆盖了，仅保留了最后一个Ids string `json:"id"`

**Comment by zcool321** [comment]
这也暴露了一个g.Dump问题~看了下 go json encode 也没处理你这种情况

**Comment by gqcn** [comment]
@zcool321 @xushushun 这块是标准库的`json`包问题，`g.Dump`底层是使用的`json`包来实现的数据编码打印。这块可以改进一下，可能比较复杂一些，自行使用反射实现`g.Dump`，参考`PHP dump`方法的输出格式。

**Comment by gqcn** [comment]
测试翻译机器人。
