### ISSUE TITLE
[gf/net/ghttp] Want a custom download file handler instead of ServeFileDownload.

### ISSUE THREAD

**Issue by DeathPoem** [gogf/gf#1230]
[gf/net/ghttp] how to write a custom download file handler like ServeFileDownload?

### 1. What version of `Go` and system type/arch are you using?

go version go1.15.8

### 2. What version of `GoFrame` are you using?

github.com/gogf/gf v1.15.6

### 3. Can this issue be reproduced with the latest release?

yes 

### 4. What did you do?

I'm trying to implement a custom download file handler by consulting ServeFileDownload (our file storage is not a local file system but a storage service).

My problem is about  [this code](https://github.com/gogf/gf/blob/v1.15.6/net/ghttp/ghttp_response_writer.go#L23).

This variable is not exported, So I can't set it as true like [this line](https://github.com/gogf/gf/blob/v1.15.6/net/ghttp/ghttp_server_handler.go#L287)

And will got an error like comment in  [this code](https://github.com/gogf/gf/blob/v1.15.6/net/ghttp/ghttp_response_writer.go#L23) said, 

```
http: superfluous response.WriteHeader call from github.com/gogf/gf/net/ghttp.(*ResponseWriter).Flush
```

### 5. What did you expect to see?

If I want use goframe to implement my handler, what's the best solution? Thanks for your advice.

### 6. What did you see instead?

skip

**Comment by DeathPoem** [comment]
By now, I have two solution:

1. Use Response.SetBuffer() to copy content directly 
2. Add a SetWroteHeader function in goframe 's source code.

**Comment by gqcn** [comment]
@DeathPoem Sorry missing this issue, I'll handle it these this week.
