### ISSUE TITLE
gconv.Int和标准库(strconv.Atoi)的结果不一致

### ISSUE THREAD

**Issue by arieslee** [gogf/gf#1236]
### 1. What version of `Go` and system type/arch are you using?

Go版本 1.15.3 darwin adm64

### 2. What version of `GoFrame` are you using?

GoFrame版本 v1.15.6

### 3. What did you do?

```
numStr := "0120"
numInt, _ := strconv.Atoi(numStr)
g.Log().Line(true).Println("numInt by strconv", numInt)
g.Log().Line(true).Println("numInt by gconv.Int", gconv.Int(numStr))
```

在标准库中numInt=120

gconv.Int("0120")=80

**Comment by LonelySally** [comment]
终于有人跟我有同样的发现了...被当做8进制给处理掉了.

**Comment by arieslee** [comment]
> 终于有人跟我有同样的发现了...被当做8进制给处理掉了.

是的，8进制

**Comment by chenall** [comment]
我去年就提出了类似的问题。
https://github.com/gogf/gf/issues/993
转换规则不一样。

gconv 0x 开头认为16进制
0开头认为是8进制

**Comment by gqcn** [comment]
@chenall @arieslee @LonelySally 是的，`gconv`包有对字符串参数做自动进制检测，具体可以参考文档 https://goframe.org/pages/viewpage.action?pageId=1114317 ，这一点和标准库的`strconv`包逻辑不一致，经过仔细考虑，仍旧保留了该特性。

**Comment by LonelySally** [comment]
> @chenall @arieslee @LonelySally 是的，`gconv`包有对字符串参数做自动进制检测，具体可以参考文档 https://goframe.org/pages/viewpage.action?pageId=1114317 ，这一点和标准库的`strconv`包逻辑不一致，经过仔细考虑，仍旧保留了该特性。

可以在gconv出一个strconv.Atoi的别名方法 直接调用strconv.Atoi.

**Comment by chenall** [comment]
为了方便自己的使用,我修改了个版本, 目前可以满足我的使用需求.

https://github.com/chenall/gf/commit/f1e99fcf85a08d22372cfe0688d1754b274bf60c

gconv.Struct 允许指定使用 10 进制进行转换

实现方式算不上优雅,^_^.
