### ISSUE TITLE
How to remove certain session by session id？

### ISSUE THREAD

**Issue by Pingze-github** [gogf/gf#1238]
我尝试通过`session.setId()`设定固定的id，并通过`gsession.NewStorageMemory()`返回的storage对象的`RemoveAll(id)`方法清除指定id的session对象。
报错：
```
this feature is disabled in this storage
```
在仓库里搜了下源码，看起来redis和文件储存的版本，也都无法使用这个方法。

有其他手段能做到动态删除指定的session吗？为了实现即时踢人下线的功能

**Comment by steve-jokes** [comment]
目前这个功能还在 TODO 中, 我想请问一下目前有没有什么 work around 能够临时实现这个功能?
我的具体需求是在用户通过邮件异步重置账户密码以后, 移除之前一个 session 的登陆状态
当用户在不安全的设备上登陆并且忘记登出以后, 这个功能能够防止之前的设备继续使用相关功能
目前能想到的办法就是将登陆的 token 单独建表来处理, 但是这样的改动就大了
