### ISSUE TITLE
为gcharset模块添加更多的编码支持

### ISSUE THREAD

**Issue by johngcn** [gogf/gf#124]
目前`gcharset`模块使用的是`mahonia`第三方包实现的编码转换，但是支持的编码类型比较少，而且不支持常用的`gb2312`编码，并且该第三方包已不再维护。因此需要引入并且优先使用golang官方的`text/encoding`包来进行编码转换：https://github.com/golang/text/blob/master/encoding

`gb2312`的编码转换示例：https://segmentfault.com/q/1010000011081775

改进方案如下：
1. 将`text/encoding`包引入到`gf`框架的`third`目录下，路径为`/third/golang.org/x/text/encoding`；
1. 梳理golang官方的`text/encoding`包与`mahonia`包支持编码的差异；
1. 如果`mahonia`不支持的编码，引入`text/encoding`来实现；
1. 如果两者同时支持的编码，调整为`text/endoing`来实现；

**Comment by wenzi1** [comment]
好的，我改下
