### ISSUE TITLE
Can I generate model with pointer fields? gf gen dao生成的model结构体字段，能否选择指针类型?

### ISSUE THREAD

**Issue by LouZon** [gogf/gf#1243]
### 1. What version of `Go` and system type/arch are you using?

go 1.16 

### 2. What version of `GoFrame` are you using?

v1.15.7

### 4. Problems

I use `gf gen dao` to generate model from my database tables,  and I found that all my structure fields except `datetime` is not pointer,  which produce the following problems:

#### when I user `dao.Mymodel.FindOne` or other query function,  nil fields will be assigned with zero value,  e.g. my model structure field type is int64, db type is bigint, db value is nil, when I query, I want this fields to be nil in my program, but now it's 0

so, I want to know wether I can generate my orm model with pointer fields

问题：
用 `gf gen dao`生成的model属性中，`varchar、int、bigint`等数据库字段都对应成了基本类型，如`string、int、int64`，这导致我进行insert或query的时候，存在零值的干扰，无法将数据库字段设置为业务上有意义的nil，或查询出业务上有意义的nil，因此想询问一下，能否将生成的model中的字段类型改为指针类型

**Comment by gqcn** [comment]
@lz908580572 NoNoNo，你想用指针就是想要像`gorm`的`Model`设计那样定义一个数据对象到处使用。`goframe`的设计不是这样，为了严谨期间，不同的业务模型请自行单独定义，查询数据的时候你也可以给定数据模型进行`Scan`赋值。
