### ISSUE TITLE
session文件模式下,重启服务器会struct中的int64加载为float64导致出现偏差

### ISSUE THREAD

**Issue by xushushun** [gogf/gf#1249]
`	user := model.ContextUser{
		Id:       1265476890672672808,
		Idcc:     0,
		Account:  "",
		Password: "",
		NickName: "",
		Name:     "",
		Avatar:   0,
		Orgid:    "",
		Wforgids: "",
	}
	r.Session.Set("kkfs", user)
`
代码如上,id类型为int64 这个时候重启程序,再读取会发现id被加载为float64 导致数值发生变化

**Comment by housemecn** [comment]
建议使用 string 的格式返回前端，或许在`json:id,string` 可以这样

**Comment by xushushun** [comment]
> 建议使用 string 的格式返回前端，或许在`json:id,string` 可以这样
这个和前端没关系的,直接调试状态下就可以看出问题
