### ISSUE TITLE
why using vardict params in some scenes that only accessing index 0? 

### ISSUE THREAD

**Issue by kaka19ace** [gogf/gf#1251]
### Cases
```text
gcfg pkg: getJson(file ...string) *gjson.Json  

ghttp pkg:  GetServer(name ...interface{}) *Server  
```
### Q
Why using vardict params in cases?
In detail codes, only index 0 is used.

**Comment by zcool321** [comment]
if the param is not set, the default value is used; it's just that you don't have to set the value

source code：

```go
func GetServer(name ...interface{}) *Server {
	serverName := gDEFAULT_SERVER
	if len(name) > 0 && name[0] != "" {
		serverName = gconv.String(name[0])
	}
……
}

func (c *Config) getJson(file ...string) *gjson.Json {
	var name string
	if len(file) > 0 && file[0] != "" {
		name = file[0]
	} else {
		name = c.name
	}
…………
}
```

**Comment by zcool321** [comment]
仅仅为了调用方法，支持设置参数，也支持不设置参数

**Comment by kaka19ace** [comment]
> if the param is not set, the default value is used; it's just that you don't have to set the value
> 
> source code：
> 
> ```go
> func GetServer(name ...interface{}) *Server {
> 	serverName := gDEFAULT_SERVER
> 	if len(name) > 0 && name[0] != "" {
> 		serverName = gconv.String(name[0])
> 	}
> ……
> }
> 
> func (c *Config) getJson(file ...string) *gjson.Json {
> 	var name string
> 	if len(file) > 0 && file[0] != "" {
> 		name = file[0]
> 	} else {
> 		name = c.name
> 	}
> …………
> }
> ```

got it!, thx for reply :)
