### ISSUE TITLE
希望能封装这个不需要cgo的支持标准database/sql的sqlite库

### ISSUE THREAD

**Issue by logoove** [gogf/gf#1253]
由于orm只能自己自定义驱动,原来的sqlite驱动需要cgo,非常不方便编译,在网上发现 modernc.org/sqlite这个驱动完美融入goframe,且不需要cgo,当然本人英文不好,作者可以看看,总之自己测试没问题

**Comment by logoove** [comment]
忘了放地址 https://gitlab.com/cznic/sqlite 这个项目不在github

**Comment by xiaodingding** [comment]
过了吗

**Comment by gqcn** [comment]
@logoove `goframe`的`orm`都是依靠标准库的database/sql注册数据库驱动的，不需要`orm`组件对第三方包做任何的封装，直接引用第三方包注册使用即可。
