### ISSUE TITLE
client连续请求，jaeger没有记录到信息

### ISSUE THREAD

**Issue by xushenghao** [gogf/gf#1259]
### 1. What version of `Go` and system type/arch are you using?
go 1.15 windows

### 2. What version of `GoFrame` are you using?
gf@v1.15.7

### 3. Can this issue be reproduced with the latest release?
可以

### 4. What did you do?
使用的是官方示例代码 https://github.com/gogf/gf-tracing/tree/master/examples/grpc_db_redis_log
运行后jaeger没有任何信息
在insert、query、delete 执行后加上time.Sleep(time.Second)，jaeger能够有信息
老大帮忙解答下如果去掉延时时间不能在jaeger输出信息的原因是什么

**Comment by xushenghao** [comment]
问题解决，应该是客户端流程走完后关闭了grpc连接，服务端没有给jaeger发送数据，客户端走完流程后关闭grpc连接延迟一会，
时间毫秒，希望老大来确定下是不是这个原因
`
	conn, err := grpc.Dial(":8001", grpcClientOptions...)
	if err != nil {
		g.Log().Fatalf("did not connect: %v", err)
	}
	defer func() {
		time.Sleep(time.Millisecond*100)
		conn.Close()
	}()
`

**Comment by gqcn** [comment]
@xushenghao Jaeger采用了缓冲机制提交数据，它有个`Close/Flush`方法，建议在`main`包中采用`defer`方式调用该方法防止数据丢失。
