### ISSUE TITLE
弱弱的问句，goframe如何获取网卡的出入口实时流量

### ISSUE THREAD

**Issue by qq1196** [gogf/gf#126]
想根据入出口流量进行限流，不知道如何获取实时流量

**Comment by johngcn** [comment]
@qq1196 
网卡限流是系统层面的概念，我猜你问的应该是WebServer的限流。

对WebServer限流可以使用钩子特性来实现，和权限校验是一样的做法，通过绑定`BEFORE_SERVE`钩子事件来处理，具体请参考 https://goframe.org/net/ghttp/router/hook
