### ISSUE TITLE
单元测试config目录问题

### ISSUE THREAD

**Issue by xushushun** [gogf/gf#1260]
单元测试config目录在当前go文件搜索,以及go的安装src目录下搜索,没有在src目录中项目根目录搜索导致需要手动复制config.toml到相应目录才能正常执行测试.

**Comment by chenall** [comment]
目前我的作法如下仅供参考

在测试目录下新建文件 init.go 关建内容如下
```
func init() {
	if !gfile.Exists("config/config.toml") {
		workdir, _ := filepath.Abs("../")
		os.Chdir(workdir)
	}
}
```

 filepath.Abs("../") 这个目录根据你的单元测试位置来指定，也可以直接固定为项目根目录
