### ISSUE TITLE
请求设置10秒钟，平滑重启时，请求会中断

### ISSUE THREAD

**Issue by ansionfor** [gogf/gf#1263]
### 1. What version of `Go` and system type/arch are you using?
go version go1.15.6 linux/amd64

### 2. What version of `GoFrame` are you using?
require github.com/gogf/gf v1.15.7

### 3. Can this issue be reproduced with the latest release?
Yes

### 4. What did you do?

main.go
```
package main
  
import (
    "time"
    "github.com/gogf/gf/frame/g"
    "github.com/gogf/gf/os/gproc"
    "github.com/gogf/gf/net/ghttp"
)

func main() {
    s := g.Server()
    s.BindHandler("/sleep", func(r *ghttp.Request){
        time.Sleep(10*time.Second)
        r.Response.Writeln(gproc.Pid())
    })
    s.SetPort(8199)
    s.Run()
}
```

config.toml
Graceful        = true

```
curl 127.0.0.1:8199/sleep
kill -SIGUSR1 24449
```

### 5. What did you expect to see?
output pid()

### 6. What did you see instead?
curl: (52) Empty reply from server

**Comment by ansionfor** [comment]
当使用pull的新增配置后：
```
    Graceful        = true
    ShutdownTimeout = 15
```

10秒的请求正常执行完
```
curl 127.0.0.1:8199/sleep
1923
```

**Comment by gqcn** [comment]
@ansionfor 好的，我复现了，我仔细先看看哈

**Comment by gqcn** [comment]
@ansionfor 你好，经过测试该问题只会出现在信号重启的场景中，不会影响API重启接口。可尝试使用最新版本，如果问题依旧，可以重新提交pr。
