### ISSUE TITLE
Modification of the configuration file does not take effect in windows 7

### ISSUE THREAD

**Issue by jiftle** [gogf/gf#1267]
### 1. What version of `Go` and system type/arch are you using?

go v1.14.3

### 2. What version of `GoFrame` are you using?

gogf  v1.15.7

### 3. Can this issue be reproduced with the latest release?

Modification of the configuration file does not take effect in windows 7

### 4. What did you do?

Modification of the configuration file does not take effect in windows 7

### 5. What did you expect to see?

Modification of the configuration file take effect in windows 7

### 6. What did you see instead?

Please resolve it , Thanks.

我还是用中文吧，英文怕表达不清楚。
问题：
    在Windows下修改配置文件，重启服务不生效。 

情况分析：
 1、 Linux下，手工重启服务是生效的。
 2、Windows下，手工重启也是生效的。
 3、【程序打包为Windows服务】修改完成配置，服务管理器重启服务，不生效。

**Comment by gqcn** [comment]
@jiftle 配置文件在外部被修改后通过`gcfg`能获取到最新的配置，不需要重启服务的。我没明白你说得重启是什么意思？看起来似乎是你打包为windows服务后出的问题？

**Comment by jiftle** [comment]
## 使用以下方式问题得到解决，还是怀疑配置文件的加载顺序，
```
// 指定配置文件路径
g.Cfg().SetPath("C:\\SoftWare\\Ncktc\\config")
```

## 官方文档描述：
```
默认目录配置

gcfg配置管理对象初始化时，默认会自动添加以下配置文件搜索目录：

    当前工作目录及其下的config目录：例如当前的工作目录为/home/www时，将会添加/home/www及/home/www/config；
    当前可执行文件所在目录及其下的config目录：例如二进制文件所在目录为/tmp时，将会添加/tmp及/tmp/config；
    当前main源代码包所在目录及其下的config目录(仅对源码开发环境有效)：例如main包所在目录为/home/john/workspace/gf-app时，将会添加/home/john/workspace/gf-app及/home/john/workspace/gf-app/config；
```

##  配置文件

排查因为是windows服务方式，所以工作目录是在` C:\Windows\system32`，但是检查目录下有config目录，并没有服务的配置。
