### ISSUE TITLE
How to extend glog library？

### ISSUE THREAD

**Issue by xiaodingding** [gogf/gf#1269]
At the moment I wanted to extend the glog log library functionality by dynamically configurable log levels and filtering logs from the top layer, but when I was ready to start, I found that the only area where the framework interface could be extended was when writing data streams, which I couldn't do. The interface I want to call wants to know when the log was generated, the level of the log, the name of the module, etc. If I need this information, will I have to write the glog library myself, but not extend it?

Too much to say, may not understand, let me be brief, I want an interface similar to this  logcallback(time,level,content....)

@chenall

**Comment by xiaodingding** [comment]
目前我打算扩展一下glog日志库功能，通过上层可以动态的配置日志的级别以及对日志进行过滤，但是在我准备开搞的时候，发现框架的接口唯一可以扩展的地方，只是在写数据流的时候，这让我无法下手；我想要调用的接口是希望可以知道日志产生时间，日志的级别，模块的名称等这些信息，如果需要这些信息，是不是只能自己写glog这个库了，而不能进行扩展了吗？说的太多了，可能不号理解，我简短点说吧，我想要的接口类似于这种 logcallback(time,level,content....) | 目前我打算扩展一下glog日志库功能，通过上层可以动态的配置日志的级别以及对日志进行过滤，但是在我准备开搞的时候，发现框架的接口唯一可以扩展的地方，只是在写数据流的时候，这让我无法下手；我想要调用的接口是希望可以知道日志产生时间，日志的级别，模块的名称等这些信息，如果需要这些信息，是不是只能自己写glog这个库了，而不能进行扩展了吗？说的太多了，可能不号理解，我简短点说吧，我想要的接口类似于这种 logcallback(time,level,content....)

&nbsp;

<br class="Apple-interchange-newline">

**Comment by xiaodingding** [comment]
@gqcn 麻烦大佬看一下

**Comment by gqcn** [comment]
@xiaodingding It added custom handler feature to logger, currently in master branch. It'll be release along with next release.
