### ISSUE TITLE
建议gconv.Struct方法支持结构的多层次继承的成员赋值

### ISSUE THREAD

**Issue by youyixiao** [gogf/gf#127]
gconv_struct.go中的方法：
func Struct(params interface{}, objPointer interface{}, attrMapping...map[string]string) error {
如果结构objPointer有多级继承成员时，继承的成员目前不支持映射，如：
type Person struct{
Name string
}
type Staff struct{
Person
StaffId int
}
staff:=&Staff{}
params:=make(map[string]string,0)
gconv.Struct(params,staff)//Name成员的赋值没有处理

**Comment by johngcn** [comment]
@youyixiao 已改进，新增了`gconv.StructDeep`实现多级继承转换，下一个版本发布。

**Comment by johngcn** [comment]
@youyixiao 已发布

**Comment by River-Heart** [comment]
> @youyixiao 已发布 https://goframe.org/util/gconv/struct

[官方文档中的示例](https://goframe.org/pages/viewpage.action?pageId=1114345#id-%E7%B1%BB%E5%9E%8B%E8%BD%AC%E6%8D%A2Struct%E8%BD%AC%E6%8D%A2-Struct%E9%80%92%E5%BD%92%E8%BD%AC%E6%8D%A2)并不能复现

![gf-struct-bug](https://user-images.githubusercontent.com/21359035/123224627-93220d80-d504-11eb-99b5-d9417c02f2fd.png)
