### ISSUE TITLE
ghttp.Request.Parse() error or bug?

### ISSUE THREAD

**Issue by Tongzp** [gogf/gf#1273]
Go 版本 (go version) ：1.16
GF (github.com/gogf/gf)：v1.16.1
问题：
调用 ghttp.Request.Parse() 解析前端传来的json格式的数据失败
提示如下：
![image](https://user-images.githubusercontent.com/33510725/120137177-4d746c80-c206-11eb-8e51-ca24a8495485.png)

结构体格式：
![image](https://user-images.githubusercontent.com/33510725/120137207-5feea600-c206-11eb-8884-08882cc69af9.png)

前端请求：
![image](https://user-images.githubusercontent.com/33510725/120137224-6bda6800-c206-11eb-8fa0-d0f8aa07af5d.png)

使用json库的jsoniter.UnmarshalFromString()函数可以成功解析，正确输出
![image](https://user-images.githubusercontent.com/33510725/120137473-f91dbc80-c206-11eb-9711-77f3080aa7ea.png)

输出结果
![image](https://user-images.githubusercontent.com/33510725/120137497-09ce3280-c207-11eb-89a9-28738c1de88e.png)

不知道是格式不对，还是说函数确实无法正确地把 json 转换成目标struct

**Comment by gqcn** [comment]
@Tongzp 请给定复现问题的代码示例。

**Comment by Tongzp** [comment]
json 请求数据
{
    "group_name": "aaa",
    "desc": "bb",
    "member_ciphers": {
        "70": [
            "20"
        ]
    }
}


问题复现代码
func (c *Controller) CreateDeviceGroup(r *ghttp.Request) {
	defer r.Exit()

	 //获取前端请求数据
	req := new(struct {
		GroupName     string              `json:"group_name"`     //组名称
		Desc          string              `json:"desc"`           //描述
		MemberCiphers map[string][]string `json:"member_ciphers"` //成员以及对应的ciphers
	})

        if err := r.Parse(req); err != nil {
		fmt.Println(err)
		return
	}
	
	fmt.Println(req)
}



能正确输出的代码
func (c *Controller) CreateDeviceGroup(r *ghttp.Request) {
	defer r.Exit()

	//获取前端请求数据
	req := new(struct {
		GroupName     string              `json:"group_name"`     //组名称
		Desc          string              `json:"desc"`           //描述
		MemberCiphers map[string][]string `json:"member_ciphers"` //成员以及对应的ciphers
	})

        if jsoniter.UnmarshalFromString(r.GetBodyString(), req) != nil {
   	        fmt.Println(err)
		return
	}
	
	fmt.Println(req)
}

**Comment by Tongzp** [comment]
###代码
```go
func main() {
	s := g.Server()
	s.SetPort(8888)
	s.BindHandler("/hello", func(r *ghttp.Request) {
		req := new(struct {
			Token         string              `json:"token"`          //用户令牌
			GroupName     string              `json:"group_name"`     //组名称
			Desc          string              `json:"desc"`           //描述
			MemberCiphers map[string][]string `json:"member_ciphers"` //成员以及对应的ciphers
		})

		//正确输出
		if err := jsoniter.UnmarshalFromString(r.GetBodyString(), req); err != nil {
			fmt.Println(err)
			return
		}

		//错误输出
		//if err := r.Parse(req); err != nil {
		//	fmt.Println(err)
		//	return
		//}

		fmt.Println(req)
	})

	s.Run()
}
```

###请求数据
```json
{
    "group_name": "aaa",
    "desc": "bb",
    "member_ciphers": {
    "70": [
    "20"
]
}
}
```

**Comment by Tongzp** [comment]
###补充一下import部分
```go
import (
	"fmt"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/net/ghttp"
	jsoniter "github.com/json-iterator/go"
)
```

**Comment by gqcn** [comment]
这个我看了，由于属性类型较复杂，目前暂不支持，需要改进一下，需要花点实践。
