### ISSUE TITLE
联表更新时，无法指定的待更新字段表别名

### ISSUE THREAD

**Issue by youyixiao** [gogf/gf#128]
目前MYSQL是这样的：
UPDATE pw_passageway m,pw_template t
SET `t.status`=99 WHERE m.templateId=t.id AND m.status = 0;

正确的应该是这样的：
UPDATE pw_passageway m,pw_template t
SET t.`status`=99 WHERE m.templateId=t.id AND m.status = 0;

可以修改如下：
switch kind {
        case reflect.Map:   fallthrough
        case reflect.Struct:
            var fields []string
            for k, v := range gconv.Map(data) {
                alias:=""
                colum:=k
                p:=strings.Index(k,".")
                if p>0{
                    alias=k[:p]+"."
                    colum=k[p+1:]
                }
                fields = append(fields, fmt.Sprintf("%s%s%s%s=?",alias, charL, colum, charR))
                params = append(params, convertParam(v))
            }
            updates = strings.Join(fields, ",")
        default:
            updates = gconv.String(data)
    }

**Comment by johngcn** [comment]
@youyixiao 你可以这样实现
```go
package main

import (
	"fmt"
	"github.com/gogf/gf/g"
)

func main() {
	db := g.DB()
	db.SetDebug(true)
	result, err := db.Table("pw_passageway m,pw_template t").Data("t.status", 99).Where("m.templateId=t.id AND m.status = 0").Update()
	if err != nil {
		panic(err)
	}
	fmt.Println(result.RowsAffected())
}
```
