### ISSUE TITLE
DB group方式取得不到配置

### ISSUE THREAD

**Issue by gongcf** [gogf/gf#1281]
[database]
    [[database.default]]
        link = "mysql:root:123456@tcp(127.0.0.1:3306)/test"
    [[database.voice]]
        debug = true
        link = "mysql:root:123456@tcp(127.0.0.1:3306)/test"

db, err1 := gdb.New("voice")
if err1 != nil {
glog.Error(err1)
}
会Error
[ERRO] database configuration node "voice" is not found, did you misspell group name "voice" or miss the database configuration?

**Comment by gqcn** [comment]
@gongcf Use instance function `g.DB` instead of package function `gdb.New`:
```go
package main

import (
	"fmt"
	"github.com/gogf/gf/frame/g"
)

func main() {
	fmt.Println(g.DB("voice").PingMaster())
}
```

**Comment by ansionfor** [comment]
gdb.New是创建一个新的数据库对象(非单例)，无法使用配置文件，需要使用包配置管理方法进行配置
https://goframe.org/pages/viewpage.action?pageId=1114686
