### ISSUE TITLE
orm  order() 排序不能使用+字段  -字段 进行排序

### ISSUE THREAD

**Issue by zhaiyujin** [gogf/gf#1282]
order()排序的时候可以使用+字段不能使用-字段 ，是否正则过滤掉了。希望能够使用

quoteWordReg = regexp.MustCompile(`^[a-zA-Z0-9\-_]+$`)

 有些情况需要吧排序控制权给前端。使用+- 变得更容易

**Comment by ouyangfangyuan** [comment]
The + field can be used when order () is sorting, but the - field cannot be used. Is it regular and filtered out. Hope to be able to use

quoteWordReg = regexp.MustCompile(^[a-zA-Z0-9\-_]+$)

In some cases, you need to give the front-end control of the sorting. It's easier to use + -

**Comment by gqcn** [comment]
@zhaiyujin @ouyangfangyuan Please submit the codes demonstrating your issue.
