### ISSUE TITLE
order 排序

### ISSUE THREAD

**Issue by zhaiyujin** [gogf/gf#1286]
### 1. What version of `Go` and system type/arch are you using?

go version go1.15.3 linux/amd64

### 2. What version of `GoFrame` are you using?

v1.16.1

### 4. What did you do?

前端请求sort="-id,+sort"
```go
order := "-id,+sort"
err = dao.Order.Where(where).WithAll().Page(page, pageSize).Order(order).Scan(&list)
```
报错
-id不是一个字段

### 5. What did you expect to see?

排序应该支持+,-    . 我看到quoteWordReg = regexp.MustCompile(`^[a-zA-Z0-9\-_]+$`) 过滤掉了-   

### 6. What did you see instead?
报错 -id不是一个字段

**Comment by danvinhe** [comment]
@zhaiyujin 不建议直接使用前端的请求参数，可能存在安全隐患。

@gqcn +id不符合正则，原样输出；-id符合正则，强制加了\`\`，被看作一个字段。-id命名合法但字段不存在，于是就报错了。
我疑惑的地方在于为什么要给特定字符串加\`\`，有什么特殊目的？
