### ISSUE TITLE
第三方fsnotify导致项目运行报错

### ISSUE THREAD

**Issue by snail007** [gogf/gf#129]
go 版本:1.12.5
引入最新gogf,
go run *.go 项目运行报错github.com/gogf/gf/third/github.com/fsnotify/fsnotify/inotify.go:19:2: C source files not allowed when not using cgo or SWIG: gccgo_c.c
必须:
CGO_ENABLED=0 go run *.go 才行.

**Comment by johngcn** [comment]
@snail007 刚看到你的issue，我看看

**Comment by johngcn** [comment]
@snail007 你好，我当前的几个项目中均没有出现这个错误，能否提供该问题的系统、架构信息，以及可复现该问题的最小代码。

**Comment by johngcn** [comment]
@snail007 蜗牛大佬，没问题我就关闭这个issue了哈。
