### ISSUE TITLE
windows10下无法打印调试信息

### ISSUE THREAD

**Issue by kbdxbt** [gogf/gf#1290]
如题, 在windows10下无法打印stack堆栈错误信息

**Comment by hailaz** [comment]
详细说明一下，其它环境信息，如go、goframe版本号。
以及复现的最小代码。

**Comment by kbdxbt** [comment]
> 
> 
> 详细说明一下，其它环境信息，如go、goframe版本号。
> 以及复现的最小代码。

![图片](https://user-images.githubusercontent.com/33480434/134890449-3038229e-619e-49b9-9337-85dee75505fb.png)

你好, 没有详细的堆栈信息, 这个你可以看下吗? 用的就是gf官方代码, gf1.15.7版本, go1.15.6, win10系统

**Comment by hailaz** [comment]
先试试新建一个最简单项目，看看

**Comment by kbdxbt** [comment]
> 
> 
> 先试试新建一个最简单项目，看看
> 
> ```go
> s := g.Server()
> s.BindHandler("/", func(r *ghttp.Request) {
>     panic("6666")
>     r.Response.Write("哈喽世界！")
> })
> s.SetPort(8199)
> s.Run()
> ```

![图片](https://user-images.githubusercontent.com/33480434/135192882-d3000171-1cc0-43d2-af44-e8d8942df23e.png)
也不行呢. 麻烦看下
