### ISSUE TITLE
gjson.Set("field", val) when the 2nd param val type is *gjson.Json

### ISSUE THREAD

**Issue by primexiao** [gogf/gf#1291]
### 1. What version of `Go` and system type/arch are you using?

go version go1.15.2 darwin/amd64

### 2. What version of `GoFrame` are you using?

v1.15.1
v1.16.2

### 3. Can this issue be re-produced with the latest release?
yes

### 4. What did you do?

```go
// sample code
jsonval := gjson.New(g.Map{
                  "user1": g.Map{"name": "user1"},
                  "user2": g.Map{"name": "user2"},
                  "user3": g.Map{"name": "user3"},
                  })
user1 := jsonval.GetJson("user1")
user1.Set("id", 111)
jsonval.Set("user1", user1)   // then ["user1"] becomes to nil
//jsonval.Set("user1", user1.Map())  // it works well

```

### 5. What did you expect to see?
```
["user1"]  is not nil
```
when the 2nd param val type is gjson.Json/ *gjson.Json, it should works as well

### 6. What did you see instead?
```
["user1"]  is nil
```

**Comment by logoove** [comment]
要是有个处理json中循环的方法就方便多了,比如这个包就有github.com/buger/jsonparser

**Comment by gqcn** [comment]
@primexiao Please update to the latest `master` branch and try again.
