### ISSUE TITLE
希望能gjson能增加数组的处理

### ISSUE THREAD

**Issue by logoove** [gogf/gf#1295]
平常开发接口用到很多json处理,目前的没有处理数组,类似json包,github.com/buger/jsonparser就有arrayeach处理,主要是不想给复杂的json写结构体.

**Comment by gqcn** [comment]
@logoove 你看下`gjson`的API呢，可以通过`GetJsons`获取返回的`gjson.Json`数组，然后自行遍历处理。

**Comment by logoove** [comment]
好的
