### ISSUE TITLE
配置文件修改后不生效，一直是之前的配置

### ISSUE THREAD

**Issue by EthanChenLi** [gogf/gf#1298]
修改了配置文件再读取仍然是之前的配置文件。 新增和修改字段都是原来的配置，重启IDE问题任然存在。
复现方法：
  开启一个服务，然后通过任务管理员kill掉。
  再重新开一个服务，这个时候配置就不生效了。

**Comment by EthanChenLi** [comment]
解决了 ，把 pack/data.go 打包内容删了就行了

**Comment by chenall** [comment]
因为这个是优先使用打包的资源文件的

有需要的话也可以我修改的版本，优先使用文件系统的文件。
