### ISSUE TITLE
Return immediately when the parameter check error occurs, do not continue to pass

### ISSUE THREAD

**Issue by Light0821** [gogf/gf#1299]
### 1. What version of `Go` and system type/arch are you using?
> go version go1.15 darwin/amd64

### 2. What version of `GoFrame` are you using?

>  v1.16.2

### 3. Can this issue be re-produced with the latest release?

> yes

### 4. What did you do?

输入参数校验时，遇到校验不通过时不会中断会继续，直到所有参数都校验完毕参会结束

### 5. What did you expect to see?

输入参数校验时，希望有字段校验不通过时立即返回error，不要继续向下传到，直到所有字段都校验完毕才返回error

**Comment by gqcn** [comment]
@Light0821 好建议。目前数据校验组件都已经采用了链式对象+链式操作设计，因此可以增加一个配置项链式操作方法来决定是否在校验错误时立即返回。欢迎感兴趣的小伙伴可以贡献PR。
