### ISSUE TITLE
gtcp.NewServer的返回对象没有关闭方法

### ISSUE THREAD

**Issue by zjfsdnu** [gogf/gf#130]
### 1. What version of `Go` and system type/arch are you using?

go version go1.12 windows/amd64

### 2. What version of `GoFrame` are you using?

1.6.6

### 3. Can this issue be reproduced with the latest release?

是的

### 4. What did you do?

`server1 := gtcp.NewServer("127.0.0.1:8999", func(conn *gtcp.Conn) { })`

### 5. What did you expect to see?

原生的tcp listener是有关闭方法的

```
type Listener interface {
	// Accept waits for and returns the next connection to the listener.
	Accept() (Conn, error)

	// Close closes the listener.
	// Any blocked Accept operations will be unblocked and return errors.
	Close() error

	// Addr returns the listener's network address.
	Addr() Addr
}
```

### 6. What did you see instead?

只有三个方法
SetAddress
SetHandler
Run

**Comment by johngcn** [comment]
这个功能会和TCP的包管理改进工作一起完成，并一同发布。

**Comment by johngcn** [comment]
@zjfsdnu 请更新到最新版本再试。
