### ISSUE TITLE
github.com/gogf/gf/net/gtrace 包引入异常，包升级到了v1.0.0-RC1

### ISSUE THREAD

**Issue by DukeAnn** [gogf/gf#1302]
# github.com/gogf/gf/net/gtrace
../../../../pkg/mod/github.com/gogf/gf@v1.16.3/net/gtrace/gtrace_baggage.go:40:10: undefined: "go.opentelemetry.io/otel/baggage".ContextWithValues
../../../../pkg/mod/github.com/gogf/gf@v1.16.3/net/gtrace/gtrace_baggage.go:51:10: undefined: "go.opentelemetry.io/otel/baggage".ContextWithValues
../../../../pkg/mod/github.com/gogf/gf@v1.16.3/net/gtrace/gtrace_baggage.go:58:9: undefined: "go.opentelemetry.io/otel/baggage".Set
../../../../pkg/mod/github.com/gogf/gf@v1.16.3/net/gtrace/gtrace_baggage.go:73:11: undefined: "go.opentelemetry.io/otel/baggage".Value
../../../../pkg/mod/github.com/gogf/gf@v1.16.3/net/gtrace/gtrace_span.go:20:32: cannot use opts (type []trace.SpanOption) as type []trace.SpanStartOption in argument to NewTracer().Tracer.Start

**Comment by housemecn** [comment]
otel包每次发包更新都比较大，建议不要随意更新OTEL的版本，建议使用v0.19.0版本！

**Comment by housemecn** [comment]
> # github.com/gogf/gf/net/gtrace
> ../../../../pkg/mod/github.com/gogf/gf@v1.16.3/net/gtrace/gtrace_baggage.go:40:10: undefined: "go.opentelemetry.io/otel/baggage".ContextWithValues
> ../../../../pkg/mod/github.com/gogf/gf@v1.16.3/net/gtrace/gtrace_baggage.go:51:10: undefined: "go.opentelemetry.io/otel/baggage".ContextWithValues
> ../../../../pkg/mod/github.com/gogf/gf@v1.16.3/net/gtrace/gtrace_baggage.go:58:9: undefined: "go.opentelemetry.io/otel/baggage".Set
> ../../../../pkg/mod/github.com/gogf/gf@v1.16.3/net/gtrace/gtrace_baggage.go:73:11: undefined: "go.opentelemetry.io/otel/baggage".Value
> ../../../../pkg/mod/github.com/gogf/gf@v1.16.3/net/gtrace/gtrace_span.go:20:32: cannot use opts (type []trace.SpanOption) as type []trace.SpanStartOption in argument to NewTracer().Tracer.Start

maste 分支已经更新了，你可以下载看看！

**Comment by DukeAnn** [comment]
好的 谢谢啦
