### ISSUE TITLE
请教如何自定义数据校验中的:attribute值

### ISSUE THREAD

**Issue by ygcool** [gogf/gf#1305]
Go Version:  go1.16.3
GF Version:  v1.16.0

比如规则是 `same:pssword` 
就会提示`“PasswordConfirmed 字段值必须和password相同”`，
如何把i18n多语言字段提示改为`“确认密码 字段值必须和密码相同"` 

简单说，如何自定义字段提示别名。期待回复，感激不尽，谢谢

**Comment by gqcn** [comment]
@ygcool 你看下文档呢，有介绍 https://goframe.org/pages/viewpage.action?pageId=1114384

**Comment by ygcool** [comment]
抱歉，可能是我描述有问题，我的意思是，在使用默认的“gf.gvalid.rule.required”规则或其他默认规则时，其中的:attribute能自定义文案吗？当前默认是直接取字段名，类似laravel表单验证中的public function attributes()
![image](https://user-images.githubusercontent.com/16422689/124606635-a8e9e800-de9f-11eb-9ddf-e1d4c3acd10a.png)

**Comment by gqcn** [comment]
@ygcool 不行，你可以自定义错误，不使用其中的`:attribute`属性。

**Comment by ygcool** [comment]
好的了解了，谢谢
