### ISSUE TITLE
针对postgresql的模式问题，使用orm更新数据，表名中加入【模式.表名】会报错

### ISSUE THREAD

**Issue by 651016236** [gogf/gf#1306]
使用以下语句更新数据会验证data中的字段，目前解决方案重写driver，不知道有没有其他好的解决方案
`_, _ = db.Model("common.shop_closed_daily").Data(g.Map{
	"c_pos_qty":   CPosQty,
	"c_void_qty":  CVoidQty,
	"c_pos_total": CPosTotal,
	"modified":    gtime.Now().Timestamp(),
	"status":      1,
	"recalculate": 0,
}).Where("id = ?", daily.Id).Update()`

![image](https://user-images.githubusercontent.com/5875767/123235074-1eec6780-d50e-11eb-964b-df277241bc4c.png)

**Comment by gqcn** [comment]
duplicated with https://github.com/gogf/gf/issues/1308
