### ISSUE TITLE
gdb如何实现数据库表和字段的生成修改删除操作

### ISSUE THREAD

**Issue by EthanChenLi** [gogf/gf#1311]
需要实现对mysql数据库表进行增删改查， 还需要对数据库表的字段进行增删改查。 
GDB有实现的方法吗，还是说只能通过原生SQL实现。

**Comment by housemecn** [comment]
修改表结构吗？这样修改完之后，需要更新dao层的内容

**Comment by EthanChenLi** [comment]
我的场景是后台有个自定义表单，需要在运行动态创建和删除数据库表。

**Comment by EthanChenLi** [comment]
> 修改表结构吗？这样修改完之后，需要更新dao层的内容

请问能实现吗？

**Comment by housemecn** [comment]
> > 修改表结构吗？这样修改完之后，需要更新dao层的内容
> 
> 请问能实现吗？

这个需要数据库权限，你可以自己fork一个分支捣腾

**Comment by BeanWei** [comment]
简单点说，你这种只能自己写原生sql。

另外，这种我做过实现，强烈建议用mongo来做，mongo不用关心表的结构，非常适合用来做这种动态的东西。

**Comment by housemecn** [comment]
> 简单点说，你这种只能自己写原生sql。
> 
> 另外，这种我做过实现，强烈建议用mongo来做，mongo不用关心表的结构，非常适合用来做这种动态的东西。
> 
> 可以看下我的开源项目，antapi, 有啥疑问可以在实战3群里交流。

这是个好主意 @EthanChenLi

**Comment by gqcn** [comment]
@EthanChenLi 通过`gdb`包你可以使用`Exec`方法的原生SQL来实现。
