### ISSUE TITLE
gdb模型定义 err or bug

### ISSUE THREAD

**Issue by EthanChenLi** [gogf/gf#1318]
go version: 1.15.7
GoFrame Version: v1.16.2 

当我再model目录顶一个查询结构体这么定义的时候
```
 type GcCategoryWith struct {
	Id        int         `orm:"id,primary" json:"id"`         //
	Type      string      `orm:"type"       json:"type"`       // 栏目类型
	Pid       int         `orm:"pid"        json:"pid"`        // 上级ID
	Title     string      `orm:"title"      json:"title"`      // 栏目名称
	Status    int         `orm:"status"     json:"status"`     // 1启用，0 禁用
	CreatedAt *gtime.Time `orm:"created_at" json:"created_at"` //
	UpdatedAt *gtime.Time `orm:"updated_at" json:"updated_at"` //
	CategoryNews *GcCategoryNews `orm:"with:category_id=id" json:"category_news"`
}
```
使用查询语句``` dao.GcCategory.WithAll().Scan()```查询是OK的

当我直接继承internal结构体的时候
```
type GcCategoryWith struct {
	internal.GcCategory
	CategoryNews *GcCategoryNews `orm:"with:category_id=id" json:"category_news"`
}
```
会抛 **cannot find the related value for attribute name \"id\" of with tag \"category_id=id\"** ,
internal.GcCategory 里面的内容跟我上面那个结构体贴的内容一模一样的。

**Comment by gqcn** [comment]
@EthanChenLi `With`关联查询可能对嵌入结构体没支持好，先挂我头上，我看看。

**Comment by gqcn** [comment]
@EthanChenLi 你的结构体少了数据表的指定，你按照文档介绍的把`gmeta.Meta`加上呢：https://goframe.org/pages/viewpage.action?pageId=7297190

**Comment by EthanChenLi** [comment]
> @EthanChenLi 你的结构体少了数据表的指定，你按照文档介绍的把`gmeta.Meta`加上呢：https://goframe.org/pages/viewpage.action?pageId=7297190

尝试修改成
```
type GcCategoryWith struct {
	gmeta.Meta `orm:"table:gc_category"`  // 这里不管带不带前缀都报错
	CategoryNews *GcCategoryNews `orm:"with:category_id=id" json:"category_news"`
	CategoryPage *GcCategoryPage `orm:"with:category_id=id" json:"category_page"`
	CategoryJump *GcCategoryJump `orm:"with:category_id=id" json:"category_jump"`
}
```
依然抛出
```cannot find the related value for attribute name \"id\" of with tag \"category_id=id\"```

**Comment by gqcn** [comment]
@EthanChenLi 你试试最新的`master`分支: `go get -u github.com/gogf/gf@master`。如果不行的话你提交一份可复现该问题的最小代码以及SQL，我运行试试。

**Comment by EthanChenLi** [comment]
```
CLI Built Detail:
  Go Version:  go1.16.3
  GF Version:  v1.16.0
```
使用该定义方法
```
type GcCategoryWith struct {
	internal.GcCategory
	CategoryNews *GcCategoryNews `orm:"with:category_id=id" json:"category_news"`
}
```
仍然报错**cannot find the related value for attribute name "id" of with tag "category_id=id" **，不知是否没有升级版本
