### ISSUE TITLE
gf orm pg driver not support LastInsertId. how can i get insert id in pg driver?

### ISSUE THREAD

**Issue by huoyinghui** [gogf/gf#1319]
### 1. What version of `Go` and system type/arch are you using?

```
➜  git:(master) ✗ gf version
GoFrame CLI Tool v1.16.3, https://goframe.org
GoFrame Version: v1.16.3 in current go.mod
CLI Installed At: /usr/local/bin/gf
CLI Built Detail:
  Go Version:  go1.16.3
  GF Version:  v1.16.0
  Git Commit:  42d9811d5f8c8be349a1591c8b98c916cf8281aa
  Build Time:  2021-06-22 22:02:04
➜ git:(master) ✗ 
```

### 2. What version of `GoFrame` are you using?

v1.16.0

### 3. Can this issue be re-produced with the latest release?

can

### 4. What did you do?

```go
 dao.Model.InsertAndGetId()
```
pg not suuport lastid

### 5. What did you expect to see?

such as django / beego orm insert return id.

Alternatively, the  model can provide an interface for the user to interpolate a RETURNING ID in the INSERT SQL

**Comment by ansionfor** [comment]
https://pkg.go.dev/github.com/lib/pq

`pq does not support the LastInsertId() method of the Result type in database/sql. To return the identifier of an INSERT (or UPDATE or DELETE), use the Postgres RETURNING clause with a standard Query or QueryRow call:`

```var userid int
err := db.QueryRow(`INSERT INTO users(name, favorite_fruit, age)
	VALUES('beatrice', 'starfruit', 93) RETURNING id`).Scan(&userid)
```

**Comment by ansionfor** [comment]
在goframe中就是：
```
package main
  
import (
    _ "github.com/lib/pq"
    "github.com/gogf/gf/frame/g"
    "fmt"
)

func main() {
    db := g.DB("pg")
    var id int
    rows, _ := db.Query("insert into test1 (name) values (123) returning id")
    for rows.Next() {
        rows.Scan(&id)
    }
    fmt.Println(id)
}
```

**Comment by chaggle** [comment]
mark
