### ISSUE TITLE
ghttp的client的SetBrowserMode方法对post请求无效。

### ISSUE THREAD

**Issue by hailaz** [gogf/gf#132]
ghttp的client的SetBrowserMode方法对post请求无效。dorequest的时候post情况下不会执行SetBrowserMode相关操作。

**Comment by hailaz** [comment]
具体代码位置
github.com\gogf\gf@v1.6.14\g\net\ghttp\ghttp_client_request.go:268
github.com\gogf\gf@v1.6.14\g\net\ghttp\ghttp_client_request.go:269
github.com\gogf\gf@v1.6.14\g\net\ghttp\ghttp_client_request.go:321

**Comment by johngcn** [comment]
@hailaz 确实是，有意思，应该是不小心漏掉了。

**Comment by johngcn** [comment]
@hailaz 已改进
