### ISSUE TITLE
请问有办法禁用session吗

### ISSUE THREAD

**Issue by ruziyi** [gogf/gf#1320]
有些纯api项目, 并不需要session, 有办法禁用session吗?

**Comment by housemecn** [comment]
大佬说是要使用才启动的

**Comment by gqcn** [comment]
@ruziyi 虽然你看到Request请求对象中有个`Session`对象，但默认`Session`是关闭的，这只是个空对象。`Session`采用了懒初始化设计，只有在你使用到`Session`的方法时才会真正初始化启用。
