### ISSUE TITLE
能不能保持低版本兼容?

### ISSUE THREAD

**Issue by Desdemo** [gogf/gf#1322]
go mod 升级gf最新版本很多代码都出错，老代码修改太麻烦了。维护成本太高了。

**Comment by housemecn** [comment]
只有验证这一块加了ctx参数，其他的除非是执行了gf gen重新生成了

> go mod 升级gf最新版本很多代码都出错，老代码修改太麻烦了。维护成本太高了。

**Comment by Desdemo** [comment]
> 只有验证这一块加了ctx参数，其他的除非是执行了gf gen重新生成了
> 
> > go mod 升级gf最新版本很多代码都出错，老代码修改太麻烦了。维护成本太高了。

gf gen model 升级之后才发现被移除了
