### ISSUE TITLE
template {{.Session.SessionKeyUser.Nickname}} not parse after app restart

### ISSUE THREAD

**Issue by tangr** [gogf/gf#1323]
### 1. What version of `Go` and system type/arch are you using?
go version go1.15.6 darwin/amd64

### 2. What version of `GoFrame` are you using?
v1.16.1

### 3. Can this issue be re-produced with the latest release?
Yes

### 4. What did you do?
for the gf-demos, after restart the webserver, the session  parse not decode.

I tested the demo.
https://goframe.org/pages/viewpage.action?pageId=1114302#id-%E5%BC%80%E5%A7%8B%E8%BF%90%E8%A1%8C-2.%E7%94%A8%E6%88%B7%E7%99%BB%E5%BD%95-/user/signin

https://goframe.org/pages/viewpage.action?pageId=1114173#id-%E6%95%B0%E6%8D%AE%E8%BF%94%E5%9B%9E%E6%A8%A1%E6%9D%BF%E8%A7%A3%E6%9E%90-Session

Added the new api showpage in the router

```
		group.Group("/", func(group *ghttp.RouterGroup) {
			group.Middleware(service.Middleware.Auth)
			group.ALL("/user/profile", api.User.Profile)
			group.ALL("/user/showpage", api.User.ShowPage)
		})
```

and
```
func (a *userApi) ShowPage(r *ghttp.Request) {
	content := `Session Nickname:{{.Session.SessionKeyUser.Nickname}}
Session: {{.Session.SessionKeyUser}}
Session nickname: {{.Session.SessionKeyUser.nickname}}`
	r.Response.WriteTplContent(content)
}

```

The curl -H 'gfsessionid:' http://127.0.0.1:8199/user/showpage not worked after the app restart.

Thanks.

**Comment by gqcn** [comment]
@tangr Try `go get -u github.com/gogf/gf@master`
