### ISSUE TITLE
Can't find command `gf` after go get on both mac and ubuntu

### ISSUE THREAD

**Issue by yangyanqing** [gogf/gf#1327]
### 1. What version of `Go` and system type/arch are you using?
- **Mac**: go version go1.16.3 darwin/amd64
- **Ubuntu**: go version go1.15.12 linux/amd64

### 2. What version of `GoFrame` are you using?

v1.16.4

### 3. Can this issue be re-produced with the latest release?

Yes

### 4. What did you do?

**Mac**
```bash
$ rm -rf ${GOPATH}/bin 
$ rm -rf ${GOPATH}/pkg
$ rm -rf ${GOPATH}/src/github.com/gogf
$ alias gf=gf
$ go get -u -v github.com/gogf/gf
go: downloading github.com/gogf/gf v1.16.4
```
**Ubuntu**
```bash
$ rm -rf ${GOPATH}/bin 
$ rm -rf ${GOPATH}/pkg
$ rm -rf ${GOPATH}/src/github.com/gogf
$ alias gf=gf
$ go get -u -v github.com/gogf/gf
go: downloading github.com/gogf/gf v1.16.4
go: github.com/gogf/gf upgrade => v1.16.4
```

### 5. What did you expect to see?

bin file `gf` should be in somewhere.

### 6. What did you see instead?

I could NOT find it in ${GOPATH}/bin or somewhere.

**Comment by gqcn** [comment]
@yangyanqing The repository `github.com/gogf/gf` is the basic coding framework, to make it lightweight and with less dependences, the CLI tool is hosted in another repository: github.com/gogf/gf-cli
