### ISSUE TITLE
模型关联条件判断

### ISSUE THREAD

**Issue by fakery2009** [gogf/gf#1333]
请问当我使用with模型关联的时候，比如您提交的例子，用户表，关联了用户学分，当我with用户学分模型的时候，这个学分模型如何加Where条件呢，比如查询用户列表，然后关联用户学分，其中关联的学分数据这一部分我只需要学分大于2的这种，请问一下这种情况该如何写啊

**Comment by gqcn** [comment]
@fakery2009 目前不支持，后续改进吧。

**Comment by wenxian2012** [comment]
> @fakery2009目前不支持，后继续改进吧。

强哥，这个需求不能沉啊
