### ISSUE TITLE
数据库查询Struct不支持解析JSON数组字符串

### ISSUE THREAD

**Issue by macnie** [gogf/gf#1334]
结构体：

```
type User struct{
     Tags []UserTag `json:"tags"`
}

type UserTag struct[
  Name string `json:"name"`
  Color string `json:"color"`
]
```

数据表：

`表名：user`
`tags 字段类型为 json`

经过测试，目前GF的 g.Model("user").Struct(&user) ，不能正常解析出来User结构体，含UserTag结构体。
提示：reflect.Value.Convert: value of type string cannot be converted to type UserTag

**Comment by housemecn** [comment]
建议使用

> 结构体：
> 
> ```
> type User struct{
>      Tags []UserTag `json:"tags"`
> }
> 
> type UserTag struct[
>   Name string `json:"name"`
>   Color string `json:"color"`
> ]
> ```
> 
> 数据表：
> 
> `表名：user`
> `tags 字段类型为 json`
> 
> 经过测试，目前GF的 g.Model("user").Struct(&user) ，不能正常解析出来User结构体，含UserTag结构体。
> 提示：reflect.Value.Convert: value of type string cannot be converted to type UserTag

Structs (),Struct() 适合单个的 
详见：https://github.com/gogf/gf/blob/046749566da0bc14c01808d157a3b29120a805fa/database/gdb/gdb_model_select.go#L244

**Comment by gqcn** [comment]
@macnie 麻烦给一下复现问题的sql和代码。
