### ISSUE TITLE
使用框架进行反向代理的正确姿势是?  how to use reverse proxy ?

### ISSUE THREAD

**Issue by JOSEFAzyq** [gogf/gf#1336]
请指教如何正确的使用goframe来进行反向代理的操作?  看的资料都需要用到 ListenAndServe 来传入 httpHandle 来进行代理操作,是goframe不适合这种需求吗?

**Comment by gqcn** [comment]
标准库有相关方法，请自行研究下。

**Comment by mdgg0816** [comment]
同问
