### ISSUE TITLE
1.16.2版本cpu持续攀升，是什么问题呢？

### ISSUE THREAD

**Issue by mashibao** [gogf/gf#1342]
![image](https://user-images.githubusercontent.com/24691557/125581456-efda0c76-27f7-4428-975c-fa3c1f48d5cb.png)
![image](https://user-images.githubusercontent.com/24691557/125581475-44bc435d-54cd-4862-8088-4d91ab2e96e0.png)
![image](https://user-images.githubusercontent.com/24691557/125581493-9a026c05-b776-4e48-b6a2-44281e868829.png)
![image](https://user-images.githubusercontent.com/24691557/125581555-1152b731-ad52-4b55-b5f9-68ecb14204ba.png)
gf 版本 1.16.2
重启后降下来了，gtimer的问题？有没有大佬，解决一下啊，谢谢

**Comment by gqcn** [comment]
@mashibao 你的pprof中只有框架两个模块的方法调用，没有任何业务方法调用，并且goroutine数量过多都是不正常的点。建议给定复现问题的代码。

**Comment by mashibao** [comment]
通过go tool pprof多次查内存和CPU性能，定位到，项目中多个地方使用了gdb.New("数据库分组名称")，这个函数调用了gcache.New()，它调用了gtimer.AddSingleton，抱着试试的想法，因为埋点捕捉的也是gtimer创建太多，所以把gtimer.AddSingleton注释掉，放到线上，结果奇迹般好了！激动
这里感谢作者gqcn，抽出时间帮我查找问题

### 注释地方
文件名gcache_cache.go
![image](https://user-images.githubusercontent.com/24691557/126450639-7230853d-5382-441b-952e-c447a03e60cb.png)

### 之前
![image](https://user-images.githubusercontent.com/24691557/126450543-edc999bc-2c78-49f7-b6fe-a8d5d55082ec.png)

### 现在
![image](https://user-images.githubusercontent.com/24691557/126450579-4a2fa469-b8b9-438c-80d2-3ba3ade101a0.png)
