### ISSUE TITLE
update方法报错请问怎么处理

### ISSUE THREAD

**Issue by tianxia0079** [gogf/gf#1349]
最新版本 v1.16.4
```
func testupdate()  {
	id := 72
	pass := 2
	entity, e := ai_sentence.Model.Where("id=?", id).One()
	if e != nil {
		g.Log().Line().Error(e)
	}

	entity.State = pass
	_, err := entity.Update()
	if err != nil {
		g.Log().Line().Error(err)
	} else {
	}
}


2021-07-20 14:27:22.713 [ERRO] sentence.go:121: sql: expected 8 arguments, got 9, UPDATE `ai_sentence` SET `delate`=0,`id`=72,`phone`='2088702302431853',`add_time`='2021-06-02 14:49:56',`update_time`='2021-06-02 14:49:56',`content`='今天晚上是您值班，请勿迟到，请认真填写各项表格，祝您工作顺利！',`state`=1 WHERE `id` IN (72)
Stack:
```

**Comment by zuozhehao** [comment]
clone后再update 试看看

**Comment by tianxia0079** [comment]
不行

**Comment by gqcn** [comment]
@tianxia0079 用最新的`master`分支试试，不行的话给个我可以运行的代码。

**Comment by tianxia0079** [comment]
@gqcn
[Desktop.zip](https://github.com/gogf/gf/files/6913982/Desktop.zip)
我在2021年8月2日10:20试了最新的1.16.4，还是报一样的错误。

压缩包里有表脚本,自动 生产的代码，还有一个可以运行的测试用例，麻烦看下啥情况。

**Comment by gqcn** [comment]
> @gqcn
> [Desktop.zip](https://github.com/gogf/gf/files/6913982/Desktop.zip)
> 我在2021年8月2日10:20试了最新的1.16.4，还是报一样的错误。
> 
> 压缩包里有表脚本,自动 生产的代码，还有一个可以运行的测试用例，麻烦看下啥情况。
> 补充：表里没有数据，请随便填一条就可以，id设置为72

我看了你的代码，你使用的是老的`model`方式，新版本已经不支持，建议你升级为`dao`方式。或者保留使用老版本，在下一个版本升级为`dao`。

**Comment by tianxia0079** [comment]
@gqcn 
1. 为什么不支持model方式了，是有性能问题吗，有没有详细说明的地方，想了解一下原因
2.新版本不支持，应该彻底删除，代码编译也不报错，但是运行报错，体验很差，如果真有问题，应该彻底删除

**Comment by gqcn** [comment]
> @gqcn
> 
> 1. 为什么不支持model方式了，是有性能问题吗，有没有详细说明的地方，想了解一下原因
>    2.新版本不支持，应该彻底删除，代码编译也不报错，但是运行报错，体验很差，如果真有问题，应该彻底删除

主要原因是`CLI`生成的旧版`model`代码扩展性和维护性不佳，框架新增了方法`CLI`工具模板也要新增修改。新版本改为了继承嵌套方式，并且开发者可以使用`Scan`方法将查询结果绑定到任意的可接收对应参数的结构体上，而不是只依靠`Entity`对象。

这个`model`的代码是`cli`工具生成的，框架控制不了。新版本`cli`工具已经删除了该命令，但是已经生成的`model`代码只有开发者升级为`dao`方式才能使用最新的`goframe`框架版本。
