### ISSUE TITLE
建议glog模块，添加异步功能，以及文本里的err错误可以支持跳转

### ISSUE THREAD

**Issue by 15951836388** [gogf/gf#135]
想实现开发时，同步，方便调错，上线时异步，不影响主程序。

![image](https://user-images.githubusercontent.com/14047483/58408699-e95fc080-80a0-11e9-8f6e-1ff08dc22998.png)

在log的文本文件里，只有最后1行可以点击跳转到代码，希望可以每行都能跳转

**Comment by johngcn** [comment]
@15951836388 我用Windows试了一下，是每一行都可以跳转的
![image](https://user-images.githubusercontent.com/26347176/58533952-7bd89f00-821c-11e9-9002-5ac05861be9f.png)

**Comment by johngcn** [comment]
@15951836388 https://goframe.org/os/glog/async
