### ISSUE TITLE
防火墙交互模式，导致电脑死机？

### ISSUE THREAD

**Issue by seakk** [gogf/gf#1351]
### 1. What version of `Go` and system type/arch are you using?

go version go1.16.5 darwin/amd64 , macos 10.14.6 

### 2. What version of `GoFrame` are you using?

goframe v1.16.4 , gf-demos, gf-focus

### 3. Can this issue be re-produced with the latest release?

我装了ESET Cyber Security Pro，实际我只用它的防火墙功能，防火墙模式为交互（没加入防火墙规则入站请求都会弹出让用户选择）。当我在浏览器访问 http://127.0.0.1:8199 时（此时入站端口规则未在防火墙规则内）， 防火墙会弹出窗口让我选择允许或者是拒绝，无论选择允许或是拒绝，此时go 运行的 进程会挂起，即使点击了允许，浏览器中网页不能访问。无处从活动监视器或者终端强制杀死此进程时，就会无反应，以至于卡住，从而导致电脑慢慢处于死机状态，只能强制关机重启，而其它的go应用程序不存在上述问题。

我分别试用了两次都是同样的结果，第一次运行的程序是 gogf/gf-demos，第二次运行的程序是 gogf/focus 。

**Comment by zcool321** [comment]
1、可以把监听配置改为Address     = "127.0.0.1:8199" 这样     试试防火墙还会不会拦截；
2、试过其他go web程序无此问题？
3、pprof是否可以访问，看看当前goroutine信息？

**Comment by gqcn** [comment]
@seakk @zcool321 该问题与`goframe`框架无关，关闭。
