### ISSUE TITLE
[Feature Request]:  gcache support remove keys by pattern

### ISSUE THREAD

**Issue by BeanWei** [gogf/gf#1353]
RT.

**Comment by gqcn** [comment]
@BeanWei Package `gcache` uses `map` structure for its underlying data storage, which is too simple to support key pattern like `key*` or `*key`。It is better using `b-tree` or `skip-list` for keys indexing, but there's advantage and disadvantage between `map`, `b-tree` and `skip-list`. Package `gcache`  chooses `map`.

**Comment by danvinhe** [comment]
I don't think it makes sense. You can find out all the keys, and then traverse and delete the qualified data
