### ISSUE TITLE
新版的gf-cli1.6.4 gf gen dao命令导致链式查询有误

### ISSUE THREAD

**Issue by yakxi** [gogf/gf#1354]
1、原来通过gf gen dao 命令执行后model目录下没有model.go文件的，现在执行之后多了这个文件。
2、进而要求删除重复定义的结构体
3、并且导致orm链式查询字段名大小写未转换成数据库字段。

如：原来查询的时候，select order_id , order_sn....
现在变成了大写 SELECT `OrderId`,`OrderSn`,`DealCode`,`PayTime`,

![image](https://user-images.githubusercontent.com/3667848/126918295-5a0663f3-dabe-42ab-8dea-dba1c6bf5607.png)

**Comment by housemecn** [comment]
> 1、原来通过gf gen dao 命令执行后model目录下没有model.go文件的，现在执行之后多了这个文件。
> 2、进而要求删除重复定义的结构体
> 3、并且导致orm链式查询字段名大小写未转换成数据库字段。
> 
> 如：原来查询的时候，select order_id , order_sn....
> 现在变成了大写 SELECT `OrderId`,`OrderSn`,`DealCode`,`PayTime`,
> 
> ![image](https://user-images.githubusercontent.com/3667848/126918295-5a0663f3-dabe-42ab-8dea-dba1c6bf5607.png)

先备份model 目录，在删除model目录，重新生成试试

**Comment by gqcn** [comment]
@yakxi 你应该升级一下`goframe`框架，试试最新的`master`分支吧
