### ISSUE TITLE
1.16.4版本gfcli.gen.dao多个配置使用工具链生成model.go模型，只能生成其中一个，不能同时生成多个。

### ISSUE THREAD

**Issue by yakxi** [gogf/gf#1355]
1.16.4版本的开发工具链生成model.go文件的时候有个问题，如果我的 gfcli.gen.dao配置有多个，比如

```

[gfcli]
    [[gfcli.gen.dao]]
    link = "mysql:root:123456@tcp(127.0.0.1:3306)/test1"
    group = "test1"
    jsonCase = "Snake"
[[gfcli.gen.dao]]
    link = "mysql:root:123456@tcp(127.0.0.1:3306)/test2"
    group = "test2"
    jsonCase = "Snake"

```

那么test2生成的model.go文件会覆盖test1生成的model.go文件，这样就会有很大的困扰了。这点希望能改进下！

**Comment by housemecn** [comment]
你可以先自己 拉源码编译 gf 工具，master分支 已经有处理了。

**Comment by housemecn** [comment]
> 1.16.4版本的开发工具链生成model.go文件的时候有个问题，如果我的 gfcli.gen.dao配置有多个，比如
> 
> ```
> 
> [gfcli]
>     [[gfcli.gen.dao]]
>     link = "mysql:root:123456@tcp(127.0.0.1:3306)/test1"
>     group = "test1"
>     jsonCase = "Snake"
> [[gfcli.gen.dao]]
>     link = "mysql:root:123456@tcp(127.0.0.1:3306)/test2"
>     group = "test2"
>     jsonCase = "Snake"
> ```
> 
> 那么test2生成的model.go文件会覆盖test1生成的model.go文件，这样就会有很大的困扰了。这点希望能改进下！

```
gf gen dao -h
USAGE
    gf gen dao [OPTION]

OPTION
    -/--path             directory path for generated files.
    -l, --link           database configuration, the same as the ORM configuration of GoFrame.
    -t, --tables         generate models only for given tables, multiple table names separated with ','
    -e, --tablesEx       generate models excluding given tables, multiple table names separated with ','
    -g, --group          specifying the configuration group name of database for generated ORM instance,
                         it's not necessary and the default value is "default"
    -p, --prefix         add prefix for all table of specified link/database tables.
    -r, --removePrefix   remove specified prefix of the table, multiple prefix separated with ','
    -m, --mod            module name for generated golang file imports.
    -j, --jsonCase       generated json tag case for model struct, cases are as follows:
                         | Case            | Example            |
                         |---------------- |--------------------|
                         | Camel           | AnyKindOfString    |
                         | CamelLower      | anyKindOfString    | default
                         | Snake           | any_kind_of_string |
                         | SnakeScreaming  | ANY_KIND_OF_STRING |
                         | SnakeFirstUpper | rgb_code_md5       |
                         | Kebab           | any-kind-of-string |
                         | KebabScreaming  | ANY-KIND-OF-STRING |
    -/--stdTime          use time.Time from stdlib instead of gtime.Time for generated time/date fields of tables.
    -/--modelFile        custom file name for storing generated model content.
    -/--tplDaoIndex      template content for Dao index files generating.
    -/--tplDaoInternal   template content for Dao internal files generating.
    -/--tplModelIndex    template content for Model index files generating.
    -/--tplModelStruct   template content for Model internal files generating.

CONFIGURATION SUPPORT
    Options are also supported by configuration file.
    It's suggested using configuration file instead of command line arguments making producing.
    The configuration node name is "gf.gen.dao", which also supports multiple databases, for example:
    [gfcli]
        [[gfcli.gen.dao]]
            link     = "mysql:root:12345678@tcp(127.0.0.1:3306)/test"
            tables   = "order,products"
            jsonCase = "CamelLower"
        [[gfcli.gen.dao]]
            link   = "mysql:root:12345678@tcp(127.0.0.1:3306)/primary"
            path   = "./my-app"
            prefix = "primary_"
            tables = "user, userDetail"

EXAMPLES
    gf gen dao
    gf gen dao -l "mysql:root:12345678@tcp(127.0.0.1:3306)/test"
    gf gen dao -path ./model -c config.yaml -g user-center -t user,user_detail,user_login
    gf gen dao -r user_

```

上面是最新的 gf工具的 gf gen dao 命令的说明

**Comment by yakxi** [comment]
config 配置
[gfcli]
    # gf_study 自定义DAO生成配置(默认是读取database配置)
    [[gfcli.gen.dao]]
        link   = "mysql:......1"
        group  = "gf_study"
        tables = "user,order_status,failure_reason,order_status_category,order_status_ignore,order_status_type,return_order_status_type,return_shipping_status_type,shipping_status_type"
    #octobase-e3-0303 自定义DAO生成配置(默认是读取database配置)
    [[gfcli.gen.dao]]
        link   = "mysql:......2"
        group  = "e3"
        tables = "goods_barcode,kehu,cangku,order_info,order_return,goods,sd_cangku_sku_adapt"

执行命令
[going@dev gf-study]$ gf gen dao          **<----- 命令**
generated: app/dao/internal/user.go 
generated: app/dao/internal/order_status.go 
generated: app/dao/internal/failure_reason.go 
generated: app/dao/internal/order_status_category.go 
generated: app/dao/internal/order_status_ignore.go 
generated: app/dao/internal/order_status_type.go 
generated: app/dao/internal/return_order_status_type.go 
generated: app/dao/internal/return_shipping_status_type.go 
generated: app/dao/internal/shipping_status_type.go 
generated: app/model/model.go      **<-----  第一次产生**
generated: app/dao/internal/goods_barcode.go 
generated: app/dao/internal/kehu.go 
generated: app/dao/internal/cangku.go 
generated: app/dao/internal/order_info.go 
generated: app/dao/internal/order_return.go 
generated: app/dao/internal/goods.go 
generated: app/dao/internal/sd_cangku_sku_adapt.go 
generated: app/model/model.go        **<-----  第二次覆盖**
done! 

不知道错在哪里？

**Comment by yakxi** [comment]
嗯，知道了。需要配置个modelFile
