### ISSUE TITLE
链式查询，不可以定义别名

### ISSUE THREAD

**Issue by yakxi** [gogf/gf#1357]
[going@dev gf-study]$ gf -v
GoFrame CLI Tool v1.16.4, https://goframe.org 
GoFrame Version: v1.16.4 in current go.mod 
CLI Installed At: /home/going/go/bin/gf 
Current is a custom installed version, no installation information. 

[going@dev gf-study]$ go version
go version go1.16.6 linux/amd64

` m := g.DB("e3").Model("cangku") `  <----------
debug 后的语句： **SELECT `id`,`ckdm`,`ckmc`,`outer_code`,`erp_outer_code` FROM `cangku`** （正确的语句）

 `m := g.DB("e3").Model("cangku c")`   <---------- 定义别名
debug 后的语句： **SELECT `Id`,`Ckdm`,`Ckmc`,`OuterCode`,`ErpOuterCode` FROM `cangku` c** （错误的字段名）
由于字段不对，出现sql查询报错：
Error: Error 1054: Unknown column 'OuterCode' in 'field list' 
Stack:

**Comment by gqcn** [comment]
@yakxi Please try branch `master`.
