### ISSUE TITLE
安装了gtoken的时候，编译运行报错

### ISSUE THREAD

**Issue by lala0257** [gogf/gf#1359]
F:\go-project\src\my-gf>gf run main.go
2021-07-27 17:12:48.683 build: main.go
2021-07-27 17:12:48.751 go build -o bin\main.exe  main.go
2021-07-27 17:12:55.163 build error:
# github.com/gogf/gf/net/gtrace
..\..\pkg\mod\github.com\gogf\gf@v1.16.4\net\gtrace\gtrace_baggage.go:40:10: undefined: "go.opentelemetry.io/otel/baggage".ContextWithValues
..\..\pkg\mod\github.com\gogf\gf@v1.16.4\net\gtrace\gtrace_baggage.go:51:10: undefined: "go.opentelemetry.io/otel/baggage".ContextWithValues
..\..\pkg\mod\github.com\gogf\gf@v1.16.4\net\gtrace\gtrace_baggage.go:58:9: undefined: "go.opentelemetry.io/otel/baggage".Set
..\..\pkg\mod\github.com\gogf\gf@v1.16.4\net\gtrace\gtrace_baggage.go:73:11: undefined: "go.opentelemetry.io/otel/baggage".Value
..\..\pkg\mod\github.com\gogf\gf@v1.16.4\net\gtrace\gtrace_span.go:20:32: cannot use opts (type []trace.SpanOption) as type []trace.SpanStartOption in argument to NewTracer().Tracer.Start
exit status 2

**Comment by houseme** [comment]
https://github.com/gogf/gf/issues/1515
