### ISSUE TITLE
为什么GoFrame(gf) 的star挺少的才5.8k呢

### ISSUE THREAD

**Issue by 1211ciel** [gogf/gf#1362]

**Comment by gqcn** [comment]
哈哈，还是推广做少了，多参加宣讲推广视频什么的就涨起来了。不过`GoFrame`有大概70%用户是粘性用户，也就是说大概有`5.8K`中的`70%`正在使用`GoFrame`。这一比例还是很惊人的。`GoFrame`不以`Star`为发展目标，`Star`多少也不能为`GoFrame`带来什么。倒是希望大家多多参与贡献，一起为社区添砖加瓦。
