### ISSUE TITLE
建议gf update后打印一下更新日志,并提供版本回退功能

### ISSUE THREAD

**Issue by ysxpark** [gogf/gf#1367]
这段时间也看群里不少人在反应这个问题,主要是gfcli改动后更新内容不透明,开发者不知道这次更新了什么内容,是否应该升级

**Comment by housemecn** [comment]
> 这段时间也看群里不少人在反应这个问题,主要是gfcli改动后更新内容不透明,开发者不知道这次更新了什么内容,是否应该升级

在 https://github.com/gogf-cli 可以更新 选择版本安装

**Comment by gqcn** [comment]
@ysxpark `gf-cli`每一次发布有打标签，可以选择安装指定版本：https://github.com/gogf/gf-cli
