### ISSUE TITLE
Why we put the http client `resp` in the internal pkg

### ISSUE THREAD

**Issue by Shoothzj** [gogf/gf#1368]
Why put the http client's `resp` in the `internal` package ? 

We have some pieces of code, doing same check on `resp`, wanting to refractor these actions as a method. But can't refer the sturct in `internal`

**Comment by gqcn** [comment]
@Shoothzj Please use `ghttp.ClientResponse`.

**Comment by Shoothzj** [comment]
> @

could you please show a piece of code ?
```go
g.Client().Get("http://www.baidu.com")
```
this can only get the response in the internal package

**Comment by gqcn** [comment]
```go
var (
    err error
    res *ghttp.ClientResponse
)
res, err = g.Client().Get("http://www.baidu.com")
```

**Comment by Shoothzj** [comment]
@gqcn Thank you.
