### ISSUE TITLE
建议glog模块，增加json格式输出和颜色

### ISSUE THREAD

**Issue by 15951836388** [gogf/gf#137]
在终端，json人眼可读友好，有颜色，就更好了

对日志收集分析系统也友好

**Comment by johngcn** [comment]
@15951836388 日志里面加颜色？我见过写日志同时输出到终端的时候，终端会有颜色，但是觉得不太必要，终端颜色你可以提个建议我看看。JSON那个我会支持。

**Comment by johngcn** [comment]
@15951836388 https://goframe.org/os/glog/json
