### ISSUE TITLE
I found a bug about route resolution！

### ISSUE THREAD

**Issue by windf17** [gogf/gf#1370]
1. run shell command
` gf init test `
` cd test `
 `go mod tidy `
2. edit file “router/router.go”
`package router

import (
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/net/ghttp"
	"test/app/api"
)

func init() {
	s := g.Server()
	s.Group("/", func(group *ghttp.RouterGroup) {
		group.ALL("/hello", api.Hello)
		group.ALL("/:name", api.Name)
	})
}
`
3. edit file "app/api/hello.go"
`package api

import (
	"fmt"
	"github.com/gogf/gf/net/ghttp"
)

func Hello(r *ghttp.Request) {
	fmt.Println("This is hello！")
	r.Response.Writeln("Hello World!")
}

func Name(r *ghttp.Request) {
	fmt.Println("This is name！")
	r.Response.Writeln("Hello ,", r.Get("name"))
}
`
4. run shell command
`go run ./main.go`
5. when you access"http://127.0.0.1:8199/hello"，shell print：
This is hello！
This is name！
6. when you access"http://127.0.0.1:8199/mike"，shell print：
This is name！
This is name！

final：The function “name” was executed repeatedly

**Comment by ansionfor** [comment]
你的gf是什么版本呢，我用1.16.5测试并没有重复打印
![image](https://user-images.githubusercontent.com/17793750/128830498-b74bef61-cc02-4b73-960a-069853ef43db.png)

**Comment by windf17** [comment]
我刚刚又测试了一次，先执行go get -u -v github.com/gogf/gf，再执行gf update，再创建新测试项目gf init test2。
里面有重复执行，具体可以下载这个视频看看我这运行的状况：
链接: https://pan.baidu.com/s/1VslMhSp1wgO3F0RLAvcBSg  密码: 9el1
--来自百度网盘超级会员V4的分享

**Comment by ansionfor** [comment]
@windf17 这是因为浏览器额外发了一个icon请求，在shell下是不会的
![image](https://user-images.githubusercontent.com/17793750/129126867-b0a516e1-5910-42b2-9739-50d0f2e5d30d.png)

**Comment by windf17** [comment]
经过测试，确实如此。
添加config/config.toml中serverRoot路径，
在public目录下添加favicon.ico文件后确实没有重复的记录！！
