### ISSUE TITLE
The port of the linux platform project is invalid 

### ISSUE THREAD

**Issue by YY-Me** [gogf/gf#1375]
## 1. What version of `Go` and system type/arch are you using?

go version go1.16.5 windows/amd64

### 2. What version of `GoFrame` are you using?

github.com/gogf/gf v1.16.4

### 4. What did you do?

1：create project
2：update config
[server]
	Address     = ":18080"
	ServerRoot  = "public"
	ServerAgent = "gf-app"
	LogPath     = "/tmp/log/gf-app/server"

[gfcli]
    [gfcli.build]
        name     = "officeView"
        arch     = "amd64"
        system   = "linux"
        version  = "v1.0.0"
        output   = "./bin"
3：gf build

### 5. What did you expect to see?

I hope to see the port is 18080 on the linux platform 

### 6. What did you see instead?

The port of the windows platform is 18080 
But the port of the linux platform is 80

**Comment by danvinhe** [comment]
1. Make sure your configuration is correct
2. Is there a packed old configuration in the pack directory
3. It may also fail to start. And 80 is the port of nginx

**Comment by YY-Me** [comment]
> 1. Make sure your configuration is correct
> 2. Is there a packed old configuration in the pack directory
> 3. It may also fail to start. And 80 is the port of nginx

I created the project through the command of the official document:  gf init myapp
After that, I changed the default port and packaged it ，I just changed the port ，Where did the old configuration come from 
The port of the windows platform is correct, but the linux port is incorrect 
Thanks for your answer, but it doesn't seem to help

**Comment by gqcn** [comment]
@YY-Me Maybe it cannot find the configuration file. Enable the debug mode and watch the debug information output in the stdout: https://goframe.org/pages/viewpage.action?pageId=1114207
