### ISSUE TITLE
关于1.16.4 model放到一个文件 model.go 的问题

### ISSUE THREAD

**Issue by renfan** [gogf/gf#1378]
因为我们开发用的一个数据库，如果都放到一个model.go 中，万一程序员A改变了数据库字段名称，然后在自己代码里修改了字段名；然后程序员B生成后，因为B的代码没改就报错，需要等A提交代码，然后B拉过来后才能继续开发。
我们以前生成的时候用 -t 参数，只生成和自己当前开发的表，其他表别人改了也不会影响呢，目前大家都挺尴尬的，怎么办

**Comment by ysongyang** [comment]
而且现在配置了多库的话，执行gf gen dao 命令，model.go 还会被覆盖，必须指定-g 和 --fileModel 来指定

**Comment by houseme** [comment]
> 因为我们开发用的一个数据库，如果都放到一个model.go 中，万一程序员A改变了数据库字段名称，然后在自己代码里修改了字段名；然后程序员B生成后，因为B的代码没改就报错，需要等A提交代码，然后B拉过来后才能继续开发。
> 我们以前生成的时候用 -t 参数，只生成和自己当前开发的表，其他表别人改了也不会影响呢，目前大家都挺尴尬的，怎么办

必须指定-g 和 --fileModel 来指定 这样还是可以解决以前的问题，一样可以生成单个表的model文件

**Comment by gqcn** [comment]
@renfan 数据模型由工具维护的，开发人员不应该去该代码中的字段，这样会引起数据结构与代码映射不一致，开发者应该去修改数据库结构并且单向同步到程序代码中。这也是为了规范，就是为了避免你说的这一种场景。

**Comment by gqcn** [comment]
@renfan 最新`v2`版本已经拆分。
