### ISSUE TITLE
gdb操作调用Filter()方法时，因为内部字段比较是区分大小写的，所以可能导致一些字段匹配不上而错误过滤了

### ISSUE THREAD

**Issue by youyixiao** [gogf/gf#138]
···
// 将map的数据按照fields进行过滤，只保留与表字段同名的数据
func (bs *dbBase) filterFields(table string, data map[string]interface{}) map[string]interface{} {
    if fields, err := bs.db.getTableFields(table); err == nil {
        for k, _ := range data {
            if _, ok := fields[k]; !ok {
                delete(data, k)
            }
        }
    }
    return data
}
···

**Comment by johngcn** [comment]
@youyixiao 你好，应该是你写入数据的时候字段和数据库字段不一致造成的，`Filter`方法会在执行数据库操作之前将用户输入的字段与表字段做匹配，不匹配的字段会被过滤的，当然这种匹配肯定是区分大小写的，不然提交的数据库执行会失败的。
