### ISSUE TITLE
开启XSS 转译，base64图片无法输出

### ISSUE THREAD

**Issue by 35598253** [gogf/gf#1382]
go: 1.16
gf: 1.16.5

设置模版 Autoencode 为ture  
模版输出变量为  base64 图片时，转译出错，输出为 #ZgotmplZ

另，
  有些时候是需要输出原生语句的，希望模版变量加一个标签禁止转移，比如  {{.test | raw}} 则不过滤进行输出，望采纳

**Comment by gqcn** [comment]
@35598253 参考一下`htmldecode`: https://goframe.org/pages/viewpage.action?pageId=17203987

**Comment by 35598253** [comment]
> @35598253 参考一下`htmldecode`: https://goframe.org/pages/viewpage.action?pageId=17203987

htmldecode 用这个函数反转后变为字符串，导致无法输出html；

**Comment by chaegumi** [comment]
不能开autoencode的样子，要自己评估处理避免XSS
