### ISSUE TITLE
希望有 数据库 和 redis 指定配置文件。

### ISSUE THREAD

**Issue by xybingbing** [gogf/gf#1385]
原因： 生产环境的 数据库配置 都是下发的  ，编译时自动读取生产的数据库配置。 希望有个接口 修改默认的数据库配置文件
比如：
![image](https://user-images.githubusercontent.com/10228562/130545956-c7f35ec3-36a4-4147-ac94-c82f2be3ac32.png)

**Comment by houseme** [comment]
官方文档上有说明。
是希望启动之后再修改链接配置吗？

> 原因： 生产环境的 数据库配置 都是下发的 ，编译时自动读取生产的数据库配置。 希望有个接口 修改默认的数据库配置文件
> 比如：
> ![image](https://user-images.githubusercontent.com/10228562/130545956-c7f35ec3-36a4-4147-ac94-c82f2be3ac32.png)

**Comment by gqcn** [comment]
@xybingbing 你好，数据库和Redis组件都有设置配置的方法（不通过配置文件），配置是package级别的，可以再程序启动时将配置读取出来设置到数据库/Redis组件中去。
