### ISSUE TITLE
gtime.time 类型，值为空的话则会自动转为空字符串

### ISSUE THREAD

**Issue by macnie** [gogf/gf#1387]
不知道这算不算一个BUG。

GF版本：1.16.5
MYSQL：8.0 严格模式

数据表：confirm_time datetime  default: NULL

场景还原：

前端界面的日期输入框，业务上可以留空。

后端定义了request结构体：
``` go
type OrderCreateRequest struct{
  ConfirmTime *gtime.Time
}
```
经 r.Parse解析后，保存至数据表：
``` go
req := new(OrderCreateRequest)

r.Parse(req)

g.Model("order").Insert(req)

```
此时会报错：
**Incorrect date value: '' for column 'confirm_time' at row 1** 

我测试发现，是gtime.time类型，转为了空字符串，我感觉应该空值的情况下，应为nil

同时，在把数据填充到前端界面上，也会有此问题：

```
r.Response.Json(g.Model("order").Scan(req)
```
前端得到了confirm_time 是空字符串，而不是null

**Comment by sootma** [comment]
请问是哪个版本解决的，我升级到最新的16.6还是一样， 数据库为null的datetime, 在转为json时为 ""， 而不会是 null
