### ISSUE TITLE
请去除mysql的自动依赖,因为引入了 github.com/gogf/mysql 而无法使用其他的orm 比如gorm

### ISSUE THREAD

**Issue by Insua** [gogf/gf#1388]
在新版本的gf里的go.mod里引入了  github.com/gogf/mysql,  github.com/gogf/mysql 这个包里 sql.Register(name, &MySQLDriver{}）里注册了mysql驱动。
我再引入gorm gorm.Open(mysql.Open(dsn), &gorm.Config{}) 就会panic panic: sql: Register called twice for driver mysql

我即使只把gf当一个工具库 只引入几个工具函数，但是也会去注册mysql，我认为gf是一个通用的工具库，不应该去绑定死了数据库驱动，像以前的版本 gf的go.mod引入的是 github.com/go-sql-driver/mysql 这个包不会去register 就不会报错了

谢谢

**Comment by Insua** [comment]
得等下一次版本发布吧

**Comment by QK-Beginner** [comment]
> 得等下一次版本发布吧

你好你的问题解决了吗 我现在也是这样

**Comment by housemecn** [comment]
> > 得等下一次版本发布吧
> 
> 你好你的问题解决了吗 我现在也是这样

最新版已经解决这个问题了，版本是V1.16.6
