### ISSUE TITLE
gdb对time.Time的支持不足

### ISSUE THREAD

**Issue by youyixiao** [gogf/gf#139]
1、字段类型为time.Time时，没有赋值的时候报错：
Error: Error 1292: Incorrect datetime value: '0000-00-00' for column 'receiptTime' at row 1
需要有配置：datasource.url=jdbc:mysql://localhost:3306/testdb？zeroDateTimeBehavior=convertToNull

2、字段类型为*time.Time时，赋值的时候报错：
Error: Error 1292: Incorrect datetime value: '2019-05-31 09:10:34 m=+0.427276916' for column 'receiptTime' at row 1

**Comment by johngcn** [comment]
@youyixiao 
1、在业务上时间为零值的情况要避免，如果需要时间零值自动转换为`nill`，那么请使用指针类型如`*time.Time`或者`*gtime.Time`
2、下一个版本将提供支持

**Comment by johngcn** [comment]
@youyixiao 已发布。
