### ISSUE TITLE
官网挂了 无法访问文档

### ISSUE THREAD

**Issue by liangbaika** [gogf/gf#1393]
官网挂了 无法访问文档官网挂了 无法访问文档官网挂了 无法访问文档官网挂了 无法访问文档
官网挂了 无法访问文档官网挂了 无法访问文档官网挂了 无法访问文档

**Comment by LvJianfeng** [comment]
+1

**Comment by housemecn** [comment]
> 官网挂了 无法访问文档官网挂了 无法访问文档官网挂了 无法访问文档官网挂了 无法访问文档
> 官网挂了 无法访问文档官网挂了 无法访问文档官网挂了 无法访问文档

已恢复
