### ISSUE TITLE
goleak report goroutine leak

### ISSUE THREAD

**Issue by x1a0x** [gogf/gf#1397]
### 1. What version of `Go` and system type/arch are you using?

go1.17, darwin/amd64

### 2. What version of `GoFrame` are you using?

v1.16.6

### 4. What did you do?

this is my repo [91go/rss2](https://github.com/91go/rss2), i use `goleak` to detect whether goroutine leak, and goleak report this...

![image](https://user-images.githubusercontent.com/8591495/132125460-906790bf-b511-419c-bef3-46de928e1cc0.png)

**Comment by gqcn** [comment]
@x1a0x Some goroutines in `goframe` components start with process and die with process, they handle buffer feature or timely jobs internally. I think you should not  worry about it.
