### ISSUE TITLE
gf-demo Context.Get(ctx).Session.Set(sessionKeyUser, user) 调用报错

### ISSUE THREAD

**Issue by leopardxu** [gogf/gf#1399]
### runtime error: invalid memory address or nil pointer dereference
// 设置用户Session.
func (s *sessionService) SetUser(ctx context.Context, user *model.User) error {
	glog.Info(user)
	return Context.Get(ctx).Session.Set(sessionKeyUser, user)
}
 
gf version 1.16.2

**Comment by leopardxu** [comment]
r.context()  is nil ~~~

**Comment by Ambition9186** [comment]
你好，请问你这个地方是怎么解决的呢？
