### ISSUE TITLE
中间件流程控制

### ISSUE THREAD

**Issue by wangbs95** [gogf/gf#1403]
### 1. What version of `Go` and system type/arch are you using?
go version go1.16.5 darwin/arm64

### 2. What version of `GoFrame` are you using?

v1.15.3

### 3. Can this issue be re-produced with the latest release?
don't try

### 4. What did you do?
多个中间件的情况下，对于某个接口依次注册了AB 两个middleware，由于 A 流程较长，误写了两个`r.Middleware.Next()`，那么 B 中的`r.Response.WriteStatusExit(http.StatusUnauthorized)`之类的结束流程的语句不能终止流程，会最终执行到接口方法。

### 5. What did you expect to see?
框架最好能容错此类错误，或者在文档中明确提示，否则，此类问题非常难排查。

### 6. What did you see instead?
容错处理

**Comment by danvinhe** [comment]
我理解这样根本不会执行b的逻辑， 直接跳到接口方法了，应该很容易排查出问题呢。
框架不好限制，中间件是用户自己实现的

**Comment by wangbs95** [comment]
> 我理解这样根本不会执行b的逻辑， 直接跳到接口方法了，应该很容易排查出问题呢。
> 框架不好限制，中间件是用户自己实现的

想回答问题的话，花5分钟复现一下不好吗，直接「理解」一下就开始质疑别人产生的现象了

**Comment by gqcn** [comment]
@wangbs95 `WriteStatusExit`只会终止当前方法，不会终止流程，你可以使用`ExitAll`，请参考：https://goframe.org/pages/viewpage.action?pageId=38569768
