### ISSUE TITLE
embedded内嵌结构体覆盖过滤敏感字段不生效

### ISSUE THREAD

**Issue by lyw0053** [gogf/gf#1404]
### 1. What version of `Go` and system type/arch are you using?
go v1.17  gf v1.16.6

**Comment by danvinhe** [comment]
麻烦详细说明，并给出最少可执行代码

**Comment by sinnerwjj** [comment]
![image](https://user-images.githubusercontent.com/13197286/133615573-78223b98-7bb9-4030-b1a3-c39c3967e9ae.png)
![image](https://user-images.githubusercontent.com/13197286/133615796-e10676a8-99ab-4f9c-a759-98bf8edb2e3d.png)
我这里通过内嵌覆盖掉password，但是结果还是被展示出来

**Comment by mingzaily** [comment]
覆盖无效的，这个官方的也是这样
