### ISSUE TITLE
如何集成statsviz?

### ISSUE THREAD

**Issue by Insua** [gogf/gf#1410]
https://github.com/arl/statsviz

```
s.BindHandler("/debug/statsviz/*path", func(r *ghttp.Request) {
		if r.GetRouterVar("path").String() == "/ws" {
			statsviz.Ws(r.Response.Writer, r.Request)
			return
		}
		statsviz.IndexAtRoot("/debug/statsviz").ServeHTTP(r.Response.Writer, r.Request)
	})
```
我这样写了　不好使

**Comment by danvinhe** [comment]
1. 路由注册 **router/router.go**
```
group.Group("/debug", func(group *ghttp.RouterGroup) {
	group.Group("/statsviz", func(group *ghttp.RouterGroup) {
		group.GET("/ws", ghttp.WrapF(statsviz.Ws))
		group.GET("/*", ghttp.WrapF(statsviz.Index))
	})
})
```

2. 添加URI与静态目录的映射
`s.AddStaticPath("/debug/statsviz", statsviz_static_path)`
statsviz_static_path为你本地statsviz包的静态目录

**Comment by Insua** [comment]
> 1. 注册路由 **router/router.go**
> 
> ```
> group.Group("/debug", func(group *ghttp.RouterGroup) {
> 	group.Group("/statsviz", func(group *ghttp.RouterGroup) {
> 		group.GET("/ws", ghttp.WrapF(statsviz.Ws))
> 		group.GET("/*", ghttp.WrapF(statsviz.Index))
> 	})
> })
> ```
> 
> 1. 添加URI与静态目录的映射
>    `s.AddStaticPath("/debug/statsviz", statsviz_static_path)`
>    statsviz_static_path为你本地statsviz包的静态目录

谢谢
