### ISSUE TITLE
链路追踪-http server

### ISSUE THREAD

**Issue by kk531200922** [gogf/gf#1413]
报错：
../../../go/pkg/mod/github.com/gogf/gf@v1.16.6/net/ghttp/internal/client/client_tracing.go:73:3: undefined: attribute.Any
../../../go/pkg/mod/github.com/gogf/gf@v1.16.6/net/ghttp/internal/client/client_tracing_tracer.go:150:3: undefined: attribute.Any
../../../go/pkg/mod/github.com/gogf/gf@v1.16.6/net/ghttp/internal/client/client_tracing_tracer.go:151:3: undefined: attribute.Any

attribute没有Any 方法

**Comment by danvinhe** [comment]
使用最新的master分支或等待最新的发行版本

**Comment by houseme** [comment]
https://github.com/gogf/gf/issues/1515

创建项目之后，不要执行`go get -v -u all`

该包`go.opentelemetry.io/otel`有兼容性的问题，在v1.0.0-RC3到V1.0.0的时候，有删除`any`的方法。
