### ISSUE TITLE
gogf/swagger 1.3在gf最新的master中会报错

### ISSUE THREAD

**Issue by jroam** [gogf/gf#1415]
### 1. What version of `Go` and system type/arch are you using?
go 1.17.1

### 2. What version of `GoFrame` are you using?
gf master

### 4. What did you do?
编译的时候报错：
![image](https://user-images.githubusercontent.com/5014017/134611195-52920ec1-1255-4d93-8243-cabe1cd7e3d3.png)

### 5. What did you expect to see?
请看看.

**Comment by housemecn** [comment]
最新版已经移除了GetMap 这个方法，以及不建议更新到最新版本使用

**Comment by arieslee** [comment]
> 最新版已经移除了GetMap 这个方法

貌似获取具体类型的方法都移除了，有些尴尬，不好升级呀

**Comment by housemecn** [comment]
> > 最新版已经移除了GetMap 这个方法
> 
> 貌似获取具体类型的方法都移除了，有些尴尬，不好升级呀,写的也不如原来爽了

静待下一个大招吧，这一块都统一到*gvar.Var

**Comment by jroam** [comment]
只有自己再根据场景封装一下了。

**Comment by arieslee** [comment]
> > > 最新版已经移除了GetMap 这个方法
> > 
> > 
> > 貌似获取具体类型的方法都移除了，有些尴尬，不好升级呀,写的也不如原来爽了
> 
> 静待下一个大招吧，这一块都统一到*gvar.Var

嗯，期中，想看看v2有什么大招^_^

**Comment by gqcn** [comment]
@arieslee @jroam @housemecn 使用类似`g.Cfg().MustGet(ctx, `xxx`).Map()`

**Comment by gqcn** [comment]
@jroam 新版本不再支持`gogf/swagger`以及第三方`swag`工具这种依靠注释来手动写接口文档的方式，采用了全自动的接口文档生成方式。

**Comment by zhonghuaxunGM** [comment]
> @jroam 新版本不再支持`gogf/swagger`以及第三方`swag`工具这种依靠注释来手动写接口文档的方式，采用了全自动的接口文档生成方式。

@gqcn 
I found that its documentation is not updated.
(https://goframe.org/pages/viewpage.action?pageId=7298098)
Where can I get the latest usage guide？
