### ISSUE TITLE
使用模板引擎，指定模板文件会受其它模板文件影响

### ISSUE THREAD

**Issue by hailaz** [gogf/gf#1416]
### 1. What version of `Go` and system type/arch are you using?

go version go1.16.3 windows/amd64

### 2. What version of `GoFrame` are you using?

github.com/gogf/gf v1.16.3

### 3. Can this issue be re-produced with the latest release?

github.com/gogf/gf v1.16.6 不能

#### 使用模板引擎，即使指定模板文件，也会受其它模板文件影响执行。
```go
func Test_TPL(t *testing.T) {
	v := g.View()
	b, err := v.Parse(
		context.TODO(),
		"gview.tpl",
		map[string]interface{}{
			"hello": "world",
		})
	fmt.Println(err)
	fmt.Println(b)
}
```
#### 两个模板文件
```
<!-- gview.tpl -->
test.tpl content, vars: {{.}}
```

```
<!-- gview copy.tpl -->
test.tpl content, vars: {{ hello }}
```
#### 未添加gview copy.tpl文件时正常，添加后报错
gview copy.tpl:2: function "hello" not defined

**Comment by gqcn** [comment]
@hailaz Use `ParseOption` insdead.
