### ISSUE TITLE
How to delete all data in the table?

### ISSUE THREAD

**Issue by jaryf** [gogf/gf#1417]
I want to delete all the data in a data table. I used the Delete() method, but this method seems to have to enter a condition to delete.
I checked the source code, it seems that you have judged whether there is a where condition, if not, it returns an error.
So which method should I use to clear the data?

我想删除一个数据表的全部数据,我使用了Delete()这个方法,但是这个方法好像是必须要输入一个条件才能删除.
我查看了一下源码,好像是里面你判断了是否有where条件,如果没有,就返回错误.
那我应该用哪个方法来清空数据呢?

**Comment by housemecn** [comment]
比如主键大于0就可以

**Comment by hailaz** [comment]
where id >0

**Comment by gqcn** [comment]
@jaryf `Delete` is a sensitive method, so there should be `Where` condition given to make it rigorous.
