### ISSUE TITLE
gf如何设置超时时间?

### ISSUE THREAD

**Issue by kbdxbt** [gogf/gf#1418]
请问下gf怎么设置请求的超时时间, 我尝试通过 config.server.readTimeout 设置没法生效

**Comment by hailaz** [comment]
https://goframe.org/pages/viewpage.action?pageId=1114489
![image](https://user-images.githubusercontent.com/29968474/134887721-f7c1cd7c-f105-4f36-9a90-cb0f5e2a5822.png)
或
```go
s := g.Server()
s.SetReadTimeout(time.Minute)
```

**Comment by kbdxbt** [comment]
> 
> 
> https://goframe.org/pages/viewpage.action?pageId=1114489
> ![image](https://user-images.githubusercontent.com/29968474/134887721-f7c1cd7c-f105-4f36-9a90-cb0f5e2a5822.png)
> 或
> 
> ```go
> s := g.Server()
> s.SetReadTimeout(time.Minute)
> ```



> 
> 
> https://goframe.org/pages/viewpage.action?pageId=1114489
> ![image](https://user-images.githubusercontent.com/29968474/134887721-f7c1cd7c-f105-4f36-9a90-cb0f5e2a5822.png)
> 或
> 
> ```go
> s := g.Server()
> s.SetReadTimeout(time.Minute)
> ```

第一种方法我就是试了不行才问的, 第二种我刚试了也不行. 我在控制器里面sleep5秒, 请求没有断开, 而是继续请求了

**Comment by hailaz** [comment]
> > https://goframe.org/pages/viewpage.action?pageId=1114489
> > ![image](https://user-images.githubusercontent.com/29968474/134887721-f7c1cd7c-f105-4f36-9a90-cb0f5e2a5822.png)
> > 或
> > ```go
> > s := g.Server()
> > s.SetReadTimeout(time.Minute)
> > ```
> 
> > https://goframe.org/pages/viewpage.action?pageId=1114489
> > ![image](https://user-images.githubusercontent.com/29968474/134887721-f7c1cd7c-f105-4f36-9a90-cb0f5e2a5822.png)
> > 或
> > ```go
> > s := g.Server()
> > s.SetReadTimeout(time.Minute)
> > ```
> 
> 第一种方法我就是试了不行才问的, 第二种我刚试了也不行. 我在控制器里面sleep5秒, 请求没有断开, 而是继续请求了

我理解错了，我看看使用什么方法解决。

**Comment by hailaz** [comment]
我看了下源码，目前的中间件方式，好像实现不了。
先记下一些资料
https://studygolang.com/articles/28444
https://blog.csdn.net/lengyue1084/article/details/118144058

**Comment by gqcn** [comment]
@hailaz @kbdxbt 这个`Server`的`ReadTimeout`是由标准库控制的，具体超时时间比较有意思，具体可以自己研究。如果想要达到比较快速的超时控制，自己通过中间件+`ContextTimeout`来控制。
