### ISSUE TITLE
use count sum in with or withall

### ISSUE THREAD

**Issue by zhizhu** [gogf/gf#1427]
I'm using version 1.15.4 of Go

I'm using version 1.16.6 of GoFrame

How can I use function such as COUNT() SUM(), etc in the with() or withall()  mechanism

**Comment by gqcn** [comment]
@zhizhu No, you cannot use complex SQL statement in With feature. Instead you can use `ScanList` for such situation: https://goframe.org/pages/viewpage.action?pageId=1114326
