### ISSUE TITLE
升级到1.6.6后出现undefined: attribute.Any问题

### ISSUE THREAD

**Issue by xinjiayu** [gogf/gf#1428]
# github.com/gogf/gf/net/ghttp/internal/client
../../../../gowork/pkg/mod/github.com/gogf/gf@v1.16.6/net/ghttp/internal/client/client_tracing.go:73:3: undefined: attribute.Any
../../../../gowork/pkg/mod/github.com/gogf/gf@v1.16.6/net/ghttp/internal/client/client_tracing_tracer.go:150:3: undefined: attribute.Any
../../../../gowork/pkg/mod/github.com/gogf/gf@v1.16.6/net/ghttp/internal/client/client_tracing_tracer.go:151:3: undefined: attribute.Any

操作系統： macos
golang版本：1.16

**Comment by housemecn** [comment]
链路追踪的1.0.0版本去掉了这几个方法，可以强制性使用 rc3版本的，但是gf的master已经兼容了1.0.0的代码了

**Comment by zjlx** [comment]
我也遇到这个问题，我目前的解决办法是go.mod文件里有go.opentelemetry.io\otel并且显示是v1.0.1，把它删掉后，运行go mod tidy就解决了，不知道你的情况跟我的是否相同。

**Comment by housemecn** [comment]
> 我也遇到这个问题，我目前的解决办法是go.mod文件里有go.opentelemetry.io\otel并且显示是v1.0.1，把它删掉后，运行go mod tidy就解决了，不知道你的情况跟我的是否相同。

你们俩都是使用了go get -u 或许直接拉取了最新的opentelemetry 的代码。

**Comment by zjlx** [comment]
> > 我也遇到这个问题，我目前的解决办法是go.mod文件里有go.opentelemetry.io\otel并且显示是v1.0.1，把它删掉后，运行go mod tidy就解决了，不知道你的情况跟我的是否相同。
> 
> 你们俩都是使用了go get -u 或许直接拉取了最新的opentelemetry 的代码。

嗯，应该是这个原因了，最近安装了rpcx，它的安装就是用了-u，结果可能导致依赖库的版本变化了。

**Comment by houseme** [comment]
https://github.com/gogf/gf/issues/1515

**Comment by wavechao** [comment]
> 我也遇到这个问题，我目前的解决办法是go.mod文件里有go.opentelemetry.io\otel并且显示是v1.0.1，把它删掉后，运行go mod tidy就解决了，不知道你的情况跟我的是否相同。

同样遇到了这个问题，按这种方式解决了，谢谢

**Comment by houseme** [comment]
> > 我也遇到这个问题，我目前的解决办法是go.mod文件里有go.opentelemetry.io\otel并且显示是v1.0.1，把它删掉后，运行go mod tidy就解决了，不知道你的情况跟我的是否相同。
> 
> 同样遇到了这个问题，按这种方式解决了，谢谢

也可以升级到v1.16.9的版本
