### ISSUE TITLE
http server keepalive问题

### ISSUE THREAD

**Issue by snail007** [gogf/gf#143]
项目需要禁止http的keepailve功能，go官方的http.Server是可以直接使用SetKeepAlivesEnabled方法设置，但是gf框架对http.Server包裹了一层gf/g/net/ghttp/ghttp_server_graceful.go，没找着到可以获取底层http.Server对象的方法，如果有地方可以获取包裹的底层http.Server对象会更加灵活一些。

**Comment by johngcn** [comment]
好的，我看看。

**Comment by johngcn** [comment]
@snail007 你好，可以通过`SetKeepAlive`方法设置开启/关闭`keepalive`功能，默认为开启，例如：
```go
package main

import (
	"github.com/gogf/gf/g"
	"github.com/gogf/gf/g/net/ghttp"
)

func main() {
	s := g.Server()
	s.SetIndexFolder(true)
	s.BindHandler("/", func(r *ghttp.Request) {
		r.Response.Write("hello world")
	})
	s.SetKeepAlive(false)
	s.SetPort(8199)
	s.Run()
}
```
`GF`的`WebServer`功能比较强大，支持多Server、多端口及域名绑定等等特性，因此无法直接暴露底层的`http.Server`给开发者。

**Comment by johngcn** [comment]
@snail007 对了，你得升级框架版本到最新的`v1.6.16`

**Comment by snail007** [comment]
OK
