### ISSUE TITLE
gtcp server关闭时，只关闭了listen，没有关闭且等待正在使用的连接

### ISSUE THREAD

**Issue by ansoda** [gogf/gf#1430]
gtcp server关闭时，只关闭了listen，没有关闭且等待正在使用的连接

**Comment by huangqian1985** [comment]
这个问题不是框架本身应该提供的, 因为框架本身不会管理连接到server的client, 自然就没有办法去主动调用client socket的close方法. 你可以在主动关闭gtcp的时候, 遍历你管理的每个client调用socket close方法, 或者是客户端监测与服务器的断开状态(一般是 recv 方法返回错误)

**Comment by huangqian1985** [comment]
[WeOpen Star]I would like to help
