### ISSUE TITLE
建议换官网的托管平台，试过很多次，打开乱码，或者打不开

### ISSUE THREAD

**Issue by FTLLOVE** [gogf/gf#1433]
![image](https://user-images.githubusercontent.com/22320062/136723751-509fdeea-684d-441f-a81f-24e5163770d2.png)

**Comment by danvinhe** [comment]
ip是香港的，某些地区的某些运营商，可能需要翻墙。
最好的做法还是去备案，放到国内

**Comment by FTLLOVE** [comment]
翻墙了有的时候还是不行，建议强哥还是换一个

**Comment by gqcn** [comment]
[摆手]

**Comment by lala0257** [comment]
大家捐点钱，把官网搞上去。 访问都访问不到，让人感觉有点鸡肋~

**Comment by psx516** [comment]
在本地加一个DNS解析就好了 因为IP地址是固定的 43.129.15.157
