### ISSUE TITLE
order by field

### ISSUE THREAD

**Issue by caveychen** [gogf/gf#1434]
goframe代码：dao.XXX.Order("field(id, 1, 2)").All()
生成的SQL语句：ORDER BY field(\`id\`,\`1\`,2)，会对1使用反引号，导致报错Error 1054: Unknown column '1' in 'order clause'

**Comment by gqcn** [comment]
@CaveyChan 你试试`gdb.Raw`，如果不行的话，可以增加对`gdb.Raw`的支持。

**Comment by zhonghuaxunGM** [comment]
problem solved
