### ISSUE TITLE
gdb.raw()方法未生效

### ISSUE THREAD

**Issue by psx516** [gogf/gf#1435]
### 1. What version of `Go` and system type/arch are you using?

go version 1.17,1

### 2. What version of `GoFrame` are you using?

gf version 1.16.6

### 4. What did you do?

使用的oracle数据库

```go
var contrlist gdb.List
for _, i := range conidres { //遍历数组中所有元素追加成string
k, _ := i["CONTRAID"]
paramap := g.Map{
"ID":         gconv.Int(grand.Digits(18)),
"STATE":      1,
"START_DATE": gdb.Raw("systimestamp"),
"CONTRAID":   k.String(),  //一个字符串
}
contrlist = append(contrlist, paramap)
}
rs, erro := g.DB().Insert("formmain_3047", contrlist)
```

最后生成的语句 raw功能没有生效，systimestamp被当做字符串处理

"ORA-01858: a non-numeric character was found where a numeric was expected\n, INSERT ALL INTO formmain_3047(id,state,start_date,field0018) VALUES(571046924887305126,1,'systimestamp','PZLHT2021004821') INTO formmain_3047(id,state,start_date,field0018) VALUES(70896015181989927,1,'systimestamp','PZLHT2021003471')

### 5. What did you expect to see?
正确的处理结果应该是作为系统函数提交

**Comment by danvinhe** [comment]
看源码是没有特殊处理下Raw类型的参数https://github.com/gogf/gf/blob/a2c5c577dbfa5b5c3b0c0ba7b991013a3aa0a8c1/database/gdb/gdb_driver_oracle.go#L286

我没有用oracle，修改后无法验证。希望你可以提交pr，修改请参考这里。https://github.com/gogf/gf/blob/a2c5c577dbfa5b5c3b0c0ba7b991013a3aa0a8c1/database/gdb/gdb_core.go#L419

**Comment by danvinhe** [comment]
> > 看源码是没有特殊处理下Raw类型的参数
> > https://github.com/gogf/gf/blob/a2c5c577dbfa5b5c3b0c0ba7b991013a3aa0a8c1/database/gdb/gdb_driver_oracle.go#L286
> > 
> > 我没有用oracle，修改后无法验证。希望你可以提交pr，修改请参考这里。
> > https://github.com/gogf/gf/blob/a2c5c577dbfa5b5c3b0c0ba7b991013a3aa0a8c1/database/gdb/gdb_core.go#L419
> 
> 感谢您的回复，我不会提交pr（个人开发者），就把代码贴这里了
> 
> ```
> func FormatSqlWithArgs(sql string, args []interface{}) string {
> 	index := -1
> 	newQuery, _ := gregex.ReplaceStringFunc(
> 		`(\?|:v\d+|\$\d+|@p\d+)`,
> 		sql,
> 		func(s string) string {
> 			index++
> 			if len(args) > index {
> 				if args[index] == nil {
> 					return "null"
> 				}
> 				if v, ok := args[index].(Raw); ok {
> 					return gconv.String(v)
> 				} else {
> 					var (
> 						rv   = reflect.ValueOf(args[index])
> 						kind = rv.Kind()
> 					)
> 					if kind == reflect.Ptr {
> 						if rv.IsNil() || !rv.IsValid() {
> 							return "null"
> 						}
> 						rv = rv.Elem()
> 						kind = rv.Kind()
> 					}
> 
> 					switch kind {
> 					case reflect.String, reflect.Map, reflect.Slice, reflect.Array:
> 						return `'` + gstr.QuoteMeta(gconv.String(args[index]), `'`) + `'`
> 
> 					case reflect.Struct:
> 						if t, ok := args[index].(time.Time); ok {
> 							return `'` + t.Format(`2006-01-02 15:04:05`) + `'`
> 						}
> 						return `'` + gstr.QuoteMeta(gconv.String(args[index]), `'`) + `'`
> 					}
> 					return gconv.String(args[index])
> 				}
> 
> 			}
> 			return s
> 		})
> 	return newQuery
> ```

咱俩修的方式略微不一样哈，我是直接把这种类型的参数填充到sql，而不是像其他类型的用?和参数填充。
感觉你的方式更好些，我去提交个pr。
任何人都可以提交pr哈，这也是对开源社区的贡献方式。
