### ISSUE TITLE
session文件都已经过期好久了 但是为什么还不清除？

### ISSUE THREAD

**Issue by Insua** [gogf/gf#1437]
![截图_2021-10-15_14-50-29.png](http://tva1.sinaimg.cn/large/002QsfEQly1gvg0ldd4e4j60v40sukjl02.jpg)

长此以往下去，这session文件不得越来越多 最后把服务器干爆了？

哪里的配置 能让session文件 清除，比如我这session 设置的是24小时过期 那最后修改时间是24小时的session文件 肯定得被删除了

**Comment by Insua** [comment]
如果 我想自己去手动清除过期时间都一个月以上的session文件 怎么去清理呢？

**Comment by gqcn** [comment]
> 如果 我想自己去手动清除过期时间都一个月以上的session文件 怎么去清理呢？

你这个场景，如果非要强行手动清理，可以编写定时任务删除session目录下满足条件的文件即可。

**Comment by Insua** [comment]
哪个函数能获取session目录 谢谢
