### ISSUE TITLE
pgsql insert bug

### ISSUE THREAD

**Issue by hametan** [gogf/gf#1439]
使用pgsql时,dao.insert,如果遇到主键字段会报错，查看SQL，SQL里有主键字段，这个是必现，就不需要发代码了吧。

**Comment by redwolf2019** [comment]
+

**Comment by redwolf2019** [comment]
+1

**Comment by gqcn** [comment]
> 

`FieldsEx`？https://goframe.org/pages/viewpage.action?pageId=1114229
