### ISSUE TITLE
多数据校验 - CheckMap 无效

### ISSUE THREAD

**Issue by hbsycc** [gogf/gf#1443]
### 1. What version of `Go` and system type/arch are you using?
go version go1.16.6 windows/amd64

### 2. What version of `GoFrame` are you using?
GoFrame Version: v1.16.6 in current go.mod

### 4. What did you do?

``````
	params := map[string]string{
		//"zh-CN": "中文",
		"en": "英文",
	}
	rules := []string{
		"zh-CN@required|length:1,16#中文required有效|中文length有效",
		"en@required|length:1,16#英文required有效|英文length有效",
	}

	if err := g.Validator().Rules(rules).CheckMap(params); err != nil {
		fmt.Println(err.Map())
	} else {
		fmt.Println(err == nil)
	}
``````

### 5. What did you expect to see?

map[required:中文required有效 length:中文length有效]

### 6. What did you see instead?

true

**Comment by huangqian1985** [comment]
#之后的提示是规则校验失败才会打印的内容，你的这个规则校验是成功的， 所以打印的结果是true

**Comment by gqcn** [comment]
@hbsycc So it is as @huangqian1985 explained.
