### ISSUE TITLE
ScanList根据其中1个对象的key，查询赋值给另一个对象时报错 

### ISSUE THREAD

**Issue by qinshinailiu** [gogf/gf#1444]
### 1. What version of `Go` and system type/arch are you using?
go version go1.16.2 windows/amd64

### 2. What version of `GoFrame` are you using?
 v1.16.6

### 3. Can this issue be re-produced with the latest release?
会

### 4. What did you do?
        //填充alarm
	if err := dao.FilmAlarm.Ctx(ctx).Where(condition).
		Order(dao.FilmAlarm.Columns.CreateTime+" desc").
		Page(input.Page, input.Limit).
		ScanList(&alarms, "Alarm"); err != nil {
		return resp, err
	}
	//填充Film
	if err := dao.FilmFilm.Ctx(ctx).Where(g.Map{
		dao.FilmFilm.Columns.FilmId:           gdb.ListItemValuesUnique(alarms, "Alarm", "FilmId"),
		dao.FilmFilm.Columns.FilmId + " <> ?": 0,
		dao.FilmFilm.Columns.DevId:            input.DevId,
	}).ScanList(&alarms, "Film", "Alarm", "FilmId:FilmId"); err != nil {
		return resp, err
	}
	//填充FilmInfo
	if err := dao.FilmFilmInfo.Ctx(ctx).Where(g.Map{
		dao.FilmFilmInfo.Columns.InfoId:           gdb.ListItemValuesUnique(alarms, "Film", "InfoId"),
		dao.FilmFilmInfo.Columns.InfoId + " <> ?": 0,
		dao.FilmFilmInfo.Columns.DevId:            input.DevId,
	}).ScanList(&alarms, "FilmInfo", "Film", "InfoId:InfoId"); err != nil {
		return resp, err
	}
alarm中有filmId，film中有infoid，filminfo中也有infoID
出现报错 invalid relation specified: \"[Film InfoId:InfoId]\"

**Comment by gqcn** [comment]
@qinshinailiu 这个issue我感觉无从下手，可以先试试最新框架版本，如果问题依旧请给SQL以及复现问题代码。

**Comment by hellotrik** [comment]
https://github.com/gogf/focus
