### ISSUE TITLE
功能建议：建议支持Controller每个方法单独Method

### ISSUE THREAD

**Issue by finchcn** [gogf/gf#1457]
建议支持注册Controller或者Object时，支持以方便的方式对每个Action单独设置Method

比如可以通过方法名前缀，
如GetSome绑定GET /prefix/controller/some 
PostSome 绑定POST /prefix/controller/some

**Comment by Mortence** [comment]
这样不能实现吗
```
group.GET("/GetSome", some.GetSome)
group.POST("/GetSome", some.PostSome)
```

**Comment by gqcn** [comment]
@finchcn 这种问题也提`issue`？

**Comment by finchcn** [comment]
我希望能有的是一种更便捷的方式，一行语句绑定整个controller，但是每个方法不同Method，而不是一个一个func的绑定，只是一个更便捷的提议
