### ISSUE TITLE
同一个浏览器两个页面发送http请求问题

### ISSUE THREAD

**Issue by yincongcyincong** [gogf/gf#146]
同一个浏览器两个页面发送http请求，发送请求的返回值不属于自己，是另一个页面的

**Comment by yincongcyincong** [comment]
go v1.11

**Comment by jroam** [comment]
首先，你这个问题描述得不是很清楚。
其次，我猜，请求路径有没问题，用postman工具仔细测试一下。
最后，99.9999%不是go的问题。

**Comment by johngcn** [comment]
@yincongcyincong 这个问题很奇怪，服务端的请求流程是通过`*Request`对象传递请求和返回数据的。你只有在自己的前后端请求流程上检查下，特别是加点调试信息。另外，如果你对`*Request`做了什么缓存处理，着重检查下。

PS：以后提问题描述详细一些，以便提高交流和执行的效率高。

**Comment by yincongcyincong** [comment]
路由复用对象导致的，已经解决了
