### ISSUE TITLE
convertRowsToResult  bug

### ISSUE THREAD

**Issue by AmarsDing** [gogf/gf#1464]
《convertRowsToResult》 methods have a bug

### 1. What version of `Go` and system type/arch are you using?

go 1.16

### 2. What version of `GoFrame` are you using?

v1.16.6

### 3. Can this issue be re-produced with the latest release?

yes

### 4. What did you do?
```sql
SELECT *
FROM "tableA" a
LEFT JOIN "tableB" b
ON  ( a."time" =b."time" ) 
```
```
tableA  fields  =  tableB fields
tableA  fields is [  user, time, class  ]
tableB  fields is [ user, time, class ]
```
the query data is formated by convertRowsResult with record map,  and record key is columns name 

--------------------------------------
```go
for {
		if err := rows.Scan(scanArgs...); err != nil {
			return result, err
		}
		record := Record{}
		for i, value := range values {
			if value == nil {
				record[columnNames[i]] = gvar.New(nil)
			} else {
				record[columnNames[i]] = gvar.New(c.convertFieldValueToLocalValue(value, columnTypes[i]))
			}
		}
		result = append(result, record)
		if !rows.Next() {
			break
		}
	}
```
--------------------------------------

### 5. What did you expect to see?

the right result of leftjoin  query 

### 6. What did you see instead?

the query result is error

**Comment by gqcn** [comment]
@AmarsDing Your queried result have duplicated columns, so the last one overwrites the previous one. I do not think it is a bug.
