### ISSUE TITLE
使用gf dao生成的代码进行插入操作的时候忽略自定义字段

### ISSUE THREAD

**Issue by redwolf2019** [gogf/gf#1469]
### 1. What version of `Go` and system type/arch are you using?

```go version go1.17.2 darwin/amd64```

### 2. What version of `GoFrame` are you using?

```github.com/gogf/gf v1.16.6```

### 3. Can this issue be re-produced with the latest release?

```Yes```

### 4. What did you do?

- 使用```gf dao```生成的对象进行ORM操作的时候，用结构体写入的方法，是否有方法可以忽略某些字段的插入？
```
type User struct {
    Id int64
    Username string
    Password string
}

dao.User.insert(&User{
   Username: "hello",
   Password: "world",
})

```

- 这种情况，希望能有方法能忽略id字段的插入

### 5. What did you expect to see?

- 希望能有类似ingore的方法
```
dao.User.insert(&User{
   Username: "hello",
   Password: "world",
}).IgnoreFields("id","other")
```

**Comment by OathMoon** [comment]
新的gf-cli可以通过参数生成model_dao.go文件，里面的struct字段类型都是interface{}，说是为这类需求设计的

**Comment by mingzaily** [comment]
关注v2版本
