### ISSUE TITLE
单元测试在不同环境下的运行出现了巨大差异

### ISSUE THREAD

**Issue by similarJ** [gogf/gf#1470]
`package api

import (
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/test/gtest"
	"testing"
)

func Test_account(t *testing.T)  {
	prefix :="http://127.0.0.1:8599"
	cl := g.Client()
	cl.SetPrefix(prefix)
	gtest.C(t, func(t *gtest.T) {
		t.Assert(cl.GetContent("/api/account/register"), "{\"code\":400,\"data\":null,\"message\":\"请输入手机号; 请输入密码; 密码长度为6到20位; 请确认密码; 两次密码不一致; 请输入验证码\"}\n")
	})
}`
在windows上执行go test可以正常运行，在linux上抛出如下错误
![image](https://user-images.githubusercontent.com/5722511/141037774-d6c3b4a9-b40f-4777-92b0-1f3551372af0.png)
非常奇怪的问题。

**Comment by ansionfor** [comment]
贴一下linux下的接口输出接口
