### ISSUE TITLE
[BUG] g.Cfg()  set  value can't support hierarchical data access by char separator

### ISSUE THREAD

**Issue by tianbocheng** [gogf/gf#1471]
# 1. go and gf version
github.com/gogf/gf v2.0.0-alpha   and   v2.0.0-alpha
go1.16 darwin/amd64

# 2. step
```
ctx := context.TODO()
g.Cfg().Set(ctx, "logger", map[string]interface{}{})
g.Cfg().Set(ctx, "logger.level", "debug")
testVar, _ := g.Cfg().Get(ctx, "logger")
fmt.Println(testVar)

```

# 3. What did you expect to see?
It supports hierarchical data access by char separator, which is '.' in default.

**Comment by gqcn** [comment]
@tianbocheng It makes confusion when using `gcfg.Config.Set`, so it will be removed in latest version.
