### ISSUE TITLE
HTTP 服务端出错易导致上层 API 网关出现 panic

### ISSUE THREAD

**Issue by lrioo** [gogf/gf#1473]
### 1. What version of `Go` and system type/arch are you using?

go version go1.15.8 linux/amd64

### 2. What version of `GoFrame` are you using?

github.com/gogf/gf v1.16.5

### 3. Can this issue be re-produced with the latest release?

yes

### 4. What did you do?

HTTP 客户端发起的请求通过 API 网关进行路由转发；API 网关反向代理到 HTTP 服务端。

当服务端出现 卡死（导致超时 context canceled 错误）/崩溃（导致连接断开 EOF错误） 等情况后，API 网关日志中易出现如下输出：

![image](https://user-images.githubusercontent.com/38975626/141227434-50752bc9-e1d7-4f55-88f3-c0df2a3ddea9.png)

### 5. What did you expect to see?

是否有人遇到过类似问题，抑或是我使用方法有误？

如果是已知问题，是否有解决方案和解决计划。

**Comment by gqcn** [comment]
@lrioo There might be bug at `ghttp_server_handler.go:88` in your case. It is appreciated if your commit PR or it will be scheduled to be further checked.

**Comment by lrioo** [comment]
@gqcn I'd read the code in `ghttp_server_handler.go`, but have no idea how this panic happened. sorry for that.

**Comment by starccck** [comment]
Can you give more detail to reproduce the case? It will help solving the problem.

**Comment by lrioo** [comment]
@starccck 

We use `g.Server().Group()` to handle Router.
```go
g.Server().Group("/", func(group *ghttp.RouterGroup) {
    group.ALL("/*", api.ReverseProxy.Reverse)
})
```

And do ReverseProxy with underlying `ResponseWriter` and `Request`.
```go
func (p *reverseProxy) Reverse(r *ghttp.Request) {
	p.ServeHTTP(r.Response.ResponseWriter, r.Request)
}
```

Underlying dependency is `ReverseProxy.ServeHTTP` in `net/http/httputil/reverseproxy.go`.

**Comment by gqcn** [comment]
@lrioo 请提供下复现该问题的，可运行的代码。
