### ISSUE TITLE
数据量不是很大，但是批量保存会报错

### ISSUE THREAD

**Issue by FTLLOVE** [gogf/gf#1475]
![image](https://user-images.githubusercontent.com/22320062/141428998-f7a05260-7df2-454c-882d-49c96d9e05af.png)
![image](https://user-images.githubusercontent.com/22320062/141429026-d759231e-5136-4436-934f-13ed9458ab23.png)
![image](https://user-images.githubusercontent.com/22320062/141429063-cd0193f3-43a3-4b2d-af34-84c0944729f9.png)

**Comment by FTLLOVE** [comment]
数据量少的情况下保存是不会出现这种问题的

**Comment by FTLLOVE** [comment]
![image](https://user-images.githubusercontent.com/22320062/141429368-687d306b-0e59-4dd6-8a7f-d494799b3f89.png)
这种方式同样会报错

**Comment by LonelySally** [comment]
> ![image](https://user-images.githubusercontent.com/22320062/141429368-687d306b-0e59-4dd6-8a7f-d494799b3f89.png) 这种方式同样会报错

链式一个.Batch(512)试试

**Comment by FTLLOVE** [comment]
![image](https://user-images.githubusercontent.com/22320062/143537191-7570a60f-87dc-4375-811d-518e1274d6b3.png)
![image](https://user-images.githubusercontent.com/22320062/143537244-2edc386e-3bf0-48bc-83b8-868f74fa9d2c.png)
![image](https://user-images.githubusercontent.com/22320062/143537285-df59bc07-5bda-47b0-893c-9f6171368ff5.png)
说实话感觉并不是很好用

**Comment by LonelySally** [comment]
> ![image](https://user-images.githubusercontent.com/22320062/143537191-7570a60f-87dc-4375-811d-518e1274d6b3.png) ![image](https://user-images.githubusercontent.com/22320062/143537244-2edc386e-3bf0-48bc-83b8-868f74fa9d2c.png) ![image](https://user-images.githubusercontent.com/22320062/143537285-df59bc07-5bda-47b0-893c-9f6171368ff5.png) 说实话感觉并不是很好用

这个错误本身就不是框架返回的 属于mysql返回的错误.写的很明显占位符过多.另外你BatchInster第三个参数传数据长度跟没分批有什么区别?

**Comment by LonelySally** [comment]
.Batch(512)这里的512指代的是每次执行多少条数据而不是你的数据长度,如果这里的给定为数据长度跟all-in-one有什么区别,要根据业务的每一条数据执行是需要占位的数据来决定一次批量写入多少条.关于mysql一次传入多少个占位符百度下就清楚了.

**Comment by gqcn** [comment]
@FTLLOVE So it is as @LonelySally explained.

**Comment by FTLLOVE** [comment]
我明白了，我换成拼接，分批次就好了，感谢解释
