### ISSUE TITLE
ORM查询-Scan 解析字段不支持orm tag

### ISSUE THREAD

**Issue by sanrentai** [gogf/gf#1477]
### 1. What version of `Go` and system type/arch are you using?

go1.17.1 windows/amd64

### 2. What version of `GoFrame` are you using?

1.16.6 

### 3. Can this issue be re-produced with the latest release?

yes

### 4. What did you do?

type InfoBasis struct {
	CompanyId         int64       `json:"company_id" orm:"company_id"`    
        RoomId            int64       `json:"room_id" orm:"room_id"`  
} 
var resp *InfoBasis
m := g.DB().Model("v_info_basis")
m.Where("room_id=?", 123)
err = m.Scan(&resp)

### 5. What did you expect to see?

select company_id,room_id from v_info_basis where room_id=123

### 6. What did you see instead?

select CompanyId,RoomId from v_info_basis where room_id=123

**Comment by sanrentai** [comment]
v_info_basis  is  view not table

**Comment by gqcn** [comment]
@sanrentai Please submit codes that can reproduce this issue.

**Comment by gqcn** [comment]
> 

OK, I see. It cannot retrieve columns information from `view` currently, that is needed be improved.
