### ISSUE TITLE
版本1.16.6，使用SUM不正确

### ISSUE THREAD

**Issue by hackchen01** [gogf/gf#1482]
g.DB().Model("test").Fields("id").Fields("name").Sum("id")，最后生成的SQL为  SELECT id,name,SUM(id) FROM test，期望生成的SQL语句为 SELECT SUM(id) FROM test，版本1.16.1经过测试，生成的是  SELECT SUM(id) FROM test

**Comment by danvinhe** [comment]
看代码是有优化，直接使用g.DB().Model("test").Sum("id")即可
