### ISSUE TITLE
阿里云镜像下载最新版依赖失败

### ISSUE THREAD

**Issue by kim709394** [gogf/gf#1484]
### 1. What version of `Go` and system type/arch are you using?
go v1.17   windows

go version go1.17.3 windows/amd64

### 2. What version of `GoFrame` are you using?
1.17

### 3. Can this issue be re-produced with the latest release?

https://mirrors.aliyun.com/goproxy/
此阿里云镜像代理地址无法下载最新版本的依赖，1.16之前的都可以。

**Comment by housemecn** [comment]
阿里云的好像是每天同步一次，建议使用 https://goproxy.cn

**Comment by kim709394** [comment]
> 阿里云的好像是每天同步一次，建议使用 https://goproxy.cn

换成https://goproxy.cn之后，更新latest只能更新到1.16.6

**Comment by housemecn** [comment]
> > 阿里云的好像是每天同步一次，建议使用 https://goproxy.cn
> 
> 换成https://goproxy.cn之后，更新latest只能更新到1.16.6

如果需要更新到v2 还是1.16.7-xxxx呢？
可以试试 go get -u github.com/gogf/gf@master
