### ISSUE TITLE
gtime 可以配置或者设置时区

### ISSUE THREAD

**Issue by zhzhong6** [gogf/gf#1490]
### 1. What version of `Go` and system type/arch are you using?
go 1.16 

### 2. What version of `GoFrame` are you using?
1.16

### 3.背景
1，数据库存的是UTC 0 时区时间 （为了避免时间和机器时区依赖）
2，gtime 时间依赖本地机器时区，created_at 等默认直接是本地时间的string;
3，此时迁移到goframe 时区没法设置

### 4. What did you expect to see?
3，希望 orm 中 gtime 可以设置默认时区

**Comment by locxiang** [comment]
可以设置时区  

```golang

	err := gtime.SetTimeZone("Asia/Shanghai")

```
