### ISSUE TITLE
建议 gen dao 提供 将mysql tinyint(1) 转成bool 的能力

### ISSUE THREAD

**Issue by zhzhong6** [gogf/gf#1491]
### 1. What version of `Go` and system type/arch are you using?
1.16
### 2. What version of `GoFrame` are you using?
1.16

### 4. What did you do?
1,bool 值insert 到mysql 存储成tinyint(1)
2,gen dao 出来的结构体 字段是int ，不是bool

**Comment by houseme** [comment]
> ### 1. What version of `Go` and system type/arch are you using?
> 1.16
> 
> ### 2. What version of `GoFrame` are you using?
> 1.16
> 
> ### 4. What did you do?
> 1,bool 值insert 到mysql 存储成tinyint(1) 2,gen dao 出来的结构体 字段是int ，不是bool

tinyint(1) 范围不止0，1 ,还可以是其他的-9，9范围内的
