### ISSUE TITLE
关于协程管理-grpool的使用疑问

### ISSUE THREAD

**Issue by feng99** [gogf/gf#1493]
### 1. What version of `Go` and system type/arch are you using?

```

CLI Built Detail:
  Go Version:  go1.16.3
  GF Version:  v1.16.0

```

### 2. What version of `GoFrame` are you using?

```
GoFrame CLI Tool v1.16.3, https://goframe.org
GoFrame Version: v1.15.7 in current go.mod
CLI Installed At: C:\Go\bin\gf.exe
```

### 3. Can this issue be re-produced with the latest release?
```
yes
```

### 4. What did you do?
```
package main

import (
	"fmt"

	"github.com/gogf/gf/os/glog"

	"github.com/gogf/gf/net/ghttp"
	"github.com/gogf/gf/os/grpool"
)

func main() {
	//开启pprof检测功能
	//程序运行后访问http://127.0.0.1:8299/debug/pprof
	go ghttp.StartPProfServer(8299)
	pool := grpool.New(10)

	//定义一个缓冲的队列
	jobList := make(chan string, 20)
	pool.Add(func() {
		for true {
			json := "98766984k54jh"
			jobList <- json
		}
	})

	pool.Add(func() {
		for v := range jobList {
			glog.Debug(v)
			fmt.Println("worker:", pool.Size())
			fmt.Println("  jobs:", pool.Jobs())
		}
	})

	select {}
}

```

### 5. What did you expect to see?
数字不应该是98
应该是我自己的理解有误, 求各位路过的大佬 科普下, 十分感谢.

### 6. What did you see instead?

http://127.0.0.1:8299/debug/pprof/goroutine?debug=2
这里看到的正在运行的goroutine数量和pool里设置的10个数字不一样.
goroutine 98 [running]:
为何是98个?

还是我代码的使用方式有误呢?

main函数有个协程
pprof我开了一个协程
pool.Add了2次
一共是4个协程

98这个数字 是怎么来的?

------
求各位路过的大佬 科普下, 十分感谢.

**Comment by tiktm** [comment]
因为其它地方也用了goroutine
