### ISSUE TITLE
gf，我从1.16.2版本升级到1.16.6版本后orm结果和原先不符。

### ISSUE THREAD

**Issue by chenyuwulu** [gogf/gf#1502]
### 1. What version of `Go` and system type/arch are you using?
go1.17.3 windows/amd64

### 2. What version of `GoFrame` are you using?
gf 1.16.6

### 3. Can this issue be re-produced with the latest release?
yes

### 4. What did you do?
存储在数据库里的字段类型是字符串，通过garray.array定义类型，orm的scan进行查询，结果是1.16.2可以直接转换成数组，而在1.16.6无法转换成数组，请问这是orm的bug还是特性修改了？
```
type Log struct {
	Id         int          `orm:"id"  json:"id"`
	Title      string       `orm:"title"  json:"title"`
	Content    garray.Array `orm:"content" json:"content"`
	Time       string       `orm:"time"  json:"time"`
	EditTime   int          `orm:"edittime"  json:"edittime"`
	CreateTime int          `orm:"createtime"  json:"createtime"`
}

func (a *main) GetLog(*ghttp.Request) *response.Response {
	var logs []*Log
	_ = g.DB().Model(logs).Order("id desc").Scan(&logs)
	return &response.Response{Data: logs, Message: "获取成功!"}
}
```

### 5. What did you expect to see?

![mysql](https://user-images.githubusercontent.com/32855928/143794831-dd205707-9e69-4e95-ad33-8cd5dda9a6cf.png)
![okres](https://user-images.githubusercontent.com/32855928/143794849-057002ca-43df-4080-8e7e-d94bfb1ee1b6.png)

### 6. What did you see instead?

![mysql](https://user-images.githubusercontent.com/32855928/143794857-42413969-e1a0-4ce7-bb15-2187b4660f0a.png)
![fuckres](https://user-images.githubusercontent.com/32855928/143794860-42879239-6869-4e4e-aef4-d7d18b861bc0.png)

**Comment by gqcn** [comment]
@chenyuwulu 你好，是可以实现转换的，请试试最新的master分支，如果问题依旧请提供复现SQL和可运行代码。
