### ISSUE TITLE
query执行update操作导致的阻塞问题

### ISSUE THREAD

**Issue by cocotww** [gogf/gf#1514]
### 1. What version of `Go` and system type/arch are you using?
 go1.15.11 windows/amd64

### 2. What version of `GoFrame` are you using?
gf v1.15.3

### 3. Can this issue be re-produced with the latest release?
没有用最新的版本重现过

### 4. What did you do?

使用query方法执行一个更新的sql，会导致连接池连接耗尽，后续sql操作会被阻塞

### 5. What did you expect to see?

已经解决问题，使用exe方法即可，但是想知道为什么会出现该情况

### 6. What did you see instead?

我将连接池有效时间设置为10s，连接池不会回收被占用的连接，被阻塞的后续db操作不会超时抛出异常

**Comment by LonelySally** [comment]
```
rows,err:=g.DB().Query("do it")
if err!=nil{
   defer rows.Close()
}
```
