### ISSUE TITLE
How can i fix this issue?

### ISSUE THREAD

**Issue by stiffer831** [gogf/gf#1515]
![image](https://user-images.githubusercontent.com/23020938/145214727-77478ed4-4a05-46e5-94fd-93e82a828592.png)

**Comment by houseme** [comment]
把go.opentelemetry.io/otel 该包都设置为v1.0.0-RC3的版本就可以了，应该是你执行了 go get -u 的命令，间接更新了go.opentelemetry.io/otel

**Comment by stiffer831** [comment]
> 

请问如何更新呢，新手，感谢！

**Comment by houseme** [comment]
> > 
> 
> 请问如何更新呢，新手，感谢！


`go get go.opentelemetry.io/otel@v1.0.0-RC3 `

**Comment by stiffer831** [comment]
> > > 
> > 
> > 
> > 请问如何更新呢，新手，感谢！
> 
> `go get go.opentelemetry.io/otel@v1.0.0-RC3 `

非常感谢！！！
