### ISSUE TITLE
glog的打印格式顺序可否自定义？

### ISSUE THREAD

**Issue by jialeo** [gogf/gf#1519]
### 1. What version of `Go` and system type/arch are you using?

 linux/amd64

### 2. What version of `GoFrame` are you using?

1.16.6

### 4. What did you do?

当前日志打印：
```
2021-12-11 10:21:45.859 [DEBU] {be072e39-9944-4f71-9c72-2b155f5c3df1} server.go:157:   xxxxxxxxx
```

是否能自定义requestId的内容在调用行号信息后？

期望定义后的格式：

```
2021-12-11 10:21:45.859 [DEBU] server.go:157 {be072e39-9944-4f71-9c72-2b155f5c3df1} :   xxxxxxxxx
```

**Comment by houseme** [comment]
> ### 1. What version of `Go` and system type/arch are you using?
> linux/amd64
> 
> ### 2. What version of `GoFrame` are you using?
> 1.16.6
> 
> ### 3. Can this issue be re-produced with the latest release?
> ### 4. What did you do?
> 当前日志打印：
> 
> ```
> 2021-12-11 10:21:45.859 [DEBU] {be072e39-9944-4f71-9c72-2b155f5c3df1} server.go:157:   xxxxxxxxx
> ```
> 
> 是否能自定义requestId的内容在调用行号信息后？
> 
> 期望定义后的格式：
> 
> ```
> 2021-12-11 10:21:45.859 [DEBU] server.go:157 {be072e39-9944-4f71-9c72-2b155f5c3df1} :   xxxxxxxxx
> ```

改成这样之后的目标是什么以及可以带来哪些优势呢？

**Comment by aloncn** [comment]
https://goframe.org/pages/viewpage.action?pageId=17207121
