### ISSUE TITLE
关于token session功能实现

### ISSUE THREAD

**Issue by arden** [gogf/gf#152]
现在的大多数应用，比如：app、小程序等，session方案基本上都已经不依赖于cookie的机制了，大多数都直接采用从header或者url里传递token的机制来做session处理，所以gf是不是可以改进成优先从header里取session id，这样就实现了token机制的session方案了。

**Comment by arden** [comment]
因为实际上现在基于cookie机制的session方案很少用，放在那里也耗资源，可以提供一个配置功能让用户可以直接屏蔽cookie的session，以便节省资源。

**Comment by johngcn** [comment]
@arden `v2.0`版本增加对`header`传递`sessionid`的支持，另外`jwt`功能可以参考：https://github.com/gogf/gf-jwt

**Comment by johngcn** [comment]
@arden 请更新到最新框架版本再试试。
