### ISSUE TITLE
generate swagger error

### ISSUE THREAD

**Issue by stiffer831** [gogf/gf#1522]
根据官方文档提供的命令: `gf swagger --pack` 生成文档失败，提示如下:   
flag provided but not defined: -o

**Comment by houseme** [comment]
使用新版本吧

**Comment by zut** [comment]
> 使用新版本吧

Gf-swag 仓库都不更新了……

**Comment by housemecn** [comment]
> > 使用新版本吧
> 
> Gf-swag 仓库都不更新了……

https://goframe.org/pages/viewpage.action?pageId=30736904 看这个文档

**Comment by gqcn** [comment]
@stiffer831 是的，该命令维护成本太高，为了让大家在2.14也能少加班陪伴女友，该命令已废除，新版本提供了更好的方式释放生产力。
