### ISSUE TITLE
ghttp.Request 调用Parse方法在转成map[string]interface{} 时，数据转成float64时出现BUG

### ISSUE THREAD

**Issue by sanrentai** [gogf/gf#1523]
### 1. What version of `Go` and system type/arch are you using?
go1.17.1 windows/amd64
### 2. What version of `GoFrame` are you using?
v1.16.6 , v2.0.0-beta 都能出现这个BUG

经过测试v1.15.1版本正常

### 3. Can this issue be re-produced with the latest release?
Yes

### 4. What did you do?
```
type Request struct {
	Act  string                 `json:"act"`
	Data map[string]interface{} `json:"data"`
}

var jsonString = `{
	"act": "chaXun",
	"data": {
			"jinE": 0.01
	}
}`

func jsonUmarshal() {
	req := Request{}
	err := json.Unmarshal([]byte(jsonString), &req)
	if err != nil {
		panic(err)
	}
	data := req.Data
	g.Log().Info(data)
	jinE, ok := data["jinE"].(float64)
	g.Log().Info(jinE, ok)
}
func main() {
	jsonUmarshal()
	s := g.Server()
	s.Group("/", func(group *ghttp.RouterGroup) {
		group.ALL("/bug1", func(r *ghttp.Request) {
			g.Log().Info(r.GetBodyString())
			var req *Request
			if err := r.Parse(&req); err != nil {
				g.Log().Error(err)
				return
			}
			data := req.Data
			g.Log().Info(data)
			jinE, ok := data["jinE"].(float64)
			g.Log().Info(jinE, ok)

		})
	})
	s.SetAddr(":8199")
	s.Run()
}
```
在解析参数时,jinE总是0

### 5. What did you expect to see?

0.01 true

### 6. What did you see instead?

0 false

**Comment by jqb44179** [comment]
你好，gf在后面的版本里面json反序列化采用了`json.UnmarshalUseNumber()`方式进行处理，该方法会对float64替换成json.number，建议在使用的时候采用`reflect.TypeOf(data["jinE"])`的方式判断下具体的类型，然后再进行断言
![image](https://user-images.githubusercontent.com/5601043/147642642-9b8aafbd-e5d3-4827-a247-27d17150f31d.png)

**Comment by jqb44179** [comment]
至于为什么要采用这种方式，是为了解决科学计数法的问题，如果还有问题欢迎随时联系，这个issue就先关闭了哈
