### ISSUE TITLE
gproc.ShellExec 没有输出

### ISSUE THREAD

**Issue by liuchenailq** [gogf/gf#1526]
我的程序和示例一样，但没有输出命令的执行结果
package main

import (
   "fmt"
   "github.com/gogf/gf/os/gproc"
)

func main () {
   r, err := gproc.ShellExec(`sleep 3s; echo "hello gf!";`)
   fmt.Println("result:", r)
   fmt.Println(err)
}

输出如下：
result: 
<nil>

没有输出命令的执行结果，请问这是什么问题，版本问题？

**Comment by jqb44179** [comment]
你好，请列下gf的版本以及系统相关环境，以便排查问题。
在我这边是能正确输出的，我的环境是：
go version:
go 1.17
gf version:
gf v2.0
os version
mac 10.13.6

**Comment by gqcn** [comment]
@liuchenailq 之前有个版本确实有问题，请试试最新master分支。
