### ISSUE TITLE
gtime.New("Wed, 22 Dec 2021 04:00:12 GMT") 解析错误

### ISSUE THREAD

**Issue by zuozhehao** [gogf/gf#1528]
### 1. What version of `Go` and system type/arch are you using?
`go version go1.17.4 windows/amd64`

### 2. What version of `GoFrame` are you using?
`v1.16.6`

### 3. Can this issue be re-produced with the latest release?

解析错误，输出`0000-01-01 04:00:12 `

**Comment by huangqian1985** [comment]
当前版本暂时不支持解析**"Wed, 22 Dec 2021 04:00:12 GMT"**这种时间格式, 可以看一下文档选择现在支持的时间格式进行格式化处理 https://goframe.org/pages/viewpage.action?pageId=1114883

**Comment by huangqian1985** [comment]
加入自定义格式化可以解决这个问题

gtime.New("Wed, 22 Dec 2021 04:00:12 GMT", "D, d M Y H:i:s T")

输出内容 ： 2021-12-22 04:00:12
