### ISSUE TITLE
往pg写入数组类型的数据会报错

### ISSUE THREAD

**Issue by alaywn** [gogf/gf#1531]
### 1. What version of `Go` and system type/arch are you using?

go version go1.17.5 darwin/amd64

### 2. What version of `GoFrame` are you using?

github.com/gogf/gf/v2 v2.0.0-beta

### 3. Can this issue be re-produced with the latest release?

YES

### 4. What did you do?

// 注：这里没法提供外网可访问的数据库地址
	sql := ` CREATE TABLE test_table ("code" varchar NOT NULL,"path" varchar[]); 
`
	db.Exec(sql)
	var data = g.Map{
		"code": "test",
		"path": []string{"c700a87b-e4d8-4aa1-aa18-38ebe107d0ae", "330cba76-8a69-4321-b783-199c53df64ae"},
	}
	db.Model("tablename").Data(data).Insert(data)

### 5. What did you expect to see?

希望可以支持数组类型的字段值写入pg数据库表中

**Comment by gqcn** [comment]
临时解决方案，使用`gdb.Raw`:
```go
package main

import (
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gctx"
	"github.com/gogf/gf/v2/os/glog"
	_ "github.com/lib/pq"
)

func main() {
	var dbConfig = gdb.ConfigNode{
		Host:  "106.14.167.81",
		Port:  "5432",
		User:  "alaywn",
		Pass:  "Simba#1994",
		Name:  "cronus_ewh",
		Type:  "pgsql",
		Debug: true,
	}

	gdb.SetConfigGroup("MY_TEST", gdb.ConfigGroup{dbConfig})
	db, _ := gdb.New("MY_TEST")
	sql := `DROP TABLE IF EXISTS sys.test_table;`
	if _, err := db.Exec(gctx.New(), sql); err != nil {
		glog.Warning(nil, err)
	}
	sql = ` CREATE TABLE sys.test_table ("code" varchar NOT NULL,"path" varchar[]);`
	if _, err := db.Exec(gctx.New(), sql); err != nil {
		glog.Warning(nil, err)
	}
	var data = g.Map{
		"code": "test",
		"path": gdb.Raw("ARRAY['c700a87b-e4d8-4aa1-aa18-38ebe107d0ae', '330cba76-8a69-4321-b783-199c53df64ae']"),
	}
	if _, err := db.Model("sys.test_table").Insert(data); err != nil {
		glog.Warning(nil, err)
	}
}
```

永久解决方案，为`pgsql_driver`实现自定义自定义的`ConvertDataForRecord`方法，欢迎贡献`PR`，感兴趣的小伙伴可以来联系我，远程给你介绍如何实现。

**Comment by mmyj** [comment]
Let me fix this.
