### ISSUE TITLE
v2 group.* 指定第三参数地址错误

### ISSUE THREAD

**Issue by zuozhehao** [gogf/gf#1533]
### 1. What version of `Go` and system type/arch are you using?

go version go1.17.4 darwin/amd64

### 2. What version of `GoFrame` are you using?

v2.0.0-beta

### 6. What did you see instead?

```go
group.POST("/user", new(api.User), "Edit,Save") // 多个method正常 /user/edit、/user/save
```

单个method
```go
group.POST("/user", new(api.User), "Edit") // 地址是 /user 这边应该是/user/edit 是否规范点
```

### 4. What did you do?

https://github.com/gogf/gf/blob/984e5f98f7c825f038f41b64aac46029f8593859/net/ghttp/ghttp_server_service_object.go#L231

这边最后参数不确定为啥要false，导致`methodName`没拼接

**Comment by starccck** [comment]
I will deal with id later, and it needs to be evaluated what is influenced.

**Comment by starccck** [comment]
I have a try with this issue, and it register correctly. The gf version is `v2.0.0-beta.0.20211214130136-bb1a95fff873`，you'd better try again, or give the code `api.User`.

**Comment by zuozhehao** [comment]
> I have a try with this issue, and it register correctly. The gf version is `v2.0.0-beta.0.20211214130136-bb1a95fff873`，you'd better try again, or give the code `api.User`.

@starccck 

```go
type api struct{}

func (a *api) Index1(r *ghttp.Request) {}
func (a *api) Index2(r *ghttp.Request) {}

func main() {

	s := g.Server()

	s.Group("/", func(group *ghttp.RouterGroup) {

		group.POST("/api1", new(api))
		group.POST("/api2", new(api), "Index1")
		group.POST("/api3", new(api), "Index1, Index2")
	})

	_ = s.Start()
}
```

![image](https://user-images.githubusercontent.com/4464252/147676000-922b4916-e91e-4213-8a0b-54744153d4da.png)

**Comment by gqcn** [comment]
@zuozhehao @starccck 各位，请看下文档 https://goframe.org/pages/viewpage.action?pageId=1114376 两种注册方式本身不一样。此外，使用分组路由注册由于没有结构化传参，所以容易混淆，所以我们从V2版本开始推荐使用规范路由。
