### ISSUE TITLE
gring的bug

### ISSUE THREAD

**Issue by zhongzhaoxue** [gogf/gf#1534]
关于gring的bug：
代码：文档上的例子：
https://goframe.org/pages/viewpage.action?pageId=27756576#id-%E5%B9%B6%E5%8F%91%E5%AE%89%E5%85%A8%E7%8E%AF%E6%96%B9%E6%B3%95%E4%BB%8B%E7%BB%8D-Link
func ExampleRing_Link_Common() {
	r := gring.New(10)
	for i := 0; i < 5; i++ {
		r.Set(i).Next()
	}

	s := gring.New(10)
	for i := 0; i < 10; i++ {
		val := i + 5
		s.Set(val).Next()
	}

	r.Link(s) // Link Ring s to Ring r

	fmt.Println("Len:", r.Len())
	fmt.Println("Cap:", r.Cap())
	fmt.Println(r.SlicePrev())
	fmt.Println(r.SliceNext())

	// Output:
	// Len: 15
	// Cap: 20
	// [4 3 2 1 0]
	// [5 6 7 8 9 10 11 12 13 14]
}

bug现象：
预期link之后，cap为20，实际输出：19

**Comment by huangqian1985** [comment]
论坛里面回答过啦, 你是基于1.16版本跑的sample, 现在的sample都是基于master分支的V2版本写的. 所以输出会有不同
