### ISSUE TITLE
建议glog，添加方法名，参数，可通过配置设置是否需要

### ISSUE THREAD

**Issue by 15951836388** [gogf/gf#154]
rt

**Comment by johngcn** [comment]
@15951836388 请描述详细

**Comment by 15951836388** [comment]
Flags 特性里，可添加 方法名和参数

**Comment by 15951836388** [comment]
![image](https://user-images.githubusercontent.com/14047483/59916613-40fc0c80-9452-11e9-9d7a-06c43cb8b181.png)
 if pc, file, cline, ok := runtime.Caller(i); ok && len(file) > 2 {
           if (goRoot == "" || !gregex.IsMatchString("^" + goRoot, file)) && !gregex.IsMatchString(`<autogenerated>`, file) {
			   f := runtime.FuncForPC(pc)
			   funName:=f.Name()
			   if funName != "runtime.main" && funName != "runtime.goexit" {
			   	lastIdx:=strings.LastIndex(funName,".")+1
			   	fName:=gstr.SubStr(funName,lastIdx,len(funName))
				   backtrace += fmt.Sprintf(`%d. %s:%d (%s)%s`, index, file, cline, fName, ln)
			   }
               index++
           }
       } else {
           break
       }

**Comment by 15951836388** [comment]
if (goRoot == "" || !gregex.IsMatchString("^" + goRoot, file)) && !gregex.IsMatchString(`<autogenerated>`, file) {
			   f := runtime.FuncForPC(pc)
			   funName:=f.Name()
			   lastIdx := strings.LastIndex(funName, ".") + 1
			   fName := gstr.SubStr(funName, lastIdx, len(funName))
			   backtrace += fmt.Sprintf(`%d. %s:%d (%s)%s`, index, file, cline, fName, ln)
			   index++
           }

**Comment by johngcn** [comment]
@15951836388 该feature已开发完成，将会随着下一次大的版本发布，预计本月下旬。

**Comment by johngcn** [comment]
@15951836388 该特性在`v1.8.0`已发布。
