### ISSUE TITLE
database support ssh ？

### ISSUE THREAD

**Issue by adamchenEpm** [gogf/gf#1543]
database . such as mysql 。 if support ssh agent connect ?   for aliyun RDS。thanks

**Comment by starccck** [comment]
[go mysql drive](https://github.com/go-sql-driver/mysql) provided solution, refer to [blog](https://www.zhangshengrong.com/p/O3aA7mEMX4/)

**Comment by adamchenEpm** [comment]
Thank your reply. Is it possible "extend" DriverMssql and gdb.Register()  ?

**Comment by starccck** [comment]
please describe it in detail.

**Comment by starccck** [comment]
I close this issue due to long time inactive, you can new issue or reopen this one if there is any problem. And it is OK to register new Driver.
