### ISSUE TITLE
在ORM的Where中使用gdb.Raw会导致查询失败

### ISSUE THREAD

**Issue by sudden3** [gogf/gf#1553]
### 1. What version of `Go` and system type/arch are you using?

go version go1.17.3 windows/amd64
mysql 5.7

### 2. What version of `GoFrame` are you using?

v2.0.0-beta.0.20211223140028-b79e4a3ab7a9

### 3. Can this issue be re-produced with the latest release?

yes

#### 1:
```go
  _, err = dao.Tokens.Ctx(ctx).Where("expire > ?", gdb.Raw("now()")).Data(g.Map{
	  "expire": gdb.Raw("now()"),
  }).Update()
  panic(err)
```
#### 2:

```go
  _, err = dao.Tokens.Ctx(ctx).Where(g.Map{
	  "expire > ?": gdb.Raw("now()"),
  }).Data(g.Map{
	  "expire": gdb.Raw("now()"),
  }).Update()
  panic(err)
```

### 5. What did you expect to see?

```go
panic(err)
<nil>
```

#### 1:
 ```
Error 1292: Incorrect datetime value: 'now()' for column 'expire' at row 1, UPDATE `tokens` SET `expire`=now() WHERE expire > now()
```
这个SQL语句是没问题的 我复制到mysql中可以成功执行，但是执行前被orm拦截了下来 因为识别到now()不是正确的时间格式?

#### 2.
```
Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?now()' at line 1, UPDATE `tokens` SET `expire`=now() WHERE expire > ?now() 
```
这次查询语句通过了#1中orm的拦截 在mysql中执行了，但是因为多了一个"?"导致执行失败；

在官网文档中搜索gdb.Raw只能看到在Data()中使用的例子, 所以在Where中是否支持使用？如果支持的话那这应该是个BUG。

**Comment by starccck** [comment]
gdb.Raw 目的是根据给定的 prepared SQL 和参数，直接生成 model 对象，func Data() 的目的是为 model 对象设置值。
参考方法注释 [Data](https://github.com/gogf/gf/blob/master/database/gdb/gdb_model_insert.go#L40) 和 [Raw](https://github.com/gogf/gf/blob/master/database/gdb/gdb_model.go#L153)

**Comment by sudden3** [comment]
@starccck 用go取得本地时间再写入到数据库 而不是调用数据库的NOW函数
```go
  dao.Tokens.Ctx(ctx).Where("id", 1).Data(g.map{
    "expire": gtime.Now()
  })
```
如果想更新某字段为当前时间是不是只能这样做，
或者说 这样是最好的做法嘛

**Comment by gqcn** [comment]
@starccck @sudden3 你无法将`now()`作为一个占位符的值传递给底层的`mysql driver`，按照`issue`的意思，建议：
```go
_, err = dao.Tokens.Ctx(ctx).Where("expire > now()").Data("expire=gdb.Raw("now()").Update()
```
