### ISSUE TITLE
[P0]建议v2版本新增Request file的自动注入

### ISSUE THREAD

**Issue by locxiang** [gogf/gf#1556]
### 1. What version of `Go` and system type/arch are you using?

1.16.5

### 2. What version of `GoFrame` are you using?

V2

### 3. Can this issue be re-produced with the latest release?
希望在下个版本中加入文件上传，如下能力：
```
type XxxxxReq struct {
	g.Meta `path:"/upload" mime:"multipart/form-data"  method:"post" tags:"用户" summary:"上传文件"`
	File   *ghttp.UploadFile `form:"file"`
}
```

### 4. What did you do?

目前无法获取到file，只能通过ctx获取
```
	req.File = ghttp.RequestFromCtx(ctx).GetUploadFile("file")

```

**Comment by gqcn** [comment]
可在参数解析映射的时候做个判断即可，先Schedule.
