### ISSUE TITLE
v2 建议增加一个文件流下载

### ISSUE THREAD

**Issue by locxiang** [gogf/gf#1558]
### 1. What version of `Go` and system type/arch are you using?

go 1.16.5, linux/amd64

### 2. What version of `GoFrame` are you using?

v2

### 3. Can this issue be re-produced with the latest release?

建议增加一个文件流下载，目前只有 ServeFile ，ServeFileDownload
需要一个传入文件流的需求

**Comment by gqcn** [comment]
@locxiang 底层实现本来就是流式的，客户端下载需要按照HTTP方式下载，注意HTTP下载大文件是需要分段的。
