### ISSUE TITLE
系统调试功能无法开启

### ISSUE THREAD

**Issue by locxiang** [gogf/gf#1559]
### 1. What version of `Go` and system type/arch are you using?

go 1.16.5, linux/amd64

### 2. What version of `GoFrame` are you using?

v2

### 3. Can this issue be re-produced with the latest release?

在main函数中增加了，开启调试功能无效
```
isDebug, err := g.Config().Get(context.Background(), "server.debug")
	if err != nil {
		panic(err)
	}
	g.SetDebug(isDebug.Bool())

	if err := cmd.Main.Run(ctx); err != nil {
		g.Log().Fatal(ctx, err)
	}
```

### 4. What did you do?

我通过环境变量，和setDebug都无效，logger.level 也设置的all

### 5. What did you expect to see?

我希望看到系统调试信息 INTE

### 6. What did you see instead?

实际上还是没有这个信息，日志也只有debug级别

**Comment by Hamster601** [comment]
https://goframe.org/pages/viewpage.action?pageId=7297419 看这个文档是否解决了你的问题呢？
