### ISSUE TITLE
修改gen-dao生成目录之后，提示  use of internal package xxx not allowed

### ISSUE THREAD

**Issue by flywish** [gogf/gf#1562]
### 1. What version of `Go` and system type/arch are you using?
 Go Version:  go1.17.5

### 2. What version of `GoFrame` are you using?
 GF Version:  v2.0.0-beta

### 3. Can this issue be re-produced with the latest release?
Yes

### 4. What did you do?
step 1: 修改config.yaml 中gen -> dao -> path 到自定义目录
![image](https://user-images.githubusercontent.com/24400037/148721697-a689daf0-e037-402d-bdfb-488d8620d2e1.png)
step 2: 使用自带的gf-cli, 生成对应目录 `gf gen dao`
![image](https://user-images.githubusercontent.com/24400037/148721779-ba4193b7-4b8d-4687-83f1-fb1019361d30.png)
step 3: 按照 [gf-demos](https://github.com/gogf/gf-demos) 项目中的代码, 学习中发现 使用自定义目录后,运行报错. 错误信息为 ` use of internal package apisword/gen/service/internal/dao not allowed`, 网上查询大致意思是 使用了 `internal` 关键字, 会认为是一个go内部的包, 但实际上显然不是.(项目不是在gopath下运行的). 
![image](https://user-images.githubusercontent.com/24400037/148721943-0c897b7c-ab2c-4de1-bca0-104d184c4a24.png)

[备注: 个人刚开始学习go, 还是个小白, 求指教.]

**Comment by starccck** [comment]
多了解下 Golang 的特性，也要从搜索引擎多检索一下。参考资料如下：

- [Go 1.4 Release](https://go.dev/doc/go1.4#internalpackages)
- [https://www.bitlogs.tech](https://www.bitlogs.tech/2019/10/go%E8%AF%AD%E8%A8%80%E5%86%85%E9%83%A8%E5%8C%85internal/)
