### ISSUE TITLE
swagger 增加配置内容

### ISSUE THREAD

**Issue by locxiang** [gogf/gf#1564]
### 1. What version of `Go` and system type/arch are you using?
1.16.5

### 2. What version of `GoFrame` are you using?

v2

### 3. Can this issue be re-produced with the latest release?

需要增加swagger自定义部分比如头部属性

### 4. What did you do?
比如在main函数上加上描述
```golang 
// @title RK Swagger for Echo
// @version 1.0
// @description This is a greeter service with rk-boot.
// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name X-API-Key
func main() {
//......
}

```

否则我无法打开swagger的token设置功能，给前端调试非常难受

**Comment by houseme** [comment]
建议使用2.0版本，可以提PR

**Comment by starccck** [comment]
It seems like you doesn't install latest swag binary, please check from [swag](https://github.com/swaggo/swag)
