### ISSUE TITLE
v2 在结构体内 路由可以多种请求方式吗 

### ISSUE THREAD

**Issue by junsonw** [gogf/gf#1578]
比如 g.Meta `path:"/hello" tags:"Hello" method:"get|post" summary:"You first hello api"`

**Comment by starccck** [comment]
现在还没有这功能，修个 issue 添加功能吧。可以简单描述下为什么 get/post 共用接口嘛？一般方法不同功能不同啊

**Comment by junsonw** [comment]
主要是客户端 两个ios跟安卓请求方式没统一 还有一个问题 如果一个控制器 映射两个路由 是不是没有办法用结构体

**Comment by starccck** [comment]
结构体上不能解析两个路由，只能通过 `server.BindHandler("/your/uri", youtStruct.Method)` 实现了
