### ISSUE TITLE
v2中如何配置swagger的jwt访问

### ISSUE THREAD

**Issue by Macrow** [gogf/gf#1579]
原来的配置遵循swaggo/swag的配置方法，新版v2采用```g.Meta```的方式配置，文档中没发现如何配置jwt认证

**Comment by starccck** [comment]
Support for swagger does not change from before, could you share usage in v1?

**Comment by Macrow** [comment]
https://goframe.org/pages/viewpage.action?pageId=30736904

This is how swagger config in v2.

There is no need config every api method right now, all we need is just update request schema like this
```
type CurrentInfoReq struct {
	g.Meta `path:"/info" tags:"Current" method:"get" summary:"get my info"`
}
```
In this doc, I can't find how to config ```JWT```security config


this code below doesn't work
```
type CurrentInfoReq struct {
	g.Meta `path:"/info" tags:"Current" method:"get" summary:"get my info"`
        Token  string `json:"Authorization" in:"header"`
}
```

**Comment by Macrow** [comment]
I find how to config ```JWT```

```
openapi.Components = goai.Components{
		SecuritySchemes: goai.SecuritySchemes{
			"JWT": goai.SecuritySchemeRef{
				Ref: "",
				Value: &goai.SecurityScheme{
					Type:         "http",
					Scheme:       "bearer",
					BearerFormat: "JWT",
					Description:  "JWT Authentication",
				},
			},
		},
	}
	securityConfig := make(goai.SecurityRequirements, 1)
	configMap := make(map[string][]string)
	configMap["JWT"] = []string{}
	securityConfig[0] = configMap
	openapi.Security = &securityConfig
```

**Comment by starccck** [comment]
good news

**Comment by wisonlau** [comment]
> I find how to config `JWT`
> 
> ```
> openapi.Components = goai.Components{
> 		SecuritySchemes: goai.SecuritySchemes{
> 			"JWT": goai.SecuritySchemeRef{
> 				Ref: "",
> 				Value: &goai.SecurityScheme{
> 					Type:         "http",
> 					Scheme:       "bearer",
> 					BearerFormat: "JWT",
> 					Description:  "JWT Authentication",
> 				},
> 			},
> 		},
> 	}
> 	securityConfig := make(goai.SecurityRequirements, 1)
> 	configMap := make(map[string][]string)
> 	configMap["JWT"] = []string{}
> 	securityConfig[0] = configMap
> 	openapi.Security = &securityConfig
> ```

我按照你这个方法设置没有生效.

```
type HelloReq struct {
	g.Meta `path:"/hello" tags:"Hello" method:"get" summary:"You first hello api"`
}
type HelloRes struct {
	g.Meta `mime:"text/html" example:"string"`
}
```

像这样的api,要怎么样才可以生效
