### ISSUE TITLE
请 orm created_at updated_at 支持 int类型

### ISSUE THREAD

**Issue by CrazyRocks** [gogf/gf#1580]
请 orm created_at updated_at 支持 int类型
我们在实际使用过程中，会用到时区切换，时区切换 int 类型可以直接加减 更加方便

**Comment by gqcn** [comment]
@CrazyRocks 其实你用Golang的话用时间类型更方便和合适一些，其他开发语言由于没有类似时间类型所以常用`int`来存储时间戳。
