### ISSUE TITLE
pg驱动无法加载

### ISSUE THREAD

**Issue by MiltonErickson** [gogf/gf#1585]
### 1. What version of `Go` and system type/arch are you using?

1.17.6 mac

### 2. What version of `GoFrame` are you using?

v2.0.0-rc2

### 3. Can this issue be re-produced with the latest release?

yes

### 4. What did you do?

使用pg数据库

### 5. What did you expect to see?
![image](https://user-images.githubusercontent.com/19679392/150900652-89c4067c-d91e-4e59-83a3-88df359f55c5.png)

**Comment by gqcn** [comment]
@MiltonErickson https://github.com/gogf/gf/tree/master/contrib/drivers

**Comment by MiltonErickson** [comment]
ok
