### ISSUE TITLE
gf的orm查询缓存未对js精度丢失做适配

### ISSUE THREAD

**Issue by redwolf2019** [gogf/gf#1586]
- gf dao生成的ORM结构体
```
type HelloRecord struct {
	Id           int64       `orm:"id"            json:"id"`           //
	UpdatedAt    *gtime.Time `orm:"updated_at"    json:"updatedAt"`    //
	CreatedAt    *gtime.Time `orm:"created_at"    json:"createdAt"`    //
	Code         string      `orm:"code"          json:"code"`         //
}
```
- 使用gf自带的orm缓存查询方式
```
dao.HelloRecord.Cache(time.Second * 30).Where(xxxx)
```

- orm在引入缓存的时候，默认将查询的结果序列化为了json对象，但是在golang in64等大数中，json会有精度丢失问题，请问这个要如何解决呢？不使用json缓存结果，而用其他方式，或着能自动将golang in64转为json string

### 1. What version of `Go` and system type/arch are you using?

- go version go1.17.5 linux/amd64

### 2. What version of `GoFrame` are you using?

- V1.16.6

### 3. Can this issue be re-produced with the latest release?
- YES

**Comment by gqcn** [comment]
@redwolf2019 底层有做相关处理，无法复现所述问题，请提供可运行问题代码。
