### ISSUE TITLE
reflect.Value.Convert: value of type json.Number cannot be converted to type decimal.Decimal

### ISSUE THREAD

**Issue by hinego** [gogf/gf#1590]
`request.Parse(item)`

时有decimal类型，但是提交的参数非字符串（纯数字）类型会报错

有看到这个

https://github.com/gogf/gf/issues/1038

但是现在decimal也没实现这两个接口啊

**Comment by hinego** [comment]
已解决，解决方案：
`
func (d *Decimal) UnmarshalValue(data interface{}) error {
	return d.UnmarshalText([]byte(gconv.String(data)))
}
`

**Comment by iWinston** [comment]
前端使用字符串就可以了
