### ISSUE TITLE
gdb produce a SQL syntax error on UnionAll and Union operator

### ISSUE THREAD

**Issue by litecy** [gogf/gf#1596]
### 1. What version of `Go` and system type/arch are you using?
go version go1.16.5 darwin/amd64

### 2. What version of `GoFrame` are you using?

github.com/gogf/gf/v2 v2.0.0-rc2

### 3. Can this issue be re-produced with the latest release?
yes

### 4. What did you do?

```
	ctx := gctx.New()
	dao.User.Ctx(ctx).UnionAll(
		dao.User.Ctx(ctx).Where(dao.User.Columns().Id, 1),
		dao.User.Ctx(ctx).Where(dao.User.Columns().Id, 1),
		).All()
```

### 5. What did you expect to see?

no SQL syntax error

### 6. What did you see instead?

in the SQL log, a SQL syntax error was printed

<img width="1386" alt="image" src="https://user-images.githubusercontent.com/14884855/152540847-39cacbc7-83ff-427c-8335-f10756068469.png">

**Comment by houseme** [comment]
https://github.com/gogf/gf/issues/1551
