### ISSUE TITLE
使用gogf的数据库ORM的update返回值缺少获取matched、changed、warnings数量的方法！

### ISSUE THREAD

**Issue by windf17** [gogf/gf#1599]
我在使用update更新数据时发现它的返回值是(result sql.Result, err error)，其中err可以获取执行sql语句更新时数据库反馈的报错信息，但result只有LastInsertId和RowsAffected这2个方法，它们的返回值都是(int64,error)。我可以肯定使用这2个方法无法获得update之后matched、changed、warnings的记录数量！

最近遇到一个这样的状况：前端用react后端用gogf开发，前端提交的id不并不存在，后端根据这个id执行update并没有报错！
我根据前端的sql语句在mysql命令行下使用不存在的id执行update会收到如下提示：
Rows matched: 0  Changed: 0  Warnings: 0
说明sql语句执行成功，但匹配到0条记录、更新到0条记录、警告为0条记录。
这种情况应该属于一种异常，我应该给后端反馈“匹配到0条记录，没有成功更新数据！”。目前我只能在update之前执行一下select，以确保要更新的id确实存在！

但我觉得执行update以后应该要拿到matched、changed、warnings，针对这3个数值做一些处理，这样逻辑更严密，可以防止隐性bug。

**Comment by houseme** [comment]
```go
// A Result summarizes an executed SQL command.
type Result interface {
	// LastInsertId returns the integer generated by the database
	// in response to a command. Typically this will be from an
	// "auto increment" column when inserting a new row. Not all
	// databases support this feature, and the syntax of such
	// statements varies.
	LastInsertId() (int64, error)

	// RowsAffected returns the number of rows affected by an
	// update, insert, or delete. Not every database or database
	// driver may support this.
	RowsAffected() (int64, error)
}
```
RowsAffected 返回影响的行数

**Comment by houseme** [comment]
> > 
> 
> 收到提示，谢谢 Thank you for your prompt
> 
> > ```go
> > // A Result summarizes an executed SQL command.
> > type Result interface {
> > 	// LastInsertId returns the integer generated by the database
> > 	// in response to a command. Typically this will be from an
> > 	// "auto increment" column when inserting a new row. Not all
> > 	// databases support this feature, and the syntax of such
> > 	// statements varies.
> > 	LastInsertId() (int64, error)
> > 
> > 	// RowsAffected returns the number of rows affected by an
> > 	// update, insert, or delete. Not every database or database
> > 	// driver may support this.
> > 	RowsAffected() (int64, error)
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > RowsAffected 返回影响的行数
> 
> Thank you for your prompt. I think MySQL give three numbers, I think that it's more exact.

建议给Go官方建议，目前官方只提供了2个接口方法
