### ISSUE TITLE
gf V2.0 rc2 build 交叉编译报错

### ISSUE THREAD

**Issue by doasp** [gogf/gf#1600]
What version of `Go` and system type/arch are you using?

MacOS  Big Sur 11.6.1

`gf -v`                                   
GoFrame CLI Tool v2.0.0-rc2, https://goframe.org 
GoFrame Version: cannot find goframe requirement in go.mod 
CLI Installed At: /usr/local/bin/gf 
CLI Built Detail:
  Go Version:  go1.17.6
  GF Version:  v2.0.0-rc2
  Git Commit:  2022-01-24 16:32:59 f2e7f18d613b1ec6b8eefd48c8ad04974e52da09
  Build Time:  2022-01-24 08:43:01 

**代码是用 `gf init` 创建的空模板项目**

`gf build`
2022-02-11 11:48:09.054 start building... 
2022-02-11 11:48:09.054 go build -o ./bin/linux_amd64/main main.go 
2022-02-11 11:48:10.309 failed to build, os:linux, arch:amd64, error:
runtime/cgo
linux_syscall.c:67:13: error: implicit declaration of function 'setresgid' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
linux_syscall.c:67:13: note: did you mean 'setregid'?
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/unistd.h:593:6: note: 'setregid' declared here
linux_syscall.c:73:13: error: implicit declaration of function 'setresuid' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
linux_syscall.c:73:13: note: did you mean 'setreuid'?
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/unistd.h:595:6: note: 'setreuid' declared here

**Comment by houseme** [comment]
重新安装一下 
Command Line Tools 工具
