### ISSUE TITLE
[bug] gjson int64 convert error

### ISSUE THREAD

**Issue by whoneed** [gogf/gf#1603]
### 1. What version of `Go` and system type/arch are you using?
go version go1.16 linux/amd64

### 2. What version of `GoFrame` are you using?
v1.16.6

### 3. Can this issue be re-produced with the latest release?
yes

### 4. What did you do?
// ==== test code
str := "{\"Id\":1492404095703580672,\"Name\":\"Jason\"}"
strJson := gjson.New(str)
g.Dump(strJson)

// ==== error output
{
	"Id": 1492404095703580700,
	"Name": "Jason"
}

### 5. What did you expect to see?
// ==== expect output
{
	"Id": 1492404095703580672,
	"Name": "Jason"
}

**Comment by gqcn** [comment]
@whoneed 
```go
package main

import (
	"github.com/gogf/gf/v2/encoding/gjson"
	"github.com/gogf/gf/v2/frame/g"
)

func main() {
	str := `{"Id":1492404095703580672,"Name":"Jason"}`
	strJson := gjson.NewWithOptions(str, gjson.Options{
		StrNumber: true,
	})
	g.Dump(strJson)
}
```

**Comment by whoneed** [comment]
Hi, this looks very awesome.
Many thanks.
