### ISSUE TITLE
version:gf1.16.6 关于统一的异常处理    无法进行数据校验的错误类型断言 

### ISSUE THREAD

**Issue by Hllang** [gogf/gf#1604]
```go
package middleware

import (
	"fmt"
	"gfdemo/util"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/net/ghttp"
	"github.com/gogf/gf/util/gvalid"
)

func MiddlewareErrorHandler(r *ghttp.Request) {
	r.Middleware.Next()
	if err := r.GetError(); err != nil {
		g.Log("exception").Error(err)
		r.Response.ClearBuffer()

		**fmt.Printf("%T\n", err) // gerror.Error
		// 我想在这进行数据校验的类型断言，但是无法通过
		if v, ok := err.(gvalid.Error); ok {
			util.ResponseJsonExit(r, 404, v.FirstString(), nil)
		}**

		util.ResponseJsonExit(r, 500, err.Error(), nil)
	}
}
```

**Comment by Hllang** [comment]
package api

import (
	"gfdemo/util"
	"github.com/gogf/gf/net/ghttp"
)

type RegisterReq struct {
	Name  string `p:"username"  v:"required|length:6,30#请输入账号|账号长度为:min到:max位"`
	Pass  string `p:"password1" v:"required|length:6,30#请输入密码|密码长度不够"`
	Pass2 string `p:"password2" v:"required|length:6,30|same:password1#请确认密码|密码长度不够|两次密码不一致"`
}

type RegisterRes struct {
	Code  int         `json:"code"`
	Error string      `json:"error"`
	Data  interface{} `json:"data"`
}

func Login(r *ghttp.Request) {

	var req *RegisterReq
	**if err := r.Parse(&req); err != nil {

		panic(err)
	}**
	util.ResponseJsonExit(r, 200, "success", req)

}

**Comment by Hllang** [comment]
package api

import (
	"gfdemo/util"
	"github.com/gogf/gf/net/ghttp"
)

type RegisterReq struct {
	Name  string `p:"username"  v:"required|length:6,30#请输入账号|账号长度为:min到:max位"`
	Pass  string `p:"password1" v:"required|length:6,30#请输入密码|密码长度不够"`
	Pass2 string `p:"password2" v:"required|length:6,30|same:password1#请确认密码|密码长度不够|两次密码不一致"`
}

type RegisterRes struct {
	Code  int         `json:"code"`
	Error string      `json:"error"`
	Data  interface{} `json:"data"`
}

func Login(r *ghttp.Request) {

	var req *RegisterReq
	**if err := r.Parse(&req); err != nil {

		panic(err)
	}**
	util.ResponseJsonExit(r, 200, "success", req)

}

**Comment by starccck** [comment]
Read document [goframe doc](https://goframe.org/pages/viewpage.action?pageId=3671862), it may be helpful.

**Comment by gqcn** [comment]
@Hllang I see. The caught error is not any more `gvalid.Error` as you throw it using `panic`. The sever considers `error` from `panic` as `exception` not normal `error`. So your `gvalid.Error` is converted to another error.
You can use `r.SetError` set your `err` to current request, and then it can be retrieved by middleware. But this feature will be at next release.
