### ISSUE TITLE
gconv.Scan bug

### ISSUE THREAD

**Issue by s690759602** [gogf/gf#1607]
### 1. What version of `Go` and system type/arch are you using?

go1.17.6 darwin/arm64

### 2. What version of `GoFrame` are you using?
v1.16.6

### 3. Can this issue be re-produced with the latest release?

yes

### 4. What did you do?

```package main

import (
	"fmt"
	"math/big"

	"github.com/gogf/gf/util/gconv"
)

type Float64 float64

type Demo1 struct {
	B Float64
}

func (f *Float64) UnmarshalValue(value interface{}) error {
	if v, ok := value.(*big.Rat); ok {
		f64, _ := v.Float64()
		*f = Float64(f64)
	}
	return nil
}

func main() {
	rat := &big.Rat{}
	rat.SetFloat64(1.5)
	vals := []map[string]interface{}{
		{"A": 1, "B": rat},
	}
	demos := make([]Demo1, 1)
	gconv.Scan(vals, &demos)
	fmt.Println(demos[0])
}
```

### 5. What did you expect to see?

{1.5}

### 6. What did you see instead?

{0}

**Comment by s690759602** [comment]
调试后发现是
![image](https://user-images.githubusercontent.com/32607532/154041396-d62632c2-0b16-48d5-9358-a5ef454da8a8.png)
这一步没有panic strconv.ParseFloat的错误，导致直接返回了0。就没有进行到后面调用UnmarshalValue的那一步

**Comment by s690759602** [comment]
![image](https://user-images.githubusercontent.com/32607532/154041728-3f5344f3-b8f3-4aba-882f-25cc694c9759.png)

**Comment by starccck** [comment]
如 [代码图示](https://github.com/gogf/gf/issues/1607#issuecomment-1040096205) 中的高亮行，函数 `String()` 没有能够准确的完成类型转换
