### ISSUE TITLE
when use postgresql, gf gen dao: ERROR: database initialization failed

### ISSUE THREAD

**Issue by ljd1995** [gogf/gf#1608]
### 1. What version of `Go` and system type/arch are you using?

GoFrame CLI Tool v2.0.0-rc2, https://goframe.org
GoFrame Version: cannot find go.mod
CLI Installed At: D:\Program Files\Multipass\bin\gf.exe
CLI Built Detail:
  Go Version:  go1.17.6
  GF Version:  v2.0.0-rc2
  Git Commit:  2022-01-24 16:32:59 f2e7f18d613b1ec6b8eefd48c8ad04974e52da09
  Build Time:  2022-01-24 08:43:01

### 4. What did you do?

When using MySQL, gen dao is normal. When using postgresql, gen dao reports `ERROR: database initialization failed`. Confirm that the link configuration is correct. The error appears in new version, it works fine in 1.x version gf-cli

**Comment by starccck** [comment]
Is there any postgresql config info in your config file? Or you can provide these config trough command line argument, refer to [goframe gen dao](https://goframe.org/pages/viewpage.action?pageId=3673173)

**Comment by ljd1995** [comment]
I find this error in gf-cli code in here

**Comment by ljd1995** [comment]
I find this error in gf-cli code
![image](https://user-images.githubusercontent.com/17735771/154394597-0cd13b27-896f-4946-8f28-2adf93bb775b.png)
so I do some test
![image](https://user-images.githubusercontent.com/17735771/154394954-3e48167a-9b3b-4df7-8639-8eb3867b32b7.png)
In mysql, it output

[mysql:root:123456@tcp(127.0.0.1:3306)/gf_study mysql root:123456@tcp(127.0.0.1:3306)/gf_study]
3
&{0xc0000e0a80}

In Postgres,it output

[pgsql:user=postgres password=123456 host=127.0.0.1 port=23451 dbname=gf_study sslmode=disable pgsql user=postgres password=123456 host=127.0.0.1 port=23451 dbname=gf_study sslmode=disable]
3
\<nil\>

and then,I try use lib/pq to verify my link config
![image](https://user-images.githubusercontent.com/17735771/154395253-e683369b-2989-41d2-88ef-49e4e21e7644.png)
it output
&{0 {user=postgres password=123456 host=127.0.0.1 port=23451 dbname=cmdb sslmode=disable 0xb67a48} 0 {0 0} [0xc000200000] map[] 0 1 0xc00001c2a0 false map[0xc000200000:map[0xc000200000:true]] map[] 0 0 0 0 <nil> 0 0 0 0 0x7dbe60}

so, maybe the v2 version of gdb has problems with the postgresql connection

**Comment by starccck** [comment]
Has db gf_study been created?

**Comment by gqcn** [comment]
@ljd1995 The `gf` cli might loose import for `pgsql` library, and I see this is fixed in codes. You can manually install `gf` cli current as follows:
```
git clone https://github.com/gogf/gf
cd gf/cmd/gf && go build
./gf install
```
