### ISSUE TITLE
2.0规范路由中，请求参数的校验错误没法用原来r.GetError()中间件捕获

### ISSUE THREAD

**Issue by SSnoWich** [gogf/gf#1626]
##### 2.0规范路由中，请求参数的校验错误没法用原来r.GetError()中间件捕获。

![image](https://user-images.githubusercontent.com/53852923/155503515-0970d8f9-a9b3-4cc8-bc76-a650af4eb26e.png)
![image](https://user-images.githubusercontent.com/53852923/155503535-74bb2417-9f6f-4115-a0d6-b97ce2abd810.png)

- 我在之前版本中用r.GetError()的后置中间件统一处理错误，在2.0中我发现该方法没法捕获到请求参数中的校验错误，其他的自定义错误都没有问题。
- 用r.GetHandlerResponse()方法可以捕获到请求参数中的校验错误，但是捕获不到其他的自定义错误。

**Comment by gqcn** [comment]
@SSnoWich 请给定复现代码。
