### ISSUE TITLE
How to add token verification in swagger UI in gf v2 version 

### ISSUE THREAD

**Issue by ljd1995** [gogf/gf#1635]
### 2. What version of `GoFrame` are you using?

gf v2.0.0-rc3
### 4. What did you do?

Most APIs of the program need to go through the token verification middleware before they can get the interface response data, but the swagger UI does not see the place where the token can be filled in. Can you tell me whether the current version of gf supports the configuration of token verification in swagger? If not, can you provide an idea?

**Comment by gqcn** [comment]
@ljd1995 Yes, the token can be configured in goframe swagger, as it uses standard OpenAPI specification, please refer to https://swagger.io/specification/
