### ISSUE TITLE
建议，为生成的entity的 deleted_at 字段的json tag 加上 omitempty

### ISSUE THREAD

**Issue by sanrentai** [gogf/gf#1639]
建议，为生成的entity的 deleted_at 字段的json tag 加上 omitempty
该字段如果有值，表示已经软删除了，正常情况下查询也没有。

**Comment by YahuiAn** [comment]
想问一下，gf gen dao 支持配置某些字段增加 json - 或者 omitempy 吗？比如 password, phone 这种不想返回给前端，但是又不想再 copy 一份 entity.User 结构体
