### ISSUE TITLE
改进建议，日志组件在打印错误堆栈时最好能把错误产生时的位置打印出来，而不是打印时的调用堆栈

### ISSUE THREAD

**Issue by sanrentai** [gogf/gf#1640]
### 1. What version of `Go` and system type/arch are you using?

go1.17.1 windows/amd64

### 2. What version of `GoFrame` are you using?

v2.0.0-rc2

### 3. Can this issue be re-produced with the latest release?

是

### 4. What did you do?

```
func main() {
	Demo()
}
func Demo() {
	err := Func1()
	if err != nil {
		g.Log().Error(gctx.New(), err)
		fmt.Printf("%+v", err) // 想要的打印方式
	}
}
func Func1() error {
	return Func2()
}
func Func2() error {
	return Func3()
}
func Func3() error {
	return gerror.New("有些错误")
}
```

### 5. What did you expect to see?

2022-03-03 13:47:53.947 [ERRO] {f495315ed3c8d816bddc5f7a9f91544a} 有些错误 
Stack:

 1.  main.Func3
      D:/gopath/go/src/gitee.com/xntk2381/gfv2group/main.go:29
 2.  main.Func2
      D:/gopath/go/src/gitee.com/xntk2381/gfv2group/main.go:26
 3.  main.Func1
      D:/gopath/go/src/gitee.com/xntk2381/gfv2group/main.go:23
 4.  main.Demo
      D:/gopath/go/src/gitee.com/xntk2381/gfv2group/main.go:16
 5.  main.main
      D:/gopath/go/src/gitee.com/xntk2381/gfv2group/main.go:12

### 6. What did you see instead?

2022-03-03 13:47:53.947 [ERRO] {f495315ed3c8d816bddc5f7a9f91544a} 有些错误 
Stack:
1.  main.Demo
    D:/gopath/go/src/gitee.com/xntk2381/gfv2group/main.go:18
2.  main.main
    D:/gopath/go/src/gitee.com/xntk2381/gfv2group/main.go:12

**Comment by gqcn** [comment]
`g.Log().Printf("%+v", err)`

**Comment by sanrentai** [comment]
当 error 发生时打印用 g.Log().Error 这样会定位到错误发生的位置，如果经过分层逻辑以后，可能是在最顶层打印错误，这时候用 g.Log().Error 打印时，错误对账里没有发生时的信息。
