### ISSUE TITLE
something wrong in using sqlite in GoFrame v2.0.0-rc3,  shows forget importing the database driver

### ISSUE THREAD

**Issue by ziyht** [gogf/gf#1642]
### 1. What version of `Go` and system type/arch are you using?
go version go1.17.4 linux/amd64

### 2. What version of `GoFrame` are you using?
v2.0.0-rc3

### 3. Can this issue be re-produced with the latest release?
yes

### 4. What did you do?
using sqlite for local caching

### 5. What did you expect to see?
note: those next test by goframe v2.0.0-rc.0.20220117131058-9345eb5e946f

./test 
2022-03-03 16:34:58.543 [DEBU] [967 ms] [sqlite] [rows:0  ] 
CREATE TABLE if not exists a_alert(
  alert          CHAR(32)   NOT NULL,
  desc           TEXT       NOT NULL,
  threshold      TEXT,
  default_       INT        NOT NULL,
  state          INT        NOT NULL,
  info           TEXT,
  createdAt      timestamp,
  updatedAt      timestamp,
  PRIMARY KEY(alert)
);
         
2022-03-03 16:34:58.556 [DEBU] swagger ui is serving at address: http://127.0.0.1:8000/swagger/ 
2022-03-03 16:34:58.556 [DEBU] openapi specification is serving at address: http://127.0.0.1:8000/api.json 
2022-03-03 16:34:58.557 2408: http server started listening on [:8000] 

### 6. What did you see instead?
./test 
panic: cannot find database driver for specified database type "sqlite", did you misspell type name "sqlite" or forget importing the database driver?

goroutine 1 [running]:
github.com/gogf/gf/v2/frame/gins.Database.func1()
        /home/qos/gopath/pkg/mod/github.com/gogf/gf/v2@v2.0.0-rc3/frame/gins/gins_database.go:168 +0xdf6
github.com/gogf/gf/v2/container/gmap.(*StrAnyMap).doSetWithLockCheck(0xc000557260, {0xc00002a2d0, 0x21}, {0xac0e20, 0xc0000e51c0})
        /home/qos/gopath/pkg/mod/github.com/gogf/gf/v2@v2.0.0-rc3/container/gmap/gmap_hash_str_any_map.go:215 +0x132
github.com/gogf/gf/v2/container/gmap.(*StrAnyMap).GetOrSetFuncLock(0xb83b69, {0xc00002a2d0, 0x21}, 0x2)
        /home/qos/gopath/pkg/mod/github.com/gogf/gf/v2@v2.0.0-rc3/container/gmap/gmap_hash_str_any_map.go:252 +0x5b
github.com/gogf/gf/v2/frame/gins.Database({0xc000557280, 0x1, 0x1})
        /home/qos/gopath/pkg/mod/github.com/gogf/gf/v2@v2.0.0-rc3/frame/gins/gins_database.go:41 +0x1a5
github.com/gogf/gf/v2/frame/g.DB(...)
        /home/qos/gopath/pkg/mod/github.com/gogf/gf/v2@v2.0.0-rc3/frame/g/g_object.go:87
test/internal/service/internal/dao/internal.(*AlertDao).DB(...)
        /home/qos/projects/microscope/test/internal/service/internal/dao/internal/alert.go:55
test/internal/service/internal/dao.(*alertDao).Init(0x0, {0xd04c50, 0xc0000260a8})
        /home/qos/projects/microscope/test/internal/service/internal/dao/alert.go:49 +0x7c
test/internal/service.Init(...)
        /home/qos/projects/microscope/test/internal/service/init.go:9
main.main()
        /home/qos/projects/microscope/test/main.go:15 +0x2e

**Comment by ziyht** [comment]
I upload a example code for this issue
https://github.com/ziyht/gf_bad_example

go.mod
```go
require (
	github.com/gogf/gf/v2 v2.0.0-rc3
	//github.com/gogf/gf/v2 v2.0.0-rc.0.20220117131058-9345eb5e946f
	github.com/mattn/go-sqlite3 v1.14.12
)```

please change the comment line for quick test

**Comment by sanrentai** [comment]
https://github.com/gogf/gf/blob/master/contrib/drivers/README.md

**Comment by gqcn** [comment]
@ziyht As @sanrentai answered.
