### ISSUE TITLE
How to friendly query field of date type in mysql 

### ISSUE THREAD

**Issue by niluan304** [gogf/gf#1643]
How to friendly query field of `date` type in mysql

1. ### ENV

   go version ：go 1.18rc1 windows/amd64

   GoFrame Version: v2.0.0-rc3

   Mysql : 5.7

2. ###  Can this issue be re-produced with the latest release?
  yes

3. ### What did you do?

   I want to query field in Mysql, using the `date`  type ( yyyy-m-d). And gf-cli  generate the entity struct like this:

```go
type Sample struct{
    Date *gtime.time
}
```

I try to do that to get data:

```go
func Get(ctx context.Context, gDate *gtime.Time) (err error) {
    var (
    d = dao.User
    m = d.Ctx(ctx)
    c = d.Columns()
    )

    one, _ := m.Where(c.Date, gDate).One()
    one.IsEmpty() // always true
    ...
}
```

`one` always is empty, because `gDate` will be parsed as `datetime`( yyyy-m-d HH:mm:ss) not `date `type.

If do that, I can get. 

```go
	// convert to yyyy-m-d
	one, _ := m.Where(c.Date, gDate.String()[:10]).One()
```

​    

I check log, the mysql code like this :

```mysql
[default] [rows:0  ] SELECT * FORM table_sample WHERE (`date` = '2006-01-02 15:04:05') LIMIT 1
```

I want 

```mysql
[default] [rows:1  ] SELECT * FORM table_sample WHERE (`date` = '2006-01-02') LIMIT 1
```

​

**Comment by sanrentai** [comment]
I think use `gDate.Format("Y-m-d")` is better than gDate.String()[:10]

**Comment by gqcn** [comment]
> I think use `gDate.Format("Y-m-d")` is better than `gDate.String()[:10]`

@niluan304 Yep, @sanrentai is right.
