### ISSUE TITLE
Bug: gconv.Struct is not working properly，when your structure is labeled like ‘p’

### ISSUE THREAD

**Issue by freanx** [gogf/gf#1646]
GoFrame CLI Tool v2.0.0-rc, https://goframe.org
GoFrame Version: v2.0.0-rc2 in current go.mod
CLI Built Detail:
  Go Version:  go1.17.6
  GF Version:  v2.0.0-beta
  Git Commit:  2022-01-24 11:02:57 37d535f61e975dff1765f98e3b505aeccfec338e
  Build Time:  2022-01-24 03:01:42

The gconv.Struct is not working properly，when  your structure is labeled like ‘p’.
When using API structure (this has not been tried in other scenarios), like this:

```go
  //set Api struct
  type Some struct {
	  g.Meta `path:"/aa" method:"get" summary:"xx" tags:"xx"`
	  Some    string  `json:"some"    p:"s"   description:"xx"`
  }
  
  //set model struct
  type SomeInput struct {
	  Some    string  `json:"some"`
  }
  
  err = gconv.Struct(Some , &SomeInput )
```

There is no error in the conversion, but the field cannot get the value.

**Comment by Hamster601** [comment]
Can you tell us more details?

**Comment by freanx** [comment]
> Can you tell us more details?


还是用中文吧哈哈，这个bug是这样的：
使用gf2工程框架，在api包的struct中 ，某个或者多个属性如果设置了 'p' 这个参数名标签（'p'使用别名），然后使用gconv.Struct 方法 转换结构体数据到model中的结构体，运行结果不会有err报错，但是转换的目标struct中，属性无法获取到原结构体的属性值，所有属性的值都会是空值，即使两个结构体中的属性名和 json标签完全一致。

复现方法，设置两个属性完全相同的结构体A和B，属性可以任意多，其中api包结构体A 的某属性设置 参数名标签 ’p‘，控制器方法内，使用gconv.Struct(A , &B )，发起请求传递数据，打印结果 B的属性都是空值

```go
  //set Api struct

  type A struct {
	g.Meta `path:"/aa" method:"post" summary:"xx" tags:"xx"`
	Some1    string  `json:"some1"    p:"s"   dc:"xx"`
        Some2    string  `json:"some2"             dc:"xx"`
  }
  
  //set model struct

  type B struct {
	Some1    string  `json:"some1"`
        Some2    string  `json:"some2"`
  }

  //set controller 

  func (a *cCon) Test (ctx context.Context, req *apiv1.A) (res *apiv1.As, err error) {
	var in *model.B
	err = gconv.Struct(req , &in)
	if err != nil {
	    g.Log().Error(ctx, err.Error())
	}
	g.Log().Print(ctx,in)
        return 
  }
//最后的打印结果 in 的属性 Some1 和 Some2 是 字符串空值
//如果去掉了 A 中 的'p'标签，运行结果就是正常，in 的属性 Some1 和 Some2 是 请求参数传递值
```

**Comment by gqcn** [comment]
@freanx 请给定完整可复现问题代码。

**Comment by freanx** [comment]
rc2是有这个，使用2.03看了新文档，，这个p标签是没有了，问题关闭
