### ISSUE TITLE
建议：支持工具生成的数据库数据模型中，tinyint（1）的生成为bool类型，或者特定前缀的字段生成为bool（比如is，ex：isSys）

### ISSUE THREAD

**Issue by SSnoWich** [gogf/gf#1648]
建议：支持工具生成的数据库数据模型中，tinyint（1）的生成为bool类型，或者特定前缀的字段生成为bool（比如is，ex：isSys）

**Comment by WesleyWu** [comment]
1、true|false建议用 bit 类型
mysql类型中括号中使用的数字1仅用于宽度显示。INT(1)和TINYINT(1)不会影响存储。
TINYINT占用1字节，这意味着它的范围是-128到+127，所以，并不适合被生成为bool类型。
2、不建议通过字段前缀、后缀来判断生成的类型，这会导致碰巧使用这种前缀、后缀的开发者获得非期待的结果。
比如，gfast原来的生成代码策略是为所有 xxx_status 的字段生成 bool 类型，并且在前端用 element-ui 的 switch 去inline修改这个状态，但我的业务表里恰巧有很多 xxx_status 字段，大部分并非 true|false 类型，所以在最新版的gfast，我把这个处理去掉了。
