### ISSUE TITLE
Duplicated swagger content using redoc

### ISSUE THREAD

**Issue by wapscccs** [gogf/gf#1650]
当我自定义openApi的Description字段时，如果是markdown的话，一级标题和二级标题会渲染两条信息
![截屏2022-03-08 下午9 12 12](https://user-images.githubusercontent.com/40046239/157358637-6aa966b2-e944-466d-9bff-9e09575331c6.png)
![截屏2022-03-08 下午9 12 02](https://user-images.githubusercontent.com/40046239/157358654-d21f8c25-e5c3-45ec-b541-34cfbfdd715e.png)

**Comment by gqcn** [comment]
https://github.com/Redocly/redoc/issues/1925
