### ISSUE TITLE
BUG：使用规范路由后，POST请求Json数据中如果包括null值时报空指针错误

### ISSUE THREAD

**Issue by alaywn** [gogf/gf#1653]
### 1. What version of `Go` and system type/arch are you using?

go version go1.17.8 darwin/amd64

### 2. What version of `GoFrame` are you using?

github.com/gogf/gf/v2 v2.0.3

### 3. Can this issue be re-produced with the latest release?

Yes

### 4. What did you do?

debug后发现问题在于：
文件：gvalid_validator_check_value.go
执行的方法：doCheckValueRecursively
问题所在行：570：**originTypeAndKind := utils.OriginTypeAndKind(item)**
原因分析：对item没有判断是否为nil，导致了空指针错误
重现代码：**在评论区**

### 5. What did you expect to see?

应该加入判空语句

### 6. What did you see instead?

runtime error: invalid memory address or nil pointer dereference

**Comment by alaywn** [comment]
package ghttp_test

import (
	"context"
	"fmt"
	"github.com/gogf/gf/v2/net/ghttp"
	"github.com/gogf/gf/v2/net/gtrace"
	"github.com/gogf/gf/v2/os/gctx"
	"github.com/gogf/gf/v2/os/gtime"
	"github.com/gogf/gf/v2/test/gtest"
	"testing"
	"time"

	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/util/guid"
)

type TestReq struct {
	g.Meta    `path:"/test" method:"post" summary:"执行报表查询" tags:""`
	UUID      string  `json:"uuid" v:"required#菜单唯一码不可为空" dc:""`
	Limit     int     `json:"limit"`
	Filter    []g.Map `json:"filter"`
	FilterMap g.Map   `json:"filter_map"`
}

type TestRes struct {
	UUID     string `json:"uuid"`
	FeedBack string `json:"feed_back"`
}

type cFoo struct{}

var Foo = new(cFoo)

func (r cFoo) PostTest(ctx context.Context, req *TestReq) (*TestRes, error) {
	ctx, span := gtrace.NewSpan(ctx, "Execute")
	defer span.End()
	fmt.Println(req)
	fmt.Println("-----OK-----")
	return &TestRes{UUID: req.UUID, FeedBack: "单元测试：" + gtime.Datetime()}, nil
}

func Test_GF(t *testing.T) {
	s := g.Server(guid.S())
	s.Use(ghttp.MiddlewareHandlerResponse)
	s.Group("/boot", func(grp *ghttp.RouterGroup) {
		grp.Bind(Foo)
	})
	s.SetPort(9527)
	s.Start()
	defer s.Shutdown()
	time.Sleep(1000 * time.Millisecond)
	ctx := gctx.New()
	// g.Client()测试：
	gtest.C(t, func(t *gtest.T) {
		c := g.Client()
		c.SetPrefix(fmt.Sprintf("http://127.0.0.1:%d", s.GetListenedPort()))
		dataReq := `
{"uuid":"28ee701c-7daf-4cdc-9a62-6d6704e6112b","limit":0,"filter":[{"code":"P00001","constraint":"","created_at":"2022-03-08 04:56:15","created_by":"3ed72aba-1622-4262-a61e-83581e020763","default_value":"MonthStart()","expression":"AND A.DLVDAT_0>='%v'","force":false,"frequent":true,"name":"发货日期起","parent":"13109602-0da3-49b9-827f-2f44183ab756","read_only":false,"reference":null,"type":"date","updated_at":"2022-03-08 04:56:15","updated_by":"3ed72aba-1622-4262-a61e-83581e020763","updated_tick":1,"uuid":"e6cd3268-1d75-42e0-83f9-f1f7b29976e8"},{"code":"P00002","constraint":"","created_at":"2022-03-08 04:56:15","created_by":"3ed72aba-1622-4262-a61e-83581e020763","default_value":"MonthEnd()","expression":"AND A.DLVDAT_0<='%v'","force":false,"frequent":true,"name":"发货日期止","parent":"13109602-0da3-49b9-827f-2f44183ab756","read_only":false,"reference":null,"type":"date","updated_at":"2022-03-08 04:56:15","updated_by":"3ed72aba-1622-4262-a61e-83581e020763","updated_tick":1,"uuid":"dba005b5-655e-4ac4-8b22-898aa3ad2294"}],"filter_map":{"P00001":1646064000000,"P00002":1648742399999},"selector_template":""}
`
		c.Post(ctx, "/boot/test", dataReq)
	})

	//Postman测试：（time.Sleep(1000 * time.Minute)时间得放长一点）
	//1.启动服务
	//2.发起POST请求:
	//	地址：http://127.0.0.1:9527/boot/test
	//	参数：
	//{"uuid":"28ee701c-7daf-4cdc-9a62-6d6704e6112b","limit":0,"filter":[{"code":"P00001","constraint":"","created_at":"2022-03-08 04:56:15","created_by":"3ed72aba-1622-4262-a61e-83581e020763","default_value":"MonthStart()","expression":"AND A.DLVDAT_0>='%v'","force":false,"frequent":true,"name":"发货日期起","parent":"13109602-0da3-49b9-827f-2f44183ab756","read_only":false,"reference":null,"type":"date","updated_at":"2022-03-08 04:56:15","updated_by":"3ed72aba-1622-4262-a61e-83581e020763","updated_tick":1,"uuid":"e6cd3268-1d75-42e0-83f9-f1f7b29976e8"},{"code":"P00002","constraint":"","created_at":"2022-03-08 04:56:15","created_by":"3ed72aba-1622-4262-a61e-83581e020763","default_value":"MonthEnd()","expression":"AND A.DLVDAT_0<='%v'","force":false,"frequent":true,"name":"发货日期止","parent":"13109602-0da3-49b9-827f-2f44183ab756","read_only":false,"reference":null,"type":"date","updated_at":"2022-03-08 04:56:15","updated_by":"3ed72aba-1622-4262-a61e-83581e020763","updated_tick":1,"uuid":"dba005b5-655e-4ac4-8b22-898aa3ad2294"}],"filter_map":{"P00001":1646064000000,"P00002":1648742399999},"selector_template":""}
}

**Comment by alaywn** [comment]
func OriginTypeAndKind(value interface{}) (out OriginTypeAndKindOutput) {
// 临时在这里增加了判空解决了
	**_if value==nil{
		return 
	}_**
// -----
	if reflectType, ok := value.(reflect.Type); ok {
		out.InputType = reflectType
	} else {
		if reflectValue, ok := value.(reflect.Value); ok {
			out.InputType = reflectValue.Type()
		} else {
			out.InputType = reflect.TypeOf(value)
		}
	}
	out.InputKind = out.InputType.Kind()
	out.OriginType = out.InputType
	out.OriginKind = out.InputKind
	for out.OriginKind == reflect.Ptr {
		out.OriginType = out.OriginType.Elem()
		out.OriginKind = out.OriginType.Kind()
	}
	return
}

**Comment by alaywn** [comment]
`func OriginTypeAndKind(value interface{}) (out OriginTypeAndKindOutput) {
// 临时在这里增加了判空解决了
if value==nil{
return
}
// -----
if reflectType, ok := value.(reflect.Type); ok {
out.InputType = reflectType
} else {
if reflectValue, ok := value.(reflect.Value); ok {
out.InputType = reflectValue.Type()
} else {
out.InputType = reflect.TypeOf(value)
}
}
out.InputKind = out.InputType.Kind()
out.OriginType = out.InputType
out.OriginKind = out.InputKind
for out.OriginKind == reflect.Ptr {
out.OriginType = out.OriginType.Elem()
out.OriginKind = out.OriginType.Kind()
}
return
}`

**Comment by alaywn** [comment]
func OriginTypeAndKind(value interface{}) (out OriginTypeAndKindOutput) {
// 临时在这里增加了判空解决了
if value==nil{
return
}
// -----
if reflectType, ok := value.(reflect.Type); ok {
out.InputType = reflectType
} else {
if reflectValue, ok := value.(reflect.Value); ok {
out.InputType = reflectValue.Type()
} else {
out.InputType = reflect.TypeOf(value)
}
}
out.InputKind = out.InputType.Kind()
out.OriginType = out.InputType
out.OriginKind = out.InputKind
for out.OriginKind == reflect.Ptr {
out.OriginType = out.OriginType.Elem()
out.OriginKind = out.OriginType.Kind()
}
return
}

**Comment by houseme** [comment]
decimal类型的对象 暂时不支持

**Comment by alaywn** [comment]
> decimal类型的对象 暂时不支持

我想你说的decimal类型应该是时间戳，那是没问题的。这里的问题是，null值不支持导致的报错
