### ISSUE TITLE
规范路由-*Req入参-数据校验：嵌套结构体时疑似校验不生效（有可重现问题的单元测试代码）

### ISSUE THREAD

**Issue by alaywn** [gogf/gf#1662]
### 1. What version of `Go` and system type/arch are you using?
go version go1.17.8 darwin/amd64

### 2. What version of `GoFrame` are you using?
gf 2.0.3

### 3. Can this issue be re-produced with the latest release?

重现代码单独放在了评论区

### 5. What did you expect to see?

希望规范路由入参自动校验对嵌套结构体也生效

**Comment by alaywn** [comment]
package ghttp_test
// 重现代码
import (
	"context"
	"fmt"
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/net/ghttp"
	"github.com/gogf/gf/v2/net/gtrace"
	"github.com/gogf/gf/v2/os/gctx"
	"github.com/gogf/gf/v2/test/gtest"
	"github.com/gogf/gf/v2/util/guid"
	"testing"
	"time"
)

type LbseMasterHead struct {
	Code     string   `json:"code" datatype:"varchar" constraints:"NOT NULL," v:"code@required|min-length:1#The code is required"`
	Active   bool     `json:"active" datatype:"boolean" constraints:","`
	Preset   bool     `json:"preset" datatype:"boolean" constraints:","`
	Superior string   `json:"superior" datatype:"uuid" constraints:","`
	Path     []string `json:"path" datatype:"varchar" constraints:","`
	Sort     int      `json:"sort" datatype:"integer" constraints:","`
	Folder   bool     `json:"folder" datatype:"boolean" constraints:","`
	Test     string   `json:"test" datatype:"boolean" constraints:"," v:"required"`
}

type Template struct {
	LbseMasterHead
	Datasource string `json:"datasource" datatype:"uuid" constraints:"," v:"required|length:32,32#The datasource is required"`
	SQLText    string `json:"sql_text" datatype:"text" constraints:","`
}

type TemplateCreateReq struct {
	g.Meta `path:"/test" method:"post" summary:"Create template" tags:"Template"`
	Master Template `json:"master"`
}

type TemplateCreateRes struct{}

type cFoo1 struct{}

var Foo1 = new(cFoo1)

func (r cFoo1) PostTest1(ctx context.Context, req *TemplateCreateReq) (res *TemplateCreateRes, err error) {
	g.Dump(req)
	ctx, span := gtrace.NewSpan(ctx, "Create")
	defer span.End()
	return
}

func Test_GF1(t *testing.T) {
	s := g.Server(guid.S())
	s.Use(ghttp.MiddlewareHandlerResponse)
	s.Group("/boot", func(grp *ghttp.RouterGroup) {
		grp.Bind(Foo1)
	})
	s.SetPort(8888)
	s.Start()
	defer s.Shutdown()
	time.Sleep(1000 * time.Millisecond)
	ctx := gctx.New()
	// g.Client()测试：
	// code字段传入空字符串时，校验没有提示
	gtest.C(t, func(t *gtest.T) {
		c := g.Client()
		c.SetPrefix(fmt.Sprintf("http://127.0.0.1:%d", s.GetListenedPort()))
		dataReq := `
{"master":{"active":true,"code":"","created_at":"","created_by":"","created_by_text":"","datasource":"38b6f170-a584-43fc-8912-cc1e9bf1b1a9","description":"币种","folder":false,"path":"[\"XCUR\"]","preset":false,"sort":1000,"sql_text":"SELECT!!!!","superior":null,"updated_at":"","updated_by":"","updated_by_text":"","updated_tick":0,"uuid":""},"translation":[{"code":"zh_CN","text":"币种"},{"code":"en_US","text":"币种"}],"filters":null,"fields":[{"code":"F001","created_at":"2022-01-18 23:37:38","created_by":"3ed72aba-1622-4262-a61e-83581e020763","field":"value","hide":false,"min_width":120,"name":"value","parent":"296154bf-b718-4e8f-8b70-efb969b831ec","updated_at":"2022-01-18 23:37:38","updated_by":"3ed72aba-1622-4262-a61e-83581e020763","updated_tick":1,"uuid":"f2140b7a-044c-41c3-b70e-852e6160b21b"},{"code":"F002","created_at":"2022-01-18 23:37:38","created_by":"3ed72aba-1622-4262-a61e-83581e020763","field":"label","hide":false,"min_width":120,"name":"label","parent":"296154bf-b718-4e8f-8b70-efb969b831ec","updated_at":"2022-01-18 23:37:38","updated_by":"3ed72aba-1622-4262-a61e-83581e020763","updated_tick":1,"uuid":"2d3bba5d-308b-4dba-bcac-f093e6556eca"}],"limit":0}
`
		c.Post(ctx, "/boot/test", dataReq)
	})
}

**Comment by gqcn** [comment]
@alaywn 因为在你的代码中顶层的`Master`节点本身没有`required`规则，也就是说
