### ISSUE TITLE
deleted_at is null ，对于mysql不走索引，希望是int类型

### ISSUE THREAD

**Issue by runlabs** [gogf/gf#1663]
### 1. What version of `Go` and system type/arch are you using?

go version go1.17.5 darwin/arm64

### 2. What version of `GoFrame` are you using?

goframe v 1.16

### 4. What did you do?

deleted_at Why can't at be int, is null, and don't use  mysql index

### 5. What did you expect to see?
deleted_at int type default 0

**Comment by WesleyWu** [comment]
即使是datatime/timestamp类型，即使表记录里该字段是null，索引依然会被用到。

之所以你没看到索引被使用，是因为你的查询获取了表里的所有数据，从而使用了全表扫描（因为deleted_at全是null），无需用到索引。

另外：int字段并不会比datetime字段的索引快。

所以，我感觉这个需求并不需要实现，

**Comment by codeyifei** [comment]
@WesleyWu 那unique唯一索引需要怎么解决呢？

**Comment by versionlabs** [comment]
> deleted_at是逻辑删除的标记，会有经常查询表全部数据的业务，举例： 用户表，有10条数据，deleted_at被标记为删除的，有10行，我这时候想知道，当前有效的用户量，我的SQL： select count(id) from t_user where deleted_at is null; 这样会走索引吗？
