### ISSUE TITLE
Why doesn't the latest version support PgSQL driver?

### ISSUE THREAD

**Issue by ft3226848** [gogf/gf#1665]
According to the documentation, it is found that PgSQL cannot be used. After looking at the source code discovery framework, it seems that the built-in driver support has been removed from version 1.8

Do you have to write your own driver to use PgSQL now?

**Comment by gqcn** [comment]
@ft3226848 The `pgsql` driver has never been build-in as part of `goframe`, but it is also supported through community contribution libraries. you'd better look this: https://github.com/gogf/gf/tree/master/contrib/drivers
