### ISSUE TITLE
使用goframe的redis搭配lua脚本实现原子操作？

### ISSUE THREAD

**Issue by FTLLOVE** [gogf/gf#1666]

**Comment by gqcn** [comment]
@FTLLOVE `goframe`的`gredis`组件基于的是第三方的`go-redis`库，通过使用命令行通道的方式保证良好的扩展性和通用性，因此只要是`redis`命令行通道支持的命令，都是支持的。建议自行研究一下，可以帮助完善下`goframe`官方使用文档。

**Comment by FTLLOVE** [comment]
好的
