### ISSUE TITLE
bug：swagger apidoc  Cannot be used outside the local test environment

### ISSUE THREAD

**Issue by Light0821** [gogf/gf#1668]
### 1. What version of `Go` and system type/arch are you using?
go version go1.16.8 darwin/amd64

### 2. What version of `GoFrame` are you using?
github.com/gogf/gf/v2 v2.0.3

### 3. Can this issue be re-produced with the latest release?
yes 

### 4. What did you do?
When forwarding to the back-end service using nginx reverse proxy, the swagger API document cannot be opened. There is a problem with the path of `redoc.standalone.js` file. It should be only uri without domain.
![1646968884230](https://user-images.githubusercontent.com/16831868/157795966-ab3672ae-2136-433b-804f-10276b270863.jpg)

the related code(**net/ghttp/ghttp_server_swagger.go**):
```
// swaggerUI is a build-in hook handler for replace default swagger json URL to local openapi json file path.
// This handler makes sense only if the openapi specification automatic producing configuration is enabled.
func (s *Server) swaggerUI(r *Request) {
	if s.config.OpenApiPath == "" {
		return
	}
	if r.StaticFile != nil && r.StaticFile.File != nil && r.StaticFile.IsDir {
		content := gstr.ReplaceByMap(swaggerUITemplate, map[string]string{
			swaggerUIDocURLPlaceHolder:  s.config.OpenApiPath,
			swaggerUIDocNamePlaceHolder: gstr.TrimRight(r.GetUrl(), "/") + "/" + swaggerUIDocName,
		})
		r.Response.Write(content)
		r.ExitAll()
	}
}
```

**Comment by gqcn** [comment]
@Light0821 Already done, duplicated with https://github.com/gogf/gf/issues/1655
