### ISSUE TITLE
How to use Swagger UI for API testing?

### ISSUE THREAD

**Issue by bluceyee** [gogf/gf#1670]
1. What version of Go and system type/arch are you using?
2. What version of GoFrame are you using?
gf v2.0.3

3. Can this issue be re-produced with the latest release?
4. What did you do?
 Gf v2 版本支持自动生成openapiv3版本的接口文档， 这个功能非常好，但是不像gfv1.x 可以在swagger ui页面直接测试api,  现在的swagger ui界面上貌似只能查看接口，请问需要额外配置什么吗，还是说只能使用第三方的测试工具来测试，比如postman? 
多谢！

6. What did you expect to see?
7. What did you see instead?

**Comment by gqcn** [comment]
@bluceyee The new version `goframe http server` component uses new swagger ui `redoc`, which has very good looking face but it does not support `try out` feature directly on swagger ui page. But we usually do not test API directly on swagger ui page, try using unit testing codes or postman instead, which can also record your API parameters history.

**Comment by LvBay** [comment]
如果能直接在swagger上调试，那将会更好一点
