### ISSUE TITLE
After log rotation, log file name is too long

### ISSUE THREAD

**Issue by shou55** [gogf/gf#1672]
### 1. What version of `Go` and system type/arch are you using?

`go version go1.16.3 linux/amd64`

`CentOS Linux release 7.9.2009 (Core)`
`Linux  3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

### 2. What version of `GoFrame` are you using?

`gf v1.16.6`

### 3. Can this issue be re-produced with the latest release?

not tested

### 4. What did you do?

config.toml
```
[logger]
  Path=                  "./log"
  Level=                 "all"
  Stdout=                false
  RotateExpire=            "2s"
  RotateBackupLimit=     10
  RotateBackupExpire=    "7d"
  RotateCheckInterval=   "5s"
```

main.go
```
func main() {
	for {
		g.Log().Info(grand.Letters(150))
		time.Sleep(3 * time.Second)
	}
}
```

RotateSize works fine
RotateExpire not working properly

### 5. What did you expect to see?

The name of the log file is too long, e.g.
`2022-03-15.20220315133906826583.20220315133911827353.20220315133916833606.20220315133921826619.20220315133926827509.20220315133931837886.20220315133936827193.20220315133941852119.20220315133946827389.20220315133951834830.20220315133956827832.log`

Please shorten the name of the log file

**Comment by wenzi1** [comment]
见 #1844
