### ISSUE TITLE
使用gdb.Instance()创建对象执行sql，logger对象未读取配置信息

### ISSUE THREAD

**Issue by houseme** [gogf/gf#1674]
### 2. What version of `GoFrame` are you using?

v2.0.4
### 4. What did you do?

使用gdb.Instance()创建对象执行sql，logger对象未读取配置信息

### 5. What did you expect to see?

可以正常读取配置，按照配置打印log信息

**Comment by houseme** [comment]
https://github.com/gogf/gf/issues/664

**Comment by gqcn** [comment]
@houseme `gdb.Instance`不会自动读取配置，只是获取一个单例ORM对象。如果想要自动读取配置，可以使用`g.DB`
