### ISSUE TITLE
使用bind和group绑定路由的时候, 后面的group会影响前面绑定的路由(gf萌新不知道我这么写对不对, 求大佬指教😭)

### ISSUE THREAD

**Issue by iosyyy** [gogf/gf#1692]
### 1. What version of `Go` and system type/arch are you using?
go1.12 windows

### 2. What version of `GoFrame` are you using?
v2.0.0-rc2

### 3. Can this issue be re-produced with the latest release?
yes

### 4. What did you do?
```go
s.Group("/", func(group *ghttp.RouterGroup) {
				group.Bind(
					controller.Login,
				)
				group.Group("/api", func(group *ghttp.RouterGroup) {
					group.Bind(
						controller.Hello,
					)
				})
			})
```
在gf 2.0中我使用两个group但是最后通过bind绑定路由后, 前面的s.group就消失了. 
类似于这样
controller.Login绑定了'/login'接口但是会被后续的group影响添加上'/api'

**Comment by zhonghuaxunGM** [comment]
我按照你的代码，复现不出来问题。接口之间并没有收到影响。
```
			s.Group("/", func(group *ghttp.RouterGroup) {
				group.Bind(
					controller.SystemInfo,
				)
				group.Group("/api", func(group *ghttp.RouterGroup) {
					group.Bind(
						controller.GroupInfo,
					)
				})
			})
```
```
  :17799  | DELETE | /api/group/:id    | dp-frame-auth/internal/controller.(*Group).Delete               |
----------|--------|-------------------|-----------------------------------------------------------------|--------------------
  :17799  | GET    | /api/group/:id    | dp-frame-auth/internal/controller.(*Group).Detail               |
----------|--------|-------------------|-----------------------------------------------------------------|--------------------
  :17799  | GET    | /api/group/member | dp-frame-auth/internal/controller.(*Group).Member               |
----------|--------|-------------------|-----------------------------------------------------------------|--------------------
  :17799  | GET    | /api/group/option | dp-frame-auth/internal/controller.(*Group).Option               |
----------|--------|-------------------|-----------------------------------------------------------------|--------------------
  :17799  | GET    | /buildinfo        | dp-frame-auth/internal/controller.(*System).Info                |
----------|--------|-------------------|-----------------------------------------------------------------|--------------------
  :17799  | GET    | /health           | dp-frame-auth/internal/controller.(*System).Health              |
----------|--------|-------------------|-----------------------------------------------------------------|--------------------
```

你能提供一下程序启动时候的路由表吗？

**Comment by iosyyy** [comment]
> 我按照你的代码，复现不出来问题。接口之间并没有收到影响。
> 
> ```
> 			s.Group("/", func(group *ghttp.RouterGroup) {
> 				group.Bind(
> 					controller.SystemInfo,
> 				)
> 				group.Group("/api", func(group *ghttp.RouterGroup) {
> 					group.Bind(
> 						controller.GroupInfo,
> 					)
> 				})
> 			})
> ```
> 
> ```
>   :17799  | DELETE | /api/group/:id    | dp-frame-auth/internal/controller.(*Group).Delete               |
> ----------|--------|-------------------|-----------------------------------------------------------------|--------------------
>   :17799  | GET    | /api/group/:id    | dp-frame-auth/internal/controller.(*Group).Detail               |
> ----------|--------|-------------------|-----------------------------------------------------------------|--------------------
>   :17799  | GET    | /api/group/member | dp-frame-auth/internal/controller.(*Group).Member               |
> ----------|--------|-------------------|-----------------------------------------------------------------|--------------------
>   :17799  | GET    | /api/group/option | dp-frame-auth/internal/controller.(*Group).Option               |
> ----------|--------|-------------------|-----------------------------------------------------------------|--------------------
>   :17799  | GET    | /buildinfo        | dp-frame-auth/internal/controller.(*System).Info                |
> ----------|--------|-------------------|-----------------------------------------------------------------|--------------------
>   :17799  | GET    | /health           | dp-frame-auth/internal/controller.(*System).Health              |
> ----------|--------|-------------------|-----------------------------------------------------------------|--------------------
> ```
> 
> 你能提供一下程序启动时候的路由表吗？
> 
> 你可以关注一下 路由表中的 handler 一列的接口函数名称

https://github.com/iosyyy/testGf 我将项目上传到了git上, 大概是这样的就是个简单的测试项目

项目启动后的路由表如下所示
```

  ADDRESS | METHOD |     ROUTE      |                             HANDLER                             |    MIDDLEWARE
----------|--------|----------------|-----------------------------------------------------------------|--------------------
  :8000   | ALL    | /*             | github.com/gogf/gf/v2/net/ghttp.internalMiddlewareServerTracing | GLOBAL MIDDLEWARE
----------|--------|----------------|-----------------------------------------------------------------|--------------------
  :8000   | ALL    | /*             | awesomeProject12/internal/cmd.MiddlewareCORS                    | GLOBAL MIDDLEWARE
----------|--------|----------------|-----------------------------------------------------------------|--------------------
  :8000   | ALL    | /*             | github.com/gogf/gf/v2/net/ghttp.MiddlewareHandlerResponse       | GLOBAL MIDDLEWARE
----------|--------|----------------|-----------------------------------------------------------------|--------------------
  :8000   | ALL    | /api.json      | github.com/gogf/gf/v2/net/ghttp.(*Server).openapiSpec           |
----------|--------|----------------|-----------------------------------------------------------------|--------------------
  :8000   | ALL    | /api/*any      | awesomeProject12/internal/cmd.LoginMiddleware                   | GLOBAL MIDDLEWARE
----------|--------|----------------|-----------------------------------------------------------------|--------------------
  :8000   | GET    | /api/api/hello | awesomeProject12/internal/controller.(*cHello).Hello            |
----------|--------|----------------|-----------------------------------------------------------------|--------------------
  :8000   | POST   | /api/login     | awesomeProject12/internal/controller.(*cHello).Login            |
----------|--------|----------------|-----------------------------------------------------------------|--------------------
  :8000   | ALL    | /swagger/*     | github.com/gogf/gf/v2/net/ghttp.(*Server).swaggerUI             | HOOK_BEFORE_SERVE
----------|--------|----------------|-----------------------------------------------------------------|--------------------

```

**Comment by zhonghuaxunGM** [comment]
这是来自QQ邮箱的自动回复邮件。
   已收到

**Comment by iosyyy** [comment]
我知道哪里出了问题了..我在绑定的时候cv错了搞到一个类里面了, 抱歉耽误您的时间了
