### ISSUE TITLE
use `gen dao -g default -t xs_test`, you can see some interesting things

### ISSUE THREAD

**Issue by keehao** [gogf/gf#1693]
### 1. What version of `Go` and system type/arch are you using?
go version go1.15.15 darwin/amd64

### 2. What version of `GoFrame` are you using?
gf v1.15.4

### 3. Can this issue be re-produced with the latest release?
yes

### 4. What did you do?
excute `gen dao -g default -t xs_test`
then you see it generate the dao and model has suffix `table` of each files.
```
app/dao/internal/xs_test_table.go
app/dao/xs_test_table.go
app/model/internal/xs_test_table.go
app/model/xs_test_table.go
```

### 5. What did you expect to see?
```
app/dao/internal/xs_test.go
app/dao/xs_test.go
app/model/internal/xs_test.go
app/model/xs_test.go
```

### 6. What did you see instead?
maybe the key of test is very especially, haha ....

**Comment by gqcn** [comment]
@keehao Yes, the `_test.go` is special, very special.
