### ISSUE TITLE
ghttp获取 数字类型 超过一定长度 精度会出现问题

### ISSUE THREAD

**Issue by zhangsan-feng** [gogf/gf#1696]
ghttp 获取数字长度超过int 的11位 大概 大于15位长度的时候回出现这个问题

![image](https://user-images.githubusercontent.com/54844110/159658140-616389ef-1b00-435b-8cf3-b3a626652d16.png)

**Comment by houseme** [comment]
建议把代码贴上来

> ghttp 获取数字长度超过int 的11位 大概 大于15位长度的时候回出现这个问题
> 
> ![image](https://user-images.githubusercontent.com/54844110/159658140-616389ef-1b00-435b-8cf3-b3a626652d16.png)

**Comment by gqcn** [comment]
@zhangsan-feng 你需要提供可复现的代码。根据我对解析代码的了解，新版本不会有这样的问题，比较老的`goframe`版本可能存在。
