### ISSUE TITLE
疑问：service层 调用 model层 为什么不传指针， 或者说看什么场景？

### ISSUE THREAD

**Issue by lucas-sw** [gogf/gf#1698]
如题
<img width="687" alt="WechatIMG129" src="https://user-images.githubusercontent.com/65225672/159830157-0a5e2643-e1fe-4353-a7af-82ee66c47a02.png">

**Comment by starccck** [comment]
这是哪里的代码，麻烦说明一下出处，尽可能给出一些细节

**Comment by houseme** [comment]
> 如题 <img alt="WechatIMG129" width="687" src="https://user-images.githubusercontent.com/65225672/159830157-0a5e2643-e1fe-4353-a7af-82ee66c47a02.png">

如果是V2版本 这个model应该是指针的

**Comment by cn-ygf** [comment]
> 这是哪里的代码，麻烦说明一下出处，尽可能给出一些细节，没太清楚提问的具体出发点。

好像是那个论坛项目
https://github.com/gogf/focus-single
![image](https://user-images.githubusercontent.com/20332876/160975099-969c7772-cfd4-4e33-9c0e-8a0422e8c9fe.png)

**Comment by mingzaily** [comment]
一般是用指针

**Comment by gqcn** [comment]
这个`issue`我暂时不打`tag`，等抽空写篇文章介绍下。不打`tag`的`issue`，下次我都会优先处理。
