### ISSUE TITLE
当新建文件时，必须要判断文件是否存在才能读出内容，否则读取为空

### ISSUE THREAD

**Issue by zhongdalu** [gogf/gf#17]
package main

import (
	"fmt"
	"gitee.com/johng/gf/g"
	"gitee.com/johng/gf/g/os/gfile"
	"gitee.com/johng/gf/g/os/gfsnotify"
	"gitee.com/johng/gf/g/os/glog"
)

func main() {
	// /home/john/temp 是一个目录，当然也可以指定文件
	paths:=g.Config().GetFilePath()
	fmt.Println("=====",paths)
	path := "/ftpDic"
	_, err := gfsnotify.Add(path, func(event *gfsnotify.Event) {
		if event.IsCreate() {
			glog.Println("创建文件 : ", event.Path)
		}
		if event.IsWrite() {
			glog.Println("写入文件 : ", event.Path)
			if gfile.Exists(event.Path) {
				fmt.Printf("%s\n", gfile.GetContents(event.Path))
			}
			//gfile.GetContents()
		}
		if event.IsRemove() {
			glog.Println("删除文件 : ", event.Path)
		}
		if event.IsRename() {
			glog.Println("重命名文件 : ", event.Path)
		}
		if event.IsChmod() {
			glog.Println("修改权限 : ", event.Path)
		}

		glog.Println(event)
	})

	// 移除对该path的监听
	// gfsnotify.Remove(path)

	if err != nil {
		glog.Fatal(err)
	} else {
		select {}
	}
}

**Comment by johng-cn** [comment]
@zhongdalu 
系统版本：MacOS 10.13.5
GO版本：go v1.11.4
GF版本：gf v1.3.8
测试代码如下：
```go
package main

import (
    "fmt"
    "gitee.com/johng/gf/g/os/gfile"
    "gitee.com/johng/gf/g/os/gfsnotify"
    "gitee.com/johng/gf/g/os/glog"
)

func main() {
    path := "/Users/john/Temp"
    _, err := gfsnotify.Add(path, func(event *gfsnotify.Event) {
        if event.IsWrite() {
            glog.Println("写入文件 : ", event.Path)
            fmt.Printf("%s\n", gfile.GetContents(event.Path))
        }
    })
    if err != nil {
        glog.Fatal(err)
    } else {
        select {}
    }
}
```
测试结果：
<img width="820" alt="default" src="https://user-images.githubusercontent.com/26347176/50200401-b9ddb700-0390-11e9-8a1d-a24c93bcdb07.png">

**Comment by johng-cn** [comment]
这块我还需要在`Windows`系统测试下
