### ISSUE TITLE
数据表内两个字段名称相似不规范时会导致查询异常

### ISSUE THREAD

**Issue by AShujiao** [gogf/gf#1700]
gf版本：1.16

例：shop表
字段：id、userid、user_id

1、使用gf-cli生成模型--正常
2、查询数据
![image](https://user-images.githubusercontent.com/14969576/159868821-04ad0d71-c57c-48c5-a7f1-d8ebb49fa3e7.png)

![R}RZ5JQ%V}B`S1)J 51GVKN](https://user-images.githubusercontent.com/14969576/159864902-e8c4bc7e-a6be-47f4-abb2-1ee7998f7441.png)

查看控制台时发现生成的sql为如图所示。

3、尝试指定字段
![image](https://user-images.githubusercontent.com/14969576/159865411-a48bff15-7460-41ca-a568-d225998ddade.png)
![image](https://user-images.githubusercontent.com/14969576/159865661-9bef9ec3-0817-4d0d-91d2-f5cd1e3329ba.png)

经过多次debug发现userid、user_id只会有一个字段有值，无法同时两个字段都有值，要么userid有，要么user_id有。

4、目前解决方法
修改生成的model增加uid字段，查询时使用user_id as uid。
由于业务需要不能改数据表字段，只能改model兼容处理

（涉及敏感信息不方便全部截图，英文太渣可能描述不清楚还是用中文好了）

**Comment by houseme** [comment]
userid、user_id、userId、userID都认为是一个字段。
