### ISSUE TITLE
dao层的Fields方法异常

### ISSUE THREAD

**Issue by otherhan** [gogf/gf#1701]
### 1. What version of `Go` and system type/arch are you using?
go1.15.14 linux/amd64

### 2. What version of `GoFrame` are you using?
1.14.6

### 3. Can this issue be re-produced with the latest release?
I don't know

### 4. What did you do?
dao.TestTable.Fields("if(1=1, 1, null)").All()

### 5. What did you expect to see?
```go
SELECT if(1=1,1,null) FROM `test_table`
```

### 6. What did you see instead?
```go
SELECT if(1=1,null) FROM `test_table`
```

**Comment by houseme** [comment]
建议升级一下新版本

**Comment by otherhan** [comment]
> 建议升级一下新版本

线上项目。。一般就不考虑升级了

**Comment by houseme** [comment]
> > 建议升级一下新版本
> 
> 线上项目。。一般就不考虑升级了

可以考虑小版本升级，可以试试gdb.Raw()

**Comment by gqcn** [comment]
已修复，下一个版本发布
