### ISSUE TITLE
gf命令行工具建立的项目无法运行报错

### ISSUE THREAD

**Issue by jinyuanqing** [gogf/gf#1702]
使用gfv2的cli命令行工具建立了项目,然后使用gf run main.go,就开始报错了
_PS C:\gotest2> gf run main.go
build: main.go 
go build -o ./\main.exe  main.go 
build error: 
go: github.com/gogf/gf/v2@v2.0.0: missing go.sum entry; to add it:
        go mod download github.com/gogf/gf/v2
go: github.com/gogf/gf/v2@v2.0.0: missing go.sum entry; to add it:
        go mod download github.com/gogf/gf/v2
exit status 1
SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'._
![Code_zCsXUEATJk](https://user-images.githubusercontent.com/12565969/160064667-f47f8329-c8e5-4f6c-9e22-13ef56291e8e.png)

**Comment by houseme** [comment]
> 使用gfv2的cli命令行工具建立了项目,然后使用gf run main.go,就开始报错了 _PS C:\gotest2> gf run main.go build: main.go go build -o ./\main.exe main.go build error: go: github.com/gogf/gf/v2@v2.0.0: missing go.sum entry; to add it: go mod download github.com/gogf/gf/v2 go: github.com/gogf/gf/v2@v2.0.0: missing go.sum entry; to add it: go mod download github.com/gogf/gf/v2 exit status 1 SECURITY ERROR This download does NOT match an earlier download recorded in go.sum. The bits may have been replaced on the origin server, or an attacker may have intercepted the download attempt.
> 
> For more information, see 'go help module-auth'._ ![Code_zCsXUEATJk](https://user-images.githubusercontent.com/12565969/160064667-f47f8329-c8e5-4f6c-9e22-13ef56291e8e.png)

先执行 `go mod tidy` 在运行`gf run main.go`

**Comment by gqcn** [comment]
@jinyuanqing 请升级一下`CLI`工具，`v2.0.0`版本发布的时候有点问题，新CLI已经使用了后续版本。你也可以手动升级下使用最新`goframe`版本。
