### ISSUE TITLE
Import sqlite dependency got errors at gf v2.0.4

### ISSUE THREAD

**Issue by bluceyee** [gogf/gf#1705]
### 1. What version of `Go` and system type/arch are you using?
go version go1.17.8 windows/amd64

### 2. What version of `GoFrame` are you using?
v2.0.4

### 3. Can this issue be re-produced with the latest release?
yes

### 4. What did you do?
When i import the sqlite dependency by doc, it's 
_ "github.com/gogf/gf/contrib/drivers/sqlite/v2"

then compile and got below errors
# github.com/gogf/gf/contrib/drivers/sqlite/v2
C:\Users\yililong\go\pkg\mod\github.com\gogf\gf\contrib\drivers\sqlite\v2@v2.0.0-20220319145450-d1f76f3834e1\sqlite.go:109:17: d.DoSelect undefined (type *Driver has no field or method DoSelect)
C:\Users\yililong\go\pkg\mod\github.com\gogf\gf\contrib\drivers\sqlite\v2@v2.0.0-20220319145450-d1f76f3834e1\sqlite.go:144:19: d.DoSelect undefined (type *Driver has no field or method DoSelect)

Compilation finished with exit code 2

that because gf frame changed the fun name in the latest branch

Now, question is, i am using v2.0.4 , and how to import the matched sqlite version.

Thanks.

**Comment by BeanWei** [comment]
try go get -u github.com/gogf/gf/contrib/drivers/sqlite/v2@6ffdff70950eacc74cd91a3a00d8d385018437de

**Comment by bluceyee** [comment]
Yes, it works as you suggestion, tks
At last, I suggest that the contrib libs also should be released as the gf with same version, otherwise we will be confused.
