### ISSUE TITLE
Automatically setting created_at & updated_at to current time does not meet all use cases

### ISSUE THREAD

**Issue by WesleyWu** [gogf/gf#1713]
### 1. What version of `Go` and system type/arch are you using?

go1.17.6 darwin/amd64

### 2. What version of `GoFrame` are you using?

v2.0.4

### 3. Can this issue be re-produced with the latest release?
yes

### 4. What did you do?

I found GF would automatically set created_at & updated_at to current time (now) which is great for most use cases.
But sometimes I need to manually set created_at & updated_at value, usually a time before now.

Also in some use cases, updated_at should not be set when the record to be inserted is a new record, which means there is no updating at all.

I explain the use case as  below:
I need to synchronize some third party data like purchase order into my database. The third party order record has a created_at (obviously before current time) and empty updated_at.

I want to copy the original order creating record in my database. After I copied the original data record (with created_at = 2021-10-02 13:13:13, updated_at = nil) into my Order entity and did insert, I found the created_at and updated_at column were automatically set to current time.

Really frustrating.

The workaround is not using created_at & updated_at column to save the original record. Instead I have to use original_created_at & original_updated_at to make sure the original create/update time can be preserved.

I thinks it will be better to introduce a db config option like "handle_created_updated_automaticallly = true|false". When set to false, GF will not overwrite the created_at & updated_at value (even a nil updated_at) which were already set by developer.

Thanks in advance.

**Comment by gqcn** [comment]
@WesleyWu Thanks for your advise. There're two options to configure `ORM` component of `GoFrame` not update `create_at/update_at` fields automatically: https://goframe.org/pages/viewpage.action?pageId=1114139
1. Use `Unscoped` function.
2. Use `TimeMaintainDisabled` configuration.
