### ISSUE TITLE
 Error connecting to mssql database

### ISSUE THREAD

**Issue by wilsonliu123** [gogf/gf#1719]
### 1. What version of `Go` and system type/arch are you using?

go version go1.18 darwin/arm64

### 2. What version of `GoFrame` are you using?

V2.0.4 

### 4. What did you do?

g.DB().Model ("xxx")

### 5. What did you expect to see?
return query record

### 6. What did you see instead?

# github.com/gogf/gf/contrib/drivers/mssql/v2
../../go/pkg/mod/github.com/gogf/gf/contrib/drivers/mssql/v2@v2.0.0-20220319145450-d1f76f3834e1/mssql.go:226:18: d.DoSelect undefined (type *Driver has no field or method DoSelect)
../../go/pkg/mod/github.com/gogf/gf/contrib/drivers/mssql/v2@v2.0.0-20220319145450-d1f76f3834e1/mssql.go:292:20: d.DoSelect undefined (type *Driver has no field or method DoSelect)

**Comment by BeanWei** [comment]
Related [#1705](https://github.com/gogf/gf/issues/1705#issuecomment-1078975607)

**Comment by wilsonliu123** [comment]
Someone suggested this version, and it worked.
require (
	
	github.com/gogf/gf/contrib/drivers/mssql/v2 v2.0.0-20220314113956-2eec1bc61acf
	
)
