### ISSUE TITLE
安全疑虑  r.Response.WriteTplContent(`{{dump .}}`, viewData) 与 {{.}}

### ISSUE THREAD

**Issue by Omiga3721** [gogf/gf#1720]
r.Response.WriteTplContent(`{{dump .}}`, viewData)  的结果竟然把config都打印出来了, 数据库信息都暴露到前台,岂不是有些数据安全问题? 调试的时候不小心用一下dump .  忘记删除的话... 

个人建议还是把模板  {{.}} 里面的config配置信息屏蔽掉

<img width="794" alt="WX20220329-002753@2x" src="https://user-images.githubusercontent.com/24944112/160444137-9215a997-98a0-451c-8d29-ff125f64236d.png">

**Comment by gqcn** [comment]
@Omiga3721 已改进。`dump`方法仅在`develop`模式下启用。
