### ISSUE TITLE
gf build编译时的pack参数生成的data.go所在目录是/packed

### ISSUE THREAD

**Issue by sudden3** [gogf/gf#1721]
### 1. What version of `Go` and system type/arch are you using?

`go version go1.17.3 windows/amd64`

### 2. What version of `GoFrame` are you using?

```
GoFrame CLI Tool v2.0.4, https://goframe.org
GoFrame Version: cannot find go.mod
CLI Installed At: C:\Users\ifhov\go\bin\gf.exe
CLI Built Detail:
  Go Version:  go1.17.7
  GF Version:  v2.0.4
  Git Commit:  2022-03-14 19:39:56 2eec1bc61acff958c3abe465c6c63b8d44bce126
  Build Time:  2022-03-14 19:38:57
```
通过`gf build main.go --pack manifest/config`命令编译后，**项目根目录**中多出一个**packed**文件夹，新版本goframe的packed目录应该是在internal目录(main.go中引用的是 internal/packed)，所以根目录的packed目录/包没有被引用，导致init方法没有执行, 运行编译后的文件端口是默认的80 也验证了data.go没有被编译进去

**Comment by XiaobinZhao** [comment]
gf 工具使用配置文件进行build也不生效。配置文件如下：
```
[gfcli]
    [build]
        name=      "my-goframe"
        arch=      "all"
        system=    "all"
        mod=       "none"
        cgo=       0
        pack=      "config,i18n,public,template"
        version=   ""
        output=    "./bin"
        extra=     ""
```
直接执行gf build， 不会自动引用config的配置项

**Comment by sudden3** [comment]
@XiaobinZhao 我没有遇到过这个问题 正常读取gf的配置文件
