### ISSUE TITLE
json to struct 失败

### ISSUE THREAD

**Issue by 59duncom** [gogf/gf#173]
type Wafrules struct{
	name  string `json:"Name"`
	description string `json:"Description"`
	code int `json:"Code"`
	matchheader int `json:"Matchheader"` //匹配类型
	matchstringvalue string  `json:"Matchstringvalue"`
	nextrule *Wafrules  `json:"Nextrule"`
	morefunc bool  `json:"Morefunc"`  //是为and 否为or
	action int `json:"Action"`
	off bool `json:"Off"`
	matchcount int64 `json:"Matchcount"`
}

func  Newjsonwaf( jsonstring string)*Wafrules {
	if j, err := gjson.DecodeToJson([]byte(jsonstring)); err != nil {
		glog.Error(err)
		return nil
	} else {
		o:=&Wafrules{}
		j.ToStruct(o)
		return o
	}

}

 data:=  `{
         "Name":"test",
        "Description":"匹配url包含首页",
        "Code": 2,
       "Matchheader":6,
      "Matchstringvalue":"/",
     "Action":4,
     "Off":false
    }`

  s:=   waf.Newjsonwaf(data )
  fmt.Println(s)

**Comment by johngcn** [comment]
因为你的struct属性都是私有的，没有公开的属性是不能被其他模块引用的，也就无法赋值
