### ISSUE TITLE
v2.0.4 的 gcron 表达式会执行多次

### ISSUE THREAD

**Issue by arden** [gogf/gf#1734]
cron 好像有些问题  0 */50 9-18 * * * 这种表达式，会在整点及每隔50分钟都会执行1次，但是同样的cron表达式在 gf 1.x 版本里确实只会隔50分钟才会执行1次。

**Comment by DGuang21** [comment]
> cron 好像有些问题 0 */50 9-18 * * * 这种表达式，会在整点及每隔50分钟都会执行1次，但是同样的cron表达式在 gf 1.x 版本里确实只会隔50分钟才会执行1次。

cron 表达式可使用https://tool.lu/crontab进行校验，此处可以使用 ```@every 50m```进行实现

**Comment by gqcn** [comment]
> 

是的，按照你的`Cron`表达式，确实是：9-18点整点第50分执行一次。
至于`v1.x`你说的情况，可能是`BUG`，这些组件都是不断在迭代维护的。
