### ISSUE TITLE
希望gdb增加commit hook

### ISSUE THREAD

**Issue by qinyuguang** [gogf/gf#1736]
gf v2.0.6新增了crud的hook，希望增加commit hook

因为很多时候是一个DB事务中的某个逻辑会使用hook，最终事务提交时执行（子事务的commit不应执行）

@gqcn

**Comment by gqcn** [comment]
@qinyuguang 我建议可以提供`Commit`的`HOOK`，这样可能更有价值一些，而不是单独给`TX`加个`HOOK`功能。
