### ISSUE TITLE
HTTPClient SetHeader not work with PostForm

### ISSUE THREAD

**Issue by shou55** [gogf/gf#1739]
### 1. What version of `Go` and system type/arch are you using?

`go version go1.16.3 linux/amd64`

`CentOS Linux release 7.9.2009 (Core)`
`Linux  3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

### 2. What version of `GoFrame` are you using?

`gf v1.16.6`

### 3. Can this issue be re-produced with the latest release?

not tested

### 4. What did you do?

main.go(client)
```
func main() {
	c := g.Client()
	c.SetHeader("User-Agent", "test agent")
	data := url.Values{}
	data.Set("name", "zhangsan")
	c.PostForm("http://127.0.0.1:12345", data)
}
```

server, use linux nc command
```
nc -k -l 12345
```

### 5. What did you expect to see?

when use c.PostForm , c.SetHeader  not work ,  but c.Get or c.Post   works well

**Comment by shou55** [comment]
![image](https://user-images.githubusercontent.com/18003903/162164080-fd675ec3-5e5c-4a3a-a5bb-4c937cf12c61.png)

**Comment by houseme** [comment]
> ### 1. What version of `Go` and system type/arch are you using?
> `go version go1.16.3 linux/amd64`
> 
> `CentOS Linux release 7.9.2009 (Core)` `Linux 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
> 
> ### 2. What version of `GoFrame` are you using?
> `gf v1.16.6`
> 
> ### 3. Can this issue be re-produced with the latest release?
> not tested
> 
> ### 4. What did you do?
> main.go(client)
> 
> ```
> func main() {
> 	c := g.Client()
> 	c.SetHeader("User-Agent", "test agent")
> 	data := url.Values{}
> 	data.Set("name", "zhangsan")
> 	c.PostForm("http://127.0.0.1:12345", data)
> }
> ```
> 
> server, use linux nc command
> 
> ```
> nc -k -l 12345
> ```
> 
> ### 5. What did you expect to see?
> when use c.PostForm , c.SetHeader not work , but c.Get or c.Post works well

```go
func main() {
	c := g.Client().SetHeader("User-Agent", "test agent")
	data := url.Values{}
	data.Set("name", "zhangsan")
	c.PostForm("http://127.0.0.1:12345", data)
}

```

**Comment by gqcn** [comment]
@shou55 It cannot be reproduced in latest version of `goframe`. Besides, the `PostForm` function is deprecated from `v2` of goframe.
