### ISSUE TITLE
garray中的search方法不能正确返回位置值

### ISSUE THREAD

**Issue by jroam** [gogf/gf#174]
1.环境
go1.12
windows
gf 的master最近代码

问题样例:
```
a2 := []int{1}
array2 := garray.NewSortedIntArrayFrom(a2)
gtest.Assert(array2.Search(2),-1)
```
search查找值是否存在于数组中，如果没有存在就返回 -1, 但却返回了0.

**Comment by johngcn** [comment]
嗯，这个Search的返回结果没有处理，直接返回了内部的二分查找结果，这样不行有问题，我需要改一下
