### ISSUE TITLE
无法使用gf gen dao 生成mssql相关文件

### ISSUE THREAD

**Issue by exment** [gogf/gf#1741]
当使用gf工具链接mssql生成dao的时候报错:
gfcli版本 ^2.0
当使用1.0版本的cli工具时能正常生成
exception recovered: runtime error: invalid memory address or nil pointer dereference
1. exception recovered: runtime error: invalid memory address or nil pointer dereference
   1).  github.com/gogf/gf/v2/os/gcmd.(*Command).doRun.func1
        /home/runner/work/gf/gf/os/gcmd/gcmd_command_run.go:97
   2).  github.com/gogf/gf/cmd/gf/v2/internal/cmd.generateColumnDefinitionForDao
        /home/runner/work/gf/gf/cmd/gf/internal/cmd/cmd_gen_dao.go:682
   3).  github.com/gogf/gf/cmd/gf/v2/internal/cmd.generateDaoInternal
        /home/runner/work/gf/gf/cmd/gf/internal/cmd/cmd_gen_dao.go:502
   4).  github.com/gogf/gf/cmd/gf/v2/internal/cmd.generateDao
        /home/runner/work/gf/gf/cmd/gf/internal/cmd/cmd_gen_dao.go:328
   5).  github.com/gogf/gf/cmd/gf/v2/internal/cmd.doGenDaoForArray
        /home/runner/work/gf/gf/cmd/gf/internal/cmd/cmd_gen_dao.go:270
   6).  github.com/gogf/gf/cmd/gf/v2/internal/cmd.cGen.Dao
        /home/runner/work/gf/gf/cmd/gf/internal/cmd/cmd_gen_dao.go:171
   7).  github.com/gogf/gf/v2/os/gcmd.newCommandFromMethod.func1
        /home/runner/work/gf/gf/os/gcmd/gcmd_command_object.go:306
   8).  github.com/gogf/gf/v2/os/gcmd.(*Command).doRun
        /home/runner/work/gf/gf/os/gcmd/gcmd_command_run.go:120
   9).  github.com/gogf/gf/v2/os/gcmd.(*Command).RunWithValueError
        /home/runner/work/gf/gf/os/gcmd/gcmd_command_run.go:77
   10). github.com/gogf/gf/v2/os/gcmd.(*Command).RunWithValue
        /home/runner/work/gf/gf/os/gcmd/gcmd_command_run.go:32
   11). github.com/gogf/gf/v2/os/gcmd.(*Command).Run
        /home/runner/work/gf/gf/os/gcmd/gcmd_command_run.go:26
   12). main.main
        /home/runner/work/gf/gf/cmd/gf/main.go:69

**Comment by pzheng** [comment]
您好，你的邮件我已收到！
