### ISSUE TITLE
希望可以提供gf各种标签的使用情况总结

### ISSUE THREAD

**Issue by dyzsoft** [gogf/gf#1744]
### 6. What did you see instead?

**希望可以提供gf各种标签的使用情况总结**

**Comment by hailaz** [comment]
[可能还需要补充](https://goframe.org/pages/viewpage.action?pageId=7296348#FAQ%EF%BC%88%E7%A4%BE%E5%8C%BA%E5%85%B1%E5%BB%BA%EF%BC%89-4%E3%80%81GoFrame%E7%9A%84structtag%E6%9C%89%E5%93%AA%E4%BA%9B%EF%BC%9F)
