### ISSUE TITLE
文件上传报错

### ISSUE THREAD

**Issue by wuruipeng404** [gogf/gf#1746]
![image](https://user-images.githubusercontent.com/34570968/162712006-f0a833e8-1ef1-4b8f-abb4-27247d588d60.png)

**Comment by gqcn** [comment]
@wuruipeng404 标题党，敢把服务端报错截图出来吗？或者可复现的代码贴出来？

**Comment by wuruipeng404** [comment]
> @wuruipeng404 标题党，敢把服务端报错截图出来吗？服务端有报错都会打印详细的堆栈的，甚至可以精确到报错的行号。

你自己打个demo试一下啊。。。问题是没有报错啊。。服务器日志都正常， 客户端获取不到response

**Comment by wuruipeng404** [comment]
> @wuruipeng404 标题党，敢把服务端报错截图出来吗？服务端有报错都会打印详细的堆栈的，甚至可以精确到报错的行号。

而且我这还真不是标题党。 我接手的项目 用的1.14.6版本，我一路网上换版本试，每个版本都有这个bug

**Comment by wuruipeng404** [comment]
> > @wuruipeng404 标题党，敢把服务端报错截图出来吗？服务端有报错都会打印详细的堆栈的，甚至可以精确到报错的行号。
> 
> 你自己打个demo试一下啊。。。问题是没有报错啊。。服务器日志都正常， 客户端获取不到response

而且我觉得您试 最好试1.x版本。因为就算您2.x解决了我也不太可能升级。成本太大了。

**Comment by wuruipeng404** [comment]
> @wuruipeng404 标题党，敢把服务端报错截图出来吗？服务端有报错都会打印详细的堆栈的，甚至可以精确到报错的行号。

再给您一个详细特征吧。 所有 form-data上传文件的接口， 只要文件超过3M， 在中间件退出，客户端就永远无法获取任何response.
![image](https://user-images.githubusercontent.com/34570968/162725748-74df4c42-d6ee-482d-94e2-493dc5ad48b6.png)

**Comment by houseme** [comment]
> > @wuruipeng404 标题党，敢把服务端报错截图出来吗？服务端有报错都会打印详细的堆栈的，甚至可以精确到报错的行号。
> 
> 再给您一个详细特征吧。 所有 form-data上传文件的接口， 只要文件超过3M， 在中间件退出，客户端就永远无法获取任何response. ![image](https://user-images.githubusercontent.com/34570968/162725748-74df4c42-d6ee-482d-94e2-493dc5ad48b6.png)

默认是8M大小的

**Comment by wuruipeng404** [comment]
> > > @wuruipeng404 标题党，敢把服务端报错截图出来吗？服务端有报错都会打印详细的堆栈的，甚至可以精确到报错的行号。
> > 
> > 
> > 再给您一个详细特征吧。 所有 form-data上传文件的接口， 只要文件超过3M， 在中间件退出，客户端就永远无法获取任何response. ![image](https://user-images.githubusercontent.com/34570968/162725748-74df4c42-d6ee-482d-94e2-493dc5ad48b6.png)
> 
> 默认是8M大小的

![image](https://user-images.githubusercontent.com/34570968/162728561-5ff9b62b-7a43-4c94-a9a8-3a67d0ea0850.png)
我设置过了 没有用。

**Comment by houseme** [comment]
> > > > @wuruipeng404 标题党，敢把服务端报错截图出来吗？服务端有报错都会打印详细的堆栈的，甚至可以精确到报错的行号。
> > > 
> > > 
> > > 再给您一个详细特征吧。 所有 form-data上传文件的接口， 只要文件超过3M， 在中间件退出，客户端就永远无法获取任何response. ![image](https://user-images.githubusercontent.com/34570968/162725748-74df4c42-d6ee-482d-94e2-493dc5ad48b6.png)
> > 
> > 
> > 默认是8M大小的
> 
> ![image](https://user-images.githubusercontent.com/34570968/162728561-5ff9b62b-7a43-4c94-a9a8-3a67d0ea0850.png) 我设置过了 没有用。

`r.Response.ClearBuffer()` 后面还少一个`r.Middleware.Next()` 代码

**Comment by houseme** [comment]
你这个中间件的代码有问题吧。清理缓冲输出，直接就401错误了吧

**Comment by wuruipeng404** [comment]
> > > > > @wuruipeng404 标题党，敢把服务端报错截图出来吗？服务端有报错都会打印详细的堆栈的，甚至可以精确到报错的行号。
> > > > 
> > > > 
> > > > 再给您一个详细特征吧。 所有 form-data上传文件的接口， 只要文件超过3M， 在中间件退出，客户端就永远无法获取任何response. ![image](https://user-images.githubusercontent.com/34570968/162725748-74df4c42-d6ee-482d-94e2-493dc5ad48b6.png)
> > > 
> > > 
> > > 默认是8M大小的
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/34570968/162728561-5ff9b62b-7a43-4c94-a9a8-3a67d0ea0850.png) 我设置过了 没有用。
> 
> `r.Response.ClearBuffer()` 后面还少一个`r.Middleware.Next()` 代码

同样的 我试过了， 如果您能自己试一下就更好了。 我截图只是截的你们2.0文档下面 有人提的和我同样的问题

**Comment by wuruipeng404** [comment]
> 你这个中间件的代码有问题吧。清理缓冲输出，直接就401错误了吧

不清理也是一样的结果， 问题的本质就是 form-data 上传超过 3M的文件 ，只要在中间件里， 调用任何 r.Response.xxxExit(),方法，客户端就收不到任何响应， 而服务端一切正常。 还是那句话 您自己尝试一下就好了。 至少我从1.14.6 一路换到 1.16.7 都是有这个问题。看了你们的文档评论 2.0应该依旧有这个问题

**Comment by houseme** [comment]
建议多看看文档：https://goframe.org/pages/viewpage.action?pageId=17203785

**Comment by wuruipeng404** [comment]
> > ```go
> > package main
> > 
> > import (
> > 	"fmt"
> > 
> > 	"github.com/gogf/gf/frame/g"
> > 	"github.com/gogf/gf/net/ghttp"
> > )
> > 
> > func MiddlewareAuth(r *ghttp.Request) {
> > 	r.Middleware.Next()
> > 	fmt.Println("body: ", r.Response.BufferString())
> > 	r.Response.ClearBuffer()
> > 	r.Response.WriteStatusExit(401, "dddddXXXX")
> > }
> > 
> > func main() {
> > 	s := g.Server()
> > 
> > 	s.Group("/api", func(group *ghttp.RouterGroup) {
> > 		group.Middleware(MiddlewareAuth)
> > 		group.GET("/", func(r *ghttp.Request) {
> > 			r.Response.Write("GET: /api")
> > 		})
> > 		group.POST("/", func(r *ghttp.Request) {
> > 			files := r.GetUploadFiles("upload-file")
> > 			names, err := files.Save("./tmp/")
> > 			if err != nil {
> > 				r.Response.WriteExit(err)
> > 			}
> > 			r.Response.WriteExit("upload successfully: ", names)
> > 			r.Response.Write("POST: /api")
> > 		})
> > 	})
> > 	s.Run()
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > go.mod
> > ```go
> > module demo
> > 
> > require github.com/gogf/gf v1.16.7
> > 
> > go 1.14
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @wuruipeng404 你运行一下吧,这个代码是可以正常处理上传的。
> 
> ![image](https://user-images.githubusercontent.com/34570968/162861032-c59369b1-ea7a-41cc-bc53-19f82155f691.png) 您这个代码不符合正常逻辑吧。 我不管做什么校验， 我的预处理逻辑 肯定是在 next 之前啊，为什么要放在next 之后呢？

**Comment by houseme** [comment]
那把next放到后面，这个可以调整的，既然已经exit，后面的处理都停止了，你去看看`r.Response.WriteStatusExit()`源码

**Comment by wuruipeng404** [comment]
> > > 那把next放到后面，这个可以调整的，既然已经exit，后面的处理都停止了，你去看看`r.Response.WriteStatusExit()`源码
> > 
> > 
> > 对呀问题是放到后面，客户端获取不到响应，这个 您不觉得是bug？ 只要我不传文件， 响应就出来了，一传超过3m的文件 客户端就没有任何响应，这不是bug？，您如果觉得不是bug 那您就close吧。 感觉我好像再说什么也没啥用。。
> 
> 理解了，v2.0、v1.16.7版本都是没问题的。
> 
> ```go
> func MiddlewareAuth(r *ghttp.Request) {
> 	fmt.Println("body: ", r.Response.BufferString())
> 	r.Response.ClearBuffer()
> 	r.Response.WriteStatusExit(401, "dddddXXXX")
> 	r.Middleware.Next()
> }
> ```
> 
> <img alt="image" width="716" src="https://user-images.githubusercontent.com/4829346/162876004-4ea5cf6a-1c0c-45e1-a73c-248a49d596c4.png">
> 
> <img alt="image" width="686" src="https://user-images.githubusercontent.com/4829346/162876156-fa05a574-9492-4e31-b6fa-5270041d48dc.png">

这就有点奇怪了。。
![image](https://user-images.githubusercontent.com/34570968/162886982-85636bb6-eb48-4d11-abf1-981480dd20f6.png)
我升级到 1.16.7 也还是一样的。。

**Comment by wuruipeng404** [comment]
> > > 那把next放到后面，这个可以调整的，既然已经exit，后面的处理都停止了，你去看看`r.Response.WriteStatusExit()`源码
> > 
> > 
> > 对呀问题是放到后面，客户端获取不到响应，这个 您不觉得是bug？ 只要我不传文件， 响应就出来了，一传超过3m的文件 客户端就没有任何响应，这不是bug？，您如果觉得不是bug 那您就close吧。 感觉我好像再说什么也没啥用。。
> 
> 理解了，v2.0、v1.16.7版本都是没问题的。
> 
> ```go
> func MiddlewareAuth(r *ghttp.Request) {
> 	fmt.Println("body: ", r.Response.BufferString())
> 	r.Response.ClearBuffer()
> 	r.Response.WriteStatusExit(401, "dddddXXXX")
> 	r.Middleware.Next()
> }
> ```
> 
> <img alt="image" width="716" src="https://user-images.githubusercontent.com/4829346/162876004-4ea5cf6a-1c0c-45e1-a73c-248a49d596c4.png">
> 
> <img alt="image" width="686" src="https://user-images.githubusercontent.com/4829346/162876156-fa05a574-9492-4e31-b6fa-5270041d48dc.png">

我发现个现象 
![image](https://user-images.githubusercontent.com/34570968/162889263-6971aa49-7f50-4770-8bac-b3ee2c452956.png)
如果在中间件里 通过 把文件获取出来，响应就可以正常获取了。 这肯定是有些问题的把。。。

**Comment by houseme** [comment]
应该研究一下http了。

**Comment by wuruipeng404** [comment]
> 应该研究一下http了。

好吧 ，祝好~
