### ISSUE TITLE
注册clickhouse驱动后，问号（？）占位解析异常

### ISSUE THREAD

**Issue by alaywn** [gogf/gf#1751]
### 1. What version of `Go` and system type/arch are you using?
go 1.18

### 2. What version of `GoFrame` are you using?
gf 2.0.6

### 3. Can this issue be re-produced with the latest release?

YES

### 4. What did you do?

驱动代码详见2楼

**Comment by alaywn** [comment]
package clickhouse

import (
	"database/sql"
	"fmt"
	_ "github.com/ClickHouse/clickhouse-go/v2"
	"github.com/gogf/gf/v2/container/gmap"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/errors/gcode"
	"github.com/gogf/gf/v2/errors/gerror"
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/text/gregex"
	"github.com/gogf/gf/v2/text/gstr"
	"strings"
)

const (
	driverName           = "clickhouse"
	underlyingDriverName = "clickhouse"
)

var (
	tableFieldsMap = gmap.New(true)
)

type Driver struct {
	*gdb.Core
}

func init() {
	if err := gdb.Register(driverName, New()); err != nil {
		panic(err)
	}
}

func New() gdb.Driver {
	return &Driver{}
}

func (rcv *Driver) New(core *gdb.Core, node *gdb.ConfigNode) (gdb.DB, error) {
	return &Driver{
		Core: core,
	}, nil
}

func (rcv *Driver) Open(config *gdb.ConfigNode) (db *sql.DB, err error) {
	var (
		source string
	)
	if config.Link != "" {
		source = config.Link
	} else {
		if config.Pass != "" {
			source = fmt.Sprintf("clickhouse://%s:%s@%s:%s/%s",
				config.User, config.Pass, config.Host, config.Port, config.Name)
		} else {
			source = fmt.Sprintf("clickhouse://%s@%s:%s/%s",
				config.User, config.Host, config.Port, config.Name)
		}
		source += fmt.Sprintf("?charset=%s&debug=%t&compress=%t",
			config.Charset, config.Debug, true,
		)
	}
	if db, err = sql.Open(underlyingDriverName, source); err != nil {
		err = gerror.WrapCodef(
			gcode.CodeDbOperationError, err,
			`sql.Open failed for driver "%s" by source "%s"`,
			underlyingDriverName, source,
		)
		return nil, err
	}
	return
}

func (rcv *Driver) GetChars() (charLeft string, charRight string) {
	return "\"", "\""
}

func (rcv *Driver) Tables(ctx g.Ctx, schema ...string) (tables []string, err error) {
	var result gdb.Result
	link, err := rcv.SlaveLink(schema...)
	if err != nil {
		return nil, err
	}
	query := fmt.Sprintf("SELECT name FROM `system`.tables WHERE database = '%s'", rcv.GetConfig().Name)
	result, err = rcv.DoSelect(ctx, link, query)
	if err != nil {
		return
	}
	for _, m := range result {
		for _, v := range m {
			tables = append(tables, v.String())
		}
	}
	return
}

func (rcv *Driver) TableFields(ctx g.Ctx, table string, schema ...string) (fields map[string]*gdb.TableField, err error) {
	charL, charR := rcv.GetChars()
	table = gstr.Trim(table, charL+charR)
	if gstr.Contains(table, " ") {
		return nil, gerror.NewCode(gcode.CodeInvalidParameter, "function TableFields supports only single table operations")
	}
	//useSchema := rcv.GetSchema()
	//if len(schema) > 0 && schema[0] != "" {
	//	useSchema = schema[0]
	//}
	v := tableFieldsMap.GetOrSetFuncLock(
		fmt.Sprintf(`table_fields_%s_%s@group:%s`, table, "useSchema", rcv.GetGroup()),
		func() interface{} {
			var (
				result       gdb.Result
				link         gdb.Link
				structureSql = fmt.Sprintf("SELECT name,position,default_expression,comment from `system`.`columns` WHERE `database` = '%s' and `table` = '%s'", rcv.GetConfig().Name, table)
			)
			//if link, err = rcv.SlaveLink(useSchema); err != nil {
			//	return nil
			//}
			structureSql, _ = gregex.ReplaceString(`[\n\r\s]+`, " ", gstr.Trim(structureSql))
			result, err = rcv.DoSelect(ctx, link, structureSql)
			if err != nil {
				return nil
			}
			fields = make(map[string]*gdb.TableField)
			for i, m := range result {
				fields[strings.ToLower(m["name"].String())] = &gdb.TableField{
					Index: i,
					Name:  strings.ToLower(m["name"].String()),
					Type:  strings.ToLower(m["type"].String()),
				}
			}
			return fields
		},
	)
	if v != nil {
		fields = v.(map[string]*gdb.TableField)
	}
	return
}

func (rcv *Driver) FilteredLink() string {
	linkInfo := rcv.GetConfig().Link
	if linkInfo == "" {
		return ""
	}
	s, _ := gregex.ReplaceString(
		`(.+?):(.+)@tcp(.+)`,
		`$1:xxx@tcp$3`,
		linkInfo,
	)
	return s
}

func (rcv *Driver) DoInsert(ctx g.Ctx, link gdb.Link, table string, list gdb.List, option gdb.DoInsertOption) (result sql.Result, err error) {
	switch option.InsertOption {
	case gdb.InsertOptionSave:
		return nil, gerror.NewCode(gcode.CodeNotSupported, `Save operation is not supported by mssql driver`)
	case gdb.InsertOptionReplace:
		return nil, gerror.NewCode(gcode.CodeNotSupported, `Replace operation is not supported by mssql driver`)
	}
	var (
		keys   []string
		values []string
		params []interface{}
	)
	var (
		listLength  = len(list)
		valueHolder = make([]string, 0)
	)
	for k := range list[0] {
		keys = append(keys, k)
		valueHolder = append(valueHolder, "?")
	}
	var (
		batchResult    = new(gdb.SqlResult)
		charL, charR   = rcv.GetChars()
		keyStr         = charL + strings.Join(keys, charL+","+charR) + charR
		valueHolderStr = strings.Join(valueHolder, ",")
	)
	intoStr := make([]string, 0)
	for i := 0; i < len(list); i++ {
		for _, k := range keys {
			params = append(params, list[i][k])
		}
		values = append(values, valueHolderStr)
		intoStr = append(intoStr, fmt.Sprintf("INTO %s(%s) VALUES(%s)", table, keyStr, valueHolderStr))
		if len(intoStr) == option.BatchCount || (i == listLength-1 && len(valueHolder) > 0) {
			r, err := rcv.DoExec(ctx, link, fmt.Sprintf(
				"INSERT ALL %s SELECT * FROM DUAL",
				strings.Join(intoStr, " "),
			), params...)
			if err != nil {
				return r, err
			}
			if n, err := r.RowsAffected(); err != nil {
				return r, err
			} else {
				batchResult.Result = r
				batchResult.Affected += n
			}
			params = params[:0]
			intoStr = intoStr[:0]
		}
	}
	return batchResult, nil
}

**Comment by alaywn** [comment]
要复现问题，需要本地安装clickhouse，执行如下代码就能看到问题：
1.DB.Model("system.databases").Where("name", "cronus").One()
2.DB.GetAll(ctx, "select * from system.databases where name = ?", "default")
可以正常执行的代码：
DB.GetAll(ctx, "select * from system.databases where name = 'default'")

**Comment by DGuang21** [comment]
原因是v2 占位符不支持问号，需要使用类似于 pgsql 一样的 $1 $2 $3 
已经将 clickhouse-go 升级到 v2，https://github.com/gogf/gf/pull/1762
