### ISSUE TITLE
问题：下载clickhouse驱动提示版本异常

### ISSUE THREAD

**Issue by alaywn** [gogf/gf#1754]
### 1. What version of `Go` and system type/arch are you using?

go 1.18
### 2. What version of `GoFrame` are you using?

gf 2.0.6

### 3. Can this issue be re-produced with the latest release?

go get -u -v github.com/gogf/gf/contrib/drivers/clickhouse/v2
go: github.com/gogf/gf/contrib/drivers/clickhouse/v2@v2.0.0-20220412133644-5144cc0e082d requires
        github.com/gogf/gf/v2@v2.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000

**Comment by DGuang21** [comment]
fix https://github.com/gogf/gf/pull/1762
