### ISSUE TITLE
Is this a bug？？？

### ISSUE THREAD

**Issue by fc221** [gogf/gf#1758]
### 1. What version of `Go` and system type/arch are you using?

`go version go1.16.14 windows/amd64`

### 2. What version of `GoFrame` are you using?

```
GoFrame CLI Tool v2.0.6, https://goframe.org
GoFrame Version: v2.0.4 in current go.mod
CLI Installed At: C:\Program Files\Go\bin\gf2.exe
CLI Built Detail:
  Go Version:  go1.17.7
  GF Version:  v2.0.6
  Git Commit:  2022-03-31 16:57:32 66803fd6641e31c60f0489180668243ea092b87b
  Build Time:  2022-03-31 16:55:38
```
### 3. Can this issue be re-produced with the latest release?
能

### 4. What did you do?

```
db := dao.User.Ctx(ctx).Clone()
db.Where("username", "")
```

### 5. What did you expect to see?
![DON83JN2 L%R Z4H39393UH](https://user-images.githubusercontent.com/24759664/163148697-8437fd66-07f0-4732-b0f3-66bf21dbb005.png)

### 6. What did you see instead?

![SE}JUS@{VKZ1 @X~D)TE{97](https://user-images.githubusercontent.com/24759664/163149375-addabae6-555f-473f-9198-44b85ca4ea24.png)

**Comment by fc221** [comment]
@houseme 
![image](https://user-images.githubusercontent.com/24759664/163167669-84cecee2-f530-4b13-95b2-78a8eb67691c.png)
不行

**Comment by houseme** [comment]
赋值之后，还需要有变量接着，这样才可以，你截图里的where前面需要
`db = db.where("id = ?",1)`
`result := db.Scan(&a)`

**Comment by fc221** [comment]
@houseme 这我知道 我看文中中说 Clone() 可以不需要重新赋值
![image](https://user-images.githubusercontent.com/24759664/163178817-f04bbf12-3f8e-4f20-b806-fa431981e031.png)

**Comment by houseme** [comment]
你看下Where方法的代码
```go
func (m *Model) Where(where interface{}, args ...interface{}) *Model {
	return m.doWhereType(``, where, args...)
}

func (m *Model) doWhereType(t string, where interface{}, args ...interface{}) *Model {
	model := m.getModel()
	if model.whereHolder == nil {
		model.whereHolder = make([]ModelWhereHolder, 0)
	}
	if t == "" {
		if len(args) == 0 {
			t = whereHolderTypeNoArgs
		} else {
			t = whereHolderTypeDefault
		}
	}
	model.whereHolder = append(model.whereHolder, ModelWhereHolder{
		Type:     t,
		Operator: whereHolderOperatorWhere,
		Where:    where,
		Args:     args,
	})
	return model
}


```

**Comment by fc221** [comment]
@houseme 所以文档中的Clone和dao中的Clone并不一致？

**Comment by houseme** [comment]
> @houseme 所以文档中的Clone和dao中的Clone并不一致？

碰到异常情况，可以看看源码

**Comment by fc221** [comment]
@houseme 多谢 我之前一直在质疑这个
