### ISSUE TITLE
sql查询结果不能解析json字符串

### ISSUE THREAD

**Issue by wangtufly** [gogf/gf#1760]
### 1. What version of `Go` and system type/arch are you using?
 macos 11.2   go 1.16

### 2. What version of `GoFrame` are you using?
1.16.6

```
//ProdInfo 产品信息
	ProdInfo struct {
		Pics             string      `json:"pics" v:"required"`
		ServiceInfo      *gjson.Json `json:"service_info" d:"-"` //[{"spid":1,"service_type":"1","name":"普通洗车","nums":"1"}]
		Ext              string      `json:"ext" d:"-"`
	}

//ProdList 请求产品列表
func ProdList(ctx context.Context, req *ProdListReq) (*ProdListRes, error) {
	output := &ProdListRes{}
	prodWhere := g.Map{}
	result, err := dao.SpProduct.Ctx(ctx).Where(prodWhere).Limit(req.PageSize).
		Offset((req.Page - 1) * req.PageSize).
		OrderDesc(columns.UpdatedAt).
		All()
	if err != nil {
		return output, gerror.NewCode(code.ActSearchError)
	}
	if !result.IsEmpty() {
		prodList := ([]*ProdInfoRes)(nil)
		err := gconv.Scan(result, &prodList)
		if err != nil {
			return output, gerror.NewCode(code.ActInvalidParam, "查询结果非正确格式")
		}
		output.List = prodList
	}
	return output, nil
}
```

返回
```
{
    "code": 0,
    "msg": "",
    "message": "",
    "data": {
        "list": [
            {
                "pics": "12",
                "service_info": null,
                "ext": "",
            }
        ]
    }
}
```
数据库结构
![image](https://user-images.githubusercontent.com/44032147/163315849-5a2a3c57-886d-4778-9e98-5912283d963c.png)

就是解析不了[{},{}]这样的json，只能解析{},这个问题要怎么处理，是代码的问题还是？

**Comment by danvinhe** [comment]
me to! [1,2]这种一维数组也不行，查询出来是n

**Comment by danvinhe** [comment]
@wangtufly 底层最终按map解析的，所以转换失败。尝试在util/gconv/gconv.go直接支持*gjson.Json，会有循环导入的问题，无解。不过可以定义结构体的反序列化方法来解决改问题。
```
type User struct {
	Id         int
	Passport   string
	Password   *gjson.Json
	Nickname   *gjson.Json
	CreateTime *gtime.Time
}

func (user *User) UnmarshalValue(value interface{}) error {
	if record, ok := value.(gdb.Record); ok {
		*user = User{
			Id:         record["id"].Int(),
			Passport:   record["passport"].String(),
			Password:   gjson.New(record["passwor"].String()),
			Nickname:   gjson.New(record["nickname"].String()),
			CreateTime: record["create_time"].GTime(),
		}
		return nil
	}
	return gerror.NewCodef(gcode.CodeInvalidParameter, `unsupported value type for UnmarshalValue: %v`, reflect.TypeOf(value))
}

```

**Comment by wangtufly** [comment]
> @wangtufly 底层最终按map解析的，所以转换失败。尝试在util/gconv/gconv.go直接支持*gjson.Json，会有循环导入的问题，无解。不过可以定义结构体的反序列化方法来解决改问题。
> 
> ```
> type User struct {
> 	Id         int
> 	Passport   string
> 	Password   *gjson.Json
> 	Nickname   *gjson.Json
> 	CreateTime *gtime.Time
> }
> 
> func (user *User) UnmarshalValue(value interface{}) error {
> 	if record, ok := value.(gdb.Record); ok {
> 		*user = User{
> 			Id:         record["id"].Int(),
> 			Passport:   record["passport"].String(),
> 			Password:   gjson.New(record["passwor"].String()),
> 			Nickname:   gjson.New(record["nickname"].String()),
> 			CreateTime: record["create_time"].GTime(),
> 		}
> 		return nil
> 	}
> 	return gerror.NewCodef(gcode.CodeInvalidParameter, `unsupported value type for UnmarshalValue: %v`, reflect.TypeOf(value))
> }
> ```

**Comment by wangtufly** [comment]
@danvinhe  thanks，按照你的方法尝试一下看看
