### ISSUE TITLE
mssql: 对象名 'SYSOBJECTS' 无效   大小写问题

### ISSUE THREAD

**Issue by zhangyong0129** [gogf/gf#1761]
fetching tables failed: mssql: 对象名 'SYSOBJECTS' 无效。, SELECT NAME FROM SYSOBJECTS WHERE XTYPE='U' AND STATUS >= 0 ORDER BY NAME

mssql: 对象名 'SYSOBJECTS' 无效。, SELECT NAME FROM SYSOBJECTS WHERE XTYPE='U' AND STATUS >= 0 ORDER BY NAME
```
1). github.com/gogf/gf/v2/database/gdb.(*Core).DoCommit
/home/runner/work/gf/gf/database/gdb/gdb_core_underlying.go:253
2). github.com/gogf/gf/v2/database/gdb.(*Core).DoQuery
/home/runner/work/gf/gf/database/gdb/gdb_core_underlying.go:62
/home/runner/work/gf/gf/os/gcmd/gcmd_command_run.go:77
12). github.com/gogf/gf/v2/os/gcmd.(*Command).RunWithValue
/home/runner/work/gf/gf/os/gcmd/gcmd_command_run.go:32
13). github.com/gogf/gf/v2/os/gcmd.(*Command).Run
/home/runner/work/gf/gf/os/gcmd/gcmd_command_run.go:26
14). main.main
/home/runner/work/gf/gf/cmd/gf/main.go:69
15). runtime.main
/opt/hostedtoolcache/go/1.17.7/x64/src/runtime/proc.go:255
16). runtime.goexit
/opt/hostedtoolcache/go/1.17.7/x64/src/runtime/asm_amd64.s:1581
```

```
GoFrame CLI Tool v2.0.4, https://goframe.org/
GoFrame Version: v2.0.5-0.20220329123100-707dc6b34624 in current go.mod
CLI Installed At: E:\GoWorkSpace\bin\gf.exe
CLI Built Detail:
Go Version: go1.17.7
GF Version: v2.0.4
Git Commit: 2022-03-14 19:39:56 https://github.com/gogf/gf/commit/2eec1bc61acff958c3abe465c6c63b8d44bce126
Build Time: 2022-03-14 19:38:57
```

大写查不到，小写可以查到。如何处理

**Comment by gqcn** [comment]
似乎是查询数据库的数据表列表的时候SQL有点问题？https://github.com/gogf/gf/blob/583d576cdba6c46049f23f2caf36714054d30cc4/contrib/drivers/mssql/mssql.go#L223

有没朋友来协助看看？

**Comment by wenzi1** [comment]
@zhangyong0129 mssql是什么版本的

SELECT NAME FROM SYSOBJECTS WHERE XTYPE='U' AND STATUS >= 0 ORDER BY NAME
这个语句放到mssql里执行会报错吗？ 怎么感觉和你的mssql版本有关系或者和你登录用户的权限有关系。

我是在2012版上测试的

**Comment by zhangyong0129** [comment]
> @zhangyong0129 mssql是什么版本的
> 
> SELECT NAME FROM SYSOBJECTS WHERE XTYPE='U' AND STATUS >= 0 ORDER BY NAME 这个语句放到mssql里执行会报错吗？ 怎么感觉和你的mssql版本有关系或者和你登录用户的权限有关系。
> 
> 我是在2012版上测试的

2017正式版

**Comment by wenzi1** [comment]
mssql登录方式？ 用什么用户登录的？ 查询时指定的db是什么？
