### ISSUE TITLE
gtime哪里用的不对？

### ISSUE THREAD

**Issue by iAsuma** [gogf/gf#1763]
![image](https://user-images.githubusercontent.com/33219490/163515966-77c64a9d-b57c-45f8-b3d6-5c6554ee1993.png)

![image](https://user-images.githubusercontent.com/33219490/163515991-7dc898f1-3883-4c7a-8361-d74e64f689ee.png)

![image](https://user-images.githubusercontent.com/33219490/163516069-a7f689f3-f9ca-4dcc-b69d-671a0c34ff58.png)

### 1. What version of `Go` and system type/arch are you using?
go version go1.17.9 windows/amd64

### 2. What version of `GoFrame` are you using?
v2.0.6

**Comment by zjfsdnu** [comment]
time使用请到qq群里提问或者自行百度
