### ISSUE TITLE
session强制缓存到内存的问题

### ISSUE THREAD

**Issue by zhoxife3ng** [gogf/gf#1781]
最近新上服务时发现服务内存使用过多，所以开启了pprof定位，最后定位到是使用了session的问题，从源码可以看到，每次请求结束关闭session时都会把当前session刷进内存且在内存存活的时间与session stroge一致，这样就会导致session的数据会存在两份，一份在远端存储，一份为本地内存。当请求用户基数较大时程序会占用非常大的内存且很久都无法释放
https://github.com/gogf/gf/blob/be77779affcc6b58d9841001c128956aeac750bc/os/gsession/gsession_session.go#L106

我理解这样设计的原因是当远端session存储不可用时，可以有内存session进行兜底。
但我觉得至少也需要有方法可以限制session使用的内存，遗憾的是目前并没有发现有提供这样的方法
https://github.com/gogf/gf/blob/be77779affcc6b58d9841001c128956aeac750bc/os/gsession/gsession_manager.go#L33

希望可以在实例化`SessionManager`的时候设置`sessionData`的`lruCap`大小；或者提供可选项，由开发者选择是否使用本地内存缓存session

**Comment by codeyifei** [comment]
是否替换过session的驱动呢

**Comment by gqcn** [comment]
@zhoxife3ng @codeyifei 大家好！是的，如果使用`KeyValue`类型的`StorageRedis` `Adapter`，为了保障效率降低对`Redis`服务的操作频率，在内存中是有一份`Session`记录。优点是`Session`操作效率特别高，缺点是会额外占用一份`Session`内存。
如果想要避免这样的情况，可以使用`StorageRedisHashTable`，这种`Adapter`所有的操作直接通过`Redis`操作实现，在内存中没有记录。优点是对内存占用小，缺点是会所有`Session`操作都是直接操作`Redis`。

**Comment by zhoxife3ng** [comment]
> @zhoxife3ng @codeyifei 大家好！
> 
> 是的，如果使用`KeyValue`类型的`StorageRedis`，为了保障效率降低对`Redis`服务的操作频率，在内存中是有一份`Session`记录。优点是`Session`操作效率特别高，缺点是会额外占用一份`Session`内存。考虑是用户`Session`是常驻且频繁操作类数据，一般容量不应当很大，如果太大可能是`Session`设计不合理导致。（假设一个在线用户`10KB Session`数据，**10万在线**用户约`100000*10KB~=1GB`）。
> 
> 如果想要避免这样的情况，可以使用`StorageRedisHashTable`，这种`Storage`所有的操作直接通过`Redis`操作实现，在内存中没有记录。优点是对内存占用小，缺点是所有`Session`操作都是直接操作`Redis`。
> 
> 具体的，大家可以看看源码实现对比下。此外，如果觉得不满意，也可以自实现`Session Storage`。`GoFrame`框架的核心组件均采用了接口化设计，提供了非常强大的可扩展性。

@gqcn 我从源码上并没有看到会提高`Session`查询的效率哦，而只是提供了兜底操作，当远程存储不可用时可以降级使用本地session，另外`StorageRedisHashTable`这种方式的确可以绕过内存session，但无法兼容我们的业务系统，这就很蛋疼了
https://github.com/gogf/gf/blob/be77779affcc6b58d9841001c128956aeac750bc/os/gsession/gsession_session.go#L38
![image](https://user-images.githubusercontent.com/13849457/165251261-373986c8-e73a-4d37-b164-771f6e9316f3.png)

**Comment by gqcn** [comment]
> > @zhoxife3ng @codeyifei 大家好！
> > 是的，如果使用`KeyValue`类型的`StorageRedis`，为了保障效率降低对`Redis`服务的操作频率，在内存中是有一份`Session`记录。优点是`Session`操作效率特别高，缺点是会额外占用一份`Session`内存。考虑是用户`Session`是常驻且频繁操作类数据，一般容量不应当很大，如果太大可能是`Session`设计不合理导致。（假设一个在线用户`10KB Session`数据，**10万在线**用户约`100000*10KB~=1GB`）。
> > 如果想要避免这样的情况，可以使用`StorageRedisHashTable`，这种`Storage`所有的操作直接通过`Redis`操作实现，在内存中没有记录。优点是对内存占用小，缺点是所有`Session`操作都是直接操作`Redis`。
> > 具体的，大家可以看看源码实现对比下。此外，如果觉得不满意，也可以自实现`Session Storage`。`GoFrame`框架的核心组件均采用了接口化设计，提供了非常强大的可扩展性。
> 
> @gqcn 在一个请求的生命周期里面保存session到内存是合理的，但是请求结束后内存session没有销毁这点我从源码上并没有看到会提高`Session`查询的效率哦，而只是提供了兜底操作，当远程存储不可用时可以降级使用本地session，另外`StorageRedisHashTable`这种方式的确可以绕过内存session，但无法兼容我们的业务系统，这就很蛋疼了
> 
> https://github.com/gogf/gf/blob/be77779affcc6b58d9841001c128956aeac750bc/os/gsession/gsession_session.go#L38
> 
> 
> ![image](https://user-images.githubusercontent.com/13849457/165251261-373986c8-e73a-4d37-b164-771f6e9316f3.png)

`Session`不是随着请求结束而销毁的，你看到的在请求流程中的`Session.Close`只是更新`Session TTL`，`Session`中的数据只要在使用就会不断更新`TTL`。你可以调`Session.RemoveAll`方法清空`Session`，特别是在用户注销登录时。

**Comment by zhoxife3ng** [comment]
我觉得你可能没有理解我的意思，我说的内存session是指内存缓存，`Session`确实不是随着请求结束而销毁的，只是会更新`Session TTL`或将session保存起来。
举个例子吧，目前`Session.Close`时，`session`会分别保存到内存和redis，调用`Session.RemoveAll`会清除内存和reids保存的session，但这并不是我期望的结果。
我期望的是`Session.Close`时session只会保存到redis而不会保存到内存，因为保存到内存并不会带来效率的提升。
目前我已通过其它方式解决这个问题了，解决的方式是通过将`sessionMaxAge`值设置成非常小，而在自定义的`SessionStorage`里忽略`sessionMaxAge`的值。把`sessionMaxAge`设置的非常小是为了内存缓存能快速释放，`SessionStorage`里忽略`sessionMaxAge`是为了session能在redis保存得久一点。
不管怎样，还是感谢你耐心的解答 @gqcn

**Comment by gqcn** [comment]
> 我觉得你可能没有理解我的意思，我说的内存session是指内存缓存，`Session`确实不是随着请求结束而销毁的，只是会更新`Session TTL`或将session保存起来。 举个例子吧，目前`Session.Close`时，`session`会分别保存到内存和redis，调用`Session.RemoveAll`会清除内存和reids保存的session，但这并不是我期望的结果。 我期望的是`Session.Close`时session只会保存到redis而不会保存到内存，因为保存到内存并不会带来效率的提升。 目前我已通过其它方式解决这个问题了，解决的方式是通过将`sessionMaxAge`值设置成非常小，而在自定义的`SessionStorage`里忽略`sessionMaxAge`的值。把`sessionMaxAge`设置的非常小是为了内存缓存能快速释放，`SessionStorage`里忽略`sessionMaxAge`是为了session能在redis保存得久一点。 不管怎样，还是感谢你耐心的解答 @gqcn

我的意思是这样的：
1. 首先，基础的，应该正确认识`Session`，它是只是在线资源的管理，不在线的资源应当持久化或者注销掉。所以不要什么东西都往里面保存。
2. 如果认为内存占用大，那可能需要审视下`Session`的规划，内存占用量需要结合在线用户数量综合评估。我都给你了例子做参考。需要注意如果在线用户不大但是内存占用大的场景。
3. 目前你采用的`Storage`我认为是`KeyValue`类型的，这种`Session`的效率是非常高的。这个效率高的理解是，在整个请求流程中，所有`Session`操作都是基于内存的（ns级别），而不是远端`Redis`服务(ms级别)。

**Comment by gqcn** [comment]
> > 是否替换过session的驱动呢
> 
> 你说的session驱动是怎样的呢，我这边是通过`g.Server().SetSessionStorage`函数使用了自己实现的session storge，但这也是无法绕过内存缓存的，因为缓存是在session manager里写死的，具体可以看下面这两个函数
> 
> https://github.com/gogf/gf/blob/be77779affcc6b58d9841001c128956aeac750bc/os/gsession/gsession_manager.go#L30
> 
> 
> https://github.com/gogf/gf/blob/be77779affcc6b58d9841001c128956aeac750bc/os/gsession/gsession_manager.go#L79

自实现`Session Storage`是可以绕开内存的，具体可以参考`StorageRedisHashTable`实现。

**Comment by zhoxife3ng** [comment]
> > 我觉得你可能没有理解我的意思，我说的内存session是指内存缓存，`Session`确实不是随着请求结束而销毁的，只是会更新`Session TTL`或将session保存起来。 举个例子吧，目前`Session.Close`时，`session`会分别保存到内存和redis，调用`Session.RemoveAll`会清除内存和reids保存的session，但这并不是我期望的结果。 我期望的是`Session.Close`时session只会保存到redis而不会保存到内存，因为保存到内存并不会带来效率的提升。 目前我已通过其它方式解决这个问题了，解决的方式是通过将`sessionMaxAge`值设置成非常小，而在自定义的`SessionStorage`里忽略`sessionMaxAge`的值。把`sessionMaxAge`设置的非常小是为了内存缓存能快速释放，`SessionStorage`里忽略`sessionMaxAge`是为了session能在redis保存得久一点。 不管怎样，还是感谢你耐心的解答 @gqcn
> 
> 我的意思是这样的：
> 
> 1. 首先，基础的，应该正确认识`Session`，它是只是在线资源的管理，不在线的资源应当持久化或者注销掉。所以不要什么东西都往里面保存。
> 2. 如果认为内存占用大，那可能需要审视下`Session`的规划，内存占用量需要结合在线用户数量综合评估。我都给你了例子做参考。需要注意在线用户不大但是内存占用大的场景。在我看来，你通过设置`MaxAge`的方式只是`workaround`，并不是`solution`。
> 3. 目前你采用的`Storage`我认为是`KeyValue`类型的，这种`Session`的效率是非常高的。这个效率高的理解是，在整个请求流程中，所有`Session`操作都是基于内存的（`ns`级别），而不是远端`Redis`服务(`ms`级别)。

所以说我们的交流根本就没在一个频道上
1、什么东西该往session存很多时候不是由个人决定的，而是来自多方面的妥协。合理的使用session只是大多数所谓的架构师脑中的yy。
2、就算是在线用户不大内存占用小，这部分内存也不应该被框架强行剥夺。况且占用的内存并没有在请求初始化session的时候带来效率的提升。设置`MaxAge`只是无奈之举。
3、现在确实采用的是`KeyValue`类型的，这种类型在初始化session时加载到内存，在使用时基于内存操作，在请求结束时刷回redis存储，我觉得这只是常规操作，我想讨论的也并不是这部分，可以不用再解释。

**Comment by gqcn** [comment]
> > > 我觉得你可能没有理解我的意思，我说的内存session是指内存缓存，`Session`确实不是随着请求结束而销毁的，只是会更新`Session TTL`或将session保存起来。 举个例子吧，目前`Session.Close`时，`session`会分别保存到内存和redis，调用`Session.RemoveAll`会清除内存和reids保存的session，但这并不是我期望的结果。 我期望的是`Session.Close`时session只会保存到redis而不会保存到内存，因为保存到内存并不会带来效率的提升。 目前我已通过其它方式解决这个问题了，解决的方式是通过将`sessionMaxAge`值设置成非常小，而在自定义的`SessionStorage`里忽略`sessionMaxAge`的值。把`sessionMaxAge`设置的非常小是为了内存缓存能快速释放，`SessionStorage`里忽略`sessionMaxAge`是为了session能在redis保存得久一点。 不管怎样，还是感谢你耐心的解答 @gqcn
> > 
> > 
> > 我的意思是这样的：
> > 
> > 1. 首先，基础的，应该正确认识`Session`，它是只是在线资源的管理，不在线的资源应当持久化或者注销掉。所以不要什么东西都往里面保存。
> > 2. 如果认为内存占用大，那可能需要审视下`Session`的规划，内存占用量需要结合在线用户数量综合评估。我都给你了例子做参考。需要注意在线用户不大但是内存占用大的场景。在我看来，你通过设置`MaxAge`的方式只是`workaround`，并不是`solution`。
> > 3. 目前你采用的`Storage`我认为是`KeyValue`类型的，这种`Session`的效率是非常高的。这个效率高的理解是，在整个请求流程中，所有`Session`操作都是基于内存的（`ns`级别），而不是远端`Redis`服务(`ms`级别)。
> 
> 所以说我们的交流根本就没在一个频道上 1、什么东西该往session存很多时候不是由个人决定的，而是来自多方面的妥协。合理的使用session只是大多数所谓的架构师脑中的yy。 2、就算是在线用户不大内存占用小，这部分内存也不应该被框架强行剥夺。况且占用的内存并没有在请求初始化session的时候带来效率的提升。设置`MaxAge`只是无奈之举。 3、现在确实采用的是`KeyValue`类型的，这种类型在初始化session时加载到内存，在使用时基于内存操作，在请求结束时刷回redis存储，我觉得这只是常规操作，我想讨论的也并不是这部分，可以不用再解释。

我确实解释得比较多了，如果不满意默认的`Storage`，可以自实现的，源码都有可以参考。

**Comment by zhoxife3ng** [comment]
> > > > 我觉得你可能没有理解我的意思，我说的内存session是指内存缓存，`Session`确实不是随着请求结束而销毁的，只是会更新`Session TTL`或将session保存起来。 举个例子吧，目前`Session.Close`时，`session`会分别保存到内存和redis，调用`Session.RemoveAll`会清除内存和reids保存的session，但这并不是我期望的结果。 我期望的是`Session.Close`时session只会保存到redis而不会保存到内存，因为保存到内存并不会带来效率的提升。 目前我已通过其它方式解决这个问题了，解决的方式是通过将`sessionMaxAge`值设置成非常小，而在自定义的`SessionStorage`里忽略`sessionMaxAge`的值。把`sessionMaxAge`设置的非常小是为了内存缓存能快速释放，`SessionStorage`里忽略`sessionMaxAge`是为了session能在redis保存得久一点。 不管怎样，还是感谢你耐心的解答 @gqcn
> > > 
> > > 
> > > 我的意思是这样的：
> > > 
> > > 1. 首先，基础的，应该正确认识`Session`，它是只是在线资源的管理，不在线的资源应当持久化或者注销掉。所以不要什么东西都往里面保存。
> > > 2. 如果认为内存占用大，那可能需要审视下`Session`的规划，内存占用量需要结合在线用户数量综合评估。我都给你了例子做参考。需要注意在线用户不大但是内存占用大的场景。在我看来，你通过设置`MaxAge`的方式只是`workaround`，并不是`solution`。
> > > 3. 目前你采用的`Storage`我认为是`KeyValue`类型的，这种`Session`的效率是非常高的。这个效率高的理解是，在整个请求流程中，所有`Session`操作都是基于内存的（`ns`级别），而不是远端`Redis`服务(`ms`级别)。
> > 
> > 
> > 所以说我们的交流根本就没在一个频道上 1、什么东西该往session存很多时候不是由个人决定的，而是来自多方面的妥协。合理的使用session只是大多数所谓的架构师脑中的yy。 2、就算是在线用户不大内存占用小，这部分内存也不应该被框架强行剥夺。况且占用的内存并没有在请求初始化session的时候带来效率的提升。设置`MaxAge`只是无奈之举。 3、现在确实采用的是`KeyValue`类型的，这种类型在初始化session时加载到内存，在使用时基于内存操作，在请求结束时刷回redis存储，我觉得这只是常规操作，我想讨论的也并不是这部分，可以不用再解释。
> 
> 我确实解释得比较多了，如果不满意默认的`Storage`，可以自实现的，源码都有可以参考。

抱歉，我很满意现在的`Storage`，我只是不满意`SessionManager`

**Comment by gqcn** [comment]
> > > > > 我觉得你可能没有理解我的意思，我说的内存session是指内存缓存，`Session`确实不是随着请求结束而销毁的，只是会更新`Session TTL`或将session保存起来。 举个例子吧，目前`Session.Close`时，`session`会分别保存到内存和redis，调用`Session.RemoveAll`会清除内存和reids保存的session，但这并不是我期望的结果。 我期望的是`Session.Close`时session只会保存到redis而不会保存到内存，因为保存到内存并不会带来效率的提升。 目前我已通过其它方式解决这个问题了，解决的方式是通过将`sessionMaxAge`值设置成非常小，而在自定义的`SessionStorage`里忽略`sessionMaxAge`的值。把`sessionMaxAge`设置的非常小是为了内存缓存能快速释放，`SessionStorage`里忽略`sessionMaxAge`是为了session能在redis保存得久一点。 不管怎样，还是感谢你耐心的解答 @gqcn
> > > > 
> > > > 
> > > > 我的意思是这样的：
> > > > 
> > > > 1. 首先，基础的，应该正确认识`Session`，它是只是在线资源的管理，不在线的资源应当持久化或者注销掉。所以不要什么东西都往里面保存。
> > > > 2. 如果认为内存占用大，那可能需要审视下`Session`的规划，内存占用量需要结合在线用户数量综合评估。我都给你了例子做参考。需要注意在线用户不大但是内存占用大的场景。在我看来，你通过设置`MaxAge`的方式只是`workaround`，并不是`solution`。
> > > > 3. 目前你采用的`Storage`我认为是`KeyValue`类型的，这种`Session`的效率是非常高的。这个效率高的理解是，在整个请求流程中，所有`Session`操作都是基于内存的（`ns`级别），而不是远端`Redis`服务(`ms`级别)。
> > > 
> > > 
> > > 所以说我们的交流根本就没在一个频道上 1、什么东西该往session存很多时候不是由个人决定的，而是来自多方面的妥协。合理的使用session只是大多数所谓的架构师脑中的yy。 2、就算是在线用户不大内存占用小，这部分内存也不应该被框架强行剥夺。况且占用的内存并没有在请求初始化session的时候带来效率的提升。设置`MaxAge`只是无奈之举。 3、现在确实采用的是`KeyValue`类型的，这种类型在初始化session时加载到内存，在使用时基于内存操作，在请求结束时刷回redis存储，我觉得这只是常规操作，我想讨论的也并不是这部分，可以不用再解释。
> > 
> > 
> > 我确实解释得比较多了，如果不满意默认的`Storage`，可以自实现的，源码都有可以参考。
> 
> 抱歉，我很满意现在的`Storage`，我只是不满意`SessionManager`

感谢你的反馈，我昨晚仔细回顾了这块的代码实现，确实有需要改进的地方。我来优先处理一下，可能需要一点时间。
