### ISSUE TITLE
通用dao层设计

### ISSUE THREAD

**Issue by doodle971002** [gogf/gf#1783]
### 1. What version of `Go` and system type/arch are you using?
Go Version:  go1.17.7

### 2. What version of `GoFrame` are you using?
v2.0.6

### 4. What did you do?
每个实体均需要实现增删改查大量相似逻辑

### 5. What did you expect to see?
可否提供通用dao层？根据不同的实体来操作表
需要的是不想每一个表都去写一遍增删改查，而是提供一个传入表名就能自动去增删改查对应的表的通用方法。现在的问题是如果有100张表，就得在dao文件里写一百次根据id查询实体的链式调用，这显然重复操作太多了，可以参考springboot jpa的设计理念，提供通用的增删改查甚至搜索的dao实现

**Comment by mingzaily** [comment]
你的dao层是经常写类似 GetListByXXXX，GetOneByXXXX这些逻辑吗

**Comment by doodle971002** [comment]
> 你的dao层是经常写类似 GetListByXXXX，GetOneByXXXX这些逻辑吗

是这样的

**Comment by mingzaily** [comment]
可以给gf cli提个PR哦

**Comment by gqcn** [comment]
@doodle971002 @mingzaily 哥哥些，`gf gen dao`不是就自动生成`dao`了么，并且`dao`就带了通用操作的链式方法。提问之前能先了解下现有功能嘛 https://goframe.org/pages/viewpage.action?pageId=3673173

**Comment by doodle971002** [comment]
> @doodle971002 @mingzaily 哥哥些，`gf gen dao`不是就自动生成`dao`了么，并且`dao`就带了通用操作的链式方法。提问之前能先了解下现有功能嘛 https://goframe.org/pages/viewpage.action?pageId=3673173

你根本就没理解大家想要什么，就随便关掉了issue。事实上我们需要的是不想每一个表都去写一遍增删改查，而是提供一个传入表明就能自动去增删改查对应的表。
还有个问题就是，大家在网上回复问题都喜欢怼人吗？到底是谁没了解清楚需求呢

**Comment by gqcn** [comment]
> > @doodle971002 @mingzaily 哥哥些，`gf gen dao`不是就自动生成`dao`了么，并且`dao`就带了通用操作的链式方法。提问之前能先了解下现有功能嘛 https://goframe.org/pages/viewpage.action?pageId=3673173
> 
> 你根本就没理解大家想要什么，就随便关掉了issue。事实上我们需要的是不想每一个表都去写一遍增删改查，而是提供一个传入表名就能自动去增删改查对应的表的通用方法。现在的问题是如果有100张表，我得在dao文件里写一百次根据id查询实体的链式调用，这显然重复操作太多了，可以参考springboot jpa的设计理念，提供通用的增删改查甚至搜索的dao实现
> 
> 还有个问题就是，大家在网上回复问题都喜欢怼人吗？到底是谁没了解清楚需求呢

你把你的这段评论放`issue`主题内容，都会比现在一句话要好很多，不是吗。

**Comment by gqcn** [comment]
@doodle971002 @mingzaily 根据后续描述，这个问题其实可以通过自定义`dao`代码生成模板来实现。

**Comment by doodle971002** [comment]
> > > @doodle971002 @mingzaily 哥哥些，`gf gen dao`不是就自动生成`dao`了么，并且`dao`就带了通用操作的链式方法。提问之前能先了解下现有功能嘛 https://goframe.org/pages/viewpage.action?pageId=3673173
> > 
> > 
> > 你根本就没理解大家想要什么，就随便关掉了issue。事实上我们需要的是不想每一个表都去写一遍增删改查，而是提供一个传入表名就能自动去增删改查对应的表的通用方法。现在的问题是如果有100张表，我得在dao文件里写一百次根据id查询实体的链式调用，这显然重复操作太多了，可以参考springboot jpa的设计理念，提供通用的增删改查甚至搜索的dao实现
> > 还有个问题就是，大家在网上回复问题都喜欢怼人吗？到底是谁没了解清楚需求呢
> 
> 你把你的这段评论放`issue`主题内容，都会比现在一句话要好很多，不是吗？


我觉得看一下这句话应该就能明白
> 你的dao层是经常写类似 GetListByXXXX，GetOneByXXXX这些逻辑吗

除非你不经常写这些

**Comment by doodle971002** [comment]
### 现阶段根据框架文档搞了个暂时的解决方案：

>  dao/common.go

```go
package dao

import (
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

type DaoCommon struct {
	Table string
	Model *gdb.Model
}

func NewCommonDao (table string) *DaoCommon {
	return &DaoCommon{table, g.Model(table)}
}

func (common *DaoCommon) FindById (id int64) (*gdb.Record, error) {
	record, err := common.Model.One("id=?", id)
	return &record, err
}

func (common *DaoCommon) ListPageable (pageIndex int, pageSize int) (*gdb.Result, int, error) {
	results, err := common.Model.Limit(pageIndex*pageSize, pageSize).All()
	total, err := common.Model.Count()
	return &results, total, err
}

func (common *DaoCommon) DeleteById (id int64) error {
	_, err := common.Model.Delete("id=?", id)
	return err
}

func (common *DaoCommon) Create (data interface{}) error {
	_, err := common.Model.Data(data).Insert()
	return err
}

func (common *DaoCommon) UpdateById (data interface{}, id int64) error {
	_, err := common.Model.Data(data).Where("id=?", id).Update()
	return err
}
```


> eg: service/person.go

```go
var commonDao = dao.NewCommonDao("person")
func (p *sPerson) Create(in *v1.PersonCreateReq) error {
	err := commonDao.Create(&do.Person{
		Name:      in.Name,
		Gender:    in.Gender,
		Birth:     in.Birth,
		Passed:    in.Passed,
		AvatarUrl: in.AvatarUrl,
	})
	return err
}
```

实测暂未发现问题

**Comment by doodle971002** [comment]
> @doodle971002 这种在`dao`上封装操作方法的工作价值并不是很大，因为具体的ORM业务场景比较复杂、并且链式操作已经很方便了通过方法组合的方式已经能满足需求。我理解的价值最大的是自动生成`controller/model/service`的`CURD`方法和模型定义。

那为什么jpa要通过反射实现类似的功能呢

**Comment by gqcn** [comment]
> > @doodle971002 这种在`dao`上封装操作方法的工作价值并不是很大，因为具体的ORM业务场景比较复杂、并且链式操作已经很方便了通过方法组合的方式已经能满足需求。我理解的价值最大的是自动生成`controller/model/service`的`CURD`方法和模型定义。
> 
> 那为什么jpa要通过反射实现类似的功能呢

`jpa`是什么？
