### ISSUE TITLE
Transaction error

### ISSUE THREAD

**Issue by peng** [gogf/gf#1785]
go version 1.7  
goframe version 2.0  
macos 12.3.1    apple-m1 

response body: exception recovered: runtime error: invalid memory address or nil pointer dereference

if run above code
```
var db gdb.DB
db.Transaction(context.TODO(), func(ctx context.Context, tx *gdb.TX) error {
return nil
}
```

when run this func response body:  exception recovered: runtime error: invalid memory address or nil pointer dereference

**Comment by DGuang21** [comment]
Can you tell us more details?

**Comment by peng** [comment]
> 

https://github.com/peng/gf-demo-user/blob/test/internal/service/internal/dao/user.go

end of this file i wrote a demo, with a user_test file in current folder

**Comment by DGuang21** [comment]
> > Can you tell us more details?
> 
> 
> 
> 而且文档上db 怎么来的希望写一下，我照你们写的test 上的写法找的db ，但是用起来报错

单测中的db已经提前进行过初始化所以不会报错，如果是希望使用相关功能可以查阅下方文档。
[数据库 ORM](https://goframe.org/pages/viewpage.action?pageId=1114686)
[gf dao](https://goframe.org/pages/viewpage.action?pageId=3673173)

**Comment by peng** [comment]
> > > Can you tell us more details?
> > 
> > 
> > 而且文档上db 怎么来的希望写一下，我照你们写的test 上的写法找的db ，但是用起来报错
> 
> 单测中的db已经提前进行过初始化所以不会报错，如果是希望使用相关功能可以查阅下方文档。 [数据库 ORM](https://goframe.org/pages/viewpage.action?pageId=1114686) [gf dao](https://goframe.org/pages/viewpage.action?pageId=3673173)

建议文档有个 db 在哪的link , 之前看过那，当时没注意到，后来就忘了；问题已解决，感谢！
