### ISSUE TITLE
gset.New(true) can't add g.Map

### ISSUE THREAD

**Issue by arden** [gogf/gf#1787]
```go
	userSet := gset.New(true)
	userSet.Add(g.Map{
		"id": 1,
		"name": "arden",
	})
	userSet.Add(g.Map{
		"id": 2,
		"name": "tujiao",
	})
```

panic: runtime error: hash of unhashable type map[string]interface {}

goroutine 1 [running]:
github.com/gogf/gf/v2/container/gset.(*Set).Add(0xc00029bf58, 0xc00029bf68, 0x1, 0x1)
	D:/Go/pkg/mod/github.com/gogf/gf/v2@v2.0.6/container/gset/gset_any_set.go:72 +0xa8
main.main()
	E:/repository/tooyoung/hdcj/go/easypush/devops/guangdong_push.go:16 +0x1eb

**Comment by gqcn** [comment]
@arden The underlying data structure of `set` is map. The value of set is assigned as key of map, it so requires the value should be hashable.
