### ISSUE TITLE
use validate component of min:1 occured bug

### ISSUE THREAD

**Issue by FTLLOVE** [gogf/gf#1791]
### 1. What version of `Go` and system type/arch are you using?

go version go1.18 darwin/amd64

### 2. What version of `GoFrame` are you using?

Goframe v1.16.7

### 4. What did you do?

When I use Min: 1 to verify whether the value of int type is required, the verification does not take effect;

<img width="752" alt="image" src="https://user-images.githubusercontent.com/22320062/165543847-b721d476-667b-4096-a124-0d4a9a8ae97c.png">
<img width="770" alt="image" src="https://user-images.githubusercontent.com/22320062/165544144-1fd8dda3-cc80-41cb-a500-e7a2a6e52086.png">
<img width="538" alt="image" src="https://user-images.githubusercontent.com/22320062/165544661-8c1687df-c3fc-4c85-bc19-e4229984fe7c.png">

### 5. What did you expect to see?
I think this is a bug

**Comment by DGuang21** [comment]
你可以尝试一下将原始的request打印出来，按图中参数传递大概率是 `DictTypeId=` ，对应的校验规则应当为`required|min:1` .

[关于参数校验的详细规则](https://goframe.org/pages/viewpage.action?pageId=1114244)

**Comment by FTLLOVE** [comment]
> 你可以尝试一下将原始的request打印出来，按图中参数传递大概率是 `DictTypeId=` ，对应的校验规则应当为`required|min:1` .
> 
> [关于参数校验的详细规则](https://goframe.org/pages/viewpage.action?pageId=1114244)

接收不到,r.parse(&c)，这个dictTypeId都没有，而且required对int类型是不生效的，之前我用1.15的时候，使用min:1是没问题的，不知道是不是1.16的bug

**Comment by gqcn** [comment]
@FTLLOVE Use composed validation rules `v:"reqiured|min:1"` instead of `v:"min:1"` if this parameter is required.
