### ISSUE TITLE
pgsql有插入返回ID功能，为什么在GF当中没有集成？

### ISSUE THREAD

**Issue by hametan** [gogf/gf#1793]
pgsql有插入返回ID功能returning id
pgsql同时也有插入更新conflict 

为什么集成到GF当中呢？

**Comment by houseme** [comment]
> pgsql有插入返回ID功能returning id pgsql同时也有插入更新conflict
> 
> 为什么集成到GF当中呢？

```go
func (m *Model) InsertAndGetId(data ...interface{}) (lastInsertId int64, err error) 
```

**Comment by gqcn** [comment]
> > pgsql有插入返回ID功能returning id pgsql同时也有插入更新conflict
> > 为什么集成到GF当中呢？
> 
> ```go
> func (m *Model) InsertAndGetId(data ...interface{}) (lastInsertId int64, err error) 
> ```

他说的不是这个方法。
