### ISSUE TITLE
多域名下如何设置对应多个静态目录SetServerRoot

### ISSUE THREAD

**Issue by 308066400** [gogf/gf#1794]
s.Domain("www.domain.com").BindHandler("/", www.Static)
s.Domain("a.domain.com").BindHandler("/", a.Static)

www开头的域名对应的是static/www目录
a开头的域名对应的是static/a目录

**Comment by houseme** [comment]
https://goframe.org/pages/viewpage.action?pageId=3670228

**Comment by gqcn** [comment]
@308066400 GoFrame应该是支持的，可以看看文档。
