### ISSUE TITLE
好像没有权限管理模块？

### ISSUE THREAD

**Issue by dbsn** [gogf/gf#18]
感谢作者的努力和无私奉献。

能否增加一个权限管理模块？
或者增加对 https://github.com/casbin/casbin 的支持？

**Comment by johng-cn** [comment]
@dbsn 很多朋友都问过这个问题，不过目前`GF`框架暂时没有权限管理模块，可以考虑第三方比较成熟的`casbin`包。未来`GF`会有权限管理模块，可能是轻量级的`RBAC`方式，也可能会基于`casbin`。

**Comment by dbsn** [comment]
收到，多谢作者回复。

**Comment by hsluoyz** [comment]
你好，Casbin目前对大多数Web框架都有插件来支持集成，gf框架的，应该也需要写一个``gf-authz``插件。但是看了下官方文档，好像没有找到插件开发相关的内容，请问如何开发一个gf的过滤器插件呢？

**Comment by johng-cn** [comment]
@hsluoyz 你好，官方文档的确没有权限这块的说明。自行实现权限校验可以通过`HOOK`回调注册一个全局的`HOOK_BEFORE_SERVE`回调钩子来实现，如`/*`, `/api/*`等等全局的路由。在回调函数中调用相应的校验模块来完成权限校验，如果权限校验失败，调用`r.Exit()`退出后续的业务逻辑执行即可。

**Comment by johngcn** [comment]
@hsluoyz 你好，关于`gf`的权限管理插件可以参考`gf-jwt`这个插件来编写：https://github.com/gogf/gf-jwt 不知道你是否有时间为`gf`贡献一款基于`casbin`的权限管理插件？

**Comment by vance-liu** [comment]
可以参考下这个 https://github.com/vance-liu/gdb-adapter
