### ISSUE TITLE
gf1.5和2.0的差异问题

### ISSUE THREAD

**Issue by wuyuzhe** [gogf/gf#1801]
### 1. What version of `Go` and system type/arch are you using?
go 1.16.3

### 2. What version of `GoFrame` are you using?
1.15    2.0

#### 1、 gf2.0框架为什么不把route路由单独提出来？
类似version 1的方式。对于一些项目路由可能有上百个，会导致cmd.go这个文件特别庞大，也不利于后期的路由维护

#### 2、goframe的版本哪一个是长期维护的版本？
一个是对于一些项目时间相对来说是比较长的，不适合频繁的更换框架版本。
另外就是对于长期开发的项目希望能有持续迭代的大版本。不是目前这种version1到version2的大变更。

#### 3、目前的框架文档没有看到对gf生成的代码树的一个清晰的说明
```
1.15有代码树图片但是图片无法查看。
gf工具只有简单的说明，1.15没有看到是依据什么去生成对应的dao和model的。

2.0的gf文档还可以看到一个bilibili的链接。能看到是根据sql来生成。但是信息量相对视频长度来说太少了。
```

####  4、gf工具能否安装多个版本。用于生成不同版本的框架
可能会同时维护多个版本的项目。

**Comment by BeanWei** [comment]
gf 主框架的版本是遵循了 `semver` 规则的，v1 => v2 这种大版本变更迁移肯定会有或多或少的成本，是可以理解的。
至于长期维护的版本，老实讲，核心开发目前依然只有作者本人，所以在功能迭代，bug处理上肯定会有侧重点。虽说如此，但是比较大的bug一般旧版也不会有吧，如果有的话可以提issue。自己的项目并不需要紧跟框架版本走，v1 => v2 并不是意味着 v1 bug太多 然后跳票到 v2，生态在变，语言本身的特性在变，开发者的诉求在变，这些才是大版本更新的原因。

然后说下 gf 周边的生态吧，我个人是从来没有使用过 gf 的 cli 工具和代码生成的。这其中的原因是：我个人有对工程的理解，而且个人开发的项目有不同的诉求，所以我更习惯使用自己的代码组织方式和代码生成工具。

Anyway, gf 是完全开源的，而且作者也十分open，不管是需求还是pr 都是十分欢迎的。

**Comment by gqcn** [comment]
@wuyuzhe @BeanWei 
1. **`gf2.0`框架为什么不把`route`路由单独提出来？**
从`v2`版本开始，我们推荐业务项目使用结构化的输入/输出接口定义，并且建议通过`g.Meta`方式维护接口描述，因此原本的`router`包就不再有太大的意义（具体请参考文档：https://goframe.org/pages/viewpage.action?pageId=40219890 ）。这其实也是为了改进支持业务维护大量的接口来考虑的。当然对于非结构化的接口管理方式，你也可以依旧保留`router`包，这些都可以自主灵活管理。
2. **`goframe`的版本哪一个是长期维护的版本？**
`goframe`会长期维护，但是不存在`长期维护的特定版本`。我理解，你其实想要的是一个兼容性的稳定版本，`v2`版本是按照`golang`推荐的版本管理来发布的，是一个不兼容`v1`的版本。不过，经过多年的沉淀，目前`goframe`的各个组件也越趋于稳定。
3. **目前的框架文档没有看到对`gf`生成的代码树的一个清晰的说明**
在这里有几篇介绍工程化设计的文章，可以看看：https://goframe.org/pages/viewpage.action?pageId=30740161 其次看看代码生成的工具命令：https://goframe.org/pages/viewpage.action?pageId=1115790
`goframe`由于自身走得过快，忽视了对新人的培养，没有进行详细的宣讲和推广，这也是她目前的缺陷。
4. `gf`工具能否安装多个版本。用于生成不同版本的框架
`goframe`的`cli`工具本身支持版本管理的，可以自主选择版本使用。从`v2`版本开始和主库共同维护，保持版本一致。
