### ISSUE TITLE
clickhouse driver can`t change username, password and database

### ISSUE THREAD

**Issue by qq375251855** [gogf/gf#1808]
### 1. What version of `Go` and system type/arch are you using?

go 1.17

### 2. What version of `GoFrame` are you using?

gf 2.0.7-0.20220509062228-534abb7f179a

### 3. Can this issue be re-produced with the latest release?
Yes

### 4. What did you do?

go get -u -v github.com/gogf/gf/v2@master
go get -u -v github.com/gogf/gf/contrib/drivers/clickhouse/v2

connect, err := gdb.New(gdb.ConfigNode{
		Host:  "127.0.0.1",
		Port:  "9000",
		User:  "no_default",  // no default
		Name:  "no_default", // no default    
		Type:  "clickhouse",
		Debug: true,
	})

sqlStr := "CREATE TABLE IF NOT EXISTS visits (id UInt64,duration Float64,url String,created DateTime) ENGINE = MergeTree()  PRIMARY KEY id ORDER BY id"
_, err := connect.Exec(context.Background(), sqlStr) // error
### 6. What did you see instead?
the request has been waiting and no error

### 7. Why

the clickhouse driver use the clickhouse-go v1.5.2, according to the document，the dsn is like 
~~~
tcp://host1:9000?username=user&password=qwerty&database=clicks&read_timeout=10&write_timeout=20&alt_hosts=host2:9000,host3:9000
~~~
but, the clickhouse driver use the format(clickhouse-go v2)
~~~
clickhouse://username:password@host1:9000,host2:9000/database?dial_timeout=200ms&max_execution_time=60
~~~
so,i can`t change username, password,database

**Comment by qq375251855** [comment]
in clickhouse-go@v1.5.4/bootstrap.go,
~~~
url, err := url.Parse(dsn)
	if err != nil {
		return nil, err
	}
	var (
		hosts             = []string{url.Host}
		query             = url.Query()
		secure            = false
		skipVerify        = false
		tlsConfigName     = query.Get("tls_config")
		noDelay           = true
		compress          = false
		database          = query.Get("database")
		username          = query.Get("username")
		password          = query.Get("password")
       )
~~~
so, use the v2 format, can`t find the username,password and database

**Comment by qq375251855** [comment]
meanwhile, there is no error and the request has been waiting

**Comment by DGuang21** [comment]
The current driver version is still using V1 and will be upgraded to V2 soon. We will follow up on this issue.

**Comment by gqcn** [comment]
@DGuang21 Please follow on this issue after `v2` version of `clickhouse` driver is supported in `goframe`.

**Comment by DGuang21** [comment]
upgrade ClickHouse dependencies to V2  https://github.com/gogf/gf/pull/1772
