### ISSUE TITLE
单元测试完善：contrib/drivers/pgsql

### ISSUE THREAD

**Issue by gqcn** [gogf/gf#1812]
完善社区组件 `contrib/drivers/pgsql` 的单元测试。

组件地址：https://github.com/gogf/gf/tree/master/contrib/drivers/pgsql

要求：
1. 提供`Model`的`CURD`用例，至少包含这些方法的测试用例：
- 模型：`Model/Raw`
- 查询：`All/One/Value/Array/Scan/Count`
- 条件：多条件`Where`组合用例
- 写入：`Insert/Replace/Save`
- 更新：`Update`
- 删除：`Delete`
3. 提供`DB`接口的`CURD`用例，至少包含这些方法的测试用例：
- 原生：`Query/Exec`
- 查询：`GetAll/GetOne/GetValue/GetCount/GetArray/GetScan`
- 写入：`Insert/Replace/Save` 
- 更新：`Update`
- 删除：`Delete`
- 功能：`Tables/TableFields` 特别重要

注意事项：不支持的方法断言返回的错误即可。

**Comment by chaggle** [comment]
I want to try my best to contribute this issue

**Comment by chaggle** [comment]
#1837

**Comment by chaggle** [comment]
#1838

**Comment by nuan1989** [comment]
大佬, gf的单元测试用要用什么工具啊, 我直接在goland文件右键"使用覆盖率运行", 发现ghttp需要在hosts设置"http://local:"域名, 
我是win系统, 只能手动添加域名嘛

**Comment by hailaz** [comment]
> 大佬, gf的单元测试用要用什么工具啊, 我直接在goland文件右键"使用覆盖率运行", 发现ghttp需要在hosts设置"[http://local:"域名](http://local:%22%E5%9F%9F%E5%90%8D), 我是win系统, 只能手动添加域名嘛

@nuan1989 https://github.com/gogf/gf/blob/141ca62c6dd8cb75234fbba2484855e41a385a7e/.github/workflows/before_script.sh#L6

ci里面有个脚本加了个host，可以试试在本地加个host

**Comment by nuan1989** [comment]
> > 大佬，gf的单元测试用什么工具啊，我直接在goland文件右键“使用覆盖率运行”，发现ghttp需要在hosts设置“ [http://local:”域名](http://local:%22%E5%9F%9F%E5%90%8D)，我是win系统，只能手动添加域名
> 
> @nuan1989
> 
> https://github.com/gogf/gf/blob/141ca62c6dd8cb75234fbba2484855e41a385a7e/.github/workflows/before_script.sh#L6
> 
> ci里面有一个脚本加了个host，可以在本地加个host试试
亮哥, 我是草根, 没用过ci, win就能自己用不, 还是win需要自己去配置这个hosts脚本, 我看了里面的命令都是Linux用的. 如果需要自己再配置, 我就不学ci了. 哈哈哈... 谢谢亮仔

**Comment by hailaz** [comment]
> [local](http://local):

@nuan1989 下载一个switchhosts，设置比较方便。
![image](https://github.com/gogf/gf/assets/29968474/1b1e1da2-8593-4b91-940d-d718e580f03e)

**Comment by nuan1989** [comment]
> > [本地](http://local)：
> 
> @nuan1989下载一个switchhosts，设置比较方便。 ![图像](https://user-images.githubusercontent.com/29968474/277219792-1b1e1da2-8593-4b91-940d-d718e580f03e.png)

嗯嗯, 谢谢亮仔....
