### ISSUE TITLE
HTTPClient大量请求没有释放

### ISSUE THREAD

**Issue by xxxlzj520** [gogf/gf#1822]
c := g.Client()
	defer c.CloseIdleConnections()
	url:=fmt.Sprintf("http://xxxx/inner/books/owned/list?uid=%d",i)
	r, err := c.Get(gctx.New(), url)
	defer r.Close()
	if err != nil{
		fmt.Println(err)
		
	}else {
		fmt.Println(r.StatusCode)
		
	}

gf版本：v2.0.6
现像描述：当for循环调用请求时，数据过多会导致请求没有释放，本地打开文件数过多

**Comment by huangqian1985** [comment]
g.Client() 底层是对原生http.Client的封装, 代码见 https://github.com/gogf/gf/blob/583d576cdba6c46049f23f2caf36714054d30cc4/net/gclient/gclient.go#L59

http.Client原生是支持连接池的处理的, http.Transport的MaxConnsPerHost和MaxIdleConnsPerHost属性控制了每个Client最大支持的请求对象的数量, MaxIdleConns属性控制了保持多少个活跃连接.

所以其实在for循环里一直创建gClient对象不是一个好的处理方案.

但是我看了gClient的方法,并没有自定义http.Client的方式, 是否考虑加一个相关的方法？可以开一个help wanted 我来操作一波 @gqcn 。

@xxxlzj520 如果你比较着急的话, 我建议你使用gpool的方式来做实现. 文档见 https://goframe.org/pages/viewpage.action?pageId=1114377

**Comment by gqcn** [comment]
@xxxlzj520 @huangqian1985 不要在循环中使用`defer`，这样会`defer`失败的。
