### ISSUE TITLE
orm 关于 order 排序字段自定义排序规则问题

### ISSUE THREAD

**Issue by ituserxxx** [gogf/gf#1828]
### 1. What version of `Go` and system type/arch are you using?

  Go Version:  go1.17.7  windows/amd64

### 2. What version of `GoFrame` are you using?

 GF Version:  v2.0.6
GoFrame Version: v2.0.0-rc.0.20220117131058-9345eb5e946f in current go.mod

### 3. Can this issue be re-produced with the latest release?
ok

### 4. What did you do?

使用 Msyql  中 有一个 tinyint 类型 status 字段查询排序的场景，例如:

我需要对 status 字段自定义排序按照 2,1,3 的排序方式进行查询多行记录，那么在 Mysql Cmd中执行语句是：
```
SELECT `status` FROM `device` ORDER BY field(`status`,2,1,3)
```
上面语句可成功查询

但是当我用 orm 链式查询方式：
```
# 1.直接写原生 sql
dao.Device.Ctx(ctx).Fields("device_id").Order("field(`status`,2,1,3)")
# 2.使用 gdb.Raw()
dao.Device.Ctx(ctx).Fields("status").Order(string(gdb.Raw("field(`status`,2,1,3)")))
```
以上2种方式均报错，提示如下:
```
Error 1054: Unknown column '3' in 'order clause', SELECT `device_id` FROM `device` ORDER BY field(`status`,`2`,`1`,3)
```

### 5. What did you expect to see?

I would like to see gf processing into statements that mysql can execute

### 6. What did you see instead?
Different results

**Comment by gqcn** [comment]
```go
dao.Device.Ctx(ctx).Fields("status").Order(db.Raw("field(`status`,2,1,3)"))
```
