### ISSUE TITLE
g.log 输出在win2012系统下不换行

### ISSUE THREAD

**Issue by xushushun** [gogf/gf#1829]
### 1. What version of `Go` and system type/arch are you using?

系统win2012,
go1.16

### 2. What version of `GoFrame` are you using?

gf版本 v2.0.0-rc.0.20220117131058-9345eb5e946f

### 4. What did you do?

`	for i := 0; i < 20; i++ {
				g.Log().Print(context.TODO(), "aaa", i)
			}`

### 5. What did you expect to see?

所有输出都在同一行

### 6. What did you see instead?

输出在不同行

**Comment by xushushun** [comment]
> print和printf都带换行的，就是这样写的

我在win10系统上面确实是带换行的,但是部署到win2012服务器上就不带换行了.

**Comment by wenzi1** [comment]
没有环境，无法复现。。。。

**Comment by gqcn** [comment]
@xushushun 我也很奇怪呢。由社区小伙伴来帮助你吧。

**Comment by xushushun** [comment]
经过测试 是系统问题，将日志文件复制到别的系统就可以正常显示换行了。
