### ISSUE TITLE
swagger 中引用了一个无法打开的url导致页面无内容

### ISSUE THREAD

**Issue by sanrentai** [gogf/gf#1862]
### 1. What version of `Go` and system type/arch are you using?
go version go1.17.1 windows/amd64

### 2. What version of `GoFrame` are you using?
v2.0.6

### 3. Can this issue be re-produced with the latest release?

yes

### 4. What did you do?
[<!--
If possible, provide a copy of shortest codes for reproducing the error.
A complete runnable program is best.
http://127.0.0.1:8201/swagger/

在源码 ghttp_server_swagger.go 文件中，引用了一个外部的js
``` 
<script src="https://cdn.jsdelivr.net/npm/redoc@latest/bundles/redoc.standalone.js"> </script>
``` 

### 6. What did you see instead?

https://cdn.jsdelivr.net/npm/redoc@latest/bundles/redoc.standalone.js  无法访问，404

**Comment by sanrentai** [comment]
查看源码，发现已经把redoc.standalone.js 打包到静态资源中了，可以将
``` 
<script src="https://cdn.jsdelivr.net/npm/redoc@latest/bundles/redoc.standalone.js"> </script>
``` 
改成
``` 
<script src="./redoc.standalone.js"> </script>
```

**Comment by houseme** [comment]
> https://cdn.jsdelivr.net/npm/redoc@latest/bundles/redoc.standalone.js

网络问题？

**Comment by hailaz** [comment]
cdn.jsdelivr.net被墙了
已替换新的资源 61271e4f7b1f04e239e13c9bddee53bb45ba5764
