### ISSUE TITLE
gqueue的方法new后，Push可能会引起panic

### ISSUE THREAD

**Issue by jroam** [gogf/gf#188]
go 1.12
windows
gf最新代码

注意：要多运行几次才有可能发生，运行一次或二次，有可能不会发生问题。

```
maxs:=14
q2:=gqueue.New(maxs)
for i:=1;i<maxs;i++{
	q2.Push(i)
}
i3:=q2.Pop()
gtest.Assert(i3,1)
```

提示错误代码
```
PASS
panic: send on closed channel

goroutine 38 [running]:
github.com/gogf/gf/g/container/gqueue.(*Queue).startAsyncLoop(0xc000050840)
```

**Comment by johngcn** [comment]
@jroam 我的测试代码如下：
```go
package main

import (
	"github.com/gogf/gf/g/container/gqueue"
	"github.com/gogf/gf/g/test/gtest"
)

func main() {
	max := 14
	for i := 0; i < 10; i++ {
		q := gqueue.New(max)
		for i := 1; i < max; i++ {
			q.Push(i)
		}
		gtest.Assert(q.Pop(), 1)
	}
}
```
运行多次从来没有报错，准确的错误定位要看报错的`backtrace`列表详情，如果你实在无法定位原因，可以提交pr后我来完整运行试试看。

**Comment by jroam** [comment]
package gqueue_test

import (
	"github.com/gogf/gf/g/container/gqueue"
	"github.com/gogf/gf/g/test/gtest"
	"testing"
)

func TestQueue_Len(t *testing.T) {
	q1 := gqueue.New(300)
	for i := 0; i < 200; i++ {
		q1.Push(i)
	}
	gtest.Assert(q1.Len(), 200)
}

func TestQueue_Pop(t *testing.T) {
	q1 := gqueue.New()

	q1.Push(1)
	q1.Push(2)
	i1 := q1.Pop()
	gtest.Assert(i1, 1)
	q1.Close()
	i1 = q1.Pop()
	gtest.Assert(i1, 2)

	maxs := 12
	q2 := gqueue.New(maxs)
	for i := 0; i < maxs; i++ {
		q2.Push(i)
	}

	i3 := q2.Pop()
	gtest.Assert(i3, 0)

}

func TestQueue_Close(t *testing.T) {
	q1 := gqueue.New()
	q1.Push(2)
	q1.Push(2)
	gtest.Assert(q1.Len(), 2)

	q1.Close()
	gtest.Assert(q1.Len(), 2)

}

**Comment by jroam** [comment]
大佬已解决。
