### ISSUE TITLE
g.Log() 输出时，ctxStr是否使用json格式更好

### ISSUE THREAD

**Issue by larryclean** [gogf/gf#1883]
### 1. What version of `Go` and system type/arch are you using?
go version go1.18.1 darwin/arm64

### 2. What version of `GoFrame` are you using?
v2.0.4

### 3. Can this issue be re-produced with the latest release?

nil

### 5. What did you expect to see?

{"traceId":"80d4d4c3d0a1f21617331238b3f1afec","demo1":"1232", "demo2":"3456"}

这样方便使用日志采集平台，不然现在这样不对称感觉无法区分。只是个人建议。

### 6. What did you see instead?
{80d4d4c3d0a1f21617331238b3f1afec, 1232, 3456}

**Comment by houseme** [comment]
这个格式是可以配置的

**Comment by gqcn** [comment]
@larryclean https://goframe.org/pages/viewpage.action?pageId=17207121
