### ISSUE TITLE
404 error req startus 200 

### ISSUE THREAD

**Issue by codgo** [gogf/gf#1893]
404 error req startus 200 
404 返回的状态码肯定不应该是200 啊, 这样百度索引上的....应该是404

**Comment by houseme** [comment]
这个404是业务code吗？

**Comment by codgo** [comment]
404 返回状态码, 你们现在是200....

houseme ***@***.***> 于2022年6月7日周二 08:42写道：

**Comment by codgo** [comment]
![6E939132ACF59F62C7FEAC09BC7E8795](https://user-images.githubusercontent.com/52227185/172315313-cdbf04a7-139d-4ffd-b189-1e6a0847f201.png)
`package main

import (
    "github.com/gogf/gf/frame/g"
    "github.com/gogf/gf/net/ghttp"
)

func main() {
    s := g.Server()
    s.BindHandler("/status/:status", func(r *ghttp.Request) {
        r.Response.Write("woops, status ", r.Get("status"), " found")
    })
    s.BindStatusHandler(404, func(r *ghttp.Request){
        r.Response.RedirectTo("/status/404")
    })
    s.SetPort(8199)
    s.Run()
}`

**Comment by houseme** [comment]
> ![6E939132ACF59F62C7FEAC09BC7E8795](https://user-images.githubusercontent.com/52227185/172315313-cdbf04a7-139d-4ffd-b189-1e6a0847f201.png)
> 
> ```
> package main
> 
> import (
>     "github.com/gogf/gf/frame/g"
>     "github.com/gogf/gf/net/ghttp"
> )
> 
> func main() {
>     s := g.Server()
>     s.BindHandler("/status/:status", func(r *ghttp.Request) {
>         r.Response.Write("woops, status ", r.Get("status"), " found")
>     })
>     s.BindStatusHandler(404, func(r *ghttp.Request){
>         r.Response.RedirectTo("/status/404")
>     })
>     s.SetPort(8199)
>     s.Run()
> }
> ```
> 
> 另外写法是一样的
> 
> ```
> package main
> 
> import (
> 	"github.com/gogf/gf/frame/g"
> 	"github.com/gogf/gf/net/ghttp"
> )
> 
> func main() {
> 	s := g.Server()
> 	s.BindHandler("/", func(r *ghttp.Request) {
> 		r.Response.Writeln("halo 世界！")
> 	})
> 	s.BindStatusHandler(404, func(r *ghttp.Request) {
> 		r.Response.Writeln("This is customized 404 page")
> 	})
> 	s.SetPort(8199)
> 	s.Run()
> }
> ```
> 
> 指定http 的status code 不应该是404 如果返回200 搜索引擎会强制收录,会有很多麻烦

可以来提个pr

**Comment by houseme** [comment]
```go
package main

import (
    "github.com/gogf/gf/frame/g"
    "github.com/gogf/gf/net/ghttp"
)

func main() {
    s := g.Server()
    s.BindHandler("/status/:status", func(r *ghttp.Request) {
        r.Response.Write("woops, status ", r.Get("status"), " found")
    })
    s.BindStatusHandler(404, func(r *ghttp.Request){
        r.Response.RedirectTo("/status/404")
    })
    s.SetPort(8199)
    s.Run()
}
```

这个代码是404跳转到正常的200页面

**Comment by codgo** [comment]
找到原因了... 
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/net/ghttp"
V2 正常
1.16.9 不对

**Comment by auula** [comment]
我想修复这个问题，请你们给我一些指导，谢谢

**Comment by codgo** [comment]
gcode规范有问题, 这边应该 按照http的status 来.比如 查找ID为I 的数据, 成功以后   code 的0 应该是200 , code 65 应该是404 接口返回的http状态不应该是200- 应该是404

**Comment by codgo** [comment]
实际工作之中, nginx 的log 如果 api返回http头, 如果是200 状态, nginx log是记录不到的,

**Comment by houseme** [comment]
> 实际工作之中, nginx 的log 如果 api返回http头, 如果是200 状态, nginx log是记录不到的,

一个是业务的code一个是http的code，只要服务正常，业务逻辑异常还是返回正常的 `http`  `code` `200`，没必要业务逻辑查询不到某个信息，`http` 请求就返回 `404` 这样的服务找不到的信息

**Comment by Hao-Wu** [comment]
> gcode规范有问题, 这边应该 按照http的status 来.比如 查找ID为I 的数据, 成功以后 code 的0 应该是200 , code 65 应该是404 接口返回的http状态不应该是200- 应该是404

这是一个老生常谈的问题了，没有明确对错。但是在实际项目中，http状态码更多会被用于各种监控，如果依靠http里的404来表示业务逻辑里的not found，会在监控日志里留下大量异常，还是不推荐。

**Comment by gqcn** [comment]
@codgo 不好意思，来晚了。请升级使用最新版本。此外，这个状态码是可以自定义的。
