### ISSUE TITLE
gf gen dao 生成的文件与gf-demo-user 项目目录结构不一致

### ISSUE THREAD

**Issue by memtopia** [gogf/gf#1894]
### 1. What version of `Go` and system type/arch are you using?
go version go1.18.1 darwin/arm64

### 2. What version of `GoFrame` are you using?
2.0.4

### 3. Can this issue be re-produced with the latest release?
yes

### 4. What did you do?
执行 gf gen dao， 生成的文件与 gf-demo-user   项目目录结构不一致
 gf-demo-user  目录结构为
internal/model/entity/user.go
internal/service/internal/do/user.go
internal/service/internal/dao/user.go
internal/service/internal/dao/internal/user.go
部分文件在 service中， 而执行gf gen dao生成的文件不在 service/internal 中

### 6. What did you see instead?
$: gf gen dao

generated: internal/dao/internal/user.go
generated: internal/model/do/user.go
generated: internal/model/entity/user.go
done!

**Comment by houseme** [comment]
最新版本的gf生成的目录，`dao` 目录从 `service` 下移到项目目录，也可以自定义，`do` 目录移到了 `model` 目录
