### ISSUE TITLE
gf build：add -v value into BuildInfo

### ISSUE THREAD

**Issue by czhao0378** [gogf/gf#1896]
### 1. What version of `Go` and system type/arch are you using?
go version go1.18.2 windows/amd64

### 2. What version of `GoFrame` are you using?
GoFrame Version: v2.0.6 

### 5. What did you expect to see?
希望在gf build的时候，将 -v 参数的值 加入到 BuildInfo中
这样可以避免在项目中再去硬编码 二进制文件版本信息

**Comment by gqcn** [comment]
@czhao0378 可以考虑使用`-r`参数：
![image](https://user-images.githubusercontent.com/26347176/184893633-8ded75a9-8b8c-4153-b841-7383e89ec2dd.png)
