### ISSUE TITLE
v2.1.0 需要手工引数据库驱动

### ISSUE THREAD

**Issue by larryclean** [gogf/gf#1898]
gf升级为v2.1.0-rc4后需要手工引入数据库驱动

### 1. What version of `Go` and system type/arch are you using?
go 1.17

### 2. What version of `GoFrame` are you using?
v2.1.0-rc4

### 4. What did you do?
，请问这个就是这个设计了还是后续会增加

**Comment by mingzaily** [comment]
已经改成这个设计了，具体看文档

https://goframe.org/pages/viewpage.action?pageId=1114686#id-%E6%95%B0%E6%8D%AE%E5%BA%93ORM-%E9%A9%B1%E5%8A%A8%E5%BC%95%E5%85%A5

**Comment by larryclean** [comment]
感谢，我就是确认一下。
