### ISSUE TITLE
gqueue性能问题咨询

### ISSUE THREAD

**Issue by foxhack** [gogf/gf#190]
最近在使用gf的gqueue的时候，使用日志打点发现gqueue的性能似乎不太稳定，在我理解应该都是毫秒以下的处理，但是实际抖动延时很大，最大的时候达到了140ms，具体如下图描述，是否在使用上存在有什么不对的地方么。
golang 版本   go version go1.11.4 GOOS=linux AMD64
gf 版本            v1.6.17

[
![TIM截图20190616163435](https://user-images.githubusercontent.com/16910405/59580470-d53d3b00-9103-11e9-82bf-a60bdf1bb3e1.png)
](url)

**Comment by johngcn** [comment]
@foxhack 这个抖动确实有点大，你往`queue`里面放置的数据量有多少？最大值？

**Comment by foxhack** [comment]
> 
> 
> @foxhack 这个抖动确实有点大，你往`queue`里面放置的数据量有多少？最大值？

没有设置limit，是默认大小，这些数据都是实时产生的，数据的长度固定最大可能有1m+ 最小600

**Comment by johngcn** [comment]
@foxhack 嗯，`1m+`有点多，有可能是数据同步那块的内存分配造成的。正好我这两天在优化`gqueue`这块，预计今晚或者最晚明天发布一个新版本，到时你再试试。

**Comment by foxhack** [comment]
好的，新版出了我测试一下，到时给你反馈

**Comment by johngcn** [comment]
@foxhack 你可以通过`go clean -modcache`清空本地缓存后，使用`test`版本试试，这个是未正式发布前的测试版本

**Comment by johngcn** [comment]
@foxhack 你好，请更新到最新的`v1.7.1`版本再试。

**Comment by johngcn** [comment]
@foxhack 请确认是否还有问题，若无问题可关闭该`issue`。

**Comment by foxhack** [comment]
目前还在跑，我看是通过gDEFAULT_MAX_BATCH_SIZE来控制，这个值后期会设置成可控制么

**Comment by johngcn** [comment]
@foxhack 当前默认的`gDEFAULT_MAX_BATCH_SIZE`为`10`是一个相对比较折中的值，为简化使用复杂度，不建议暴露给开发者。

**Comment by foxhack** [comment]
好的，可以现关闭了。我等过段时间进行大数据量测试跑跑测试结果，看看和直接的channel的差异在哪里

**Comment by johngcn** [comment]
@foxhack 好的，有什么问题欢迎随时反馈。
