### ISSUE TITLE
Using gjson.set method is weird

### ISSUE THREAD

**Issue by wilsonliu123** [gogf/gf#1906]
### 1. What version of `Go` and system type/arch are you using?  

╰─$ go version
go version go1.18 darwin/arm64

### 2. What version of `GoFrame` are you using?

─$ gf -v
GoFrame CLI Tool v2.1.0-rc4, https://goframe.org
GoFrame Version: cannot find goframe requirement in go.mod
CLI Installed At: /Users/wilson/go/bin/gf
CLI Built Detail:
  Go Version:  go1.17.10
  GF Version:  v2.1.0-rc4
  Git Commit:  2022-06-01 16:36:40 0639becccc486fda179b81e7a685f67c91b173a4
  Build Time:  2022-06-01 16:34:52

### 3. Can this issue be re-produced with the latest release?

 yes 

### 4. What did you do?

<img width="669" alt="image" src="https://user-images.githubusercontent.com/11918825/173288245-e8f7870d-c73c-4347-9765-d98b89323229.png">

### 5. What did you expect to see?

<img width="441" alt="image" src="https://user-images.githubusercontent.com/11918825/173288293-4498de3f-b616-4a7a-ac2c-e304a16462e3.png">

### 6. What did you see instead?

<img width="509" alt="image" src="https://user-images.githubusercontent.com/11918825/173288334-5585f52a-2807-4802-8dab-bc29e12c1753.png">

**Comment by wilsonliu123** [comment]
gf v1.16 .x  is  normal ,but v2.0 is wired

**Comment by wilsonliu123** [comment]
<img width="806" alt="image" src="https://user-images.githubusercontent.com/11918825/173288619-5dc74483-c41f-444b-9089-e6a3dda2e0b8.png">
Problem is here ?

**Comment by wilsonliu123** [comment]
@gqcn   Has this issue been resolved?

**Comment by wilsonliu123** [comment]
Is this problem solved?

**Comment by gqcn** [comment]
@wilsonliu123 Sorry for late, the issue and me are both alive. I'm looking into it, it needs time.

**Comment by gqcn** [comment]
@wilsonliu123 Can you provides the source codes of the picture there.

**Comment by wilsonliu123** [comment]
hi , It's working fine. It should have been fixed
![image](https://user-images.githubusercontent.com/11918825/185540690-e5e7d5f7-9e53-4958-ae42-cdc0e2463462.png)
