### ISSUE TITLE
Post请求，Req结构字段定义`in:header`，仍会出现在body中，导致swagger或redoc出现两个相同字段

### ISSUE THREAD

**Issue by mingzaily** [gogf/gf#1912]
### 1. What version of `Go` and system type/arch are you using?

go 1.17, mac

### 2. What version of `GoFrame` are you using?

v2.1.0-rc4

### 3. Can this issue be re-produced with the latest release?

yes

##### define
```
type GetUserReq struct {
	g.Meta `path:"/user" tags:"User" method:"post" sm:"获取用户信息"`
	Token  string `json:"token" v:"required" dc:"用户token" in:"header"`
	UserId int    `json:"user_id" v:"required" dc:"用户ID"`
}

type GetUserRes struct{}
```

#####  open /swagger

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/44798713/173984555-b7e91630-886e-44dc-8b2e-79e3451fb9d4.png">

##### open /api.json

<img width="1055" alt="image" src="https://user-images.githubusercontent.com/44798713/173984833-c28e70c1-d872-4873-b70b-519a5a7e1735.png">

### 5. What did you expect to see?

header param not in request body

### 6. What did you see instead?

header param in request body

**Comment by houseme** [comment]
建议升级版本使用
