### ISSUE TITLE
api请求参数使用p标签重命名请求参数,生成的swagger还是使用变量名为参数

### ISSUE THREAD

**Issue by xushushun** [gogf/gf#1914]
```go
type HelloReq struct {
	g.Meta `path:"/hello" tags:"Hello" method:"get" summary:"我的哈喽api"`
	Name   string
	Pwd    string `p:"pw" v:"required|length:6,30#请输入密码|密码长度不够"`
}
```
例如这个 生成的api文档参数 用的是pwd  而实际参数应该是 pw才对

**Comment by mingzaily** [comment]
swagger生成不根据p标签，p标签主要用于请求转Req，具体请看，swagger主要还是依赖json标签

[GoFrame的struct tag(标签) 有哪些？](https://goframe.org/pages/viewpage.action?pageId=7296348#FAQ%EF%BC%88%E7%A4%BE%E5%8C%BA%E5%85%B1%E5%BB%BA%EF%BC%89-4%E3%80%81GoFrame%E7%9A%84structtag(%E6%A0%87%E7%AD%BE)%E6%9C%89%E5%93%AA%E4%BA%9B%EF%BC%9F)

**Comment by xushushun** [comment]
我感觉根据目前实际情况既然api的 req里面允许使用p标签,并且程序实际也是接收p标签的参数来转化到字段,swagger应该生成的是p标签里面的参数.

**Comment by gqcn** [comment]
@xushushun 按理说`p`标签应该也是支持的，莫方，我瞅瞅。
