### ISSUE TITLE
模板引擎-模板文件后缀，必须跟 define template 的文件后缀保持一致

### ISSUE THREAD

**Issue by sanrentai** [gogf/gf#1917]
### 1. What version of `Go` and system type/arch are you using?
go1.17.1 windows/amd64

### 2. What version of `GoFrame` are you using?
2.0.6

### 3. Can this issue be re-produced with the latest release?

yes

### 4. What did you do?
(https://goframe.org/pages/viewpage.action?pageId=1114280)
把 layout.html 改成 layout.tpl 后会报错。

### 5. What did you expect to see?

如果是bug 希望做个修复
否则，希望官网能针对该限制增加一个说明

**Comment by codgo** [comment]
我这里没报错, 他意思是, 比如你 有个文件叫news_content.tpl  你 define 得是 ${define "news_content"}

**Comment by sanrentai** [comment]
layout.html 这个文件改成 layout.tpl，但header.html 不做任何改变，那么就会报错。

**Comment by gqcn** [comment]
@sanrentai 模板文件 和 `define template` 的文件后缀必须保持一致的
