### ISSUE TITLE
关于2.0规范路由后中间件和路由组的问题

### ISSUE THREAD

**Issue by moipa-cn** [gogf/gf#1920]
2.0使用了规范路由的写法，但我翻遍了文档，貌似关于中间件和路由组的写法还是保持着1.X的样子。（或者是我遗漏了这方面的文档）
对于规范路由后想使用中间件和路由组，我该怎么做？

**Comment by moipa-cn** [comment]
> 不知道你要的是不是这个：https://goframe.org/pages/viewpage.action?pageId=30736904
> 
> ```go
> s := g.Server()
> 	s.Group("/api.v2", func(group *ghttp.RouterGroup) {
> 		group.Middleware(MiddlewareCORS)
>                 group.Bind(
>                   new(Hello),
>                 )
> 	})
> ```

这个我看了，感觉这样比较麻烦，不太好管理。
目前遇到的问题是：
1、路由组太多的时候，路由组下面绑定的路由过多，都写到一起，代码太长，不好管理。如果分几个文件分别管理路由组，后续有人来接手项目的时候成本又太高。而且会有2的问题。
2、A路由组下面的方法，如果因为某些原因要换到B组路由下，那么要改的东西太多，不太方便，容易漏掉某些地方，尤其对于新接手项目的同学，对整体代码还不是非常熟悉的时候。
我看gf2.0有规范路由的写法，我觉得蛮直观的，对于团队项目沟通也方便，但是在文档中没有看到对应的规范路由组的写法，对于这方面的改动是否有计划？

**Comment by gqcn** [comment]
> 

能举例阐述吗？

**Comment by gqcn** [comment]
> > 不知道你要的是不是这个：https://goframe.org/pages/viewpage.action?pageId=30736904
> > ```go
> > s := g.Server()
> > 	s.Group("/api.v2", func(group *ghttp.RouterGroup) {
> > 		group.Middleware(MiddlewareCORS)
> >                 group.Bind(
> >                   new(Hello),
> >                 )
> > 	})
> > ```
> 
> 这个我看了，感觉这样比较麻烦，不太好管理。 目前遇到的问题是： 1、路由组太多的时候，路由组下面绑定的路由过多，都写到一起，代码太长，不好管理。如果分几个文件分别管理路由组，后续有人来接手项目的时候成本又太高。而且会有2的问题。 2、A路由组下面的方法，如果因为某些原因要换到B组路由下，那么要改的东西太多，不太方便，容易漏掉某些地方，尤其对于新接手项目的同学，对整体代码还不是非常熟悉的时候。 我看gf2.0有规范路由的写法，我觉得蛮直观的，对于团队项目沟通也方便，但是在文档中没有看到对应的规范路由组的写法，对于这方面的改动是否有计划？

能举例阐述吗？
