### ISSUE TITLE
一直没有搞明白每次在使用最新版本的 cli时 ，linux的应该选择哪个呢？

### ISSUE THREAD

**Issue by 1211ciel** [gogf/gf#1924]
这是我的系统信息： Linux howls 5.15.0-39-generic #42-Ubuntu SMP Thu Jun 9 23:42:32 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

[gf_linux_386](https://github.com/gogf/gf/releases/download/v2.1.0/gf_linux_386)
16.1 MB
13 hours ago
[gf_linux_amd64](https://github.com/gogf/gf/releases/download/v2.1.0/gf_linux_amd64)
18.1 MB
13 hours ago
[gf_linux_arm](https://github.com/gogf/gf/releases/download/v2.1.0/gf_linux_arm)
15.9 MB
13 hours ago
[gf_linux_arm64](https://github.com/gogf/gf/releases/download/v2.1.0/gf_linux_arm64)
17.5 MB
13 hours ago
[gf_linux_mips](https://github.com/gogf/gf/releases/download/v2.1.0/gf_linux_mips)
17.4 MB
13 hours ago
[gf_linux_mips64](https://github.com/gogf/gf/releases/download/v2.1.0/gf_linux_mips64)
18.7 MB
13 hours ago
[gf_linux_mips64le](https://github.com/gogf/gf/releases/download/v2.1.0/gf_linux_mips64le)
18.6 MB
13 hours ago
[gf_linux_mipsle](https://github.com/gogf/gf/releases/download/v2.1.0/gf_linux_mipsle)
17.3 MB
13 hours ago
[gf_linux_ppc64](https://github.com/gogf/gf/releases/download/v2.1.0/gf_linux_ppc64)
17.7 MB
13 hours ago
[gf_linux_ppc64le](https://github.com/gogf/gf/releases/download/v2.1.0/gf_linux_ppc64le)

请问应该选择哪个呢？

**Comment by codgo** [comment]
13 hours ago
[gf_linux_amd64](https://github.com/gogf/gf/releases/download/v2.1.0/gf_linux_amd64)吧

**Comment by hailaz** [comment]
如果装了go的话，很简单，go env
go env GOOS
go env GOARCH

或者直接装
```shell
wget -O gf https://github.com/gogf/gf/releases/latest/download/gf_$(go env GOOS)_$(go env GOARCH) && chmod +x gf && ./gf install -y && rm ./gf
```

----
题外：
go tool dist list

GOOS：目标平台的操作系统（darwin、freebsd、linux、windows）
GOARCH：目标平台的体系架构（386、amd64、arm）

**Comment by 1211ciel** [comment]
➜  ~ go env GOARCH
amd64

谢谢，知道了。
