### ISSUE TITLE
gtime.SetTimeZone fails to work normally

### ISSUE THREAD

**Issue by WillHu** [gogf/gf#1931]
### 1. What version of `Go` and system type/arch are you using?

go1.18.2 darwin/amd64

### 2. What version of `GoFrame` are you using?

v2.1.0-rc4

### 3. Can this issue be re-produced with the latest release?
Yes

### 4. What did you do?

func TestTime(t *testing.T) {
	gtime.SetTimeZone("Asia/Shanghai")
	fmt.Println(gtime.Datetime())
	fmt.Println(gtime.Now())

	gtime.SetTimeZone("Asia/Tokyo")
	fmt.Println(gtime.Datetime())
	// May Output:
	// 2018-08-08 08:08:08
	// 2018-08-08 08:08:08
	// 2018-08-08 09:08:08
}

### 5. What did you expect to see?
2022-06-23 11:05:43
2022-06-23 11:05:43
2022-06-23 12:05:43

### 6. What did you see instead?
2022-06-23 11:05:43
2022-06-23 11:05:43
2022-06-23 11:05:43

**Comment by gqcn** [comment]
@WillHu https://goframe.org/pages/viewpage.action?pageId=1114268
![image](https://user-images.githubusercontent.com/26347176/175313118-7ad3f391-5c70-423a-959b-be6401be79e6.png)
