### ISSUE TITLE
go gen dao 不能正常工作

### ISSUE THREAD

**Issue by sersoong** [gogf/gf#1939]
### 1. What version of `Go` and system type/arch are you using?
go version go1.18.3 windows/amd64

### 2. What version of `GoFrame` are you using?
v2.0.4

### 3. Can this issue be re-produced with the latest release?
None

#### 配置好mysql数据库，运行gf gen dao，当数据库的表名称中包含` "."点符号`，则运行出错，报错信息如下：
出问题的表名称为：cap.published
现有场景是不允许修改表名称

fetching tables fields failed for table "cap.published": Error 1049: Unknown database 'cap', SHOW FULL COLUMNS FROM cap.published

1. Error 1049: Unknown database 'cap', SHOW FULL COLUMNS FROM cap.published

   1).  github.com/gogf/gf/v2/database/gdb.(*Core).DoCommit
        /home/runner/work/gf/gf/database/gdb/gdb_core_underlying.go:267
   2).  github.com/gogf/gf/v2/database/gdb.(*Core).DoQuery
        /home/runner/work/gf/gf/database/gdb/gdb_core_underlying.go:63
   3).  github.com/gogf/gf/v2/database/gdb.(*Core).DoSelect
        /home/runner/work/gf/gf/database/gdb/gdb_core.go:155
   4).  github.com/gogf/gf/contrib/drivers/mysql/v2.(*DriverMysql).TableFields.func1
        /home/runner/work/gf/gf/contrib/drivers/mysql/mysql.go:170
   5).  github.com/gogf/gf/v2/container/gmap.(*AnyAnyMap).doSetWithLockCheck
        /home/runner/work/gf/gf/container/gmap/gmap_hash_any_any_map.go:220
   6).  github.com/gogf/gf/v2/container/gmap.(*AnyAnyMap).GetOrSetFuncLock
        /home/runner/work/gf/gf/container/gmap/gmap_hash_any_any_map.go:257
   7).  github.com/gogf/gf/contrib/drivers/mysql/v2.(*DriverMysql).TableFields
        /home/runner/work/gf/gf/contrib/drivers/mysql/mysql.go:160
   8).  github.com/gogf/gf/cmd/gf/v2/internal/cmd.generateDao
        /home/runner/work/gf/gf/cmd/gf/internal/cmd/cmd_gen_dao.go:299
   9).  github.com/gogf/gf/cmd/gf/v2/internal/cmd.doGenDaoForArray
        /home/runner/work/gf/gf/cmd/gf/internal/cmd/cmd_gen_dao.go:277
   10). github.com/gogf/gf/cmd/gf/v2/internal/cmd.cGen.Dao
        /home/runner/work/gf/gf/cmd/gf/internal/cmd/cmd_gen_dao.go:178
   11). github.com/gogf/gf/v2/os/gcmd.newCommandFromMethod.func1
        /home/runner/work/gf/gf/os/gcmd/gcmd_command_object.go:315
   12). github.com/gogf/gf/v2/os/gcmd.(*Command).doRun
        /home/runner/work/gf/gf/os/gcmd/gcmd_command_run.go:120
   13). github.com/gogf/gf/v2/os/gcmd.(*Command).RunWithValueError
        /home/runner/work/gf/gf/os/gcmd/gcmd_command_run.go:77
   14). github.com/gogf/gf/v2/os/gcmd.(*Command).RunWithValue
        /home/runner/work/gf/gf/os/gcmd/gcmd_command_run.go:32
   15). github.com/gogf/gf/v2/os/gcmd.(*Command).Run
        /home/runner/work/gf/gf/os/gcmd/gcmd_command_run.go:26
   16). main.main
        /home/runner/work/gf/gf/cmd/gf/main.go:69

### 5. What did you expect to see?
运行gf gen dao时能正确处理表名称中包含“.”点符号的情形。

### 6. What did you see instead?
None

**Comment by DGuang21** [comment]
`fetching tables fields failed for table "cap.published": Error 1049: Unknown database 'cap', SHOW FULL COLUMNS FROM cap.published`

这个错误是在告诉你，当前连接找不到名为cap的database，你可以尝试将语句`SHOW FULL COLUMNS FROM cap.published`单独执行能否成功。

如果能成功，请检查一下配置文件中的数据库配置是否有效

**Comment by houseme** [comment]
> > `fetching tables fields failed for table "cap.published": Error 1049: Unknown database 'cap', SHOW FULL COLUMNS FROM cap.published`
> > 这个错误是在告诉你，当前连接找不到名为cap的database，你可以尝试将语句`SHOW FULL COLUMNS FROM cap.published`单独执行能否成功。
> > 如果能成功，请检查一下配置文件中的数据库配置是否有效
> 
> 能成功，并且数据库配置正确有效，这个问题是`gf中database\gdb\gdb_func.go`文件中66行：quoteWordReg = regexp.MustCompile(`^[a-zA-Z0-9\-_]+$`)没有匹配 **.** 点号导致的，我不确定修改后会否对其他功能造成影响，所以我就没提这个PR。 目前临时解决方案是：clone一个gf仓库到本地，修改上面说的文件的66行为quoteWordReg = regexp.MustCompile(`^[a-zA-Z0-9\-\._]+$`)。编译出一个单独的gf程序运行gf gen dao就能正确生成。

这样设置表名的出发点是什么呢？改完之后，其他运行正常吗？

**Comment by sersoong** [comment]
> > > `fetching tables fields failed for table "cap.published": Error 1049: Unknown database 'cap', SHOW FULL COLUMNS FROM cap.published`
> > > 这个错误是在告诉你，当前连接找不到名为cap的database，你可以尝试将语句`SHOW FULL COLUMNS FROM cap.published`单独执行能否成功。
> > > 如果能成功，请检查一下配置文件中的数据库配置是否有效
> > 
> > 
> > 能成功，并且数据库配置正确有效，这个问题是`gf中database\gdb\gdb_func.go`文件中66行：quoteWordReg = regexp.MustCompile(`^[a-zA-Z0-9\-_]+$`)没有匹配 **.** 点号导致的，我不确定修改后会否对其他功能造成影响，所以我就没提这个PR。 目前临时解决方案是：clone一个gf仓库到本地，修改上面说的文件的66行为quoteWordReg = regexp.MustCompile(`^[a-zA-Z0-9\-\._]+$`)。编译出一个单独的gf程序运行gf gen dao就能正确生成。
> 
> 这样设置表名的出发点是什么呢？改完之后，其他运行正常吗？

我也不知道这个出发点是啥，但在实际业务场景中，我这边有个第三方公司开发的系统，就是这样命名。其他功能目前暂时未发现异常。

**Comment by houseme** [comment]
> > > > `fetching tables fields failed for table "cap.published": Error 1049: Unknown database 'cap', SHOW FULL COLUMNS FROM cap.published`
> > > > 这个错误是在告诉你，当前连接找不到名为cap的database，你可以尝试将语句`SHOW FULL COLUMNS FROM cap.published`单独执行能否成功。
> > > > 如果能成功，请检查一下配置文件中的数据库配置是否有效
> > > 
> > > 
> > > 能成功，并且数据库配置正确有效，这个问题是`gf中database\gdb\gdb_func.go`文件中66行：quoteWordReg = regexp.MustCompile(`^[a-zA-Z0-9\-_]+$`)没有匹配 **.** 点号导致的，我不确定修改后会否对其他功能造成影响，所以我就没提这个PR。 目前临时解决方案是：clone一个gf仓库到本地，修改上面说的文件的66行为quoteWordReg = regexp.MustCompile(`^[a-zA-Z0-9\-\._]+$`)。编译出一个单独的gf程序运行gf gen dao就能正确生成。
> > 
> > 
> > 这样设置表名的出发点是什么呢？改完之后，其他运行正常吗？
> 
> 我也不知道这个出发点是啥，但在实际业务场景中，我这边有个第三方公司开发的系统，就是这样命名。其他功能目前暂时未发现异常。

是不是原来用的是postgrsql

**Comment by sersoong** [comment]
并不是
