### ISSUE TITLE
[bug]gcmd parse args abnormal

### ISSUE THREAD

**Issue by lgcgo** [gogf/gf#1941]
The following three different command args option
```shell
$ gf -v
GoFrame CLI Tool v2.1.0, https://goframe.org
...
$ gf -vvv
GoFrame CLI Tool v2.1.0, https://goframe.org
...
$ gf -vfdsfsdfsd
USAGE
    gf COMMAND [OPTION]
```
Obviously, "-vvv" is a non-existent option

**Comment by gqcn** [comment]
@lgcgo The command manager parses the arguments in loose mode ind default , which means it does not treat none support arguments as an operation error. More details please refer: https://goframe.org/pages/viewpage.action?pageId=35357529
![image](https://user-images.githubusercontent.com/26347176/195084120-447a40e7-4ba8-4228-889b-92c7de2ff160.png)
