### ISSUE TITLE
关于gf v2.1.1中的gf gen service的建议

### ISSUE THREAD

**Issue by Tiller-Mu** [gogf/gf#1942]
在gf gen service的文档中指出：不同业务模块中定义的结构体名称在生成的service接口名称时可能会重复覆盖，因此需要在设计业务模块时保证名称不能冲突。
这里在生成的service接口文件时，能否把包名作为前缀加入到接口定义中。例如如下两个包定一个服务端结构体：
package user
type sInfo struct{}
type sAddr() struct{}

package customer
type sInfo struct{}
type sAddr struct{}
--------------------------------
在生成service接口时，类似如下：
type IUserAddr interface {
	List(ctx context.Context, in model.CardAddrListInput) (out *model.CardAddrListOutput, err error)
	Confirm(ctx context.Context, in model.CardAddrConfirmInput) (out *model.CardAddrConfirmOutput, err error)
}
type IUserInfo interface {}
type ICustomerInfo interface{}
type ICustomerAddr interface{}

这样应该可以降低对于logic下各包的命名的规范困难。同时也避免了在logic下面的各个包里面，goland产生的“Name starts with the package name”提示

**Comment by gqcn** [comment]
@Tiller-Mu 感谢您的建议！当出现接口命名冲突的时候，这确实是一种解决办法。最新版本的`v2.2.0`开始，`CLI`将会按照`logic`下的业务模块包名生成对应的接口`go`文件，开发者可以通过`logic`中的接口方法返回二级业务模块的接口，聚合更清晰，使用更简便。至于二级拆分的业务模块，你可以按照接口管理，也可以直接返回内部的`struct`。像这样：
![image](https://user-images.githubusercontent.com/26347176/195085047-36d04fd4-80fd-4549-990c-d3ba62cdf0ba.png)
![image](https://user-images.githubusercontent.com/26347176/195085215-51551e61-b8cc-476c-873a-9995878a0832.png)
