### ISSUE TITLE
[BUG]cli v2.1.1 gf gen service 的问题

### ISSUE THREAD

**Issue by Tiller-Mu** [gogf/gf#1943]
![image](https://user-images.githubusercontent.com/60461226/175815664-fe97af86-9340-43c8-b47e-ef8379bff9ec.png)
当logic代码完成，并完成service接口注册代码后，若删除之前自动生成的service接口文件，重新执行gf gen service，会导致service接口定义文件import service包，导致循环依赖。此时需要逐个文件删除该import。

**Comment by hamster1963** [comment]
可以尝试一下使用goimports解决？

**Comment by Tiller-Mu** [comment]
有使用go import插件，不能自动解决
