### ISSUE TITLE
2.1版本 server 的logger段配置问题

### ISSUE THREAD

**Issue by stevenyangecho** [gogf/gf#1946]
### 1. What version of `Go` and system type/arch are you using?
go version go1.18 windows/amd64

### 2. What version of `GoFrame` are you using?
CLI Built Detail:
  Go Version:  go1.17.11
  GF Version:  v2.1.0
  Git Commit:  2022-06-21 21:52:54 3b9e5c71bfd9f19e53dc4754e2170df1c534f0bb
  Build Time:  2022-06-21 22:04:44

[https://goframe.org/pages/viewpage.action?pageId=44449484](url)
有一个关于服务端logger的配置
我在本地 配置

> [server]
address = ":800"
httpsAddr = ":443"
HTTPSCertPath = "server.crt"
HTTPSKeyPath = "server.key"
openapiPath = "/api.json"
swaggerPath = "/swagger"
logpath = "logs/server"   # 日志文件路径。默认为空，表示关闭，仅输出到终端
logstdout = true          # 日志是否同时输出到终端。默认true
errorLogEnabled = true
errorStack = true
errorLogPattern = "error.{Ymd}.log"
accessLogEnabled = true
accessLogPattern = "access.{Ymd}.log"
[server.logger]
path= "logs/server"
prefix = ""            # 日志内容输出前缀。默认为空
file=                "{Y-m-d}.log"
level = "all"         # 日志输出级别
ctxKeys = []            # 自定义Context上下文变量名称，自动打印Context的变量到日志中。默认为空
rotateSize = 0             # 按照日志文件大小对文件进行滚动切分。默认为0，表示关闭滚动切分特性
rotateExpire = "7d"             # 按照日志文件时间间隔对文件滚动切分。默认为0，表示关闭滚动切分特性
rotateBackupLimit = 0             # 按照切分的文件数量清理切分文件，当滚动切分特性开启时有效。默认为0，表示不备份，切分则删除
rotateBackupExpire = "7d"             # 按照切分的文件有效期清理切分文件，当滚动切分特性开启时有效。默认为0，表示不备份，切分则删除
rotateBackupCompress = 0             # 滚动切分文件的压缩比（0-9）。默认为0，表示不压缩
rotateCheckInterval = "5s"          # 滚动切分的时间检测间隔，一般不需要设置。默认为1小时
stdoutColorDisabled = false         # 关闭终端的颜色打印。默认开启
writerColorEnable = false         # 日志文件是否带上颜色。默认false，表示不带颜色

build 运行 后会报错

> 2022-06-27 13:54:01.963 [FATA] {c87f03e57a64fc162ff14002b0c53cf2} exception recovered: runtime error: invalid memory address or nil pointer dereference
1. exception recovered: runtime error: invalid memory address or nil pointer dereference

debug调试代码 发现 
https://github.com/gogf/gf/blob/f57d71b6fa363dc1766228e9e7895427bdae1973/frame/gins/gins_server.go#L70

这一行覆盖了 server 的config字段,导致 server.config.Logger.init 为nil. 从而导致程序出错

**问题二**

> path= "logs/server"
prefix = ""            # 日志内容输出前缀。默认为空
file=                "{Y-m-d}.log"

这些字段似乎和 server 本身的

> logpath = "logs/server"   # 日志文件路径。默认为空，表示关闭，仅输出到终端
logstdout = true          # 日志是否同时输出到终端。默认true
errorLogEnabled = true
errorLogPattern = "error.{Ymd}.log"
accessLogEnabled = true
accessLogPattern = "access.{Ymd}.log"

有重复?冲突? 有没有详细一点的解释呢

**Comment by glennliao** [comment]
遇到了相同的问题，请问后续有如何处理吗

**Comment by gqcn** [comment]
@stevenyangecho @glennliao 不好意思我来晚了，我初步`check`了一下，是一个`BUG`，我优先修复一下，请骚等。
