### ISSUE TITLE
建议 glog 错误等级日志用颜色区分一下

### ISSUE THREAD

**Issue by skiy** [gogf/gf#196]
建议 glog 参考 beego ，错误等级日志用颜色区分一下。
这样方便查看日志记录。

**Comment by vmvz** [comment]
我也希望能够支持颜色区分

https://github.com/sirupsen/logrus (Go)
https://github.com/Delgan/loguru (Python)

都是支持日志颜色

**Comment by gqcn** [comment]
并不是优先级高的功能，感兴趣的小伙可以提`pr`，不着急则排期处理。

**Comment by ttcc** [comment]
@gqcn 能否举个例子,我来参考loguru来完善.

**Comment by gqcn** [comment]
> @gqcn 能否举个例子, 我来pr, 参考loguru来完善.

其实比较简单，只是没太大必要。颜色功能只能终端输出才有效，千万别输出到日志文件中。你可以自行先研究一下。

**Comment by skiy** [comment]
> @gqcn 能否举个例子, 我来pr, 参考loguru来完善.

logrus 的也不太好用。只能显示在终端，且只支持 text 格式，不支持 JSON 格式的。
不是硬需求，就是调试和排查问题的时候方便些而已。
