### ISSUE TITLE
gf与gmap冲突导致的mysql driver找不到

### ISSUE THREAD

**Issue by wuyuzhe** [gogf/gf#1961]
### 1. What version of `Go` and system type/arch are you using?
go1.18

### 2. What version of `GoFrame` are you using?
gf2.1.1

### 4. What did you do?
```
import (
	"context"
	"math/rand"
	"medlive_career/apiv1"

	"github.com/gogf/gf/container/gmap"
	"github.com/gogf/gf/v2/frame/g"
)
```
在gf2.1.1中引入gmap时，gmap同时更新了gf达到1.16。gf/v2/frame/g 无法被引用，重新加载gf/v2。不报无法引用的错误。启动程序，请求报
```
 cannot find database driver for specified database type "mysql", did you misspell type name "mysql" or forget importing the database driver? possible reference: https://github.com/gogf/gf/tree/master/contrib/drivers
```

**Comment by wuyuzhe** [comment]
找到问题了，文档的问题，https://pkg.go.dev/github.com/gogf/gf@v1.16.9/container/gmap 这个地方的文档还是1.16版本的。

**Comment by houseme** [comment]
> ## gf与gmap冲突导致的mysql driver找不到
> ### 1. What version of `Go` and system type/arch are you using?
> go1.18
> 
> ### 2. What version of `GoFrame` are you using?
> gf2.1.1
> 
> ### 3. Can this issue be re-produced with the latest release?
> ### 4. What did you do?
> ```
> import (
> 	"context"
> 	"math/rand"
> 	"medlive_career/apiv1"
> 
> 	"github.com/gogf/gf/container/gmap"
> 	"github.com/gogf/gf/v2/frame/g"
> )
> ```
> 
> 在gf2.1.1中引入gmap时，gmap同时更新了gf达到1.16。gf/v2/frame/g 无法被引用，重新加载gf/v2。不报无法引用的错误。启动程序，请求报
> 
> ```
>  cannot find database driver for specified database type "mysql", did you misspell type name "mysql" or forget importing the database driver? possible reference: https://github.com/gogf/gf/tree/master/contrib/drivers
> ```

这个是俩个不同的gf版本。
