### ISSUE TITLE
希望能增加gRPC server的支持

### ISSUE THREAD

**Issue by ericzhao1979** [gogf/gf#1962]
GF是我见过的很好的集大成的框架，然而缺乏gRPC支持有点难受。
希望能支持

**Comment by houseme** [comment]
> GF是我见过的很好的集大成的框架，然而缺乏gRPC支持有点难受。 希望能支持

在这里 https://github.com/gogf/katyusha

**Comment by ljd1995** [comment]
> > GF是我见过的很好的集大成的框架，然而缺乏gRPC支持有点难受。 希望能支持
> 
> 在这里 https://github.com/gogf/katyusha

`katyusha`这个微服务框架一直在关注，但是一直都在WIP状态，请问`katyusha`有大概的发布时间不？

**Comment by gqcn** [comment]
> 

`katyusha`将会合并到框架中作为社区组件提供，名称将会调整为`grpcx`。预计框架`v2.3.0`版本开始发布。

**Comment by gqcn** [comment]
由于`v2.3`的改动较大，准备工作较多，因此拆分为两次版本，`grpcx`组件以及相关文档放到`v2.4`发布。
