### ISSUE TITLE
guuid废弃了吗？

### ISSUE THREAD

**Issue by sersoong** [gogf/gf#1964]
guuid在2.0里面废弃了吗？

**Comment by houseme** [comment]
https://github.com/gogf/guuid

**Comment by sersoong** [comment]
> https://github.com/gogf/guuid

thanks!

**Comment by houseme** [comment]
> > https://github.com/gogf/guuid
> 
> thanks!

更新了guuid的依赖包，`GoFrame`升级到了v2.1.1 和 `uuid` v1.3.0
