### ISSUE TITLE
GF2.1.0 From子查询 SHOW FULL COLUMNS FROM “ ”

### ISSUE THREAD

**Issue by glennliao** [gogf/gf#1965]
### 1. What version of `Go` and system type/arch are you using?

go 1.18 win/amd64
### 2. What version of `GoFrame` are you using?

2.1.0

### 3. Can this issue be re-produced with the latest release?
yes

### 4. What did you do?

![image](https://user-images.githubusercontent.com/14543369/177146503-f3c683ed-59d5-40d2-860c-327770a53f36.png)

just like the doc -> https://goframe.org/pages/viewpage.action?pageId=7302091

![image](https://user-images.githubusercontent.com/14543369/177146549-20c04ed3-38e0-43af-a19d-f4793bf12681.png)

### 6. What did you see instead?

![image](https://user-images.githubusercontent.com/14543369/177146724-a4e74201-6860-4933-9f5b-f9486946c8ab.png)

实际上sql还是正常执行了,

**Comment by mingzaily** [comment]
已复现，现象是否为报错但不中断流程？SQL正常执行，未返回error？

**Comment by glennliao** [comment]
@mingzaily 是的。

**Comment by glennliao** [comment]
@mingzaily 
刚又试了下, 现在又可以了。 然后新增了下字段，出现了新的问题。 问题依旧是`报错 + 不中断 + sql正常 + 未返回err`

```go

func TestName(t *testing.T) {

	type User struct {
		Id       string
		Username string
	}

	var users []User

	subSelect := g.DB().Model("sys_user").Fields("id", "username")

	err := g.DB().Model("? as u", subSelect).
		Where("id <", 18).
		Scan(&users)

	if err != nil {
		panic(err)
	}

	g.Dump(users)

}
```

![image](https://user-images.githubusercontent.com/14543369/177466898-d58b356a-0820-4208-ae14-3190d3aa9acf.png)

**Comment by melsendev** [comment]
It's running well when I'm using With of Model struct method expression.  this issue has been existing in the early GF version.
```
err := g.DB().Model("? as u", subSelect).With(User{})
		Where("id <", 18).
		Scan(&users)
```

**Comment by glennliao** [comment]
```go
package demo

import (
	_ "github.com/gogf/gf/contrib/drivers/mysql/v2"
	"github.com/gogf/gf/v2/frame/g"
	"testing"
)

type User struct {
	Username string
}

func TestName(t *testing.T) {
	db := g.DB()
	var users []User
	db.Model("? as u",
		db.Model("sys_user").Fields("username"),
	).Where("username", "admin").Scan(&users)
}

```
![image](https://user-images.githubusercontent.com/14543369/194685268-5de218cf-0292-430a-9b59-4fdb1d0a5045.png)
![image](https://user-images.githubusercontent.com/14543369/194685282-cda18a56-7c1a-4613-aca8-57885f270f2e.png)

**Comment by gqcn** [comment]
https://github.com/gogf/gf/pull/2177
