### ISSUE TITLE
OmitEmptyWhere 对 Wheref 失效

### ISSUE THREAD

**Issue by qq375251855** [gogf/gf#1969]
### 1. What version of `Go` and system type/arch are you using?

go1.18.3 windows/amd64

### 2. What version of `GoFrame` are you using?

v2.1.1

### 3. Can this issue be re-produced with the latest release?

yes

### 4. What did you do?

![image](https://user-images.githubusercontent.com/48313408/177276869-faae772f-724b-43d9-991e-1be0bfa96046.png)

### 5. What did you expect to see?

SELECT COUNT(1) FROM `xxxx` WHERE  `deleted_at` IS NULL

### 6. What did you see instead?

![image](https://user-images.githubusercontent.com/48313408/177277050-154bee05-5581-4da3-835e-12721b43647c.png)

**Comment by gqcn** [comment]
@qq375251855 是的，`Wheref`语句不会做`OmitEmpty`，因为那个`format`参数可能带有比较复杂的条件，很难过滤。不过滤才是严谨的做法。你可以自行加个`if`条件判断一下。
