### ISSUE TITLE
OmitEmptyWhere 对 Where.Builder 失效

### ISSUE THREAD

**Issue by qq375251855** [gogf/gf#1970]
### 1. What version of `Go` and system type/arch are you using?

go1.18.3 windows/amd64

### 2. What version of `GoFrame` are you using?

v2.1.1

### 3. Can this issue be re-produced with the latest release?

yes

### 4. What did you do?

![image](https://user-images.githubusercontent.com/48313408/177277717-79ab6b25-98f4-416e-8113-cbf986fe4301.png)

### 5. What did you expect to see?

SELECT COUNT(1) FROM `xxx` WHERE ((`xx`='')) AND `deleted_at` IS NULL

### 6. What did you see instead?

![image](https://user-images.githubusercontent.com/48313408/177277774-3a72afbe-371b-4841-9230-7b4015ba0ec0.png)

**Comment by gqcn** [comment]
@qq375251855 你好，`Builder`是一个独立的模块。不受外层`Model`的`OmitEmptyWhere`方法影响，你可以在创建`Buidler`的时候为`Builder`指定`OmitEmptyWhere`属性，例如：
```go
builder := db.Model(table).OmitEmptyWhere().Builder()
```
