### ISSUE TITLE
precision lost in data converting of ORM

### ISSUE THREAD

**Issue by hinego** [gogf/gf#2001]
以pgsql的decimal类型举例 被映射到了golang float64

但是golang 的float64是用8个字节来储存的（至多能精确表达 2 ** 64个数字）

而pgsql的decimal 是可变长的（可以表达的数字几乎不限量【小数点前 131072 位；小数点后 16383 位】）

float64至多能精确表达：18446744073709552000个数字

但是很明显decimal能表达的数字不止这么点。。。。

这明显不是计算时才有问题了

例如：数据库里面有一个大数：88888888888888888888888888888
但是用gf orm去取出来就变成了88888888888888900000000000000
再例如 api提交了一个大数：88888888888888888888888888888
但是保存到数据库里的就是88888888888888900000000000000了
详见：[https://www.runoob.com/postgresql/postgresql-data-type.html
](https://www.runoob.com/postgresql/postgresql-data-type.html)

解决方案：
1. 将decimal类型用golang的string类型承载（这是最轻松的方案）
2. 将decimal类型用 [https://github.com/shopspring/decimal](https://github.com/shopspring/decimal) 库的decimal 类型（可以直接内置到gf里面 新增一个类型 例如 g.decimal ）（希望的方案）
3.支持自定义类型来承载decimal （这么做的话也麻烦，因为gf gen dao 生成后还需要修改）

上面这个decimal 用于数据库时有点问题（我配合gorm使用时）

我自己做了一些修改在 https://github.com/hinego/decimal （可以参考一下我的修改）

**Comment by hinego** [comment]
`package main

import (
	"fmt"
	"unsafe"
)

func main() {
	var data float64 = 88888888888888888.8888
	fmt.Println(unsafe.Sizeof(data))
	//output: 8
}
`

**Comment by gqcn** [comment]
@hinego 你好，我们会在新版本使用`math/big.Int`来解决这个问题。

**Comment by gqcn** [comment]
https://github.com/shopspring/decimal 是个很不错的库，能否尽可能采用标准库来解决问题？比如使用`math/big`包？
