### ISSUE TITLE
gqueue.Queue.Close() is not threadsafe

### ISSUE THREAD

**Issue by xzzh999** [gogf/gf#2015]
### 1. What version of `Go` and system type/arch are you using?

1.18.3

### 2. What version of `GoFrame` are you using?

latest

### 3. Can this issue be re-produced with the latest release?
yes

### 4. What did you do?

call gqueue.Queue.Close() in 2 diffrent coroutines

### 5. What did you expect to see?
work fine

### 6. What did you see instead?
panic inside gqueue.Queue.Close(), the tips is `close of closed channel`

**Comment by gqcn** [comment]
I see, it seems that it has something to do here. It'd better using `CAS`.
<img width="752" alt="image" src="https://user-images.githubusercontent.com/26347176/213109441-367afa82-b8b0-4bd9-8615-9f45b3666411.png">
