### ISSUE TITLE
glog自定义writer的时候，message信息被重写问题

### ISSUE THREAD

**Issue by fanshu19** [gogf/gf#202]
非常感谢强哥新一版的glog解决了我发送graylog的需求。昨晚用了一下，发现有个问题，需求是这样的：我写日志的时候，想用graylog的gelf的http模式发送到graylog服务器上，按照文档上写的，很简单的时候了一个新的writer。但是实际测试发现graylog服务器没办法接收到信息，原因是发生的时候，这个报表文和我想要的格式不一样。
比如我定义一个message的struct结构，在glog上被重新定义成时间 + [info] + message的json格式，这个可以成功写入到本地的日志文件，但是另外发送的graylog的时候，报表文还是以glog那个string格式发送，而不是单一的message的json格式，导致graylog服务器不接受这种信息。

个人建议，writer重新定义的时候，用户定义传递的信息先不需要重写，重写交给重新定义的writer。

目前我才用自己封装方法的形式来处理了。

**Comment by fanshu19** [comment]
参照官方文档
定义graylog writer
`type GraylogWriter struct {
    Gelf   *gelf.Gelf
    Logger *glog.Logger
}

func (w *GraylogWriter) Write(p []byte) (n int, err error) {
    //w.Gelf.Send(p)
    w.Logger.Println(string(p))
    w.Gelf.Send(p)
    return w.Logger.Write(p)
}`

配置新的writer
`myLogWriter := &common.GraylogWriter{
		Logger: glog.New(),
		Gelf  : gelf.New(gelf.Config{
			GraylogPort     : c.GetInt("graylog.GraylogPort"),
			GraylogHostname : c.GetString("graylog.GraylogHostname"),
			//Connection      : c.GetString("graylog.Connection"),
			MaxChunkSizeWan : c.GetInt("graylog.MaxChunkSizeWan"),
			MaxChunkSizeLan : c.GetInt("graylog.MaxChunkSizeLan"),
		}),
	}
	//myLogWriter.Gelf.Log(`{"short_message":"Hello test e", "host":"example.org", "facility":"test", "_foo":"bar"}`)   //直接用第三方插件发送，可以发送成功
	myLogWriter.Logger.SetPath(logpath)
	myLogWriter.Logger.SetStdoutPrint(false)
	glog.SetWriter(myLogWriter)`

使用glog.Info写日志，这条能写入本地，但是不能发送到graylog服务器，而上面的那个直接用第三方插件的，可以发送成功
`glog.Info(`{"short_message":"Hello test e", "host":"example.org", "facility":"test", "_foo":"bar"}`)`

**Comment by johngcn** [comment]
@fanshu19 代码很乱，麻烦整理下

**Comment by johngcn** [comment]
@fanshu19 超过2个月没有活跃，关闭该issue，若有问题请reopen。
