### ISSUE TITLE
gf调用微服务

### ISSUE THREAD

**Issue by zhenhua1** [gogf/gf#2026]
请问如果gf做客户端是否可以调用go-zero的微服务，或者有没有小例子参考一下，使设计更符合gf风格

**Comment by gqcn** [comment]
@zhenhua1 `goframe`和`gozero`都是属于框架，微服务通信根据你选择的底层通信协议而异。以常见的`grpc`为例，只需要调用对应`proto`生成的客户端（有的框架需要配置注册发现），按照`rpc`方式调用对应方法即可。
