### ISSUE TITLE
how to get the value in req when type is in:header

### ISSUE THREAD

**Issue by zcyc** [gogf/gf#2036]
### 1. What version of `Go` and system type/arch are you using?

1.18.4

### 2. What version of `GoFrame` are you using?

2.1.2

### 3. Can this issue be re-produced with the latest release?
yes

### 4. What did you do?

i want to defind a header like `Authorization` in my `PasswordChangeReq` and valid it.
this is my PasswordChangeReq
```go
type PasswordChangeReq struct {
	g.Meta        `path:"/change" tags:"password" method:"post" summary:"change"`
	Authorization string `v:"required#Authorization is null" in:"header"`
	Password      string `json:"password" v:"required|length:8,32#password is null"`
}
```
can i get `Authorization` in my controller use req.Authorization
```go
func (c *cPassword) PasswordChange(ctx context.Context, req *v1.PasswordChangeReq) (res *v1.PasswordChangeRes, err error) {
	// how can i get the header in PasswordChangeReq
        // if can't get value, it is only show in openAPI, and i can't set valid for it
	g.Log().Info(ctx, req.Authorization)
	return
}
```

### 5. What did you expect to see?
```json
{
    "code": 51,
    "message": "Authorization is null",
    "data": null
}
```

### 6. What did you see instead?
```json
{
    "code": 0,
    "message": "",
    "data": null
}
```

**Comment by zcyc** [comment]
@gqcn

**Comment by oldme-git** [comment]
In my test, It can print header's value successfully. Gf Version: 2.6.2

**Comment by zcyc** [comment]
> In my test, It can print header's value successfully. Gf Version: 2.6.2

ok，i see the release.
