### ISSUE TITLE
gctx在ios跨平台上的bug

### ISSUE THREAD

**Issue by omegamt** [gogf/gf#2039]
### 1. What version of `Go` and system type/arch are you using?
go version go1.17.7 darwin/amd64

### 2. What version of `GoFrame` are you using?
GoFrame CLI Tool v2.1.2

gf通过gomobile编译成ios的framework供 xcode调用,有使用到 httpserver, gres,crypto 等模块
ios模拟器 通过✅
iphone真机release模式 通过✅
iphone真机debug模式  不通过❌  ,  gf v2.0.6时是没有问题的

```bash
//xcoder控制台错误反馈
panic: runtime error: slice bounds out of range [:-1]

goroutine 1 [running]:
github.com/gogf/gf/v2/os/gctx.init.0()
/var/folders/mh/0qjn57lx2kb_c6tc8y6_dkgc0000gp/T/gomobile-work-
2242032366/ios/pkg/mod/github.com/gogf/gf/v2@v2.1.2/os/gctx/gctx.go:36 +0x23c
dyld4 config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:
/Developer/usr/lib/libMainThreadChecker.dylib:
/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
```

找到gctx.go发现os.Environ()获取不到环境变量,或变量格式有问题的时候 出现了上面越界的情况
```go
func init() {
	// All environment key-value pairs.
	m := make(map[string]string)
	i := 0
	for _, s := range os.Environ() {
		i = strings.IndexByte(s, '=')
                 //添加以下判断后完美解决问题, os.Environ() 中有一行的值是 \371\246t\366\241!  显然不存在=号
+		if i == -1 {
+		    continue
+		}
		m[s[0:i]] = s[i+1:] //第36行
	}
	// OpenTelemetry from environments.
	processCtx = otel.GetTextMapPropagator().Extract(
		context.Background(),
		propagation.MapCarrier(m),
	)
}
```

go 的init函数 很多时候真是跨平台的大坑.

小bug就不提pr了, 麻烦gf团队有空修复一下.

**Comment by houseme** [comment]
> ### 1. What version of `Go` and system type/arch are you using?
> go version go1.17.7 darwin/amd64
> 
> ### 2. What version of `GoFrame` are you using?
> GoFrame CLI Tool v2.1.2
> 
> gf通过gomobile编译成ios的framework供 xcode调用,有使用到 httpserver, gres,crypto 等模块 ios模拟器 通过✅ iphone真机release模式 通过✅ iphone真机debug模式 不通过❌ , gf v2.0.6时是没有问题的
> 
> ```shell
> //xcoder控制台错误反馈
> panic: runtime error: slice bounds out of range [:-1]
> 
> goroutine 1 [running]:
> github.com/gogf/gf/v2/os/gctx.init.0()
> /var/folders/mh/0qjn57lx2kb_c6tc8y6_dkgc0000gp/T/gomobile-work-
> 2242032366/ios/pkg/mod/github.com/gogf/gf/v2@v2.1.2/os/gctx/gctx.go:36 +0x23c
> dyld4 config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:
> /Developer/usr/lib/libMainThreadChecker.dylib:
> /Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
> ```
> 
> 找到gctx.go发现os.Environ()获取不到环境变量,或变量格式有问题的时候 出现了上面越界的情况
> 
> ```go
> func init() {
> 	// All environment key-value pairs.
> 	m := make(map[string]string)
> 	i := 0
> 	for _, s := range os.Environ() {
> 		i = strings.IndexByte(s, '=')
>                  //添加以下判断后完美解决问题, os.Environ() 中有一行的值是 \371\246t\366\241!  显然不存在=号
> +		if i == -1 {
> +		    continue
> +		}
> 		m[s[0:i]] = s[i+1:] //第36行
> 	}
> 	// OpenTelemetry from environments.
> 	processCtx = otel.GetTextMapPropagator().Extract(
> 		context.Background(),
> 		propagation.MapCarrier(m),
> 	)
> }
> ```
> 
> go 的init函数 很多时候真是跨平台的大坑.
> 
> 小bug就不提pr了, 麻烦gf团队有空修复一下.

顺便就把PR提了吧，免费社区团队还要造环境来测试。

**Comment by omegamt** [comment]
@houseme  好的, 我没有进过团队, 业余受好者, 把问题想简单了

**Comment by gqcn** [comment]
@omegamt `IOS`平台上的`Env`如果不带有`=`符号的话，是什么样子的？
