### ISSUE TITLE
从2.0.3升级到2.1.2后，swagger文档地址无法访问的bug

### ISSUE THREAD

**Issue by linngc** [gogf/gf#2042]
### 1. What version of `Go` and system type/arch are you using?
go version go1.17.10 linux/amd64

### 2. What version of `GoFrame` are you using?

Ⅰ.开发环境：为无网络的环境，无法访问外网

Ⅱ.项目原先使用的gf是2.0.3版本，swagger文档地址能够正常访问 🆗
Ⅲ.后续升级为2.1.2版本后，swagger地址无法访问 ❌

Ⅳ.通过代码debugger发现，2.0.3版本引用的redoc.standalone.js文件为本地文件，2.1.2版本引用的文件则为unpkg.com网络下的文件，如果为内网环境，会导致因无法下载js时，而无法使用。

如果为公司内网无法上网的环境时，js无法下载<script src="https://unpkg.com/redoc@2.0.0-rc.70/bundles/redoc.standalone.js"> </script>，会出现该错误。

具体代码定位如下图
![gf-2 0 3](https://user-images.githubusercontent.com/48039456/182063564-066c3d2b-56a1-475c-9ed7-801734015dec.png)
![gf-2 1 12](https://user-images.githubusercontent.com/48039456/182063588-93bd36a9-ae77-448b-aa89-f79a91ee5091.png)

**Comment by gqcn** [comment]
@linngc 新版本已修改采用了内置UI的方式展示Swagger UI。当然如果你想要切换为外网访问也可以，具体请查看https://goframe.org/pages/viewpage.action?pageId=47703685
