### ISSUE TITLE
关于grpool的一些疑惑

### ISSUE THREAD

**Issue by hailaz** [gogf/gf#205]
1.没有limit的pool的Size函数返回会为负数（函数执行后）
size这个函数名感觉是pool大小，但其实返回的是当前运行数量，建议换个名字。

2.pool的limit无法读取。

3.pool被close后还能继续add。

4.pool的close状态无法读取。

5.函数不一致，底层是一致的。
```
func Jobs() int {
	return pool.list.Len()
}

func (p *Pool) Jobs() int {
	return p.list.Size()
}

```

**Comment by johngcn** [comment]
@hailaz 已改进。
