### ISSUE TITLE
How to develop the doquery method in callback processing on the ORM interface to obtain the request header information of the current request

### ISSUE THREAD

**Issue by FTLLOVE** [gogf/gf#2068]
### 1. What version of `Go` and system type/arch are you using?

go1.16

### 2. What version of `GoFrame` are you using?

goframe1.16.*
### 3. Can this issue be re-produced with the latest release?
no

### 4. What did you do?

func (d *MyDriver) DoQuery(ctx context.Context, link gdb.Link, sql string, args ...interface{}) (rows *sql.Rows, err error) {
 r.GetParam("")
}

### 5. What did you expect to see?
I want to get the information in the request header of the current request in the callback processing doquery method developed by the ORM interface, because I need to get the tenant in the current request header and then dynamically splice the SQL

**Comment by LonelySally** [comment]
将需要的信息注入到ctx中一路传递下来,在回调方法内取回即可.

**Comment by FTLLOVE** [comment]
> 将需要的信息注入到ctx中一路传递下来,在回调方法内取回即可.

I don't quite understand how this context passes values. Can you write some sample code for me?

**Comment by LonelySally** [comment]
> > 将需要的信息注入到ctx中一路传递下来,在回调方法内取回即可.
> 
> I don't quite understand how this context passes values. Can you write some sample code for me?

1. 假设auth/租户信息是在middleware解析出来的
2.

**Comment by FTLLOVE** [comment]
> > > 将需要的信息注入到ctx中一路传递下来,在回调方法内取回即可.
> > 
> > 
> > I don't quite understand how this context passes values. Can you write some sample code for me?
> 
> 假设auth/租户信息是在middleware解析出来的,调用r.SetCtxVar(租户标识key, 租户标识值).然后在ORM处显式调用.Ctx()方法将request的ctx传入进去.之后在自定义驱动处调用d.DriverMysql.GetCtx().Value(租户标识key)取回值即可.[d.DriverMysql为定义的实现接口struct名称]
this is auth middleware auth. insert tenant_id to context.
<img width="757" alt="38309a0e8ca553d713a2d6aade5fb1a" src="https://user-images.githubusercontent.com/22320062/184813553-e9ca2264-2e6e-4a5e-9599-a0a9aa6bcd49.png">
<img width="1278" alt="c88ce35dd7a73970d6773a1534be0d1" src="https://user-images.githubusercontent.com/22320062/184813713-61533c9f-5960-4b43-9010-7389c98e9664.png">
<img width="710" alt="2e5af2b9eefd1e00c9784ec7fc68eb5" src="https://user-images.githubusercontent.com/22320062/184813748-f9e3a600-3357-4339-99a8-3c6e7c54a3d3.png">
but,the result is nil. i don't quite understand "然后在ORM处显式调用.Ctx()方法将request的ctx传入进去" and [d.DriverMysql为定义的实现接口struct名称]".can you write some sample code for me ? i need you help

**Comment by LonelySally** [comment]
//middleware
func Auth(r *ghttp.Request) {
	r.SetCtxVar("tenant_id", guid.S())
}
//ORM
g.Model().Ctx(r.GetCtx()).All()
//driver
d.DriverMysql.GetCtx().Value("tenant_id")

**Comment by FTLLOVE** [comment]
Is there a better way, because if it passed to the context in ORM, I think it will violate the current code and can only use G.Model to pass the value. What I want is that in the middleware setting value, and get the value of the callback position.

**Comment by FTLLOVE** [comment]
> //middleware func Auth(r *ghttp.Request) { r.SetCtxVar("tenant_id", guid.S()) } //ORM g.Model().Ctx(r.GetCtx()).All() //driver d.DriverMysql.GetCtx().Value("tenant_id")

Is there a better way, because if it passed to the context in ORM, I think it will violate the current code and can only use G.Model to pass the value. What I want is that in the middleware setting value, and get the value of the callback position.

**Comment by FTLLOVE** [comment]
> //middleware func Auth(r *ghttp.Request) { r.SetCtxVar("tenant_id", guid.S()) } //ORM g.Model().Ctx(r.GetCtx()).All() //driver d.DriverMysql.GetCtx().Value("tenant_id")

Or is there a better way, add the Tenant_id field to the execution SQL

**Comment by LonelySally** [comment]
> > //middleware func Auth(r *ghttp.Request) { r.SetCtxVar("tenant_id", guid.S()) } //ORM g.Model().Ctx(r.GetCtx()).All() //driver d.DriverMysql.GetCtx().Value("tenant_id")
> 
> Is there a better way, because if it passed to the context in ORM, I think it will violate the current code and can only use G.Model to pass the value. What I want is that in the middleware setting value, and get the value of the callback position.

这就是规范(阅读v2版本源码会发现几乎所有方法第一个参数都是ctx).各组件解耦,通过上下文联系,链路追踪亦是如此.

**Comment by FTLLOVE** [comment]
> > > //middleware func Auth(r *ghttp.Request) { r.SetCtxVar("tenant_id", guid.S()) } //ORM g.Model().Ctx(r.GetCtx()).All() //driver d.DriverMysql.GetCtx().Value("tenant_id")
> > 
> > 
> > Is there a better way, because if it passed to the context in ORM, I think it will violate the current code and can only use G.Model to pass the value. What I want is that in the middleware setting value, and get the value of the callback position.
> 
> 这就是规范(阅读v2版本源码会发现几乎所有方法第一个参数都是ctx).各组件解耦,通过上下文联系,链路追踪亦是如此.

Yes, I know the V2 version understands the coupling of the component, so when I do the project, I still use the V1.16 version by default. In fact, I want to realize the https://gorm.io/zh_cn/hooks.html like gorm's ORM. But I haven't found a better way in Goframe until now

**Comment by LonelySally** [comment]
> > > > //middleware func Auth(r *ghttp.Request) { r.SetCtxVar("tenant_id", guid.S()) } //ORM g.Model().Ctx(r.GetCtx()).All() //driver d.DriverMysql.GetCtx().Value("tenant_id")
> > > 
> > > 
> > > Is there a better way, because if it passed to the context in ORM, I think it will violate the current code and can only use G.Model to pass the value. What I want is that in the middleware setting value, and get the value of the callback position.
> > 
> > 
> > 这就是规范(阅读v2版本源码会发现几乎所有方法第一个参数都是ctx).各组件解耦,通过上下文联系,链路追踪亦是如此.
> 
> Yes, I know the V2 version understands the coupling of the component, so when I do the project, I still use the V1.16 version by default. In fact, I want to realize the https://gorm.io/zh_CN/docs/hooks.html like gorm's ORM. But I haven't found a better way in Goframe until now

hoook功能在v2里有实现,但在v1仅能如此(就我目前所知).

**Comment by FTLLOVE** [comment]
> Yes, I see hooks being supported in 2.0, but it seems to make some hooks for the model. Actually, I think not only on the model, I prefer to use 'dao.***.***'. In the absence of a better way, I thought I'd create a method to do something about tenant_id alone. Thank you very much for your reply

**Comment by FTLLOVE** [comment]
> > > > > //middleware func Auth(r *ghttp.Request) { r.SetCtxVar("tenant_id", guid.S()) } //ORM g.Model().Ctx(r.GetCtx()).All() //driver d.DriverMysql.GetCtx().Value("tenant_id")
> > > > 
> > > > 
> > > > Is there a better way, because if it passed to the context in ORM, I think it will violate the current code and can only use G.Model to pass the value. What I want is that in the middleware setting value, and get the value of the callback position.
> > > 
> > > 
> > > 这就是规范(阅读v2版本源码会发现几乎所有方法第一个参数都是ctx).各组件解耦,通过上下文联系,链路追踪亦是如此.
> > 
> > 
> > Yes, I know the V2 version understands the coupling of the component, so when I do the project, I still use the V1.16 version by default. In fact, I want to realize the https://gorm.io/zh_CN/docs/hooks.html like gorm's ORM. But I haven't found a better way in Goframe until now
> 
> hoook功能在v2里有实现,但在v1仅能如此(就我目前所知).

Yes, I see hooks being supported in 2.0, but it seems to make some hooks for the model. Actually, I think not only on the model, I prefer to use 'dao..'. In the absence of a better way, I thought I'd create a method to do something about tenant_id alone. Thank you very much for your reply

**Comment by LonelySally** [comment]
> > > > > > //middleware func Auth(r *ghttp.Request) { r.SetCtxVar("tenant_id", guid.S()) } //ORM g.Model().Ctx(r.GetCtx()).All() //driver d.DriverMysql.GetCtx().Value("tenant_id")
> > > > > 
> > > > > 
> > > > > Is there a better way, because if it passed to the context in ORM, I think it will violate the current code and can only use G.Model to pass the value. What I want is that in the middleware setting value, and get the value of the callback position.
> > > > 
> > > > 
> > > > 这就是规范(阅读v2版本源码会发现几乎所有方法第一个参数都是ctx).各组件解耦,通过上下文联系,链路追踪亦是如此.
> > > 
> > > 
> > > Yes, I know the V2 version understands the coupling of the component, so when I do the project, I still use the V1.16 version by default. In fact, I want to realize the https://gorm.io/zh_CN/docs/hooks.html like gorm's ORM. But I haven't found a better way in Goframe until now
> > 
> > 
> > hoook功能在v2里有实现,但在v1仅能如此(就我目前所知).
> 
> Yes, I see hooks being supported in 2.0, but it seems to make some hooks for the model. Actually, I think not only on the model, I prefer to use 'dao..'. In the absence of a better way, I thought I'd create a method to do something about tenant_id alone. Thank you very much for your reply

在dao也是可以使用hook的,只是要稍微手动加工下.有兴趣的话可以看下以下两个文件
[https://gitee.com/tsbjt/brand/blob/master/internal/driver/hook_handler.go](hook)
[https://gitee.com/tsbjt/brand/blob/master/internal/dao/users.go](used:33)

**Comment by FTLLOVE** [comment]
> 

Thank you very much. Now I have a question, how do I pass the value of the middleware into the Model object

**Comment by FTLLOVE** [comment]
> > > > > > > //middleware func Auth(r *ghttp.Request) { r.SetCtxVar("tenant_id", guid.S()) } //ORM g.Model().Ctx(r.GetCtx()).All() //driver d.DriverMysql.GetCtx().Value("tenant_id")
> > > > > > 
> > > > > > 
> > > > > > Is there a better way, because if it passed to the context in ORM, I think it will violate the current code and can only use G.Model to pass the value. What I want is that in the middleware setting value, and get the value of the callback position.
> > > > > 
> > > > > 
> > > > > 这就是规范(阅读v2版本源码会发现几乎所有方法第一个参数都是ctx).各组件解耦,通过上下文联系,链路追踪亦是如此.
> > > > 
> > > > 
> > > > Yes, I know the V2 version understands the coupling of the component, so when I do the project, I still use the V1.16 version by default. In fact, I want to realize the https://gorm.io/zh_CN/docs/hooks.html like gorm's ORM. But I haven't found a better way in Goframe until now
> > > 
> > > 
> > > hoook功能在v2里有实现,但在v1仅能如此(就我目前所知).
> > 
> > 
> > Yes, I see hooks being supported in 2.0, but it seems to make some hooks for the model. Actually, I think not only on the model, I prefer to use 'dao..'. In the absence of a better way, I thought I'd create a method to do something about tenant_id alone. Thank you very much for your reply
> 
> 在dao也是可以使用hook的,只是要稍微手动加工下.有兴趣的话可以看下以下两个文件 [hook](https://gitee.com/tsbjt/brand/blob/master/internal/driver/hook_handler.go) [used:33](https://gitee.com/tsbjt/brand/blob/master/internal/dao/users.go)

Actually, I don't think the support of orm component of goframe in multi-tenancy is particularly good.
