### ISSUE TITLE
TCP RecvPkg 字节序问题

### ISSUE THREAD

**Issue by ghchris** [gogf/gf#2070]
### 2. What version of `GoFrame` are you using?

v2.1.2

### 4. What did you do?

tcp RecvPkg  默认BigEndian，但是使用场景有LittleEndian的情况！

### 5. What did you expect to see?
能否在PkgOption中加入一个字节序类型的参数

**Comment by gqcn** [comment]
`SendPkg/RecvPkg`是属于`gtcp`组件内置的轻量级包通信网络协议，为了解决粘包问题，并简化包传输。此外，网络传输中，传递通常都使用`BigEndian`。
