### ISSUE TITLE
*gclient.Client.GetVar() will not return an error due to context timeout, resulting in an empty scan

### ISSUE THREAD

**Issue by zhonghuaxunGM** [gogf/gf#2073]
### 1. What version of `Go` and system type/arch are you using?
go version go1.16.15 windows/amd64

### 2. What version of `GoFrame` are you using?
github.com/gogf/gf/v2 v2.1.2

### 3. Can this issue be re-produced with the latest release?
yes

### 4. What did you do?

I want to query an interface and scan the specified struct. 
Just like:
```
	var artifacts []Artifact
	err := g.Client().GetVar(ctx, url).Scan(&artifacts)
	if err != nil {
		panic(err)
	}
```
I found when the `ctx` I pass in times out, the structure `Artifact` from scan is empty, and err is nil.

> I suspect it is caused by the context timeout !

When I use the following  ` g.Client().Get` method, the error `context deadline exceeded:` can appear.
```
	// var artifacts []Artifact
	// ctx, cancel := context.WithTimeout(context.Background(), time.Second)
	// defer cancel()
	r, err := g.Client().Get(ctx, url)
	// .Scan(&artifacts)
	if err != nil {
		panic(err)
	}
	fmt.Println(r.ReadAllString())
```

I looked through the source code and found that he did not deal with err but discarded it, I don't understand the concept of design.
```
// RequestVar sends request using given HTTP method and data, retrieves converts the result
// to specified pointer. It reads and closes the response object internally automatically.
// The parameter `pointer` can be type of: struct/*struct/**struct/[]struct/[]*struct/*[]struct, etc.
func (c *Client) RequestVar(ctx context.Context, method string, url string, data ...interface{}) *gvar.Var {
	response, err := c.DoRequest(ctx, method, url, data...)
	if err != nil {
		return gvar.New(nil)
	}
	defer response.Close()
	return gvar.New(response.ReadAll())
}
```

**Comment by DGuang21** [comment]
[HTTP Client - 基础使用 - *Var方法](https://goframe.org/pages/viewpage.action?pageId=1114381#HTTPClient%E5%9F%BA%E6%9C%AC%E4%BD%BF%E7%94%A8-*Var%E6%96%B9%E6%B3%95)

This method has declared the feature of ignoring errors in the description. If you need to handle errors, please use the standard method, and then manually call gvar.New.

**Comment by zhonghuaxunGM** [comment]
FINE. GOT IT.
