### ISSUE TITLE
gf gen dao希望增加参数控制结构体成员名的生成规则

### ISSUE THREAD

**Issue by promisingMan** [gogf/gf#2078]
### 1. What version of `Go` and system type/arch are you using?
go version go1.18.4 windows/amd64

### 2. What version of `GoFrame` are you using?
v2.0.6

我司数据库表（MySQL）字段命名规范是全大写加下划线分隔符，像这种 LABEL_ID
我现在通过gf gen dao生成的代码，结构体成员名都是无下划线全大写的格式，像这种LABELID，可读性很差（希望是生成LabelId这种首字符大写的形式）
![image](https://user-images.githubusercontent.com/26761403/185354732-b6ea5d3a-23aa-4c8d-b2ff-d964dae5fa1b.png)

期望：看文档gf gen dao有jsonCase参数控制json标签名称规则，希望针对结构体成员名也增加相应的参数控制

**Comment by DGuang21** [comment]
这属于增强的建议，如果您有兴趣的话可以尝试自己提交一个PR~
