### ISSUE TITLE
请问规范化路由中间件如何定义返回更多的参数?

### ISSUE THREAD

**Issue by 544751779** [gogf/gf#2080]
比如我想返回一个列表查询到的  total总数 
在有些情况下 加一些 debug数据给接口开发人员
等 

```
{"code":0,"message":"","data":[xxxxxx,xxxx],"total":123 ,debug:{xxxxx} }
```
另外在swagger 中只是显示data中的结构体 没有 完整的返回字段,应该如何设置呢 ?

**Comment by LonelySally** [comment]
> 比如我想返回一个列表查询到的 total总数 在有些情况下 加一些 debug数据给接口开发人员 等
> 
> ```
> {"code":0,"message":"","data":[xxxxxx,xxxx],"total":123 ,debug:{xxxxx} }
> ```
> 
> 另外在swagger 中只是显示data中的结构体 没有 完整的返回字段,应该如何设置呢 ?

自定义一个Response的middleware,再定义一个自身需求的HandlerResponse结构体,在controller里将一些额外信息注入到ctx中,在middleware.Response的后置行为里取回注入的额外信息,根据自身需求组装返回内容即可.
