### ISSUE TITLE
关于gdb的一些小想法

### ISSUE THREAD

**Issue by larryclean** [gogf/gf#2088]
1.Handle 是否可以增加一个全局的Handle
2.model对象是不是可以增加GetTableName() string
如果增加的这些可以实现saas模式的开发

**Comment by FTLLOVE** [comment]
> 

i use custom driver to handle tenant

**Comment by larryclean** [comment]
> > 
> 
> i use custom driver to handle tenant

我也是，但是我认为有个全局的handle操作起来会更简单

**Comment by larryclean** [comment]
@houseme @gqcn 不知道大佬们，是否可以提供一个思路实现多租户的几种模式。总感觉目前已经可以满足了。但是实现的时候却发现总是哪里少了点东西。
1.共享表也就是每张表增加一个tenant_id
2.共享数据库不同schema的方式
3.不同数据源的方式。

**Comment by larryclean** [comment]
<img width="454" alt="image" src="https://user-images.githubusercontent.com/18585750/200602323-9c142fa9-e722-4f4d-8992-26683326c79b.png">
而且翻了一下源码，感觉这个WithDB就像是一个无用的方法一样.
```

  //这个判断好像永远也进不去
  if ctxDb := DBFromCtx(dbCtx); ctxDb != nil {
  return dbCtx
  }

```

**Comment by lusson-luo** [comment]
@FTLLOVE @larryclean 多租户的查询的全局处理，有什么解决方案吗

**Comment by houseme** [comment]
> i use custom driver to handle tenant

可以更详细的描述一下，以及现有的想法或许想实现的目标
