### ISSUE TITLE
gfcli docker example 短参数与输入不匹配

### ISSUE THREAD

**Issue by hailaz** [gogf/gf#2100]
![271993e49e36a72cd2db6b4af06462d](https://user-images.githubusercontent.com/29968474/187141097-b8a9cdd3-9992-47bf-a351-887e0bb6eb00.png)

**Comment by FallingHeart** [comment]
wow, thx

**Comment by gqcn** [comment]
@FallingHeart @hailaz 已增加兼容的标签支持旧版本。
