### ISSUE TITLE
请问怎么使用中间间拦截 /static/20220826/xx.png 这样的请求？

### ISSUE THREAD

**Issue by g1012415019** [gogf/gf#2102]
请问怎么使用中间间拦截 /static/20220826/xx.png 这样的请求？

**Comment by DGuang21** [comment]
[静态文件服务](https://goframe.org/pages/viewpage.action?pageId=1114172)

> func beforeServeHook(r *ghttp.Request) {
	glog.Debugf(r.GetCtx(), "beforeServeHook [is file:%v] URI:%s", r.IsFileRequest(), r.RequestURI)
	r.Response.CORSDefault()
}

**Comment by zhonghuaxunGM** [comment]
Maybe you can use a simple and rude method.
In Middlerwarehandler, get the uri and judge that the prefix is ​​/static.

This issue is closed. If still have a question, plz let me known.
