### ISSUE TITLE
用gf-cli2.1.2打包生成的二进制文件执行报找不到配置文件

### ISSUE THREAD

**Issue by zhenhua1** [gogf/gf#2104]
![image](https://user-images.githubusercontent.com/22211474/187818875-c3f9d9f7-ebd9-40df-ad5c-21398b176533.png)
相关配置如下
![image](https://user-images.githubusercontent.com/22211474/187818916-623a6a5a-7632-4559-9f65-49c08e3aba04.png)
![image](https://user-images.githubusercontent.com/22211474/187818958-87898bd2-dd35-47ec-93c3-9a53ec229b12.png)

**Comment by ar026** [comment]
可以将配置文件拷贝至二进制文件同目录运行程序，也可将配置文件作为资源文件打包至二进制文件中   打包可参考 https://goframe.org/pages/viewpage.action?pageId=17203571 注意 打包后需要在main文件中引用
