### ISSUE TITLE
is gf gen biz in planning?

### ISSUE THREAD

**Issue by zcyc** [gogf/gf#2107]
### 1. What version of `Go` and system type/arch are you using?

1.19

### 2. What version of `GoFrame` are you using?

2.1.4

### 3. Can this issue be re-produced with the latest release?
yes

### 4. What did you do?

cli generate api controller logic service and so on
so i have enough time to code the core logic but crud

### 5. What did you expect to see?
generate api controller logic service and so on

### 6. What did you see instead?
only generate model entity do

**Comment by sanrentai** [comment]
It is a good idea.
