### ISSUE TITLE
文件监听写入时会触发两次

### ISSUE THREAD

**Issue by tianxia0079** [gogf/gf#2110]
_, err := gfsnotify.Add(monitor.String(), func(event *gfsnotify.Event) {

		if event.IsWrite() {
			//会写入两次，加锁的方式，对第二次写入事件才调用特定的方法
			glog.Debug(ctx, "写入文件 : ", event.Path, gfile.Size(event.Path))
		}
		if event.IsRemove() {
			glog.Debug(ctx, "删除文件 : ", event.Path)
		}

		glog.Debug(ctx, event)
	}, true)

希望底层完成两次触发写入事件的问题。或者提供个参考方法实现：对第二次写入事件才调用特定的方法

**Comment by YanCastle** [comment]
我发现gf run 也会触发两次的样

**Comment by hailaz** [comment]
[	_, err = gfsnotify.Add(gfile.RealPath("."), func(event *gfsnotify.Event) {](https://github.com/gogf/gf/blob/master/cmd/gf/internal/cmd/cmd_run.go#L94)

可以参考这个代码去重，两次触发应该是区别的，建议按自己的业务处理。

**Comment by hailaz** [comment]
> [ _, err = gfsnotify.Add(gfile.RealPath("."), func(event *gfsnotify.Event) {](https://github.com/gogf/gf/blob/master/cmd/gf/internal/cmd/cmd_run.go#L94)
> 
> 可以参考这个代码去重，两次触发应该是区别的，建议按自己的业务处理。

突然记起来了，有些时候两次写入是因为某些编辑器自动格式化导致的。

**Comment by gqcn** [comment]
> _, err = gfsnotify.Add(gfile.RealPath("."), func(event *gfsnotify.Event) {

是的，编辑器搞的。
