### ISSUE TITLE
数据库的ORM链式操作WhereLike方法有BUG

### ISSUE THREAD

**Issue by xinjiayu** [gogf/gf#2115]
数据库的ORM链式操作有BUG

代码如下：

```
		m := dao.NetworkTunnel.Ctx(ctx).WhereLike(dao.NetworkTunnel.Columns().Name, "%"+in.KeyWord+"%")
```
这样使用的时候，link的语句是有作用的。

如果分开写，like语句就没起作用。

		m := dao.NetworkTunnel.Ctx(ctx)
		m.WhereLike(dao.NetworkTunnel.Columns().Name, "%"+in.KeyWord+"%")

**Comment by houseme** [comment]
> 数据库的ORM链式操作有BUG
> 
> 代码如下：
> 
> ```
> 		m := dao.NetworkTunnel.Ctx(ctx).WhereLike(dao.NetworkTunnel.Columns().Name, "%"+in.KeyWord+"%")
> ```
> 
> 这样使用的时候，link的语句是有作用的。
> 
> 如果分开写，like语句就没起作用。
> 
> ```
> 	m := dao.NetworkTunnel.Ctx(ctx)
> 	m.WhereLike(dao.NetworkTunnel.Columns().Name, "%"+in.KeyWord+"%")
> ```

```go
    var list = ([]*entity.NetworkTunnel)(nil)
    m := dao.NetworkTunnel.Ctx(ctx)
    m = m.WhereLike(dao.NetworkTunnel.Columns().Name, "%"+in.KeyWord+"%")
    if err = m.Scan(&list); err != nil {
        err = gerror.Wrap(err, "xxxxx")
    }

```

**Comment by zcyc** [comment]
.Ctx() 是 safe 连接，需要给之前的 m 赋值。这个不是 bug，注意看文档。

**Comment by zhonghuaxunGM** [comment]
FYI：
```
https://goframe.org/pages/viewpage.action?pageId=61149607#ORM%E9%93%BE%E5%BC%8F%E6%93%8D%E4%BD%9C%E6%A8%A1%E5%9E%8B%E5%88%9B%E5%BB%BA-Clone%E6%96%B9%E6%B3%95
```
