### ISSUE TITLE
什么时候能支持http2

### ISSUE THREAD

**Issue by wsy998** [gogf/gf#2120]
什么时候能支持http2

**Comment by Bluevitality** [comment]
同问...

**Comment by gqcn** [comment]
这块需求似乎并不高。

**Comment by 888go** [comment]
> 这块需求似乎并不高。

感觉还是有需要,  为了支持http2, 我现在是额外加个反向代理. 主要是gf文档太好了, 我就舍弃gin

**Comment by 888go** [comment]
> 这块需求似乎并不高。

需求不高, 是因为国内很多人根本不知道有http2,  天天窝着干活,  都认为停留在1.1

**Comment by nuan1989** [comment]
感觉还是希望有官方的支持, http2还是有意义的. 我现在也是只能加个反向代理
