### ISSUE TITLE
vscode+调试+自动编译

### ISSUE THREAD

**Issue by junk123321** [gogf/gf#2126]
请问使用GoFrame，如何配置vscode，能让项目可以断点调试，以及自动编译？谢谢

**Comment by LonelySally** [comment]
一般都是写test用例做debug调试.起web服务直接测试端点没接触过.

**Comment by zcyc** [comment]
1. 安装插件 https://marketplace.visualstudio.com/items?itemName=wk-j.save-and-run
2. vscode 配置文件中添加：
```
  "saveAndRun": {
    "commands": [
      {
        "match": ".*",
        "cmd": "gf gen service",
        "useShortcut": false,
        "silent": false
      } // 自动生成 gf service
    ]
  } // 保存自动执行命令
```
3. 根据自己的喜好修改 match 中的正则表达式实现在特定的文件执行命令

**Comment by zcyc** [comment]
@junk123321
