### ISSUE TITLE
希望glog的配置可以更加细致可控

### ISSUE THREAD

**Issue by 15951836388** [gogf/gf#213]
1. 希望可以添加自定义log 级别 。
我的项目里，debug用来打印调试信息（比较多）上线时会关掉
error用来收集错误
这时，希望在debug和error之间，再添加一个XXX级别，用来重点帮助查错

在控制台，手动设置，只打印xxx和err级别（debug太多了，不打印）
在log文件里，手动设置，打印debug、xxx和err级别

设置writer后，会有空行
![image](https://user-images.githubusercontent.com/14047483/60066072-9e38dc00-9738-11e9-8f8c-5abdd87a64f9.png)

**Comment by johngcn** [comment]
@15951836388 
考虑到通用性，`glog`不打算增加自定义级别的特性，这种特殊需求的特性你可以考虑自行封装方法实现。

空行的话应该是没有使用对，参考一下示例：https://github.com/gogf/gf/blob/master/geg/os/glog/glog_writer_hook.go

**Comment by johngcn** [comment]
@15951836388 下一步改进`glog`的级别配置，以便对于开发者配置更友好。

**Comment by johngcn** [comment]
@15951836388 请更新到最新的`v1.10.0`试试，相关文档：https://goframe.org/os/glog/config
