### ISSUE TITLE
ORM chain operation - update, how to update multiple pieces of data in batches (except Data(&strcut).Save() , only use Data(&strcut).Update())

### ISSUE THREAD

**Issue by zhonghuaxunGM** [gogf/gf#2132]
### 1. What version of `Go` and system type/arch are you using?
go 1.17.13

### 2. What version of `GoFrame` are you using?
goframe v2.0.0 in go mod

### 3. Can this issue be re-produced with the latest release?
feature/v2.2.0

### 4. What did you do?

```
https://goframe.org/pages/viewpage.action?pageId=1114238#ORM%E9%93%BE%E5%BC%8F%E6%93%8D%E4%BD%9C%E6%9B%B4%E6%96%B0%E5%88%A0%E9%99%A4-RawSQL%E8%AF%AD%E5%8F%A5%E5%B5%8C%E5%85%A5
```

The examples of updating I see in the document are all updating one piece. 

Is there a way to update multiple pieces of data in batches through a dynamic judgment method?

Similar to making a field in a structure meet a certain condition.

For example: 
data is sclice, which is multiple pieces of data; 
where condition is designed such that the id of the old data is equal to the id of the new data.

This is the code of the mock logic.
``` 
func UpdResource(data []model.TInfResource) int64 {
	orm, err := GetDBInstance()
	Assert(err)
	result, err := orm.Model("t_inf_resource").Data(data).Where(data.id = data.id).Update()
	Assert(err)
	total, err := result.RowsAffected()
	Assert(err)
	return total
}
```

**Comment by PsyLinkist** [comment]
Do we have a solusion here?
