### ISSUE TITLE
Why the middleware runs before request params validated?

### ISSUE THREAD

**Issue by SimonChyi** [gogf/gf#2139]
Hi, there~
Why the middleware runs before request params validated?
It always appear, so I don`t support the code. Can I reverse this case by someone setting??
Thank you ! 

### 1. What version of `Go` and system type/arch are you using?
go version go1.15.14 darwin/amd64

### 2. What version of `GoFrame` are you using?
v2.0.6

### 3. Can this issue be re-produced with the latest release?
yes, v2.1.4 is same result

### 4. What did you do?
just add some v rule for request params:
```
g.Meta `path:"/rec" method:"post" summary:"api"`
Sign string `v:"required"`
```
then add a middleware:
```
s.Group("/", func(group *ghttp.RouterGroup) {
	group.Middleware(middleware.CheckSign) // just common logic
	group.Bind(
		controller.Rec,
	)
})
```

### 5. What did you expect to see?
change their running order

**Comment by zhonghuaxunGM** [comment]
I think the middleware itself is designed to be executed before or after each api is processed.
Middleware are often used for global or partial global authentication processing or cross-domain, etc.

Or you can manually call parameter validation in the middleware, but it will be executed again after the middleware.

btw，review this page. ` https://goframe.org/pages/viewpage.action?pageId=55289881 `

**Comment by SimonChyi** [comment]
@zhonghuaxunGM Thank you, OK, I see ~
