### ISSUE TITLE
mssql bit类型生成的语句错误

### ISSUE THREAD

**Issue by Q32611600** [gogf/gf#2148]
mssql bit类型;生成的语句是是true和false, 应该是1和0;
`is_use_room=false,img='',flavor='无',is_quota=false,is_select_unit=false`

**Comment by zhonghuaxunGM** [comment]
It is recommended that you provide more version information，plz

**Comment by Q32611600** [comment]
2.1.1版本

**Comment by gqcn** [comment]
@Q32611600 https://goframe.org/pages/viewpage.action?pageId=3673173
![image](https://user-images.githubusercontent.com/26347176/201093406-1adde0ce-e329-4b05-aa51-59bdc526e193.png)
