### ISSUE TITLE
Please support common management endpoints in particular /health

### ISSUE THREAD

**Issue by chamhaw** [gogf/gf#2151]
### 1. What version of `Go` and system type/arch are you using?

go version go1.18.4 darwin/arm64

### 2. What version of `GoFrame` are you using?

v2.1.4

### 3. Can this issue be re-produced with the latest release?
yes

### 4. What did you do?

searched all the docs.

### 5. What did you expect to see?
support common management endpoints such as /health /ready or something else. Better to see custome indicator can be registed to these endpoints.

### 6. What did you see instead?
404 Not Found

**Comment by zhonghuaxunGM** [comment]
It is recommended that you can implement it yourself in routing. 
You must know that the standards for health detection are different in different business scenarios.
You can use ` *ghttp.RouterGroup ` as route grouping.

**Comment by chamhaw** [comment]
If I setup a health check endpoint, how to exclude this endpoint from access logs? @zhonghuaxunGM

**Comment by zhonghuaxunGM** [comment]
@chamhaw 
I don't understand why you do this.
The health check endpoint is also a kind of API. If you want record the result of apis which were accessed, why you exclude that ?

**Comment by zhonghuaxunGM** [comment]
If you still has question, plz let  me know.
