### ISSUE TITLE
gf can't support UInt256 data types  

### ISSUE THREAD

**Issue by hd5723** [gogf/gf#2156]
### 1. What version of `Go` and system type/arch are you using?

 Go Version:  go1.17.11
 GF Version:  v2.1.2
 
### 2. The bug deatil ：
在查询数据库数据时，UInt256类型的数据返回值为0
查询代码：temp, err = g.DB().Model(tableWithDatabase).Safe().Ctx(ctx).Limit(0, 20).All()

![image](https://user-images.githubusercontent.com/80188736/192448162-16ccd5f0-32b1-4a7e-b65c-97d53ee90562.png)

![image](https://user-images.githubusercontent.com/80188736/192448414-5d8f008a-c492-4ae8-bf6b-cd07ea69b22b.png)

### 3. I hope gf can  support UInt256 data types on gdb.

**Comment by houseme** [comment]
是哪个类型的数据库？`MySQL/MariaDB/TiDB`，`SQL Server`，`PostgreSQL`,`Oracle `,`SQLite`,`ClickHouse`,`DM`

**Comment by DGuang21** [comment]
uint/int 128/256 不属于常用数据结构，已在https://github.com/gogf/gf/pull/2214 添加支持
