### ISSUE TITLE
Custom validation rules always return nil and cannot return error messages（自定义效验规则始终返回nil，无法返回错误信息）

### ISSUE THREAD

**Issue by haophper** [gogf/gf#2159]
### 1. What version of `Go` and system type/arch are you using?
go version go1.19.1 darwin/amd64

### 2. What version of `GoFrame` are you using?
v2.1.4

### 3. Can this issue be re-produced with the latest release?
yes

### 4. What did you do?

#Run it directly as middleware
```go
func MiddlewareTest(r *ghttp.Request) {
	fn := func(ctx context.Context, input gvalid.RuleFuncInput) (err error) {
		err = errors.New("this is a error test")
		fmt.Println("----------test-un-name----------", err)
		return
	}
	gvalid.RegisterRule("test-un-name", fn)
	err := g.Validator().Bail().Rules(g.MapStrStr{
		"name": "test-un-name",
	}).Messages("name check fail").Data(g.Map{
		"name": "",
	}).Run(r.GetCtx())
	fmt.Println("----->err:", err)    //Here, it always returns nil
	return
	r.Middleware.Next()
}
```

### 5. What did you expect to see?
----------test-un-name---------- this is a error test
----->err: this is a error test

### 6. What did you see instead?

----------test-un-name---------- this is a error test
----->err: <nil>

**Comment by houseme** [comment]
试试beta版本
