### ISSUE TITLE
The generated entity type does not match

### ISSUE THREAD

**Issue by QQ32920892** [gogf/gf#2168]
gf gen dao 
PostgreSQL Bigint should be int64 but it gets int
# in entity

**Comment by houseme** [comment]
gf的版本号，试试beta版本！

**Comment by QQ32920892** [comment]
> gf的版本号，试试beta版本！

Tried the beta version and had the same problem

**Comment by houseme** [comment]
SQL标准只定义了整型integer(或int)， smallint和bigint。名为int2, int4 和int8的类型都是扩展，它们也在许多其它符合SQL标准的数据库系统中使用。

没有int64的类型 http://www.postgres.cn/docs/9.3/datatype-numeric.html#DATATYPE-INT 

https://www.postgresql.org/docs/14/datatype-numeric.html#DATATYPE-INT 

请问是这里说的‘SQL only specifies the integer types integer (or int), smallint, and bigint. The type names int2, int4, and int8 are extensions, which are also used by some other SQL database systems.’ 这些类型吗？

**Comment by QQ32920892** [comment]
> 

I mean SQL type bigint, int8. The entity file structure generated by using the "gf gen dao" command is int. It should be int64

**Comment by houseme** [comment]
> Author

更新ci工具

**Comment by QQ32920892** [comment]
> > Author
> 
> 更新ci工具

Just updated the latest version, the problem is still not solved

**Comment by gqcn** [comment]
@QQ32920892 很早之前有这个问题，你使用`v2.2.0-beta2`版本的`cli`工具试试呢？

**Comment by QQ32920892** [comment]
> 

CLI Built Detail:
  Go Version:  go1.19.1
  GF Version:  v2.2.0-beta2
  Git Commit:  none
  Build Time:  2022-10-09 20:44:40

This is the latest compiled version and still has problems

**Comment by QQ32920892** [comment]
> @QQ32920892 如果类型是`bigint`是会被转换为`int64`的，你确认下类型，如果仍旧有问题，可以微信私聊我，我试试。

@gqcn  PostgreSQL data types bigint and int8 are incorrectly converted to int

**Comment by gqcn** [comment]
> > @QQ32920892 如果类型是`bigint`是会被转换为`int64`的，你确认下类型，如果仍旧有问题，可以微信私聊我，我试试。
> 
> @gqcn PostgreSQL data types bigint and int8 are incorrectly converted to int

Any table definition that can reproduce this issue?

**Comment by QQ32920892** [comment]
> > > @QQ32920892 如果类型是`bigint`是会被转换为`int64`的，你确认下类型，如果仍旧有问题，可以微信私聊我，我试试。
> > 
> > 
> > @gqcn PostgreSQL data types bigint and int8 are incorrectly converted to int
> 
> Any table definition that can reproduce this issue?

CREATE TABLE "public"."sys_user" (
  "id" int8 NOT NULL,
  "username" varchar(45) COLLATE "pg_catalog"."default" NOT NULL,
  "password" varchar(64) COLLATE "pg_catalog"."default" NOT NULL,
  "state" int4,
  "user_type" int4,
  "updated_at" timestamp(6),
  "created_at" timestamp(6)
)

**Comment by QQ32920892** [comment]
Fixed in v2.2.1 #2222
