### ISSUE TITLE
gredis操作封装建议

### ISSUE THREAD

**Issue by fanshu19** [gogf/gf#218]
谢谢john提供的gredis工具包。提供一个数据转换的功能。
建议提供一些redis操作方法的封装包。这样使用起来方便点。
目前我自己是参照这个库：aiscrm/redisgo  里面的一些函数，自己做了几个方法封装使用了

**Comment by johngcn** [comment]
@fanshu19 感谢支持，现有的`gredis`模块比较轻量级，但是足够使用。目前GF开发团队有小伙伴正在开发一个功能比较完善的`redis`模块（ https://github.com/piaohao/godis ），等待完善后再集成进来。

**Comment by arden** [comment]
怎么不直接支持 https://github.com/go-redis/redis
