### ISSUE TITLE
思考：是否 g.Meta 使用结构体替代现在的标签更合适？

### ISSUE THREAD

**Issue by loocor** [gogf/gf#2187]
以规范路由中常使用 g.Meta 元数据为例，现有形式struct tags 两点明显不足：
- 没有静态检查，因输入 tag 键名错误导致无法获得请求参数；
- 难以格式化，加上 dc、v 尤其是多组校验规则后一长串非常难看、难以维护；

关于 struct tags 的不足已经在 go 2 的一些提案里讨论到，提出允许 tags 换行、用 tab 对齐、使用切片描述等，基本都是针对前面两个问题的。

那在 go 2 到来之前，是否可以用结构体构建 g.Meta，类似：

```golang
// 内置 GMeta 结构体定义
type GMeta struct {
  P    string
  Dc   string
  JSON string
  XML  string
  V    []g.gvalid
  ...
}

// 嵌入请求结构体，是否匿名待定
type HttpRequest struct {
  GMeta
  Name    string
  Gender  int
  Mobile  string
  ...
}

// 实例部分偷懒不写了
...
```
当然，这样只是解决了 g.Meta Tags 的问题，请求结构体里其他字段的 Tags 问题还在，也不知道是否值得继续探讨尝试😂

**Comment by zcyc** [comment]
struct tags 确实丑且难以维护，但是拆开写太繁杂了，增加了工作量。我觉得 tags 换行是好想法，但是要等 go 支持。

**Comment by LonelySally** [comment]
> struct tags 确实丑且难以维护，但是拆开写太繁杂了。tags 换行是好想法，但是要等 go 支持。

最大的问题是不能做静态检测全靠人工审查(method+router).

**Comment by gqcn** [comment]
struct tags 确实丑且难以维护，但是拆开写太繁杂了。tags 换行是好想法，但是要等 go 支持。
