### ISSUE TITLE
关于glog配置，如果想在config.toml文件里配置glog非常不方便。

### ISSUE THREAD

**Issue by arden** [gogf/gf#219]
我在config.tom里配置如下：
```go
[logger]
    logpath = "./log"
    # ALL=504, DEV=504, PROD=448, DEBUG=8, INFO=16, WARN=64, ERROR=128
    level = 16
    debug = false
```
boot.go代码如下：
```go
package boot

import (
	"github.com/gogf/gf/g"
	"github.com/gogf/gf/g/os/gfile"
	"github.com/gogf/gf/g/os/glog"
)

// 用于应用初始化。
func init() {
	c := g.Config()

	// glog配置
	logpath := c.GetString("logger.logpath")
	if !gfile.Exists(logpath) {
		gfile.Mkdir(logpath)
	}
	//level := c.GetInt("logger.level")
	glog.SetPath(logpath)
	glog.SetStdoutPrint(true)
	//glog.SetLevel(level)
	glog.SetLevel(glog.LEVEL_ALL)
	glog.SetFlags(glog.F_TIME_STD | glog.F_FILE_LONG)
	debug := c.GetBool("logger.debug", false)
	if !debug {
		glog.SetDebug(false)
	}

	//glog.Debug(logpath)
}
```

然后我在代码里调用：
glog.Debug("hello")
这个时候会log目录下的日志文件里把Debug的调试信息也输出来，并且在日志文件里以[INFO]标识输出，而不是以[DEBU]标识输出，另外标识也应该是[DEBUG]，而不是DEBU吧。这个问题好像不是必现，我在Linux下面出现这问题。

**Comment by johngcn** [comment]
@arden 

配置这个我改进一下，便于配置级别。

设计的时候就是`DEBU`，每个级别的前缀统一保留4个字母，以便日志输出的时候格式对齐。

下面那个问题我没有复现，看了程序也不会出现你说的这种问题，请自行调试下是否本身输出的级别就是`Info`。

**Comment by arden** [comment]
> @arden
> 
> 配置这个我改进一下，便于配置级别。
> 
> 设计的时候就是`DEBU`，每个级别的前缀统一保留4个字母，以便日志输出的时候格式对齐。
> 
> 下面那个问题我没有复现，看了程序也不会出现你说的这种问题，请自行调试下是否本身输出的级别就是`Info`。

那个错误，后面我确认过了，是我同事今天也在调，在Linux服务器直接调了错了，是我这边的问题，没注意到，配置方面可以改进一下。

**Comment by johngcn** [comment]
@arden 请更新到最新的`v1.10.0`试试，相关文档：https://goframe.org/os/glog/config
