### ISSUE TITLE
校验组件需要 password1

### ISSUE THREAD

**Issue by zcyc** [gogf/gf#2190]
### 1. What version of `Go` and system type/arch are you using?

go1.19.1 windows/amd64

### 2. What version of `GoFrame` are you using?

v2.2.0

### 3. Can this issue be re-produced with the latest release?
yes

### 4. What did you do?

校验密码是数字和字母

### 5. What did you expect to see?
要么只校验长度，要么就是校验大小写加数字。不能只校验字母及数字，需要自定义校验。

### 6. What did you see instead?
新增一种校验类型，password1，密码必须包含数字及字母即可，不限制大小写。

**Comment by zhonghuaxunGM** [comment]
@zcyc 
plz, keep focus on this pull request.
https://github.com/gogf/gf/pull/2209

**Comment by zcyc** [comment]
> @zcyc 
> 
> plz, keep focus on this pull request.
> 
> https://github.com/gogf/gf/pull/2209

thx

**Comment by gqcn** [comment]
@zcyc @zhonghuaxunGM 大家好，这种简单的密码规则并不通用、较为特殊。建议使用正则表达式`regex:$[a-zA-Z]\d]+^`

**Comment by zcyc** [comment]
@gqcn 我要的是必须包含数字和字母组成。这个正则只能校验是不是由数字或者字母组成。
