### ISSUE TITLE
数据库脚本管理支持

### ISSUE THREAD

**Issue by wo10378931** [gogf/gf#22]
是否能集成类似flyway那种数据库脚本管理的支持

**Comment by johngcn** [comment]
@wo10378931 你好，感谢提供建议。目前`GF`的`ORM`暂无支持类似`flyway`那样的数据库版本管理功能的计划。数据库的管理功能交给其他的第三方工具。

**Comment by wo10378931** [comment]
嗯，感谢。已经用goose 来搞了。
