### ISSUE TITLE
 gf gen service BUG：当logic中的函数返回值使用泛型

### ISSUE THREAD

**Issue by plhwin** [gogf/gf#2202]
GF Version:  v2.2.0

go version go1.19.1 darwin/arm64

<img width="1237" alt="image" src="https://user-images.githubusercontent.com/1219345/195598254-99f04e5f-2e83-471c-90ab-e93888e9af27.png">

这是gf-demo-user工程，当当logic中的函数返回值使用泛型时，gf gen service 生成的service文件，import部份有误，详情见截图。

**Comment by CCpro10** [comment]
maybe it is Goland’s bug，make sure your Goland version support generic

**Comment by plhwin** [comment]
确定不是ide的bug，就是自动生成的service会额外引入很多无用的import。

**Comment by plhwin** [comment]
报错也并不是出现在泛型部份，而是import部份

**Comment by plhwin** [comment]
补充下，通过v2.2.0发布版本安装的gf工具，https://github.com/gogf/gf/releases/download/v2.2.0/gf_darwin_arm64 ，会导致以上问题；


但从gf代码仓库拉取最新master分支，编译gf客户端工具后，该问题不在出现。


试了下，如果再次通过wget安装v2.2.0的发布版本，问题依然存在，说明这个版本的gf gen service 对泛型支持的确存在问题。

**Comment by DGuang21** [comment]
> 补充下，通过v2.2.0发布版本安装的gf工具，https://github.com/gogf/gf/releases/download/v2.2.0/gf_darwin_arm64 ，会导致以上问题；
> 
> 但从gf代码仓库拉取最新master分支，编译gf客户端工具后，该问题不在出现。
> 
> 试了下，如果再次通过wget安装v2.2.0的发布版本，问题依然存在，说明这个版本的gf gen service 对泛型支持的确存在问题。

关于为何通过v2.2.0发布的工具总是能否复现的原因：https://git-scm.com/book/en/v2/Git-Basics-Tagging
> Tagging
Like most VCSs, Git has the ability to tag specific points in a repository’s history as being important. Typically, people use this functionality to mark release points (v1.0, v2.0 and so on). In this section, you’ll learn how to list existing tags, how to create and delete tags, and what the different types of tags are.

v2.2.0 只是 git 中的一个 tag ，指向的是一个准确的 commit ，代表着的是一个确切的提交。如果直接拉取 master 代码后问题不再出现，则代表着是在最新版的代码中已经将该问题修复，静候发布新版本即可。

如果在开发环境中需要先解决该问题，则可自行拉取 master 编译即可。
