### ISSUE TITLE
error from gdb.New()  always nil

### ISSUE THREAD

**Issue by CCpro10** [gogf/gf#2204]
```go
node := gdb.ConfigNode{
		  Host:  "127.0.0.1",
		  Port:  "9000",
		  User:  "default",
		  Name:  "default",
		  Type:  "clickhouse",
		  Debug: false,
	}
db, err = gdb.New(node)
if err ! = nil{
     
}


// New creates and returns a database object for clickhouse.
// It implements the interface of gdb.Driver for extra database driver installation.
func (d *Driver) New(core *gdb.Core, node *gdb.ConfigNode) (gdb.DB, error) {
	return &Driver{
		Core: core,
	}, nil
}
```
### 5. What did you expect to see?

if fail to connect database, I wish err ! = nil
 
### 6. What did you see instead?
The returned err is nil regardless of whether the connection is successful or not
（err 始终为nil ）

**Comment by CCpro10** [comment]
I hope insert PingMaster()  into  func (d *Driver) New(core *gdb.Core, node *gdb.ConfigNode) (gdb.DB, error)  can resolve it

**Comment by DGuang21** [comment]
请先发起Pr

**Comment by CCpro10** [comment]
> 请先发起Pr

＃2212

**Comment by CCpro10** [comment]
> 请先发起Pr

https://github.com/gogf/gf/pull/2212

**Comment by gqcn** [comment]
@CCpro10 The `New` function just creates database management object, it does not connection to database server right then. It does and checks connection until it does really database operations. So you can call `PingMaster/PingSlave` to check the connection, not by `New`.

**Comment by zcyc** [comment]
@gqcn 
Why make the err always be nil?
Why don't  remove it or set a check result for it?
