### ISSUE TITLE
请求验证能否加入返回验证错误的变量名

### ISSUE THREAD

**Issue by ppozippy** [gogf/gf#2218]
**### What version of Go and system type/arch are you using?**
Go Version:  go1.17.13

**### What version of GoFrame are you using?**
GF Version:  v2.2.0

** ### What did you do?**
请求验证错误后会返回错误信息，但是不返回具体是发生错误的变量名，能否加入错误返回的变量名及错误信息？

**### What did you expect to see?**
api路由
type UserCreateReq struct {
	g.Meta `path:"/user/create" tags:"创建" method:"post" summary:"创建用户"`
	Name   string `json:"name" v:"required|length:4,40#姓名不能为空|姓名长度为:min到:max位" dc:"用户姓名"`
	Mobile string `json:"mobile" dc:"手机号"`
	Sex    uint   `json:"sex" dc:"性别"`
	Status int    `json:"status" dc:"启用状态"`
}

输入值
{
    "name": "",
    "mobile": "",
    "sex": 0,
    "status": true
}

返回验证失败json
{
    "code": 100,
    "message": "姓名不能为空",
    "data": null
}

希望能增加返回验证失败的变量名称  name

**Comment by DGuang21** [comment]
> err := g.Validator().Messages(messages).Rules(rules).Data(params).Run(gctx.New())
if err != nil {
	g.Dump(err.Maps())
}

> {
    "passport": {
        "length": "账号长度应当在6到16之间",
        "required": "账号不能为空"
    },
    "password": {
        "same": "两次密码输入不相等"
    }
}

[https://goframe.org/pages/viewpage.action?pageId=7301695](数据校验)

**Comment by ppozippy** [comment]
> > err := g.Validator().Messages(messages).Rules(rules).Data(params).Run(gctx.New())
> > if err != nil {
> > g.Dump(err.Maps())
> > }
> 
> > {
> > "passport": {
> > "length": "账号长度应当在6到16之间",
> > "required": "账号不能为空"
> > },
> > "password": {
> > "same": "两次密码输入不相等"
> > }
> > }
> 
> [https://goframe.org/pages/viewpage.action?pageId=7301695](%E6%95%B0%E6%8D%AE%E6%A0%A1%E9%AA%8C)

这样做是不是提交表单的时候不做任何验证，把所有的验证放到后续的处理中？

**Comment by ppozippy** [comment]
> > err := g.Validator().Messages(messages).Rules(rules).Data(params).Run(gctx.New())
> > if err != nil {
> > g.Dump(err.Maps())
> > }
> 
> > {
> > "passport": {
> > "length": "账号长度应当在6到16之间",
> > "required": "账号不能为空"
> > },
> > "password": {
> > "same": "两次密码输入不相等"
> > }
> > }
> 
> [https://goframe.org/pages/viewpage.action?pageId=7301695](%E6%95%B0%E6%8D%AE%E6%A0%A1%E9%AA%8C)

这样做是不是提交表单的时候不做任何验证，把所有的验证放到后续的处理中？

**Comment by DGuang21** [comment]
> > > err := g.Validator().Messages(messages).Rules(rules).Data(params).Run(gctx.New())
> > > if err != nil {
> > > g.Dump(err.Maps())
> > > }
> > 
> > 
> > > {
> > > "passport": {
> > > "length": "账号长度应当在6到16之间",
> > > "required": "账号不能为空"
> > > },
> > > "password": {
> > > "same": "两次密码输入不相等"
> > > }
> > > }
> > 
> > 
> > [https://goframe.org/pages/viewpage.action?pageId=7301695](%E6%95%B0%E6%8D%AE%E6%A0%A1%E9%AA%8C)
> 
> 这样做是不是提交表单的时候不做任何验证，把所有的验证放到后续的处理中？

https://github.com/gogf/gf/blob/1c5fd1a1f77ccec605856d1cf89ecc8a3587afb1/net/ghttp/ghttp_request_param.go#L111
并不需要，gf在将参数转换完毕后，会调用gvalid进行数据的校验。如果抛回来了一个错误，可断言或者使用```gerror.Code(err)``` 进行错误的获取。
