### ISSUE TITLE
ORM 查询时使用时间条件时无结果

### ISSUE THREAD

**Issue by ifelsedo** [gogf/gf#2225]
### 1. What version of `Go` and system type/arch are you using?
go1.18.7

### 2. What version of `GoFrame` are you using?
v2.2.0

### 3. Can this issue be re-produced with the latest release?
yes

### 4. What did you do?
condition := g.Map{
  "order_status":      1,
  "updated_at <=":     gtime.Now().Add(-30 * time.Second),
}
return dao.Order.Ctx(ctx).Fields(dao.Order.Columns().Id).Limit(50).Where(condition).Array()

上面执行后发现没有报错，但同时也没有数据返回，debug 显示sql: SELECT `id` FROM `order` WHERE `order_status`=1 AND trade_status <= 4 AND updated_at < '2022-10-20 21:38:27' LIMIT 50
在将 sql 复制到数据库中执行发现有结果，于是注释 updated_at 条件，再次运行有数据了，确认过时间没有问题；

<img width="698" alt="1" src="https://user-images.githubusercontent.com/20554450/196968864-26d07eb9-835a-4c9e-8abd-f834eaa01d70.png">

![image](https://user-images.githubusercontent.com/20554450/196969287-6b4bbfce-bd58-428d-a10e-d3152a446bc4.png)

**Comment by DGuang21** [comment]
你可以尝试一下改成
```
gtime.Now().Add(-30 * time.Second).String()
```

**Comment by zhonghuaxunGM** [comment]
简单猜了一下，是不是时区问题导致，你申明db配置时候的link 有没有 loc 的参数配置

**Comment by ifelsedo** [comment]
好的，谢谢，我试试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月24日(周一) 下午2:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [gogf/gf] ORM 查询时使用时间条件时无结果 (Issue #2225)

**Comment by zhonghuaxunGM** [comment]
有问题再评论吧，此 issue 先关闭了
