### ISSUE TITLE
Generic response support

### ISSUE THREAD

**Issue by doyard** [gogf/gf#2227]
```go
type Content interface {
}
type PageableContentRes[T Content] struct {
	Content  []*T `json:"content"`
}

(v1.PageableContentRes[v1.xxxxxRes], error)
```

invalid struct naming for response: defined as "%s", but it should be named with "Res" suffix like "XxxRes"

**Comment by houseme** [comment]
Currently, generics of golang are not supported.

**Comment by chamhaw** [comment]
> 

Thanks for replying. Since Go 1.19 has been released for a while, please consider supporting generic among GoFrame.

**Comment by gqcn** [comment]
@houseme @doyard We should support the generic definition in routes registering.
