### ISSUE TITLE
[Help wanted] How to configure swagger doc for removing omitempty from keys?

### ISSUE THREAD

**Issue by doyard** [gogf/gf#2234]
Omitempty after JSON keys may cause confusion to frontend engineers.
![image](https://user-images.githubusercontent.com/9896402/197919056-78f2ee65-19ed-438e-bfe9-a534bd3fe26a.png)

**Comment by chamhaw** [comment]
https://github.com/gogf/gf/pull/2294
Did the PR above fix the issue？
