### ISSUE TITLE
can't setting group route

### ISSUE THREAD

**Issue by NorseLZJ** [gogf/gf#2237]
### 1. What version of `Go` and system type/arch are you using?

go version go1.19.1 windows/amd64

### 2. What version of `GoFrame` are you using?
GoFrame CLI Tool v2.2.0-beta2, https://goframe.org
GoFrame Version: cannot find go.mod
CLI Installed At: C:\Users\Administrator\go\bin\gf.exe
CLI Built Detail:
  Go Version:  go1.17.13
  GF Version:  v2.2.0-beta2
  Git Commit:  2022-09-30 15:42:57 007715dbd5dd949c10727c6e84abcd932ac4937f
  Build Time:  2022-09-30 15:44:39

### 3. Can this issue be re-produced with the latest release?

yes

### 4. What did you do?

it's codes and errors and document examples
![image](https://user-images.githubusercontent.com/52354783/198026020-c96240e3-1c19-4b53-b93f-e284d07eda4e.png)

### 6. What did you see instead?

![image](https://user-images.githubusercontent.com/52354783/198026243-3b55bcdf-f9c3-40ee-a6ba-0af694187fec.png)

**Comment by zhonghuaxunGM** [comment]
我这边无法复现你的问题，请提供最小化可运行代码，或提供public项目链接。

![image](https://user-images.githubusercontent.com/50815786/198544872-06398816-5824-49af-8838-3a07cb9a368d.png)
![image](https://user-images.githubusercontent.com/50815786/198544888-e73f67a4-ed74-42f6-a222-0e569137bf9e.png)

**Comment by NorseLZJ** [comment]
我这边找到问题了,不过不确定为什么会这样

![image](https://user-images.githubusercontent.com/52354783/198585265-c88ceaee-28bc-4fd8-8c7b-39ee444d2142.png)

**Comment by NorseLZJ** [comment]
也许是我理解有问题吧,有可以运行的办法,上面有示例,就不去探究这两种的差别什么了吧,后面有空了再说

**Comment by zhonghuaxunGM** [comment]
或许是在 req 中的metadata 数据中重复定义了route。
```
g.Meta     `path:"/hello" method:"get" tags:"" summary:""`
```
