### ISSUE TITLE
When i use ghttp.RestartAllServer to upgrade my server catch an error

### ISSUE THREAD

**Issue by zcyc** [gogf/gf#2243]
### 1. What version of `Go` and system type/arch are you using?

1.19.2 windows amd64

### 2. What version of `GoFrame` are you using?

2.2.1

### 3. Can this issue be re-produced with the latest release?
yes

### 4. What did you do?

```
// download
r, err := g.Client().Get(ctx, "http://download-link-for-new-server")
if err != nil {
	return errors.New("download failed")
}

// put bytes
newFile:= "newFile"
if err := gfile.PutBytes(newFile, r.ReadAll()); err != nil {
	return errors.New("put bytes failed")
}

// chmod
if err := gfile.Chmod(newFile, gfile.DefaultPermCopy); err != nil {
	return errors.New("chmod filed")
}

// graceful restart
if err := ghttp.RestartAllServer(ctx, newFile); err != nil {
	return errors.New("graceful restart failed")
}
```

### 5. What did you expect to see?
server restart and run newFile

### 6. What did you see instead?
the restart is fialed with wrong command,
gf set the new file path and old file path together in restart command.

**Comment by gqcn** [comment]
@zcyc What's the error message when it failed?
