### ISSUE TITLE
glog CtxKeys  empty value  placeholder

### ISSUE THREAD

**Issue by hanqian200705** [gogf/gf#2245]
### 4. What did you do?

When the traceId or CtxStr partial value is empty of the log output from the glog component , a placeholder is provided. The log format is unified to facilitate log collection

config： CtxKeys     = ["key","key2"]

### 5. What did you expect to see?

traceId is empty：
2022-10-31 10:36:43.522 [INFO]    {} {aaa} {kv2} auth...

Both traceId and key are empty ：
2022-10-31 10:36:43.522 [INFO]    {} {} {kv2} auth...

**Comment by hailaz** [comment]
version？

**Comment by hailaz** [comment]
You can refer tohttps://github.com/hailaz/gflearn/blob/main/os/0-log/main.go
