### ISSUE TITLE
Cannot deserialize composited struct with normalized router

### ISSUE THREAD

**Issue by doyard** [gogf/gf#2246]
**Cannot deserialize composited struct.**
go 1.19.2
gf 2.1.4

1. curl request:
```bash
curl --location --request PUT 'http://127.0.0.1:8000/api/v1/namespaces/stable/rollouts/test' \
--header 'Content-Type: application/json' \
--data-raw '{
  "spec": {
      "replicas": 10,
      "strategy": {
        "rollingUpdate": {
          "maxUnavailable": "10%",
          "maxSurge": 2
        }
      },
      "paused": false
    }
}'
```
2. Response body
```json
{
    "code": 50,
    "message": "reflect.Value.Convert: value of type map[string]interface {} cannot be converted to type v1alpha1.RolloutSpec",
    "data": null
}
```
3. Unit test(Succeed)
```go
import (
	"fmt"
	"log"
	"testing"
         
         "k8s.io/apimachinery/pkg/util/json"

         "github.com/argoproj/argo-rollouts/pkg/apis/rollouts/v1alpha1"
)

func Test(t *testing.T) {
	j := `{
           "spec": {
               "replicas": 10,
               "strategy": {
                  "rollingUpdate": {
                       "maxUnavailable": "10%",
                       "maxSurge": 2
                   }
                 },
                 "paused": false
            }
         }`

	rolloutReq := &RolloutReq{}
	err := json.Unmarshal([]byte(j), rolloutReq)
	if err != nil {
		log.Fatal(err)
		return
	}
	newJ, _ := json.Marshal(rolloutReq)
	fmt.Println("req:" + string(newJ))
}

type RolloutReq struct {
	g.Meta `path:"/namespaces/:namespace/rollouts/:name" tags:"Deployment" method:"put" summary:"Create Rollout Deployment"`
	*v1alpha1.Rollout
}

```

**Comment by chamhaw** [comment]
Registering the router myself works well.
`group.PUT("/namespaces/:namespace/rollouts/:name", controller.Rollout.Replace)`
```go
func (c cRollout) Replace(r *ghttp.Request) {}
```

**Comment by chamhaw** [comment]
The root cause maybe the Scan function.
`r.GetJson.Scan(&rollout)` got the same error while `json.Unmarshal(r.GetBody(), rollout)` works.

**Comment by hailaz** [comment]
Not reproducible
![image](https://user-images.githubusercontent.com/29968474/199665840-57a81bc1-3c59-4604-b7d6-f1fbe68bb289.png)

**Comment by chamhaw** [comment]
> Not reproducible ![image](https://user-images.githubusercontent.com/29968474/199665840-57a81bc1-3c59-4604-b7d6-f1fbe68bb289.png)

Thanks for your hard-working. I will try to reproduce it again sometime later and post more information I missed.

**Comment by doyard** [comment]
> Not reproducible ![image](https://user-images.githubusercontent.com/29968474/199665840-57a81bc1-3c59-4604-b7d6-f1fbe68bb289.png)

What middleware did you use? It seems you were using a JSON deserializer rather than the gconv module with reflect implementation.

**Comment by gqcn** [comment]
@doyard Please try the latest version, if this issue persists, submit a new one.
