### ISSUE TITLE
gcache.GetOrSetFun() 返回 nil 死锁

### ISSUE THREAD

**Issue by songouku** [gogf/gf#226]
### 1. What version of `Go` and system type/arch are you using?
go1.12.1 linux/amd64
### 2. What version of `GoFrame` are you using?
v1.7.0
### 3. Can this issue be reproduced with the latest release?
可重现

### 4. What did you do?

```go
func localCache() {
	result := gcache.GetOrSetFunc("test.key.1", func() interface{} {
		return nil
	}, 1000*60*2)
	if result == nil {
		common.Error("未获取到值")
	} else {
		common.Infofln("result is $v", result)
	}
}

func TestCache(t *testing.T) {
	for i := 0; i < 100; i++ {
		localCache()
	}
}
```

**Comment by johngcn** [comment]
@songouku 感谢反馈，已修复，请更新到最新的`v1.7.1`试试。
