### ISSUE TITLE
r.GetRequestMap()返回内容包含form-data表单body信息

### ISSUE THREAD

**Issue by LonelySally** [gogf/gf#2261]
request请求Content-Type为multipart/form-data时,返回r.GetRequestMap()获取数据会意外得到表单的body原始信息.
```
{
"----------------------------675405739396733188684112\r\nC ontent-Disposition:_form-data;_name": "\"passport\"\r\n\r\nxxx\r\n----------------------------675405739396733188684112\r\nContent-Disposition: form-data; name=\"password\"\r\n\r\n123456\r\n----------------------------6754057 39396733188684112--\r\n",
"passport": "xxx",
"password": "123456"
}
````
原因猜测:
request解析时parseBody[ghttp_request_param.go:243]执行了r.bodyMap, _ = gstr.Parse(r.GetBodyString()) 将body按等号切割成了kv赋值给了bodyMap对象,GetRequestMap()[ghttp_request_param_request.go:97]获取时将r.xxxMap全部合并导致body原始信息出现在返回对象中.

**Comment by hailaz** [comment]
试了一下并不会，不确定是不是已经修复了
require github.com/gogf/gf/v2 v2.3.0
```
data := r.GetRequestMap()
glog.Debug(r.GetCtx(), data)
```
```
<body>
    <form action="/" method="post" encType="multipart/form-data">
        <input type="text" name="name" id="" value="123">
        <button type="submit">提交</button>
    </form>
</body>
```

![image](https://user-images.githubusercontent.com/29968474/218673854-982a7eec-d748-4be5-9f82-d1efc1bd5141.png)
![image](https://user-images.githubusercontent.com/29968474/218674035-64ade50d-b33a-4307-b0ac-b24d88f99f69.png)

![image](https://user-images.githubusercontent.com/29968474/218673926-a9b6d56c-7a21-4116-a9cc-c41231cde6c6.png)

**Comment by LonelySally** [comment]
> 试了一下并不会，不确定是不是已经修复了 require github.com/gogf/gf/v2 v2.3.0
> 
> ```
> data := r.GetRequestMap()
> glog.Debug(r.GetCtx(), data)
> ```
> 
> ```
> <body>
>     <form action="/" method="post" encType="multipart/form-data">
>         <input type="text" name="name" id="" value="123">
>         <button type="submit">提交</button>
>     </form>
> </body>
> ```
> 
> ![image](https://user-images.githubusercontent.com/29968474/218673854-982a7eec-d748-4be5-9f82-d1efc1bd5141.png) ![image](https://user-images.githubusercontent.com/29968474/218674035-64ade50d-b33a-4307-b0ac-b24d88f99f69.png)
> 
> ![image](https://user-images.githubusercontent.com/29968474/218673926-a9b6d56c-7a21-4116-a9cc-c41231cde6c6.png)

![image](https://user-images.githubusercontent.com/26945597/218676068-fc1fc30c-5df0-4c20-844c-5ef8739e1467.png)
用postman测试的 没在网页端做个表单测试

**Comment by hailaz** [comment]
@LonelySally 我先用postman试过，没出现，才写个页面测试。

**Comment by LonelySally** [comment]
> @LonelySally 我先用postman试过，没出现，才写个页面测试。最好是能够提供版本，最小复现代码，否则不容易排查。 ![image](https://user-images.githubusercontent.com/29968474/218982222-fc449210-3e98-4196-8fbe-88672804cf73.png) ![image](https://user-images.githubusercontent.com/29968474/218982761-693eb8fd-64dc-409f-a3f3-3c00f1eebaa9.png)

找到原因了,你写一个中间件,在中间件的前置行为里执行一次r.GetBody()
`
func (s *sMiddleware) Test(r *ghttp.Request) {
	r.GetBody()
        r.Middleware.Next()
}
`
然后在控制器里执行g.Dump(g.RequestFromCtx(ctx).GetRequestMap())就有输出了

**Comment by hailaz** [comment]
![4698fda1c920f01607c78bb0a0a556b](https://user-images.githubusercontent.com/29968474/219299830-ce504255-033c-4490-92e1-cfc8315221b6.png)
准确定位到，因为先r.GetBody()，会保留body内容，那么body内容将会被parse进bodymap，而如果先GetRequestMap()，在GetRequestMap()里面包含了原生的ParseForm，ParseForm会清空r.body内容，而导致r.GetBody()为空。
