### ISSUE TITLE
github.com/gogf/gf/contrib/drivers/mysql/v2 v2.2.1 版本报错

### ISSUE THREAD

**Issue by mushu1990** [gogf/gf#2263]
### 1. What version of `Go` and system type/arch are you using?
go 1.19 mac

### 2. What version of `GoFrame` are you using?
gf 2.1.4

### 4. What did you do?
github.com/gogf/gf/contrib/drivers/mysql/v2 v2.2.1 引入此版本报错信息如下。
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/5515926/199881480-db29f06f-4428-44ed-b1a5-5af65c29ad21.png">

github.com/gogf/gf/contrib/drivers/mysql/v2 v2.1.2 无此问题。

配置信息如下:
<img width="686" alt="image" src="https://user-images.githubusercontent.com/5515926/199881783-6bc794db-d92b-49d1-90b8-48ea8284464a.png">

**Comment by houseme** [comment]
引入之后，需要执行 `go mod tidy`

**Comment by hailaz** [comment]
修改gf依赖版本

**Comment by mushu1990** [comment]
好吧。一不注意 gf 都 2.2.2 了
