### ISSUE TITLE
error from gdb.New() always nil

### ISSUE THREAD

**Issue by CCpro10** [gogf/gf#2278]
```go
node := gdb.ConfigNode{
		  Host:  "127.0.0.1",
		  Port:  "9000",
		  User:  "default",
		  Name:  "default",
		  Type:  "clickhouse",
		  Debug: false,
	}
db, err = gdb.New(node)
if err ! = nil{
     
}


// New creates and returns a database object for clickhouse.
// It implements the interface of gdb.Driver for extra database driver installation.
func (d *Driver) New(core *gdb.Core, node *gdb.ConfigNode) (gdb.DB, error) {
	return &Driver{
		Core: core,
	}, nil
}
```
### 5. What did you expect to see?

if fail to connect database, I wish err ! = nil
 
### 6. What did you see instead?
The returned err is nil regardless of whether the connection is successful or not
（err 始终为nil ）

**Comment by CCpro10** [comment]
gdb.New() 返回的error 一定为nil，那么返回错误有什么意义，这样处理是否优雅？是不是函数签名设计的失误？

既然error一定为nil，是否可以不返回error？参考 go-Redis

如果仍然返回error，error是否应该在某些情况下不是nil？参考 gorm？

我认为这里设计的非常不优雅。
#2204

**Comment by sanrentai** [comment]
gdb.AddConfigNode

**Comment by gqcn** [comment]
@CCpro10 你好，`gdb.New`返回的`error`是有意义的，具体请查看最新版本源码。而`Driver.New`方法是接口实现，不同的数据库驱动对于创建`Driver`对象的逻辑不一样，所以接口中的`error`是有一定意义的。
