### ISSUE TITLE
gogf/gf/geg/other/terminal-color.go 

### ISSUE THREAD

**Issue by ywanbing** [gogf/gf#228]
line:32   
`for d := range []int{0, 1, 4, 5, 7, 8} { // 显示方式 = 0,1,4,5,7,8`

我觉得你想表达的意思应该这样  `for _, d := range []int{0, 1, 4, 5, 7, 8} { // 显示方式 = 0,1,4,5,7,8`

**Comment by johngcn** [comment]
@ywanbing 是的，这个文件是测试用的。
