### ISSUE TITLE
参数绑定时若数据类型不一致可否报错而非使用默认类型零值

### ISSUE THREAD

**Issue by YahuiAn** [gogf/gf#2301]
### 1. What version of `Go` and system type/arch are you using?

go version go1.18.3 linux/amd64

### 2. What version of `GoFrame` are you using?

v2.2.4

### 3. Can this issue be re-produced with the latest release?
yes

### 4. What did you do?

```go
package main

import (
	"context"
	"fmt"

	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/net/ghttp"
)

type HelloReq struct {
	g.Meta `path:"/hello/{ID}" method:"get"`
	ID     int `v:"required"`
}
type HelloRes struct {
	Reply string `dc:"Reply content"`
}

type Hello struct{}

func (Hello) Say(ctx context.Context, req *HelloReq) (res *HelloRes, err error) {
	g.Log().Debug(ctx, err)
	res = &HelloRes{
		Reply: fmt.Sprintf(`Hi %d`, req.ID),
	}
	return
}

func main() {
	s := g.Server()
	s.Use(ghttp.MiddlewareHandlerResponse)
	s.Group("/", func(group *ghttp.RouterGroup) {
		group.Bind(
			new(Hello),
		)
	})
	s.Run()
}

```

### 5. What did you expect to see?
用户传递字符串类型的参数时直接报错 400，流程停止

### 6. What did you see instead?
没有报错，返回零值 0

```shell
$ curl http://localhost:62866/hello/xyz
{"code":0,"message":"","data":{"Reply":"Hi 0"}}

$ curl http://localhost:62866/hello/1
{"code":0,"message":"","data":{"Reply":"Hi 1"}}
```

感觉这样做的好处有两点：
1. 快速报错方便客户端调整参数类型
2. 接口后续的逻辑拿到的数据一定是正确的，不需要考虑是否为零值

**Comment by LonelySally** [comment]
改写成 v:"required|integer|gt:0"

**Comment by YahuiAn** [comment]
感谢感谢，使用 v:"integer" 确实可以，就是每次为了校验数据类型都写 tag 可能有点麻烦 😢

**Comment by LonelySally** [comment]
> 感谢感谢，使用 v:"integer" 确实可以，就是每次为了校验数据类型都写 tag 可能有点麻烦 😢

入参类型本身就是需要进行校验的,不论在哪种框架中都应当如此.不能依赖错误去决定处理逻辑,而应尽可能的把错误描述完整.

**Comment by LonelySally** [comment]
暂时先关闭了,有问题请重新打开.

**Comment by YahuiAn** [comment]
> > 感谢感谢，使用 v:"integer" 确实可以，就是每次为了校验数据类型都写 tag 可能有点麻烦 😢
> 
> 入参类型本身就是需要进行校验的,不论在哪种框架中都应当如此.不能依赖错误去决定处理逻辑,而应尽可能的把错误描述完整.

## gin
在 gin 中数据绑定时不需要再使用 tag 重复声明数据类型的

```go
package main

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

type HelloReq struct {
	ID int `json:"id" bind:"required"`
}

func main() {
	r := gin.Default()

	r.POST("/hello", func(c *gin.Context) {
		var param HelloReq

		if err := c.ShouldBindJSON(&param); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
			return
		}

		c.JSON(http.StatusOK, gin.H{"msg": "success"})
	})

	r.Run("localhost:6666")
}
```

![image](https://user-images.githubusercontent.com/39142491/202101841-63fb9927-c764-45fe-93d1-57d33ff2755c.png)

可以看到如果客户端传递 string 会有提示信息的

## gf

```go
package main

import (
	"context"
	"fmt"

	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/net/ghttp"
)

type HelloReq struct {
	g.Meta `path:"/hello" method:"post"`
	ID     int `v:"required"`
}
type HelloRes struct {
	Reply string `dc:"Reply content"`
}

type Hello struct{}

func (Hello) Say(ctx context.Context, req *HelloReq) (res *HelloRes, err error) {
	res = &HelloRes{
		Reply: fmt.Sprintf(`Hi %d`, req.ID),
	}
	return
}

func main() {
	s := g.Server()
	s.SetAddr("localhost:8000")
	s.Use(ghttp.MiddlewareHandlerResponse)
	s.Group("/", func(group *ghttp.RouterGroup) {
		group.Bind(
			new(Hello),
		)
	})
	s.Run()
}
```

![image](https://user-images.githubusercontent.com/39142491/202102358-f9c2a912-b8a4-41f0-a13c-ecbc8cee4fd0.png)

我理解在定义结构体时已经表明 ID 是 int 类型了，但是还要再使用 v:"interger" 来约束类型，有种重复的感觉，如果忘记了加约束，默认使用类型零值可能会带来困惑。

**Comment by LonelySally** [comment]
> > > 感谢感谢，使用 v:"integer" 确实可以，就是每次为了校验数据类型都写 tag 可能有点麻烦 😢
> > 
> > 
> > 入参类型本身就是需要进行校验的,不论在哪种框架中都应当如此.不能依赖错误去决定处理逻辑,而应尽可能的把错误描述完整.
> 
> ## gin
> 在 gin 中数据绑定时不需要再使用 tag 重复声明数据类型的
> 
> ```go
> package main
> 
> import (
> 	"net/http"
> 
> 	"github.com/gin-gonic/gin"
> )
> 
> type HelloReq struct {
> 	ID int `json:"id" bind:"required"`
> }
> 
> func main() {
> 	r := gin.Default()
> 
> 	r.POST("/hello", func(c *gin.Context) {
> 		var param HelloReq
> 
> 		if err := c.ShouldBindJSON(&param); err != nil {
> 			c.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
> 			return
> 		}
> 
> 		c.JSON(http.StatusOK, gin.H{"msg": "success"})
> 	})
> 
> 	r.Run("localhost:6666")
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/39142491/202101841-63fb9927-c764-45fe-93d1-57d33ff2755c.png)
> 
> 可以看到如果客户端传递 string 会有提示信息的
> 
> ## gf
> ```go
> package main
> 
> import (
> 	"context"
> 	"fmt"
> 
> 	"github.com/gogf/gf/v2/frame/g"
> 	"github.com/gogf/gf/v2/net/ghttp"
> )
> 
> type HelloReq struct {
> 	g.Meta `path:"/hello" method:"post"`
> 	ID     int `v:"required"`
> }
> type HelloRes struct {
> 	Reply string `dc:"Reply content"`
> }
> 
> type Hello struct{}
> 
> func (Hello) Say(ctx context.Context, req *HelloReq) (res *HelloRes, err error) {
> 	res = &HelloRes{
> 		Reply: fmt.Sprintf(`Hi %d`, req.ID),
> 	}
> 	return
> }
> 
> func main() {
> 	s := g.Server()
> 	s.SetAddr("localhost:8000")
> 	s.Use(ghttp.MiddlewareHandlerResponse)
> 	s.Group("/", func(group *ghttp.RouterGroup) {
> 		group.Bind(
> 			new(Hello),
> 		)
> 	})
> 	s.Run()
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/39142491/202102358-f9c2a912-b8a4-41f0-a13c-ecbc8cee4fd0.png)
> 
> 我理解在定义结构体时已经表明 ID 是 int 类型了，但是还要再使用 v:"interger" 来约束类型，有种重复的感觉，如果忘记了加约束，默认使用类型零值可能会带来困惑。

猜测是执行顺序不一样,先绑定后校验与先校验后绑定的区别.gin的bind标签应该是指的参数来源指定,绑定(赋值)时发生类型报错(可能是panic).在gf中bind对应的标签应该是p,与v标签互相独立. @gqcn 这个你来看下?

**Comment by hnutank163** [comment]
这个问题真的反直觉，好像还是没有解决？

**Comment by packing-pake** [comment]
> 这个问题真的反直觉，好像还是没有解决？

并不是反直觉的问题,限制入参类型的会有两种情况,  id:1与id:"1".这种情况本身就是运行执行类型转换的.非数字类型的转换为类型默认值的原因只是在bind前做了new操作赋予了默认值.建议还是用validate去避免这种情况的发生而不是依赖字段类型.
实际上之前的回复少了字符串类型的数字情况.
