### ISSUE TITLE
建议goframe类似beego中的bee工具

### ISSUE THREAD

**Issue by biij5698** [gogf/gf#231]
不清楚goframe有没有这样的工具，刚才大概浏览了一下，没发现有，建议增加，如有，请略过。

**Comment by johngcn** [comment]
@biij5698 是的，目前暂时没有类似的脚手架工具，计划会增加，目前已创建了仓库 https://github.com/gogf/gf-cli 预计可能会随着`v1.9.0`或者`1.10.0`发布。

**Comment by johngcn** [comment]
@biij5698 已发布。
