### ISSUE TITLE
cli gen service:BUG

### ISSUE THREAD

**Issue by alaywn** [gogf/gf#2310]
### 1. What version of `Go` and system type/arch are you using?

go version go1.19.3 darwin/arm64

### 2. What version of `GoFrame` are you using?

github.com/gogf/gf/v2 v2.2.4

### 3. Can this issue be re-produced with the latest release?

YES!

### 4. What did you do?

BUG1：使用gf gen service时，logic目录下的代码中被注释的**方法**，依旧会在service中生成接口方法
BUG2：使用gf gen service时，如果service中已经生成的了文件，再回提示no dirty信息，无法重新生成覆盖已有文件（参数overwrite=true）

BUG1复现方式：focus-single项目中，注释某个logic目录中的方法，然后运行gf gen service 就可以重现
BUG2复现方式：focus-single项目中直接运行gf gen service 就可以重现

**Comment by zcyc** [comment]
不仅如此，在 logic 下的文件，没有 struct 的文件也会生成 service。

**Comment by sanrentai** [comment]
遇到同样的问题，v2.3.2

**Comment by gqcn** [comment]
@alaywn @zcyc @sanrentai 大家好，其实这个`gen service`命令内部是使用正则匹配来实现方法的搜集和生成的，目前并没有识别注释的逻辑。所以这里改进的话可以增加相关逻辑即可，也比较简单。
另外一种更优雅的代码生成方式，是通过官方的Golang语法解析包解析源代码来生成代码，这种方式会稍微复杂一些，但是确实优雅、非常优雅！
感兴趣的小伙伴可以一起参与建设。

**Comment by oldme-git** [comment]
Please show #3067
