### ISSUE TITLE
interface conversion: interface {} is nil, not map[string]*gdb.TableField error in  github.com/gogf/gf/database/gdb.(*DriverMysql).TableFields 

### ISSUE THREAD

**Issue by Charntent** [gogf/gf#2320]
### 1. What version of `Go` and system type/arch are you using?
Linux Centos 
Go 1.14

### 2. What version of `GoFrame` are you using?
gf 1.13.1

### 3. Can this issue be re-produced with the latest release?
No

### 4. What did you do?
github.com/gogf/gf/database/gdb.(*DriverMysql).TableFields这个函数在运行一段时间缓存丢失或者其他错误后居然报错 

 interface conversion: interface {} is nil, not map[string]*gdb.TableField

### 5. What did you expect to see?

自动更新数据表结构，而且缓存丢失时能自动缓存回来

### 6. What did you see instead?

panic   interface conversion: interface {} is nil, not map[string]*gdb.TableField

**Comment by gqcn** [comment]
@Charntent `v2`版本开始这里有较大改动，建议升级到最新版本再看能否复现该问题。
