### ISSUE TITLE
Scan cannot copy "Id"

### ISSUE THREAD

**Issue by chamhaw** [gogf/gf#2324]
<img width="464" alt="image" src="https://user-images.githubusercontent.com/93499036/203697009-6b73dc8f-f351-4f36-98e2-f163061bc5f9.png">

gf 2.1.5
go 1.19.2

**Comment by LonelySally** [comment]
两者层级都不同,请贴下代码.

**Comment by chamhaw** [comment]
@LonelySally 
```go
input := &model.SecretUpdateInput{}
err := gconv.Scan(req, input)

type SecretUpdateReq struct {
	g.Meta       `path:"/secrets/:secret" tags:"Secret" method:"put" summary:"update Secret"`
	Id           int64  `json:"secret" p:"secret" in:"path" dc:"Secret id"`
	Name         string `json:"name" v:"required" dc:"Secret name"`
}

type SecretUpdateInput struct {
	Id int64
	SecretBaseFiled
	UpdatedBy string
}
type SecretBaseFiled struct {
	Name         string `json:"name" v:"required" dc:"Secret name"`
}
```

**Comment by LonelySally** [comment]
> 



> @LonelySally
> 
> ```go
> input := &model.SecretUpdateInput{}
> err := gconv.Scan(req, input)
> 
> type SecretUpdateReq struct {
> 	g.Meta       `path:"/secrets/:secret" tags:"Secret" method:"put" summary:"update Secret"`
> 	Id           int64  `json:"secret" p:"secret" in:"path" dc:"Secret id"`
> 	Name         string `json:"name" v:"required" dc:"Secret name"`
> }
> 
> type SecretUpdateInput struct {
> 	Id int64
> 	SecretBaseFiled
> 	UpdatedBy string
> }
> type SecretBaseFiled struct {
> 	Name         string `json:"name" v:"required" dc:"Secret name"`
> }
> ```
去掉tag标签或者让两者一致 gconv会根据tag属性做匹配
例如这样
type SecretUpdateReq struct {
	g.Meta       `path:"/secrets/:secret" tags:"Secret" method:"put" summary:"update Secret"`
	Id           int64 
	Name         string `json:"name" v:"required" dc:"Secret name"`
}
或者
type SecretUpdateInput struct {
	Id int64 `json:"secret" p:"secret" in:"path" dc:"Secret id"`
	SecretBaseFiled
	UpdatedBy string
}

**Comment by LonelySally** [comment]
暂时先关闭,有问题请重新打开.
