### ISSUE TITLE
1.7.2  gbase64.Decode  无法解析非常规字符

### ISSUE THREAD

**Issue by qq1196** [gogf/gf#233]
1.7.0 可以正常解析这个，HwHsGhXMaGc===
但现在1.7.2无法解析，返回是空，没内容，

**Comment by qq1196** [comment]
1.7.2
data := "HwHsGhXMaGc==="
	var datab []byte
	datab,_= gbase64.Decode([]byte(data))
	data = string(datab)
	fmt.Println(data)
返回为空，无法解码非常规gbase64码，




1.7.0
data := "HwHsGhXMaGc==="
	data,_= gbase64.Decode(data)
	fmt.Println(data)
有返回内容，可以正常解码这种非常规gbase64码

**Comment by johngcn** [comment]
@qq1196 原因是新版本当判断到解析出错时直接返回`nil`，我这里改一下，改成和之前一致。

**Comment by johngcn** [comment]
@qq1196 已修复，请更新到`v1.7.3`再试。
