### ISSUE TITLE
 suggestion for transaction in SQLSERVER

### ISSUE THREAD

**Issue by myvfpx** [gogf/gf#2330]
强哥:
SQLSERVER中保存事务点的命令为SAVE TRAN,现在框架中的保存事务点使用的SAVEPOINT固定值。
希望强哥考虑一下对SQLSERVER保存事务点的兼容。感谢强哥！

**Comment by gqcn** [comment]
@myvfpx `SAVEPOINT`是常用数据库的标准做法。欢迎提供改进建议或者`PR`。
