### ISSUE TITLE
gconv.Bool   解析错误

### ISSUE THREAD

**Issue by keryoo** [gogf/gf#234]
### 1. What version of `Go` and system type/arch are you using?
go 1.12

### 2. What version of `GoFrame` are you using?
 gf 1.7.0

### 3. Can this issue be reproduced with the latest release?

no

### 4. What did you do?
```		
if v, err := g.Redis().Do("MGET", getDatas...); err != nil {
			mylog.Println(err)
		} else {
			mylog.Println(v)
			mv := gconv.Interfaces(v)  
			mylog.Println(mv)  //打印 [<nil> <nil> [49] [48] <nil> <nil> <nil> <nil> <nil>]
			for _, v:= range mv {
				r := gconv.Bool(v) 
	                        fmt.Println(r)	  //49和48打印的都是ture 	
                       } 
```

### 5. What did you expect to see?
    48 应该是false

**Comment by johngcn** [comment]
@keryoo 那是因为你给的参数是数字`48`，参数类型为`byte`，所以识别为了`true`。我猜想你想要的是`string(byte(48))`这样的参数对吧，那你需要传递字符串，不要传递数字。

**Comment by keryoo** [comment]
```
_, err = redisConn.rc.Do("SET", "useron:"+L.UID, true, "EX", "43200")
```
redis 里设置的bool 的true或false

使用redis 客户端查的也是 
172.16.1.113:6379> get useron:974284
"0"
172.16.1.113:6379> get useron:940437
"1"
172.16.1.113:6379> get useron:14
(nil)

**Comment by johngcn** [comment]
@keryoo 已修复，将会在下一个版本`v2.0`发布。

**Comment by johngcn** [comment]
@keryoo 请更新最新框架代码再试试。
