### ISSUE TITLE
How to get headers map from request and clone headers from request to gclient?

### ISSUE THREAD

**Issue by zcyc** [gogf/gf#2342]
### 1. What version of `Go` and system type/arch are you using?
v1.19.2 windows/amd64

### 2. What version of `GoFrame` are you using?
latest

### 3. Can this issue be re-produced with the latest release?
yes

### 4. What did you do?
I want to get headers map from request and clone headers from context to gclient.

### 5. What did you expect to see?
I can clone all headers from request.
I can get headers map from request.
I can set headers use Header type.

### 6. What did you see instead?
I only can get header by name, can not get all headers to a map.
I only can set headers map to gclient, can not set header with Header or Context.

**Comment by gqcn** [comment]
1. The `ghttp.Request.Header` is the received map from client.
2. Use configuration function `SetHeader/SetHeaderMap/SetHeaderRaw` or chaining function `Header/HeaderRaw`.

**Comment by zcyc** [comment]
@gqcn 
ghttp.Request.Header get a `map[string][]string`, but SetHeaderMap need a map[string]string.
So, how can i copy it from request to gclient without any handle.

**Comment by zcyc** [comment]
SetHeaderRaw need a string, how can i `GetHeaderRaw`.
