### ISSUE TITLE
orm的count返回类型及统一

### ISSUE THREAD

**Issue by demozx** [gogf/gf#2350]
GoFrame2.25
model的count方法返回值改成了int64，但是g.RequestFromCtx(ctx).GetPage的参数totalSize仍然是int类型，是否需要统一

func (m *Model) Count(where ...interface{}) (int64, error){
} 

func (r *Request) GetPage(totalSize, pageSize int) *gpage.Page {
}

**Comment by zcyc** [comment]
fix #2361

**Comment by niluan304** [comment]
#2378 v2.2.6的 返回值改回了 int类型，刚发布的 v2.3.0 也继续着使用int类型.

**Comment by zcyc** [comment]
v2.2.5 版本不符合 semver，所以 v2.2.6 又改回去了。
