### ISSUE TITLE
gtimer 类方法备注有误

### ISSUE THREAD

**Issue by nuan1989** [gogf/gf#2355]
gtimer_timer.go
gtimer.go
这两个文件, 备注有误, 应该是: 
"adds a timing job after delay of `delay` duration."
![1](https://user-images.githubusercontent.com/43518669/207044617-dbba7777-6869-4031-a158-50a14f6c7091.png)

**Comment by gqcn** [comment]
https://github.com/gogf/gf/pull/2430
