### ISSUE TITLE
数据库 unsigned 类型识别失败，无符号类型全部识别成了有符号类型

### ISSUE THREAD

**Issue by xt-inking** [gogf/gf#2356]
### 1. What version of `Go` and system type/arch are you using?

go version go1.19.4 linux/amd64

### 2. What version of `GoFrame` are you using?

v2.2.5

### 3. Can this issue be re-produced with the latest release?
Yes.

### 4. What did you do?

```sql
CREATE TABLE `demo` (
	`id` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;
INSERT INTO `demo` (`id`) VALUES (18446744073709551615);
```

```go
package main

import (
	"github.com/gogf/gf/v2/frame/g"

	_ "github.com/gogf/gf/contrib/drivers/mysql/v2"
)

func main() {
	r, e := g.DB().Model("demo").One()
	if e != nil {
		panic(e)
	}
	g.DumpWithType(r["id"].Val())
}
```

### 5. What did you expect to see?
uint64(18446744073709551615)
or
uint(18446744073709551615)

### 6. What did you see instead?
int64(-9223372036854775808)

**Comment by gqcn** [comment]
@xt-inking 感谢反馈，我先打上标签，后续跟进查看一下。

**Comment by gqcn** [comment]
https://github.com/gogf/gf/pull/2428
