### ISSUE TITLE
如何阻止表单验证或业务逻辑error的stdout输出

### ISSUE THREAD

**Issue by acsiver** [gogf/gf#2359]
### 1. What version of `Go` and system type/arch are you using?
1.9.13

### 2. What version of `GoFrame` are you using?

2.2.5

### 4. What did you do?

表单验证规则返回的是一个error，当表单验证失败时错误信息输出到标准输出stdout，这会导致有大量的非必要的验证日志（比如格式错误，必填选项等）输出到终端，我设置了server的logStdout为false才不会输出，但这样会屏蔽所有日志，请问如何能实现一些非必要的error到stdout呢

**Comment by hailaz** [comment]
表单校验错误是非必要错误？

**Comment by gqcn** [comment]
@acsiver 可以加一个后置中间件判断错误码，结合`SetError`来过滤掉这种错误。
