### ISSUE TITLE
写入mysql时间字段的时区比当前时间早8小时

### ISSUE THREAD

**Issue by yuanlj-tea** [gogf/gf#2360]
### 1. What version of `Go` and system type/arch are you using?
go version go1.18.9 darwin/arm64

### 2. What version of `GoFrame` are you using?
github.com/gogf/gf/v2 v2.2.2

### 3. Can this issue be re-produced with the latest release?
Only tried in v2.2.2

### 4. What did you do?
- 数据库时区
![5e494603308033646c1632d5bea20c58](https://user-images.githubusercontent.com/20747808/207763966-61b99c85-85c3-4b25-8543-57e8763eafb7.png)
- orm配置
![fb2e704ba921ba6e7193d04141d3a7ae](https://user-images.githubusercontent.com/20747808/207763988-6685ea3b-a366-486c-8473-a12fbb64c5b8.png)
- 数据库连接配置：
?loc=Local&parseTime=true
- 日志打印的sql
![image](https://user-images.githubusercontent.com/20747808/207764173-827f28b8-dbcc-4d30-ad09-d8fb9ab0109a.png)

最终写入数据库的时间比当前时间早8小时，是哪里设置的问题吗

**Comment by zcyc** [comment]
你在系统里打印一下系统时区。

**Comment by yuanlj-tea** [comment]
问题已经解决，换成v2.1.4，在代码里设置了时区为上海；就解决了
