### ISSUE TITLE
MYSQL的sleep线程过多,没有复用连接数.

### ISSUE THREAD

**Issue by qq413434162** [gogf/gf#2376]
在gf2.1.4版本下,通过设置
maxIdle:               "(可选)连接池最大闲置的连接数"
发现并没有效果

通过mysql语句查询  
```mysql
select * from information_schema.processlist 
```
得到的sleep线程数达到100多

问题1.该maxIdle设置不是理解上的,空闲时会释放连接池中的连接,只保留设置的数量在连接池中吗?

问题2.mysql显示的sleep线程越来越多,好像连接池并没有重用一样?
maxOpen:               "(可选)连接池最大打开的连接数" 没有设置
ps:所有的sleep线程的ip都是同一个,并该ip下只有该进程在运行

我想要解决?
问题1.希望不要保留太多的空闲连接数

问题2.希望连接池能重用连接数,因为发现sleep的线程只会越来越多.

**Comment by qq413434162** [comment]
使用的事务方式是,手动commit而不是闭包或defer,有可能出现异常后直接跳出,占用了连接.

现在改用defer里面commit就解决了

**Comment by zfha** [comment]
我也出现了，有找到修复版本么？
