### ISSUE TITLE
请问这个bug 什么时候修改呢？ superfluous response.WriteHeader call from

### ISSUE THREAD

**Issue by 1211ciel** [gogf/gf#2379]
不影响运行，但偶尔就会报错
错误如下
```
2022-12-27 20:49:00.248 [ERRO] http: superfluous response.WriteHeader call from github.com/gogf/gf/v2/net/ghttp.(*ResponseWriter).Flush (ghttp_response_writer.go:58)
Stack:
1.  github.com/gogf/gf/v2/net/ghttp.(*ResponseWriter).Flush
    /Users/ciel/go/pkg/mod/github.com/gogf/gf/v2@v2.2.5/net/ghttp/ghttp_response_writer.go:58
2.  github.com/gogf/gf/v2/net/ghttp.(*Response).Flush
    /Users/ciel/go/pkg/mod/github.com/gogf/gf/v2@v2.2.5/net/ghttp/ghttp_response.go:151
3.  github.com/gogf/gf/v2/net/ghttp.(*Server).ServeHTTP
    /Users/ciel/go/pkg/mod/github.com/gogf/gf/v2@v2.2.5/net/ghttp/ghttp_server_handler.go:196


```
### 1. What version of `Go` and system type/arch are you using?
go version go1.19.1 darwin/arm64

### 2. What version of `GoFrame` are you using?

GoFrame CLI Tool v2.2.5, https://goframe.org
GoFrame Version: v2.2.5 in current go.mod
CLI Installed At: /opt/homebrew/bin/gf
CLI Built Detail:
  Go Version:  go1.17.13
  GF Version:  v2.2.5
  Git Commit:  2022-11-25 10:45:56 4553f90a834ea32ff844303da3f6f18c9f091635
  Build Time:  2022-11-28 20:31:52

### 4. What did you do?
在 go.mod 里面将 版本更新为 `github.com/gogf/gf/v2 v2.2.5` 后出现错误

之前`github.com/gogf/gf/v2 v2.0.6` 是正常的

**Comment by Martin2037** [comment]
同问

**Comment by goblin1987** [comment]
遇到相同问题

**Comment by 1211ciel** [comment]
@goblin1987 ，@Martin2037 官方说下个版本修复，出现此错误的话暂时不要升级。

**Comment by goblin1987** [comment]
@1211ciel 好的，谢谢
