### ISSUE TITLE
func RuleGT.Run  always return error

### ISSUE THREAD

**Issue by happyinsect** [gogf/gf#2380]
### 1. What version of `Go` and system type/arch are you using?
go 1.19

### 2. What version of `GoFrame` are you using?
 v2.2.5

### 3. Can this issue be re-produced with the latest release?
yes

### 4. What did you do?
I add a valid v:"gt:0" on PageNo

type GetInspectionTemplateReq struct {
	g.Meta       `path:"/inspectionTemplate/get" tags:"InspectionTemplate" method:"post" summary:"GetInspectionTemplate"`
	Name         string `json:"name"`
	TemplateType int    `json:"templateType"`
	PeriodType   int    `json:"periodType"`
	Used         int    `json:"used"`
	PageNo       int    `json:"pageNo" v:"gt:0"`
	PageSize     int    `json:"pageSize" v:"gt:0"`
}
Then test the api in postman, the reqest as:
{
"pageNo":1,
"pageSize":10
}

### 5. What did you expect to see?

it return the data from db.

### 6. What did you see instead?

it returns error, "The PageNo" value '1' must be greater than field value ''

**Comment by hailaz** [comment]
use min `v:"min:1"`
https://goframe.org/pages/viewpage.action?pageId=1114367#id-%E6%95%B0%E6%8D%AE%E6%A0%A1%E9%AA%8C%E6%A0%A1%E9%AA%8C%E8%A7%84%E5%88%99-min
