### ISSUE TITLE
热编译传入args参数时，在windows10下无法正常启动

### ISSUE THREAD

**Issue by bufanyun** [gogf/gf#2383]
> 热编译传入args参数时，在windows10下无法正常启动，但是在linux环境下可以正常使用

gf版本：v2.2.5
```
PS E:\server> gf -v
GoFrame CLI Tool v2.2.5, https://goframe.org
GoFrame Version: v2.2.5 in current go.mod
CLI Installed At: C:\Windows\gf2.exe
CLI Built Detail:
  Go Version:  go1.17.13
  GF Version:  v2.2.5
  Git Commit:  2022-11-25 10:45:56 4553f90a834ea32ff844303da3f6f18c9f091635
  Build Time:  2022-11-28 20:31:52
```

代码如下：

```
PS E:\server> gf run main.go --args "test"
build: main.go
go build -o ./\main.exe  main.go
./\main.exe test
build running error: exec: "E:\\server\\main.exe test": file does not exist
```

**Comment by FZUKingDuck** [comment]
![image](https://user-images.githubusercontent.com/31122754/215411482-ef3a3437-78ee-488f-8373-1bb5d8020848.png)
cmd/gf/internal/cmd/cmd_run.go文件里，把启动调用的命令参数改一下重新编译就好了。windows 下main.exe test好像会被识别成一个文件，导致路径找不到。

**Comment by hailaz** [comment]
> ![image](https://user-images.githubusercontent.com/31122754/215411482-ef3a3437-78ee-488f-8373-1bb5d8020848.png) cmd/gf/internal/cmd/cmd_run.go文件里，把启动调用的命令参数改一下重新编译就好了。windows 下main.exe test好像会被识别成一个文件，导致路径找不到。

可以，我pr修复一下
