### ISSUE TITLE
need support for Chinese table name in ORM

### ISSUE THREAD

**Issue by danfate** [gogf/gf#2386]
### 1. What version of `Go` and system type/arch are you using?
go 1.18 macOS/amd64

### 2. What version of `GoFrame` are you using?
github.com/gogf/gf/v2 v2.2.5

### 3. Can this issue be re-produced with the latest release?
yes

### 4. What did you do?

mysql表名包含中文时，insert数据失败

定位了下，gdb.go中指定了regularFieldNameRegPattern = `^[\w\.\-]+$` 匹配不了中文字符，golang的\w只能匹配ASCII

比如fmt.Println(gregex.IsMatchString(`^[\w\.\-]+$`, "test_performance_备份1"))会返回false

gdb_core_structure.go文件中的guessPrimaryTableName方法，会因此返回空的表名

导致mappingAndFilterData方法，拿到的fieldsMap会为空，
【fieldsMap, err := c.db.TableFields(ctx, c.guessPrimaryTableName(table), schema)】

最后导致插入失败

### 5. What did you expect to see?

插入成功

### 6. What did you see instead?

报错：Column count doesn't match value count at row 1, INSERT INTO test_performance_备份1(``) VALUES(),(),(),()

**Comment by danfate** [comment]
测试了下，把正则改为`^[\w\p{Han}\.\-]+$`可以正确处理中文表名并插入，但是不知道这样改会不会引入别的bug。

**Comment by gqcn** [comment]
> 测试了下，把正则改为`^[\w\p{Han}\.\-]+$`可以正确处理中文表名并插入，但是不知道这样改会不会引入别的bug。

这样也只能支持中文，不支持其他地域编码。

**Comment by UrsaMajor-Alioth** [comment]
你好，支持中文表名的建议不会被采纳吗？
