### ISSUE TITLE
nil pointer exception when using sqlite in arm

### ISSUE THREAD

**Issue by mage0991** [gogf/gf#2387]
数据库使用的是sqlite，在windows和centos中可以按预期运行程序，但是在arm架构系统是Linux buildroot 3.10.108的电脑上查询数据库抛出了异常。尝试过升级goframe到最新版本，尝试过更换数据库驱动为sqlite3。我把异常贴在下面。

go的版本是：go1.19.1
goframe框架版本是：v2.2.1

1. exception recovered
   1).  go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.func1
        C:/Users/10266/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.11.1/trace/span.go:383
   2).  go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End
        C:/Users/10266/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.11.1/trace/span.go:415
   3).  modernc.org/sqlite/lib.Xsqlite3WhereBegin
        C:/Users/10266/go/pkg/mod/modernc.org/sqlite@v1.19.2/lib/sqlite_linux_arm.go:104599
   4).  modernc.org/sqlite/lib.Xsqlite3Select
        C:/Users/10266/go/pkg/mod/modernc.org/sqlite@v1.19.2/lib/sqlite_linux_arm.go:90411
   5).  modernc.org/sqlite/lib.yy_reduce
        C:/Users/10266/go/pkg/mod/modernc.org/sqlite@v1.19.2/lib/sqlite_linux_arm.go:110139
   6).  modernc.org/sqlite/lib.Xsqlite3Parser
        C:/Users/10266/go/pkg/mod/modernc.org/sqlite@v1.19.2/lib/sqlite_linux_arm.go:111694
   7).  modernc.org/sqlite/lib.Xsqlite3RunParser
        C:/Users/10266/go/pkg/mod/modernc.org/sqlite@v1.19.2/lib/sqlite_linux_arm.go:112417
   8).  modernc.org/sqlite/lib.sqlite3Prepare
        C:/Users/10266/go/pkg/mod/modernc.org/sqlite@v1.19.2/lib/sqlite_linux_arm.go:84550
   9).  modernc.org/sqlite/lib.sqlite3LockAndPrepare
        C:/Users/10266/go/pkg/mod/modernc.org/sqlite@v1.19.2/lib/sqlite_linux_arm.go:84633
   10). modernc.org/sqlite/lib.Xsqlite3_prepare_v2
        C:/Users/10266/go/pkg/mod/modernc.org/sqlite@v1.19.2/lib/sqlite_linux_arm.go:84700
   11). modernc.org/sqlite/lib.Xsqlite3_exec
        C:/Users/10266/go/pkg/mod/modernc.org/sqlite@v1.19.2/lib/sqlite_linux_arm.go:79512
   12). modernc.org/sqlite/lib.Xsqlite3InitOne
        C:/Users/10266/go/pkg/mod/modernc.org/sqlite@v1.19.2/lib/sqlite_linux_arm.go:84184
   13). modernc.org/sqlite/lib.Xsqlite3Init
        C:/Users/10266/go/pkg/mod/modernc.org/sqlite@v1.19.2/lib/sqlite_linux_arm.go:84261
   14). modernc.org/sqlite/lib.Xsqlite3ReadSchema
        C:/Users/10266/go/pkg/mod/modernc.org/sqlite@v1.19.2/lib/sqlite_linux_arm.go:84288
   15). modernc.org/sqlite/lib.Xsqlite3Pragma
        C:/Users/10266/go/pkg/mod/modernc.org/sqlite@v1.19.2/lib/sqlite_linux_arm.go:81191
   16). modernc.org/sqlite/lib.yy_reduce
        C:/Users/10266/go/pkg/mod/modernc.org/sqlite@v1.19.2/lib/sqlite_linux_arm.go:111161
   17). github.com/glebarez/go-sqlite.(*conn).prepareV2
        C:/Users/10266/go/pkg/mod/github.com/glebarez/go-sqlite@v1.19.2/sqlite.go:1245
   18). github.com/glebarez/go-sqlite.(*stmt).query
        C:/Users/10266/go/pkg/mod/github.com/glebarez/go-sqlite@v1.19.2/sqlite.go:605
   19). github.com/glebarez/go-sqlite.(*conn).query
        C:/Users/10266/go/pkg/mod/github.com/glebarez/go-sqlite@v1.19.2/sqlite.go:1480
   20). github.com/glebarez/go-sqlite.(*conn).QueryContext
        C:/Users/10266/go/pkg/mod/github.com/glebarez/go-sqlite@v1.19.2/sqlite_go18.go:38
   21). github.com/gogf/gf/v2/database/gdb.(*Core).DoCommit
        C:/Users/10266/go/pkg/mod/github.com/gogf/gf/v2@v2.2.1/database/gdb/gdb_core_underlying.go:206
   22). github.com/gogf/gf/v2/database/gdb.(*Core).DoQuery
        C:/Users/10266/go/pkg/mod/github.com/gogf/gf/v2@v2.2.1/database/gdb/gdb_core_underlying.go:74
   23). github.com/gogf/gf/v2/database/gdb.(*Core).DoSelect
        C:/Users/10266/go/pkg/mod/github.com/gogf/gf/v2@v2.2.1/database/gdb/gdb_core.go:155
   24). github.com/gogf/gf/contrib/drivers/sqlite/v2.(*Driver).TableFields
        C:/Users/10266/go/pkg/mod/github.com/gogf/gf/contrib/drivers/sqlite/v2@v2.2.1/sqlite.go:152
   25). github.com/gogf/gf/v2/database/gdb.(*DriverWrapperDB).TableFields.func1
        C:/Users/10266/go/pkg/mod/github.com/gogf/gf/v2@v2.2.1/database/gdb/gdb_driver_wrapper_db.go:80
   26). github.com/gogf/gf/v2/container/gmap.(*StrAnyMap).doSetWithLockCheck
        C:/Users/10266/go/pkg/mod/github.com/gogf/gf/v2@v2.2.1/container/gmap/gmap_hash_str_any_map.go:217
   27). github.com/gogf/gf/v2/container/gmap.(*StrAnyMap).GetOrSetFuncLock
        C:/Users/10266/go/pkg/mod/github.com/gogf/gf/v2@v2.2.1/container/gmap/gmap_hash_str_any_map.go:254
   28). github.com/gogf/gf/v2/database/gdb.(*DriverWrapperDB).TableFields
        C:/Users/10266/go/pkg/mod/github.com/gogf/gf/v2@v2.2.1/database/gdb/gdb_driver_wrapper_db.go:78
   29). github.com/gogf/gf/v2/database/gdb.(*Model).TableFields
        C:/Users/10266/go/pkg/mod/github.com/gogf/gf/v2@v2.2.1/database/gdb/gdb_model_utility.go:38
   30). github.com/gogf/gf/v2/database/gdb.(*Model).mappingAndFilterToTableFields
        C:/Users/10266/go/pkg/mod/github.com/gogf/gf/v2@v2.2.1/database/gdb/gdb_model_utility.go:56
   31). github.com/gogf/gf/v2/database/gdb.(*Model).getFieldsFrom
        C:/Users/10266/go/pkg/mod/github.com/gogf/gf/v2@v2.2.1/database/gdb/gdb_model_fields.go:212
   32). github.com/gogf/gf/v2/database/gdb.(*Model).Fields
        C:/Users/10266/go/pkg/mod/github.com/gogf/gf/v2@v2.2.1/database/gdb/gdb_model_fields.go:30
   33). github.com/gogf/gf/v2/database/gdb.(*Model).doStruct
        C:/Users/10266/go/pkg/mod/github.com/gogf/gf/v2@v2.2.1/database/gdb/gdb_model_select.go:235
   34). github.com/gogf/gf/v2/database/gdb.(*Model).Scan
        C:/Users/10266/go/pkg/mod/github.com/gogf/gf/v2@v2.2.1/database/gdb/gdb_model_select.go:326
   35). box/internal/logic/user.sUser.SignIn
        C:/hongmen/code/edgebox/软件/box/internal/logic/user/user.go:52
   36). box/internal/controller.(*cUser).SignIn
        C:/hongmen/code/edgebox/软件/box/internal/controller/user.go:28
   37). github.com/gogf/gf/v2/net/ghttp.(*middleware).callHandlerFunc.func1
        C:/Users/10266/go/pkg/mod/github.com/gogf/gf/v2@v2.2.1/net/ghttp/ghttp_request_middleware.go:152
   38). github.com/gogf/gf/v2/net/ghttp.niceCallFunc
        C:/Users/10266/go/pkg/mod/github.com/gogf/gf/v2@v2.2.1/net/ghttp/ghttp_func.go:55
   39). github.com/gogf/gf/v2/net/ghttp.(*middleware).callHandlerFunc
        C:/Users/10266/go/pkg/mod/github.com/gogf/gf/v2@v2.2.1/net/ghttp/ghttp_request_middleware.go:129
   40). github.com/gogf/gf/v2/net/ghttp.(*middleware).Next.func1
        C:/Users/10266/go/pkg/mod/github.com/gogf/gf/v2@v2.2.1/net/ghttp/ghttp_request_middleware.go:75
   41). github.com/gogf/gf/v2/util/gutil.TryCatch
        C:/Users/10266/go/pkg/mod/github.com/gogf/gf/v2@v2.2.1/util/gutil/gutil.go:56
   42). github.com/gogf/gf/v2/net/ghttp.(*middleware).Next
        C:/Users/10266/go/pkg/mod/github.com/gogf/gf/v2@v2.2.1/net/ghttp/ghttp_request_middleware.go:49
   43). github.com/gogf/gf/v2/net/ghttp.MiddlewareHandlerResponse
        C:/Users/10266/go/pkg/mod/github.com/gogf/gf/v2@v2.2.1/net/ghttp/ghttp_middleware_handler_response.go:25
   44). github.com/gogf/gf/v2/net/ghttp.(*middleware).Next.func1.1
        C:/Users/10266/go/pkg/mod/github.com/gogf/gf/v2@v2.2.1/net/ghttp/ghttp_request_middleware.go:55
   45). github.com/gogf/gf/v2/net/ghttp.(*middleware).Next.func1
        C:/Users/10266/go/pkg/mod/github.com/gogf/gf/v2@v2.2.1/net/ghttp/ghttp_request_middleware.go:54
2. runtime error: invalid memory address or nil pointer dereference

**Comment by gqcn** [comment]
@mage0991 建议使用最新版本执行，若有错误贴出最新版本的完整堆栈信息。
