### ISSUE TITLE
Run the grpc server according to the official example and report an error directly. Where is the problem?

### ISSUE THREAD

**Issue by z10086** [gogf/gf#2394]
### 1. What version of `Go` and system type/arch are you using?
go version go1.19.3 windows/amd64

### 2. What version of `GoFrame` are you using?
GoFrame CLI Tool v2.2.5, https://goframe.org
GoFrame Version: cannot find go.mod
CLI Installed At: c:\windows\gf.exe
CLI Built Detail:
  Go Version:  go1.17.13
  GF Version:  v2.2.5
  Git Commit:  2022-11-25 10:45:56 4553f90a834ea32ff844303da3f6f18c9f091635
  Build Time:  2022-11-28 20:31:52

### 4. What did you do?
run the example https://goframe.org/pages/viewpage.action?pageId=3673718

### 5. What did you expect to see?

run as in the docs

### 6. What did you see instead?

GOROOT=C:\Program Files\Go #gosetup
GOPATH=C:\Users\unknow\go #gosetup
"C:\Program Files\Go\bin\go.exe" build -o C:\Users\unknow\AppData\Local\Temp\GoLand\___1go_build_github_com_gogf_gf_example_trace_grpc_with_db_server.exe github.com/gogf/gf/example/trace/grpc_with_db/server #gosetup
C:\Users\unknow\AppData\Local\Temp\GoLand\___1go_build_github_com_gogf_gf_example_trace_grpc_with_db_server.exe
2023-01-11 16:25:05.549 [DEBU] set default registry using etcd service, address:
 127.0.0.1:2379
2023-01-11 16:25:05.575 [DEBU] service register: &{Head: Deployment: Namespace:
Name:demo Version: Endpoints:172.16.1.204:2591 Metadata:map[protocol:grpc]}
{"level":"warn","ts":"2023-01-11T16:25:10.578+0800","logger":"etcd-client","caller":"v3@v3.5.4/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000393180/
127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1
:2379: connectex: No connection could be made because the target machine actively refused it.\""}
2023-01-11 16:25:10.579 [FATA] etcd grant failed with keepalive ttl "10s": context deadline exceeded
1. etcd grant failed with keepalive ttl "10s"
   1).  github.com/gogf/gf/contrib/registry/etcd/v2.(*Registry).Register
        G:/gotmp/gf-master/contrib/registry/etcd/etcd_registrar.go:22
   2).  github.com/gogf/gf/v2/net/gsvc.Register
        G:/gotmp/gf-master/net/gsvc/gsvc_registry.go:24
   3).  github.com/gogf/katyusha/krpc.(*GrpcServer).Run
        C:/Users/unknow/go/pkg/mod/github.com/gogf/katyusha@v0.4.1-0.20220620125113-f55d6f739773/krpc/krpc_grpc_server.go:143
   4).  main.main
        G:/gotmp/gf-master/example/trace/grpc_with_db/server/main.go:40
2. context deadline exceeded

Stack:
1.  github.com/gogf/katyusha/krpc.(*GrpcServer).Run
    C:/Users/unknow/go/pkg/mod/github.com/gogf/katyusha@v0.4.1-0.20220620125113-f55d6f739773/krpc/krpc_grpc_server.go:144
2.  main.main
    G:/gotmp/gf-master/example/trace/grpc_with_db/server/main.go:40

**Comment by gqcn** [comment]
@z10086 You need a service registry running locally, it is suggested using etcd.

**Comment by z10086** [comment]
> @z10086 You need a service registry running locally, it is suggested using etcd.

I started the server under the etcd folder in the example, but the same error log was reported. Please tell me how to start the process in the grpc example that can run normally.
