### ISSUE TITLE
gf生成dao中tx类型不符合框架要求

### ISSUE THREAD

**Issue by qq413434162** [gogf/gf#2396]
go.mod
```
go 1.17
github.com/gogf/gf/v2 v2.2.6
```

gf version    
GoFrame CLI Tool v2.2.6, https://goframe.org
GoFrame Version: v2.2.6 in current go.mod

在gf gen dao执行后生成,出现报错
```shell
cannot use f (type func(context.Context, gdb.TX) error) as type func(context.Context, *gdb.TX) error in argument to dao.Ctx(ctx).Transaction
```

核心原因是
生成的dao问题
f func(ctx context.Context, tx gdb.TX) => f func(ctx context.Context, tx *gdb.TX)才不会有报错
```go
Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
```

**Comment by zcyc** [comment]
试了一下没有问题呀。
- v2.2.6 cli 生成的代码在 v2.2.6 框架能跑起来。
- v2.3.0 cli 生成的代码在 v2.3.0 框架能跑起来。

**Comment by houseme** [comment]
https://github.com/gogf/gf/pull/2397

**Comment by gqcn** [comment]
升级使用最新的cli工具即可

**Comment by goodking-bq** [comment]
> 升级使用最新的cli工具即可
gf -v
GoFrame CLI Tool v2.3.2, https://goframe.org
GoFrame Version: v1.16.9 in current go.mod
CLI Installed At: C:\Users\goodk\go\bin\gf.exe
CLI Built Detail:
  Go Version:  go1.17.13
  GF Version:  v2.3.2
  Git Commit:  2023-02-15 14:13:32 ad737ded3cd1354cb6f4208f11fcd8f99f94c5f3
  Build Time:  2023-02-15 14:17:00

此版本仍然报这错。
![image](https://user-images.githubusercontent.com/7803202/219325227-8220ab66-fa05-4a80-97d2-eda773a4e681.png)

**Comment by houseme** [comment]
> > 升级使用最新的cli工具即可
> > gf -v
> > GoFrame CLI Tool v2.3.2, https://goframe.org
> > GoFrame Version: v1.16.9 in current go.mod
> > CLI Installed At: C:\Users\goodk\go\bin\gf.exe
> > CLI Built Detail:
> > Go Version:  go1.17.13
> > GF Version:  v2.3.2
> > Git Commit:  2023-02-15 14:13:32 [ad737de](https://github.com/gogf/gf/commit/ad737ded3cd1354cb6f4208f11fcd8f99f94c5f3)
> > Build Time:  2023-02-15 14:17:00
> 
> 此版本仍然报这错。 ![image](https://user-images.githubusercontent.com/7803202/219325227-8220ab66-fa05-4a80-97d2-eda773a4e681.png)
@goodking-bq 
```shell
gf fix
```
