### ISSUE TITLE
在新版本下orm.Scan的变量属性是*gtime.Time的类型的默认值变成nil

### ISSUE THREAD

**Issue by qq413434162** [gogf/gf#2400]
entity.A {
CheckDate *gtime.time
}

数据库记录check_date is null

var a entity.A
在gf2.2.6版本下
orm.Scan(&a)
a.CheckDate is nil

在gf2.1.4版本下
orm.Scan(&a)
a.CheckDate is 0000-01-01 00:00:00

问题:我找了版本发布记录,好像没有这块说明,所以这是bug还是特性?

**Comment by gqcn** [comment]
@qq413434162 我记得之前有个BUG后面修复了，试试最新的版本？
