### ISSUE TITLE
g.Dump() will keep the disk writing

### ISSUE THREAD

**Issue by wanov** [gogf/gf#2406]
go 1.17, windows10 64
GoFrame CLI Tool v2.1.2, https://goframe.org
GoFrame Version: v2.2.0 in current go.mod

try this code please
```
func main() {
	type PaginateIn struct {
		Model *gdb.Model
	}
	in := &PaginateIn{
		Model: dao.SaleDtl.Ctx(gctx.New()).OrderDesc("id"),
	}
	g.Dump(in)
}
```
dao.SaleDtl create by: gf gen dao
change another dao.xxx also

nothing print,the disk full writing,use ctrl+c

3. Can this issue be re-produced with the latest release?
GoFrame Version: v2.3.0
out print:  too many errors
and end of running, disk is ok

**Comment by gqcn** [comment]
@wanov Please provide the full codes that can reproduce this issue.

**Comment by wanov** [comment]
> 

https://github.com/wanov/gftest
here is my code

**Comment by wanov** [comment]
@gqcn sorry,it's my OS
build exe to another computer have no question, just report something
