### ISSUE TITLE
gvalid使用CheckStruct时，用msgs参数覆盖gvalid tag错误提示信息的问题。

### ISSUE THREAD

**Issue by hailaz** [gogf/gf#241]
https://goframe.org/util/gvalid/checkstruct
示例2中使用msgs覆盖gvalid tag中的错误提示信息时，只能使用别名不能使用struct字段名，导致示例2中的代码没有覆盖效果。（前提是gvalid tag中的别名存在）

**Comment by hailaz** [comment]
rules的覆盖也有同样的问题。

**Comment by johngcn** [comment]
@hailaz 恩，是个问题，如果带有别名时会需要使用别名来定义`rules`和`msgs`，你看能不能来改进下。
