### ISSUE TITLE
强烈建议封装一套Websocker服务，开箱即用的

### ISSUE THREAD

**Issue by richfuns** [gogf/gf#242]
### 1. What version of `Go` and system type/arch are you using?

go1.12.6, Linux mint 19.1

### 2. What version of `GoFrame` are you using?

v1.7.3

### 4. What did you do?

游戏服务开发

### 5. What did you expect to see?

期待能封装一套开箱即用的websocket接口

### 6. What did you see instead?

目前框架好像只是集成了websocket库

**Comment by johngcn** [comment]
@richfuns `GF`集成了`WebSocket`功能 开发文档参考 https://goframe.org/net/ghttp/websocket/index ，封装的第三方包为成熟稳定的 github.com/gorilla/websocket 。如有建议欢迎随时提。

**Comment by richfuns** [comment]
@johngcn  谢谢回复，基于这个第三方的可能还需要做大量的二次封装，我的意思是说最好能封装一套机制，开箱即用哈
