### ISSUE TITLE
*gtime.time类型的字段插入数据库的值和日志打印的sql不一样

### ISSUE THREAD

**Issue by yidashi** [gogf/gf#2434]
gf version 2.2.1

demo代码
```
dao.Order.Ctx(gctx.New()).Where("id=1").Data(do.Order{
  CancelTime: gtime.Now(),
}).Update()
```

日志显示sql
 ```
UPDATE `order` SET `cancel_time`='2023-02-08 18:47:01' WHERE id=1
```
实际插入mysql的值比这个小8小时

系统时区mysql时区都调成+8:00了，配置里db的link也参考文档加了 `loc=Local&parseTime=true`

**Comment by niluan304** [comment]
试试指定时区：
timezone = "Asia/Shanghai"

可以参考这里 #1895

**Comment by yidashi** [comment]
> 试试指定时区： timezone = "Asia/Shanghai"
> 
> 可以参考这里 #1895

timezone 确实可以，文档里没有看到这个配置，只有loc那个，但是loc不生效。

非常感谢
