### ISSUE TITLE
gdb增加对数据库关键字的自动处理

### ISSUE THREAD

**Issue by johngcn** [gogf/gf#244]
需求背景：`gdb`目前在关键字处理上不够完善，部分参数类型支持了对字段参数的安全符号使用，部分没有，特别是查询操作中如果带有关键字的话是不支持的，执行的时候会直接报错，如：
```go
g.DB().Table("user_access_key").Where("key=?", key).All()
```
由于字段`key`为关键字，该操作执行将会报错。

实现难度：约5星，太难了，难得我都不想实现这个功能，主要是意义不是特别大。

改进建议：在`gdb`底层数据库操作方法`formatWhere`方法中统一使用正则表达式处理关键字，增加安全符号使用。当然，得在`gdb`中增加私有的包变量配置这些数据库关键字。

**Comment by iReadX** [comment]
这个真的太麻烦了，要根据各种数据库进行匹配关键字处理`insert`、`update`....等等语句中的查询部分、条件部分、外联条件部分、分组部分、排序部分中的关键字处理....

**Comment by alai04** [comment]
可以先实现一些简单的，比如在生成的sql中，对独立的表名、字段名都统一加上backquote。例如：
```sql
INSERT INTO `values` (`id`, `key`, `val`) VALUES (1, 'KeyForTest', 'ValForTest');
```
至于用户自己写的where中出现的字段名，应该由用户自己负责加backquote。全部由gdb来检查确实困难且影响性能。

**Comment by lvshutao** [comment]
个人觉得字段名还是不要用关键字的好；
添加双引号那个，只适用 mysql 吧，如果要兼容其它引擎，恐怕到时会更麻烦

**Comment by johngcn** [comment]
`gdb`对部分关键的方法对其中的关键字进行了一些改进，但没有办法统一做关键字处理。
