### ISSUE TITLE
【需求】通过 entity 生成对应的数据库表

### ISSUE THREAD

**Issue by lusson-luo** [gogf/gf#2440]
### 1. What version of `Go` and system type/arch are you using?

go1.19.3 darwin/amd64

### 2. What version of `GoFrame` are you using?

2.3.1

### 3. Can this issue be re-produced with the latest release?

是的

### 4. What did you do?

通过 entity 自动生成对应的数据库表，类似 gorm 的 AutoMigrate

<img width="622" alt="image" src="https://user-images.githubusercontent.com/19859400/218036005-02cb4334-6441-44e8-9b59-2e1ce136feab.png">

**Comment by dyzsoft** [comment]
这个需求明确表示不会实现

**Comment by niluan304** [comment]
[gqcn](https://github.com/gqcn) commented [on Oct 14, 2020](https://github.com/gogf/gf/issues/943#issuecomment-708390027)
`Sorry but I do not think it a good feature and will not be considered`
#943 #475 #779
