### ISSUE TITLE
about gdb, why emtpyData.Scan(&entity.Strcut{}) will get sql.ErrNoRows, but *entity.Strcut will not？

### ISSUE THREAD

**Issue by niluan304** [gogf/gf#2443]
### 1. ENV
```
go version go1.19.1 windows/amd64
gf: v2.2.5
mysql: 5.7.40
```

### 2. Can this issue be re-produced with the latest release?
I'm not sure.

### 3. What did you do?
```go
var (
  ctx    = context.TODO()
  m      = dao.CActive.Ctx(ctx)
  rowNew = new(entity.CActive)
  rowNil *entity.CActive
)

errNil := m.Where("1 = 2").Scan(&rowNil)
errNew := m.Where("1 = 2").Scan(&rowNew)

g.Log().Debug(ctx, errNil == nil)           // true
g.Log().Debug(ctx, errNew == sql.ErrNoRows) // true
```

sql :
```mysql
[rows:0  ] SELECT * FROM c_active WHERE (1 = 2) AND deleted_at IS NULL LIMIT 1
```

### 4. my question
Why `[rows: 0].Scan(rowNew) `will get `sql.ErrNoRows`, but `rowNil` will not？

I traced the code and found that the handling error:
https://github.com/gogf/gf/blob/4553f90a834ea32ff844303da3f6f18c9f091635/database/gdb/gdb_type_record.go#L48-L57

Or, the question is equivalent to, why is it designed as
```go
g.Log().Debug(ctx, !empty.IsNil(rowNew, true)) // ture
g.Log().Debug(ctx, !empty.IsNil(rowNil, true)) // false
```

Related issues: #349, #449

**Comment by gqcn** [comment]
@niluan304 
- If given empty(`nil`) pointer to function `Scan`, it will initialize it with queried value if any records found. Other wise, it does nothing and the pinter is still empty(`nil`). 
- If given an empty struct that has default value to function `Scan`, it fills it with queried value if any records found. Other wise it returns an error `sql.ErrNoRows` to notice it found no records and the struct has only default value. The default value of struct can affect the business scenario so you need some way to notice it.

**Comment by niluan304** [comment]
Sorry, I should read the manual carefully: 
[ORM结果处理-为空判断](https://goframe.org/pages/viewpage.action?pageId=47699230)

> 五、struct对象
> 关于Struct转换对象来说会有一点不一样，我们直接看例子吧。
> 
> 当传递的对象本身就是一个空指针时，如果查询到数据，那么会在内部自动创建这个对象；如果没有查询到数据，那么这个空指针仍旧是一个空指针，内部并不会做任何处理。
