### ISSUE TITLE
mysql orm 兼容有问题

### ISSUE THREAD

**Issue by liqkj** [gogf/gf#2446]
使用的是阿里云 AnalyticDB MySQL 版本数据库，使用 in查询数据过多会导致 报错 
错误信息  commands out of sync. Did you run multiple statements at once?
已经排查数据库本身问题，没有发现问题，
复现数据   11,28,51,13,15,25,27,30,41,42,43,44,45,46,47,48,49,50,52,53,54,55,56,57,58,59,64,65,66,75,76,79,80,81,82,83,84,85,86,87,88,89,90,91,93,94,95,98,99,100,101,102,104,105,107,108,109,110,111,112,113,114,115,116,117,118,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,246,251,0，300,301,302,308

提供复现数据库测试环境（联系我）
vx：18282669832

**Comment by gqcn** [comment]
请排查阿里云数据库限制。

**Comment by liqkj** [comment]
![image](https://user-images.githubusercontent.com/29451637/218898704-d161584f-d1ff-4360-b5bb-71164f229e1a.png)
![1676423135415](https://user-images.githubusercontent.com/29451637/218898717-8da73fb2-ace2-41c1-91a3-25e2b26b825a.jpg)
帮忙看一下 是哪个参数影响的呀

**Comment by liqkj** [comment]
打断点看了一下是 go-sql-driver 这个包 检查数据同步没有通过导致的
![image](https://user-images.githubusercontent.com/29451637/218915844-75b12a63-eaf0-4823-88b8-eaccb986ce8b.png)
![image](https://user-images.githubusercontent.com/29451637/218915916-21e35034-6ef1-46fd-b879-f0bc74e4fe56.png)
具体什么原因，没有看懂
