### ISSUE TITLE
gf gen service 生成struct返回service的函数时,无法实现自动注册

### ISSUE THREAD

**Issue by sanrentai** [gogf/gf#2455]
gf gen service 生成struct返回service的函数时,无法实现自动注册

logic 代码
```
type sCurd struct {
	ctx   context.Context
	title string
}

func init() {
	service.RegisterCurd(New())
}

func New() *sCurd {
	return &sCurd{}
}

// 这个函数会导致无法自动注册
func (c *sCurd) Init(ctx context.Context, title string) service.ICurd {
	return &sCurd{
		ctx:   ctx,
		title: title,
	}
}
```

### 1. What version of `Go` and system type/arch are you using?
go version go1.18.4 windows/amd64

### 2. What version of `GoFrame` are you using?
GF Version:  v2.3.1

### 3. Can this issue be re-produced with the latest release?

yes

### 4. What did you do?
gf gen service

### 5. What did you expect to see?

```
type (
	ICurd interface {
		Init(ctx context.Context, title string) ICurd
	}
)

var (
	localCurd ICurd
)

func Curd() ICurd {
	if localCurd == nil {
		panic("implement not found for interface ICurd, forgot register?")
	}
	return localCurd
}

func RegisterCurd(i ICurd) {
	localCurd = i
}
```

### 6. What did you see instead?

```
type (
	ICurd interface {
		Init(ctx context.Context, title string) ICurd
	}
)
```
缺少自动注册的部分

**Comment by gqcn** [comment]
@sanrentai 目前这种设计是检测定义的方法中如果存在初始化接口对象的方法，那么就不会生成对应的注册方法。当然有点BUG就是你返回自身接口对象。这里去掉定义的方法中，返回接口对象的返回值就可以了。
