### ISSUE TITLE
need support for generic type in router function

### ISSUE THREAD

**Issue by agzou** [gogf/gf#2457]
### 1. What version of `Go` and system type/arch are you using?
go 1.19

### 2. What version of `GoFrame` are you using?
v2.3.2

### 4. What did you do?
```go
type ListMessageReq struct {
	g.Meta    `path:"/list" method:"get"`
	StartTime int64
	EndTime   int64
}
type ListMessageRes struct {
	g.Meta
	Title   string
	Content string
}
type BaseRes[T any] struct {
	g.Meta
	Code int
	Data T
	Msg  string
}
func (c *cMessage) List(ctx context.Context, req *v1.ListMessageReq) (res *v1.BaseRes[*v1.ListMessageRes], err error) {
	return res, err
}

```
报错日志：
[FATA] invalid struct naming for response: defined as "*v1.BaseRes[*xxx/api/v1.ListMessageRes]", but it should be named with "Res" suffix like "XxxRes"

**是不是要考虑泛型情况下，返回值名称校验？**

**Comment by gqcn** [comment]
@agzou 我看了一下，可以调整下路由注册时的名称校验，欢迎提供PR改进。

**Comment by agzou** [comment]
@gqcn 好的，我研究下看看能不能提交PR

**Comment by agzou** [comment]
> @agzou 我看了一下，可以调整下路由注册时的名称校验，欢迎提供PR改进。
好的，我研究下，抽空提交下PR

**Comment by agzou** [comment]
> @agzou 我看了一下，可以调整下路由注册时的名称校验，欢迎提供PR改进。

@gqcn 好的，我研究下，看看能不能提交PR

**Comment by gqcn** [comment]
@agzou 另外，我想了解一下，你为什么不在`BaseRes`的属性上使用泛型，而不是对这个结构体使用泛型呢?

**Comment by agzou** [comment]
@gqcn `BaseRes` 定义了公共返回的code,msg等字段，其实效果和通过插件统一封装返回结果一样，不过如果定义在接口看起来会方便些，第一眼就知道返回结构，不用再找是不是中间件改了我的返回，这个是从`java`带过来的习惯，基本照搬`java`的接口返回定义

**Comment by gqcn** [comment]
https://github.com/gogf/gf/pull/3297
