### ISSUE TITLE
gvalid进行长度校验容易出错

### ISSUE THREAD

**Issue by r0liang** [gogf/gf#246]
### 1. What version of `Go` and system type/arch are you using?
go version go1.12.6 windows/amd64

### 2. What version of `GoFrame` are you using?
gf v1.7.3

### 3. Can this issue be reproduced with the latest release?
YES

### 4. What did you do?
在struct中使用如下规则
Passwd    string `params:"passwd1"  gvalid:"passwd1 @required|length:2,20|password3||密码强度不足"`
使用gvalid.CheckStruct(user, nil)进行数据校验时，会提示  字段长度为2到0个字符。

### 5. What did you expect to see?
FIX

### 6. What did you see instead?
字段长度为2到0个字符

**Comment by johngcn** [comment]
@r0liang 你好，在`MacOS`下没有复现这个问题，请提供完整可运行复现该问题的代码。

**Comment by r0liang** [comment]
```
package main

import (
	"fmt"
	"github.com/gogf/gf/g/util/gvalid"
)

type reg struct {
	Passed string `params:"passed1" gvalid:"passed1 @required|length:2,20|password3||密码强度不足"`
	User   string `params:"user1"   gvalid:"user1 @required|length:6,20||输入正确的账号"`

}

func main(){
	R := reg{"111111","22222222"}
	err := gvalid.CheckStruct(R,nil)
	if err != nil{
		fmt.Println(err.String())
	}
}
```
问题出在```||输入正确的账号```这里，如果不加上则不会报错

**Comment by johngcn** [comment]
@r0liang 你的规则使用有误，校验规则请参考：https://goframe.org/util/gvalid/checkstruct , 你的测试代码应当修改如下：
```go
package main

import (
	"fmt"
	"github.com/gogf/gf/g/util/gvalid"
)

type reg struct {
	Passed string `params:"passed1" gvalid:"passed1 @required|length:2,20|password3#||密码强度不足"`
	User   string `params:"user1"   gvalid:"user1 @required|length:6,20#|输入正确的账号"`
}

func main() {
	R := reg{"111111", "22222222"}
	err := gvalid.CheckStruct(R, nil)
	if err != nil {
		fmt.Println(err.Maps())
	}
}
```

**Comment by r0liang** [comment]
sorry
