### ISSUE TITLE
Hope to support graceful shutdown

### ISSUE THREAD

**Issue by windvalley** [gogf/gf#2469]
### 1. What version of `Go` and system type/arch are you using?

go version go1.17.6 darwin/amd64

### 2. What version of `GoFrame` are you using?

github.com/gogf/gf/v2 v2.3.2

### 3. Can this issue be re-produced with the latest release?

yes

### 4. What did you do?

1.  gf init gf2demo && cd gf2demo

2. vi internal/controller/hello.go

```go
func (c *cHello) Hello(ctx context.Context, req *v1.HelloReq) (res *v1.HelloRes, err error) {
	time.Sleep(time.Second * 15)  // ***** Add this line *****
	g.RequestFromCtx(ctx).Response.Writeln("Hello World!")
	return
}
```

3. gf build main.go

4. ./main
Output:

```text
2023-02-22 21:03:59.868 [INFO] pid[29185]: http server started listening on [:8000]
2023-02-22 21:03:59.868 [INFO] swagger ui is serving at address: http://127.0.0.1:8000/swagger/
2023-02-22 21:03:59.868 [INFO] openapi specification is serving at address: http://127.0.0.1:8000/api.json

  ADDRESS | METHOD |   ROUTE    |                             HANDLER                             |           MIDDLEWARE
----------|--------|------------|-----------------------------------------------------------------|----------------------------------
  :8000   | ALL    | /*         | github.com/gogf/gf/v2/net/ghttp.internalMiddlewareServerTracing | GLOBAL MIDDLEWARE
----------|--------|------------|-----------------------------------------------------------------|----------------------------------
  :8000   | ALL    | /api.json  | github.com/gogf/gf/v2/net/ghttp.(*Server).openapiSpec           |   
----------|--------|------------|-----------------------------------------------------------------|----------------------------------
  :8000   | GET    | /hello     | gf2demo/internal/controller.(*cHello).Hello                     | ghttp.MiddlewareHandlerResponse
----------|--------|------------|-----------------------------------------------------------------|----------------------------------
  :8000   | ALL    | /swagger/* | github.com/gogf/gf/v2/net/ghttp.(*Server).swaggerUI             | HOOK_BEFORE_SERVE
----------|--------|------------|-----------------------------------------------------------------|----------------------------------
```

5. Execute `curl localhost:8000/hello` in another terminal window, and it will hang up for response.

6. The last step: Execute `kill -SIGTERM 29185` to shutdown the server.

### 5. What did you expect to see?

The server waits for in-progress requests(step 6) to complete before shutting down the service.

And Step 5 output: `Hello World!`

### 6. What did you see instead?

The server terminated the service immediately, and ouput as follows:

```text
2023-02-22 21:04:13.647 29185: server gracefully shutting down by signal: terminated
2023-02-22 21:04:13.648 [INFO] pid[29185]: all servers shutdown
```

And Step 5 ouptut: `curl: (52) Empty reply from server`

**Comment by LonelySally** [comment]
config.yaml : 
server:
  graceful: true
  gracefulTimeout: 20

**Comment by windvalley** [comment]
> config.yaml : server: graceful: true gracefulTimeout: 20

I have tested this configuration before, it only works for graceful restart, not for graceful shutdown.

**Comment by gqcn** [comment]
@windvalley It seams graceful shutdown is not supported in signal.
