### ISSUE TITLE
it's suggested no fields filtering in function Fields, cause it a little bit slow with no fields cache in first query

### ISSUE THREAD

**Issue by wushibo** [gogf/gf#2489]
![image](https://user-images.githubusercontent.com/30285523/222873362-15393c16-f1ec-4dc1-b673-180f0d8566df.png)

**Comment by gqcn** [comment]
@wushibo English, please.

**Comment by wushibo** [comment]
The speed of mssql is slow
![image](https://user-images.githubusercontent.com/30285523/223603400-8bc91029-e6ef-483d-a056-9306768c08e5.png)
