### ISSUE TITLE
=g.client If there is an uploaded file in the post request, the server will always receive an error

### ISSUE THREAD

**Issue by zhenhua1** [gogf/gf#2511]
![image](https://user-images.githubusercontent.com/22211474/223969113-b07a5c8e-23d9-423b-85cc-ec3687c75969.png)

![image](https://user-images.githubusercontent.com/22211474/223969146-c86b59e7-f8e5-4e7c-bc8e-5824940c5501.png)

换成github.com/go-resty/resty/v2这个包解决了上面的问题

**Comment by gqcn** [comment]
@zhenhua1 This might be caused by your header `Contet-Type`. Please paste the minimum codes that can reproduce this issue.
