### ISSUE TITLE
use  withall if data is empty , i  want to  an empty array, not null

### ISSUE THREAD

**Issue by dingbophp** [gogf/gf#2519]
![image](https://user-images.githubusercontent.com/28505313/224874109-2a6d9d4b-bdb8-403a-b377-85e1bf037f80.png)

![image](https://user-images.githubusercontent.com/28505313/224874076-7896e408-1ff7-47b9-997a-1574790f91ac.png)

![36d02992dbd0e7fa81837cd1108b2e5](https://user-images.githubusercontent.com/28505313/224874683-f0b6ede7-2660-49ba-b34c-178014a79192.png)

### 1. What version of `Go` and system type/arch are you using?
       go version go1.17.1 windows/amd64

### 2. What version of `GoFrame` are you using?
  GF Version:  v2.2.4

### 4. What did you do?

use  withall()  Get the associated data 

### 5. What did you expect to see?

I want to end up with an empty array

### 6. What did you see instead?

i see  null

**Comment by gqcn** [comment]
@dingbophp If no records found, it does not initialize the attributes. If you want a default attribute, please check and assign it with custom values.
