### ISSUE TITLE
third文件夹的text包内，没有language包，导致import报错

### ISSUE THREAD

**Issue by Chenhaolin** [gogf/gf#252]
![image](https://user-images.githubusercontent.com/13374926/61264173-2c473600-a7be-11e9-96f4-31102a050ad8.png)
如图所示，源码里third文件夹下的htmlindex.go这个文件，import时候报错。经过排查发现github.com/gogf/gf/third/golang.org/x/text/路径下没有language包

**Comment by Chenhaolin** [comment]
#文件路径是github.com/gogf/gf/third/golang.org/x/text/encoding/htmlindex/htmlindex.go

**Comment by Chenhaolin** [comment]
`
package htmlindex

import (
	"errors"
	"strings"
	"sync"

	"github.com/gogf/gf/third/golang.org/x/text/encoding"
	"github.com/gogf/gf/third/golang.org/x/text/encoding/internal/identifier"
	"github.com/gogf/gf/third/golang.org/x/text/language"
)

var (
	errInvalidName = errors.New("htmlindex: invalid encoding name")
	errUnknown     = errors.New("htmlindex: unknown Encoding")
	errUnsupported = errors.New("htmlindex: this encoding is not supported")
)

var (
	matcherOnce sync.Once
	matcher     language.Matcher
)

func LanguageDefault(tag language.Tag) string {
	matcherOnce.Do(func() {
		tags := []language.Tag{}
		for _, t := range strings.Split(locales, " ") {
			tags = append(tags, language.MustParse(t))
		}
		matcher = language.NewMatcher(tags, language.PreferSameScript(true))
	})
	_, i, _ := matcher.Match(tag)
	return canonical[localeMap[i]] // Default is Windows-1252.
}

func Get(name string) (encoding.Encoding, error) {
	x, ok := nameMap[strings.ToLower(strings.TrimSpace(name))]
	if !ok {
		return nil, errInvalidName
	}
	return encodings[x], nil
}

func Name(e encoding.Encoding) (string, error) {
	id, ok := e.(identifier.Interface)
	if !ok {
		return "", errUnknown
	}
	mib, _ := id.ID()
	if mib == 0 {
		return "", errUnknown
	}
	v, ok := mibMap[mib]
	if !ok {
		return "", errUnsupported
	}
	return canonical[v], nil
}
`

**Comment by johngcn** [comment]
@Chenhaolin 经排查该包没有使用到，已删除。
