### ISSUE TITLE
glog.Error和 gerror.Wrap 同时用，会打印2遍

### ISSUE THREAD

**Issue by 15951836388** [gogf/gf#253]
glog.Error("test", gerror.Wrap(gerror.New("yyyy"), "xxxx"))
![image](https://user-images.githubusercontent.com/14047483/61279952-a8a33e80-a7e9-11e9-9a43-a578bb670fda.png)

最好gf可以自动处理这种情况。因为代码复杂起来的情况，用户自己估计也很难分清哪里该用gerror.Wrap，哪里该用普通的glog.Error，增加了心智负担

**Comment by johngcn** [comment]
@15951836388 这是你提到的代码`glog.Error("test", gerror.Wrap(gerror.New("yyyy"), "xxxx"))`输出结果：
![image](https://user-images.githubusercontent.com/26347176/61291568-6ab21480-a801-11e9-9cb5-f63e2f3a5876.png)

测试可以这样，正常情况下，当然不会这么用的。实际场景中，多个`error`的产生是分开的，在不同的调用栈中，因此`glog`打印时输出每个`error`对象的堆栈详情是有意义的，特别是调试定位问题的时候相当有用。

而你的问题其实是在于最后`glog`打印出的`Stack`信息。`error`对象在多个调用栈中传递，最终往往会有一个地方会将该对象打印到日志中以便后续分析，而打印错误对象的地方往往也和错误产生的地方不一样，因此这里的`glog.Error`打印出的`Stack`信息往往也是有意义的。当调用者觉得没有必要打印`Stack`信息时，可以使用`glog.Stack(false).Error(xxx)`来实现。

你这行测试代码，错误的产生、调用包裹、日志打印都在同一行中，看起来确实很别扭。

因此`glog`不会因此做调整。

**Comment by 15951836388** [comment]
我这里用glog.error,是因为 write里，正则 判断 
![image](https://user-images.githubusercontent.com/14047483/61339393-2dd13680-a870-11e9-8b75-b5bccd32eccf.png) 来收集错误的
