### ISSUE TITLE
redis adapter is not set, missing configuration or adapter register?

### ISSUE THREAD

**Issue by zyj5127** [gogf/gf#2533]
### 1. What version of `Go` and system type/arch are you using?
go version go1.18.3 darwin/arm64

### 2. What version of `GoFrame` are you using?
GoFrame CLI Tool v2.4.0-beta, https://goframe.org
GoFrame Version: cannot find goframe requirement in go.mod
CLI Installed At: /Users/beer/go/bin/gf
CLI Built Detail:
  Go Version:  go1.17.13
  GF Version:  v2.4.0-beta
  Git Commit:  2023-03-20 10:00:55 0b6798acb5303caebd4427259fa663151f770dd8
  Build Time:  2023-03-20 10:29:05

### 4. What did you do?
按照官网的示例，使用
main.go中的代码：
`func main() {
	var ctx = gctx.New()
	_, err := g.Redis().Set(ctx, "key", "value")
	if err != nil {
		g.Log().Fatal(ctx, err)
	}
	value, err := g.Redis().Get(ctx, "key")
	if err != nil {
		g.Log().Fatal(ctx, err)
	}
	fmt.Println(value.String())
	cmd.Main.Run(gctx.New())
}`

config.yaml中的配置项：

`redis:
  default:
    address: 127.0.0.1:8000
    db:   1
`

运行之后终端会提示：redis adapter is not set, missing configuration or adapter register?

还需要我自己再去配置adapter吗？

**Comment by niluan304** [comment]
> [v2.3 2023-01-18 - GoFrame (ZH)-Latest - GoFrame官网 - 类似PHP-Laravel, Java-SpringBoot的Go企业级开发框架](https://goframe.org/display/gf/v2.3+2023-01-18)
> - gredis
新增redis社区组件，将耦合较重的redis组件从主框架中解耦，作为社区组件提供。原有主框架增加redis接口定义，而社区组件redis提供具体的接口实现。因此，请注意，主框架gredis组件的使用方式发生了一些变更，在依赖redis的项目中需要引入社区组件redis实现，否则方法执行将会返回错误。保留兼容原有的Do/DoVar方法，并增加了100+项常用redis操作方法：[NoSQL Redis](https://goframe.org/display/gf/NoSQL+Redis)


2.3.0版本开始，redis需要像 数据库一样，手动导入包..
```
go
import (
	_ "github.com/gogf/gf/contrib/nosql/redis/v2"

	// other imported packages.
)

```
