### ISSUE TITLE
How to keep order of keys when convert map[string]interface{} to json ?

### ISSUE THREAD

**Issue by kkqy** [gogf/gf#2536]
### 1. What version of `Go` and system type/arch are you using?
go version go1.20.2 windows/amd64

### 2. What version of `GoFrame` are you using?
v2.3.3

### 3. Can this issue be re-produced with the latest release?
yes

### 4. What did you do?
```
package main

import (
	"context"
	"github.com/gogf/gf/v2/encoding/gjson"
	"github.com/gogf/gf/v2/frame/g"
)

func main() {
	amap := map[string]string{}
	gjson.DecodeTo("{\"b\":\"b\",\"a\":\"a\"}", &amap)
	g.Log().Info(context.Background(), amap)
	result, _ := gjson.EncodeString(amap)
	g.Log().Info(context.Background(), result)
}
```
INPUT is：
{"b":"b","a":"a"}
OUTPUT is:
{"a":"a","b":"b"}

### 5. What did you expect to see?

Keep the order of keys as that in map.
```
package main

import (
	"context"

	"github.com/gogf/gf/v2/encoding/gjson"
	"github.com/gogf/gf/v2/frame/g"
)

func main() {
	amap := map[string]string{
		"c": "c",
		"b": "b",
	}
	amap["a"] = "a"
	g.Log().Info(context.Background(), amap)
	result, _ := gjson.EncodeString(amap)
	g.Log().Info(context.Background(), result)
}
```
I want get {"c":"c","b":"b","a":"a"} instead of {"a":"a","b":"b","c":"c"}.

### 6. What did you see instead?

Keys are order by alphabet.

**Comment by kkqy** [comment]
This is just a example, and actual data is more complex than this.
The order of keys of my data is very important.

**Comment by windvalley** [comment]
@kkqy I couldn't reproduce the issue you described. Which specific response function did you use?

**Comment by kkqy** [comment]
> @kkqy I couldn't reproduce the issue you described. Which specific response function did you use?

I'm sorry, I made a mistake. The network panel of Chrome sorted the keys automatically.
The order of keys is correct in fact.


```
package main

import (
	"context"
	"github.com/gogf/gf/v2/encoding/gjson"
	"github.com/gogf/gf/v2/frame/g"
)

func main() {
	amap := map[string]string{}
	gjson.DecodeTo("{\"b\":\"b\",\"a\":\"a\"}", &amap)
	g.Log().Info(context.Background(), amap)
	result, _ := gjson.EncodeString(amap)
	g.Log().Info(context.Background(), result)
}
```
Acctually,the original issue is that keys of map[string]string are sorted by alphabet.
This "feature" also affects the json response when response has a map[string]interface{} member.

**Comment by kkqy** [comment]
Slice can keep order of it's elements.
Can gjson unmarshal/marshal  a type like
```
[]struct {
	key   string
	value interface{}
}
```
which can replace map[string]interface{} so that keep order of elements?

**Comment by LonelySally** [comment]
go的map输出本身就是无序的.如果key有排序规则 可以先提取所有key做排序然后再根据排序结果append到slice中.要保持原有属性json得是数组格式`[]`而非对象`{}`

**Comment by kkqy** [comment]
> go的map输出本身就是无序的.如果key有排序规则 可以先提取所有key做排序然后再根据排序结果append到slice中.要保持原有属性json得是数组格式`[]`而非对象`{}`

是的，golang中map的key是不会保证顺序的，但python和php之类的语言的key又是有顺序的。
目前我的困境在于，各个组件的数据交换是通过json格式，而又不能因为我用的golang而调整这个json的结构，因为一旦修改了，所有组件都得改，影响太大了。所以在想goframe是否支持把key有序的json对象{}解析为键值对切片，也就是用
```
[]struct {
	Key string
	Value interface{}
}
```
代替
```
map[string]interface{}
```
这样的话，我只需要修改我这个组件的struct，就能兼容其它组件传过来的有序的key的json对象了。

**Comment by kkqy** [comment]
我尝试过
```
func main() {
	amap := []struct {
		Key   string
		Value interface{}
	}{}
	gjson.DecodeTo("{\"b\":\"b\",\"a\":\"a\"}", &amap)
	g.Log().Info(context.Background(), amap)
	result, _ := gjson.EncodeString(amap)
	g.Log().Info(context.Background(), result)
}
```
但是意料之中输出是[]
所以我希望gjson提供一个特殊的类型 KeyValuePair
用于将json的对象解析为键值对。

**Comment by LonelySally** [comment]
依赖map/object的顺序本身就是不符合编程规范的(有顺序的只能是数组/切片,三方有序map输出基本都是基于内部的keyslice 例如gmap.NewListMap). 这个需求也仅限于你这个个例 基本不会有这方面的实现.如果有强依赖顺序应当声明key的排序方式而非依赖json编码.如果说你需要实现这个需求建议用正则去匹配json中的key自行实现.

**Comment by kkqy** [comment]
> 依赖map/object的顺序本身就是不符合编程规范的(有顺序的只能是数组/切片,三方有序map输出基本都是基于内部的keyslice 例如gmap.NewListMap). 这个需求也仅限于你这个个例 基本不会有这方面的实现.如果有强依赖顺序应当声明key的排序方式而非依赖json编码.如果说你需要实现这个需求建议用正则去匹配json中的key自行实现. `\"(.+?)\":.*?(?=[,{}])\"?`


有第三方包解决我的问题，但正如[GoFrame文档组件统一化](https://goframe.org/pages/viewpage.action?pageId=7290658)里说的，不想用多个包解决一个问题。于是我只能放弃gjson，完全使用第三方包。
我刚看了一下gjson的源码，发现它也是用golang自带的encoding/json来解析的，我看golang的issue里也讨论过这个问题。
https://github.com/golang/go/issues/27179
最后感谢你的回答，目前我的问题暂时解决了，自己实现了UnmarshalJSON和MarshalJSON.

**Comment by kkqy** [comment]
> 依赖map/object的顺序本身就是不符合编程规范的(有顺序的只能是数组/切片,三方有序map输出基本都是基于内部的keyslice 例如gmap.NewListMap). 这个需求也仅限于你这个个例 基本不会有这方面的实现.如果有强依赖顺序应当声明key的排序方式而非依赖json编码.如果说你需要实现这个需求建议用正则去匹配json中的key自行实现. `\"(.+?)\":.*?(?=[,{}])\"?`

您提供的这个正则也有一点问题，就是如果遇到嵌套的json就不行了，所以解析json还是个麻烦活

**Comment by kkqy** [comment]
部分参考别人的代码，用泛型写了一个KeyValuePairs类型，留给同样需要的人。
keyvaluepair.go
```
package types

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
)

type KeyValuePair[T any] struct {
	Key   string
	Value T
}
type KeyValuePairs[T any] []KeyValuePair[T]

func (p *KeyValuePairs[T]) UnmarshalJSON(data []byte) error {
	*p = make(KeyValuePairs[T], 0)
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.UseNumber()

	// must open with a delim token '{'
	t, err := dec.Token()
	if err != nil {
		return err
	}
	if delim, ok := t.(json.Delim); !ok || delim != '{' {
		return fmt.Errorf("expect JSON object open with '{'")
	}

	for dec.More() {
		t, err = dec.Token()
		if err != nil {
			return err
		}

		key, ok := t.(string)
		if !ok {
			return fmt.Errorf("expecting JSON key should be always a string: %T: %v", t, t)
		}
		var value T
		err = dec.Decode(&value)
		if err != nil {
			return fmt.Errorf("JSON value can't be decoded: %T: %v", value, value)
		}
		*p = append(*p, KeyValuePair[T]{Key: key, Value: value})
	}

	// must end with a delim token '}'
	t, err = dec.Token()
	if err != nil {
		return err
	}
	if delim, ok := t.(json.Delim); !ok || delim != '}' {
		return fmt.Errorf("expect JSON object close with '}'")
	}
	if err != nil {
		return err
	}

	t, err = dec.Token()
	if err != io.EOF {
		return fmt.Errorf("expect end of JSON object but got more token: %T: %v or err: %v", t, t, err)
	}

	return nil

}
func (p KeyValuePairs[T]) MarshalJSON() ([]byte, error) {
	buf := &bytes.Buffer{}
	buf.Write([]byte{'{'})
	for i, KeyValuePair := range p {
		b, err := json.Marshal(&KeyValuePair.Value)
		if err != nil {
			return nil, err
		}
		buf.WriteString(fmt.Sprintf("%q:", fmt.Sprintf("%v", KeyValuePair.Key)))
		buf.Write(b)
		if i < len(p)-1 {
			buf.Write([]byte{','})
		}
	}
	buf.Write([]byte{'}'})
	return buf.Bytes(), nil
}

```

用法：
```
package main

import (
	"context"
	"vnpyhttpserver/internal/types"

	"github.com/gogf/gf/v2/encoding/gjson"
	"github.com/gogf/gf/v2/frame/g"
)

type TestStruct struct {
	Name          string                      `json:"name"`
	OrderedObject types.KeyValuePairs[string] `json:"ordered_object"`
}

func main() {
	testStruct := TestStruct{}
	gjson.DecodeTo(`{
		"name": "Test",
		"ordered_object": {
			"c": "value_c",
			"b": "value_b"
		}
	}`, &testStruct)
	result, _ := gjson.EncodeString(testStruct)
	g.Log().Info(context.Background(), result)

	testStruct.OrderedObject = append(testStruct.OrderedObject, types.KeyValuePair[string]{Key: "a", Value: "value_a"})
	result, _ = gjson.EncodeString(testStruct)
	g.Log().Info(context.Background(), result)
}
```
