### ISSUE TITLE
gcfg set instance how to save to file

### ISSUE THREAD

**Issue by yuyinw** [gogf/gf#2537]
g.Cfg().GetAdapter().(*gcfg.AdapterFile).Set("logger.rotateBackupLimit", 15)

### 1. What version of `Go` and system type/arch are you using?
go1.18.5

### 2. What version of `GoFrame` are you using?
2.1

### 3. Can this issue be re-produced with the latest release?
can
### 4. What did you do?
when i use g.Cfg().GetAdapter().(*gcfg.AdapterFile).Set(), the update can not save to file

### 5. What did you expect to see?
the file  can update  when i use  g.Cfg().GetAdapter().(*gcfg.AdapterFile).Set()

### 6. What did you see instead?

the file  can update  when i use  g.Cfg().GetAdapter().(*gcfg.AdapterFile).Set()

**Comment by yuyinw** [comment]
when use  g.Cfg().GetAdapter().(*gcfg.AdapterFile).SetContent("logger.rotateBackupLimit = 15", "config.yaml")  ,  file also not changed

**Comment by gqcn** [comment]
@yuyinw The configuration component of goframe is designed `readonly`, so you cannot change the configuration content using this component. It is suggested change your configuration on your business scenario, for example, in your logic block that is going to use it.
