### ISSUE TITLE
panic: invalid address "10.0.75.1" for creating endpoint, endpoint address is like "ip:port" [recovered]

### ISSUE THREAD

**Issue by xiucaiwu** [gogf/gf#2538]
1. What version of `Go` and system type/arch are you using?
```
go 1.17.2  Windows10
```

2. What version of `GoFrame` are you using?
```
GoFrame CLI Tool v2.4.0-beta, https://goframe.org
GoFrame Version: v2.3.3 in current go.mod
```

3. Can this issue be re-produced with the latest release?

```
yes
```

4. What did you do?

server.go
```
package main

import (
    "github.com/gogf/gf/contrib/registry/file/v2"
    "github.com/gogf/gf/v2/frame/g"
    "github.com/gogf/gf/v2/net/ghttp"
    "github.com/gogf/gf/v2/net/gsvc"
    "github.com/gogf/gf/v2/os/gfile"
)

func main() {
    gsvc.SetRegistry(file.New(gfile.Temp("gsvc")))

    s := g.Server(`hello.svc`)
    s.BindHandler("/", func(r *ghttp.Request) {
        g.Log().Info(r.Context(), `request received`)
        r.Response.Write(`Hello world`)
    })
    s.Run()
}
```
client.go  
```
package main

import (
    "time"

    "github.com/gogf/gf/contrib/registry/file/v2"
    "github.com/gogf/gf/v2/frame/g"
    "github.com/gogf/gf/v2/net/gsvc"
    "github.com/gogf/gf/v2/os/gctx"
    "github.com/gogf/gf/v2/os/gfile"
)

func main() {
    gsvc.SetRegistry(file.New(gfile.Temp("gsvc")))

    client := g.Client()
    for i := 0; i < 10; i++ {
        ctx := gctx.New()
        res, err := client.Get(ctx, `http://hello.svc/`)
        if err != nil {
            panic(err)
        }
        g.Log().Debug(ctx, res.ReadAllString())
        res.Close()
        time.Sleep(time.Second)
    }
}
```

5. Running result

server
```
go run server.go
2023-03-24 16:12:56.477 [INFO] pid[1996]: http server started listening on [:57344]
2023-03-24 16:12:56.477 [INFO] openapi specification is disabled
2023-03-24 16:12:56.503 [DEBU] service register: &{Head: Deployment: Namespace: Name:hello.svc Version: Endpoints:10.0.75.1:57344 Metadata:map[insecure:true protocol:http]}

   SERVER   | DOMAIN  | ADDRESS | METHOD | ROUTE |                             HANDLER                             |    MIDDLEWARE
------------|---------|---------|--------|-------|-----------------------------------------------------------------|--------------------
  hello.svc | default | :57344  | ALL    | /     | main.main.func1                                                 |
------------|---------|---------|--------|-------|-----------------------------------------------------------------|--------------------
  hello.svc | default | :57344  | ALL    | /*    | github.com/gogf/gf/v2/net/ghttp.internalMiddlewareServerTracing | GLOBAL MIDDLEWARE
------------|---------|---------|--------|-------|-----------------------------------------------------------------|--------------------
```
client
```
go run client.go
panic: invalid address "10.0.75.1" for creating endpoint, endpoint address is like "ip:port" [recovered]
        panic: invalid address "10.0.75.1" for creating endpoint, endpoint address is like "ip:port"

goroutine 1 [running]:
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End·dwrap·12()
        E:/workspace/gowork/pkg/mod/go.opentelemetry.io/otel/sdk@v1.10.0/trace/span.go:393 +0x2a
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc0003d6480, {0x0, 0x0, 0x0})
        E:/workspace/gowork/pkg/mod/go.opentelemetry.io/otel/sdk@v1.10.0/trace/span.go:432 +0x9a2
panic({0xb64ea0, 0xc00006f1d0})
        D:/Developer/Go/src/runtime/panic.go:1038 +0x215
github.com/gogf/gf/v2/net/gsvc.NewEndpoint({0xc0002e15e5, 0x9})
        E:/workspace/gowork/pkg/mod/github.com/gogf/gf/v2@v2.3.3/net/gsvc/gsvc_endpoint.go:30 +0x128
github.com/gogf/gf/v2/net/gsvc.NewEndpoints({0xc0002e15e5, 0x9})
        E:/workspace/gowork/pkg/mod/github.com/gogf/gf/v2@v2.3.3/net/gsvc/gsvc_endpoints.go:19 +0xf4
github.com/gogf/gf/v2/net/gsvc.NewServiceWithKV({0xc0002e15c0, 0x2e}, {0x0, 0xc0002e1590})
        E:/workspace/gowork/pkg/mod/github.com/gogf/gf/v2@v2.3.3/net/gsvc/gsvc_service.go:57 +0xbf
github.com/gogf/gf/contrib/registry/file/v2.(*Registry).getServiceByFilePath(0xc0002e1470, {0xc00037eea0, 0x57})
        E:/workspace/gowork/pkg/mod/github.com/gogf/gf/contrib/registry/file/v2@v2.3.3/file_discovery.go:112 +0xb4
github.com/gogf/gf/contrib/registry/file/v2.(*Registry).getServices(0xc0002f5420, {0xc42540, 0xc0003beae0})
        E:/workspace/gowork/pkg/mod/github.com/gogf/gf/contrib/registry/file/v2@v2.3.3/file_discovery.go:81 +0x148
github.com/gogf/gf/contrib/registry/file/v2.(*Registry).Search(0xf9ebc0, {0xc42540, 0xc0003beae0}, {{0x0, 0x0}, {0xb9c99c, 0x9}, {0x0, 0x0}, 0x0})
        E:/workspace/gowork/pkg/mod/github.com/gogf/gf/contrib/registry/file/v2@v2.3.3/file_discovery.go:23 +0x45
github.com/gogf/gf/v2/net/gsvc.GetAndWatchWithDiscovery.func2()
        E:/workspace/gowork/pkg/mod/github.com/gogf/gf/v2@v2.3.3/net/gsvc/gsvc_discovery.go:56 +0xc9
github.com/gogf/gf/v2/container/gmap.(*StrAnyMap).doSetWithLockCheck(0xc0002f5500, {0xb9c99c, 0x9}, {0xaf6420, 0xc000035440})
        E:/workspace/gowork/pkg/mod/github.com/gogf/gf/v2@v2.3.3/container/gmap/gmap_hash_str_any_map.go:217 +0x132
github.com/gogf/gf/v2/container/gmap.(*StrAnyMap).GetOrSetFuncLock(0x20, {0xb9c99c, 0x9}, 0xbbdc80)
        E:/workspace/gowork/pkg/mod/github.com/gogf/gf/v2@v2.3.3/container/gmap/gmap_hash_str_any_map.go:254 +0x5b
github.com/gogf/gf/v2/net/gsvc.GetAndWatchWithDiscovery({0xc42540, 0xc0003beae0}, {0xc3d858, 0xc0002f5420}, {0xb9c99c, 0x787d89}, 0xc000063be0)
        E:/workspace/gowork/pkg/mod/github.com/gogf/gf/v2@v2.3.3/net/gsvc/gsvc_discovery.go:51 +0x1f0
github.com/gogf/gf/v2/net/gclient.internalMiddlewareDiscovery(0xc00034e300, 0xc000278d00)
        E:/workspace/gowork/pkg/mod/github.com/gogf/gf/v2@v2.3.3/net/gclient/gclient_discovery.go:45 +0x15d
github.com/gogf/gf/v2/net/gclient.(*clientMiddleware).Next(0xc0002fef80, 0xaf71e0)
        E:/workspace/gowork/pkg/mod/github.com/gogf/gf/v2@v2.3.3/net/gclient/gclient_middleware.go:47 +0x5d
github.com/gogf/gf/v2/net/gclient.(*Client).Next(0xc0000046f0, 0xc000278d00)
        E:/workspace/gowork/pkg/mod/github.com/gogf/gf/v2@v2.3.3/net/gclient/gclient_middleware.go:34 +0x7e
github.com/gogf/gf/v2/net/gclient.internalMiddlewareTracing(0xc0002b4750, 0xc000278d00)
        E:/workspace/gowork/pkg/mod/github.com/gogf/gf/v2@v2.3.3/net/gclient/gclient_tracing.go:73 +0x8aa
github.com/gogf/gf/v2/net/gclient.(*clientMiddleware).Next(0xc0002fef80, 0xaf71e0)
        E:/workspace/gowork/pkg/mod/github.com/gogf/gf/v2@v2.3.3/net/gclient/gclient_middleware.go:47 +0x5d
github.com/gogf/gf/v2/net/gclient.(*Client).Next(0xc42540, 0xc000278d00)
        E:/workspace/gowork/pkg/mod/github.com/gogf/gf/v2@v2.3.3/net/gclient/gclient_middleware.go:34 +0x7e
github.com/gogf/gf/v2/net/gclient.(*Client).DoRequest(0xc00034e300, {0xc42540, 0xc0003bea20}, {0xb92344, 0xc00005bf28}, {0xb9c995, 0xc000034060}, {0x0, 0x0, 0x0})
        E:/workspace/gowork/pkg/mod/github.com/gogf/gf/v2@v2.3.3/net/gclient/gclient_request.go:135 +0x49d
github.com/gogf/gf/v2/net/gclient.(*Client).Get(...)
        E:/workspace/gowork/pkg/mod/github.com/gogf/gf/v2@v2.3.3/net/gclient/gclient_request.go:36
main.main()
        E:/workspace/gowork/src/gfbase/registry/file/client/client.go:20 +0x490
exit status 2
```

**Comment by xiucaiwu** [comment]
上面这个问题目前在Windows11下客户端连接仍然会报错
`panic: invalid address "10.0.75.1" for creating endpoint, endpoint address is like "ip:port"`
gf版本为 2.3.3 grpcx 版本为 2.3.4
gf和grpcx升级到2.4.0后服务端运行不起来了,Linux下服务端和客户端都可以运行

以下代码都来自于官方 https://github.com/gogf/gf-demo-grpc.git 
s1.go
`
package main

import (
    "github.com/gogf/gf/contrib/rpc/grpcx/v2"

    "github.com/gogf/gf-demo-grpc/internal/controller/user"
)

func main() {
    s := grpcx.Server.New()
    user.Register(s)
    s.Run()
}
`
client.go
`
package main

import (
	"github.com/gogf/gf/contrib/rpc/grpcx/v2"
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gctx"

	"github.com/gogf/gf-demo-grpc/api/user/v1"
)

func main() {
	var (
		conn   = grpcx.Client.MustNewGrpcClientConn("demo")
		client = v1.NewUserClient(conn)
		ctx    = grpcx.Ctx.NewOutgoing(gctx.New(), g.Map{
			"UserId":   "1000",
			"UserName": "john",
		})
	)
	g.Log().Infof(ctx, `outgoing data: %v`, grpcx.Ctx.OutgoingMap(ctx).Map())
	res, err := client.GetList(ctx, &v1.GetListReq{
		Page: 1,
		Size: 10,
	})
	if err != nil {
		g.Log().Error(ctx, err)
		return
	}
	g.Log().Debug(ctx, "Response:", res.GetUsers())
}
`
Windows11下运行报错如下  
`
2023-04-25 09:45:43.930 [DEBU] {80805698310a591799732f67481837bb} set default registry using file registry as no custom registry set
2023-04-25 09:45:43.942 [DEBU] {80805698310a591799732f67481837bb} service register: &{Head: Deployment: Namespace: Name:demo Version: Endpoints:10.0.75.1:8888,192.168.0.86:8888,172.23.144.1:8888 Metadata:map[protocol:grpc]}
2023-04-25 09:45:43.943 [FATA] {80805698310a591799732f67481837bb} os.OpenFile failed with name "C:\Users\ADMINI~1\AppData\Local\Temp\gsvc\service#default#default#demo#latest#10.0.75.1:8888,192.168.0.86:8888,172.23.144.1:8888", flag "577", perm "438": open C:\Users\ADMINI~1\AppData\Local\Temp\gsvc\service#default#default#demo#latest#10.0.75.1:8888,192.168.0.86:8888,172.23.144.1:8888: The filename, directory name, or volume label syntax is incorrect.
1. os.OpenFile failed with name "C:\Users\ADMINI~1\AppData\Local\Temp\gsvc\service#default#default#demo#latest#10.0.75.1:8888,192.168.0.86:8888,172.23.144.1:8888", flag "577", perm "438"
   1).  github.com/gogf/gf/v2/os/gfile.OpenFile
        E:/workspace/gowork/pkg/mod/github.com/gogf/gf/v2@v2.4.0/os/gfile/gfile.go:97
   2).  github.com/gogf/gf/v2/os/gfile.OpenWithFlagPerm
        E:/workspace/gowork/pkg/mod/github.com/gogf/gf/v2@v2.4.0/os/gfile/gfile.go:117
   3).  github.com/gogf/gf/v2/os/gfile.putContents
        E:/workspace/gowork/pkg/mod/github.com/gogf/gf/v2@v2.4.0/os/gfile/gfile_contents.go:49
   4).  github.com/gogf/gf/v2/os/gfile.PutContents
        E:/workspace/gowork/pkg/mod/github.com/gogf/gf/v2@v2.4.0/os/gfile/gfile_contents.go:77
   5).  github.com/gogf/gf/contrib/registry/file/v2.(*Registry).Register
        E:/workspace/gowork/pkg/mod/github.com/gogf/gf/contrib/registry/file/v2@v2.4.0/file_registrar.go:28
   6).  github.com/gogf/gf/contrib/rpc/grpcx/v2.(*GrpcServer).doServiceRegister
        E:/workspace/gowork/pkg/mod/github.com/gogf/gf/contrib/rpc/grpcx/v2@v2.4.0/grpcx_grpc_server.go:197
   7).  github.com/gogf/gf/contrib/rpc/grpcx/v2.(*GrpcServer).Run
        E:/workspace/gowork/pkg/mod/github.com/gogf/gf/contrib/rpc/grpcx/v2@v2.4.0/grpcx_grpc_server.go:120
   8).  main.main
        E:/workspace/gowork/src/OtherProject/gf-demo-grpc/s1.go:12
2. open C:\Users\ADMINI~1\AppData\Local\Temp\gsvc\service#default#default#demo#latest#10.0.75.1:8888,192.168.0.86:8888,172.23.144.1:8888: The filename, directory name, or volume label syntax is incorrect.

Stack:
1.  github.com/gogf/gf/contrib/rpc/grpcx/v2.(*GrpcServer).doServiceRegister
    E:/workspace/gowork/pkg/mod/github.com/gogf/gf/contrib/rpc/grpcx/v2@v2.4.0/grpcx_grpc_server.go:198
2.  github.com/gogf/gf/contrib/rpc/grpcx/v2.(*GrpcServer).Run
    E:/workspace/gowork/pkg/mod/github.com/gogf/gf/contrib/rpc/grpcx/v2@v2.4.0/grpcx_grpc_server.go:120
3.  main.main
    E:/workspace/gowork/src/OtherProject/gf-demo-grpc/s1.go:12

exit status 1
`
Linux下运行OK
`
[root@localhost gf-demo-grpc]# go run s1.go 
2023-04-25 09:49:35.381 [DEBU] {c9ec967b670a591727ae0e67bc870605} set default registry using file registry as no custom registry set
2023-04-25 09:49:35.385 [DEBU] {c9ec967b670a591727ae0e67bc870605} service register: &{Head: Deployment: Namespace: Name:demo Version: Endpoints:10.0.2.15:8888 Metadata:map[protocol:grpc]}
2023-04-25 09:49:35.386 [INFO] {c9ec967b670a591727ae0e67bc870605} pid[23360]: grpc server started listening on [:8888]
2023-04-25 09:49:51.058 {fb6585216b0a591713a1bb1df5f54902} /user.User/GetList, 4.542ms, Page:1  Size:10, <nil>
^C2023-04-25 09:50:03.554 [INFO] {c9ec967b670a591727ae0e67bc870605} signal received: interrupt, gracefully shutting down
2023-04-25 09:50:03.554 [DEBU] {c9ec967b670a591727ae0e67bc870605} service deregister: &{Service:0xc000403810 Endpoints:10.0.2.15:8888 Metadata:map[UpdateAt:2023-04-25 09:49:35 protocol:grpc]}

[root@localhost gf-demo-grpc]# go run client.go 
2023-04-25 09:49:51.036 [DEBU] {f3a8c5206b0a591712a1bb1d9355c326} set default registry using file registry as no custom registry set
2023-04-25 09:49:51.038 [DEBU] {f3a8c5206b0a591712a1bb1d9355c326} Watch key "/service/default/default/demo/latest/"
2023-04-25 09:49:51.039 [INFO] {fb6585216b0a591713a1bb1df5f54902} outgoing data: map[userid:1000 username:john]
2023-04-25 09:49:51.043 [DEBU] {f3a8c5206b0a591712a1bb1d9355c326} client conn updated with addresses [{"Addr":"10.0.2.15:8888","ServerName":"demo","Attributes":{},"BalancerAttributes":null,"Type":0,"Metadata":null}]
2023-04-25 09:49:51.061 [DEBU] {fb6585216b0a591713a1bb1df5f54902} Response:
`

**Comment by gqcn** [comment]
@xiucaiwu 你好，看报错是创建`service`文件失败了，似乎是`windows`下不支持这种文件命名方式。由于基于文件的服务注册发现是测试使用，你可以切换为`etcd`或者其他的注册发现组件解决这个问题。

**Comment by starccck** [comment]
@xiucaiwu 已经修复完了,可以使用最新的master代码运行了

**Comment by huidou74** [comment]
panic: invalid address "192.168.10.3" for creating endpoint, endpoint address is like "ip:port"
