### ISSUE TITLE
关于优雅重启的实现问题

### ISSUE THREAD

**Issue by dchaofei** [gogf/gf#254]
看到代码里子进程向父进程发送退出消息:
```go
// 如果是子进程，那么服务开启后通知父进程销毁
	if gproc.IsChild() {
		gtimer.SetTimeout(2*time.Second, func() {
			if err := gproc.Send(gproc.PPid(), []byte("exit"), gADMIN_GPROC_COMM_GROUP); err != nil {
				glog.Error("[ghttp] server error in process communication:", err)
			}
		})
	}
```
我想到的是直接发送进程信号`p.Signal(信号) `，然后父进程监听到信号调用 `gracefulShutdownWebServers()`

所以想请教下，给进程发送消息的方式是比发送信号有优势吗？谢谢!

**Comment by johngcn** [comment]
@dchaofei 这个进程通信采用的是`Socket`的方式，在GF的开发文档你可以看得到这种方式其实是实验性的，因为`Socket`通信要处理的细节比较多，相比较于其他进程通信方式比较复杂。当然，这里的功能是非常稳定的，相比较于信号通知方式的话，跨平台型不错，信号只在`*nix`系统下有效，在`windows`下是不行的。

**Comment by dchaofei** [comment]
学习了，谢谢
