### ISSUE TITLE
command parameter is removed in the latest version specifying the configuration file?

### ISSUE THREAD

**Issue by atishoo** [gogf/gf#2543]
### 1. What version of `Go` and system type/arch are you using?
![image](https://user-images.githubusercontent.com/7723403/227748610-caf65870-31f9-4306-a555-0ef84b4b1abe.png)

### 2. What version of `GoFrame` are you using?
如上图

### 3. Can this issue be re-produced with the latest release?
yes

### 4. What did you do?
gf build --gf.gcfg.file=deploy.yaml
或者
gf build -gf.gcfg.file=deploy.yaml

### 5. What did you expect to see?
希望使用deploy的配置产生编辑结果，但是还是默认的config.yaml文件

**Comment by windvalley** [comment]
请阅读文档: https://goframe.org/pages/viewpage.action?pageId=1114380

**Comment by windvalley** [comment]
> @windvalley @atishoo It cannot customize the CLI configuration file, but it's appreciated a `PR` implementing this.

@gqcn 我猜测@atishoo 混淆了编译用的配置文件`hack/config.yaml`和项目配置文件`manifest/config/config.yaml`, 因为他使用了指定项目配置文件的参数`--gf.gcfg.file`.  不过, 一般来说编译时使用默认的`hack/config.yaml`就足够了.

**Comment by windvalley** [comment]
@atishoo 不太明白为什么要在编译时指定数据库配置，编译时将项目配置目录（manifest/config/）打包到二进制就可以了啊，启动服务时再通过环境变量或这个参数--gf.gcfg.file来指定具体的配置文件就可以了啊

**Comment by windvalley** [comment]
我刚才说的方式就可以达到你的目的。

**Comment by windvalley** [comment]
不用，已经编译进二进制文件了。可以参考这个配置：https://github.com/windvalley/gf2-demo/blob/main/hack/config.yaml

**Comment by chaegumi** [comment]
很容易使人误解呀，我开始也误解了，想成是
`gf build --gf.gcfg.file=config.prod.yaml`
不是这样的，只要`gf build`就可以，打包的时候config.yaml和config.prod.yaml都打包好了.
等部署到服务器时，配置启动程序时才加参数.
