### ISSUE TITLE
gdb单元测试生成的user表中的create_time字段值问题

### ISSUE THREAD

**Issue by alai04** [gogf/gf#255]

**Comment by alai04** [comment]
运行环境：
macOS 10.14.5
go 1.12
GoFrame 1.8.0

执行gdb的单元测试后，在mysql中查看生成的user_xxxx表时，发现表中有10条记录，前8条的create_time字段值是本地时间，但最后2条记录的create_time字段值为UTC时间。
查看各个*_test.go源文件，想找出原因，但是没有发现。执行整个package测试可以成功，但逐条执行文件中的Test*测试，发现其中TestModel_Update测试失败，找出原因后修改了测试代码并测试通过。
但是create_time字段值的问题还是没找到原因。
<img width="509" alt="屏幕快照 2019-07-17 上午10 45 11" src="https://user-images.githubusercontent.com/1415027/61343867-ece21d80-a881-11e9-99ba-838dcb9e4c7d.png">

**Comment by wenzi1** [comment]
因为你使用的mysql版本中create_time的默认值为CURRENT_TIMESTAMP，执行update时会对create_time赋默认值，默认的时区是UTC时区

**Comment by alai04** [comment]
那前8条记录的create_time为什么是本地时间？如果全是UTC或者全是本地时间，都没问题，问题是前面是本地时间，最后2条是UTC，这不奇怪吗？

**Comment by wenzi1** [comment]
前面的create_time是在测试代码中写入的，是本地时区，你可以看下文档里的说明》 https://goframe.org/database/gdb/faq

**Comment by alai04** [comment]
明白了，谢谢解答
