### ISSUE TITLE
 I hope the validator verifies the data that I decrypted

### ISSUE THREAD

**Issue by fangtongle** [gogf/gf#2553]
### 1. What version of `Go` and system type/arch are you using?

go version go1.18 windows/amd64

### 2. What version of `GoFrame` are you using?

github.com/gogf/gf/v2 v2.3.1

### 3. Can this issue be re-produced with the latest release?
yes

### 4. What did you do?

I have a requirement now, as the data provided by the frontend is encrypted through AES, so I defined a middleware to decrypt it, which will be intercepted by validate when running. Because I use encrypted data, I hope the data validated by validate is decrypted by me.
![image](https://user-images.githubusercontent.com/125536069/228800583-d17555fe-f50d-4369-afe0-b76c7dd5f679.png)
![image](https://user-images.githubusercontent.com/125536069/228800768-8baf26c4-280e-4f4f-83a2-0459c22e2f6f.png)
![image](https://user-images.githubusercontent.com/125536069/228800911-b8473fe3-bc19-4cf5-92c7-889155db3b0c.png)
![image](https://user-images.githubusercontent.com/125536069/228801010-485b3379-5aa4-4c2e-a0a2-597c06c9178b.png)

### This is the official website's call flowchart, and I need assistance
![image](https://user-images.githubusercontent.com/125536069/228801557-91fea133-42d1-4007-aff0-95fbd143fe48.png)

### 5. What did you expect to see?
I hope the data validated by validate is decrypted by me

### 6. What did you see instead?
It was intercepted by the default data validation interceptor of the system

**Comment by FTLLOVE** [comment]
![image](https://user-images.githubusercontent.com/22320062/228854013-19615857-1ddf-4b70-976e-f77db1c2cb1a.png)
这样就可以了
