### ISSUE TITLE
Mac OS 13.2.1 install gf command failed

### ISSUE THREAD

**Issue by Y-io** [gogf/gf#2555]
### 1. What version of `Go` and system type/arch are you using?
go1.19.2 darwin/arm64

### 2. What version of `GoFrame` are you using?
latest

### 3. Can this issue be re-produced with the latest release?
yes

### 4. What did you do?

环境： 系统 Mac os 13.2.1，CPU M1 MAX，终端 iTerom2 zsh

1. 执行以下拷贝的命令：
```
sudo wget -O gf https://github.com/gogf/gf/releases/latest/download/gf_$(go env GOOS)_$(go env GOARCH) && chmod +x gf && ./gf install -y && rm ./gf
```

2. 得到以下结果：
![image](https://user-images.githubusercontent.com/25784157/229286367-f2958954-6be9-4317-9c11-a449bd6ff295.png)

PS: .zshrc 中有 alias gf=gf,  gf 文件出现在 ~/gf

尝试1：chmod 777
尝试2：sudo cp ~/gf /usr/bin

### 5. What did you expect to see?
在 windows 10 和 ubuntu 20 可以

**Comment by stardemo** [comment]
可以分步执行分析安装过程
```shell
wget -O gf https://github.com/gogf/gf/releases/latest/download/gf_$(go env GOOS)_$(go env GOARCH)
chmod +x ./gf
#交互式安装
./gf install 
```
