### ISSUE TITLE
NewCodeSkip idea to skip all stacks

### ISSUE THREAD

**Issue by oldme-git** [gogf/gf#2559]
### 场景
在实际的一个Web业务上，系统上会有系统错误和业务错误（也可以叫做异常和错误）。系统错误是代码中抛出的异常，比如执行SQL失败；业务错误是用户输入不当引发的，比如说账号密码错误。
对于这两种错误，我都想使用同一种错误码设计来应对。但是系统错误我只想告诉用户系统错误或者未知错误，但是在日志中需要打印出所有的堆栈信息，方便排查错误。但是对于账号密码这种错误是不需要打印任何堆栈信息的，所以NewCodeSkip能不能有一种方法来跳过所有堆栈信息，只返回给用户错误信息，以防污染错误日志。

**Comment by gqcn** [comment]
@oldme-git `NewOption`
