### ISSUE TITLE
建议gdb的查询类操作支持手动设置master

### ISSUE THREAD

**Issue by iReadX** [gogf/gf#256]
建议gdb在 `New()` 或 `DB()` 新增对应的 `NewByMaster()` 和 `DBByMaster()` 类似的函数，此函数下的所有操作都在 `master` 上；经代码阅读 `g/database/gdb/gdb.go` 中的两个函数如下(350-358行)：
```go
// 创建底层数据库master链接对象。
func (bs *dbBase) Master() (*sql.DB, error) {
	return bs.getSqlDb(true)
}

// 创建底层数据库slave链接对象。
func (bs *dbBase) Slave() (*sql.DB, error) {
    return bs.getSqlDb(false)
}
```
通过 `NewByMaster()` 和 `DBByMaster()` 创建的 `db` 的 `Slave` 方法中 `return bs.getSqlDb(true)`
----
以上是我的思路，以最少的改动实现，同时可以向后兼容

**Comment by johngcn** [comment]
@iReadX 已开发完成，会在`v2.0`中发布。

**Comment by johngcn** [comment]
@iReadX 已发布，请更新最新框架代码再试试。
