### ISSUE TITLE
gdb batch lost field

### ISSUE THREAD

**Issue by zcyc** [gogf/gf#2561]
### 1. What version of `Go` and system type/arch are you using?

go1.20 windows/amd64

### 2. What version of `GoFrame` are you using?

v2.3.3

### 3. Can this issue be re-produced with the latest release?
yes

#### DB
```sql
CREATE TABLE `body` (
	`id` BIGINT ( 19 ) NOT NULL AUTO_INCREMENT,
	`created_at` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
	`updated_at` DATETIME NULL DEFAULT NULL COMMENT '更新时间',
	`deleted_at` DATETIME NULL DEFAULT NULL COMMENT '删除时间',
	`name` VARCHAR ( 255 ) NULL DEFAULT NULL COMMENT '' COLLATE 'utf8mb4_bin',
	`sort` INT ( 10 ) NOT NULL DEFAULT '0',
	`lock` INT ( 10 ) NOT NULL DEFAULT '0',
PRIMARY KEY ( `id` ) USING BTREE 
) COMMENT = '' COLLATE = 'utf8mb4_bin' ENGINE = INNODB ROW_FORMAT = DYNAMIC;
```
#### DEMO
```go
func TestBatch(t *testing.T) {
	dataList := []do.Body{
		{
			Id:   20,
			Sort: 0,
			Lock: 0,
		},
		{
			Id:   21,
			Name: "abc",
			Sort: 0,
			Lock: 0,
		},
		{
			Id:   22,
			Name: "abc",
			Sort: 0,
			Lock: 0,
		},
		{
			Id:   23,
			Sort: 0,
			Lock: 0,
		},
	}
	if _, err := dao.Body.Ctx(gctx.New()).Data(dataList).Batch(2).Insert(); err != nil {
		return
	}
}

```
run the test, and see db.

### 5. What did you expect to see?
Insert all info from my struct to db.

### 6. What did you see instead?
`name` is lost, there are no value in db.

**Comment by zcyc** [comment]
I guess gdb use first struct to get columns of batch sql, but first struct 's `name` is nil.
So all struct lost `name` column in db.

**Comment by 1211ciel** [comment]
Update to Like this 
if _, err := dao.Body.Ctx(nil).Data(dataList).Batch(2).Insert(); err != nil {
		return
	}

**Comment by gqcn** [comment]
> @gqcn
> I think the struct with the most fields can be used.
> Or how do I specify which fields to use.

I think there could be some enhancement in underlying inserting/updating logic to implement different records inserting. I'm working on it.
