### ISSUE TITLE
I wish that g.Log() can provide similar functionalities to the WithField and WithFields functions of the logrus library.

### ISSUE THREAD

**Issue by im-pingo** [gogf/gf#2565]
I wish that g.Log() can provide similar functionalities to the WithField and WithFields functions of the logrus library.

![image](https://user-images.githubusercontent.com/8231000/230592853-05714cc9-cd7f-46c3-b51a-66a5c9d136be.png)

![image](https://user-images.githubusercontent.com/8231000/230592803-5b749641-7b6f-458a-8a56-80b259665e47.png)

**Comment by gqcn** [comment]
@im-pingo I think you can use `SetPrefix` for the Logger, after then each logging content will print logging content with your custom prefix.
