### ISSUE TITLE
the internal context data is missing. there's internal issue should be fixed

### ISSUE THREAD

**Issue by Hnailu** [gogf/gf#2582]
### 1. What version of `Go` and system type/arch are you using?

go version go1.20.3 windows/amd64

### 2. What version of `GoFrame` are you using?

v2.2.5

### 3. Can this issue be re-produced with the latest release?
Yes

### 4. What did you do?

![image](https://user-images.githubusercontent.com/29322707/232004475-1fbd4424-b419-4c22-b654-0fc79b8daf1b.png)

### 5. What did you expect to see?
count1 = 1
count2 = 2
count3 = 3

### 6. What did you see instead?
count1 = 1 or 0
count2 = 2 or 0
count3 = 3 or 0

**Comment by Hnailu** [comment]
orm链式操作在执行Ctx(context)方法的时候 ，会在当前context中注入一个key名为[InternalCtxData]的internalData对象，

orm链式操作在执行Count()方法的时候，把当前查询语句的查询列名[columnName](select count(*) from tb_test，这里的列名就是count(*))保存到internalCtxData对象中，internalCtxData.FirstResultColumn = columnName；再根据当前internalCtxData对象的FirstResultColumn读取查询结果

同一个context并发查询共用一个internalData出现冲突，读取columnName错误

**Comment by gqcn** [comment]
@Hnailu 你好，实际上各个`ctx`之间不会存在冲突和覆盖，`dao.Xxx.Ctx(ctx)`会返回一个新的`Model`对象，并且会通过给定的`ctx`内部创建新的`ctx`，内部注入的`internalCtxData`不会注入到外层的`ctx`对象中。目前我使用`master`主分支并没有复现该问题，也许旧版本的内部实现存在一些问题，建议你更新框架版本再试试。如果问题依旧，请提交可复现该问题的最小可运行代码，感谢。
