### ISSUE TITLE
gcron定时任务添加无效

### ISSUE THREAD

**Issue by chenyang351** [gogf/gf#26]
![c678b7c3-ef4a-45fc-b452-f3cd4acac263](https://user-images.githubusercontent.com/30063958/53071983-c14f4700-351e-11e9-832f-681b27f2ee19.png)
打印出来的是空的，没有任务信息

**Comment by johngcn** [comment]
@chenyang351 能把你的代码复制一下出来吗，不要截图

**Comment by johngcn** [comment]
@chenyang351 已修复，请更新最新版本代码试试。
