### ISSUE TITLE
cross-compilation using the -o parameter does not take effect

### ISSUE THREAD

**Issue by z10086** [gogf/gf#2604]
### 1. What version of `Go` and system type/arch are you using?

  Go Version:  go1.20.3

### 2. What version of `GoFrame` are you using?

 GF Version:  v2.4.0

### 3. Can this issue be re-produced with the latest release?

yes

### 4. What did you do?

gf build main.go -o d:\sd -ps manifest/config -a amd64 -s linux

### 5. What did you expect to see?

I expect to see the compiled “sd” file in the directory d:\

### 6. What did you see instead?
compiled file in
project_dir\temp\linux_amd64

**Comment by starccck** [comment]
You can provide -p argument to specify built binary output path now. I will have a check on this issue.
