### ISSUE TITLE
gf build cross-compile and run, configuration file no such file or directory

### ISSUE THREAD

**Issue by walingcc** [gogf/gf#2606]
![image](https://user-images.githubusercontent.com/37326329/234745339-9802e3be-7a8f-4bc3-9321-ed648db3486c.png)

![image](https://user-images.githubusercontent.com/37326329/234745274-d35e8fdc-e1a6-4a17-8f8d-4c628c7659db.png)
使用gf build将config,public,template目录都打包进去了，二进制复制到服务器运行，报错“stat ./config/admin.conf: no such file or directory”

**Comment by walingcc** [comment]
图2是使用main.go, 添加gres.Dump()输出的日志

**Comment by walingcc** [comment]
gf version 1.16

**Comment by starccck** [comment]
可以试试升级最新的 gf cli , 没有能复现出你说的情况

**Comment by gqcn** [comment]
@walingcc 建议使用`v2`版本试试，如果问题依旧请检查使用的文件路径，或提供可复现代码。
