### ISSUE TITLE
delet_at  is not supported by Save() in GoFrame gdb

### ISSUE THREAD

**Issue by LiuShuKu** [gogf/gf#2627]
### 1. What version of `Go` and system type/arch are you using?

go1.18 windows10

### 2. What version of `GoFrame` are you using?
Gf 2.4.1

Using GoFrame v2.4.1, I found that the save() function could not process the delete_at field while using the database time feature. ① Create a record using the save () method, the primary key is the device sequence table Id, it is unique; Success at this point; A new record is added to the database; ② Using the delete() function also successfully deleted the logic; delete_at is not null; Successful operation; ③ Using the save() function again, I hope that the database should add a new data; It's actually the same data as last time; But update_at changed; But the delete_at field is still non-empty;

使用 GoFrame v2.4.1 版本、在使用数据库时间特性的的时候发现save()函数无法对delete_at字段进行处理；① 创建一条记录 使用save（）方法、主键为设备序列表Id，它是唯一的；此时成功；数据库也对应新增了一条记录；② 使用delete() 函数 也成功的逻辑删除了；此时delete_at 不为空；操作成功的；③ 再次使用save()函数 我希望数据库应该新增一条数据；实际上还是上次的那条数据；但是update_at 变更了；但是delete_at 字段还是非空的；

**Comment by windvalley** [comment]
你表的主键不是自增id吧

**Comment by LiuShuKu** [comment]
该字段为字符串类型，且在表内具有唯一性。

**Comment by windvalley** [comment]
> 该字段为字符串类型，且在表内具有唯一性。

我觉得你的表结构的设计可能需要优化下，如果非要这么设计，就不能软删除。

**Comment by LiuShuKu** [comment]
请告诉我个理由

**Comment by wln732** [comment]
> 请告诉我个理由

<如果写入的数据中存在主键或者唯一索引时，更新原有数据，否则写入一条新数据>。这个是文档的说明

**Comment by gqcn** [comment]
@LiuShuKu 你好，`Save`方法只是根据写入字段的唯一性做写入或更新，本质是`INSERT...ON DUPLICATED...`语句。软删除只是对表记录特殊字段做标记，因此软删除并不是真正的"删除"，在使用上有一定的限制，也就是记录本身是没有完整删除的，后续的SQL语句或者业务逻辑也会受此影响，包括你描述的第二次`Save`的场景。
