### ISSUE TITLE
file bytes uploading error in jaeger: span too large to send 

### ISSUE THREAD

**Issue by LiuShuKu** [gogf/gf#2628]
### 1. What version of `Go` and system type/arch are you using?
go 1.19

### 2. What version of `GoFrame` are you using?
2.4.1

### 问题描述：

外部接口返回了一个 []byte。将[]byte 转换为 formData 文件、然后上传、就会出现 **2023/05/07 17:59:33 multiple errors during transform: span too large to send: ** 这个错误；

### 流程：
调用BytesToFormData() 后执行 g.Client().ContentType(contentType).PostVar(gctx.New(), requestURL, data) 大概过1-3秒左右就会报错
但是文件能正常的上传、只是jaeger报错。

ps: 上传接口就是个简单的上传；

### 以下是byte数组转FormData 函数

```go
func (f *file) BytesToFormData(data []byte, fieldName string, fileNames ...string) (err error, formDataContentType string, formData *bytes.Buffer) {

	var (
		fileName string
		formFile io.Writer
		writer   *multipart.Writer
	)
	// 文件名
	{
		if len(fileNames) > 0 {
			fileName = fileNames[0]
		} else {
			fileName = "file.jpg"
		}
	}
	// 初始化 FormFile
	{
		formData = new(bytes.Buffer)
		writer = multipart.NewWriter(formData)
		formFile, err = writer.CreateFormFile(fieldName, fileName)
		if err != nil {
			err = gerror.Wrap(err, "初始化文件失败")
			return
		}
	}
	// 拷贝文件
	{
		_, err = io.Copy(formFile, bytes.NewReader(data))
		if err != nil {
			err = gerror.Wrap(err, "拷贝文件失败")
			return
		}
	}
	// 类型
	{
		formDataContentType = writer.FormDataContentType()
		err = writer.Close()
		if err != nil {
			err = gerror.Wrap(err, "关闭输出对象失败")
			return
		}
	}
	return
}
```

### 解决办法尝试过：

1 .尝试过将当前链路上所有的ctx都变成 gctx.New() --> 不管用

2. 尝试过 defer tp.shutdown(ctx)  不管用；

**Comment by houseme** [comment]
上传的文件大小是多少M？

**Comment by LiuShuKu** [comment]
不到1M

**Comment by zcyc** [comment]
试试在配置文件的 server 节点下添加如下配置
clientMaxBodySize = "200MB"

**Comment by LiuShuKu** [comment]
不是这个问题追踪到里面去，发现span标签的大小超过Jaeger的限制

**Comment by houseme** [comment]
> 不是这个问题追踪到里面去，发现span标签的大小超过Jaeger的限制

把整体错误日志内容贴一下，以及控制器方法代码也贴一下

**Comment by LiuShuKu** [comment]
目前已经改为标准库的http了，现在没有问题了；
使用g.Client的方法进行请求。data为[]byte 就会出现问题，您可以简单的测试一下

**Comment by houseme** [comment]
> 目前已经改为标准库的http了，现在没有问题了； 使用g.Client的方法进行请求。data为[]byte 就会出现问题，您可以简单的测试一下

大概指导原因了，要不提 pr 修复一下，查一下 otel 的限制值就可以了

**Comment by houseme** [comment]
https://github.com/jaegertracing/jaeger-client-go/blob/master/transport_udp.go#L37
https://github.com/open-telemetry/opentelemetry-go/blob/7dea2225a218872e86d2f580e82c089b321617b0/exporters/jaeger/agent.go#L145

限制咋这里

**Comment by houseme** [comment]
最终不能超过这个 
```go
// udpPacketMaxLength is the max size of UDP packet we want to send, synced with jaeger-agent.
udpPacketMaxLength = 65000
```

```go
if params.MaxPacketSize <= 0 || params.MaxPacketSize > udpPacketMaxLength {
	params.MaxPacketSize = udpPacketMaxLength
}
```
详细细节 https://github.com/open-telemetry/opentelemetry-go/blob/7dea2225a218872e86d2f580e82c089b321617b0/exporters/jaeger/agent.go#L123

**Comment by houseme** [comment]
可以在启动命令里添加 ：`gf.gtrace.max.content.log.size` 给参数赋值，限制大小

**Comment by houseme** [comment]
> 可以优雅一点吗

你来提一个 pr 吧，目前框架支持传入命令参数处理！

**Comment by houseme** [comment]
可以使用  otlp  的方式上报 https://github.com/gogf/gf/pull/2641

**Comment by houseme** [comment]
> 可以给个示例吗

example/trace/otlp

**Comment by LiuShuKu** [comment]
未在主库看到
