### ISSUE TITLE
使用gf gen dao 后项目报错: cannot use f (variable of type func(ctx context.Context, tx gdb.TX) error) as func(ctx context.Context, tx *gdb.TX) error value in argument to dao.Ctx(ctx).Transaction

### ISSUE THREAD

**Issue by jinyuanqing** [gogf/gf#2637]
使用gf gen dao 后项目报错:
cannot use f (variable of type func(ctx context.Context, tx gdb.TX) error) as func(ctx context.Context, tx *gdb.TX) error value in argument to dao.Ctx(ctx).Transaction

![TJTUIK8CAFGET1H2V$BAXYG](https://github.com/gogf/gf/assets/12565969/c221b7da-9d6f-42f5-8dae-9f18a769134b)

![image](https://github.com/gogf/gf/assets/12565969/f5f8d0aa-b26d-45af-88ae-a5f945fa5073)

**Comment by arieslee** [comment]
你的gf工具版本不对吧？

**Comment by zcyc** [comment]
cli 版本和 gf 依赖版本要对应才行。
2.3 版本改了 gdb.TX 类型，从指针变成了接口。

**Comment by zhonghuaxunGM** [comment]
What the above said is correct, please keep the versions of gf and gf-cli consistent.

**Comment by jinyuanqing** [comment]
谢谢各位了.确实是gf cli版本问题.
