### ISSUE TITLE
dameng database clob type mapping error

### ISSUE THREAD

**Issue by tianbocheng** [gogf/gf#2648]
# 一、开发环境
- github.com/gogf/gf/contrib/drivers/dm/v2 v2.4.1
- github.com/gogf/gf/v2 v2.4.1

# 二、操作步骤
## 2.1  初始化数据库表
```
CREATE TABLE HANDLE_INFO (
                             ID INT IDENTITY (1, 1) NOT NULL,
                             SUB_PREFIX VARCHAR(128),
                             PREFIX VARCHAR(256),
                             HANDLE_NAME VARCHAR(1024) NOT NULL,
                             CREATE_TIME TIMESTAMP,
                             UPDATE_TIME TIMESTAMP,
                             VALUE CLOB   ,
                             NOT CLUSTER PRIMARY KEY (ID)
);

INSERT INTO OA.HANDLE_INFO (SUB_PREFIX,PREFIX,HANDLE_NAME,CREATE_TIME,UPDATE_TIME,VALUE) VALUES ('88.111','88.111.1','88.111.1/test','2023-05-16 14:37:45.337897','2023-05-16 14:37:45.337897', '[{"a": "b"}]');


```

## 2.2 执行查询操作
```
adsf, _ := g.DB().Model("handle_info").Where("handle_name", handle).One()
fmt.Println(adsf)

```

**查询到 clob 字段与中不一致，结果为 {"Valid":true}  但是库中并非如此**

<img width="1151" alt="image" src="https://github.com/gogf/gf/assets/20829408/64326820-bc53-4257-aa4a-c4048a720232">

**Comment by zhonghuaxunGM** [comment]
Dameng database clob corresponding mysql is a blob？
What is the correct value? Is it a character problem or a content conversion problem?

**Comment by tianbocheng** [comment]
> Dameng database clob corresponding mysql is a blob？ What is the correct value? Is it a character problem or a content conversion problem?

dameng url is  : dm:OA:bbbbbbbbb@tcp(10.14.3.2:5236)/OA
<img width="948" alt="image" src="https://github.com/gogf/gf/assets/20829408/d36d0ec6-60bb-43d0-820f-0acd45d8cf91">


HandleInfoMysql  struct  

```
type HandleInfoMysql struct {
	Id         int       `orm:"id,primary" json:"id"`
	SubPrefix  string    `orm:"sub_prefix"`
	Prefix     string    `orm:"prefix"`
	HandleName string    `orm:"handle_name"`
	CreateTime time.Time `orm:"create_time"`
	UpdateTime time.Time `orm:"update_time"`
	Value      string    `orm:"value"`
}

```

**Comment by wln32** [comment]
最新版2.7.0中已修复
