### ISSUE TITLE
MySQL high-precision issues

### ISSUE THREAD

**Issue by ygcool** [gogf/gf#2650]
### 1. What version of `Go` and system type/arch are you using?
go version go1.20 darwin/arm64

### 2. What version of `GoFrame` are you using?
GF Version:  v2.4.1

### 3. Can this issue be re-produced with the latest release?
yes

mysql字段类型：decimal(40,18).
默认使用gf gen dao生成模型为float64类型，当值字段为1.999999999999999999时会出现溢出，orm查出来的值会溢出变为2.
尝试过将float64改为[decimal.Decimal](https://github.com/shopspring/decimal)也一样为2了
用"[自定义类型转换转](https://goframe.org/pages/viewpage.action?pageId=41255129)"为decimal.Decimal一样也是2.
请问有啥好方法可以支持decimal.Decimal类型或其他高精度呀？

**Comment by LonelySally** [comment]
这种算是极为特殊的一种情况了吧.当做string去获取然后newfromstring(跟java那边的同理用string去new,原因度娘).
`	
price, _ := decimal.NewFromString("1.99999999999999999999999999")
	price2, _ := decimal.NewFromString("1.1")
	price = price.Add(price2)
	g.Dump(price.String()) //Output:: "3.09999999999999999999999999"
`

**Comment by ygcool** [comment]
> 

你说的意思，是得把数据库的字段从decimal改为varchar了吧？

**Comment by ygcool** [comment]
> 

哦你是说结构体里面改为string呀。这个试过的，不行。string类型也会把1.999999999999999999变为2

**Comment by ygcool** [comment]
> > > 
> > 
> > 
> > 哦你是说结构体里面改为string呀。这个试过的，不行。string类型也会把1.999999999999999999变为2
> 
> 试下第二种呢?

一样也不行的哦

**Comment by LonelySally** [comment]
> > > > 
> > > 
> > > 
> > > 哦你是说结构体里面改为string呀。这个试过的，不行。string类型也会把1.999999999999999999变为2
> > 
> > 
> > 试下第二种呢?
> 
> 一样也不行的哦

个人推测应该是gvar造成的.若业务紧张,且在数据库中该字段无运算行为可先改为varchar.我先弄个环境debug下.

**Comment by LonelySally** [comment]
debug记录下,在[https://github.com/gogf/gf/blob/master/database/gdb/gdb_core_structure.go#L177](gdb_core_structure)这里任何精度的decimal都被作为float64处理了,而float64应该只能支持到15位小数.

**Comment by ygcool** [comment]
对的，这就是问题所在，想着用什么方法能支持[decimal.Decimal](https://github.com/shopspring/decimal)，但是没有找到

**Comment by lusson-luo** [comment]
是的，我也遇到这个问题，我的金额在数据库用的高精度，转成 entity 成 float64，计算的金额是浮点，不是正确的金额。
<img width="1370" alt="image" src="https://github.com/gogf/gf/assets/19859400/0a20ddd8-b89d-4764-8149-b7fb2aeb172f">

**Comment by LonelySally** [comment]
> 是的，我也遇到这个问题，我的金额在数据库用的高精度，转成 entity 成 float64，计算的金额是浮点，不是正确的金额。 <img alt="image" width="1370" src="https://user-images.githubusercontent.com/19859400/241758004-0a20ddd8-b89d-4764-8149-b7fb2aeb172f.png">

目前社区正在跟进处理.若急用可以先fork,将decimal独立一个case分支返回LocalTypeString.再使用replace替换go mod为fork地址.

**Comment by LonelySally** [comment]
拉取master代码,decimal返回类型已变更为string.另外可以自行编译一个master的cli工具,在hack配置typeMapping即可完成entity中对decimal.Decimal的支持.
