### ISSUE TITLE
Doubts about the service layer

### ISSUE THREAD

**Issue by xingcxb** [gogf/gf#2659]
### 1. What version of `Go` and system type/arch are you using?

go1.20.3 darwin/arm64

### 2. What version of `GoFrame` are you using?

v2.4.1

### 3. Can this issue be re-produced with the latest release?
是的

### 4. What did you do?

在使用的过程中发现，service层仅仅是定义了一层接口，我个人的理解来说的话这部分代码其实属于一种规范。(如果是我没有理解透这部分代码还请谅解)

是否可以考虑在service层生成的时候就直接和model进行绑定，封装基础的model增删改查呢？比如FindById，FindAll...
这样在logic处理业务的时候可以更加从容的调用各个不同的模型来进行处理。更复杂的处理逻辑的话就直接在logic中自行封装就可以了

**Comment by gqcn** [comment]
@xingcxb `service`是接口抽象，具体是的实现在`logic`层，至于数据的`CURD`可以直接调用`dao`层，你甚至可以在`controller`中直接调用`dao`。
