### ISSUE TITLE
MySQL 2.4.1 reports an error after the driver is introduced

### ISSUE THREAD

**Issue by atgui** [gogf/gf#2669]
The latest version 2.4.1 creates a project, introduces the mysql driver, and runs the project
gf init test
gf run main.go    OK

_ "github.com/gogf/gf/contrib/drivers/mysql/v2"

gf run main.go ERROR

![image](https://github.com/gogf/gf/assets/20312548/84bbef52-1d6d-4c6b-9d0c-00c980561af8)

**Comment by LonelySally** [comment]
检查下mysql社区包版本是否跟框架版本一致.

**Comment by atgui** [comment]
![image](https://github.com/gogf/gf/assets/20312548/4d29aee7-abd3-45d5-9d2a-d3ed11f78f9f)

 2.4.1    go version go1.20.4 windows/amd64

**Comment by atgui** [comment]
![image](https://github.com/gogf/gf/assets/20312548/4d29aee7-abd3-45d5-9d2a-d3ed11f78f9f)

 2.4.1    go version go1.20.4 windows/amd64

**Comment by LonelySally** [comment]
> ![image](https://user-images.githubusercontent.com/20312548/242761990-4d29aee7-abd3-45d5-9d2a-d3ed11f78f9f.png)
> 
> 2.4.1 go version go1.20.4 windows/amd64
![image](https://github.com/gogf/gf/assets/26945597/6b4f0909-2034-4443-a5c5-f5164e31a247)


测试未能复现 go 1.19.9
请尝试执行go clean --modcache 删除go.sum 删除vendor(若存在) 后并重新执行go mod tidy

**Comment by atgui** [comment]
go clean --modcache 删除go.sum 执行后可以了，感谢!
