### ISSUE TITLE
gconfig解析文件内容格式异常

### ISSUE THREAD

**Issue by zcool321** [gogf/gf#267]
版本：1.8.0
系统：windows
场景：
使用
```
	c := g.Config("config")
	// glog配置
	logPath := c.GetString("log-path")
```
获取配置信息，配置文件名称：config.toml
内容：
log-path = "./logs"
报错：
2019-07-22 17:35:33.465 [CRIT] [gcfg] Load config file "D:\workspace_go\data_repair\config\config.toml" failed: unsupported type for loading 

内容修改为
log-path = "./logs"

# title设置
[setting]
    title = "修复程序"

程序正常

**Comment by johngcn** [comment]
@zcool321 请更新到最新的`v1.8.1`再试试。

**Comment by zcool321** [comment]
真效率~更新完美解决
