### ISSUE TITLE
orm 使用 PostgreSQL 时需要手动为 Table 添加双引号

### ISSUE THREAD

**Issue by lvshutao** [gogf/gf#268]
### 1. What version of `Go` and system type/arch are you using?

go version go1.12.6 darwin/amd64

### 2. What version of `GoFrame` are you using?

github.com/gogf/gf v1.8.0

使用的是 postgreSql

```
// 正确
err = g.DB().Table("\"user\"").Where("id", user.Id).Struct(&user)
[DEBU] SELECT * FROM "user"  WHERE id=$1

// 错误
err = g.DB().Table("user").Where("id", user.Id).Struct(&user)
DB ERROR: pq: column "id" does not exist
DB QUERY: SELECT * FROM user  WHERE id=$1
DB PARAM: [2]
```

希望能自动添加上双引号

**Comment by johngcn** [comment]
@lvshutao 请更新到最新的`v1.8.1`再试试。
