### ISSUE TITLE
Try to propose a solution to the decimal precision problem at a lower cost

### ISSUE THREAD

**Issue by hinego** [gogf/gf#2685]
现在把decimal的数据类型映射到了float64类型
这导致了精度丢失（从string => float就已经产生了丢失，即使再转回来也无法解决，因为已经丢了）
并且这一步是在 c.RowsToResult就执行的，也就是在不改变框架代码的情况下，是无法解决这个问题
https://github.com/gogf/gf/blob/8cc5338870dd5188b84f44a4b8f66a535fe9b602/database/gdb/gdb_core_underlying.go#L246
解决方案：
将decimal映射到string
当然这存在一些问题，是关于gconv的
因为orm的Scan方法，是先获取Record再转成目标结构体的，使用`gconv.StructTag(r, pointer, OrmTagForStruct)`完成
我不清楚假设相同字段假设源与目标的类型不同时是否也能正常转换
如下，我简单验证了一下，没有问题

那么这说明将decimal映射到string并不会破坏之前的代码，不会有兼容性问题

并且还可以把它自动转换成其他类型，例如decimal
```
package main

import (
	"github.com/gogf/gf/v2/encoding/gjson"
	"github.com/gogf/gf/v2/util/gconv"
	"github.com/shopspring/decimal"
	"log"
)

type T1 struct {
	Value string `orm:"value"`
}
type T2 struct {
	Value float64 `orm:"value"`
}
type T3 struct {
	Value decimal.Decimal `orm:"value"`
}

func main() {
	t1 := &T1{Value: "1"}
	t2 := &T2{}
	t3 := &T3{}
	if err := gconv.StructTag(t1, t2, "json"); err != nil {
		log.Println(err)
		return
	}
	if err := gconv.StructTag(t1, t3, "json"); err != nil {
		log.Println(err)
		return
	}
	log.Println("pass t2", gjson.MustEncodeString(t2))
	log.Println("pass t3", gjson.MustEncodeString(t3))
}
# Output
2023/06/04 22:03:38 pass t2 {"Value":1}
2023/06/04 22:03:38 pass t3 {"Value":"1"}
```
随后在`gf gen dao`加上一个自定义类型映射的功能即可
可以是用户在项目配置文件里面添加一份配置
举例的hack/config.yaml
```

# 工具相关配置
gfcli:
  # 工具编译配置
  build:
    name:     "focus"
    arch:     "amd64"
    system:   "linux,darwin,windows"
    mod:      ""
    cgo:      0

  # dao生成
  gen:
    dao:
      - link:            "mysql:root:12345678@tcp(127.0.0.1:3306)/focus"
        removePrefix:    "gf_"
        descriptionTag:  true
        noModelComment:  true
    mapping:
      - type:            "decimal"    # 匹配的数据库类型
        dest:            "decimal.Decimal"  # 自定义映射的类型
        import:          "github.com/shopspring/decimal"  # （可选）自定义映射类型需要导入的包，如果是内置类型则不需要导入

      - type:            "decimal"    # 匹配的数据库类型
        dest:            "float64"  # 自定义映射的类型
        import:          ""  # （可选）自定义映射类型需要导入的包
```

这样应该能完美解决decimal的问题！！！

**Comment by LonelySally** [comment]
[add custom local type mapping support for command gen dao](https://github.com/gogf/gf/pull/2656)
欢迎一起参与讨论 该pr的import目前可以通过同级目录下定义type的形式去隐式实现.

**Comment by hinego** [comment]
> [add custom local type mapping support for command gen dao](https://github.com/gogf/gf/pull/2656) 欢迎一起参与讨论 该pr的import目前可以通过同级目录下定义type的形式去隐式实现.

可以看看我的实现 https://github.com/gogf/gf/pull/2686

修改添加的代码比较少
