### ISSUE TITLE
在项目中使用g.Server().EnableAdmin()方法问题

### ISSUE THREAD

**Issue by yanyuxuanz** [gogf/gf#269]
在项目中使用g.Server().EnableAdmin()方法，启动服务后会报错。出现
slice bounds out of range.
![image](https://user-images.githubusercontent.com/29646744/61693878-ead8fc80-ad62-11e9-97ed-0202a799fe6e.png)

**Comment by johngcn** [comment]
@yanyuxuanz 你好，我并没有复现你所说的问题，我的示例代码如下：
```go
package main

import (
	"github.com/gogf/gf/g"
)

func main() {
	s := g.Server()
	s.EnableAdmin()
	s.SetPort(8199)
	s.Run()
}
```
