### ISSUE TITLE
client.Response support return structure, or scan structure?

### ISSUE THREAD

**Issue by lusson-luo** [gogf/gf#2696]
### 1. What version of `Go` and system type/arch are you using?
go 1.19, linux/amd64

### 2. What version of `GoFrame` are you using?
gf 2.4.1

### 3. Can this issue be re-produced with the latest release?
可以复现

### 4. What did you do?
我希望http的请求 client.Response 能将 requestBody 解析成一个结构体对象，或者注入一个结构体指针。目前只支持返回 string，再转 结构体。
目前 http client 去请求数据，大部分返回都是 json 结构体，希望框架能直接集成解析成json对应的结构体
```
# 目前代码
client := ghttp.NewClient()
resp, err := client.Post("https://httpbin.org/post", map[string]string{
  "name":  "John",
  "email": "john@example.com",
})
requestBody :=resp.ReadAllString()
err := json.Unmarshal([]byte(jsonStr), &person)
if err != nil {
  fmt.Println("Error:", err)
  return
}
fmt.Println(person)

# 期望实现
client := ghttp.NewClient()
resp, err := client.Post("https://httpbin.org/post", map[string]string{
  "name":  "John",
  "email": "john@example.com",
})
personPoint := &Person{}
requestBody,err :=resp.ReadAllScan(personPoint)
if err != nil {
  fmt.Println("Error:", err)
  return
}
fmt.Println(person)
```

### 6. What did you see instead?
取出 jsonString，再转 struct 对象

**Comment by gqcn** [comment]
@lusson-luo You can use `g.Client().PostVar(ctx, "http://xxx.xxx.xxx/api/v1/xxx").Scan(xxx).`
