### ISSUE TITLE
gdb 中处理 bool / tinyint(1)类型问题

### ISSUE THREAD

**Issue by IGGAbc** [gogf/gf#270]
目前在一个项目中, 发现 

mysql数据表字段 b tinyint(1) / bool , 
要采集的日志文件log中, 对应的内容为 true/false, 

利用gdb 批量插入时候, 会出现异常, 无法正常插入.  

不知道能否根据字段类型判断字符串 true/false 自动转换为 1/0 , 或者mysql 关键字 TRUE/FALSE

**Comment by johngcn** [comment]
@IGGAbc 我在`mysql`中测试了没有复现你所说的问题，不过这个`issue`有点久了，我使用的是未发布的`v2.0`版本，类型这块我有做处理，回头我发布了你再试试看吧。
