### ISSUE TITLE
[BUG] windows gproc shell not work

### ISSUE THREAD

**Issue by kele1997** [gogf/gf#2700]
### 1. What version of `Go` and system type/arch are you using?

go version go1.18.10 windows/amd64

### 2. What version of `GoFrame` are you using?

github.com/gogf/gf v1.16.9

### 3. Can this issue be re-produced with the latest release?
Yes

### 4. What did you do?

When compile project on windows environment, `go build` should add build info to binary, like `buildtime`, `build git commit` or else. 

https://github.com/gogf/gf/blob/2ece368810588d6d11504b71a783f9a617eab3f4/cmd/gf/internal/cmd/cmd_build.go#L324-L330

In gf, we use `gproc.ShellExec` run the command `git log -1 --format="%cd %H" --date=format:"%Y-%m-%d %H:%M:%S"` 

```go
package main

import (
	"context"
	"fmt"
	"strings"

	"github.com/gogf/gf/v2/os/gproc"
)
func main() {
	ret, err := gproc.ShellExec(context.TODO(), `git log -1 --format="%cd %H"`)
	if err != nil {
		fmt.Printf("err is %s\n", err)
	}
	fmt.Println(ret)

}
```

### 5. What did you expect to see?

`Mon Jun 12 10:30:38 2023 +0800 adb9a35c60fd666f40cdea135ee874d59f1551f3` 

### 6. What did you see instead?
```
err is exit status 128
fatal: ambiguous argument '%H"': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

### 7. Thoughts
the problem is caused by `parseCommand` function in https://github.com/gogf/gf/blob/2ece368810588d6d11504b71a783f9a617eab3f4/os/gproc/gproc_shell.go#L66-L101

The code split command line by space, then the git args `--format="%cd %H"` is converted to `["--format=%cd", "%H"]` .  
I am not familar with windows cmd, the origin code care about backslash `\` character, but only for second one?

```go
func SplitCmd(cmd string) (args []string) {
	doublequota := false
	singlequota := false
	var sb strings.Builder
	for _, c := range cmd {
		if c == '"' {
			doublequota = !doublequota
		} else if c == '\'' {
			singlequota = !singlequota
		} else if c == ' ' && !doublequota && !singlequota {
			s := sb.String()
			args = append(args, s)
			sb.Reset()
		} else {
			sb.WriteRune(c)
		}
	}

	if sb.Len() != 0 {
		args = append(args, sb.String())
	}
	return
}
// cmd:  git log -1 --format="%cd %H"
// return: []string{"git", "log", "-1", "--format=%cd %H"}
```

**Comment by wln732** [comment]
原来的有bug，解析引号中参数如果有空格的 就会变成多个参数，导致错误

**Comment by wln732** [comment]
```go
func parseCommand(cmd string) (args []string) {

	if runtime.GOOS != "windows" {
		return []string{cmd}
	}
	// Just for "cmd.exe" in windows.
	var argStr string
	var firstChar, prevChar, lastChar1, lastChar2 byte
	array := gstr.SplitAndTrim(cmd, " ")
	for _, v := range array {
		if len(argStr) > 0 {
			argStr += " "
		}
		firstChar = v[0]
		lastChar1 = v[len(v)-1]
		lastChar2 = 0
		if len(v) > 1 {
			lastChar2 = v[len(v)-2]
		}
		if prevChar == 0 && (firstChar == '"' || firstChar == '\'') {
			// It should remove the first quote char.
			argStr += v[1:]
			prevChar = firstChar
		} else if prevChar != 0 && lastChar2 != '\\' && lastChar1 == prevChar {
			// It should remove the last quote char.
			argStr += v[:len(v)-1]
			args = append(args, argStr)
			argStr = ""
			prevChar = 0
		} else if len(argStr) > 0 {
			argStr += v
		} else {
                      // 新添加一个条件判断，如果当前是 args“ 的这种会，自动合并到上个参数
			if v[len(v)-1]=='"' || v[len(v)-1]=='\''{
				args[len(args)-1] += " " +v
			}else{
				args = append(args, v)
			}


		}
	}
	return

}
```
这个是我的修改

另外需要在cmd_build.go文件里面的getGitCommit的函数那里，执行完git的命令后，需要判断下错误，如果有错误，就没有git信息，可以直接返回空，还需要加个
```go
 s = gstr.Replace(s, "\"", "")
```
去除双引号，不然会多出几个双引号

**Comment by gqcn** [comment]
@kele1997 我记得之前处理过类似的问题，可以尝试一下最新框架版本，如果问题依旧，请继续反馈。
