### ISSUE TITLE
add new cmd `gf gen ctrl` for auto generating controller go files according to api definitions

### ISSUE THREAD

**Issue by gqcn** [gogf/gf#2701]
## 基础功能
1. 遍历`/api`目录下所有的`go`文件，提取目录名称(如`user`)及`*Req`结构体名称(如`GetListReq`)，得到一个结果数组`ctrls1`。
2. 遍历`/internal/controller`下的目录及代码文件，得到与步骤`1`相等数据结构的结果数组`ctrls2`。
3. 从数组`ctrls1`中过滤掉存在于数组`ctrls2`的结果，并得到新的数组`ctrls3`。
4. 遍历数组`ctrls3`，并自动生成对应`/internal/controller`下的控制器目录(如`user`)以及方法文件(如`user_get_list.go`)文件。
    - 如果`/internal/controller`下不存在对应目录，那么生成目录时同时生成控制器初始化文件(如`user.go`)，初始化创建方法使用`New() *Controller`。
    - 如果`/api`中的该目录存在多个版本，那么新版本的文件增加版本号来识别即可(如`user.v2.go`)，同时初始化方法名称使用`NewV2() *ControllerV2`，同时方法文件也增加版本号来识别即可(如`user_get_list.v2.go`)。

## 扩展能力(可选)

1. API子模块：如果在`g.Meta`中定义了`module/m`标签定义(如`stats`)，那么表示该`api`属于当前目录的子模块，生成的文件名称中应当包含子模块的名称以作区分：
- 文件名：`user.stats.v2.go`
- 初始化：`NewStatsV1() ControllerStats`
- 方法名: `(c *ControllerStats) GetStatsListReq(ctx context.Context, req *v1.GetStatsListReq)(res *GetStatsListRes, err error)`

2. 接口化生成：在`/api`目录下对应的各个模块目录下生成`go`接口文件，用来约定实现该模块`api`的接口列表(如`/api/user/user.go`)，接口定义形如：
```go
type IUserV1 interface{
    GetList(ctx context.Context, req *v1.GetListReq)(res *GetListRes, err error)
    // ...
}
```

3. SDK自动化生成: 在指定目录下生成实现对应`api`接口的SDK go文件。这块我来实现，已有手动编写的源码。

**Comment by hinego** [comment]
我来重述一遍，看看我理解是否有错，首先从`api`目录开始说起，其中定义了大量的`xxxReq`与`xxxRes`

以这个项目为例：https://github.com/gogf/focus-single/tree/master/api/v1

其中包含了api文件内容大概如下：
```

type AskIndexReq struct {
	g.Meta `path:"/ask" method:"get" tags:"问答" summary:"展示Ask列表页面"`
	ContentGetListCommonReq
}
type AskIndexRes struct {
	ContentGetListCommonRes
}

type AskDetailReq struct {
	g.Meta `path:"/ask/{Id}" method:"get" tags:"问答" summary:"展示Ask详情页面" `
	Id     uint `in:"path" v:"min:1#请选择查看的内容" dc:"内容id"`
}
type AskDetailRes struct {
	g.Meta `mime:"text/html" type:"string" example:"<html/>"`
}

```

此时可以匹配出所有`[Name][Action]Req`并且存在`g.Mate`字段的结构体，且存在`[Name][Action]Res`（也可以自动生成一个）

此时可以使用[Name] 作为生成controller文件的文件名，结构体名称如:`ask.v1.go` （当前需要先略过已经存在的）
```
func NewV1Ask() any {  //直接写成 *cAak 在goland中会有一个提示 Exported function with the unexported return type 
	return &cAak{}
}

type cAakV1 struct{}

func (a *cAakV1) Index(ctx context.Context, req *v1.AskIndexReq) (res *v1.AskIndexRes, err error) {
	return
}

func (a *cAakV1) Detail(ctx context.Context, req *v1.AskDetailReq) (res *v1.AskDetailRes, err error) {
	return
}

```

剩下的就是目录层级的问题，例如 `api/v1/admin/*`下的api文件应该对应
`controller/admin/*`

**Comment by hinego** [comment]
然后是 API子模块：如果在g.Meta中定义了module/m标签定义(如stats)，那么表示该api属于当前目录的子模块，生成的文件名称中应当包含子模块的名称以作区分：

这个我没太理解是什么意思 最好能给个例子

**Comment by hinego** [comment]
接口化生成：在/api目录下对应的各个模块目录下生成go接口文件，用来约定实现该模块api的接口列表(如/api/user/user.go)，接口定义形如：

这是要实现类似给 `logic` 生成 `service` 里面的接口吗？

然后可以 直接返回它的接口名称
```

func NewV1Ask()  v1.IV1Ask { 
	return &cAak{}
}
```

**Comment by hinego** [comment]
然后我还有个想法，开发者只需要定义类似如下的配置（这就是我之前自己实现的版本）：
```
- api: v8
  controller: admin
  controller_path: app/controller
  logic_path: app/logic
  api_path: app/api
  model:
    - name: Service
      tags: 服务
      actions:
        - action: Fetch
        - action: Create
        - action: Update
        - action: Get
        - action: Delete
        - action: Default
```

即可自动生成service的API文件和controller （当然可以只生成api文件，然后再由API文件生成controller也是一样的）

此时开发者只需要去填充每个api文件需要的字段即可

不需要重复的写大量的`XxxXxxReq`与`XxxXxxRes`了

**Comment by hinego** [comment]
其实如果是为新的项目考虑的话，直接按我说的那种通过配置文件去生成要容易实现一些，开发者也能少些一些东西

因为按你上述的表达，似乎API文件还是需要开发者自己创建，定义结构体

**Comment by gqcn** [comment]
目前除了"API子模块"的特性，其他功能已经实现。
