### ISSUE TITLE
gf gen dao -l "mysql:roots:cf42b1748796f358@tcp(127.0.0.1:3306)/shop"

### ISSUE THREAD

**Issue by seth-shi** [gogf/gf#2705]
![image](https://github.com/gogf/gf/assets/28035971/66fa6f1f-aedb-446a-baa3-bc8eda62d43d)

gen dao use username is root? why not roots?

**Comment by hailaz** [comment]
![image](https://github.com/gogf/gf/assets/29968474/ca3b2224-6b65-4d33-95b0-344a1339a652)
无法复现，请提供一下版本号
