### ISSUE TITLE
建议新增Http服务端多文件上传功能

### ISSUE THREAD

**Issue by yanyuxuanz** [gogf/gf#271]
![image](https://user-images.githubusercontent.com/29646744/61939534-10197500-afc6-11e9-8f10-b6f04164a0ff.png)

此处代码返回第一个文件对象以及句柄，建议改进成如下的方式

![image](https://user-images.githubusercontent.com/29646744/61939599-36d7ab80-afc6-11e9-96f8-789c91217b66.png)

```

func UploadMore(r *ghttp.Request,hotel_uuid string){

	//设置内存大小
	r.ParseMultipartForm(32 << 20);
	//获取上传的文件组
	files := r.MultipartForm.File["file"];
	len := len(files);
	for i := 0; i < len; i++ {
		//打开上传文件
		file, err := files[i].Open();
		defer file.Close();
		if err != nil {
			glog.Error(err);
		}
		buffer := make([]byte, files[i].Size)
		file.Read(buffer)

		//创建上传目录
		if !gfile.Exists("./Uploads"){
			gfile.Mkdir("./Uploads")
		}

		gfile.PutBinContents("./Uploads/"+ hotel_uuid +"/"+ gfile.Basename(files[i].Filename), buffer)

	}

}
```

**Comment by yanyuxuanz** [comment]
if r.MultipartForm == nil {
		return
	}

**Comment by johngcn** [comment]
@yanyuxuanz 感谢建议，已增加多文件上传的支持，包括客户端和服务端都已改进，请参考开发文档：https://goframe.org/net/ghttp/client/demo/upload

该功能将会在`v1.10`版本发布。

**Comment by johngcn** [comment]
@yanyuxuanz 请更新到最新的`v1.10.0`试试
