### ISSUE TITLE
The panic log is recovered, how can it be hooked

### ISSUE THREAD

**Issue by zcyc** [gogf/gf#2713]
### 1. What version of `Go` and system type/arch are you using?
go version go1.20.3 windows/amd64

### 2. What version of `GoFrame` are you using?
GoFrame CLI Tool v2.4.3, https://goframe.org
GoFrame Version: v2.3.3 in current go.mod

### 3. Can this issue be re-produced with the latest release?
yes

### 4. What did you do?
I want to hook panic logs like https://goframe.org/pages/viewpage.action?pageId=1114336

### 5. What did you expect to see?
send notifications to me

### 6. What did you see instead?
exception recovered

**Comment by starccck** [comment]
As shown in the [doc](https://goframe.org/pages/viewpage.action?pageId=1114336#id-%E6%97%A5%E5%BF%97%E7%BB%84%E4%BB%B6Writer%E6%8E%A5%E5%8F%A3-%E7%A4%BA%E4%BE%8B1%EF%BC%8C%E5%AE%9E%E7%8E%B0%E6%97%A5%E5%BF%97HOOK), you can implement a writer , eg.

```
type MyWriter struct {
	logger *glog.Logger
}

func (w *MyWriter) Write(p []byte) (n int, err error) {
        defer func() {
                if errx := recover(); errx !=nil {
                        // notify somewhere
                }
        }
	var (
		s   = string(p)
		ctx = context.Background()
	)
	if gregex.IsMatchString(`PANI|FATA`, s) {
		fmt.Println("SERIOUS ISSUE OCCURRED!! I'd better tell monitor in first time!")
		g.Client().PostContent(ctx, "http://monitor.mydomain.com", s)
	}

       // trigger some panic 
	return w.logger.Write(p)
}

```

**Comment by zcyc** [comment]
> As shown in the [doc](https://goframe.org/pages/viewpage.action?pageId=1114336#id-%E6%97%A5%E5%BF%97%E7%BB%84%E4%BB%B6Writer%E6%8E%A5%E5%8F%A3-%E7%A4%BA%E4%BE%8B1%EF%BC%8C%E5%AE%9E%E7%8E%B0%E6%97%A5%E5%BF%97HOOK), you can implement a writer , eg.
> 
> ```
> type MyWriter struct {
> 	logger *glog.Logger
> }
> 
> func (w *MyWriter) Write(p []byte) (n int, err error) {
>         defer func() {
>                 if errx := recover(); errx !=nil {
>                         // notify somewhere
>                 }
>         }
> 	var (
> 		s   = string(p)
> 		ctx = context.Background()
> 	)
> 	if gregex.IsMatchString(`PANI|FATA`, s) {
> 		fmt.Println("SERIOUS ISSUE OCCURRED!! I'd better tell monitor in first time!")
> 		g.Client().PostContent(ctx, "http://monitor.mydomain.com", s)
> 	}
> 
>        // trigger some panic 
> 	return w.logger.Write(p)
> }
> ```

I tried, but couldn't trigger this Writer

**Comment by gqcn** [comment]
@zcyc You need set the writer for the logger you are using. For example, `glog.SetWriter` or `g.Log().SetWriter`.
