### ISSUE TITLE
如何使用中间件去批量处理用规范路由定义的请求参数？

### ISSUE THREAD

**Issue by WankkoRee** [gogf/gf#2718]
### 1. What version of `Go` and system type/arch are you using?

`go version go1.20.5 windows/amd64`

### 2. What version of `GoFrame` are you using?

`v2.4.4`

### 3. Can this issue be re-produced with the latest release?

……

### 4. What did you do?

……

### 5. What did you expect to see?

我使用了规范路由，并且希望在 controller 中获取到的 Req 是经过中间件统一处理的（如解密等操作），可以实现吗？

在文档中没找到相关说明。

### 6. What did you see instead?

……

**Comment by starccck** [comment]
参考官网文档试一下 https://goframe.org/pages/viewpage.action?pageId=73224366 和 [ghttp](https://pkg.go.dev/github.com/gogf/gf/v2/net/ghttp)

**Comment by WankkoRee** [comment]
> 参考官网文档试一下 https://goframe.org/pages/viewpage.action?pageId=73224366 和 [ghttp](https://pkg.go.dev/github.com/gogf/gf/v2/net/ghttp)

我看过这个文档，但是没找到可以修改请求的方法，自己尝试了下发现request中的body是readonly的，不知道如何修改。

**Comment by LonelySally** [comment]
func (s *sMiddleware) DecodeData(r *ghttp.Request) {
	//读取加密数据
	data := r.Get("data", "").String()
	if data != "" {
		dataStr, err := gbase64.DecodeToString(data) //根据需求执行对应解密操作
		if err == nil && dataStr != "" {
			r.SetParamMap(gjson.New(dataStr).Map())//根据实际情况设置
		}
	}
	r.Middleware.Next()
}
这段代码在文档评论区放过 我忘记是哪页了

**Comment by LonelySally** [comment]
在中间件的前置行为中可以使用r.SetParam/r.SetQuery/r.SetForm设置对应的请求参数,并且在中间件中设置参数后会在后续的validate中支持自动校验.若还有问题请重新打开PR.
