### ISSUE TITLE
gf gen service func parser optimization

### ISSUE THREAD

**Issue by fakecore** [gogf/gf#2727]
### 1. What version of `Go` and system type/arch are you using?

go version go1.20.4 darwin/arm64

### 2. What version of `GoFrame` are you using?

CLI Built Detail:
  Go Version:  go1.17.13
  GF Version:  v2.3.2
  Git Commit:  2023-02-15 14:13:32 ad737ded3cd1354cb6f4208f11fcd8f99f94c5f3
  Build Time:  2023-02-15 14:17:00

### 3. Can this issue be re-produced with the latest release?
yes

### 4. What did you do?

I wanna use `gf gen service` to create an interface file for my logic code.
I wrote code like those.
```go
func(s*sBizTest)Test(){
}
```
I found no func declared in the interface file.

### 5. What did you expect to see?
//interface file.
```go
type (
	IBizTest interface {
	    Test() ()
	}
)
```

### 6. What did you see instead?
1. support multi code style func declaration
2. display the incorrect code style warning

**Comment by gqcn** [comment]
@fakecore You need define your function as or automatically format it as :
```go
func (s *sBizTest) Test() {
}
```
