### ISSUE TITLE
gf orm support interceptor

### ISSUE THREAD

**Issue by lusson-luo** [gogf/gf#2730]
### 1. What version of `Go` and system type/arch are you using?

go 1.19

### 2. What version of `GoFrame` are you using?

goframe v2.4.2

### 3. Can this issue be re-produced with the latest release?
goframe v2.4.2

### 4. What did you do?

goframe 的 orm 可以应该支持拦截器功能吗？这样我可以在拦截器里做一些统一操作，有以下场景
1. 多租户场景，在select 时统一添加租户id的查询
2. 当XXX创建成功后，需要给XXX推送一条业务消息；
3. 当XXX更新的时候，需要给XXX推送一条业务提醒；
4. 当XXX创建OR更新的时候，需要将最新的数据推送到搜索引擎中，以方便其他业务系统在搜索引擎中能查询到；
5. 当XXX更新的时候，需要更新分布式缓存的XXX数据；

### 5. What did you expect to see?
有一个统一拦截器去做通用操作，如果有方案讨论出来，我可以来实现

### 6. What did you see instead?
目前使用 hook 在每个地方做调用

**Comment by LonelySally** [comment]
当前没有全局的hook钩子,当然也可以通过自定义驱动去实现.[ORM接口开发-驱动开发](https://goframe.org/pages/viewpage.action?pageId=1114304).
关于hook可以在dao中定义一个公共方法提前引入到链式中.(PS:select的hook修改in.Table暂时是无效的) 例如:
```
func (f *fileDao) Init(ctx context.Context, tx ...gdb.TX) *gdb.Model {
	m := f.Ctx(ctx).Hook(driver.Hook.Func)
	if len(tx) > 0 {
		m.TX(tx[0])
	}
	return m
}
//used dao.File.Init(ctx)
```

**Comment by lusson-luo** [comment]
dao 一般是通过 gf 生成的代码，我理解dao不允许修改，否则重新生成会覆盖修改。

gf orm 有考虑加上过滤器功能吗，mybatis 是有过滤器功能的。

**Comment by LonelySally** [comment]
> dao 一般是通过 gf 生成的代码，我理解dao不允许修改，否则重新生成会覆盖修改。
> 
> gf orm 有考虑加上过滤器功能吗，mybatis 是有过滤器功能的。

dao是允许修改的(//Fill with you ideas below.),但是需要注意,在执行生成的时候不要指定为强制覆盖模式.另外dao的模板也是可以自定义的.
关于过滤功能不清楚你的需求场景无法给出建议.

**Comment by lusson-luo** [comment]
> 功能不清楚你的需求场景无法

@LonelySally 说的不太准确，是拦截器，拦截器的作用是方便代码在无侵入的形势下，对 orm 的操作做一些全局的处理，比如

**Comment by LonelySally** [comment]
> 

请参考我的第一条回复.

**Comment by lusson-luo** [comment]
> > 
> 
> 请参考我的第一条回复.

@LonelySally 我了解了 gorm 没有全局的拦截器功能这种，我想说 gorm 有必要去开发这个特性吗？

**Comment by lusson-luo** [comment]
两种方式实现
1. 通过自定义 driver（推荐），指引文档: https://goframe.org/pages/viewpage.action?pageId=1114158
2. 修改 dao 生成模版，指引文档: https://goframe.org/pages/viewpage.action?pageId=92132292，配置 tplDaoInternalPath，原 dao 的生成模版在 https://github.com/gogf/gf/blob/master/cmd/gf/internal/cmd/gendao/gendao_dao.go
