### ISSUE TITLE
Is there a built-in abstract interface for both gdb.TX and gdb.DB

### ISSUE THREAD

**Issue by halfcrazy** [gogf/gf#2731]
### 1. What version of `Go` and system type/arch are you using?

go version go1.20.4 linux/amd64

### 2. What version of `GoFrame` are you using?

github.com/gogf/gf/v2 v2.2.4

### 4. What did you do?

In `dao` layer i have a get/list method, expect to work with both gdb.TX and gdb.DB param.
```go
func ListUser(ctx context.Context, db gdb.DB) (*[]entity.User, error) {
	res := &[]entity.Users{}
	err := db.Ctx(ctx).Model(User.Table()).Scan(res)
	return res, err
}

func ListUserTx(ctx context.Context, tx gdb.TX) (*[]entity.User, error) {
	res := &[]entity.Users{}
	err := tx.Ctx(ctx).Model(User.Table()).Scan(res)
	return res, err
}
```

### 5. What did you expect to see?
In caller Eg. Logic layer, sometimes create gdb.DB instance and sometimes create gdb.TX instance.
Is there is a built-in abstract interface for both gdb.DB and gdb.TX to work for my case?

### 6. What did you see instead?
gdb module doesn't provide such interface

**Comment by LonelySally** [comment]
事务会通过ctx传播,不需要这样额外指定.[五、嵌套事务在工程中的参考示例](https://goframe.org/pages/viewpage.action?pageId=47699240#ORM%E4%BA%8B%E5%8A%A1%E5%A4%84%E7%90%86%E5%B5%8C%E5%A5%97%E4%BA%8B%E5%8A%A1-%E4%BA%94%E3%80%81%E5%B5%8C%E5%A5%97%E4%BA%8B%E5%8A%A1%E5%9C%A8%E5%B7%A5%E7%A8%8B%E4%B8%AD%E7%9A%84%E5%8F%82%E8%80%83%E7%A4%BA%E4%BE%8B)
