### ISSUE TITLE
When using HTTP service discovery, it will cause conflicts between g.Client() service discovery requests and normal requests

### ISSUE THREAD

**Issue by xgd16** [gogf/gf#2737]
When using HTTP service discovery, it will cause conflicts between g.Client() service discovery requests and normal requests
error:
2023-07-04 14:44:46.772 [31m[ERRO][0m {60638ab322976e174d71e211bfd4e564} service not found with name "api.mch.weixin.qq.com"
Stack:
1.  github.com/xgd16/gf-x-tool/xTool.CreateFastResponse
    /Users/xuguodong/go/pkg/mod/github.com/xgd16/gf-x-tool@v0.1.11/xTool/resp.go:55
2.  github.com/xgd16/gf-x-tool/xTool.FastResp
    /Users/xuguodong/go/pkg/mod/github.com/xgd16/gf-x-tool@v0.1.11/xTool/resp.go:43
3.  accountRegister/src/service/web/controller.SmsGetNumbersStatus
    /Users/xuguodong/code/go/accountRegistr/src/service/web/controller/sms.go:13
4.  github.com/gogf/gf/v2/net/ghttp.(*middleware).callHandlerFunc.func1
    /Users/xuguodong/go/pkg/mod/github.com/gogf/gf/v2@v2.4.4/net/ghttp/ghttp_request_middleware.go:131
5.  github.com/gogf/gf/v2/net/ghttp.niceCallFunc
    /Users/xuguodong/go/pkg/mod/github.com/gogf/gf/v2@v2.4.4/net/ghttp/ghttp_func.go:61
6.  github.com/gogf/gf/v2/net/ghttp.(*middleware).callHandlerFunc
    /Users/xuguodong/go/pkg/mod/github.com/gogf/gf/v2@v2.4.4/net/ghttp/ghttp_request_middleware.go:129
7.  github.com/gogf/gf/v2/net/ghttp.(*middleware).Next.func1.4
    /Users/xuguodong/go/pkg/mod/github.com/gogf/gf/v2@v2.4.4/net/ghttp/ghttp_request_middleware.go:90
8.  github.com/gogf/gf/v2/net/ghttp.niceCallFunc
    /Users/xuguodong/go/pkg/mod/github.com/gogf/gf/v2@v2.4.4/net/ghttp/ghttp_func.go:61
9.  github.com/gogf/gf/v2/net/ghttp.(*middleware).Next.func1
    /Users/xuguodong/go/pkg/mod/github.com/gogf/gf/v2@v2.4.4/net/ghttp/ghttp_request_middleware.go:89
10. github.com/gogf/gf/v2/util/gutil.TryCatch
    /Users/xuguodong/go/pkg/mod/github.com/gogf/gf/v2@v2.4.4/util/gutil/gutil.go:56
11. github.com/gogf/gf/v2/net/ghttp.(*middleware).Next
    /Users/xuguodong/go/pkg/mod/github.com/gogf/gf/v2@v2.4.4/net/ghttp/ghttp_request_middleware.go:49
12. github.com/gogf/gf/v2/net/ghttp.MiddlewareCORS
    /Users/xuguodong/go/pkg/mod/github.com/gogf/gf/v2@v2.4.4/net/ghttp/ghttp_middleware_cors.go:12
13. github.com/gogf/gf/v2/net/ghttp.(*middleware).Next.func1.5
    /Users/xuguodong/go/pkg/mod/github.com/gogf/gf/v2@v2.4.4/net/ghttp/ghttp_request_middleware.go:96
14. github.com/gogf/gf/v2/net/ghttp.niceCallFunc
    /Users/xuguodong/go/pkg/mod/github.com/gogf/gf/v2@v2.4.4/net/ghttp/ghttp_func.go:61
15. github.com/gogf/gf/v2/net/ghttp.(*middleware).Next.func1
    /Users/xuguodong/go/pkg/mod/github.com/gogf/gf/v2@v2.4.4/net/ghttp/ghttp_request_middleware.go:95
16. github.com/gogf/gf/v2/util/gutil.TryCatch
    /Users/xuguodong/go/pkg/mod/github.com/gogf/gf/v2@v2.4.4/util/gutil/gutil.go:56
17. github.com/gogf/gf/v2/net/ghttp.(*middleware).Next
    /Users/xuguodong/go/pkg/mod/github.com/gogf/gf/v2@v2.4.4/net/ghttp/ghttp_request_middleware.go:49
18. github.com/gogf/gf/v2/net/ghttp.internalMiddlewareServerTracing
    /Users/xuguodong/go/pkg/mod/github.com/gogf/gf/v2@v2.4.4/net/ghttp/ghttp_middleware_tracing.go:79
19. github.com/gogf/gf/v2/net/ghttp.(*middleware).Next.func1.5
    /Users/xuguodong/go/pkg/mod/github.com/gogf/gf/v2@v2.4.4/net/ghttp/ghttp_request_middleware.go:96
20. github.com/gogf/gf/v2/net/ghttp.niceCallFunc
    /Users/xuguodong/go/pkg/mod/github.com/gogf/gf/v2@v2.4.4/net/ghttp/ghttp_func.go:61
21. github.com/gogf/gf/v2/net/ghttp.(*middleware).Next.func1
    /Users/xuguodong/go/pkg/mod/github.com/gogf/gf/v2@v2.4.4/net/ghttp/ghttp_request_middleware.go:95
22. github.com/gogf/gf/v2/util/gutil.TryCatch
    /Users/xuguodong/go/pkg/mod/github.com/gogf/gf/v2@v2.4.4/util/gutil/gutil.go:56
23. github.com/gogf/gf/v2/net/ghttp.(*middleware).Next
    /Users/xuguodong/go/pkg/mod/github.com/gogf/gf/v2@v2.4.4/net/ghttp/ghttp_request_middleware.go:49
24. github.com/gogf/gf/v2/net/ghttp.(*Server).ServeHTTP
    /Users/xuguodong/go/pkg/mod/github.com/gogf/gf/v2@v2.4.4/net/ghttp/ghttp_server_handler.go:132

**Comment by xgd16** [comment]
// Temporary processing
c := gclient.Client()
c.SetDiscovery(nil)

**Comment by gqcn** [comment]
@xgd16 https://github.com/gogf/gf/pull/2738
