### ISSUE TITLE
gjson模块增加对ini数据格式的支持

### ISSUE THREAD

**Issue by johngcn** [gogf/gf#274]
需求背景：
`gcfg`其实底层是基于`gjson`模块，目前支持了`json/xml/yaml/toml`四种常见的数据格式支持，但是一直没有增加对`ini`数据格式的支持，因为目前流行的`ini`数据格式解析包都是按照`section`的方式进行数据操作，而`gjson`采用的是层级操作方式，因此`gsjon`的操作方式对于开发者来说更加方便。

实现难度：约3星半

实现建议：
务必需要实现对`ini`数据格式的层级操作方式，以便于统一配置文件操作方式。优先考虑封装现有的成熟的第三包，当第三方包实在无法满足需求时，可考虑自己实现对`ini`文件进行解析。

**Comment by wenzi1** [comment]
层级操作方式是什么意思？
例如INI格式为：
[SECTION1]
FIELD1=1
FIELD2=2
[SECTION2]
FIELD3=3
FIELD4=4

取某个字段的方式为：SECTION1.FILED1 这样？

**Comment by johngcn** [comment]
@wenzi1 是的，就是这个意思。

**Comment by wenzi1** [comment]
我增加了gini包，还没提交，等下个版本再提交吗

**Comment by johngcn** [comment]
@wenzi1 嗯，是的，所有PR都等新版本发布之后再合并，不过你可以先提PR我先review。

**Comment by johngcn** [comment]
@wenzi1 你提交的`gini`模块有个问题，当文件存在`ini`语法问题时，解析失败后没有`error`返回，复现代码：
```go
package main

import (
	"fmt"
	"github.com/gogf/gf/encoding/gini"
)

func main() {
	s := `
a = b

`
	m, err := gini.Decode([]byte(s))
	fmt.Println(err)
	fmt.Println(m)
}
```
执行后，输出为：
```
<nil>
map[]
```
其实这个内容存在语法问题。
