### ISSUE TITLE
关于gf增加支持casbin权限管理模块的需求

### ISSUE THREAD

**Issue by joyoes** [gogf/gf#275]
需求背景：
每一个成熟的框架都必须要有一个rbac权限管理模块的支持，但gf还没有。

实现难度：约3星半

实现建议：
通过这段时间对casbin的深入研究，发现这个基于go的权限管理非常灵活，实现起来也很方便，建议将这个模块集成到gf框架中。

**Comment by zhwei820** [comment]
可能的话 建议做成插件的形式. 如果使用mysql存储权限数据, 还需要考虑表结构的维护问题, 目前的orm不支持表结构管理.

**Comment by johngcn** [comment]
@joyoes 哈哈，你这个issue写得好

**Comment by johngcn** [comment]
@zhwei820 我最近在设计插件的规范格式，这个功能当然最好也是用插件的形式。

**Comment by joyoes** [comment]
@johngcn 你是不是设计gf插件的规范格式嘛？分享给我一起学习一下嘛，好不好？

**Comment by joyoes** [comment]
@johngcn 现在不管哪个语言框架都至少有一个RABC的功能，但GF到现在都还没有，你说该不该有嘛？

**Comment by zhwei820** [comment]
@joyoes  [https://github.com/hailaz/gadmin](gadmin) 可以参考这个项目的后端哈 写的挺不错的 集成的是casbin。 应该能够暂时满足你的需求～

**Comment by zhwei820** [comment]
> @zhwei820 我最近在设计插件的规范格式，这个功能当然最好也是用插件的形式。

插件的规范格式怎么样了？ 有没有提上日程~ 我这边打算做一个rbac的插件和后台。

**Comment by johngcn** [comment]
@zhwei820 已经开发完成，使用的是中间件的方式，正在测试。

**Comment by vance-liu** [comment]
可以参考这个 https://github.com/vance-liu/gdb-adapter

**Comment by sbilly** [comment]
期待，支持集成 casbin

**Comment by hailaz** [comment]
[gdb-adapter](https://github.com/vance-liu/gdb-adapter) - GoFrame ORM adapter for Casbin.
[gf-casbin-adapter](https://github.com/hailaz/gf-casbin-adapter) - GoFrame ORM adapter for Casbin.
