### ISSUE TITLE
建议增加ExitRequest

### ISSUE THREAD

**Issue by minchenzz** [gogf/gf#276]
微信小程序不支持cookie，所以设置自定义header。
有的api需要在before request hook里做一些权限验证，验证未通过后不再执行api方法，但是要执行after request hook 设置自定义header。
建议增加一个ExitRequest，退出brefore request hook和请求api，但是执行after request hook。

**Comment by johngcn** [comment]
@minchenzz `v2.0.0`新版本会增加`MiddleWare`中间件功能，你可以使用中间件来实现，更加灵活。预计本月中下旬发布。

**Comment by minchenzz** [comment]
@johngcn 支持大佬！加油！

**Comment by johngcn** [comment]
@minchenzz 请使用最新版本的中间件功能来实现吧：https://goframe.org/net/ghttp/router/middleware
