### ISSUE TITLE
func (d *Driver) TableFields obtains column information order inconsistent with the database

### ISSUE THREAD

**Issue by zundaren** [gogf/gf#2761]
![image](https://github.com/gogf/gf/assets/44863479/b88e016b-6df1-4d11-bf60-c529b252192f)
这个是mysql驱动里面的获取操作，其他的启动应该都差不多，期望这里能够按数据库读取的顺序提供一个顺序操作map结构，不然像动态展示的列显示都是乱的，或者有没有其他的解决方法

**Comment by LonelySally** [comment]
// As a map is unsorted, the TableField struct has a "Index" field marks its sequence in the fields.
```
for i, m := range result {
		fields[m["Field"].String()] = &gdb.TableField{
			Index:   i,  //index field
			Name:    m["Field"].String(),
			Type:    m["Type"].String(),
			Null:    m["Null"].Bool(),
			Key:     m["Key"].String(),
			Default: m["Default"].Val(),
			Extra:   m["Extra"].String(),
			Comment: m["Comment"].String(),
		}
	}
```
根据fields[m["Field"].String()].Index 排序转为数组即可 [参考](https://github.com/gogf/gf/blob/master/cmd/gf/internal/cmd/gendao/gendao.go#L396)

**Comment by zundaren** [comment]
> // As a map is unsorted, the TableField struct has a "Index" field marks its sequence in the fields.
> 
> ```
> for i, m := range result {
> 		fields[m["Field"].String()] = &gdb.TableField{
> 			Index:   i,  //index field
> 			Name:    m["Field"].String(),
> 			Type:    m["Type"].String(),
> 			Null:    m["Null"].Bool(),
> 			Key:     m["Key"].String(),
> 			Default: m["Default"].Val(),
> 			Extra:   m["Extra"].String(),
> 			Comment: m["Comment"].String(),
> 		}
> 	}
> ```
> 
> 根据fields[m["Field"].String()].Index 排序转为数组即可 [参考](https://github.com/gogf/gf/blob/master/cmd/gf/internal/cmd/gendao/gendao.go#L396)

thank you DaLao, Solved the problem。
