### ISSUE TITLE
There are some issues with manually managing caching in the database

### ISSUE THREAD

**Issue by ifelsedo** [gogf/gf#2770]
### 1. What version of `Go` and system type/arch are you using?
$ gf version
GoFrame CLI Tool v2.4.4, https://goframe.org
GoFrame Version: v2.4.4 in current go.mod
CLI Installed At: D:\Golang\bin\gf.exe
Current is a custom installed version, no installation information.

### 2. What version of `GoFrame` are you using?
2.4.4

### 3. Can this issue be re-produced with the latest release?
yes

### 4. What did you do?
数据库查询缓存里面手动清除缓存的两个方法查看源码发现实现是一样的，都是清除数据库所有缓存。
```go
// ClearCache removes cached sql result of certain table.
func (c *Core) ClearCache(ctx context.Context, table string) (err error)

// ClearCacheAll removes all cached sql result from cache
func (c *Core) ClearCacheAll(ctx context.Context) (err error)
```
另外一个手动删除指定 key 的缓存的方法不生效，在 Cache 中设置的 Name 无法直接使用
```go
func (Adapter) Remove(ctx context.Context, keys ...interface{}) (lastValue *gvar.Var, err error)
```
包括 `g.DB().GetCache()` 下的缓存操作方法无法直接操作链式操作中的 Cache，查看源码才知道有个查询前缀："SelectCache:"
```go
g.Model("user").Ctx(ctx).Cache(gdb.CacheOption{Duration: time.Hour, Name:"vip-user"}).Where("uid", 1).One() // set cache
g.DB().GetCache().Remove(ctx, "vip-user") // remove fail
g.DB().GetCache().Remove(ctx, "SelectCache:vip-user") // ok
```

### 5. What did you expect to see?
希望修复，另外希望在文档中有所提示

**Comment by oldme-git** [comment]
问题汇总到：#3313
show: #3313
