### ISSUE TITLE
How should `gf gen ctrl` command be used correctly? Why isn't it working？

### ISSUE THREAD

**Issue by z91300** [gogf/gf#2778]
### 1. What version of `Go` and system type/arch are you using?
go 1.20 windows

### 2. What version of `GoFrame` are you using?
gf and gf gen tool  =>  v2.5

### 3. Can this issue be re-produced with the latest release?
lastest version

1. go init mygfapp
2. cd mygfapp
3. 删除internal/controller/hello文件夹
4. 执行 gf gen ctrl

版本
项目内的gf版本和gf工具版本均升级到最新 v2.5

期望：
会根据init项目时默认的api/v1/hello 自动生成出 internal/controller/hello中的内容，即hello的controller层

现象：
执行gf gen ctrl ，提示 done，命令行无报错，项目内无反应，没有文件被生成

问题：
应该怎样能根据api文件生成controller层？

![a3057b4d18077233a85d021dc29a48d](https://github.com/gogf/gf/assets/73412370/8e5e3e83-6be7-4203-96e5-eda472a8d95e)

![image](https://github.com/gogf/gf/assets/73412370/c636168a-b2a8-42dd-a65c-39cef08e007a)

**Comment by yzy613** [comment]
你试试把`api/hello`和`api/hello/v1`名字互换一下

**Comment by z91300** [comment]
> 你试试把`api/hello`和`api/hello/v1`名字互换一下，使之变成`api/v1/hello`
@yzy613 
是这样吗？可是还是没有作用，api/v1/hello/hello.go   api/v1/hello.go   api/hello.go  api/hello/v1/hello.go 都不行0.0

**Comment by yzy613** [comment]
> > 你试试把`api/hello`和`api/hello/v1`名字互换一下，使之变成`api/v1/hello`
> @yzy613 
> 是这样吗？可是还是没有作用，api/v1/hello/hello.go   api/v1/hello.go   api/hello.go  api/hello/v1/hello.go 都不行0.0
> 
> 

那就不是很清楚了，我这样生成是正确的

**Comment by z91300** [comment]
![image](https://github.com/gogf/gf/assets/73412370/05ec11f7-2469-4ae3-ad71-14af73044072)

@yzy613 是这样吗大概

**Comment by z91300** [comment]
方便提供一个您的目录结构以及示例`api/**/**.go`文件吗

**Comment by yzy613** [comment]
@z91300 
api/v1/public/public.go
```go
package public

import "github.com/gogf/gf/v2/frame/g"

type GetFileReq struct {
	g.Meta   `path:"/*filename" method:"get" tags:"file" summary:"读取文件"`
	Filename string `json:"filename" v:"required" description:"必填"`
}
type GetFileRes struct {
}
```

**Comment by z91300** [comment]
太感谢了，这段代码解决了我的问题，原来就是我`**.go`文件写的有问题，之前想过可能是它的问题，但是这是通过gf init生成的示例代码，我也就有些下意识忽略了，主要也不知道正确的怎么写。
