### ISSUE TITLE
gf 1.16.3 not support vaild nested struct?

### ISSUE THREAD

**Issue by MrGlp** [gogf/gf#2791]
gf 1.16.3 not support vaild nested struct?

// TaskCommitArgs 任务提交入参
type TaskCommitArgs struct {
	ResourceList []*ResourceInfo `json:"resource_list" v:"required"` // 任务列表
	UploadDir    int64           `json:"upload_dir"`                 // 文件夹 id, 为空则下载到用户默认文件夹
	Url          string          `json:"url" v:"required-without:InfoHash"`
	InfoHash     string          `json:"info_hash" v:"required-without:Url"`
}

// ResourceInfo 需要下载的资源详情
type ResourceInfo struct {
	Url        string `json:"url" v:"required-without:InfoHash"`
	InfoHash   string `json:"info_hash" v:"required-without:Url"`
	SelectFile string `json:"select_file"`
}

、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、

request jons:
{  
    "resource_list":[
        {
            "url": "",
            "info_hash": ""
            // "select_file": "1"
        }
    ],
    "url":"s",
    "info_hash":"s",
    "upload_dir": 0
}

return: check ok

The validation for the properties 'Url' and 'InfoHash' inside the 'TaskCommitArgs' structure didn't work as expected. Is it not supported in this version, or did I use it incorrectly? I used the 'Parse' method for validation.

**Comment by hailaz** [comment]
https://goframe.org/pages/viewpage.action?pageId=17204104#id-%E7%BB%93%E6%9E%84%E4%BD%93%E6%A0%A1%E9%AA%8CCheckStruct-%E7%BB%93%E6%9E%84%E4%BD%93embedded%E5%B5%8C%E5%A5%97%E6%A0%A1%E9%AA%8C

**Comment by MrGlp** [comment]
thk
