### ISSUE TITLE
In orm, the Fields function is used without quotes.

### ISSUE THREAD

**Issue by KevinMyDing** [gogf/gf#2809]
### 1. What version of `Go` and system type/arch are you using?

`go version go1.19.4 windows/amd64`

### 2. What version of `GoFrame` are you using?

`v2.5.1`

### 3. Can this issue be re-produced with the latest release?
Yes

### 4. What did you do?

In orm, the Fields function is used without quotes, which causes pgsql to return the column does not existed error.
```go
dao.Order.Ctx(context.Background()).Fields(
	dao.Order.Columns().UserId,
).FieldSum(dao.Order.Columns().Bonus, "Bonus").Where(
	g.Map{
		dao.Order.Columns().Status: 1,
	}).Group(dao.Order.Columns().UserId).All()
```
```
SQL:   SELECT userId,SUM("bonus") AS "Bonus" FROM "order" WHERE "status"=1 GROUP BY "userId"

ERROR:  column "userid" does not exist
```

**Comment by oldme-git** [comment]
@gqcn connot reproduce
