### ISSUE TITLE
post数据转struct异常 (方法：func (r *Request) GetToStruct(pointer interface{}, mapping ...map[string]string) )

### ISSUE THREAD

**Issue by zhang201702** [gogf/gf#282]
![image](https://user-images.githubusercontent.com/25653917/62758828-17ef1400-bab2-11e9-8650-bb9f2176a211.png)
![image](https://user-images.githubusercontent.com/25653917/62758874-39e89680-bab2-11e9-8dfe-e74c9feaa3c3.png)
前端web post请求的参数
![image](https://user-images.githubusercontent.com/25653917/62758890-466cef00-bab2-11e9-8434-3245a22cb34a.png)
==================
如果 headers或request为空集合时，就会报异常。
如果有值，就可以成功，如下：
![image](https://user-images.githubusercontent.com/25653917/62758977-8e8c1180-bab2-11e9-9c32-f5f25bd96221.png)

**Comment by johngcn** [comment]
@zhang201702 能否提供可运行的完整代码。

**Comment by johngcn** [comment]
@zhang201702 或者把你截图的代码粘贴一下。。。

**Comment by johngcn** [comment]
@zhang201702 当你给定的对象是一个`nil`指针时，你应当使用以下方式初始化对象：
```go
str := (*Struct)(nil)
err := r.GetPostToStruct(&str)
```
即`struct`空对象的指针的指针，这样才能使得`str`能够被内部初始化。
