### ISSUE TITLE
go-redis v9

### ISSUE THREAD

**Issue by shuqingzai** [gogf/gf#2821]
是否可以支持 [go-redis/v9](https://github.com/redis/go-redis) 版本？？
1. v9 版本已被 redis 官方收录为官方客户端
2. v9 可以支持 redis7
3. v9 已发布半年多，大部分主流的第三方包都已经支持，但是 gf 没有支持 v9 的版本，导致很多第三方包无法使用

### 1. What version of `Go` and system type/arch are you using?

`go version go1.20.6 darwin/amd64`

### 2. What version of `GoFrame` are you using?

`GF Version:  v2.5.1`

**Comment by houseme** [comment]
可以去 nosql/redis 下新建一个支持，可以用户自己选择使用哪个
