### ISSUE TITLE
Live rebuild when `manifest/config/config.yaml` changed

### ISSUE THREAD

**Issue by windvalley** [gogf/gf#2822]
### 1. What version of `Go` and system type/arch are you using?

go version go1.20.4 darwin/amd64

### 2. What version of `GoFrame` are you using?

GoFrame CLI Tool v2.5.1, https://goframe.org
GoFrame Version: v2.5.1 in current go.mod

### 3. Can this issue be re-produced with the latest release?

yes

### 4. What did you do?

```go
$ gf run main.go
```

然后修改`manifest/config/config.yaml`文件.  
### 5. What did you expect to see?

希望 `gf run main.go` 能自动rebuild

### 6. What did you see instead?

`gf run main.go` 没有自动rebuild.

看源码, 目前只是针对go文件的变动才会自动rebuild, 不过在实际开发中, 开发环境配置文件可能会是要频繁变动的, 这样每次都需要重新运行 `gf run main.go`, 比较麻烦, 是否考虑增加配置文件变动的场景也能自动rebuild的功能. 如果可以的话, 我提个pr, 感谢~

ps:  后续又测了一下, 配置文件有热更新功能, 不过貌似仅对自定义的配置生效, 对框架原生相关的配置项调整没有效果, 所以考虑到`gf run main.go`仅是在开发环境使用, 加一个配置文件变化自动rebuild的特性, 应该可以接受.

**Comment by gqcn** [comment]
@windvalley 可以给`gf run`命令增加一个参数，控制额外监听的文件路径下的对应类型文件变化。例如：欢迎pr
<img width="1521" alt="image" src="https://github.com/gogf/gf/assets/26347176/fe480956-95f7-48d3-bdca-cf50a5807400">
