### ISSUE TITLE
gf gen service work with mistake

### ISSUE THREAD

**Issue by liaowj5** [gogf/gf#2824]
### 1. What version of `Go` and system type/arch are you using?

macos

### 2. What version of `GoFrame` are you using?

GoFrame CLI Tool v2.5.1, https://goframe.org
GoFrame Version: v2.3.1 in current go.mod
CLI Installed At: /opt/homebrew/bin/gf
CLI Built Detail:
  Go Version:  go1.20.4
  GF Version:  v2.5.1
  Git Commit:  2023-07-26 21:27:58 e0e00434cc87d6edf64fc3df40ce7d3f40758794
  Build Time:  2023-07-26 21:32:56

### 3. Can this issue be re-produced with the latest release?

Yes

### 4. What did you do?

gf gen service

### 5. What did you expect to see?

generate logic.go (go file) in internal/logic

### 6. What did you see instead?

generate logic.go (as folder) instead, and has no go files under logic folder.

**Comment by pingProMax** [comment]
GoFrame CLI Tool v2.5.1, https://goframe.org
GoFrame Version: v2.5.1 in current go.mod
go version go1.20.5 windows/amd64
vscode

My question is the same as yours

**Comment by gqcn** [comment]
@liaowj5 @pingProMax Please use the latest version of cli, submit a new issue if this persists.

**Comment by Gallery2000** [comment]
I have this problem too gf v2.6.3

**Comment by xuwuruoshui** [comment]
我也遇到了，是不是都不用代码生成，都是手写的

**Comment by xuwuruoshui** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by ragnaros2046** [comment]
same error

**Comment by xuwuruoshui** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
