### ISSUE TITLE
How to indicate a bool field may be nil in ORM dao generation?

### ISSUE THREAD

**Issue by chamhaw** [gogf/gf#2829]
### 1. What version of `Go` and system type/arch are you using?

go version go1.20.4 darwin/arm64

### 2. What version of `GoFrame` are you using?

v2.4.1

### 3. Can this issue be re-produced with the latest release?

yes

### 4. What did you do?

Added a colume to a table then used `make dao`
```sql
 `code_scan` bit(1) DEFAULT NULL
```

### 5. What did you expect to see?
```go
 CodeScan *bool
```
 Wanna distinguish between nil and false. 

### 6. What did you see instead?

 CodeScan bool

**Comment by gqcn** [comment]
@chamhaw If nil, the bool filed is considered `false`. What is your business scenario that needs distinguish nil and false?
