### ISSUE TITLE
[Question] Does ORM support some shortcut operations

### ISSUE THREAD

**Issue by shuqingzai** [gogf/gf#2831]
如下一些很实用且高频使用的快捷方法，无论是 `laravel` 或 `gorm` 都支持这些方法，但在 gf 的 ORM 文档我似乎没有找到，可能是我疏忽了，请问支持吗？

- `first() 、take() 、last()` 根据条件获取第一条（根据主键排序 ASC）、获取一条、获取最新一条（根据主键排序 DESC） 记录
- `firstOrNew() || FirstOrInit()` 找不到则根据给定的数据创建一个 Entity 实例，但未保存数据库
- `firstOrCreate()` 找不到则根据给定的数据创建一个 Entity 实例且自动保存数据库
- `updateOrCreate()` 根据给定的条件查找数据，如果存在则更新给定的数据，否则使用给定的数据创建记录

### 1. What version of `Go` and system type/arch are you using?

```bash
#-> % go version
go version go1.20.6 darwin/amd64
```

### 2. What version of `GoFrame` are you using?

```bash
#-> % gf --version
GoFrame CLI Tool v2.5.1, https://goframe.org
GoFrame Version: v2.5.1 in current go.mod
```

**Comment by shuqingzai** [comment]
> 文档里面不是都有吗

我好像没找到，妳能发我链接看看吗？ @wln732 w

**Comment by wln732** [comment]
> > 文档里面不是都有吗
> 
> 我好像没找到，妳能发我链接看看吗？ @wln732

https://goframe.org/pages/viewpage.action?pageId=1114344

**Comment by shuqingzai** [comment]
> > > 文档里面不是都有吗
> > 
> > 
> > 我好像没找到，妳能发我链接看看吗？ @wln732
> 
> https://goframe.org/pages/viewpage.action?pageId=1114344

这只是 插入数据的保存 ，并没有实现我说的那几个方法 @wln732

**Comment by wln732** [comment]
1.firstOrNew() || FirstOrInit() 找不到则根据给定的数据创建一个 Entity 实例，但未保存数据库
    搞不明白你这个的逻辑，你这个默认的实例，那他的字段值是多少？？go的orm都是让你先手动新建个默认值，然后scan赋值
2.first() 、take() 、last() 根据条件获取第一条（根据主键排序 ASC）、获取一条、获取最新一条（根据主键排序 DESC） 记录
    这些不都是写在sql里面的吗
3.updateOrCreate() 根据给定的条件查找数据，如果存在则更新给定的数据，否则使用给定的数据创建记录
   使用INSERT INTO语句进行数据库写入，如果写入的数据中存在主键或者唯一索引时，更新原有数据，否则写入一条新数据。
   这个是gf orm的文档说明
4. firstOrCreate() 找不到则根据给定的数据创建一个 Entity 实例且自动保存数据库
    也就这个没有实现而已，自己可以封装个方法

**Comment by shuqingzai** [comment]
> 1.firstOrNew() || FirstOrInit() 找不到则根据给定的数据创建一个 Entity 实例，但未保存数据库 搞不明白你这个的逻辑，你这个默认的实例，那他的字段值是多少？？go的orm都是让你先手动新建个默认值，然后scan赋值 2.first() 、take() 、last() 根据条件获取第一条（根据主键排序 ASC）、获取一条、获取最新一条（根据主键排序 DESC） 记录 这些不都是写在sql里面的吗 3.updateOrCreate() 根据给定的条件查找数据，如果存在则更新给定的数据，否则使用给定的数据创建记录 使用INSERT INTO语句进行数据库写入，如果写入的数据中存在主键或者唯一索引时，更新原有数据，否则写入一条新数据。 这个是gf orm的文档说明 4. firstOrCreate() 找不到则根据给定的数据创建一个 Entity 实例且自动保存数据库 也就这个没有实现而已，自己可以封装个方法

1. 你可以查阅 gorm 的文档示例
2. 我的主题是快捷高频操作，这几个方法在日常开发中都是属于这一类，按你说的每个查询都自己使用 `order by` ，相当于很多地方都编写同一段重复逻辑代码，这就不算快捷了
3. 也许你是对的，gf 使用 `replace into` 的方式实现 `save`
4. 嗯，如果 gf 没有实现，只能这样，看了文档没找到，才询问的

**Comment by wln732** [comment]
```go
// FirstOrInit这个api完全是多此一举，
db.FirstOrInit(&user, User{Name: "non_existing"})
// user -> User{Name: "non_existing"}
// 为什么不能是这种写法呢
var user = User{Name:"jack"}
db.First(&user)
```
你上面那种写法，没有找到数据，是不是还要在反射给&user赋值？
下面这种写法才是正常的，没有找到就不做任何动作
gf的orm推崇使用指针来提前声明
```go
var user *User
// 如果没有找到数据，user还是nil什么都不做
db.One(&user)

**Comment by gqcn** [comment]
@shuqingzai @wln732 大家好，在`goframe`里面的快捷封装方法确实不多，目前已提供的基础方法我理解都可以满足开发需要。如果确实有这方面的必要，欢迎参与一起建设。
