### ISSUE TITLE
go gen ctrl generates a single controller level

### ISSUE THREAD

**Issue by z91300** [gogf/gf#2837]
go gen ctrl 生成的controller层只有一个层级，而且是以函数为单位创建的文件，就导致某个业务模块接口多的话对应目录下也是一堆文件，有办法做个分层吗或者以业务为单位写controller也行啊，不然这个功能感觉有点鸡肋了，拾之无用弃之可惜

当前现象：
![image](https://github.com/gogf/gf/assets/73412370/c92f54fc-45e0-471f-bbc7-949f78a7ca71)

期望现象：
![d4d98bf778d91b437ab088499396271](https://github.com/gogf/gf/assets/73412370/da49e7ae-2f10-4fe3-a40e-6451dd0af03e)

参考实现（一个群友提供的方案）：
https://github.com/hinego/gf_gen

**Comment by z91300** [comment]
暂用方案：gf gen ctrl --srcFolder=api/system --dstFolder=internal/app/system/controller

**Comment by gqcn** [comment]
@z91300 你好，`cli`工具的`controller`生成功能是以`api`模块为主，你可以将众多的`api`划分为模块，然后一个`api`模块对应一个`controller`，该`api`模块下的所有接口都将生成独立的代码文件。
