### ISSUE TITLE
[BUG] gf gen ctrl cannot exclude the structure definition annotated in api

### ISSUE THREAD

**Issue by alaywn** [gogf/gf#2839]
### 1. What version of `Go` and system type/arch are you using?

go version go1.20.6 darwin/arm64

### 2. What version of `GoFrame` are you using?

GoFrame CLI Tool v2.5.1, https://goframe.org
GoFrame Version: v2.5.1 in current go.mod
CLI Installed At: /opt/homebrew/bin/gf
CLI Built Detail:
  Go Version:  go1.20.4
  GF Version:  v2.5.1
  Git Commit:  2023-07-26 21:27:58 e0e00434cc87d6edf64fc3df40ce7d3f40758794
  Build Time:  2023-07-26 21:32:56

### 3. Can this issue be re-produced with the latest release?

YES

### 4. What did you do?

注释了api中定义的结构体，然后运行gf gen ctrl，结果被注释的结构体，仍然生成的controller

### 5. What did you expect to see?

希望gf gen ctrl执行时排除api中注释的结构体定义

**Comment by oldme-git** [comment]
Please show #3067
