### ISSUE TITLE
[BUG]gf gen service cannot correctly identify the package name under api (v1)

### ISSUE THREAD

**Issue by alaywn** [gogf/gf#2840]
### 1. What version of `Go` and system type/arch are you using?

go version go1.20.6 darwin/arm64

### 2. What version of `GoFrame` are you using?

```
GoFrame CLI Tool v2.5.1, https://goframe.org
GoFrame Version: v2.5.1 in current go.mod
CLI Installed At: /opt/homebrew/bin/gf
CLI Built Detail:
  Go Version:  go1.20.4
  GF Version:  v2.5.1
  Git Commit:  2023-07-26 21:27:58 e0e00434cc87d6edf64fc3df40ce7d3f40758794
  Build Time:  2023-07-26 21:32:56
```
### 3. Can this issue be re-produced with the latest release?

YES

### 4. What did you do?

前提：
存在两个api定义：
```
api/menu/v1
api/user/v1
```
注意：menu排序在user前面，根据字母自动排序的（非人为排序）

然后：
logic下的方法使用了`api/user/v1`中的结构体定义作为入参，比如：
```go
import "xxx/api/user/v1"
type sUser struct{}
func (r * sUser)Create(input *v1.CreateReq){
     //do something
}
```
此时执行`gf gen service`，生成的结果为：
```go
import "xxx/api/menu/v1"
type IUser interface {
        Create(input *v1.CreateReq)
}
```
注意：这里并没有正确导入，`"xxx/api/user/v1"`，而是导入了`"xxx/api/menu/v1"`

如果将logic中的导入改为`v1 import "xxx/api/user/v1"`，即取个别名，则生成结果是正确的

**Comment by gqcn** [comment]
@alaywn 请尝试使用最新版本，如果问题依旧，请重新打开该`issue`。
