### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by kuchaguangjie** [gogf/gf#2847]
- 执行 github readme 上的 `go install github.com/gogf/gf/cmd/gf/v2` 报错 说: 
  > go: 'go install' requires a version when current directory is not in a module
- 执行 `go install github.com/gogf/gf/cmd/gf/v2@latest` 报错:
  > go: github.com/gogf/gf/cmd/gf/v2@latest (in github.com/gogf/gf/cmd/gf/v2@v2.0.0-20230807131522-932f8c48ef29):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
- 执行 `go install github.com/gogf/gf/cmd/gf/v2@v2.5.1` 报错:
  > go: github.com/gogf/gf/cmd/gf/v2@v2.5.1: github.com/gogf/gf/cmd/gf/v2@v2.5.1: invalid version: unknown revision cmd/gf/v2.5.1

还非得 手工 下载 安装 不成 ?

**Comment by kuchaguangjie** [comment]
最后 用了这个:
> wget -O gf "https://github.com/gogf/gf/releases/latest/download/gf_$(go env GOOS)_$(go env GOARCH)" && chmod +x gf && ./gf install -y && rm ./gf

**Comment by wln732** [comment]
需要在go mod下先go get然后go install

**Comment by kuchaguangjie** [comment]
> 需要在go mod下先go get然后go install

Ok, 所以 试了下, 应该是:

```
cd project_dir/
go get github.com/gogf/gf/cmd/gf/v2
go install github.com/gogf/gf/cmd/gf/v2
gf-v
```
