### ISSUE TITLE
建议ghttp的Client增加代理设置

### ISSUE THREAD

**Issue by wehnhew** [gogf/gf#285]

**Comment by johngcn** [comment]
@wehnhew 你是否有研究过客户端的`Transport`设置？

**Comment by wehnhew** [comment]
另外设置Transport是能设置，这是常用的，增加个函数直接设置更方便

**Comment by wehnhew** [comment]
> @wehnhew 你是否有研究过客户端的`Transport`设置？

另外设置Transport是能设置，这是常用的，建议增加个函数直接设置更方便

**Comment by kirileec** [comment]
I will try

**Comment by kirileec** [comment]
增加了一个`NewClientWithProxy`方法用于设置代理, 支持http:// 和 socks5:// 这样的代理, 也支持代理用户名密码验证, 具体看该方法的注释 😄.  由于单元测试需要在代码中增加代理服务器的创建, 暂时还没有加

**Comment by gqcn** [comment]
@kirileec 感谢贡献，我已经在`PR`中回复你了，需要做一些调整，另外期望能在单元测试中增加简单的代理测试一下该功能。
