### ISSUE TITLE
[Question] How should I judge whether the HTTP request exception is caused by panic? ?

### ISSUE THREAD

**Issue by shuqingzai** [gogf/gf#2852]
1. 在进行错误统一处理时，无法得知 error 是否为 panic 转换而来，且没有可以注册自定义程序处理 panic 引发的异常

参考：

https://github.com/gogf/gf/blob/243fe73c57de8bfc12ae1f13266ee52206e737a6/net/ghttp/ghttp_request_middleware.go#L50

https://github.com/gogf/gf/blob/243fe73c57de8bfc12ae1f13266ee52206e737a6/util/gutil/gutil.go#L46

![image](https://github.com/gogf/gf/assets/44406033/1662f050-42ed-4f06-8a44-0fab4a2650dd)

![image](https://github.com/gogf/gf/assets/44406033/f743830f-66f3-4543-b396-d88824399bae)

**Comment by LonelySally** [comment]
r.GetError() != nil && r.Response.BufferLength() > 0 可以尝试下组合判断下.这里好像是缺少错误类型的区分.

**Comment by shuqingzai** [comment]
#2860  close #2852
