### ISSUE TITLE
[BUG]gf gen dao generated field type error

### ISSUE THREAD

**Issue by grenyang** [gogf/gf#2862]
1. What version of `Go` and system type/arch are you using?
go version go1.20.6 darwin/arm64

2. What version of `GoFrame` are you using?
GoFrame CLI Tool v2.5.1, https://goframe.org/
GoFrame Version: v2.5.1 in current go.mod
CLI Installed At: /opt/homebrew/bin/gf
CLI Built Detail:
Go Version: go1.20.4
GF Version: v2.5.1
Git Commit: 2023-07-26 21:27:58 https://github.com/gogf/gf/commit/e0e00434cc87d6edf64fc3df40ce7d3f40758794
Build Time: 2023-07-26 21:32:56

3. Can this issue be re-produced with the latest release?
YES

4. What did you do?
在Postgre@15数据库中自定义的菜单类型包括‘date’字符，使用gf gen dao命令生成代码中结构体字段类型变成了*gtime.Time

执行步骤如下：
a.在Postgre@15数据库中创建表tom_year_to_date_m，包括kind字段，类型为VARCHAR
b.自定义菜单类型(类型中包括了'date'字符)：
CREATE TYPE enum_year_to_date_kind AS ENUM ('folder','year_to_date');
c.修改字段类型：
ALTER TABLE tom_year_to_date_m
ALTER COLUMN "kind" TYPE enum_year_to_date_kind
USING kind::enum_year_to_date_kind;
c.执行gf gen dao
d.发现生成代码dao和entity中，结构体字段类型变成了*gtime.Time

5. What did you expect to see?
希望gf gen dao命令生成的字段类型取自定义菜单的值基础类型，比如string

6. What did you see instead?

**Comment by LonelySally** [comment]
使用cli的typeMapping特性配置下试试

**Comment by gqcn** [comment]
> 使用cli的typeMapping特性配置下试试

对的，这种数据库中自定义类型对应的Golang类型建议通过TypeMapping特性来自定义配置哈，参考文档：https://goframe.org/pages/viewpage.action?pageId=3673173

@grenyang
