### ISSUE TITLE
what is the meannig of -rm suffix

### ISSUE THREAD

**Issue by zcwhy** [gogf/gf#2866]
default |  :8199  | default | POST   | 2 | /auth/login            | github.com/gogf/gf-jwt.(*GfJWTMiddleware).LoginHandler-fm   |             
|---------|---------|---------|--------|---|------------------------|-------------------------------------------------------------|------------|
  default |  :8199  | default | POST   | 2 | /auth/refresh          | github.com/gogf/gf-jwt.(*GfJWTMiddleware).RefreshHandler-fm 

my register handler is RefreshHandler why it print -fm suffix？ what is the mening of -fm

**Comment by hailaz** [comment]
https://github.com/golang/go/issues/52809

**Comment by zcwhy** [comment]
@hailaz thanks so much!
