### ISSUE TITLE
建议gf增加token验证模块

### ISSUE THREAD

**Issue by joyoes** [gogf/gf#287]
建议gf增加token验证模块，因为经常都会将GO作为API开发，所以TOKEN经常都会用到！也就是的RESTful api的token认证的具体实现,gf连Session和Cookie都有了，就只差API端的token了，什么时候能出来啊？

**Comment by johngcn** [comment]
@joyoes `v2.0`支持通过header传递`sessionid`，这是你想要的吗？

**Comment by joyoes** [comment]
@johngcn V2.0什么时候出来啊？

**Comment by johngcn** [comment]
@joyoes 还有2-4个周吧

**Comment by johngcn** [comment]
@joyoes `gf`最新版本已经支持通过`header`传递`sessionid`了，这个是你想要的吗？另外也可以考虑`jwt`: https://github.com/gogf/gf-jwt
