### ISSUE TITLE
[feat] gregex support regexp.Regexp object as input

### ISSUE THREAD

**Issue by WankkoRee** [gogf/gf#2870]
能否为gregex模块添加对直接传入`regexp.Regexp`对象的支持。

有些时候正则表达式对象需要持久化管理和使用，虽然gregex模块已有内置的表达式复用机制，但是仍然需要锁和错误处理。

如果支持使用用户传入的表达式对象，则锁与错误处理在这种使用情况下都可以剔除。

**Comment by gqcn** [comment]
@WankkoRee 如果已经有`regexp.Regexp`对象那么可以直接使用该对象不用通过`gregex`包了。`gregex`包主要是提供了一些便捷方法来使用正则，显著的特性是内置了对象缓存，该特性也有优劣，我在项目使用中会根据场景来选择使用，有时在对性能要求比较高的场景中，也会直接使用标准库的`regexp.Regexp`对象。
