### ISSUE TITLE
graceful reload feature is disabled

### ISSUE THREAD

**Issue by kuchaguangjie** [gogf/gf#2871]
When follow guide:
https://goframe.org/pages/viewpage.action?pageId=1114220#id-%E5%B9%B3%E6%BB%91%E9%87%8D%E5%90%AF%E7%89%B9%E6%80%A7-%E7%A4%BA%E4%BE%8B1%EF%BC%9A%E5%9F%BA%E6%9C%AC%E4%BD%BF%E7%94%A8

get error:
> graceful reload feature is disabled

How to enable it ?

**Comment by LonelySally** [comment]
[doc](https://goframe.org/pages/viewpage.action?pageId=44449486) => graceful:            false
