### ISSUE TITLE
[Question] How to replace the global cache component driver implementation? ?

### ISSUE THREAD

**Issue by shuqingzai** [gogf/gf#2875]
### 1. What version of `Go` and system type/arch are you using?

```bash
#-> % go version
go version go1.21.0 darwin/amd64
```

### 2. What version of `GoFrame` are you using?

```bash
#-> % gf version
GoFrame CLI Tool v2.5.1, https://goframe.org
GoFrame Version: v2.5.1 in current go.mod
CLI Installed At: /Code/go/bin/gf
CLI Built Detail:
  Go Version:  go1.20.4
  GF Version:  v2.5.1
  Git Commit:  2023-07-26 21:27:58 e0e00434cc87d6edf64fc3df40ce7d3f40758794
  Build Time:  2023-07-26 21:32:56
```

### 3. Can this issue be re-produced with the latest release?

是的

### 4. What did you do?

全局的 `gcache.*()` 函数提供了快捷调用默认 cache 实现 
https://github.com/gogf/gf/blob/e0e00434cc87d6edf64fc3df40ce7d3f40758794/os/gcache/gcache.go#L23C12-L23C12 看了源码是基于 `Memory` 实现的，但是并没有提供替换全局默认实现的函数，是否可以提供替换全局 cache 实现的方式，一般都是使用 redis 替换全局缓存实现，达到分布式缓存的目的

### 5. What did you expect to see?

希望可以提供替换全局默认 cache 实现

**Comment by houseme** [comment]
参考使用
```go
// Create redis client object.
redis, err := gredis.New(redisConfig)
if err != nil {
	panic(err)
}
// Create redis cache adapter and set it to cache object.
cache.SetAdapter(gcache.NewAdapterRedis(redis))
```

https://goframe.org/pages/viewpage.action?pageId=1114331#id-%E7%BC%93%E5%AD%98%E7%AE%A1%E7%90%86Redis%E7%BC%93%E5%AD%98-%E4%BD%BF%E7%94%A8%E7%A4%BA%E4%BE%8B
