### ISSUE TITLE
[goframeV2.5.1 & win7-i386 ] using "gf init demo -u", the demo cannot working. 

### ISSUE THREAD

**Issue by hutucha** [gogf/gf#2876]
windows 7 - i386; 
go : V1.21.4;
goframe : V2.5.1;
using "gf init demo -u"，the demo cannot working;

The prompt message is：
-----------------------------------
h:\\>gf init demo -u
initializing...
update goframe...
exec: no command
--------------------------------------
Please check if there is a problem and how to solve it

**Comment by shuqingzai** [comment]
go 1.21 似乎已经不支持 win7 了，而且你这也太老旧了吧

**Comment by xgd16** [comment]
official description!!!

Your windows version is too low, you need to upgrade the system to at least windows 10

Darwin
As [announced](https://go.dev/doc/go1.20#darwin) in the Go 1.20 release notes, Go 1.21 requires macOS 10.15 Catalina or later; support for previous versions has been discontinued.

Windows
As [announced](https://go.dev/doc/go1.20#windows) in the Go 1.20 release notes, Go 1.21 requires at least Windows 10 or Windows Server 2016; support for previous versions has been discontinued.

**Comment by xgd16** [comment]
or downgrade your golang version to v1.20

**Comment by hutucha** [comment]
> or downgrade your golang version to v1.20

It has been switched to Go  V1.20,  but the problem as before
