### ISSUE TITLE
duplicated code in func (r *SglResult) RowsAffected() (int64, error) 

### ISSUE THREAD

**Issue by ragnaros2046** [gogf/gf#2880]
### 1. What version of `Go` and system type/arch are you using?

main branch 

gf/database/gdb/gdb_result.go
```go
func (r *SqlResult) RowsAffected() (int64, error) {
	if r.Result == nil {
		return 0, nil
	}
	if r.Affected > 0 {
		return r.Affected, nil
	}
	if r.Result == nil {
		return 0, nil
	}
	return r.Result.RowsAffected()
}
```

**Comment by gqcn** [comment]
@ragnaros2046 What do you mean?

**Comment by ragnaros2046** [comment]
> @ragnaros2046 What do you mean?


代码有重复啊强哥  两个一样的
if r.Result == nil {
		return 0, nil
	}

**Comment by gqcn** [comment]
@ragnaros2046 Sorry for late reply, it was ready fix in https://github.com/gogf/gf/commit/887803e4950019f85e8373e5bef9be221dbddf59
