### ISSUE TITLE
Deprecation notice: Use the "google.golang.org/protobuf" module instead

### ISSUE THREAD

**Issue by ragnaros2046** [gogf/gf#2882]
### 1. What version of `Go` and system type/arch are you using?

Should we switch to google.golang.org/protobuf?

github.com/golang/protobuf

It has been superseded by the [google.golang.org/protobuf](https://pkg.go.dev/mod/google.golang.org/protobuf) module, which contains an updated and simplified API, support for protobuf reflection, and many other improvements. We recommend that new code use the google.golang.org/protobuf module.

Versions v1.4 and later of github.com/golang/protobuf are implemented in terms of google.golang.org/protobuf. Programs which use both modules must use at least version v1.4 of this one.

**Comment by houseme** [comment]
这个需要 golang 官方处理才行，现在 `github.com/golang/protobuf`和`google.golang.org/protobuf`还有牵扯，等等官方处理吧

**Comment by apple1563** [comment]
> 这个需要 golang 官方处理才行，现在 `github.com/golang/protobuf`和`google.golang.org/protobuf`还有牵扯，等等官方处理吧

撸管
