### ISSUE TITLE
[Feature] Hope gf CLI supports using `go install` to installed

### ISSUE THREAD

**Issue by shuqingzai** [gogf/gf#2888]
目前安装 `gf CLI` 工具只能通过请求 github release 的方式安装，如果对于外网不友好的网络，这根本很难下载，没法使用 `go proxy` 的好处，我尝试使用 `go install` 的方式安装，但因为 `go.mod` 有替换依赖无法进行安装

参考：https://github.com/gogf/gf/blob/cf299273c499aafb5d19829809dfb6b8ef280c12/cmd/gf/go.mod#L62

```bash
#╰─○ go install github.com/gogf/gf/cmd/gf/v2@latest
go: github.com/gogf/gf/cmd/gf/v2@latest (in github.com/gogf/gf/cmd/gf/v2@v2.0.0-20230818015725-cf299273c499):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

如果可以直接 `go install` 进行安装命令行工具，那对于国内用户可真太有好了。。。

**Comment by gqcn** [comment]
@shuqingzai Let me have two thinks.

**Comment by shuqingzai** [comment]
> @shuqingzai Let me have two thinks.

啥？？

**Comment by gqcn** [comment]
> > @shuqingzai Let me have two thinks.
> 
> @gqcn 啥？？

让我想两下。

**Comment by shuqingzai** [comment]
> > > @shuqingzai Let me have two thinks.
> > 
> > 
> > @gqcn 啥？？
> 
> 让我想两下。
@gqcn 
我以为你有新的想法。。。。

如果是本地开发的问题，建议使用 [go workspaces](https://go.dev/doc/tutorial/workspaces) 的模式，更佳友好，开发更佳舒服，至少我目前是这么认为的

因为 gf 已经更新支持 1.18 ，开发模式也可以趁着这节点更新

**Comment by hailaz** [comment]
https://github.com/gogf/gf/pull/2619
之前有过提案

**Comment by gqcn** [comment]
> > > > @shuqingzai Let me have two thinks.
> > > 
> > > 
> > > @gqcn 啥？？
> > 
> > 
> > 让我想两下。
> > @gqcn
> > 我以为你有新的想法。。。。
> 
> 如果是本地开发的问题，建议使用 [go workspaces](https://go.dev/doc/tutorial/workspaces) 的模式，更加友好，开发更加舒服，至少我目前是这么认为的
> 
> 因为 gf 已经更新支持 1.18 ，开发模式也可以趁着这节点更新

好的，我抽空研究一下呢，如果你有好的想法也可以直接提pr哈。

**Comment by hailaz** [comment]
已经支持
```shell
go install github.com/gogf/gf/cmd/gf/v2@latest
go install github.com/gogf/gf/cmd/gf/v2@v2.5.5
```
