### ISSUE TITLE
希望留有接口可以更换模板引擎

### ISSUE THREAD

**Issue by xuzhibin** [gogf/gf#289]
gf的模板用的不是很习惯，可能是写习惯了php的关系，我看到有个pongo2模板引擎比较对口味，希望留有接口可以更换模板引擎。

**Comment by johngcn** [comment]
@xuzhibin 这块优先级不高。

**Comment by gqcn** [comment]
@xuzhibin 未来可以将模板引擎改进为接口化设计。
