### ISSUE TITLE
No scheme can set timeout configuration

### ISSUE THREAD

**Issue by linliyuan** [gogf/gf#2894]
### 1. What version of `Go` and system type/arch are you using?

go 1.19

### 2. What version of `GoFrame` are you using?

v2.2.2

### 3. Can this issue be re-produced with the latest release?
yes

### 4. What did you do?

web服务设置了如下配置，但是超时没有生效，想问一下大家有没有对应的方案，可以设置超时限制呢？目前是否gf已经废弃了超时限制，如果流量比较大，业务没有超时控制不会导致服务压力不可控吗？
server:
address: ":8100"
openapiPath: "/api.json"
swaggerPath: "/api/swagger"
readTimeout: "5s"

### 5. What did you expect to see?
没有方案可以设置超时配置

### 6. What did you see instead?
有方案可以支持超时控制

**Comment by linliyuan** [comment]
It seems that GF doesn't have any server-side timeout control. If a large number of long-time running requests are triggered, it can easily lead to a DDos attack. Moreover, even if the client has disconnected the request, the server will still complete the execution, which makes it even easier for the server to be attacked by DDos. How do you view this issue?

**Comment by gqcn** [comment]
@linliyuan 似乎之前确实可能存在这样的问题，请使用最新的框架版本，如果问题依旧请新建`issue`。
