### ISSUE TITLE
[Question] Does gjson not implement the scan assignment interface of sql?

### ISSUE THREAD

**Issue by shuqingzai** [gogf/gf#2895]
我在阅读 gjson 源码时，发现并没有实现 database/sql 相关扫描赋值接口，导致我在设置值是，报错，是否可以实现这些常用的接口呢？

### 1. What version of `Go` and system type/arch are you using?

```bash
#-> % go version
go version go1.21.0 darwin/amd64
```

### 2. What version of `GoFrame` are you using?

```bash
#-> % gf version
GoFrame CLI Tool v2.5.2, https://goframe.org
GoFrame Version: v2.5.2 in current go.mod
CLI Installed At: /Users/shuqingzai/Code/go/bin/gf
CLI Built Detail:
  Go Version:  go1.20.6
  GF Version:  v2.5.2
  Git Commit:  2023-08-18 09:57:25 cf299273c499aafb5d19829809dfb6b8ef280c12
  Build Time:  2023-08-18 16:23:18
```

### 3. Can this issue be re-produced with the latest release?

是的

**Comment by gqcn** [comment]
@shuqingzai 这个建议好，欢迎一起来共建吧。

**Comment by chen-mou** [comment]
这个似乎没办法实现因为,gjson这个结构体已经存在名字叫Scan的方法但是参数与Scanner接口中的Scan不同，但是golang并不支持方法的重写,所以想要实现相关功能可以自己声明一个结构体并嵌入gjson来实现相关功能

**Comment by shuqingzai** [comment]
> 这个似乎没办法实现因为,gjson这个结构体已经存在名字叫Scan的方法但是参数与Scanner接口中的Scan不同，但是golang并不支持方法的重写,所以想要实现相关功能可以自己声明一个结构体并嵌入gjson来实现相关功能

@chen-mou 目前我们的做法是这样，但是会有问题



```go

```
