### ISSUE TITLE
cannot load github.com/gogf/gf/container/gset: cannot find module providing package github.com/gogf/gf/container/gset

### ISSUE THREAD

**Issue by steedyu** [gogf/gf#290]
目前再使用这个包的时候，在go mod 模式下，1.8.3 版本，下拉后，在gomod 的包管理目录中，查看路径仍有g这个文件夹导致无法，go build 是否是您这里需要 进行一个路径修改？

**Comment by johngcn** [comment]
@steedyu 如果完整开启go module包管理是不会存在这个问题。

**Comment by steedyu** [comment]
我这里就是开启了go mode包管理，然后看了下下载下来的gomod包的目录结构，1.8.3都是带有/f/这个层次的，所以出现不饿继续编译的问题。

**Comment by johngcn** [comment]
@steedyu 请更新到最新版本再试试。
