### ISSUE TITLE
goframe swagger generate not necessary summary info

### ISSUE THREAD

**Issue by webignorant** [gogf/gf#2911]
### 1. What version of `Go` and system type/arch are you using?
go version go1.20.4 windows/amd64

### 2. What version of `GoFrame` are you using?
v2.5.1

### 3. Can this issue be re-produced with the latest release?
yes

### 4. What did you do?
if same route has multiple method, then swagger.json will generate incorrect structure.

lool this picture
<img width="298" alt="5acfea48c54c7f47f5bba6e9fcc7355" src="https://github.com/gogf/gf/assets/4382159/32c3c22c-03bb-4965-a957-df1b005f6429">

### 5. What did you expect to see?
one route, the children node only has http method.
you sure compared apifox swagger.json

look this picture
<img width="261" alt="5261e65e3afe287784703b9c5a778cd" src="https://github.com/gogf/gf/assets/4382159/443b57af-d0e4-4d5f-be40-660fc802a38f">

### 6. What did you see instead?
so use [swagger-typescript-api](https://github.com/acacode/swagger-typescript-api) tool，generated api module use Fetch Api or Axios to make requests.

if use goframe swagger.json, has following error occurred.
<img width="406" alt="f948c92e1819fc461fe36195faf2526" src="https://github.com/gogf/gf/assets/4382159/f0efa144-7506-422b-8204-d71639c24f99">

beause the summary node is an illegal node
![image](https://github.com/gogf/gf/assets/4382159/784b6247-c084-4c7b-8e6d-e1d7e6dc235f)

so use swagger-typescript-api, result is not expected
<img width="339" alt="167daa54c5775db7708ecf16d43d516" src="https://github.com/gogf/gf/assets/4382159/f244f650-97c1-4fe0-ad77-4af08f5e14e4">

**Comment by gqcn** [comment]
@webignorant @cjhyy It was fixed in https://github.com/gogf/gf/commit/47915816b58b0ff3ba5c986ca430d574140f7542
