### ISSUE TITLE
When use  the Where condition and The value with Counter other field in ORM Update

### ISSUE THREAD

**Issue by qq413434162** [gogf/gf#2912]
### 1. What version of `Go` and system type/arch are you using?
go version go1.20.3 darwin/amd64

### 2. What version of `GoFrame` are you using?
GoFrame CLI Tool v2.5.1, https://goframe.org/
GoFrame Version: v2.5.2 in current go.mod
CLI Installed At: /usr/local/bin/gf
CLI Built Detail:
Go Version: go1.20.4
GF Version: v2.5.1
Git Commit: 2023-07-26 21:27:58 https://github.com/gogf/gf/commit/e0e00434cc87d6edf64fc3df40ce7d3f40758794
Build Time: 2023-07-26 21:32:56

### 3. Can this issue be re-produced with the latest release?
Yes

### 4. What did you do?
When use  the Where condition and The value with Counter other field in ORM Update

In official example
https://goframe.org/pages/viewpage.action?pageId=1114238
```go
updateData := g.Map{
	"views": &gdb.Counter{ 
        Field: "clicks", 
        Value: 1,
    },
}
// UPDATE `article` SET `views`=`clicks`+1 WHERE `id`=1
result, err := db.Update("article", updateData, "id", 1)
```

In my example
```go
var (
			columns = dao.Order.Columns()
			ctx     = context.TODO()
		)
		data := g.Map{
			columns.AfterSurplus: &gdb.Counter{
				Field: columns.Amount,
				Value: 0,
			},
		}
		affect, err := dao.Order.
			Ctx(ctx).
			Unscoped().
			Data(data).
			Where(columns.OrderSn, "1242308294272199").
			UpdateAndGetAffected()

		convey.So(err, convey.ShouldBeNil)
		convey.So(affect, convey.ShouldBeGreaterThan, 0)
```

Stack INFO: 

Actual:   'data cannot be empty'

### 5. What did you expect to see?
```shell
UPDATE `order` SET `after_surplus`=amount+0 WHERE `order_sn`='1242308294272199'
```

### 6. What did you see instead?
```go
columns.AfterSurplus: gdb.Raw(columns.Amount + "+" + strconv.Itoa(0)),

//columns.AfterSurplus: &gdb.Counter{
//	Field: columns.Amount,
//	Value: 0,
//},
```

**Comment by gqcn** [comment]
@qq413434162 That is the orm checks the updating increment value `0` is meaningless, it so ignores the updates data. You can change the data as follows:
```go
data := g.Map{
    columns.AfterSurplus: &gdb.Counter{
        Field: columns.Amount,
        Value: 1,
    },
}
```
