### ISSUE TITLE
文档的BUG

### ISSUE THREAD

**Issue by LunacyZeus** [gogf/gf#292]
很多文档里面的超链接失效了.....
比如这个gfile的
https://goframe.org/os/gfile/index
链接到
https://godoc.org/github.com/gogf/gf/g/os/gfile

作者缺整理文档的人嘛~~~

**Comment by johngcn** [comment]
@LunacyZeus 现在框架的`master`分支已经是开发中的`v2.0`版本，文档还没有更新。等待`v2.0`发布之前会统一更新文档。

**Comment by johngcn** [comment]
@LunacyZeus 连接我修正了
