### ISSUE TITLE
"required" verification reports errors when the variable name is inconsistent with the json tag name

### ISSUE THREAD

**Issue by kukayiyi** [gogf/gf#2922]
CLI Built Detail:
  Go Version:  go1.20.4
  GF Version:  v2.5.1
  Git Commit:  2023-07-26 21:27:58 e0e00434cc87d6edf64fc3df40ce7d3f40758794
  Build Time:  2023-07-26 21:32:56

The business request fields are as follows:
```
Label  []int `json:"person_labels" dc:"标签" v:"required"`
```
When the json label and variable name are different like this, the "person_labels" in the request will be invalid and a missing field will be prompted. At this time, if the required verification is removed, the controller can receive the value normally. After testing, using "label" can pass the verification. Guess there may be similar problems with other validations

**Comment by wlynxg** [comment]
You need to achieve the effect you need by adding a validation alias, like this:
```go
Label  []int `json:"person_labels" dc:"标签" v:"person_labels@required"`
```
Please refer to the official documentation: [url](https://goframe.org/pages/viewpage.action?pageId=7302150)

**Comment by wlynxg** [comment]
> CLI Built Detail: Go Version: go1.20.4 GF Version: v2.5.1 Git Commit: 2023-07-26 21:27:58 [e0e0043](https://github.com/gogf/gf/commit/e0e00434cc87d6edf64fc3df40ce7d3f40758794) Build Time: 2023-07-26 21:32:56
> 
> The business request fields are as follows:
> 
> ```
> Label  []int `json:"person_labels" dc:"标签" v:"required"`
> ```
> 
> When the json label and variable name are different like this, the "person_labels" in the request will be invalid and a missing field will be prompted. At this time, if the required verification is removed, the controller can receive the value normally. After testing, using "label" can pass the verification. Guess there may be similar problems with other validations

You need to achieve the effect you need by adding a validation alias, like this:
```go
Label  []int `json:"person_labels" dc:"标签" v:"person_labels@required"`
```
Please refer to the official documentation: [url](https://goframe.org/pages/viewpage.action?pageId=7302150)

**Comment by wlynxg** [comment]
@gqcn I feel like we can add the ability to automatically identify names within generic tags to pass validation.What do you think?

**Comment by gqcn** [comment]
> CLI Built Detail: Go Version: go1.20.4 GF Version: v2.5.1 Git Commit: 2023-07-26 21:27:58 [e0e0043](https://github.com/gogf/gf/commit/e0e00434cc87d6edf64fc3df40ce7d3f40758794) Build Time: 2023-07-26 21:32:56
> 
> The business request fields are as follows:
> 
> ```
> Label  []int `json:"person_labels" dc:"标签" v:"required"`
> ```
> 
> When the json label and variable name are different like this, the "person_labels" in the request will be invalid and a missing field will be prompted. At this time, if the required verification is removed, the controller can receive the value normally. After testing, using "label" can pass the verification. Guess there may be similar problems with other validations

Hi, please provide a short, simple codes that can reproduce this issue.

**Comment by gqcn** [comment]
> @gqcn I feel like we can add the ability to automatically identify names within generic tags to pass validation.What do you think?

I'll check this later when codes provided.
