### ISSUE TITLE
改进gvalid校验模块，允许开发者增加自定义的校验规则

### ISSUE THREAD

**Issue by gqcn** [gogf/gf#293]
需求背景：虽然`gvalid`提供了非常丰富的校验规则，并且也支持正则校验，但是并不支持开发者添加自定义的校验规则，针对于各种各样的业务数据校验，也许允许开发者自定义校验规则是一个很不错的特性。

实现难度：3星半

实现建议：先了解现在的`gvalid`源代码再动手，其实比较简单。

**Comment by arieslee** [comment]
觉得这个实现方法就挺不错的[https://github.com/gookit/validate](url)
