### ISSUE TITLE
"gf gen dao "got fatal error

### ISSUE THREAD

**Issue by dawnFromDark** [gogf/gf#2934]
i read the doc from your official website,and find demo project :https://github.com/gogf/gf-demo-user
and i follow the demo cmd(gf gen dao) to generate dao code,however,the the code generated by gf was error,the error code is following:

**model/do/user.go**
```go
// =================================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure of table user for DAO operations like Where/Data.
type User struct {
	g.Meta   `orm:"table:user, do:true"`
	Id                   // User ID interface{} // User Passport interface{} // User Password interface{} // User Nickname
	CreateAt *gtime.Time // Created Time
	UpdateAt *gtime.Time // Updated Time
}
```
the id does not have a type ,right?

**model/entity/user.go**
```go
// =================================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Id       `json:"id"       ` // User ID
	Passport `json:"passport" ` // User Passport
	Password `json:"password" ` // User Password
	Nickname `json:"nickname" ` // User Nickname
	CreateAt *gtime.Time        `json:"createAt" ` // Created Time
	UpdateAt *gtime.Time        `json:"updateAt" ` // Updated Time
}
```
Obviously, both codes have errors! may you guys tell me how solve this?

**Comment by dawnFromDark** [comment]
> @dawnFromDark I cannot reproduce the issue you mentioned using mysql. What was your db type?

my db is mysql,and the sql file is this `https://github.com/gogf/gf-demo-user/tree/master/manifest/sql` , it was contained in the demo project.

**Comment by dawnFromDark** [comment]
> @dawnFromDark I cannot reproduce the issue you mentioned using mysql. What was your db type?

什么无法重现，你把这个代码`https://github.com/gogf/gf-demo-user `clone下来 ，对应的配置弄好数据库，执行gf gen dao,生成的代码能够执行吗？你们试试？这个很好复现的吧？？？？？？

**Comment by dawnFromDark** [comment]
gf gen dao生成的数据库的代码就是不能执行，就是不全，目测你们执行的生成的模板有问题，真的啊，你们看看吧，这个是官方的例子呢？不难复现 吧？？？？？？？

**Comment by dawnFromDark** [comment]
gf gen dao生成的数据库的代码就是不能执行，就是不全，目测你们执行的生成的模板有问题，真的啊，你们看看吧，这个是官方的例子呢？不难复现 吧？？？？？？？

**Comment by antmanjay** [comment]
I also reproduce such a problem. How did you solve it
我也一样再现这样的问题，请问你是如何解决的

**Comment by dawnFromDark** [comment]
> I also reproduce such a problem. How did you solve it 我也一样再现这样的问题，请问你是如何解决的


官方的人还不承认这个bug，2.5.2版本有这个问题，把gf版本回退的2.2.5就可以解决这个问题。亲测

**Comment by xintao222** [comment]
我的也存在这个问题，不知道大家是怎么解决的？

**Comment by xintao222** [comment]
<img width="566" alt="image" src="https://github.com/gogf/gf/assets/5466168/a1299294-e6b2-481f-baaf-77cae559d19d">
