### ISSUE TITLE
gdb生成的sql语句和绑定参数分开打印了，看sql和复制到数据库运行相当不便

### ISSUE THREAD

**Issue by xuzhibin** [gogf/gf#295]
能否直接拼成可执行sql语句，或者让用户选择用哪一种格式

**Comment by xuzhibin** [comment]
2019-08-24 21:40:42.874 DB ERROR: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'order(`serialnumber`,`playerid`,`remarks`,`created_at`,`pay_at`,`openid`,`presen' at line 1
DB QUERY: INSERT INTO order(`serialnumber`,`playerid`,`remarks`,`created_at`,`pay_at`,`openid`,`present`,`oldamount`,`productprice`,`totalprice`,`payaccount`,`updated_at`,`transactionid`,`id`,`productid`,`status`,`buyerid`,`paytype`,`paymoney`,`moneyunit`,`producttype`,`unionid`,`quantity`) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) 
DB PARAM: [65602335148 100559  1566654042 0  0 93 3 15  1566654042  0 0 0 0  0  diamond  5]
g.DB().Table("order").Safe(true).Data(model).Insert()
对于字段太多的表，不知道生成的sql语句为啥报错了，没有完整的sql语句，无法调试

**Comment by xuzhibin** [comment]
![E2362F0FF7656D0504DAC4F45241A741](https://user-images.githubusercontent.com/1763232/63646054-386bcf00-c73e-11e9-8437-44b2b01463da.jpg)

**Comment by johngcn** [comment]
@xuzhibin 已改进，将会在`v2.0`版本中发布
