### ISSUE TITLE
How to customize the OpenAPI document type?

### ISSUE THREAD

**Issue by shuqingzai** [gogf/gf#2952]
如题，我参考文档：[接口文档-OpenAPIv3](https://goframe.org/pages/viewpage.action?pageId=47703679) 定义 `type` 标签似乎无效？

```go
// ListSearchInput 列表搜索通用结构体
type ListSearchInput struct {
	// Keyword 关键字搜索
	Keyword string `json:"keyword" dc:"关键字搜索" v:"max:100"`
	// 排序方式
	SortBy listsortby.SortBy `json:"sortBy" dc:"排序方式" d:"asc" type:"string"`
}
```

上诉中 `SortBy` 字段是一个结构体，我定义为 `string` 无效，在文档中会显示 `xxxxx.SortBy` ，里面包含一个 `Error` ，我也不知道这个是干嘛的，是否可以手动强制定制 OpenAPI 字段类型？？，我似乎还发现在字段上设置类似：`format:"date-time"` 之类的标签也是无法使用的

**使用 `gf gen dao` 可以配置类型映射( `typeMapping` )，主要用于配置第三方包的类型映射，希望 OpenAPI 文档也可以配置类似的操作**

### 1. What version of `Go` and system type/arch are you using?

```bash
#╰─○ go version
go version go1.21.1 darwin/arm64
```

### 2. What version of `GoFrame` are you using?

```bash
# ╰─⠠⠵ gf version
GoFrame CLI Tool v2.5.2, https://goframe.org
GoFrame Version: v2.5.2 in current go.mod
CLI Installed At: /Code/Go/bin/gf
CLI Built Detail:
  Go Version:  go1.20.6
  GF Version:  v2.5.2
  Git Commit:  2023-08-18 09:57:25 cf299273c499aafb5d19829809dfb6b8ef280c12
  Build Time:  2023-08-18 16:23:18
```

**Comment by gqcn** [comment]
@shuqingzai 参数中可以设置的`OpenAPI`属性请参考`OpenAPIv3`的规范（文档中有链接），也可以参考`goai`中的数据结构定义，不可以随便定义新属性标签的哈。此外如果想定义自定义的属性标签，`OpenAPIv3`中也支持，就是使用扩展标签，具体请查看文档。

**Comment by shuqingzai** [comment]
> @shuqingzai 参数中可以设置的`OpenAPI`属性请参考`OpenAPIv3`的规范（文档中有链接），也可以参考`goai`中的数据结构定义，不可以随便定义新属性标签的哈。此外如果想定义自定义的属性标签，`OpenAPIv3`中也支持，就是使用扩展标签，具体请查看文档。

@gqcn 没有自定义标签，我只是想映射不同的类型，而且文档也有标注可以使用 `type` 标签定义文档字段类型
![image](https://github.com/gogf/gf/assets/44406033/e6db2b7b-30e1-46b0-a21f-3726260cac78)

@gqcn 
还有一个不理解的是：为啥每次(我提问多次不同的问题都是这样)提问的 issue 没有解决就关闭？这不是显示社区效率有多好，有多快，只会让使用者感觉很困惑，不知所措，甚至思考是否需要重开一个 issue？？，如果该 issue 三天或一周不活跃完全可以设置 CI 自动关闭，如果问题得到解决那样主动关闭没有问题

**Comment by Bleoo** [comment]
我也遇到了

CreatedAt *api.Time `json:"created_at" type:"integer"`

使用 type 标签，openapi 标准类型 integer，
<img width="781" alt="image" src="https://github.com/gogf/gf/assets/11569795/dcd891e0-e9be-47ff-8749-132392e965fb">

还是不能按 integer 正常显示
<img width="413" alt="image" src="https://github.com/gogf/gf/assets/11569795/fa669829-2b6d-467d-a574-acd03f7ddcb7">

**Comment by Bleoo** [comment]
我看了源码中并没有对 ”type“ 标签进行解析，感觉这是个 bug ? @shuqingzai @gqcn
