### ISSUE TITLE
gf The entity generated by gen dao lacks data type

### ISSUE THREAD

**Issue by hanweiweb** [gogf/gf#2954]
![image](https://github.com/gogf/gf/assets/93665931/a06637f3-007a-4a89-9121-3f2a166cb717)

**Comment by hamster1963** [comment]
同样遇到问题

**Comment by ilaziness** [comment]
The new version does not solve the problem. The problem remains.

**Comment by antmanjay** [comment]
一样遇到。为什么现在还没有解决呢

**Comment by hanweiweb** [comment]
> 建议按照官方要求的模板提问题，至少把你本地环境用到的go和gf版本列出来

出问题的是昨天发布的2.5.3版本, 今晚新发布2.5.4的好像已经解决了

**Comment by gqcn** [comment]
@hanweiweb @hamster1963 @antmanjay @windvalley 不好意思各位，上次发布的`v2.5.3`存在`bug`导致`gen dao`命令生成的`go`源码文件丢失类型，目前已经在昨天发布的`v2.5.4`中修复。并且也增加了对工具命令的单测，后续会不断完善单测用例保证稳定性。感兴趣的朋友也可以一起参与建设。
