### ISSUE TITLE
After upgraded to v2.5.2, defined as "*", but it should be named with "Res" suffix like "XxxRes"

### ISSUE THREAD

**Issue by mason51** [gogf/gf#2955]
### 1. What version of `Go` and system type/arch are you using?
1.20.4

### 2. What version of `GoFrame` are you using?
v2.5.2

### 3. Can this issue be re-produced with the latest release?
Yes

### 4. What did you do?
```
type MenuListReq struct {
	g.Meta `path:"/user/menu-list" method:"get" summary:"菜单列表" tags:"用户"`
}
type MenuListRes struct {
	Title    string         `json:"title"  dc:"菜单名称"`
	Path     string         `json:"path"  dc:"菜单地址"`
	Children []MenuListData `json:"children"`
}

func (c *cUser) MenuList(ctx context.Context, req *user.MenuListReq) (res *[]user.MenuListRes, err error) {
	return
}
```

### 6. What did you see instead?
在 v2.5.1 的时候, res *[]user.MenuListRes 是可以用的, 但升级到 v2.5.2, 就会报错. 
invalid struct naming for response: defined as "*", but it should be named with "Res" suffix like "XxxRes"

同样, 当前最新版的 v2.5.3 也会报错.

如果, 我把 res *[]user.MenuListRes 改成 res *user.MenuListRes, 也就是不用数组, 就不报错.

所以, 请问这是 gf 的 bug? 还是后续不能再用数组?

**Comment by spenice** [comment]
目测是支持泛型了，就不能用 [] 了
控制器只允许两种  "func(*ghttp.Request)" or "func(context.Context, *BizReq)(*BizRes, error)" is required
源码上  变量 是通过 反射获取 in 的参数个数 和参数类型来判断的
             返回类型 是字符串判断你的请求是否为 “xxxReq” 和 “xxxRes”
             支持泛型后，会将泛型部分移除掉，即保留中括号左边的字符串，导致获取不到你的真正的返回类型
你可以试下，res *[]user.MenuListRes  会抛出 defined as "*"
                      res []*user.MenuListRes  会抛出 defined as ""

下面是部分源码
```
// trimGeneric removes type definitions string from response type name if generic
func trimGeneric(structName string) string {
	var (
		leftBraceIndex  = strings.LastIndex(structName, "[")
		rightBraceIndex = strings.LastIndex(structName, "]")
	)
	if leftBraceIndex == -1 && rightBraceIndex == -1 {
		// no generic type usage.
		return structName
	}
	return structName[:leftBraceIndex]
}
```

**Comment by spenice** [comment]
> 目测是支持泛型了，就不能用 [] 了 控制器只允许两种 "func(*ghttp.Request)" or "func(context.Context, *BizReq)(*BizRes, error)" is required 源码上 变量 是通过 反射获取 in 的参数个数 和参数类型来判断的 返回类型 是字符串判断你的请求是否为 “xxxReq” 和 “xxxRes” 支持泛型后，会将泛型部分移除掉，即保留中括号左边的字符串，导致获取不到你的真正的返回类型 你可以试下，res _[]user.MenuListRes 会抛出 defined as "_" res []*user.MenuListRes 会抛出 defined as ""
> 
> 下面是部分源码
> 
> ```
> // trimGeneric removes type definitions string from response type name if generic
> func trimGeneric(structName string) string {
> 	var (
> 		leftBraceIndex  = strings.LastIndex(structName, "[")
> 		rightBraceIndex = strings.LastIndex(structName, "]")
> 	)
> 	if leftBraceIndex == -1 && rightBraceIndex == -1 {
> 		// no generic type usage.
> 		return structName
> 	}
> 	return structName[:leftBraceIndex]
> }
> ```
打漏*了
res *[]user.MenuListRes 会抛出 defined as "*"
res []*user.MenuListRes 会抛出 defined as ""

**Comment by mason51** [comment]
如果不能用[]了, 后续想升级gf最新版本, 好几十个接口要改

**Comment by spenice** [comment]
您好，我已经收到了你的来信

**Comment by spenice** [comment]
> 如果不能用[]了, 后续想升级gf最新版本, 好几十个接口要改

将你的 返回类型 再包装成一个新的类型

你原来的  res []user.MenuListRes  包装成
type UserMenuListRes  []user.MenuListRes
然后将新的   UserMenuListRes    做你的返回值类型


或者你所有的  返回 xxxRes  都使用一个，然后将 responseHandler  跟着修改
下面是一个小demo
![Snipaste_2023-09-12_13-38-50](https://github.com/gogf/gf/assets/40162682/04247cce-2b4e-4510-b491-346e4f99607a)
![image](https://github.com/gogf/gf/assets/40162682/78f0d9eb-3f1a-44ea-80de-c2ed97545214)

**Comment by gqcn** [comment]
> > 如果不能用[]了, 后续想升级gf最新版本, 好几十个接口要改
> 
> 将你的 返回类型 再包装成一个新的类型
> 
> 你原来的 res []user.MenuListRes 包装成 type UserMenuListRes []user.MenuListRes 然后将新的 UserMenuListRes 做你的返回值类型
> 
> 或者你所有的 返回 xxxRes 都使用一个，然后将 responseHandler 跟着修改 下面是一个小demo ![Snipaste_2023-09-12_13-38-50](https://user-images.githubusercontent.com/40162682/267221609-04247cce-2b4e-4510-b491-346e4f99607a.png) ![image](https://user-images.githubusercontent.com/40162682/267221649-78f0d9eb-3f1a-44ea-80de-c2ed97545214.png)

@mason51 对，参考这个来修改吧，其实使用正则来做批量替换也可以实现的。
