### ISSUE TITLE
pgsql does not support versions lower than postgresql10

### ISSUE THREAD

**Issue by arieslee** [gogf/gf#2967]
### 1. What version of `Go` and system type/arch are you using?

go version go1.18.10 windows/amd64

### 2. What version of `GoFrame` are you using?

GoFrame v 2.5.2

### 3. Can this issue be re-produced with the latest release?
My database version for Huawei's opengauss , is based on postgresql9 change the version, create database and data tables after 
Use
`gf gen dao`
Generate files, report errors
```shell
fetching tables failed: SELECT c.relname FROM pg_class c INNER JOIN pg_namespace n ON c.relnamespace = n.oid WHERE n.nspname = 'public' AND c.relkind IN ('r', 'p') AND c.relpartbou
nd IS NULL ORDER BY c.relname: pq: column c.relpartbound does not exist
```
After manually querying the pg_class table, there is indeed no relpartbound field
经群里大佬@黄海亮(HaiLaz)指点 @hailaz
View Document：http://www.postgres.cn/docs/10/catalog-pg-class.html 
postgresql 10 has this field since then

### 4. What did you do?

The gen dao is compatible with lower versions of postgresql9.

I switched to version postgresql16 and `gf gen dao` it's working.

**Comment by hailaz** [comment]
http://www.postgres.cn/docs/10/catalog-pg-class.html
http://www.postgres.cn/docs/9.6/catalog-pg-class.html
