### ISSUE TITLE
gproc如何使用指定用户执行

### ISSUE THREAD

**Issue by zyokia** [gogf/gf#297]
### 1. What version of `Go` and system type/arch are you using?
go version go1.12.9 darwin/amd64

### 2. What version of `GoFrame` are you using?

1.8.3

### 3. Can this issue be reproduced with the latest release?
yes

**Comment by johngcn** [comment]
@zyokia 程序切换用户和系统API有关系，Golang似乎没有提供封装的API，如果是针对特定平台你可以考虑使用`syscall`自行实现。

**Comment by zyokia** [comment]
我使用newprocess创建进程，用test_user用户执行/tmp/test.sh时，报如下错误
err:fork/exec su test_user /tmp/test.sh: no such file or directory
代码如下
p := superProcessManager.manager.NewProcess("su " + user + " " + path, args, environment)
另外，这并不是针对特定平台，能用的
目的就是使用某个帐号执行某个指令

**Comment by johngcn** [comment]
@zyokia 使用特定用户指定特定指令没有办法跨平台，标准库也没有提供类似功能，你只有自行考虑解决办法。
