### ISSUE TITLE
Execute gf gen service without generating files

### ISSUE THREAD

**Issue by pikachu011** [gogf/gf#2972]
<img width="958" alt="image" src="https://github.com/gogf/gf/assets/144210702/aaada643-a33b-467a-b32c-a773d30174c3">
<img width="1037" alt="image" src="https://github.com/gogf/gf/assets/144210702/8e5c60bc-b87c-4552-a524-00f693025d33">

GoFrame CLI Tool v2.5.4, https://goframe.org
GoFrame Version: v2.5.4 in current go.mod
CLI Built Detail:
  Go Version:  go1.20.8
  GF Version:  v2.5.4
  Git Commit:  2023-09-12 22:00:35 5219c5c37ed755ff5f717d6ec07c7a1951453991
  Build Time:  2023-09-12 22:17:31
请问是哪里的问题

**Comment by gqcn** [comment]
@pikachu011 Command `gen service` scans the sub-folders of directory `logic` as biz-modules, and generates go files for these biz-modules.
