### ISSUE TITLE
[Question] How to register the http.Handler of the standard library as a designated route processor? ? ?

### ISSUE THREAD

**Issue by shuqingzai** [gogf/gf#2975]
一般第三方扩展应用包如果支持 WebUI 或者 API 服务时，基本都提供注册 **http.Handler** 的方式接管 http 服务或提供 http 服务，但是由于 gf 似乎没有办法注册 http.Handler 作为指定路由处理器，导致没法集成一些第三方库所提供的 http 服务，希望可以支持，向标准库看齐，目前 gf 提供的注册路由方式都是 gf 自定义的标准，并不是标准库所支持的，不够通用

### 1. What version of `Go` and system type/arch are you using?

```bash
#-> % go version
go version go1.21.1 darwin/amd64
```

### 2. What version of `GoFrame` are you using?

```bash
#-> % gf version
GoFrame CLI Tool v2.5.4, https://goframe.org
GoFrame Version: v2.5.4 in current go.mod
CLI Installed At: /Users/shuqingzai/Code/go/bin/gf
CLI Built Detail:
  Go Version:  go1.20.8
  GF Version:  v2.5.4
  Git Commit:  2023-09-12 22:00:35 5219c5c37ed755ff5f717d6ec07c7a1951453991
  Build Time:  2023-09-12 22:17:31
```

### 3. Can this issue be re-produced with the latest release?

Yes

### 5. What did you expect to see?

允许注册标准库的 **http.Handler** 作为指定路由处理器，向标准库看齐

**Comment by gqcn** [comment]
@shuqingzai You can use `ghttp.WarpF/WrapH` converting `http.HandlerFunc` or `http.Handler` to `ghttp.HandlerFunc`.
