### ISSUE TITLE
invalid struct naming for response: defined as "%s", but it should be named with "Res" suffix like "XxxRes"

### ISSUE THREAD

**Issue by aguang1203** [gogf/gf#2976]
![image](https://github.com/gogf/gf/assets/7029372/324a1437-f4bb-437b-96d8-fdd717dd9032)

**Comment by gqcn** [comment]
@aguang1203 You can define a alias type like:
```go
type QueryAttendRes []ReponseItem
```

**Comment by TENX-S** [comment]
Can you release a patch for this fix? Thanks! @gqcn
