### ISSUE TITLE
建议ORM链式操作加入SetInc和SetDec接口

### ISSUE THREAD

**Issue by macnie** [gogf/gf#299]
ORM链式操作加入SetInc，SetDec，实现字段的自增和自减。

如：g.DB().Table("user").Where("id=?",1).SetInc("money",1)

**Comment by xuzhibin** [comment]
这个需求有需要

**Comment by johngcn** [comment]
@macnie @xuzhibin 可以通过`g.DB().Table("user").Data("id=id+1").Where("id", 1).Update()`实现。

**Comment by gqcn** [comment]
@macnie @xuzhibin 也可以通过`db.Table("user").Update("id=id+1")`
