### ISSUE TITLE
How to modify static resource mapping after binding

### ISSUE THREAD

**Issue by dragon-dan** [gogf/gf#2993]
### 1. What version of `Go` and system type/arch are you using?

go1.21.1 win64

### 2. What version of `GoFrame` are you using?

require github.com/gogf/gf/v2 v2.5.4

### 3. Can this issue be re-produced with the latest release?
yes

### 4. What did you do?++++++++### 6. What did you see instead?

我创建了一个server，设置了一个静态资源映射 /list==>dirA
s.AddStaticPath("/list", dirA)

功能需要在中途停下server，根据用户选择的文件夹把映射为修改为 /list==>dirB
g.Server()得到的是一个单例server，好像找不到修改映射的办法。

s.AddStaticPath("/list", dirA)
s.AddStaticPath("/list", dirB)
尝试发现连续调用AddStaticPath，并不会覆盖之前的映射。

找了一圈没有办法，目前用g.Server(...)获取多例的方式换了个新server绕过去了。

### 5. What did you expect to see?

不用多例，只用单例也能实现修改这个映射

**Comment by gqcn** [comment]
@dragon-dan 你好，在运行时不支持修改静态资源映射，因为会涉及到并发安全的处理问题。建议将涉及到动态变化的静态资源访问控制通过注册路由方法来实现。
