### ISSUE TITLE
多个表生成的插入sql语句出错

### ISSUE THREAD

**Issue by xuzhibin** [gogf/gf#300]
在php操作表正常
<img width="1356" alt="image" src="https://user-images.githubusercontent.com/1763232/63675112-a5549700-c81a-11e9-83e2-e4945b3c98c4.png">

![](https://user-images.githubusercontent.com/1763232/63646054-386bcf00-c73e-11e9-8437-44b2b01463da.jpg)

**Comment by johngcn** [comment]
@xuzhibin 你第一个报错应该是主键为0，检查下是否struct的主键字段是否为可导出字段（首字母大写）。你的第二个报错是因为表名`order`为关键字，该问题已经在新版中已经解决，你可以更新到`v1.8.3`试试，如果不行的话请再等等最新版本。

**Comment by xuzhibin** [comment]
更新版本后，已解决
