### ISSUE TITLE
保存model后，model对应的id并没有赋值

### ISSUE THREAD

**Issue by xuzhibin** [gogf/gf#301]
r,_:=g.DB().Table("player").Data(model).Save()
保存model后，model对应的id并没有赋值，应该如何获取到model的id，建议可以自动给model对应字段赋值

**Comment by johngcn** [comment]
@xuzhibin 请详细描述，并且给定可复现问题的最小代码。

**Comment by xuzhibin** [comment]
目前是这样解决：
r,_:=g.DB().Table("auth").Data(model).Save()
	id,_:=r.LastInsertId()
	if(model.Id==0){
		model.Id=id
	}

**Comment by johngcn** [comment]
@xuzhibin 是的，你传递的`model`参数是输入参数，当然不会被自动修改，你有见过ORM中模型参数既作为输入参数由作为输出参数的设计么？

**Comment by xuzhibin** [comment]
有的，保存实体后，将对应的id赋给实体属性是很正常的操作，也是符合逻辑思维的。用过ORM的有：C# 的EF，php的yii2

**Comment by arden** [comment]
改变输入参数其实是一个很不好的设计。
