### ISSUE TITLE
null should not be returned when the data cannot be queried

### ISSUE THREAD

**Issue by Wen-sijun** [gogf/gf#3012]
### 1. What version of `Go` and system type/arch are you using?

go version go1.20.9 windows/amd64

### 2. What version of `GoFrame` are you using?

v2.5.2

### 3. Can this issue be re-produced with the latest release?
Yes

### 4. What did you do?

``` golang

// List 获取列表数据
func (s *sTransaction) List(ctx context.Context, in *model.TransactionRecordListInput) (out *model.TransactionRecordListOutput, err error) {
	whereData := s.GetWhere(in)
	m := dao.MainTransactionRecord.Ctx(ctx).Where(whereData)
	out = &model.TransactionRecordListOutput{
		CommonPaginationOutput: model.CommonPaginationOutput{
			Page: in.Page,
			Size: in.Size,
		},
	}
	listModel := m.Page(in.Page, in.Size)

	if err := listModel.Scan(&out.List); err != nil {
		return out, err
	}
	if len(out.List) == 0 {
		return out, nil
	}
	out.Total, err = m.Count()
	if err != nil {
		return out, err
	}
	return
}

// 输入
type TransactionRecordListInput struct {
	// ...
}

// 输出
type TransactionRecordListOutput struct {
	List []*TransactionRecordItem
        // 分页相关...
}

type TransactionRecordItem struct {
	// 单条数据info...
}
```

### 5. What did you expect to see?
``` json
{
	"code": 0,
	"message": "",
	"data": {
		"list": [],
		"total": 0,
		"page": 1,
		"size": 10
	}
}
```

### 6. What did you see instead?
``` json
{
	"code": 0,
	"message": "",
	"data": {
		"list": null,
		"total": 0,
		"page": 1,
		"size": 10
	}
}
```

控制器层和logic都是用的指针receiver，当查询不到数据时，会响应null给前端，目前我的解决方式是在Scan(&out.List)之前对List属性进行初始化，避免其在查询不到数据时为空指针。期望可以像grom的find那样，会先调用NewScope方法来创建一个新的Scope，然后在这个新的Scope上执行查询。在创建新的Scope时，如果传入的参数是一个指向切片的指针，GORM会通过反射来创建一个新的切片，并将这个新的切片的地址赋值给传入的指针。所以，即使查询结果为空，传入的指针也会被赋值为一个空的切片。从而避免返回null，null对前端渲染数据很不友好

**Comment by shuqingzai** [comment]
这应该与框架无关，应该是 `json.Marshal` 的问题，如果切片未初始化(**值为: `nil`**)，在进行 `json.Marshal` 时，就会设置为 null

**Comment by Wen-sijun** [comment]
> 这应该与框架无关，应该是 `json.Marshal` 的问题，如果切片未初始化(**值为: `nil`**)，在进行 `json.Marshal` 时，就会设置为 null
> 
> 你可以显式设置为空切片字面量

原因不重要，而且你提供的方案我已经在备注里说明了，我期望的是可以类似于gorm一样，对这种空指针情况做优化，而不是显示声明

**Comment by shuqingzai** [comment]
> > 这应该与框架无关，应该是 `json.Marshal` 的问题，如果切片未初始化(**值为: `nil`**)，在进行 `json.Marshal` 时，就会设置为 null
> > 你可以显式设置为空切片字面量
> 
> 原因不重要，而且你提供的方案我已经在备注里说明了，我期望的是可以类似于gorm一样，对这种空指针情况做优化，而不是显示声明

1. 你所说的空指针是指？slice 的判断方式都是使用 `len()` 而不是 `s != nil` ，即使使用 `for rang` 遍历，如果 slice 长度为 0 或 为 nil ，就不会进入循环体，所以 slice 不存在你说的空指针的问题
2.  你这只是针对 数据库，如果是其他来源的数据(如查询 `redis` 等）需要响应前端呢？如果你需要返回 `[]` ，一样需要显式声明空slice字面量值，根本原因(`json.Marshal` 的问题)很重要好吗？最佳的实践还是显式声明

**Comment by shuqingzai** [comment]
> > > > 这应该与框架无关，应该是 `json.Marshal` 的问题，如果切片未初始化(**值为: `nil`**)，在进行 `json.Marshal` 时，就会设置为 null
> > > > 你可以显式设置为空切片字面量
> > > 
> > > 
> > > 原因不重要，而且你提供的方案我已经在备注里说明了，我期望的是可以类似于gorm一样，对这种空指针情况做优化，而不是显示声明
> > 
> > 
> > 
> > 1. 你所说的空指针是指？slice 的判断方式都是使用 `len()` 而不是 `s != nil` ，即使使用 `for rang` 遍历，如果 slice 长度为 0 或 为 nil ，就不会进入循环体，所以 slice 不存在你说的空指针的问题
> > 2. 你这只是针对 数据库，如果是其他来源的数据(如查询 `redis` 等）需要响应前端呢？如果你需要返回 `[]` ，一样需要显式声明空slice字面量值，根本原因(`json.Marshal` 的问题)很重要好吗？最佳的实践还是显式声明
> 
> 麻烦再看下我Issues里的备注，我说原因不重要的意思是，我知道原因，而且也给出了显式声明的解决方案，但是我想要的是类似gorm那种，在框架层面上对空指针赋值时的优化处理，而不是每次手动去显式声明，懂？ 你说的切片知识我都明白，但是不知道你拿切片举例的点在哪，赋值都是Scan给到指针receiver

你可能需要看看 https://goframe.org/pages/viewpage.action?pageId=47699230#ORM%E7%BB%93%E6%9E%9C%E5%A4%84%E7%90%86%E4%B8%BA%E7%A9%BA%E5%88%A4%E6%96%AD-%E5%85%AD%E3%80%81Struct%E6%95%B0%E7%BB%84

1. 我没有用 gf ORM，用的也是 GORM 
2. 我能理解你的意思，也说明了显式声明的问题
3. 至于你说的举例，是因为你说的空指针问题

**Comment by Wen-sijun** [comment]
> > > > > 这应该与框架无关，应该是 `json.Marshal` 的问题，如果切片未初始化(**值为: `nil`**)，在进行 `json.Marshal` 时，就会设置为 null
> > > > > 你可以显式设置为空切片字面量
> > > > 
> > > > 
> > > > 原因不重要，而且你提供的方案我已经在备注里说明了，我期望的是可以类似于gorm一样，对这种空指针情况做优化，而不是显示声明
> > > 
> > > 
> > > 
> > > 1. 你所说的空指针是指？slice 的判断方式都是使用 `len()` 而不是 `s != nil` ，即使使用 `for rang` 遍历，如果 slice 长度为 0 或 为 nil ，就不会进入循环体，所以 slice 不存在你说的空指针的问题
> > > 2. 你这只是针对 数据库，如果是其他来源的数据(如查询 `redis` 等）需要响应前端呢？如果你需要返回 `[]` ，一样需要显式声明空slice字面量值，根本原因(`json.Marshal` 的问题)很重要好吗？最佳的实践还是显式声明
> > 
> > 
> > 麻烦再看下我Issues里的备注，我说原因不重要的意思是，我知道原因，而且也给出了显式声明的解决方案，但是我想要的是类似gorm那种，在框架层面上对空指针赋值时的优化处理，而不是每次手动去显式声明，懂？ 你说的切片知识我都明白，但是不知道你拿切片举例的点在哪，赋值都是Scan给到指针receiver
> 
> 你可能需要看看 https://goframe.org/pages/viewpage.action?pageId=47699230#ORM%E7%BB%93%E6%9E%9C%E5%A4%84%E7%90%86%E4%B8%BA%E7%A9%BA%E5%88%A4%E6%96%AD-%E5%85%AD%E3%80%81Struct%E6%95%B0%E7%BB%84
> 
> 1. 我没有用 gf 的 ORM，用的也是 GORM
> 2. 我能理解你的意思，也说明了显式声明的问题，数据并不是只是来自于数据库，只是给个方案而已，别激动
> 3. 至于你说的举例，是因为你说的空指针问题

链接中的内容我之前就注意到了，但是实际使用的时候，如果查询数据为空，并没有文档提到的"ORM内部会根据查询结果智能地做自动初始化"，可能是因为没有查到数据的原因吧，暂时没去看源码。也就是说，实际在查不到数据的情况下，并不会对Scan的变量做初始化

我开始提到的空指针，也正如你链接中提到的示例一样，Scan的时候是**struct，所以我上个回答会说"不理解你说的切片举例"，我的理解是跟切片没关系，Scan是个指针，可能在orm能查到值的时候，它确实能在orm内部对空指针进行初始化赋值，但是当orm查询不到数据时(数据库中不存在符合条件的数据)，orm就不会对指针进行初始化了。以上是我的猜测，稍后准备去看下Scan的源码

**Comment by gqcn** [comment]
@Wen-sijun @shuqingzai 大家好，为了回答这个问题，我特意新增了这个章节 https://goframe.org/pages/viewpage.action?pageId=114036395
