### ISSUE TITLE
请问有容器的开发计划吗？

### ISSUE THREAD

**Issue by xuzhibin** [gogf/gf#303]
类似这个：
https://github.com/qit-team/snow/wiki/container

**Comment by johngcn** [comment]
@xuzhibin 没看出来有什么优点啊，`gf`框架里面有`gins`单例管理器以及`gmap`容器，看起来比它更强大啊。

**Comment by johngcn** [comment]
@xuzhibin 超过1个月没有活跃，因此关闭该issue，若有问题请reopen。
