### ISSUE TITLE
How to use the ToSQL function?

### ISSUE THREAD

**Issue by UrsaMajor-Alioth** [gogf/gf#3056]
### 1. What version of `Go` and system type/arch are you using?

 go 1.21.0, windows/amd64

### 2. What version of `GoFrame` are you using?

 v2.5.4

### 5. What did you expect to see?
Hello, I would like to know how to use the ToSQL function in the DAO layer.

**Comment by oldme-git** [comment]
```
sql, err := gdb.ToSQL(ctx, func(ctx context.Context) error {
    _, err := dao.Link.Ctx(ctx).All()
    return err
})
```

**Comment by arieslee** [comment]
可以这样用
`sql, _ := gdb.ToSQL(gctx.New(), func(ctx context.Context) error {
		g.DB().Ctx(ctx).Model(dao.Admin.Table()).Where("id=1").One()
		return nil
	})
	g.Dump(sql)`

**Comment by UrsaMajor-Alioth** [comment]
> ```
> sql, err := gdb.ToSQL(ctx, func(ctx context.Context) error {
>     _, err := dao.Link.Ctx(ctx).All()
>     return err
> })
> ```

Thank you for your reply !

**Comment by UrsaMajor-Alioth** [comment]
> 可以这样用
> 
> ```
> sql, _ := gdb.ToSQL(gctx.New(), func(ctx context.Context) error {
> 		g.DB().Ctx(ctx).Model(dao.Admin.Table()).Where("id=1").One()
> 		return nil
> 	})
> 	g.Dump(sql)
> ```

Thank you, it's the result I want !
