### ISSUE TITLE
(超级月经贴) Should use AST code refactoring some `gf gen` commands.

### ISSUE THREAD

**Issue by oldme-git** [gogf/gf#3067]
Now, gf-cli uses regex to get file content, but this is not precision.
PR #3066 has finished some.

**Comment by oldme-git** [comment]
@gqcn  AST is slower than Regex after testing. Why `gen service`, sensitive to generating time duration.

**Comment by oldme-git** [comment]
func BenchmarkOfAST(b *testing.B) {
	for i := 0; i < b.N; i++ {
		utils.GetStructs("./file.go")
	}
}

func BenchmarkOfRegex(b *testing.B) {
	PatternApiDefinition := `type\s+(\w+)Req\s+struct\s+{([\s\S]+?)}`
	for i := 0; i < b.N; i++ {
		fileContent := gfile.GetContents("./file.go")
		gregex.MatchAllString(PatternApiDefinition, fileContent)
	}
}

**Comment by gqcn** [comment]
> @gqcn AST is slower than Regex after testing. Why `gen service`, sensitive to generating time duration.

The command `gen service` can automatically generate go files using file watching in Goland IDE. 
<img width="1026" alt="image" src="https://github.com/gogf/gf/assets/26347176/36362c93-bd6d-41ef-bf85-a458db75a11c">

**Comment by gqcn** [comment]
> ```
> func BenchmarkOfAST(b *testing.B) {
> 	for i := 0; i < b.N; i++ {
> 		utils.GetStructs("./file.go")
> 	}
> }
> 
> func BenchmarkOfRegex(b *testing.B) {
> 	PatternApiDefinition := `type\s+(\w+)Req\s+struct\s+{([\s\S]+?)}`
> 	for i := 0; i < b.N; i++ {
> 		fileContent := gfile.GetContents("./file.go")
> 		gregex.MatchAllString(PatternApiDefinition, fileContent)
> 	}
> }
> ```

Please paste the result.

**Comment by oldme-git** [comment]
@gqcn AST is slower than Regex, but the 'gf gen' command scans all files after changing one file. This slows down the file generation process. If we make improvements and opt for AST, we can achieve greater precision and maintain an acceptable generation time.
AST是比正则要慢一些的，但是现在Goland IDE的监控是改变一个文件，会去正则所有的文件。如果只去匹配这个修改的文件，并且采用AST，这样是不是更好？

**Comment by gqcn** [comment]
> @gqcn AST is slower than Regex, but the 'gf gen' command scans all files after changing one file. This slows down the file generation process. If we make improvements and opt for AST, we can achieve greater precision and maintain an acceptable generation time.
> AST是比正则要慢一些的，但是现在Goland IDE的监控是改变一个文件，会去正则所有的文件。如果只去匹配这个修改的文件，并且采用AST，这样是不是更好？

文件的监控虽然能监控到修改了一个文件，但是在代码生成的期间可能用户又改了其他文件，这样会造成生成得代码会有遗漏。所以当前工具的代码自动生成，会每次重新遍历目录，并且判断生成的内容和当前目标文件内容是否一致，判断是否覆盖生成。

**Comment by oldme-git** [comment]
@gqcn 很多 issue 都提到了 gf gen 匹配不精确的问题，已经是月经贴了，所以我关闭了所有此类的问题，统一提到这里讨论。
正则无法适应五花八门的各类代码，在无法替换成 AST 的情况下，当前我能想到的好办法：在文档中去引导 api 和 sevice 的规范
