### ISSUE TITLE
issue in goai: value with example tag needs to be converted just like default value

### ISSUE THREAD

**Issue by wond4** [gogf/gf#3084]
### 1. What version of `Go` and system type/arch are you using?
go version go1.19.5 windows/amd64

### 2. What version of `GoFrame` are you using?
v2.5.2

### 3. Can this issue be re-produced with the latest release?
yes

### 4. What did you do?
1. 使用 gf init goframe-test 生成全新项目
2. 修改 `api/hello/v1/hello.go` ，请求改为post，请求和响应结构体增加int，float，bool字段；
请求使用 `example` 标签指定参数示例，响应使用 `default` 标签指定字段默认值。
最终代码如下：
```go
package v1

import (
	"github.com/gogf/gf/v2/frame/g"
)

type HelloReq struct {
	g.Meta `path:"/hello" tags:"Hello" method:"post" summary:"You first hello api"`

	IntParam   int     `json:"int_param" example:"666"`
	FloatParam float64 `json:"float_param" example:"666.6"`
	BoolParam  bool    `json:"bool_param" example:"true"`
}
type HelloRes struct {
	g.Meta

	IntRes   int     `json:"int_res" default:"666"`
	FloatRes float64 `json:"float_res" default:"666.6"`
	BoolRes  bool    `json:"bool_res" default:"true"`
}
```
3. 运行项目 `go mod tidy && go run main.go` ，然后访问 `swagger` 文档页面（ http://localhost:8000/swagger ）

### 5. What did you expect to see?
int_param、float_param、bool_param示例分别为int类型、浮点类型和布尔类型

### 6. What did you see instead?
int_param、float_param、bool_param 均为字符串类型
![image](https://github.com/gogf/gf/assets/38349899/10260424-9f4f-4ceb-9328-5d7af5e181dd)
但是使用 `default` 标签的 int_res、float_res、bool_res 类型均正确。
判断为生成 `api.json` 时 `default` 标签指定的值做了类型转换，`example` 标签指定的值未作类型转换。

**Comment by wond4** [comment]
已提交pr，请参阅
https://github.com/gogf/gf/pull/3085

**Comment by gqcn** [comment]
> 已提交pr，请参阅 #3085 修复结果： ![image](https://user-images.githubusercontent.com/38349899/277896341-ba95e3c2-e370-4c41-9d7b-f83181ee1ff8.png)

@wond4 Cool! I'll merge it after ci success.
