### ISSUE TITLE
sqlite生成的插入语句有点问题，自增id都写上去了

### ISSUE THREAD

**Issue by xuzhibin** [gogf/gf#309]
![6E1538CB1FC2A754FB4434521441EB9E](https://user-images.githubusercontent.com/1763232/64150724-68605400-ce5b-11e9-9e8d-203951c305b7.jpg)

**Comment by johngcn** [comment]
@xuzhibin 那是因为你写入参数中带有`id`字段，你不传递即可。如果输入的参数是struct，可以通过tag增加`json:"-"`即可

**Comment by xuzhibin** [comment]
通过tag增加json:"-",插入可以，但是调用Save()进行更新又有问题了，感觉sqlite的操作很不稳定，用mysql时就没遇到什么问题，现改用GORM，就没啥问题了。但还是希望@johngcn有空时能测一下sqlite的crud，毕竟用了gf，就不大想再用另一个orm了。

**Comment by johngcn** [comment]
@xuzhibin 能否提交较完整的最小复现问题代码？我这边好根据你反馈的问题改进一下。
