### ISSUE TITLE
批量绑定路由的时候index路径的问题

### ISSUE THREAD

**Issue by piaohao** [gogf/gf#31]
比方说，一般情况下注册路由，
```
server.bindController("/web",new(WebController))
```
此时，/web 或者/web/ 指向  Index方法。
而批量注册路由的情况下，/web或者/web/为not found，必须/web/index才能正确解析

**Comment by johngcn** [comment]
@piaohao 你好，我确认下

**Comment by johngcn** [comment]
@piaohao 确实有这样的问题，我马上处理下。

**Comment by johngcn** [comment]
@piaohao 已修复，并完善相关单元测试，请拉取最新框架代码再试试。

**Comment by piaohao** [comment]
初步测试没有问题了
