### ISSUE TITLE
gf gen service command will automatically import the current service package

### ISSUE THREAD

**Issue by HFLZRH** [gogf/gf#3114]
开发环境：go version go1.21.0 darwin/amd64 ；oFrame CLI Tool v2.5.2, https://goframe.org

![47581698724766_ pic](https://github.com/gogf/gf/assets/36185512/0a05279c-2ad5-4bc9-8bf6-1207614fbe97)

**Comment by MyTimeBox** [comment]
me too!!!!
![image](https://github.com/gogf/gf/assets/24306540/f4afbe29-1574-469e-9c80-b8c0854f1d62)
