### ISSUE TITLE
New version memory increased

### ISSUE THREAD

**Issue by CrazyRocks** [gogf/gf#3117]
I upgraded to a new version and the memory was not released.
The old version of GF only occupied 30% of the memory under the same circumstances.
After upgrading to the new one, it gradually reached more than 50%
Very strange

go version go1.21.0 darwin/amd64
gf v2.5.6

![2](https://github.com/gogf/gf/assets/1498461/c8cc92d7-a808-42f3-9b6b-1cbed93e35c9)

**Comment by hailaz** [comment]
能否补充一个旧版的内存数据图，能加快定位问题所在。
如果旧版是2.5.5的话，2.5.5有一个bug，同一标准路由的hander复用了入参变量导致请求数据污染的bug。

**Comment by CrazyRocks** [comment]
> 能否补充一个旧版的内存数据图，能加快定位问题所在。 如果旧版是2.5.5的话，2.5.5有一个bug，同一标准路由的hander复用了入参变量导致请求数据污染的bug。

func (s *sView) RenderLanCode(ctx context.Context, lan string, code string, viewData g.Map) {
	request := g.RequestFromCtx(ctx)
	site := service.BizCtx().Get(ctx)
	lanPath := fmt.Sprintf("/resource/i18n/%s", site.App.Name)
	m := g.I18n(site.App.Name)
	err := m.SetPath(lanPath)
	if err != nil {
		glog.Debug(ctx, err.Error())
		return
	}
	m.SetLanguage(lan)
	view := g.View(site.App.Name)
	view.SetI18n(m)
	request.SetView(view)

	viewData["lan"] = lan
	viewData["BuildIn"] = &viewBuildIn{httpRequest: request}
	
      content := service.AppTemplate().GetTemplate(ctx, model.AppTemplateDetailIn{
	      AppId: site.App.Id,
	      Code:  code,
      })
      _ = request.Response.WriteTplContent(content, viewData)

}

应该是WriteTplContent这个在goframe在go 1.18，go1.21.0 go的调用的函数不太一样，

go1.18调用的是bytes.makeSlice
go 1.21调用的是bytes.growSlice

观察了以一晚上，1.18没有明显增加
<img width="564" alt="image" src="https://github.com/gogf/gf/assets/1498461/c49091d1-aaae-4f68-8692-a7b6f1d7cdea">

**Comment by hailaz** [comment]
https://github.com/golang/go/blob/release-branch.go1.21/src/bytes/buffer.go#L229
https://github.com/golang/go/blob/release-branch.go1.18/src/bytes/buffer.go#L222
需要测试一下是否有关

**Comment by hailaz** [comment]
go version go1.20.2 windows/amd64
试了一下，没有复现
## 测试代码
```go
// main description
//
// createTime: 2023-11-02 14:55:58
//
// author: hailaz
func main() {
	s := g.Server()
	s.BindHandler("/:table", func(r *ghttp.Request) {
		viewData := g.Map{}
		for i := 0; i < 10; i++ {
			viewData["test"] = grand.S(100000)
			err := r.Response.WriteTplContent("{{.Request.table}}{{.test}}\n", viewData)
			if err != nil {
				r.Response.Write("error")
			}
		}
	})
	// s.SetDumpRouterMap(false)
	s.EnablePProf()
	s.SetPort(8000)
	s.Run()
}

// http://127.0.0.1:8000/hello
//  go tool pprof -http="127.0.0.1:8080"  http://127.0.0.1:8000/debug/pprof/heap

// 实时内存
// http://127.0.0.1:8080/ui/peek?si=inuse_space
// http://127.0.0.1:8080/ui/top?si=inuse_space
```
## 实时内存
![image](https://github.com/gogf/gf/assets/29968474/0691b5cf-9a96-42f9-a6ae-b88b85d0cc56)
## 累计内存
![image](https://github.com/gogf/gf/assets/29968474/1146cb45-e35a-4edb-b5a5-dbbf25a36224)

**Comment by hailaz** [comment]
go version
再补充两个版本

## 1.18.3
![image](https://github.com/gogf/gf/assets/29968474/a2a3ccfe-76c0-43a7-9f6d-4c777423f642)
![image](https://github.com/gogf/gf/assets/29968474/ee84fb0a-6052-46d3-b80c-650fa3f2d3c9)

## 1.21.3
![image](https://github.com/gogf/gf/assets/29968474/a96c65fb-c676-44d5-8a29-be5716251c7e)
![image](https://github.com/gogf/gf/assets/29968474/b1e7c6a4-d37f-45a7-9893-3beb3c51b484)

**Comment by CrazyRocks** [comment]
我在试试，我在线上跑的～

**Comment by CrazyRocks** [comment]
一个神奇的事情是，我把gf降低到了2.5.2就彻底解决了，内存从积累到50%+到现在保持在18%
<img width="458" alt="image" src="https://github.com/gogf/gf/assets/1498461/f2d38ba7-cd23-4255-b2e4-2debb67e56d6">

**Comment by hailaz** [comment]
那要想办法复现才行

**Comment by zcyc** [comment]
@CrazyRocks 你试试 1.21.3，不要用 1.21.0
