### ISSUE TITLE
gf gen ctrl supports multiple layers

### ISSUE THREAD

**Issue by north521** [gogf/gf#3123]
如目录：api/app/v1/user/auth.go  、api/app/v2/user/auth.go，这种目录gf gen ctrl不支持

**Comment by shuqingzai** [comment]
看看 [文档](https://goframe.org/pages/viewpage.action?pageId=93880327#id-%E6%8E%A5%E5%8F%A3%E8%A7%84%E8%8C%83genctrl-%E6%89%8B%E5%8A%A8%E6%A8%A1%E5%BC%8F) 再使用吧

![image](https://github.com/gogf/gf/assets/44406033/c2b29a46-9f09-4f37-b28a-4b9391a961fa)


![image](https://github.com/gogf/gf/assets/44406033/1392e210-b2ea-4562-a738-17d7af84e614)
