### ISSUE TITLE
DoQuery will escape the fields when processing the driver, but `"` is Damon's safe character.

### ISSUE THREAD

**Issue by zhonghuaxunGM** [gogf/gf#3126]
### 1. What version of `Go` and system type/arch are you using?
`go version go1.20.9 windows/amd64`

### 2. What version of `GoFrame` are you using?
`v2.5.6`

### 3. Can this issue be re-produced with the latest release?
`yes`

### 4. What did you do?
I am further adapting to the capabilities of Dameng Driver.

I'm currently dealing with Dameng's situation with the keyword `index`.

I need to add the safe character `"` to the keyword.

I originally hoped to operate in DoQuery's function, but I found that DoQuery's parsing would escape the safe character `"`, and in the end it was still not possible.

![e64bd52310049ce026f90848da94daa](https://github.com/gogf/gf/assets/50815786/a77f1d53-8d04-4960-b33c-b89c2536b89d)

So I had to handle it in DoFilter. But found that it is possible.

![24aff3f045f8611fcfef5b64a93a340](https://github.com/gogf/gf/assets/50815786/2d1182ca-e69a-442a-b096-1b1f947864e0)

Is there any special reason here? Or what do I need to do to be more precise? 

I think there are scenarios where it is better to do it only in DoQuery than in DoFilter, because some scenarios are select statement scenarios and do not include other operations.

**Comment by gqcn** [comment]
@zhonghuaxunGM I do not find any escaping operations in default `DoQuery`. The char `"` might be escaped by function `g.Dump` when printing to stdout.
