### ISSUE TITLE
Why is the gf command-line client so slow!

### ISSUE THREAD

**Issue by svea-vip** [gogf/gf#3129]
d:\>echo '%date% %time%'
'2023-11-03 16:23:14.02'

d:\>gf -v
GoFrame CLI Tool v2.5.6, https://goframe.org
GoFrame Version: cannot find go.mod
CLI Installed At: C:\Users\XXX\go\bin\gf.exe
CLI Built Detail:
  Go Version:  go1.20.8
  GF Version:  v2.5.6
  Git Commit:  2023-10-24 10:02:04 bcb479aabb85ace6c6e42d06801ea27bd2876dbb
  Build Time:  2023-10-24 10:04:35

d:\>echo '%date% %time%'
'2023-11-03 16:23:49.17'

It took over 30 seconds to print the version number

**Comment by hailaz** [comment]
我认为和工具的init函数有关，工具包含了很多init。
![image](https://github.com/gogf/gf/assets/29968474/036eacd6-bccd-4a32-bf42-baba002453fd)
