### ISSUE TITLE
gofram 如何支持response 流式返回

### ISSUE THREAD

**Issue by jetlwx** [gogf/gf#313]
### 4. What did you do?

场景：当服务端要返回BODY很大时，会以流的形式返回，比如说，一行一行将结果返回给浏览器。
目前发现，GIN,echo框架都是支持，但是GOGF还不知道怎么用？
echo：http://go-echo.org/cookbook/streaming-response/
gin：http://note.youdao.com/noteshare?id=258f0ea2ab72499e06e89cc9fa5838d5

希望能给个GOGF示例

**Comment by hailaz** [comment]
```go
s := g.Server()
s.BindHandler("/", func(r *ghttp.Request) {
	w := r.Response.ResponseWriter.ResponseWriter
	//cn, _ := w.(http.CloseNotifier)
	f, _ := w.(http.Flusher)
	//w.Header().Set("Transfer-Encoding", "chunked")
	//w.Header().Set("Conten-Type", "text/event-stream")
	w.WriteHeader(http.StatusOK)
	f.Flush()
	//clientGone := cn.CloseNotify()
	count := 0
	for {
		select {
		//case <-clientGone:
		//return true
		default:
			fmt.Fprintf(w, "time.now(): %v \n", time.Now())
			f.Flush()
			time.Sleep(time.Second)
			count++
			if count == 100 {
				return
			}
		}
	}
})
s.Run()
```

**Comment by jetlwx** [comment]
func ExecuteOSCommand(r *ghttp.Request) {
	//	var stdoutBuf, stderrBuf bytes.Buffer
	w := r.Response.ResponseWriter.ResponseWriter
	cmd := exec.Command("/bin/bash", "-c", "while [ 1 ]; do sleep 1; date; done")
	flusher, ok := w.(http.Flusher)
	if !ok {
		comm.JetLog("E", "expected http.ResponseWriter to be an http.Flusher")
		r.Response.Write("expected http.ResponseWriter to be an http.Flusher")
	}
	w.Header().Set("Connection", "Keep-Alive")
	w.Header().Set("Transfer-Encoding", "chunked")
	w.Header().Set("X-Content-Type-Options", "nosniff")
	w.Header().Set("Keep-Alive", "timeout=120")
	stdout, err := cmd.StdoutPipe()
	cmd.Stderr = cmd.Stdout

	if err != nil {
		r.Response.Write(err.Error())
	}

	if err = cmd.Start(); err != nil {
		r.Response.Write(err.Error())
	}
	// 从管道中实时获取输出并打印到终端

	reader := bufio.NewReader(stdout)

	//实时循环读取输出流中的一行内容
	for {
		line, err2 := reader.ReadString('\n')
		if err2 != nil {
			w.Write([]byte(err2.Error()))
		}

		if err2 == io.EOF {
			flusher.Flush()
			break
		}

		w.Write([]byte(line))
		flusher.Flush()
	}

	cmd.Wait()

}

//问题：服务端设置了超时，所以，不会一直显示执行结果，而无情的掐断。。。。。怎么破？？？？
