### ISSUE TITLE
After upgrading to the latest version V2.5.6, the bug that expired old log files are not cleared under Windows still exists.

### ISSUE THREAD

**Issue by wlqe** [gogf/gf#3132]
升级到最新的V2.5.6版本，该版本仍然没有修复已过期的旧文件未被清理的bug，问题依旧存在。
可使用如下配置文件还原bug。
logger:
    path: "./Log"
    file: "{Y-m-d-H-i}.log"
    level : "all"
    stdout: true
    rotateExpire: 1m      #一分钟一个回滚
    rotateBackupLimit: 4  #保留4个日志文件
    rotateCheckInterval: 5s #每5秒切分检查时间间隔
过上几分钟后，在日志目录中会发现超过4个的日志文件没有被清理掉。

_Originally posted by @wlqe in https://github.com/gogf/gf/issues/3080#issuecomment-1793995087_

**Comment by hailaz** [comment]
我试了下master可以。2.5.6应该还没更新到，https://github.com/gogf/gf/pull/3080 的合并时间比2.5.6晚。
![image](https://github.com/gogf/gf/assets/29968474/0bae6979-bc26-475e-bcfa-759dfb3fa2bb)
![image](https://github.com/gogf/gf/assets/29968474/5a6b0cee-90c3-491e-9d2b-ce77df9ec309)

**Comment by hailaz** [comment]
@wlqe

**Comment by wlqe** [comment]
@hailaz ok，谢谢，没注意2.5.6还没合并进来
