### ISSUE TITLE
[BUG] When setting the `required` tag in the gjson type field in the request or response struct (req/res), OpenAPI cannot generate the required identifier.

### ISSUE THREAD

**Issue by shuqingzai** [gogf/gf#3135]
如下，`Rgba` 字段设置了 `required` ，文档未体现必须标识， `Color` 可以体现
```go
// ColorsSaveReq 颜色 - 保存(创建/更新) - 请求
type ColorsSaveReq struct {
	g.Meta `path:"/demo/colors" method:"POST" summary:"颜色 - 保存" tags:"颜色管理" description:"颜色 - 保存"`

	// ID ID
	ID uint64 `json:"id,string" dc:"ID" v:"id-zero"`
	// Color 颜色值16进制表示法
	Color string `json:"color" dc:"颜色值16进制表示法" v:"required|max-length:10"`
	// Rgba 颜色值RGBA表示法
	Rgba *gjson.Json `json:"rgba" dc:"颜色值RGBA表示法" v:"required|json"`
}
```

生成的文档参考：

![image](https://github.com/gogf/gf/assets/44406033/57881c67-7c65-46a3-8fc9-fd98d8098dd7)

### 1. What version of `Go` and system type/arch are you using?

```bash
# -> % go version
go version go1.21.3 darwin/amd64
```

### 2. What version of `GoFrame` are you using?

```bash
# -> % gf version
GoFrame CLI Tool v2.5.6, https://goframe.org
GoFrame Version: v2.5.6 in current go.mod
```

### 3. Can this issue be re-produced with the latest release?

是的

**Comment by oldme-git** [comment]
`Required` param doesn't support struct type. You can view docs for further assistance. [docs](https://goframe.org/pages/viewpage.action?pageId=1114367#id-%E6%95%B0%E6%8D%AE%E6%A0%A1%E9%AA%8C%E6%A0%A1%E9%AA%8C%E8%A7%84%E5%88%99-required)

**Comment by shuqingzai** [comment]
> `Required` param doesn't support struct type. You can view docs for further assistance. [docs](https://goframe.org/pages/viewpage.action?pageId=1114367#id-%E6%95%B0%E6%8D%AE%E6%A0%A1%E9%AA%8C%E6%A0%A1%E9%AA%8C%E8%A7%84%E5%88%99-required)
> 
> `Required` 不支持结构体类型，可以详阅一下文档 [docs](https://goframe.org/pages/viewpage.action?pageId=1114367#id-%E6%95%B0%E6%8D%AE%E6%A0%A1%E9%AA%8C%E6%A0%A1%E9%AA%8C%E8%A7%84%E5%88%99-required)

所以才反馈问题呀，可以支持的吧，而且写了注释也没有显示

![image](https://github.com/gogf/gf/assets/44406033/b23b8684-47bb-4fb7-95b2-c1c71c598272)

**Comment by oldme-git** [comment]
@shuqingzai gjson.json 是一个结构体类型，GoFrame 支持嵌套结构体数据校检，可以查看此处文档了解 [docs](https://goframe.org/pages/viewpage.action?pageId=7302150#Struct%E6%A0%A1%E9%AA%8C%E5%9F%BA%E6%9C%AC%E4%BD%BF%E7%94%A8-%E7%BB%93%E6%9E%84%E4%BD%93%E9%80%92%E5%BD%92%E6%A0%A1%E9%AA%8C%EF%BC%88%E5%B5%8C%E5%A5%97%E6%A0%A1%E9%AA%8C%EF%BC%89)

**Comment by shuqingzai** [comment]
> @shuqingzai gjson.json 是一个结构体类型，GoFrame 支持嵌套结构体数据校检，可以查看此处文档了解 [docs](https://goframe.org/pages/viewpage.action?pageId=7302150#Struct%E6%A0%A1%E9%AA%8C%E5%9F%BA%E6%9C%AC%E4%BD%BF%E7%94%A8-%E7%BB%93%E6%9E%84%E4%BD%93%E9%80%92%E5%BD%92%E6%A0%A1%E9%AA%8C%EF%BC%88%E5%B5%8C%E5%A5%97%E6%A0%A1%E9%AA%8C%EF%BC%89)
> 
> gjson.json is a struct type. GoFrame supports validate for embedding of structs.

@oldme-git 

如果你说的与本话题有差异，虽然我知道 GF 底层生成文档时，是否必填是使用 `v` 相关标签可以指定，但是我已经明确指定为：`required` ，即使在数据验证时，不支持验证是否为空，但是文档上也可以体现吧，或者加个 OpenAPI 标签，因为我尝试在字段上加 `required="true"` 也是无效的，还有就是如果是结构体，文档中的描述也被丢弃，也是有问题吧

**Comment by wln32** [comment]
> > @shuqingzai gjson.json 是一个结构体类型，GoFrame 支持嵌套结构体数据校检，可以查看此处文档了解 [docs](https://goframe.org/pages/viewpage.action?pageId=7302150#Struct%E6%A0%A1%E9%AA%8C%E5%9F%BA%E6%9C%AC%E4%BD%BF%E7%94%A8-%E7%BB%93%E6%9E%84%E4%BD%93%E9%80%92%E5%BD%92%E6%A0%A1%E9%AA%8C%EF%BC%88%E5%B5%8C%E5%A5%97%E6%A0%A1%E9%AA%8C%EF%BC%89)
> > gjson.json is a struct type. GoFrame supports validate for embedding of structs.
> 
> @oldme-git
> 
> 你说的与本话题有差异，虽然我知道 GF 底层生成文档时，是否必填是使用 `v` 相关标签可以指定，但是我已经明确指定为：`required` ，即使在数据验证时，不支持验证是否为空，但是文档上也可以体现吧，或者加个 OpenAPI 标签，因为我尝试在字段上加 `required="true"` 也是无效的，还有就是如果是结构体，文档中的描述也被丢弃，也是有问题吧

我也觉得文档上应该生成required这个规则，用来提示这个是必须参数，具体验证的时候，不支持的时候可以忽略掉即可

**Comment by gqcn** [comment]
@shuqingzai @oldme-git @wln32 不好意思，我来晚了，由于邮件丢失我错过了一些issue的消息提示。我先来看看呢。
