### ISSUE TITLE
建议允许开发者增加自定义的校验规则

### ISSUE THREAD

**Issue by arieslee** [gogf/gf#314]
需求背景：虽然gvalid提供的验证器很多也很实用并且也支持正则校验，但是并不支持开发者添加自定义的校验规则，针对于各种各样的业务数据校验，也许允许开发者自定义校验规则是一个很不错的特性。
适用场景：前端向后台传入一个数组，后台要校验数组中的某些值
期望的提供方式：
1.
·```
像yii的Form rules一样，可以传自定义的函数名
    ['data', 'verifyData','message'=>‘请输入正确的数组数据'],
function verifyPhone($data){
    if(!$data){
        return false;
    }
    foreach($data as $k=>$v){
        if(!isset($data['checked'] || !$data['checked']){
             return false;
        }
    }
//验证失败
 return false;
  //验证成功
 return true];
}

**Comment by macnie** [comment]
这个很不错。会灵活很多的。

**Comment by hailaz** [comment]
https://goframe.org/pages/viewpage.action?pageId=1114282
