### ISSUE TITLE
Please change the input parameter type of SetDefaultLogger to ILogger

### ISSUE THREAD

**Issue by shuqingzai** [gogf/gf#3156]
同 #2704 ，不理解回复中的强制不允许修改是为什么？可以说明一下理由吗？？理论上，用户应该是可以自定义Log，既然有接口 ，比如：我们需要将日志的写入与输出格式统一化为 [zap](https://github.com/uber-go/zap) ，方便上层统一采集，现在无法实现

### 1. What version of `Go` and system type/arch are you using?

```bash
# -> % go version
go version go1.21.3 darwin/amd64
```

### 2. What version of `GoFrame` are you using?

```bash
# -> % gf version
GoFrame CLI Tool v2.5.6, https://goframe.org
GoFrame Version: v2.5.6 in current go.mod
```

### 3. Can this issue be re-produced with the latest release?

是的

**Comment by wln732** [comment]
```go
func handlerLog(ctx context.Context, in *glog.HandlerInput) {
	fmt.Println(in.Values...)
}

func main() {
	glog.SetDefaultHandler(handlerLog)
	glog.Info(nil, "hello worold", "666")
}
```
貌似可以用这种方法来实现，HandlerInput有调用info error panic方法的一些信息

**Comment by gqcn** [comment]
@shuqingzai @wln32 
不好意思，我来晚了，由于邮件丢失我错过了一些issue的消息提示。
这里的`glog.SetDefaultLogger`仅针对`glog`组件生效，用于修改`glog`组件公开包方法使用的默认`glog.Logger`对象，这样通过`glog.Xxx`或者`g.Log().Xxx`可以使用该`*glog.Logger`对象。
由于`glog.Logger`的功能特性比较多，因此不支持使用通用日志接口的形式来设置，通用日志接口的方式仅适用于其他组件包，例如该组件包仅仅会使用某几个日志打印方法且没有用到高级日志特性的场景下适用。
如果想使用第三方的日志组件可以参考前面 @wln32 提供的方式来设置自定义的日志打印逻辑。
感谢大家❤️
