### ISSUE TITLE
goroutine panics, it will also cause the service to exit.

### ISSUE THREAD

**Issue by wenhw** [gogf/gf#3158]
### 1. What version of `Go` and system type/arch are you using?

go version go1.21.3 windows/amd64

### 2. What version of `GoFrame` are you using?

GoFrame CLI Tool v2.5.6, https://goframe.org
GoFrame Version: v2.5.6 in current go.mod

### 3. Can this issue be re-produced with the latest release?

yes

### 4. What did you do?

1. gf init demo -u
2. internal/controller/hello/hello_v1_hello.go添加如下代码
```
func (c *ControllerV1) Hello(ctx context.Context, req *v1.HelloReq) (res *v1.HelloRes, err error) {
	g.RequestFromCtx(ctx).Response.Writeln("Hello World!")

	go func() {
		panic("oops!!!")
	}()

	return
}
```
3. curl -i http://localhost:8000/hello

### 5. What did you expect to see?

某个goroutine panic后，主协程（服务）不应该退出

PS C:\Users\test> netstat -anot | findstr 8000
  TCP    0.0.0.0:8000           0.0.0.0:0              LISTENING       7188     InHost
  TCP    [::]:8000              [::]:0                 LISTENING       7188     InHost

### 6. What did you see instead?

服务进程退出了

**Comment by hailaz** [comment]
自己创建的协程，需要自己捕获异常。

**Comment by wenhw** [comment]
参考gin，它是能自己recovery的

**Comment by hailaz** [comment]
> 参考gin，它是能自己recovery的

要不你再试试？或者发你的代码出来。
```go
func main() {
	router := gin.Default()
	router.GET("/ping", func(c *gin.Context) {
		go func() {
			panic("a problem has occurred")
		}()
		c.JSON(200, gin.H{
			"message": "response",
		})
	})
	router.Run()
}
```

**Comment by wenhw** [comment]
你是对的，我测试代码没加goroutine，只是panic，加了goroutine后是要自己recover
