### ISSUE TITLE
Make a suggestion and hope it can be improved and a GRPC problem

### ISSUE THREAD

**Issue by ethantx** [gogf/gf#3159]
需要改进
一、全局的注册服务发现功能，希望改成按需加载。
二、GRPC服务端建议加个超时管理，客户端连过来超过N秒后就断开。这方面gozero处理得非常好
三、GRPC客户端首次链接时不会抛出error异常。这个应该需要抛出来才行

**Comment by gqcn** [comment]
@ethantx 不好意思，我来晚了，由于邮件丢失我错过了一些issue的消息提示。感谢你的反馈和建议，我一一回复一下：
> 一、全局的注册服务发现功能，希望改成按需加载。
关于第一点，能否详细描述一下痛点？

> 二、GRPC服务端建议加个超时管理，客户端连过来超过N秒后就断开。这方面gozero处理得非常好
关于第二点，这块和 https://github.com/gogf/gf/issues/3189 重复，希望大家一起来共建这块中间件。

> 三、GRPC客户端首次链接时不会抛出error异常。这个应该需要抛出来才行
关于第三点，我看创建`GRPC`客户端时如果存在错误都会返回，这块能否也详细描述一下？
