### ISSUE TITLE
Is there any example of integration with Elastic APM Go agent?

### ISSUE THREAD

**Issue by k359792067** [gogf/gf#3163]
I am trying to use Elastic APM to observe my application, is there any example of using it? I didn't find any support at https://www.elastic.co/guide/en/apm/agent/go/master/supported-tech.html.

**Comment by hailaz** [comment]
参考gin的实现写个全局中间件应该就可以了
https://www.elastic.co/guide/en/apm/agent/go/master/builtin-modules.html#builtin-modules-apmgin
https://github.com/elastic/apm-agent-go/blob/main/module/apmgin/middleware.go
