### ISSUE TITLE
When the database requires a default value to report an error, batch addition cannot capture the error, but a single one can

### ISSUE THREAD

**Issue by lukeyMing** [gogf/gf#3168]
gf 2.5.6
go 1.20

多条新增无任何提示 err = nil, 仅当数据库配置debug: true 时，也仅仅在日志里会提示 Error 1364 (HY000): Field 'catePid' doesn't have a default value

_, err = dao.QsCategory.Ctx(ctx).Insert(g.List{
		g.Map{
			"areaId":     1,
			"cateId":     1,
			"sourceFrom": "aa",
		},
		g.Map{
			"areaId":     1,
			"cateId":     10,
			"catePid":    1,
			"sourceFrom": "aa",
		},
})

单条新增，正常返回err
_, err = dao.QsCategory.Ctx(ctx).Insert(g.Map{
			"areaId":     1,
			"cateId":     1,
			"sourceFrom": "aa",
})

**Comment by lukeyMing** [comment]
为什么唯一索引  批量新增也有这个问题，  救命啊，要改这没多代码，有没有人啊，真的要命了

**Comment by gqcn** [comment]
@lukeyMing 不好意思，由于错过了一些github的邮件提示，回复晚了。建议你更新使用最新版本再试试。如果问题依旧请重新创建issue并提交可复现该问题的最小可运行代码。
