### ISSUE TITLE
When html An error occurred when using input in SpecialCharsMapOrStruct

### ISSUE THREAD

**Issue by 1cccccc** [gogf/gf#3173]
model
```
type AdminAddInput struct {
	Name     string  `json:"name"`     //用户名
	Password string  `json:"password"` //密码
	RoleIds  *string `json:"roleIds"`  //角色列表
	IsAdmin  uint8   `json:"isAdmin"`  //是否是管理员
}
```

logic
```
func (a *sAdmin) Add(ctx context.Context, input model.AdminAddInput) error {
	if err := ghtml.SpecialCharsMapOrStruct(input); err != nil {
		return gerror.New(exceptions.XssException)
	}
	//业务代码
        return nil
}
```

接口请求参数如下
The interface request parameters are as follows
![image](https://github.com/gogf/gf/assets/68212098/28af2379-397a-4eb2-85f3-d77411c7ecc9)

报错信息如下
The error message is as follows
![image](https://github.com/gogf/gf/assets/68212098/afa3cd71-485f-47e5-8f4e-beb1b5447484)

换成地址传值却正常调用
Change to address and pass value but call normally
![image](https://github.com/gogf/gf/assets/68212098/759104c9-7017-4be7-90bb-504670fdbe22)

我的另一个接口不使用地址传值却也正常运行
My other interface doesn't use address transfer, but it still runs normally
![image](https://github.com/gogf/gf/assets/68212098/374ce4d4-f49c-4722-9eeb-62a9d3258f0e)
![image](https://github.com/gogf/gf/assets/68212098/cfac1b9c-10b5-47e2-878b-549b7dfc1339)

**Comment by gqcn** [comment]
@1cccccc Hello, the input parameter of function `ghtml.SpecialCharsMapOrStruct` should be type of pointer. I'll improve the validation of the function.
