### ISSUE TITLE
[BUG] Time analysis

### ISSUE THREAD

**Issue by shuqingzai** [gogf/gf#3180]
数据测试

```json
{
    "status": 1,
    "completedTime": "2023-01-01T19:46:31Z"
}
```

API 结构体

```go
// GfDemoCreateReq GF演示 - 创建请求
type GfDemoCreateReq struct {
	g.Meta `path:"/demo/gf-demo" method:"POST" summary:"GF演示 - 创建" tags:"演示服务" description:"GF演示 - 创建" security:"adminJWTAuth"`

	// Status 状态
	Status gf_demo.Status `json:"status" dc:"状态:0=待处理1=处理中2=已处理" v:"required|in-enums"`
	// CompletedTime 完成时间
	CompletedTime *timex.DateTimeRFC3339 `json:"completedTime" dc:"完成时间" eg:"2023-09-01T12:00:00+00:00" format:"date-time" v:"required|date-format:c"`
}
```

时间字段定义

```go
package timex

import (
	"bytes"
	"fmt"

	"github.com/golang-module/carbon/v2"
)

// DateTimeRFC3339 基于 [carbon.Carbon] 的封装 - 精度: 秒(s)
//
// 支持格式化字符串时间，如：2023-01-01T00:00:00+08:00, 2023-01-01T00:00:00Z
//
// See: timex.DateTimeRFC3339
type DateTimeRFC3339 struct {
	carbon.Carbon
}


// MarshalJSON 实现接口: [json.Marshaler]
//
// 格式化: "2006-01-02T15:04:05Z07:00"
func (t DateTimeRFC3339) MarshalJSON() ([]byte, error) {
	return []byte(fmt.Sprintf(`"%s"`, t.ToRfc3339String())), nil
}

// UnmarshalJSON 实现接口: [json.Unmarshaler]
//
// 支持格式化字符串时间，如：2023-01-01T00:00:00+08:00, 2023-01-01T00:00:00Z
func (t *DateTimeRFC3339) UnmarshalJSON(b []byte) error {
	c := carbon.ParseByLayout(string(bytes.Trim(b, `"`)), carbon.RFC3339Layout, t.Location())
	if c.Error == nil {
		*t = DateTimeRFC3339{Carbon: c}
	}
	return c.Error
}
```

1. 目前 API 时间格式解析使用 `date-format:format` 使用 `date-format:c` 不支持类似 `2023-01-01T19:46:31Z` 格式，只能是 `2023-01-01T19:46:31+00:00` ，希望可以支持

错误
```text
The CompletedTime value `2023-09-10T19:46:31Z` does not match the format: c
```

3. 如果使用 `date-format:c` 格式时间字段，如果传递非定义的格式，如：`2023-01-01 19:46:31` 会直接 panic ，而不是提示时间格式不对

错误
```text
reflect.Value.Convert: value of type string cannot be converted to type
```

### 1. What version of `Go` and system type/arch are you using?

```bash
# -> % go version
go version go1.21.4 darwin/amd64
```

### 2. What version of `GoFrame` are you using?

```bash
# -> % gf version
v2.5.7
Welcome to GoFrame!
Env Detail:
  Go Version: go1.21.4 darwin/amd64
  GF Version(go.mod):
    github.com/gogf/gf/v2@v2.5.7
CLI Detail:
  Installed At: /Code/go/bin/gf
  Built Go Version: go1.21.4
  Built GF Version: v2.5.7
Others Detail:
  Docs: https://goframe.org
  Now : 2023-11-27T18:26:37+08:00
```

### 3. Can this issue be re-produced with the latest release?

是的

**Comment by hailaz** [comment]
试试`date-format:2006-01-02\\T15:04:05Z07:00`

**Comment by shuqingzai** [comment]
> 2006-01-02\\T15:04:05Z07:00

@hailaz 使用上面测试的代码，第三个BUG没有得到正确的响应，应该是格式错误，而不是直接 panic

```bash
1. reflect.Value.Convert: value of type string cannot be converted to type timex.DateTimeRFC3339
```

请求参数

```json
{
    "status": 1,
    "completedTime": "2023-01-01 19:46:31"
}
```

**Comment by shuqingzai** [comment]
> 试试`date-format:2006-01-02\\T15:04:05Z07:00`
@hailaz 

传递UTC没有问题，但是当传递时区时就会错误

请求参数
```json
{
    "status": 1,
    "completedTime": "2023-09-10T19:46:31+08:00"
}
```

**Comment by hailaz** [comment]
@shuqingzai 

没问题的呀，转换成功之后才是规则校验，现在的情况是转换失败。
![image](https://github.com/gogf/gf/assets/29968474/8814f099-2902-44d1-a671-bddf355c963c)

**Comment by hailaz** [comment]
如果你把类型换成string就不会在转换时panic了。
```
CompletedTime string `json:"completedTime" dc:"完成时间" eg:"2023-09-01T12:00:00+00:00" format:"date-time" v:"required|date-format:2006-01-02\\T15:04:05Z07:00"`
```

The CompletedTime value `2023-01-01 19:46:31` does not match the format: 2006-01-02\T15:04:05Z07:00

提示的错误好像多了个\，得处理一下，这个\是避免T被转义了

**Comment by shuqingzai** [comment]
> 如果你把类型换成string就不会在转换时panic了。
> 
> ```
> CompletedTime string `json:"completedTime" dc:"完成时间" eg:"2023-09-01T12:00:00+00:00" format:"date-time" v:"required|date-format:2006-01-02\\T15:04:05Z07:00"`
> ```
> 
> The CompletedTime value `2023-01-01 19:46:31` does not match the format: 2006-01-02\T15:04:05Z07:00
> 
> 提示的错误好像多了个\，得处理一下，这个\是避免T被转义了

@hailaz 我不是很明白你的意思？？？

1. 如果是转换格式错误，应该是直接提示格式不对，无法转换之类的，而不是程序直接 panic ，对于业务来说 panic 比 error 的层级要深得多
2. 你说的错误多了 \ 的问题，我觉得不是问题，因为我设置的格式就是这样的，不然传递 `2023-01-01T19:46:31Z` 或 `2023-01-01T19:46:31+08:00` 不也没法通过吗？，这种情况是因为格式不对，算校验失败的错误吧，参考 3
3. 自定义类型时，它( `2023-01-01 19:46:31` )反序列化应该如何都不会成功，就像你说的没有匹配到解析时间的模板，符合预期，因为我实现了 `json.Unmarshaler` 接口，因为 httpServer 使用标准库反序列化，参考： https://github.com/gogf/gf/blob/0b6dd6fb13436f6c7eb1268efbc173e8f6a405a9/net/ghttp/ghttp_request_param.go#L242 但是有错误却被忽略了
4. 你说的用 `string` 对于用户来说，只是临时解决当前的BUG，根本问题没有解决，而且使用 `string` ，代表我的时间字段没了它的用处，难道说用户不能自定义字段类型吗？

**Comment by hailaz** [comment]
两个回复只是具体说明为什么报错。
1. 因为转换的流程出现了panic，所以流程并没有到达规则校验那一步。
2. 而使用string类型就可以到达规则校验那一步，是举例说明当转换不报错的情况是什么样子的。


至于关于\的内容是指写date-format自定义规则的时候，某些字母会被当成[内置规则](https://github.com/gogf/gf/blob/b9e2b05f0412c7f5df9a4a11a1c1a68461a2de72/os/gtime/gtime_format.go#L20)，
比如
`date-format:c`的c会被转换为`2006-01-02T15:04:05-07:00`
`date-format:\\c`的c不会
`date-format:2006-01-02\\T15:04:05Z07:00`对应`2006-01-02T15:04:05Z07:00`（\\T是避免T被转换了，Z不需要是因为没有对应规则）

但报错时提示`2006-01-02\T15:04:05Z07:00`，会被误以为需要的格式是`2006-01-02\T15:04:05Z07:00`而不是`2006-01-02T15:04:05Z07:00`

----

然后再回答你的问题
答1. 算是一个[bug](https://github.com/gogf/gf/blob/ea5d52cb2f0b8484ed2c3a84f1621ccf374c8477/util/gconv/gconv_struct.go#L652)，应该把panic转换成error 

答2. 原意是指错误的提示不准确，容易误解。

答3. 没读懂

答4. 是你误解我的意思，我是通过string来举例说明date-format如何写规则能校验RFC3339格式。因为按答1说的，有个bug的存在，体验不到校验RFC3339格式。

----

总结一下
1. 数据转换有一个bug。需要修复。
2. 数据校验的提示需要优化一下，避免误解


最后，我认为`数据转换`和`数据校验`是两个东西。

**Comment by shuqingzai** [comment]
@hailaz 第三点指的是 https://github.com/gogf/gf/blob/0b6dd6fb13436f6c7eb1268efbc173e8f6a405a9/net/ghttp/ghttp_request_param.go#L242 这行代码已经会报错（因为我实现的 `UnmarshalJSON ` 方法仅接受 `RFC3339` 的时间格式解码） 后续的代码无需再跑，这里忽略错误是不应该的，参考：#3185

或直接进入验证，提示字段错误提示语，

**Comment by shuqingzai** [comment]
@hailaz 我也很明确，数据转换和数据验证是两个概念，数据转换无法转化成功应该是用户数据有问题，两种选择
1. 直接将无法转换的信息反馈给调用方，但如果调用方就是API客户端，这很不友好，直接把 go 或系统内置的错误暴露出去，有风险
2. 使用空数据进行数据验证，由于无法转换数据，使用空数据进行数据验证可以显示用户自定义的错误信息，其实我更倾向这种处理方式
