### ISSUE TITLE
[BUG] HTTP Server response OpenTelemetry Header Key does not fully comply with the OpenTelemetry standard

### ISSUE THREAD

**Issue by shuqingzai** [gogf/gf#3186]
GF 在响应中，仅响应了  OpenTelemetry 的 `TraceID` 部分，缺少完整的信息，参考：https://github.com/gogf/gf/blob/0b6dd6fb13436f6c7eb1268efbc173e8f6a405a9/net/ghttp/ghttp_response.go#L161

应该响应一个 `Traceparent` header Key，包含完整的链路信息

参考：

- [Traceparent Header](https://www.w3.org/TR/trace-context/#traceparent-header)
- [what-is-traceparent-header](https://uptrace.dev/opentelemetry/opentelemetry-traceparent.html#what-is-traceparent-header) 

以便调用方可以获取父级的 Span 与采用率等信息

### 1. What version of `Go` and system type/arch are you using?

```bash
# -> % go version
go version go1.21.4 darwin/amd64
```

### 2. What version of `GoFrame` are you using?

```bash
# -> % gf version
v2.5.7
Welcome to GoFrame!
Env Detail:
  Go Version: go1.21.4 darwin/amd64
  GF Version(go.mod):
    github.com/gogf/gf/v2@v2.5.7
CLI Detail:
  Installed At: /Code/go/bin/gf
  Built Go Version: go1.21.4
  Built GF Version: v2.5.7
Others Detail:
  Docs: https://goframe.org
  Now : 2023-11-27T18:26:37+08:00
```

### 3. Can this issue be re-produced with the latest release?

是的

**Comment by houseme** [comment]
可以详细描述一下使用场景以及需要的作用，欢迎提pr改进
