### ISSUE TITLE
TreeMap support range iterator

### ISSUE THREAD

**Issue by mostcute** [gogf/gf#3190]
the treemap is sorted ,can it supply a new func to support range iterator?

input (start,end)
output the range key in range(start,end)

**Comment by gqcn** [comment]
@mostcute Interesting proposal! It might provide a iteration function like `IterateRange(startKey, endKey any, f func(key, value any) bool)`.

The TreeMap already provides Iteration functions, please refer to its implemented interface https://github.com/gogf/gf/blob/183395f0a0f59c1680ce0e78638dd541e4e1c84e/container/gtree/gtree.go#L119 You can workaround using this function.

**Comment by mostcute** [comment]
> @mostcute Interesting proposal! It might provide a iteration function like `IterateRange(startKey, endKey any, f func(key, value any) bool)`.
> 
> The TreeMap already provides Iteration functions, please refer to its implemented interface
> 
> https://github.com/gogf/gf/blob/183395f0a0f59c1680ce0e78638dd541e4e1c84e/container/gtree/gtree.go#L119
> 
> You can workaround using this function.

i know this func, just need a more efficient way to find some data in map,not pass all data
