### ISSUE TITLE
gredis cannot override Do method

### ISSUE THREAD

**Issue by merlin888888** [gogf/gf#3191]
![gf](https://github.com/gogf/gf/assets/25861811/9c8be133-5305-4ef0-8c26-7872e72d47e6)
使用gredis调用g.redis().Do() 和g.redis().Hset() 方法最后调用的Do方法不一致，请问下为什么不通用上面的Do方法呢？这样可以在业务层实现重写Do方法，增加一些业务处理，如日志记录等需求。
当前继承Adapter，然后使用g.Redis().SetAdapter()，自己实现Do方法，只能覆盖g.redis().Do()一种场景，使用其它封装的命令无法覆盖Do方法。

**Comment by hailaz** [comment]
我觉得你要继承的应该是https://github.com/gogf/gf/blob/ab5ab4c675290c6a89f11fe5265e177d5df4aa58/contrib/nosql/redis/redis.go#L24

**Comment by hailaz** [comment]
目前没有很好的办法处理这个问题，可能需要改进现有的实现。

**Comment by hailaz** [comment]
@merlin888888 已经可以了，如果着急可以试试master分支。具体使用可以看#3194
