### ISSUE TITLE
我需要搭建标准WebSocket服务，这个框架能实现吗？ 

### ISSUE THREAD

**Issue by richfuns** [gogf/gf#32]
### 1. What version of `Go` are you using (`go version`)?
go 1.12
<pre>
$ go version

</pre>

### 2. What version of `GoFrame` are you using?

最新版本

### 3. Does this issue reproduce with the latest release?

不确定

### 5. What did you expect to see?

我需要搭建标准WebSocket（SSL）服务，这个框架能实现吗？

**Comment by johngcn** [comment]
@richfuns 可以，请参考 https://goframe.org/net/ghttp/websocket

**Comment by richfuns** [comment]
@johngcn  谢谢回复，这个是标准的Ws吗？  能不能实现基于ssl的ws呢？
