### ISSUE TITLE
The in.Content of the custom log handler is lost

### ISSUE THREAD

**Issue by hailaz** [gogf/gf#3200]
因为这个提交删除了相关处理
https://github.com/gogf/gf/pull/2919/files#diff-0950fd3e63cfb4b28566d3c8332c953272a247a2ac36d50cf6b4e299f1aea419L209

测试代码
![image](https://github.com/gogf/gf/assets/29968474/3b3b05b4-9a27-419a-8ba7-d99e7c98d269)

https://github.com/gogf/gf/blob/887803e4950019f85e8373e5bef9be221dbddf59/os/glog/glog_z_unit_logger_handler_test.go#L23

**Comment by hailaz** [comment]
@gqcn 有空看看

**Comment by gqcn** [comment]
@hailaz OK, let me have a check.

**Comment by l12ab** [comment]
遇到了同样的情况，in.Content为空
