### ISSUE TITLE
how to control gdb trace ?

### ISSUE THREAD

**Issue by Ccheers** [gogf/gf#3201]

**Comment by Ccheers** [comment]
每个sql都会打 trace 打太多了

**Comment by weimx2023** [comment]
Hi there, You can try using controlled sampling ratio.https://github.com/gogf/gf/issues/3171

**Comment by gqcn** [comment]
@Ccheers @weimx2023 Yes, sampling radio might be a good choice for this, we'll consider this carefully and we'll be appreciated for any contributions for this. @houseme 

closed as duplicated with https://github.com/gogf/gf/issues/3171
