### ISSUE TITLE
Is there any official plan to maintain the permission plug-in? For example casbin

### ISSUE THREAD

**Issue by swift-fs** [gogf/gf#3210]
Recently, I worked on a new project that required a complete permission control process. The GF framework does a good job in all aspects, but there is no official permission control plug-in!

I searched the issue, and there are many requests for this. I saw a lot of backend management systems on awesome-gf, all of which have their own set of permission controls, such as hotgo and gfast, but many things in them are unusable and I don’t want to make modifications based on them. There are too many uncontrollable factors. 

More than that, GF itself is already very complete, and I don’t want to start a second project based on GF’s other projects. Now I want GF to create a package that can meet my needs. I originally wanted to use a plug-in similar to gorm-casbin-adapter, but I found that many of them are not maintained, and there is a risk of running away at any time, which is a headache...

**Comment by hailaz** [comment]
这个如何？https://github.com/hailaz/gf-casbin-adapter

**Comment by gqcn** [comment]
@swift-fs Hello, there's no plan of permission controlling component development in goframe recently, as there's good open-sourced choice in Golang community, for example casbin https://github.com/casbin/casbin .
