### ISSUE TITLE
The - p parameter of gf does not work

### ISSUE THREAD

**Issue by chehan01** [gogf/gf#3232]
### 1. What version of `Go` and system type/arch are you using?
go1.21.5 Linux/amd64

### 2. What version of `GoFrame` are you using?
V2.6.1

### 3. Can this issue be re-produced with the latest release?
yes

### 4. What did you do?
I run `gf build main.go -p ./manifest/docker` command in my project directory.

### 5. What did you expect to see?
gf tool builds the binary to the ./manifest/docker directory, but not.

### 6. What did you see instead?
I saw gf tool builds the binary in the project root directory.

![image](https://github.com/gogf/gf/assets/69077125/1d8b7add-e854-4164-9afb-61dc9c83ef68)

**Comment by Blacknight1260** [comment]
You got the wrong person

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Che Han ***@***.***>
Sent: Wednesday, December 27, 2023 12:41:47 AM
To: gogf/gf ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [gogf/gf] The - p parameter of gf does not work (Issue #3232)


1. What version of Go and system type/arch are you using?

go1.21.5 Linux/amd64

2. What version of GoFrame are you using?

V2.6.1

3. Can this issue be re-produced with the latest release?

yes

4. What did you do?

I run gf build main.go -p ./manifest/docker command in my project directory.

5. What did you expect to see?

gf tool builds the binary to the ./manifest/docker directory, but not.

6. What did you see instead?

I saw gf tool builds the binary in the project root directory.

image.png (view on web)<https://github.com/gogf/gf/assets/69077125/1d8b7add-e854-4164-9afb-61dc9c83ef68>

**Comment by chehan01** [comment]
> You got the wrong person 

Sorry, I don't understand what it means.
