### ISSUE TITLE
new version v2.6.1 is not compatible with version v2.5.6

### ISSUE THREAD

**Issue by JB-fy** [gogf/gf#3237]
**What version of `Go` and system type/arch are you using?**
go1.20.4 linux/amd64

**What version of `GoFrame` are you using?**
2.5.6升级2.6.1

**Can this bug be re-produced with the latest release?**
1、升级后POST表单请求(application/x-www-form-urlencoded 或 multipart/form-data)进入控制器后，r.GetBody()，r.GetBodyString()和r.Body都读取不到数据，只能增加中间件设置r.MakeBodyRepeatableRead(true)。这与2.5.6版本不兼容，请问后续会做兼容，还是特意改动。

2、gconv.Map()与MapDeep()方法也与前版本不兼容。特别是Map()方法参数已经改动，MapDeep()方法理应也做改动，可却并未看到。升级后filter := gconv.MapDeep(req.Filter)现在得写成这样filter := gconv.Map(req.Filter, gconv.MapOption{Deep: true, OmitEmpty: true})，且gconv.Map()在2.5.6之前默认OmitEmpty=true，现在却是false。

**Comment by gqcn** [comment]
@JB-fy Fixed, but the `OmitEmpty: true` for map converting should be manually set if necessary in new version from `v2.6.2`.

**Comment by l12ab** [comment]
关于GetBodyString()的bug仍然有，测试版本2.6.3

1、当raw当时POST时，GetBodyString()可以正常拿到raw body

2、当application/x-www-form-urlencoded提交请求时，在处理请求的controller（handler）内、后置中间件里，GetBodyString()都拿不到数据；但是，如果添加一个前置中间件，在前置中间件里，调用一次GetBodyString()，可以取到数据，并且此时controller和后置中间件也能取到数据了。
