### ISSUE TITLE
Parsing request parameter exceptions are inconsistent, and when business processing exceptions occur, they cannot be processed consistently.

### ISSUE THREAD

**Issue by shuqingzai** [gogf/gf#3239]
解析请求体错误时，panic异常code不一致，导致无法准确处理参数传递异常，令人很疑惑，为啥解析请求参数返回的异常类型不一致？？？

1. 解析 query 时，`errorCode == gcode.CodeInvalidParameter`
参考：https://github.com/gogf/gf/blob/335ccb32afe8b869d41c6d5dfa3af3c6114e2c30/net/ghttp/ghttp_request_param.go#L221
2. 解析 form 时，`errorCode == gcode.CodeInvalidRequest` 或  `errorCode == gcode.CodeInvalidParameter`
参考：
https://github.com/gogf/gf/blob/335ccb32afe8b869d41c6d5dfa3af3c6114e2c30/net/ghttp/ghttp_request_param.go#L276 与 https://github.com/gogf/gf/blob/335ccb32afe8b869d41c6d5dfa3af3c6114e2c30/net/ghttp/ghttp_request_param.go#L324
4. 解析body，`errorCode == gcode.CodeInternalError`
参考：https://github.com/gogf/gf/blob/335ccb32afe8b869d41c6d5dfa3af3c6114e2c30/net/ghttp/ghttp_request_param.go#L171

**What version of `Go` and system type/arch are you using?**

```bash
#-> % go version
go version go1.21.5 darwin/amd64
```

**What version of `GoFrame` are you using?**

```bash
-> % gf --version
v2.6.1
Welcome to GoFrame!
Env Detail:
  Go Version: go1.21.5 darwin/amd64
  GF Version(go.mod):
    github.com/gogf/gf/v2@v2.6.1
CLI Detail:
  Installed At: /Users/Code/go/bin/gf
  Built Go Version: go1.21.5
  Built GF Version: v2.6.1
Others Detail:
  Docs: https://goframe.org
  Now : 2024-01-03T16:01:15+08:00
```

**Can this bug be re-produced with the latest release?**

YES

**What did you do?**

**What did you expect to see?**

**What did you see instead?**

**Comment by gqcn** [comment]
@shuqingzai 你好，再次看了下错误码的返回，看起来返回的错误码没有毛病，也欢迎提好的建议：
1. `gcode.CodeInvalidParameter` 表示在解析提交的参数时失败了，通常是提交的参数格式不对，或者是参数中带有非法字符。
2. `gcode.CodeInvalidRequest`表示请求非法，比如服务端限制报文大小为1MB，但是上报了2MB。
3. `gcode.CodeInternalError`表示由于自身内部在处理请求的时候产生了错误，原因不明。
