### ISSUE TITLE
Encountered the following errors during installation.

### ISSUE THREAD

**Issue by Brian-su888** [gogf/gf#3249]
** go version 1.18.10**
Encountered the following errors during installation.
```bash
go install github.com/gogf/gf/cmd/gf/v2@latest
```
![image](https://github.com/gogf/gf/assets/107903219/fbf54c1b-1bdb-4494-b6b7-3c95ca48e9de)
unrecognized import path "aead.dev/minisign": parse https://aead.dev/minisign?go-get=1: no go-import meta tags ()

**Comment by gqcn** [comment]
@Brian-su888 Please try again.
