### ISSUE TITLE
The unit test found a large number of // Mya Output: and // Mya Output: , which should be errors left over from history.

### ISSUE THREAD

**Issue by nuan1989** [gogf/gf#3263]
**What version of `GoFrame` are you using?**

最新, 2.61

**Can this bug be re-produced with the latest release?**

是的, 存在

 
**What did you see instead?**

单元测试文件,  发现大量的 // Mya Output:   与 // Mya Output:  , 这是历史遗留的错误吗? 
还是说本来就是这样,  我用goland, 没有绿色小箭头按钮, 盲猜应该是错误的. 

![2](https://github.com/gogf/gf/assets/43518669/329cb8d4-ce78-41c4-b592-dc0f4b269f2f)

**Comment by oldme-git** [comment]
这是go的Example测试，可以了解一下
