### ISSUE TITLE
2.0版本获取不到真实客户端IP

### ISSUE THREAD

**Issue by linklin7** [gogf/gf#327]
代码调用：
![image](https://user-images.githubusercontent.com/7196297/64529554-c4d0e100-d33d-11e9-91ff-aea85b59ff4b.png)

nginx配置
![image](https://user-images.githubusercontent.com/7196297/64529719-111c2100-d33e-11e9-9856-4c6493dc8e21.png)

**Comment by johngcn** [comment]
@linklin7 你可以通过`r.GetClientIp()`获取
