### ISSUE TITLE
mongodb gen dao

### ISSUE THREAD

**Issue by Lyotoc** [gogf/gf#3275]
**Is your feature request related to a problem? Please describe.**
Is there any way to generate dao layer code using mongo as the database?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional**

**Comment by oldme-git** [comment]
@Lyotoc There is no plan to connect with mongo in the short term

**Comment by codedart2018** [comment]
只希望在gen dao 的时候在结体体中生成 bson
