### ISSUE TITLE
MSSQL数据库执行条件语句时出现错误

### ISSUE THREAD

**Issue by quwanxing** [gogf/gf#328]
debug信息 SELECT * FROM KF_User_ENo e INNER JOIN KF_User u ON (e.User_Id = u.UserId) INNER JOIN KF_Dept d ON (u.Dept_Id = d.DeptId) WHERE e.User_Id, [114] 无法执行，where条件后面少了一个“=@p1"

**Comment by johngcn** [comment]
@wenzi1 大佬能否看看？

**Comment by wenzi1** [comment]
@quwanxing 请提供下复现的代码，我在本地测试的没有发现这个问题

**Comment by chemsky** [comment]
This issue is hold on for a long time ,it seems that it's fixed. It is suggested to close this issue.
