### ISSUE TITLE
clickhouse Array(String) type support required

### ISSUE THREAD

**Issue by lepoch** [gogf/gf#3285]
**What version of `Go` and system type/arch are you using?**
```
v2.6.2
Welcome to GoFrame!
Env Detail:
  Go Version: go1.19.4 darwin/arm64
  GF Version(go.mod): cannot find go.mod
CLI Detail:
  Installed At: /Users/lepoch/go/bin/gf
  Built Go Version: go1.19.4
  Built GF Version: v2.6.2
Others Detail:
  Docs: https://goframe.org
  Now : 2024-01-25T15:13:05+08:00
```

**What version of `GoFrame` are you using?**
2.6.2

**Can this bug be re-produced with the latest release?**
是的

**What did you do?**
clickhouse 表结构
```
create table x(
    uid                    Int32,
    holding_portfolio      Array(String) default [],
)
```
用gen:dao 生成出来的类型是
```
type X struct {
	Uid                  int         `json:"uid"                  ` //
        HoldingPortfolio     string      `json:"holdingPortfolio"     ` //
}
```
调用：
```
data := map[string]interface{}{
		"uid": 100,
		"holding_portfolio": []string{"x", "y"},
	}
dao.Ctx(ctx).Insert(data)
```

**What did you expect to see?**

**What did you see instead?**
两个情况
1、类型不对应
2、调用Insert出错

现在语句是：`INSERT x (uid, holding_portfolio) VALUES (100, '["x","y"]') `

而clickhouse支持的是 `INSERT x (uid, holding_portfolio) VALUES (100, ['x','y']) `

**Comment by gqcn** [comment]
这个需求和`pgsql`的数组类型支持很类似，可以参考`pgsql`的这个源文件 https://github.com/gogf/gf/blob/master/contrib/drivers/pgsql/pgsql_convert.go 一个是用于生成`gen dao`的`go`数据类型，一个接口方法是实现支持往`pgsql`数据库写入数组类型：

**Comment by gqcn** [comment]
@lepoch `gen dao`支持特定数据库类型的需求和`pgsql`的数组类型支持很类似，可以参考`pgsql`的这个源文件 https://github.com/gogf/gf/blob/master/contrib/drivers/pgsql/pgsql_convert.go 的接口实现方法 `CheckLocalTypeForField` 。

实现了这个接口基本就可以实现数组的写入了，如果还不行的话也可以覆盖接口方法`ConvertValueForField`，实现在将数据提交到底层数据库引起之前做自定义的类型转换，请参考源文件 https://github.com/gogf/gf/blob/master/contrib/drivers/pgsql/pgsql_convert.go

欢迎感兴趣的小伙伴参与`PR`建设。
