### ISSUE TITLE
api, cannot use &ControllerV1{} (value of type *ControllerV1) will appear.

### ISSUE THREAD

**Issue by swurtheone** [gogf/gf#3288]
api:
```
type DeleteTestReq struct {
	g.Meta  `path:"/delete/test" tags:"deleteTest" method:"get" summary:"删除测试数据"`
	Account string `json:"account" v:"required" dc:"账号"`
}

type DeleteTestRes struct {
}

```
**gf gen ctrl后运行go  run main.go会出现：**
![image](https://github.com/gogf/gf/assets/31538827/67c0f104-9057-4b16-b897-4cd03c34aa52)

似乎**_DeleteTes_**t是个关键词，修改成其他的例如TestDelete、DeleteData就没有问题：

gf版本：
```
GoFrame CLI Tool v2.5.6, https://goframe.org
GoFrame Version: v2.5.7 in current go.mod
```

**Comment by oldme-git** [comment]
@swurtheone 不能使用 XxxTest 当作结构体名称哦，不然生成的控制器文件会被当作 go 的测试文件
You can't use XxxTest as struct name, otherwise, the generated controller file will be treated as go's test file
