### ISSUE TITLE
建议针对PUT请求方法增加GetPutString/GetPutMap

### ISSUE THREAD

**Issue by macnie** [gogf/gf#330]
定义路由：PUT， 没有对应的方法来解析。每次都要自己写。虽然有办法解决，但站在框架角度上，还是有完善的HTTP方法处理比较好。

比如  PUT:/user/password  ,  使用POSTMAN 提交的数据，使用 GetRawString打印出来是：id=1&password=e10adc3949ba59abbe56e057f20f883e
每次都要使用gstr有个Parse再解析一下。

建议像GetPostString 一样，增加 GetPutString ， GetPutMap ， GetPutStruct

**Comment by johngcn** [comment]
@macnie 请更新到最新版本试试，使用`GetMap`即可。

**Comment by macnie** [comment]
我觉得PUT方法，使用GetMap 这种命名不严谨。
