### ISSUE TITLE
ORM chain operation-query cache problem summary

### ISSUE THREAD

**Issue by oldme-git** [gogf/gf#3313]
# 不同 SQL 的覆盖问题
```
r, _ := db.Table("user").Cache(time.Hour, "vip-user").Where("uid", 1).One()
r, _ := db.Table("user").Cache(time.Hour, "vip-user").Where("uid", 2).One()
```
实测 uid = 2 不会覆盖 uid = 1

# ClearCache 和 ClearCacheAll
```
// ClearCache removes cached sql result of certain table.
func (c *Core) ClearCache(ctx context.Context, table string) (err error) {
	return c.db.GetCache().Clear(ctx)
}

// ClearCacheAll removes all cached sql result from cache
func (c *Core) ClearCacheAll(ctx context.Context) (err error) {
	return c.db.GetCache().Clear(ctx)
}
```

两种清除方式一样， `ClearCache` 的 `table` 参数不生效，如果使用者没注意，这可能会带来缓存击穿问题

# 清除缓存问题
`ClearCacheAll` 使用 redis 缓存时，会执行 **flushdb** 命令，这太危险。
文档中推荐使用不同的 redis db 管理缓存，但是在 [ORM链式操作-查询缓存](https://goframe.org/pages/viewpage.action?pageId=1114346) 中没有标注。

# 查询缓存的 key 值问题
GetCache() 获取缓存对象后，key 值需要携带 `SelectCache:`
gdb.DB().GetCache().get(ctx, "vip-user") // remove fail
gdb.DB().GetCache().get(ctx, "SelectCache:vip-user") // ok

**Comment by langbin522** [comment]
你的name都是一样的肯定是覆盖了。

**Comment by gqcn** [comment]
@oldme-git 我看这里面主要是`ClearCache`和`ClearCacheAll`的问题，这个问题我以为已经修复了，其实还没。具体逻辑是可以先用`Keys`取出来后遍历检测来删除。这块由我来统一处理吧。
