### ISSUE TITLE
2.6.3 nil and empty arrays should not be ignored when inserting and updating JSON fields

### ISSUE THREAD

**Issue by macnie** [gogf/gf#3317]
数据表有JSON字段类型时，保存数据，数据为空数组时，2.6版本会忽略此字段。但MYSQL中，JSON字段是必须赋值的。就造成很大困扰。

**Comment by macnie** [comment]
这些BUG什么时候能修复呢

**Comment by macnie** [comment]
比如： dao.User.Ctx(ctx).Insert(do.User{
Id:1,
Name:"小李",
Files:[]string{},
})

这时，生成的SQL语句为：insert into user (id,name) values(1,"小李") 没有files字段。但files字段是JSON字段，必须赋值。所以SQL报错。

**Comment by houseme** [comment]
这个地方很诡异，
如何判断这个json是`[]` 或 `{}` ，代码如何赋值呢？
根据结构体匹配字段的类型，再赋值默认值吗？
是不是可以在数据库字段设置默认值处理

**Comment by gqcn** [comment]
@macnie 另外一些`not null`的字段也不能直接过滤空值。我看你的示例是使用了`do`对象，该对象只会过滤`nil`值，不会过滤空值，所以你给一个空值即可。
