### ISSUE TITLE
URL request input-how to cancel complex parameters

### ISSUE THREAD

**Issue by ericzhao007** [gogf/gf#3318]
相关文档：https://goframe.org/pages/viewpage.action?pageId=1114197
在使用规范路由的场景下，如何取消复杂参数的支持。
问题原因：在与前端配合过程中，前端使用了formdata请求了json也解析成功了，问题原因是框架自动适配，如何取消这个适配让前端必须传json格式

**Comment by ericzhao007** [comment]
> @ericzhao007 可以在路由中定义一个字段用作接受参数，并且设置为 json 校检 Maybe you can usring one field to receive JSON data and set it field valid for `json`
> 
> ```
> type DemoReq struct {
> 	g.Meta `path:"/"`
> 	JDemo      string `v:"json"`
> }
> ```

这是对字段JDemo的值进行json校验吧，我是想强制限制接口只能传Content-Type: application/json

**Comment by oldme-git** [comment]
@ericzhao007 针对这种需求，可以使用前置中间件来判断请求头。
Mabye you can usring `Middleware`
[https://goframe.org/pages/viewpage.action?pageId=55289881](https://goframe.org/pages/viewpage.action?pageId=55289881)

```
func (s *sMiddleware) Demo(r *ghttp.Request) {
	r.Middleware.Next()
	var mine = r.Request.Header.Get("Content-Type")
	if gstr.ToLower(mine) != "application/json" {
		fmt.Println("error: no application/json")
	}
}
group.Middleware(service.Middleware().Demo)
```
