### ISSUE TITLE
2.6.3Update or insert datagram not gdb.getSoftFieldNameAndTypeCacheItem

### ISSUE THREAD

**Issue by langbin522** [gogf/gf#3319]
版本:2.6.3
更新update()或者insert()概率性发生
interface conversion: interface {} is string, not gdb.getSoftFieldNameAndTypeCacheItem
执行下面更新操作会报出上面错误
func (s *sProjectSetting) Update(ctx context.Context, id int64, in g.Map) (err error) {

	_, err = dao.ProjectSetting.Ctx(ctx).Where("id", id).Data(in).Update()

	if err != nil {

		err = myerror.SqlErrorWithLog(ctx, err, "更新失败")
		return
	}
	return
}

**Comment by langbin522** [comment]
![Uploading 微信图片_20240221204013.png…]()

**Comment by jtddsoft** [comment]
我也遇到相同问题 似乎是gdb_model_soft_time.go里有bug

**Comment by langbin522** [comment]
> 我也遇到相同问题 似乎是gdb_model_soft_time.go里有bug

我退回版本就好了。用2.6.3就出问题。。。

**Comment by gqcn** [comment]
@langbin522 @jtddsoft @walkmiao I cannot reproduce this issue, would you please provide minimum runnable codes that can reproduce this issue?

**Comment by wangyugits** [comment]
数据库配置缓存使用，可以复现
