### ISSUE TITLE
nacos-sdk-go is v1 not v2

### ISSUE THREAD

**Issue by lrioo** [gogf/gf#3320]
Why `github.com/gogf/gf/contrib/config/nacos/v2` with v2 major version, but used `github.com/nacos-group/nacos-sdk-go`, not `github.com/nacos-group/nacos-sdk-go/v2`?
为什么 `github.com/gogf/gf/contrib/config/nacos/v2` 具有 v2 主要版本，但使用 `github.com/nacos-group/nacos-sdk-go`，而不是 `github.com/nacos-group /nacos-sdk-go/v2`？

Any plan to support `github.com/nacos-group/nacos-sdk-go/v2` ?
有计划支持 `github.com/nacos-group/nacos-sdk-go/v2` 吗？

**Comment by lrioo** [comment]
And, why `github.com/gogf/gf/contrib/registry/nacos/v2` used the `github.com/joy999/nacos-sdk-go`, not `github.com/nacos-group/nacos-sdk-go/v2`? 

The former is  forked from the later. What is the difference between the two package?

**Comment by houseme** [comment]
欢迎提pr

**Comment by lrioo** [comment]
> 欢迎提pr

I hope I can figure out the reason before deciding whether to submit a PR. And nacos-sdk-go has incompatible changes from v1 to v2. How to upgrade it shuold think twice.
我希望能了解清楚背景，再看是否要提 PR。 nacos-sdk-go 从 v1 到 v2 有不兼容的改动，如何升级也是一个问题。

**Comment by houseme** [comment]
> And, why `github.com/gogf/gf/contrib/registry/nacos/v2` used the `github.com/joy999/nacos-sdk-go`, not `github.com/nacos-group/nacos-sdk-go/v2`? 而且，为什么 `github.com/gogf/gf/contrib/registry/nacos/v2` 使用 `github.com/joy999/nacos-sdk-go`，而不是 `github.com/nacos-group/nacos-sdk-go/v2`？
> 
> The former is forked from the later. What is the difference between the two package? 前者是从后者fork出来的。 两个包有什么区别？

找这个库的作者沟通一下，原来是修复了一个问题，才使用的fork版本。

**Comment by joy999** [comment]
gf的nacos的config与registry是由两个作者维护的。而config要先于registry出现。所以config的版本要旧些。而registry中之所以使用fork分支，是因为它有一个BUG，会导致在CI时出现资源争夺的问题，而过不去测试。我给他们提了PR，却一直没有合并，这是不得以的做法，一旦他们合并或解决了这个问题。我们便弃用fork分支。
