### ISSUE TITLE
Is it i18n support fallback fucntion?

### ISSUE THREAD

**Issue by weishirongzhen** [gogf/gf#3336]
For example, server only support "en" and "ja",  and server get lang value from header 
``` go
func (s *sMiddleware) I18n(r *ghttp.Request) {
	r.SetCtx(gi18n.WithLanguage(r.Context(), r.GetHeader("lang")))
	r.Middleware.Next()
}

```

if api caller set header["lang"] = "zh-CN", server will return messsage like "{#name_already_token}%!!(MISSING)(EXTRA string=john)"

how to auto fallback to "en" when user set lang except "en" and "ja"?

**Comment by Henriqu331** [comment]
buscarei a resposta ok

**Comment by Henriqu331** [comment]
I'll look for the answer ok
