### ISSUE TITLE
 cannot find database driver for specified database type "sqlite", did you misspell type name "sqlite" or forget importing the database driver? 

### ISSUE THREAD

**Issue by hanwei88** [gogf/gf#3341]
go版本: 1.22
gf: v2.6.3
系统 linux
我已经导入了驱动，为什么还是会报这个错误？
![image](https://github.com/gogf/gf/assets/93665931/0bb437dd-65d1-42bc-9311-98b930c65888)
![image](https://github.com/gogf/gf/assets/93665931/5dc834bc-45ed-4d20-8387-4c6bc935312f)

**Comment by hailaz** [comment]
GODEBUG=inittrace=1 go run main.go
自己查一下，启动顺序不对也会报错。必须保证调用前引入
