### ISSUE TITLE
Emergency help, the project code will be cleared after executing gf gen dao

### ISSUE THREAD

**Issue by jinyuanqing** [gogf/gf#3345]
执行gf gen dao 后代码都被清空了.控制器,服务,逻辑,模型等文件夹代码都被清空了.这是啥问题呀?qq 2838386460,在线求助.执行命令无报错信息.使用的工具是goland

gf version
v2.6.3
Welcome to GoFrame!
Env Detail:
Go Version: go1.22.0 windows/amd64
GF Version(go.mod): cannot find go.mod
CLI Detail:
Installed At: C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps\gf.exe
Built Go Version: go1.20.8
Built GF Version: v2.6.3
Git Commit: 2024-02-07 17:11:36 https://github.com/gogf/gf/commit/d64a31fd1aa490ff9136c1776806f197d86c38a6
Built Time: 2024-02-07 17:13:07
Others Detail:
Docs: https://goframe.org/
Now : 2024-03-03T08:46:14+08:00

**What version of `GoFrame` are you using?**

**Can this bug be re-produced with the latest release?**

**What did you do?**

**What did you expect to see?**

**What did you see instead?**

**Comment by jinyuanqing** [comment]
help me

**Comment by jinyuanqing** [comment]
If there's anyone left to help me

**Comment by jinyuanqing** [comment]
Still no feedback

**Comment by oldme-git** [comment]
@jinyuanqing We need more info, Please.

**Comment by jinyuanqing** [comment]
> @jinyuanqing We need more info, Please.

you need what?我的邮箱2838386460@qq.com,qq是2838386460

**Comment by gqcn** [comment]
@jinyuanqing 请尝试通过`gf up -a`命令升级使用最新版本试试。

**Comment by jinyuanqing** [comment]
这个问题肯定存在.我也不找了.项目重写了.当我再次验证这个问题时候,没有重复复现.记着使用命令时一定要做下备份
