### ISSUE TITLE
ghttp.HookAfterOutput will cause panic

### ISSUE THREAD

**Issue by shuqingzai** [gogf/gf#3361]
如果在中间件中没有执行解析 消息体 ，在 ghttp.Hook 相关事件中读取消息体会引发 `panic`

```go
package main

import (
	"fmt"
	"net/http"

	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/net/ghttp"
)

func main() {
	srv := g.Server()
	srv.BindHookHandler("/*any", ghttp.HookAfterOutput, func(r *ghttp.Request) {
		fmt.Println("------------------------------------------ response after output ------------------------------------------")
		g.Dump(r.GetBody())
		fmt.Println("------------------------------------------ response after output ------------------------------------------")
	})
	srv.BindHandler("POST:/hello", func(r *ghttp.Request) {
		fmt.Println("------------------------------------------ request handler ------------------------------------------")
		// 解析消息体
		r.GetBody() // 如果注释这行代码，会引发 panic
		r.Response.WriteStatus(http.StatusOK, "hello world")
		fmt.Println("------------------------------------------ request handler ------------------------------------------")
	})
	srv.SetPort(8199)
	srv.Run()
}
```

请求示例

1. 访问已注册的路由，并且测试注释/不注释 `r.GetBody()`

```bash
curl -XPOST http://127.0.0.1:8199/hello -d '{"name": "jack"}'
```

2. 直接访问不存在的路由 `/hello2` ，也会导致 `panic`

因为没有匹配到路由，导致没有中间件解析消息体，引发 panic

没有匹配路由时，只会写入 `Status Code = 400` 到 Response 中，在 Hook 中，我应该怎么识别当前访问是否匹配了路由执行业务逻辑了？？

```bash
curl -XPOST http://127.0.0.1:8199/hello2 -d '{"name": "jack"}'
```

**What version of `Go` and system type/arch are you using?**

```bash
#-> % go version
go version go1.21.7 darwin/amd64
```

**What version of `GoFrame` are you using?**

```bash
#-> % gf version
v2.6.4
Welcome to GoFrame!
Env Detail:
  Go Version: go1.21.7 darwin/amd64
  GF Version(go.mod):
    github.com/gogf/gf/v2@v2.6.4
CLI Detail:
  Installed At: /Code/go/bin/gf
  Built Go Version: go1.21.7
  Built GF Version: v2.6.4
Others Detail:
  Docs: https://goframe.org
  Now : 2024-03-11T13:36:04+08:00
```

**Can this bug be re-produced with the latest release?**

**What did you do?**

**What did you expect to see?**

**What did you see instead?**

**Comment by hailaz** [comment]
在流程HookAfterOutput的时候，body已经被关闭了。所以此时读取body会触发panic。那为什么调用过r.GetBody()不会报错，因为r.GetBody()内部做了缓存处理。已经读过一次，第二次并不会去读body。

不知道你是不是在找自定义处理404的功能https://goframe.org/pages/viewpage.action?pageId=1114358

**Comment by wln32** [comment]
@shuqingzai 
<ol>
<li>如果没有提前调用GetBody()方法，在HookAfterOutput下调用会panic
      是因为在这个之前gf已经调用了Flush，需要把数据写到，
      而Flush会关闭请求连接并把body中的内容全部丢弃，所以会无法获取到</li>

<li>没有匹配到路由gf会设置Status为404，你可以根据这个判断</li>
</ol>

**Comment by shuqingzai** [comment]
> @shuqingzai
> 
> 1. 如果没有提前调用GetBody()方法，在HookAfterOutput下调用会panic
>          是因为在这个之前gf已经调用了Flush，需要把数据写到，
>          而Flush会关闭请求连接并把body中的内容全部丢弃，所以会无法获取到
> 2. 没有匹配到路由gf会设置Status为404，你可以根据这个判断

除了 404 还有别的依据吗？我怎么区分 404 是框架抛出的还是我自己抛出的？？我的业务中查找数据库，找不到也是 404

**Comment by shuqingzai** [comment]
> @shuqingzai
> 
> 1. 如果没有提前调用GetBody()方法，在HookAfterOutput下调用会panic
>          是因为在这个之前gf已经调用了Flush，需要把数据写到，
>          而Flush会关闭请求连接并把body中的内容全部丢弃，所以会无法获取到
> 2. 没有匹配到路由gf会设置Status为404，你可以根据这个判断
@wln32 
对于第一个点，不是我不调用 `GetBody()` ，而是在标准路由中，如果用户访问不存在的路由时，框架就不会解析( 不调用 GetBody() ) ，但是 Hook 是一定会执行的，我是在 hook 中记录请求信息，所以需要读取 body 导致 panic ，这种情况我改如何处理？？

**Comment by shuqingzai** [comment]
> 在流程HookAfterOutput的时候，body已经被关闭了。所以此时读取body会触发panic。那为什么调用过r.GetBody()不会报错，因为r.GetBody()内部做了缓存处理。已经读过一次，第二次并不会去读body。
> 
> 不知道你是不是在找自定义处理404的功能https://goframe.org/pages/viewpage.action?pageId=1114358

@hailaz 谢谢你的回复

我的问题是如何区分 body 是否被解析，如果不被解析，我就不读了，就不会引发 panic ，你说的是使用 404 判断，但是 404 有可能是我业务抛出的，数据找不到，我也会抛出 404 ，在 hook 中无法区分是框架还是我自己抛出的

**Comment by shuqingzai** [comment]
如果是找不到路由，是否可以添加别的标识符，用户可以根据找不到路由做出相应的处理 @hailaz @wln32

**Comment by wln32** [comment]
> 如果是找不到路由，是否可以添加别的标识符，用户可以根据找不到路由做出相应的处理 @hailaz @wln32

@shuqingzai 
你可以调用这个SetCtxVar(key,val) ，当你的业务抛出404时，可以自定义一个ctx的key，然后在hook里面判断有没有对应的key，
如果没有就是框架抛出的
