### ISSUE TITLE
parseCommand Some command parsing and processing exceptions under Windows

### ISSUE THREAD

**Issue by hailaz** [gogf/gf#3370]
v2.6.4 gf build用到以下功能

例如在Windows下使用gproc.ShellExec(ctx, cmd)
执行命令`git log -1 --format="%cd %H" --date=format:"%Y-%m-%d %H:%M:%S"`时`--format="%cd %H"`参数会被切割开
导致报错
```
fatal: ambiguous argument '%H"': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

https://github.com/gogf/gf/blob/1793bf0863ca07ca4ac89654230fc3b06cfa991a/os/gproc/gproc_shell.go#L66

**Comment by wln732** [comment]
如果是windows系统的话,是否可以在process.NewProcess的函数里面添加一个判断,在初始化process后面，直接使用原生的参数不经过处理
```go
	process.SysProcAttr = &syscall.SysProcAttr{}
	process.SysProcAttr.CmdLine = path + " " + gstr.Join(args, " ")

**Comment by wln732** [comment]
> 如果是windows系统的话,是否可以在process.NewProcess的函数里面添加一个判断,在初始化process后面，直接使用原生的参数不经过处理
> 
> ```go
> 	process.SysProcAttr = &syscall.SysProcAttr{}
> 	process.SysProcAttr.CmdLine = path + " " + gstr.Join(args, " ")
> ```

需要把parseCmd函数处理下，直接返回cmd即可
