### ISSUE TITLE
希望 gconv.Slice增加更多的类型

### ISSUE THREAD

**Issue by 15951836388** [gogf/gf#338]
比如 int32 int64  uint64 等

**Comment by johngcn** [comment]
@15951836388 `gconv`的`Slice`转换只提供了最常用的类型，其他类型欢迎提PR。

**Comment by 15951836388** [comment]
func Int32s(i interface{}) []int32 {
	if i == nil {
		return nil
	}
	if r, ok := i.([]int32); ok {
		return r
	} else {
		array := make([]int32, 0)
		switch value := i.(type) {
		case []string:
			for _, v := range value {
				array = append(array, Int32(v))
			}
		case []int8:
			for _, v := range value {
				array = append(array, Int32(v))
			}
		case []int16:
			for _, v := range value {
				array = append(array, Int32(v))
			}
		case []int32:
			for _, v := range value {
				array = append(array, Int32(v))
			}
		case []int64:
			for _, v := range value {
				array = append(array, Int32(v))
			}
		case []uint:
			for _, v := range value {
				array = append(array, Int32(v))
			}
		case []uint8:
			for _, v := range value {
				array = append(array, Int32(v))
			}
		case []uint16:
			for _, v := range value {
				array = append(array, Int32(v))
			}
		case []uint32:
			for _, v := range value {
				array = append(array, Int32(v))
			}
		case []uint64:
			for _, v := range value {
				array = append(array, Int32(v))
			}
		case []bool:
			for _, v := range value {
				array = append(array, Int32(v))
			}
		case []float32:
			for _, v := range value {
				array = append(array, Int32(v))
			}
		case []float64:
			for _, v := range value {
				array = append(array, Int32(v))
			}
		case []interface{}:
			for _, v := range value {
				array = append(array, Int32(v))
			}
		case [][]byte:
			for _, v := range value {
				array = append(array, Int32(v))
			}
		default:
			return []int32{Int32(i)}
		}
		return array
	}
}

**Comment by johngcn** [comment]
@15951836388 你可以提个PR啊

**Comment by 15951836388** [comment]
pr流程太复杂了，搞得晕
