### ISSUE TITLE
Some thoughts on the XXXReq structure tag under the api package

### ISSUE THREAD

**Issue by wln732** [gogf/gf#3385]
当前XXXReq结构体里面的path 和method是否可以合并到一起去,就像函数路由那样，比如
```go
g.Meta   `path:"/admin/employee/login" method:"post" `
```
变更为
```go
g.Meta   `POST:"/admin/employee/login" `
```

**Comment by oldme-git** [comment]
@wln732 
规范路由可以注册多个哦
Norm router can register multiple method.
```
g.Meta   `path:"/admin/employee/login" method:"post,get" `
```

**Comment by wln732** [comment]
> @wln732 规范路由可以注册多个哦 Norm router can register multiple method.
> 
> ```
> g.Meta   `path:"/admin/employee/login" method:"post,get" `
> ```

我说的是简单场景下的，可以简化一些，不用每个都写method，或者可以改成以下写法，在路径前面加
```go
g.Meta `path:"GET:/admin/employee/login" `
```

**Comment by oldme-git** [comment]
@gqcn 强哥你看看呢

**Comment by oldme-git** [comment]
@gqcn 我觉得这样实现没什么特别的优势，而且底层还是通过反射来获取 `tag` 的，在实现上会带来不小的麻烦

**Comment by wln732** [comment]
> @gqcn 我觉得这样实现没什么特别的优势，而且底层还是通过反射来获取 `tag` 的，在实现上会带来不小的麻烦

这有什么麻烦，tag一次反射就能获取到所有的了，以method为准，method没写，就去找path的，没有path，
就找那几个http的mehtod开头的就行了

**Comment by wln732** [comment]
目前我已经实现了效果，
=====================
g.Meta   `GET:"/hello" method:"get" `
	&ensp;&ensp;&ensp;&ensp;第一种情况 GET:"/hello" 和 method同时存在，以谁为准
	&ensp;&ensp;&ensp;&ensp;我的解决思路思路是请求方法以method tag为准，uri还是以前面的为准
	&ensp;&ensp;&ensp;&ensp;或者也可以uri和method都以前面的为主，忽略后面的method tag的值


g.Meta   `GET:"/hello" `
	&ensp;&ensp;&ensp;&ensp;第二种情况正常解析path如果没有的话，就使用GET,POST这种形式的解析

![req1](https://github.com/gogf/gf/assets/49137144/c300b401-6175-447e-b796-57b95f3f029c)
![cmd1](https://github.com/gogf/gf/assets/49137144/89430402-a2c7-4d65-a798-8de4514ec5e7)
==============================================================

![req2](https://github.com/gogf/gf/assets/49137144/6b5a362d-fd86-41f6-b421-80cdf9007ebf)
![cmd2](https://github.com/gogf/gf/assets/49137144/c67e5c10-d92f-4228-8a5b-bc9d177f6540)
===========================================================

![req3](https://github.com/gogf/gf/assets/49137144/a63eb6c0-b011-4200-8b65-2bc7e5bdd09a)
![cmd3](https://github.com/gogf/gf/assets/49137144/fc2223da-41c2-4179-ba18-5b4a91cb06f6)

**Comment by oldme-git** [comment]
@wln732 👍提个PR吧，让强哥看看

**Comment by wln732** [comment]
> @wln732 👍提个PR吧，让强哥看看
g.Meta GET:"/hello" method:"post" 
 这种情况我还是觉得 统一用前面的好点，method=get，uri=/hello这种的，只有path tag 存在时，method tag才生效

**Comment by wln732** [comment]
@gqcn 还需要同步实现openapi的代码
