### ISSUE TITLE
1.91 log的一些问题

### ISSUE THREAD

**Issue by 15951836388** [gogf/gf#339]
1.log.err 的调用堆栈，没有排除gf框架本身的堆栈，这对用户是非必要的

2.log 开启行号后，打印出来的行号，全是错的 。全显示 extern.go:179

github太卡，图传不上来

**Comment by johngcn** [comment]
@15951836388 第一个问题是个bug，没考虑到go module使用时路径中会带版本号的情况，我修复一下，这两天会发个小版本。第二个问题我没有复现，如下：
![image](https://user-images.githubusercontent.com/26347176/65215333-c63d9e80-dadf-11e9-8d00-c579a98019de.png)
