### ISSUE TITLE
Missing command-line argument.

### ISSUE THREAD

**Issue by clh021** [gogf/gf#3390]
**What version of `Go` and system type/arch are you using?**

`Go Version: go1.21.4 linux/amd64`

**What version of `GoFrame` are you using?**

`require github.com/gogf/gf/v2 v2.6.4`

**Can this bug be re-produced with the latest release?**
Yes.
> 是的，最新发行版仍然可以重现该问题

**What did you do?**

```go
package main

import (
	"context"

	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gcmd"
	"github.com/gogf/gf/v2/os/gctx"
)

type Command struct {
	*gcmd.Command
}

var (
	Test = cTest{}
)

type cTest struct {
	g.Meta `name:"index" ad:"test"`
}

type cInput struct {
	g.Meta `name:"index"`
	A      string `short:"a" name:"aa" brief:"aa"`
	B      string `short:"b" name:"bb" brief:"bb"`
}

type cOutput struct{}

func (c cTest) Index(ctx context.Context, in cInput) (out *cOutput, err error) {
	g.Dump(in)
	return
}

func main() {
	var (
		ctx = gctx.GetInitCtx()
	)
	root, err := gcmd.NewFromObject(Test)
	if err != nil {
		panic(err)
	}
	command := &Command{root}
	command.RunWithError(ctx)
}
```
To facilitate comparison, it is recommended to use the command `gf run ./main.go -a "-a aaa -b bbb"` for debugging purposes.
为了方便对比，建议使用 `gf run ./main.go -a "-a aaa -b bbb"` 命令进行调试操作。

**What did you expect to see?**
Modifying `B` in `cInput` to `Be` or any other content will cause the loss of the parameter value `bbb`.
Modifying the short options corresponding to `A` and `B` in `cInput` such that `A` corresponds to `b`, and `B` corresponds to `a`, would result in the parameter value `aaa` still being associated with `A`, while the parameter `bbb` remains with `B`.

修改 cInput 中的 `B` 为 `Be` 或其它内容，将丢失参数值 `bbb`。
修改 cInput 中的 `A`,`B` 对应的 short，使其调换 为 `A`对应`b`, `B`对应 `a`，参数值 `aaa`仍在 `A`上，参数 `bbb` 仍在 `B` 上。

**What did you see instead?**
After modifying `B` in `cInput` to `Be` or any other content, the original parameter value `bbb` that could be received should still be accepted without being affected.
When modifying the short options corresponding to `A` and `B` in `cInput` such that `A` corresponds to `b`, and `B` corresponds to `a`, the parameter value `aaa` would now be associated with `B`, while the parameter `bbb` is on `A`.

修改 cInput 中的 `B` 为 `Be` 或其它内容后，原来可以接收的参数值 `bbb`，仍然可以顺利接收，不受影响。
修改 cInput 中的 `A`,`B` 对应的 short，使其调换 为 `A`对应`b`, `B`对应 `a`，参数值 `aaa`在 `B`上，参数 `bbb` 在 `A` 上。

**Comment by wln732** [comment]
貌似 -a "这里是你自定义的参数" ，可以运行gf run -h查看下
![1](https://github.com/gogf/gf/assets/49137144/ad619c97-0ba6-40f1-8c67-cf8d2a0b18c4)

**Comment by wln732** [comment]
这个bug是在解析完参数给结构体字段赋值的时候导致的

**Comment by wln732** [comment]
我复测了几个BUG出来
============================
首先这是我的代码
```go
type Command struct {
	*gcmd.Command
}

var (
	Test = cTest{}
)

type cTest struct {
	g.Meta `name:"index" ad:"test"`
}

type cInput struct {
	g.Meta `name:"index"`
	Name   string `short:"n" name:"age" brief:"我是name字段"`
	Age    string `short:"a" name:"name" brief:"我是age字段"`
}

type cOutput struct{}

func (c cTest) Index(ctx context.Context, in cInput) (out *cOutput, err error) {
	g.Dump(in)
	return
}

func main() {
	root, err := gcmd.NewFromObject(Test)
	if err != nil {
		panic(err)
	}
	command := &Command{root}
	command.Run(gctx.GetInitCtx())
}
```
下面贴测试结果
====================
![q1](https://github.com/gogf/gf/assets/49137144/ae614995-11ed-4b04-a8db-d0eb6729706c)
![q2](https://github.com/gogf/gf/assets/49137144/ea78785c-3c76-458c-ae7b-3ee05d86500f)
![q3](https://github.com/gogf/gf/assets/49137144/fafb23ba-2e36-4509-baef-bc46f4151d3a)
![q5](https://github.com/gogf/gf/assets/49137144/01081bb5-6eed-4921-8473-85592ae1f2f3)
![q6](https://github.com/gogf/gf/assets/49137144/4d617c26-52f2-460e-84de-79dd23aeb92c)
![q7](https://github.com/gogf/gf/assets/49137144/212c0b77-fb6d-4f5a-932d-939856c47981)

**Comment by clh021** [comment]
我刚刚进一步排查，确定了问题出在这一行代码中:
![image](https://github.com/gogf/gf/assets/1754391/6ded9a58-aa58-4427-bb24-bd9514def469)
![image](https://github.com/gogf/gf/assets/1754391/4ceb1e0a-9ee6-40b0-9726-da0d3fac8a1c)
以下是输出，说明数据在经过这一行代码时，进行了赋值操作，部分数据成功获取，部分数据丢失。
![image](https://github.com/gogf/gf/assets/1754391/8b998e8e-3cab-4e47-ac56-8e0ae9772d35)

**Comment by wln732** [comment]
你输入的数据是成功解析了的，问题就是出现在你红线标记哪里，再给字段赋值的时候，由于你tag的值和结构体字段重名了，导致错误解析

**Comment by clh021** [comment]
> 你输入的数据是成功解析了的，问题就是出现在你红线标记哪里，再给字段赋值的时候，由于你tag的值和结构体字段重名了，导致错误解析

经过又一轮调试，发现：scan 赋值的部分，顺序可能没有严格按照参数名进行匹配。
我上面提的问题有两个，其中一个是 a 和 b 的 short 定义互换，但是结构体中的赋值没有换过来，但是刚刚发现，如果把结构体中的顺序 B 放在 A 前面，得到的值就正确了。

**Comment by wln732** [comment]
> > 你输入的数据是成功解析了的，问题就是出现在你红线标记哪里，再给字段赋值的时候，由于你tag的值和结构体字段重名了，导致错误解析
> 
> 经过又一轮调试，发现：scan 赋值的部分，顺序可能没有严格按照参数名进行匹配。 我上面提的问题有两个，其中一个是 a 和 b 的 short 定义互换，但是结构体中的赋值没有换过来，但是刚刚发现，如果把结构体中的顺序 B 放在 A 前面，得到的值就正确了。

我正在试图重新实现这部分

**Comment by clh021** [comment]
以下是刚刚进一步精简出来的重现代码
```go
package main

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/util/gconv"
)

type cInput struct {
	A      string `short:"a" name:"aa" brief:"aa"`
	B      string `short:"b" name:"bb" brief:"bb"`
}

func main() {
	data := map[string]interface{}{
		"a":  "aaa",
		"aa": "bbb",
		"b":  "bbb",
		"bb": "aaa",
	}
	p := cInput{}
	err := gconv.Struct(data, &p)
	if err != nil {
		g.Dump(err)
	} else {
		g.Dump(p)
	}
}
```
原因可能找到了，（以上代码测试方法一样）
 scan 函数本身也没有问题，问题在与 scan 转换时对应的是结构体的名称，而非 short 或 name。
所以应该在 command 和 scan 之间有一个 转换关系。

**Comment by clh021** [comment]
> > > 你输入的数据是成功解析了的，问题就是出现在你红线标记哪里，再给字段赋值的时候，由于你tag的值和结构体字段重名了，导致错误解析
> > 
> > 
> > 经过又一轮调试，发现：scan 赋值的部分，顺序可能没有严格按照参数名进行匹配。 我上面提的问题有两个，其中一个是 a 和 b 的 short 定义互换，但是结构体中的赋值没有换过来，但是刚刚发现，如果把结构体中的顺序 B 放在 A 前面，得到的值就正确了。
> 
> 我正在试图重新实现这部分

您是框架核心开发者吗？我本想尝试提交 PR，但是对 gogf 的内部结构还不够熟悉，很多地方不清楚为什么那样实现，不敢改动。

**Comment by wln732** [comment]
> 以下是刚刚进一步精简出来的重现代码
> 
> ```go
> package main
> 
> import (
> 	"github.com/gogf/gf/v2/frame/g"
> 	"github.com/gogf/gf/v2/util/gconv"
> )
> 
> type cInput struct {
> 	A      string `short:"a" name:"aa" brief:"aa"`
> 	B      string `short:"b" name:"bb" brief:"bb"`
> }
> 
> func main() {
> 	data := map[string]interface{}{
> 		"a":  "aaa",
> 		"aa": "bbb",
> 		"b":  "bbb",
> 		"bb": "aaa",
> 	}
> 	p := cInput{}
> 	err := gconv.Struct(data, &p)
> 	if err != nil {
> 		g.Dump(err)
> 	} else {
> 		g.Dump(p)
> 	}
> }
> ```
> 
> 原因可能找到了，（以上代码测试方法一样） scan 函数本身也没有问题，问题在与 scan 转换时对应的是结构体的名称，而非 short 或 name。 所以应该在 command 和 scan 之间有一个 转换关系。

具体的实现

> > > > 你输入的数据是成功解析了的，问题就是出现在你红线标记哪里，再给字段赋值的时候，由于你tag的值和结构体字段重名了，导致错误解析
> > > 
> > > 
> > > 经过又一轮调试，发现：scan 赋值的部分，顺序可能没有严格按照参数名进行匹配。 我上面提的问题有两个，其中一个是 a 和 b 的 short 定义互换，但是结构体中的赋值没有换过来，但是刚刚发现，如果把结构体中的顺序 B 放在 A 前面，得到的值就正确了。
> > 
> > 
> > 我正在试图重新实现这部分
> 
> 您是框架核心开发者吗？我本想尝试提交 PR，但是对 gogf 的内部结构还不够熟悉，很多地方不清楚为什么那样实现，不敢改动。

我跟你一样呢，不是核心开发者，只是无聊学习下而已，我目前已经实现的差不多了已经，测试用例都能跑过

**Comment by clh021** [comment]
> 我跟你一样呢，不是核心开发者，只是无聊学习下而已，我目前已经实现的差不多了已经，测试用例都能跑过

测试用例可能需要再针对新的补充一点，把这次的问题发现都包含进去。感谢您帮助我一起发现了这个问题！👍

**Comment by clh021** [comment]
我目前是通过为所有参数附上默认值来避开这个问题的。

**Comment by gqcn** [comment]
我看看呢。

**Comment by gqcn** [comment]
https://github.com/gogf/gf/pull/3429
