### ISSUE TITLE
About gocnv.Scan custom mapping rules

### ISSUE THREAD

**Issue by wln732** [gogf/gf#3391]
测试代码
=====
```go
type TestData struct {
	Name string
	Age  string
}

func main() {
	data := map[string]any{
		"a":    "123",
		"name": "123",
	}
	type dataMapKey = string
	type structFieldName = string
	mapping := map[dataMapKey]structFieldName{
		"a":    "Age",
		"name": "Age",

		"age": "Name",
		"n":   "Name",
	}

	var input = &TestData{
		Name: "",
		Age:  "",
	}
	gconv.Struct(data, input, mapping)
	fmt.Println("conv====>", input)
}
```
输出结果为
conv====> &{123 123}，Name和Age字段都有值

期望结果
conv====> &{ 123}，只有Age字段有值

**Comment by wln732** [comment]
我注意到在 gf\util\gconv\gconv_struct.go的doStruct 函数末尾有三个给结构体赋值的方法
分别是 doStructBaseOnParamKeyToAttrMap ，doStructBaseOnAttribute， doStructBaseOnParamMap
当我传入了自定义映射规则后，在运行完这个函数doStructBaseOnParamKeyToAttrMap 貌似就应该退出了吧
可是目前运行完第一个，后面两个还会接着运行，会把我传入的data map的name字段给自动转换成结构体名字来赋值

**Comment by clh021** [comment]
> 我注意到在 gf\util\gconv\gconv_struct.go的doStruct 函数末尾有三个给结构体赋值的方法 分别是 doStructBaseOnParamKeyToAttrMap ，doStructBaseOnAttribute， doStructBaseOnParamMap 当我传入了自定义映射规则后，在运行完这个函数doStructBaseOnParamKeyToAttrMap 貌似就应该退出了吧 可是目前运行完第一个，后面两个还会接着运行，会把我传入的data map的name字段给自动转换成结构体名字来赋值

我看了下代码，发现是赋值不完全时才会继续运行。所以基于这个逻辑，只要把参数都赋值上默认值就可以了。
然后，我测试了以下，确实，只要设置了 d 参数，就都可以获取到值了。

**Comment by wln732** [comment]
> > 我注意到在 gf\util\gconv\gconv_struct.go的doStruct 函数末尾有三个给结构体赋值的方法 分别是 doStructBaseOnParamKeyToAttrMap ，doStructBaseOnAttribute， doStructBaseOnParamMap 当我传入了自定义映射规则后，在运行完这个函数doStructBaseOnParamKeyToAttrMap 貌似就应该退出了吧 可是目前运行完第一个，后面两个还会接着运行，会把我传入的data map的name字段给自动转换成结构体名字来赋值
> 
> 我看了下代码，发现是赋值不完全时才会继续运行。所以基于这个逻辑，只要把参数都赋值上默认值就可以了。 然后，我测试了以下，确实，只要设置了 d 参数，就都可以获取到值了。

他这个逻辑就是先和自定义规则中对的上先匹配，然后是字段名和paramsKey对应的匹配，最后是忽略下划线和大小写匹配
