### ISSUE TITLE
struct 查询有几个问题

### ISSUE THREAD

**Issue by zhaopengme** [gogf/gf#34]
struct 查询有几个问题
1. 关键字 key  希望支持转成数据库的字段名,比如createAt 应该对应成 create_at
2. 值 value ,么有过滤为空的情况
3. 我的 struct 使用了继承  , 比如 base struct {id string}   ,person struct{base}, 最后得到的 sql是 where base={id:333}

**Comment by johngcn** [comment]
@zhaopengme 
1. 在`gform`中使用`struct`作为参数时，支持使用`gconv`/`json`标签用来标识与数据表字段的对应关系；
1. 这块需要改进一下；
1. 这块我需要研究一下；

**Comment by johngcn** [comment]
@zhaopengme 
我两天后考虑了一下，并且参考了其他`ORM`的做法。

关于`struct`默认值，在`gform`中默认值仍旧是有效的，`struct`的使用场景往往是记录与对象的映射时有用，在`gform`中主要是查询完毕数据后，再对数据结果集`struct`进行修改，随后可以使用`Save`方法对该记录集进行保存。目前不会改变这个逻辑，如果有更好的建议欢迎讨论。

继承这块，`gform`也不考虑支持`struct`的继承，虽然可以做得到，但对象的继承对于数据表来说相当于表与表重复字段的简便化管理，意义不是很大，反而增加了`gform`设计的复杂度。

如果有更好的想法，也欢迎讨论。

**Comment by zhaopengme** [comment]
如果不方便,你可以预留一些接口出来,我们自己来实现

**Comment by johngcn** [comment]
@zhaopengme 不太确定你需要什么样的接口，可以提出来我考虑下。
