### ISSUE TITLE
升级为V1.9.2版本 POST请求JSON数据，GetToStruct获取不回数据，旧版没问题的

### ISSUE THREAD

**Issue by wehnhew** [gogf/gf#340]

**Comment by johngcn** [comment]
@wehnhew 你好`1.9.x`其实是未正式发版的`2.0`版本，任何修复版本号的更新可能都是大的修改。关于你这个问题，能否提供可复现问题的最小代码，以便我快速定位处理？

**Comment by wehnhew** [comment]
> @wehnhew 你好`1.9.x`其实是未正式发版的`2.0`版本，任何修复版本号的更新可能都是大的修改。关于你这个问题，能否提供可复现问题的最小代码，以便我快速定位处理？
文档的例子就能测试
https://github.com/gogf/gf/blob/master/.example/net/ghttp/server/request/request_validation.go

**Comment by johngcn** [comment]
@wehnhew 好的，我试试

**Comment by johngcn** [comment]
@wehnhew 你好，之前是因为该方法会去读取提交的参数并自动解析`JSON`参数，现在去掉自动解析`JSON`参数这个功能了，而只会使用POST提交的表单参数作为Map值。`Request`对象不再会自动解析`JSON`提交参数，只有开发者自己通过`GetJson`方法去获取并通过`ToMap`进行解析。
