### ISSUE TITLE
httpclient Header can support KEY that is not converted into uppercase letters.

### ISSUE THREAD

**Issue by FireTiger23** [gogf/gf#3408]
![image](https://github.com/gogf/gf/assets/6301010/1507e428-01af-4d10-a6ef-61b0a2d5d451)

有些第三方的API接口 会限制 Header 的KEY纯小写。如果这边走标准库的Set 会被强制转成 首字母大写。导致API调用失败。
能否这边走 
![5fc58e3345f1dfa7cd6cb5a7682d3ca9](https://github.com/gogf/gf/assets/6301010/6ed3ba08-d3f6-45f8-b669-16771c5e93c0)
这样子 可以兼容不标准API的调用。

谢谢。

**Comment by chen-mou** [comment]
这个可以通过client的middleware来实现这一操作以下是示例
![image](https://github.com/gogf/gf/assets/42209673/a2de0b68-4a25-40f1-8537-f0fa0f09522c)
这段代码的输出结果为
![image](https://github.com/gogf/gf/assets/42209673/1d5d32ee-5142-4be4-8afd-2040009de910)
有关中间件的详细说明你可以参考[[HTTPClient-拦截器/中间件](https://goframe.org/pages/viewpage.action?pageId=7301625)]

**Comment by FireTiger23** [comment]
> 这个可以通过client的middleware来实现这一操作以下是示例 ![image](https://private-user-images.githubusercontent.com/42209673/315270420-a2de0b68-4a25-40f1-8537-f0fa0f09522c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyNDE5NjksIm5iZiI6MTcxMTI0MTY2OSwicGF0aCI6Ii80MjIwOTY3My8zMTUyNzA0MjAtYTJkZTBiNjgtNGEyNS00MGYxLTg1MzctZjBmYTBmMDk1MjJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDAwNTQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNzdkNjlmNDI4OGI5NjVjYWNjNGNiNjA1MjhiZDk5NjcwMjliZDA3MTcyOWFlY2RmODcwNmI1OWRkN2I5ZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bdiq8efR1F-MkiMYHnmfhjJb29p9FoC7gI0i9siJXgc) 这段代码的输出结果为 ![image](https://private-user-images.githubusercontent.com/42209673/315270567-1d5d32ee-5142-4be4-8afd-2040009de910.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyNDE5NjksIm5iZiI6MTcxMTI0MTY2OSwicGF0aCI6Ii80MjIwOTY3My8zMTUyNzA1NjctMWQ1ZDMyZWUtNTE0Mi00YmU0LThhZmQtMjA0MDAwOWRlOTEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDAwNTQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0ZmM2Mjc2OGY3YTBjNmE0NzAyMzZkNDAwMTQ0OGMzMWNlMjlmYjZmMDkxYzJiOGFlOGZkYTFlMDQxMzFiMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-RGQyXpUmeOAfL3CaT1gDDiIdYIqw-6YFUdMOMQdrsM) 有关中间件的详细说明你可以参考[[HTTPClient-拦截器/中间件](https://goframe.org/pages/viewpage.action?pageId=7301625)]

感谢指导～～，可以了。
