### ISSUE TITLE
Verifying github.com/gogf/gf@v1.9.2: checksum mismatch

### ISSUE THREAD

**Issue by richfuns** [gogf/gf#341]
### 1. What version of `Go` and system type/arch are you using?

go version go1.13 windows/amd64

### 2. What version of `GoFrame` are you using?

1.9.1

### 3. Can this issue be reproduced with the latest release?

`从1.9.1升级到1.9.2， 执行go get -u github.com/gogf/gf`

**提示以下错误**

`go: downloading github.com/gogf/gf v1.9.2
verifying github.com/gogf/gf@v1.9.2: checksum mismatch
        downloaded: h1:MIsi/uhjWH1p8uCbv0nOg8h0976Ah5D9VPS1EruBYRg=
        sum.golang.org: h1:96Fsn+itjSlRxv3+mjkt5eUQ88ILbV+UWGq23Wa26gM=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.`

### 4. What did you do?

执行以下命令，还是有同样的错误

```
go clean -modcache
go mod tidy
```

### 5. What did you expect to see?

正常升级

**Comment by johngcn** [comment]
@richfuns 奇怪，按理说即使有问题，清空缓存了也能正常升级的，不过我还没升级到`1.13`测试过，回头我试试，你可能需要自行继续研究一下。

**Comment by richfuns** [comment]
@johngcn 谢大佬，我先回退到了1.9.1，抽空再看看

**Comment by iwz2099** [comment]
> @johngcn 谢大佬，我先回退到了1.9.1，抽空再看看

我原先用了阿里的proxy不行，我换成goproxy以后就可以拿到最新版本了
`
➜go env -w GOPROXY=https://goproxy.io,direct
➜ go get -u github.com/gogf/gf
go: downloading github.com/gogf/gf v1.9.2
go: extracting github.com/gogf/gf v1.9.2
`

**Comment by richfuns** [comment]
> > @johngcn 谢大佬，我先回退到了1.9.1，抽空再看看
> 
> 我原先用了阿里的proxy不行，我换成goproxy以后就可以拿到最新版本了
> `go env -w GOPROXY=https://goproxy.io,direct`

这个是代理吗？ 我在国外，应该不需要代理吧？

**Comment by johngcn** [comment]
@richfuns 你更新到最新版本的`GF`再试试，我把版本库中的`go.sum`删掉了，也许是这个引起的，我看了`go 1.13`开始增加了`sum.golang.org`的校验。

**Comment by richfuns** [comment]
> @richfuns 你更新到最新版本的`GF`再试试，我把版本库中的`go.sum`删掉了，也许是这个引起的，我看了`go 1.13`开始增加了`sum.golang.org`的校验。

谢大佬，升级1.9.3没有问题
