### ISSUE TITLE
请问可以支持redis-stack吗？想使用Redis的json功能

### ISSUE THREAD

**Issue by vaecou** [gogf/gf#3424]
redis-stack支持在redis中使用json功能，但是我不知道该如何向redis写入json的数据形式，没有找到案例，也没有看到相关语句，不知道是不是goframe不支持redis-stack

![image](https://github.com/gogf/gf/assets/32005908/740e9ada-b230-4c88-b84b-f4960fab326f)

**Comment by oldme-git** [comment]
@vaecou 感谢提出 issue，GF 做为一个框架不会面面俱到的支持所有细枝末节的功能。如果你单纯的只是想使用 Redis 储存 Json，可以考虑储存 Json 字符串。
Thiank you for your issue.  Gf as one framework does not support all function . However, you can use a Json string to save Json data

**Comment by vaecou** [comment]
> @vaecou 感谢提出 issue，GF 做为一个框架不会面面俱到的支持所有细枝末节的功能。如果你单纯的只是想使用 Redis 储存 Json，可以考虑储存 Json 字符串。 Thiank you for your issue. Gf as one framework does not support all function . However, you can use a Json string to save Json data

其实redis-stack和redis是一致的，不过redis-stack比redis多了一个json的语法，希望官方可以支持一下
