### ISSUE TITLE
升级为V1.9.3版本 websocket 报错

### ISSUE THREAD

**Issue by wehnhew** [gogf/gf#343]
websocket: response does not implement http.Hijacker Stack:1.  
github.com/gogf/gf/net/ghttp.(*Middleware).Next.func1.7    E:/golang/pkg/mod/github.com/gogf/gf@v1.9.3/net/ghttp/ghttp_request_middleware.go:943.  github.com/gogf/gf/net/ghttp.niceCallFunc    E:/golang/pkg/mod/github.com/gogf/gf@v1.9.3/net/ghttp/ghttp_func.go:544.  github.com/gogf/gf/net/ghttp.(*Middleware).Next.func1    E:/golang/pkg/mod/github.com/gogf/gf@v1.9.3/net/ghttp/ghttp_request_middleware.go:935.  github.com/gogf/gf/util/gutil.TryCatch    E:/golang/pkg/mod/github.com/gogf/gf@v1.9.3/util/gutil/gutil.go:696.  github.com/gogf/gf/net/ghttp.(*Middleware).Next
  E:/golang/pkg/mod/github.com/gogf/gf@v1.9.3/net/ghttp/ghttp_request_middleware.go:457.  github.com/gogf/gf/net/ghttp.(*Server).handleRequest    E:/golang/pkg/mod/github.com/gogf/gf@v1.9.3/net/ghttp/ghttp_server_handler.go:1258.  github.com/gogf/gf/net/ghttp.(*Server).defaultHttpHandle    E:/golang/pkg/mod/github.com/gogf/gf@v1.9.3/net/ghttp/ghttp_server_handler.go:34

**Comment by johngcn** [comment]
@wehnhew 收到

**Comment by johngcn** [comment]
@wehnhew 请更新最新框架代码再试试

**Comment by wehnhew** [comment]
@johngcn 正常了
