### ISSUE TITLE
gf gen service Bug

### ISSUE THREAD

**Issue by thedawn3** [gogf/gf#3434]
**What version of `Go` and system type/arch are you using?**
v2.6.4
Welcome to GoFrame!
Env Detail:
  Go Version: go1.22.1 windows/amd64
  GF Version(go.mod):
    github.com/gogf/gf/v2@v2.6.4
CLI Detail:
  Installed At: C:\GOPATH\bin\gf.exe
  Built Go Version: go1.22.1
  Built GF Version: v2.6.4
Others Detail:
  Docs: https://goframe.org
  Now : 2024-03-27T19:33:47+08:00

**What version of `GoFrame` are you using?**
Built GF Version: v2.6.4

**Can this bug be re-produced with the latest release?**
是的

**What did you do?**

![image](https://github.com/gogf/gf/assets/89783816/b624a628-c908-4b98-95fc-6248def072c8)
当我使用gf gen service自动生成service代码时，如果logic中的方法含有`/*` `*/` 的字符串 则会被错误的认定为注释中间的代码，导致中间代码无法被正确识别并生成对应接口

**What did you expect to see?**
当`/*` `*/` 为字符串内容时不应该被认为是要注释代码

**What did you see instead?**
中间的代码错误的被认为是注释了 导致无法正常生成service代码

**Comment by oldme-git** [comment]
Please show https://github.com/gogf/gf/issues/3067
