### ISSUE TITLE
When canonical routing generates OpenAPI documents, the structure in the response has no annotations.

### ISSUE THREAD

**Issue by shuqingzai** [gogf/gf#3435]
**What version of `Go` and system type/arch are you using?**

```bash
#-> % go version
go version go1.21.7 darwin/amd64
```

**What version of `GoFrame` are you using?**

```bash
#-> % gf version
v2.6.4
Welcome to GoFrame!
Env Detail:
  Go Version: go1.21.7 darwin/amd64
  GF Version(go.mod):
    github.com/gogf/gf/v2@v2.6.4
CLI Detail:
  Installed At: /Code/go/bin/gf
  Built Go Version: go1.21.7
  Built GF Version: v2.6.4
Others Detail:
  Docs: https://goframe.org
  Now : 2024-03-27T11:36:04+08:00
```

**Can this bug be re-produced with the latest release?**

**What did you do?**

参考： [规范路由-基本示例](https://goframe.org/pages/viewpage.action?pageId=116004916) 使用以下示例代码，在 OpenAPI 文档中，`HelloReq` 中的 `user` 可以生成注释，但是 `HelloRes` 中的 `user` 没有注释信息

**配置**

```yaml
server:
  address:     ":8199"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
```

**示例代码**
```go
package main

import (
	"context"

	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/net/ghttp"
)

type User struct {
	Name string `json:"name" dc:"用户名称" v:"required|length:6,30" `
	Age  int    `json:"age" dc:"年龄" v:"required|between:1,150"`
}

type HelloReq struct {
	g.Meta `path:"/hello" method:"get" sm:"hello" tags:"示例"`

	Name string `json:"name" v:"required" dc:"名称"`
	User *User  `json:"user" v:"required" dc:"用户信息"`
}
type HelloRes struct {
	Name string `json:"name" v:"required" dc:"名称"`
	User *User  `json:"user" v:"required" dc:"用户信息"`
}

type Hello struct{}

func (Hello) Say(ctx context.Context, req *HelloReq) (res *HelloRes, err error) {
	g.Log().Debugf(ctx, `receive say: %+v`, req)
	return
}

func main() {
	s := g.Server()
	// s.Use(ghttp.MiddlewareHandlerResponse)
	s.Group("/", func(group *ghttp.RouterGroup) {
		group.Bind(
			new(Hello),
		)
	})
	s.Run()
}
```
访问： http://127.0.0.1:8199/swagger/#tag/%E7%A4%BA%E4%BE%8B/paths/~1hello/get

![image](https://github.com/gogf/gf/assets/44406033/64650266-1c0b-4061-bbe3-6ca11ad827a7)

**What did you expect to see?**

**What did you see instead?**

**Comment by chen-mou** [comment]
这个结构体是对各个属性解析之后的数据
![image](https://github.com/gogf/gf/assets/42209673/91b6dc7d-b735-4504-9865-72268416c1db)
Ref是引用对应的结构体的KEY, Value是存储当前属性的一些值，问题出在goframe在解析结构体时只会设置Ref，而当结构体作为属性时，忽略了对于Value的设置所以导致了这个bug
这个bug同时会导致在请求参数中嵌套结构体的注释缺失
![image](https://github.com/gogf/gf/assets/42209673/d4f53686-8c76-4608-832f-ad38cb8a9cd0)
![image](https://github.com/gogf/gf/assets/42209673/9f9b5f56-8a4d-42a2-b929-0b9065428cef)

**Comment by chen-mou** [comment]
对于这个bug我觉得应该在解析结构体属性，同时设置Value属性，但是这样的话需要修改SchemaRef结构体的MarshalJSON方法与前端的JS，因为我发现api.json的值中如果同时存在$ref字段与其他字段，其他的字段会被忽略

**Comment by shuqingzai** [comment]
> 对于这个bug我觉得应该在解析结构体属性，同时设置Value属性，但是这样的话需要修改SchemaRef结构体的MarshalJSON方法与前端的JS，因为我发现api.json的值中如果同时存在$ref字段与其他字段，其他的字段会被忽略

也不是这个问题，使用 `$ref` 引用是为了复用 `Schema` ，减少文件输出的内容，实际上每个 struct 都会生成一个 `Schema` ，只是默认情况下，`Schema` 缺失 `Description` 属性的设置，需要在定义 struct 时带上 `gmeta.Data` 才会被解析


```go
```
