### ISSUE TITLE
Allow to get and set header in controller or logic

### ISSUE THREAD

**Issue by yangyanqing** [gogf/gf#3443]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Add some mechanism, let developer can get and set http's header.

**Describe alternatives you've considered**

**Additional**

**Comment by oldme-git** [comment]
You can work like this:
你可以这样获取 ghttp 服务:
```
// GetRequest
g.RequestFromCtx(ctx).Request
// Get Header
g.RequestFromCtx(ctx).Request.Header
// GetResponse
g.RequestFromCtx(ctx).Response
```
