### ISSUE TITLE
ghttp.client post参数问题

### ISSUE THREAD

**Issue by linklin7** [gogf/gf#345]
问题：post请求api未有文件上传时也需要支持writer.WriteField来设置请求参数。
目前框架对于普通请求参数方式：
![QQ图片20190925111246](https://user-images.githubusercontent.com/7196297/65566478-8e25d800-df85-11e9-89eb-8525ee63836d.png)

测试实现：
![image](https://user-images.githubusercontent.com/7196297/65566363-28d1e700-df85-11e9-83c9-2267ea769f6b.png)

需求：普通请求时也可以支持writer.WriteField来设置请求参数！

**Comment by johngcn** [comment]
@linklin7 看一下HTTP客户端章节，有很多示例的：https://goframe.org/net/ghttp/client/example

![image](https://user-images.githubusercontent.com/26347176/65600294-74f74880-dfd2-11e9-8f5c-42f32beb8d5c.png)
