### ISSUE TITLE
The parameter format of InsertIgnore is questionable, not sure if it is a bug

### ISSUE THREAD

**Issue by LianSchedule** [gogf/gf#3456]
我已经仔细阅读文档，因问题比较复杂暂时无法使用英文提出，请谅解。
- 我希望使用InsertIgnore方法，以下是我的代码（我知道这里的sql可能存在问题，不过它不会影响我对框架问题的疑问）
```
dao.xxx.ctx(ctx).Data("column1=?,column2=?",value1,value2).InsertIgnore()
```
- 通过阅读源码（v2.6.4）发现，它会进行一个赋值
```
model.data = "column1=?,column2=?"
model.extraArgs=[value1,value2]
```
- 报错msg是"data list cannot be empty"，以下是截取源码，可以由刚才可以知道，model.data是一个字符串，不是list、map，因为源码庞大且复杂，我也不清楚是否有其他中间的处理，这个问题最终可能是在goframe框架中insert/InsertIgnore时怎么使用占位符，谢谢
```
newData, err := m.filterDataForInsertOrUpdate(m.data)
if err != nil {
		return nil, err
}
	// It converts any data to List type for inserting.
switch value := newData.(type) {
	case List:
		list = value
	case Map:
		list = List{value}
	}
if len(list) < 1 {
		return result, gerror.NewCode(gcode.CodeMissingParameter, "data list cannot be empty")
	}
```

**Comment by LianSchedule** [comment]
还有一个例子
```
dao.User.Ctx(ctx).Insert("uuid=?", "c1")
```
会报错“data list cannot be empty”

**Comment by wln32** [comment]
可以使用g.Map 传参

**Comment by houseme** [comment]
Data, Insert 可以使用结构体和map 当作参数写入，如果需要原生SQL，可以使用如下方法：
```go
// SQL操作方法，返回原生的标准库sql对象
Query(ctx context.Context, query string, args ...interface{}) (*sql.Rows, error)
Exec(ctx context.Context, query string, args ...interface{}) (sql.Result, error)
Prepare(ctx context.Context, query string) (*sql.Stmt, error)

// 数据表记录查询：
// 查询单条记录、查询多条记录、获取记录对象、查询单个字段值(链式操作同理) 
GetAll(ctx context.Context, sql string, args ...interface{}) (Result, error)
GetOne(ctx context.Context, sql string, args ...interface{}) (Record, error)
GetValue(ctx context.Context, sql string, args ...interface{}) (Value, error)
GetArray(ctx context.Context, sql string, args ...interface{}) ([]Value, error)
GetCount(ctx context.Context, sql string, args ...interface{}) (int, error)
GetScan(ctx context.Context, objPointer interface{}, sql string, args ...interface{}) error

// 数据单条操作
Insert(ctx context.Context, table string, data interface{}, batch...int) (sql.Result, error)
Replace(ctx context.Context, table string, data interface{}, batch...int) (sql.Result, error)
Save(ctx context.Context, table string, data interface{}, batch...int) (sql.Result, error)

// 数据修改/删除
Update(ctx context.Context, table string, data interface{}, condition interface{}, args ...interface{}) (sql.Result, error)
Delete(ctx context.Context, table string, condition interface{}, args ...interface{}) (sql.Result, error)
```

具体文档：https://goframe.org/pages/viewpage.action?pageId=1114177

@LianSchedule

**Comment by LianSchedule** [comment]
> 可以使用g.Map 传参

谢谢你，想请问map传参的话在goframe框架内部属于使用占位符的方式吗？

**Comment by LianSchedule** [comment]
> Data, Insert 可以使用结构体和map 当作参数写入，如果需要原生SQL，可以使用如下方法：
> 
> ```go
> // SQL操作方法，返回原生的标准库sql对象
> Query(ctx context.Context, query string, args ...interface{}) (*sql.Rows, error)
> Exec(ctx context.Context, query string, args ...interface{}) (sql.Result, error)
> Prepare(ctx context.Context, query string) (*sql.Stmt, error)
> 
> // 数据表记录查询：
> // 查询单条记录、查询多条记录、获取记录对象、查询单个字段值(链式操作同理) 
> GetAll(ctx context.Context, sql string, args ...interface{}) (Result, error)
> GetOne(ctx context.Context, sql string, args ...interface{}) (Record, error)
> GetValue(ctx context.Context, sql string, args ...interface{}) (Value, error)
> GetArray(ctx context.Context, sql string, args ...interface{}) ([]Value, error)
> GetCount(ctx context.Context, sql string, args ...interface{}) (int, error)
> GetScan(ctx context.Context, objPointer interface{}, sql string, args ...interface{}) error
> 
> // 数据单条操作
> Insert(ctx context.Context, table string, data interface{}, batch...int) (sql.Result, error)
> Replace(ctx context.Context, table string, data interface{}, batch...int) (sql.Result, error)
> Save(ctx context.Context, table string, data interface{}, batch...int) (sql.Result, error)
> 
> // 数据修改/删除
> Update(ctx context.Context, table string, data interface{}, condition interface{}, args ...interface{}) (sql.Result, error)
> Delete(ctx context.Context, table string, condition interface{}, args ...interface{}) (sql.Result, error)
> ```
> 
> 具体文档：https://goframe.org/pages/viewpage.action?pageId=1114177
> 
> @LianSchedule

谢谢你，看起来在insert时如果想使用占位符，只能原生Exec了，我理解的对吗？

**Comment by houseme** [comment]
> > 可以使用g.Map 传参
> 
> 谢谢你，想请问map传参的话在goframe框架内部属于使用占位符的方式吗？

gdb.Raw() 有这个方法，文档有写怎么使用
