### ISSUE TITLE
gconv.Scan cannot bind string property to []float64

### ISSUE THREAD

**Issue by gaoyangtok** [gogf/gf#3477]
**What version of `Go` and system type/arch are you using?**

go version go1.20.10 linux/amd64

**What version of `GoFrame` are you using?**
v2.7.0

**Can this bug be re-produced with the latest release?**
yes

**What did you do?**
type From struct {
	Data string
}
type ToData struct {
	Data []float64
}
func TestFloat(t *testing.T) {
	f := []From{
		{Data: "[0.1,0.45]"},
	}
	var to []ToData
	gconv.Scan(f, &to)
	fmt.Println(gconv.String(to))
}

**What did you expect to see?**
[{"Data":[0.1, 0.45]}]

**What did you see instead?**
[{"Data":[0]}]

**Comment by wln32** [comment]
@gaoyangtok  目前gf并不能把string转换到[]float64，请注册一个转换函数，代码如下
```go
gconv.RegisterConverter(func(src string) (ret *[]float64, err error) {
	ret = new([]float64)
// 从数组类型的字符串转换到数字类型的数组，也可以自己实现一个
	err = json.Unmarshal([]byte(src), ret)
	return
})
```
相关文档 https://goframe.org/pages/viewpage.action?pageId=126844932
