### ISSUE TITLE
Request validator tag "required-if" is invalid

### ISSUE THREAD

**Issue by fainc** [gogf/gf#3484]
Get http://127.0.0.1:8002/workspace/district/list/level?page=1 // ⚠️no xx field 
```go
type DistrictListReq struct {
	g.Meta     `path:"/district/list/{method}" tags:"District" method:"get" summary:"获取行政区划"`
	Method     string `json:"method" v:"required|in:pid,pcode,level"`
	Page       int    `json:"page" v:"required|min:0"`
	Xx      int    `json:"xx" v:"required-if:method,level|min:0"`//  it's work ✅  tips "The Xx field is required"
        Xx      int    `json:"xx" v:"min:0|required-if:method,level"`//  it's not work ⚠️ request into controller 
}
```
  Go Version:  go1.20.8
  GF Version:  v2.6.4

**Comment by fainc** [comment]
required-if 规则在 min 规则之后时 required 失效 不传递参数也能验证通过；在min规则之前则正常

**Comment by wln32** [comment]
@fainc @gqcn 
当这样定义验证的规则的时候，由于没有Xx参数，所以required-if验证规则会不通过，返回"The Xx field is required"
Xx int json:"xx" v:"required-if:method,level|min:0"

但是如果反过来，验证min规则其实的没有通过的，返回了错误
但是由于不是required系列的规则，直接跳出了循环


![1](https://github.com/gogf/gf/assets/49137144/35e1f42d-f67d-4bdb-a6e2-b09f6b0cbc6c)

**Comment by fainc** [comment]
@wln32 搞一下？

**Comment by wln32** [comment]
> @wln32 搞一下？

@fainc 搞不了，验证那块的代码一堆if判断，你可以尝试在我分析出来的那块代码加个if判断试试，看看能不能满足你想要的结果

**Comment by gqcn** [comment]
@fainc @wln32 Let me have a check.

**Comment by gqcn** [comment]
@fainc @wln32 大家好，经过评估，该细节设计如此，不需要做任何修复或者改进，具体请参考文档：https://goframe.org/pages/viewpage.action?pageId=1114367
