### ISSUE TITLE
g.DB().Model("table t") has a bug

### ISSUE THREAD

**Issue by JustinLiu1998** [gogf/gf#3496]
**What version of `Go` and system type/arch are you using?**

go version go1.22.2 darwin/arm64

**What version of `GoFrame` are you using?**

2.7.0

**Can this bug be re-produced with the latest release?**
yes

**What did you do?**

In **gf/contrib/drivers/mysql/mysql_z_unit_model_test.go : Test_Issue1002**
below line `defer dropTable(table)`
add this content: `table = fmt.Sprintf("%s %s", table, "t1111")`

![CleanShot 2024-04-19 at 11 33 27@2x](https://github.com/gogf/gf/assets/34473099/7c219abd-d79f-4aea-a5b9-6b8251621057)

**What did you expect to see?**
it should pass the test

**What did you see instead?**
"panic: function TableFields supports only single table operations"

**Comment by oldme-git** [comment]
@JustinLiu1998 In INSERT INTO statement, why use aliases? also, GF will recognize as multiple data tables in Insert().

**Comment by JustinLiu1998** [comment]
@oldme-git During testing, I initially performed queries using the Model() method with an alias. Subsequently, when I modified the code for testing insertions, I encountered this error.
I went through the documentation and there were no indications of any restrictions on the usage of aliases.

**Comment by oldme-git** [comment]
@JustinLiu1998 You're welcome.
