### ISSUE TITLE
数据库连接异常的处理

### ISSUE THREAD

**Issue by piaohao** [gogf/gf#35]
### 1. What version of `Go` are you using (`go version`)?

<pre>
$ go version
1.11
</pre>

### 2. What version of `GoFrame` are you using?
1.57

### 3. Does this issue reproduce with the latest release?
yes

### 4. What did you do?

```
       sqlDb, err = bs.db.Open(node)
        if err != nil {
            return nil
       }
```
项目启动的时候，数据库连接超时，没有任何的记录，依然能正常启动，结果web接口也不报错，状态为0，导致很难排查线上问题。

### 5. What did you expect to see?
应该给出日志，且项目终止启动；如果是运行的过程中db连接异常，应该给出日志，web接口应该给出500状态码

### 6. What did you see instead?
没有日志，接口状态码为0

**Comment by johngcn** [comment]
@piaohao 
你好，`GF`框架也是采用了`Go`的风格设计，因此每一个数据库的操作接口都会有一个`error`参数返回，往往是第二个返回参数，交个开发者来处理错误，而不是单纯的`panic`。

另外，数据库`ORM`采用的是`lazy initializing`模式，也就是说在初始化`ORM`对象的时候并不会与数据库建立连接，而是需要操作`SQL`的时候才会真正的初始化，所以在初始化的时候往往都是成功的（除非配置不规范）。

还有，就是在`GF`的`WebServer`中，大部分情况下（除非在事务逻辑中），你如果接收到非`nil`的数据库操作`error`返回，直接`panic`即可，会直接中断服务接口执行并且会记录到错误日志中，接口会返回`500`。

此外，你说的这段代码：
```go
sqlDb, err = bs.db.Open(node)
if err != nil {
     return nil
}
```
完整的应该是这样的：
![image](https://user-images.githubusercontent.com/26347176/53609730-37c90480-3c03-11e9-9feb-d93d4dcb67dc.png)
最终连接失败会返回错误，这里使用了命名返回参数的设计。

若有疑问，可继续回复。

**Comment by johngcn** [comment]
@piaohao 你所说的返回状态码是`0`的情况，初步分析是你在操作数据库的过程中，抑制了`error`返回值，而在业务流程执行到数据库操作这块就中断掉了，而`WebServer`也没有接收到任何的异常产生，所以返回值为状态码的默认值`0`。解决办法是查看你操作数据库的地方，检查返回的`error`返回值，如果收到非`nil`情况，直接`panic`。注意的是，如果是事务操作，根据情况建议是将该事务操作放到一个操作方法中管理流程和数据库操作，以便事务回滚。

**Comment by piaohao** [comment]
@johngcn 感谢你的详细回复，根据你的建议，我试试看
