### ISSUE TITLE
数据管理模块->gredis连接池中，连接数限制[bug]

### ISSUE THREAD

**Issue by 1819997197** [gogf/gf#354]
初始化redis pool时，这两个参数没有赋值进去MaxIdle:config.MaxIdle, MaxActive:config.MaxActive（github.com/gogf/gf/database/gredis/gredis.go:66）。建议修改一下，谢谢

**Comment by johngcn** [comment]
@1819997197 感谢反馈，已修复，将在下一个修复版本发布。

**Comment by johngcn** [comment]
@1819997197 请更新最新框架代码再试。
