### ISSUE TITLE
V2.7 cannot use ORM JSON storage

### ISSUE THREAD

**Issue by Gallery2000** [gogf/gf#3560]
### Go version

1.21

### GoFrame version

2.7

### Can this bug be reproduced with the latest release?

Option Yes

### What did you do?

评论区已经有人反馈了，所有的json都字段都被解析成了空字符插入到数据库。当我把gf版本降到2.64执行gf gen dao后一切就正常了。
![image](https://github.com/gogf/gf/assets/33472593/a0c87020-52b3-4bab-9412-9d417d51df5d)
![image](https://github.com/gogf/gf/assets/33472593/85675c8e-cee4-4a1e-a94a-83c008549a10)

### What did you see happen?

 help

### What did you expect to see?

help

**Comment by wln32** [comment]
我在我的机器上试了pgsql没问题，另这个和mysql没有关系，只要数据库支持json类型的字段就可以

**Comment by leavky** [comment]
社区的这个问题是我写的，看到说是2.64是正常的，我降级后将生成的文件和2.7生成的文件对比了下，发现了问题。
2.6.4生成的：
![image](https://github.com/gogf/gf/assets/46547390/1b953b63-9cff-4d3e-aef7-974063a94da6)
2.7 以及 2.7.1 生成的：
![image](https://github.com/gogf/gf/assets/46547390/6355fccb-4c0b-49e1-b549-ad8aa31040e5)
通过对比发现2.7 生成的多了orm标签
现在有两个解决办法：
1. 修改生成的文件，将orm标签删除
2. 不修改生成的文件，在自己上一级结构体中写上 orm 标签。
![image](https://github.com/gogf/gf/assets/46547390/f0ca3285-c130-428d-86b4-9d8005f6c721)

希望可以改下，官方工具不生成这个orm标签

**Comment by Gallery2000** [comment]
对不起，我更正一下，如果插入的字段为元组类型并且len为0 ，则会提示错误：
Error: Error 3140 (22032): Invalid JSON text: "The document is empty." at position 0 in value for column 'xxx.xxx'. 
`dao.Message.Ctx(ctx).Data(model.MessageItem{
        Embeds:            make([]MessageEmbed, 0),
}).Insert()`
