### ISSUE TITLE
g.Dump: An error occurred during type serialization of json.MarshalJSON

### ISSUE THREAD

**Issue by wln32** [gogf/gf#3567]
### Go version

1.22

### GoFrame version

2.7.0

### Can this bug be reproduced with the latest release?

Option Yes

### What did you do?

```go
type implJson struct {
	buf []byte
}
func (i *implJson) MarshalJSON() ([]byte, error) {
	fmt.Println("implJson.MarshalJSON被调用")
	return i.buf, nil
}
type jsonResult struct {
	Id       int       `orm:"id"`
        // 1.指针类型时，正常调用MarshalJSON方法来序列化
       // 2值类型时，不会调用MarshalJSON方法来序列化
	JsonText *implJson `orm:"json_text"`
}

buf, err := json.Marshal(map[string]any{
		"test1": "1",
		"test2": 2,
		"test3": "gf",
})

var res =new(jsonResult)
res.Id = 2
res.JsonText  = &implJson{
		buf: buf,
}

```

### What did you see happen?

```go

// JsonText为指针类型时输出
g.Dump(res)
{
    Id:       2,
    JsonText: "{\"test1\":\"1\",\"test2\":2,\"test3\":\"gf\"}",
}

// 把JsonText 的类型改为值类型implJson 时，输出
g.Dump(res)
{
Id:       2,
    JsonText: {
        buf: [
            123,
            34,
            116,
            101,
           ...，省略后面的，实际上就是把这个buf当成一个个字符来输出，
        ],
    },
}
```

### What did you expect to see?
```go
{
    Id:       2,
    JsonText: "{\"test1\":\"1\",\"test2\":2,\"test3\":\"gf\"}",
}

{
    Id:       2,
    JsonText: "{\"test1\":\"1\",\"test2\":2,\"test3\":\"gf\"}",
}
```

**Comment by gqcn** [comment]
@wln32 以下是根据描述整理的完整源码：
```go
package main

import (
	"encoding/json"
	"fmt"

	"github.com/gogf/gf/v2/frame/g"
)

type implJson struct {
	buf []byte
}

func (i *implJson) MarshalJSON() ([]byte, error) {
	fmt.Println("implJson.MarshalJSON被调用")
	return i.buf, nil
}

type jsonResult struct {
	Id int `orm:"id"`
	// 1.指针类型时，正常调用MarshalJSON方法来序列化
	// 2值类型时，不会调用MarshalJSON方法来序列化
	JsonText *implJson `orm:"json_text"`
}

func main() {
	buf, err := json.Marshal(map[string]any{
		"test1": "1",
		"test2": 2,
		"test3": "gf",
	})
	fmt.Println(err)

	var res = new(jsonResult)
	res.Id = 2
	res.JsonText = &implJson{
		buf: buf,
	}
	g.Dump(res)
}
```
执行后输出：
```
<nil>
implJson.MarshalJSON被调用
{
    Id:       2,
    JsonText: "{\"test1\":\"1\",\"test2\":2,\"test3\":\"gf\"}",
}
```
请问这是否符合你预期？

**Comment by wln32** [comment]
> @wln32 以下是根据描述整理的完整源码：
> 
> ```go
> package main
> 
> import (
> 	"encoding/json"
> 	"fmt"
> 
> 	"github.com/gogf/gf/v2/frame/g"
> )
> 
> type implJson struct {
> 	buf []byte
> }
> 
> func (i *implJson) MarshalJSON() ([]byte, error) {
> 	fmt.Println("implJson.MarshalJSON被调用")
> 	return i.buf, nil
> }
> 
> type jsonResult struct {
> 	Id int `orm:"id"`
> 	// 1.指针类型时，正常调用MarshalJSON方法来序列化
> 	// 2值类型时，不会调用MarshalJSON方法来序列化
> 	JsonText *implJson `orm:"json_text"`
> }
> 
> func main() {
> 	buf, err := json.Marshal(map[string]any{
> 		"test1": "1",
> 		"test2": 2,
> 		"test3": "gf",
> 	})
> 	fmt.Println(err)
> 
> 	var res = new(jsonResult)
> 	res.Id = 2
> 	res.JsonText = &implJson{
> 		buf: buf,
> 	}
> 	g.Dump(res)
> }
> ```
> 
> 执行后输出：
> 
> ```
> <nil>
> implJson.MarshalJSON被调用
> {
>     Id:       2,
>     JsonText: "{\"test1\":\"1\",\"test2\":2,\"test3\":\"gf\"}",
> }
> ```
> 
> 请问这是否符合你预期？

我本意是值类型和指针类型行为不一致

**Comment by gqcn** [comment]
> > @wln32 以下是根据描述整理的完整源码：
> > ```go
> > package main
> > 
> > import (
> > 	"encoding/json"
> > 	"fmt"
> > 
> > 	"github.com/gogf/gf/v2/frame/g"
> > )
> > 
> > type implJson struct {
> > 	buf []byte
> > }
> > 
> > func (i *implJson) MarshalJSON() ([]byte, error) {
> > 	fmt.Println("implJson.MarshalJSON被调用")
> > 	return i.buf, nil
> > }
> > 
> > type jsonResult struct {
> > 	Id int `orm:"id"`
> > 	// 1.指针类型时，正常调用MarshalJSON方法来序列化
> > 	// 2值类型时，不会调用MarshalJSON方法来序列化
> > 	JsonText *implJson `orm:"json_text"`
> > }
> > 
> > func main() {
> > 	buf, err := json.Marshal(map[string]any{
> > 		"test1": "1",
> > 		"test2": 2,
> > 		"test3": "gf",
> > 	})
> > 	fmt.Println(err)
> > 
> > 	var res = new(jsonResult)
> > 	res.Id = 2
> > 	res.JsonText = &implJson{
> > 		buf: buf,
> > 	}
> > 	g.Dump(res)
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 执行后输出：
> > ```
> > <nil>
> > implJson.MarshalJSON被调用
> > {
> >     Id:       2,
> >     JsonText: "{\"test1\":\"1\",\"test2\":2,\"test3\":\"gf\"}",
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 请问这是否符合你预期？
> 
> 我本意是值类型和指针类型行为不一致

这里主要是`Go`语言里面的一个小坑吧。你可以先在框架代码中搜索一下`MarshalJSON(`的实现，你会发现接收对象都是值对象，为什么呢？
通常`MarshalJSON`需要定义到值接收对象上，这样其指针对象也实现了该方法。假如`MarshalJSON`定义到了指针接收对象上，那么其值对象是没有实现该方法的。
所以你这里的定义：
```go
func (i *implJson) MarshalJSON() ([]byte, error) {
```
修改为：
```go
func (i implJson) MarshalJSON() ([]byte, error) {
```
即可。
