### ISSUE TITLE
https://goframe.org/util/gconv/struct 里面的示例2，复杂类型的 1. slice类型属性 代码中的 直接slice赋值 代码打印失败

### ISSUE THREAD

**Issue by huangqian1985** [gogf/gf#358]
示例代码位于 .example/utils/gconv/gconv_struct3.go

```go
// 通过变量映射转换，直接slice赋值
if err := gconv.Struct(scores, user); err != nil {
	fmt.Println(err)
} else {
	g.Dump(user)
}
```

原因是Struct里的Map()方法没有处理Slice的case 所以retrun nil

**Comment by johngcn** [comment]
@huangqian1985 感谢反馈，这种不带键名的映射关系转换有点混淆，不太严谨，在新版本中被删除了，新版本中仅支持`map`/`struct`到`struct`的转换。
