### ISSUE TITLE
os/gtime: issue config

### ISSUE THREAD

**Issue by xiao-bin-bin** [gogf/gf#3590]
### Description

能不能像 python 的 Django 一样，将 所有支持修改的配置 在初始化项目的时候 生成到 配置文件中， 这样我们可以根据需求直接修改对应的配置就行， goframe在启动的时候直接读取配置文件中的配置进行初始化运行。

**Comment by hailaz** [comment]
好提议，排期一下

**Comment by hailaz** [comment]
先加一部分

**Comment by xiao-bin-bin** [comment]
@hailaz  感谢大佬对我的想法的支持
