### ISSUE TITLE
v1.5.8 binController("/",new(Controller.Index))代码不变生成路由会变动

### ISSUE THREAD

**Issue by sth4me** [gogf/gf#36]
### 1. What version of `Go` are you using (`go version`)?

<pre>
$ go version
1.12
</pre>

### 2. What version of `GoFrame` are you using?
1.5.8

### 3. Does this issue reproduce with the latest release?

no

### 4. What did you do?

升级前配置文件按文档设置，未变动。
注释控制器内部代码或者不注释不影响报错。
生成路由表每次编译有可能不生成，或者生成index方法的，或者index和user方法的都生成。
![m 62d nzd7hlme1 mr f 1e](https://user-images.githubusercontent.com/28669192/53543389-8328d780-3b5d-11e9-9ba5-dfe23893476a.png)
![iou0de3ddo50n iux ej7nu](https://user-images.githubusercontent.com/28669192/53543396-88862200-3b5d-11e9-90de-fb2708fe8ab7.png)
![pmqp p72 f8l3 a6vgd6 za](https://user-images.githubusercontent.com/28669192/53543399-8b811280-3b5d-11e9-9920-3435e410318e.png)

怀疑bug，或者我路由注册方式有问题。不过升级前没出现过。

> /router/router.go
```golang
func init() {
	// 用户模块 路由注册 - 使用执行对象注册方式
	s := g.Server()
	s.BindController("/", new(controller.Index))
}
```

> /app/controller/index.go
```golang
type Index struct {
	gmvc.Controller
}

func (i *Index) Index() {
	//...
}

func (i *Index) User() {
	//...
}
```

**Comment by johngcn** [comment]
我看你用的最新go版本，我试一下。

**Comment by johngcn** [comment]
@sth4me 感谢反馈，已修复。
