### ISSUE TITLE
database/gdb: I noticed there was a sharding feature before. Why was it removed

### ISSUE THREAD

**Issue by cruelchen** [gogf/gf#3602]
### What do you want to ask?

Why was it removed

**Comment by cruelchen** [comment]
@gqcn  
https://github.com/gogf/gf/pull/2732  
https://github.com/gogf/gf/pull/2758

**Comment by gqcn** [comment]
@cruelchen The sharding feature submitted previously was not quite complete, so it was deleted before the release. This time, we have provided a relatively complete sharding feature, which is expected to be released in the next version: https://github.com/gogf/gf/pull/4014
