### ISSUE TITLE
database/gdb: Do you want to change the default Charset?

### ISSUE THREAD

**Issue by hailaz** [gogf/gf#3609]
### What do you want to ask?

utf8mb4会逐渐成为默认的字符集，是否也要改下gf的默认字符集？
https://github.com/gogf/gf/blob/23df83cb0b68b94f57404e0577c059c0c6cd2f45/database/gdb/gdb.go#L375

**Comment by niluan304** [comment]
`utf8mb4` 是 MySQL 独有的坑吧？
其他数据库，如 Postgres 似乎并没有这个问题
