### ISSUE TITLE
container的garray.StrArray的join方法能否设置一个参数表示是否不用转义检测

### ISSUE THREAD

**Issue by foxhack** [gogf/gf#361]
建议container的garray.StrArray的join方法能否设置一个参数表示是否不用转义检测
### 1. What version of `Go` and system type/arch are you using?
golang 1.13 linux/amd64

### 2. What version of `GoFrame` are you using?
gf version 1.9.7

### 3. Can this issue be reproduced with the latest release?
最近更新gf版本后，原本正常的业务出现异常，在排查后发现是因为新gf的strarray的join方法修改了导致join出来的字符串和原来行为不一致，字符串中添加了“，导致拼接的字符串进入业务逻辑后出现异常，测试代码如下，以前的版本是没有添加多余的“，查看了gf版本变更记录后发现，改方法的逻辑修改了，能否添加一个标志，来确认是否修改字符串拼接逻辑
![图片](https://user-images.githubusercontent.com/16910405/66537383-d252d400-eb52-11e9-9235-ec492dc4b7f3.png)

![图片](https://user-images.githubusercontent.com/16910405/66537314-8b64de80-eb52-11e9-9535-c6b22624ac21.png)

**Comment by johngcn** [comment]
@foxhack 问题收到。

**Comment by johngcn** [comment]
@foxhack 已修复，请更新到最新框架代码再试试。
