### ISSUE TITLE
gf pack arg -p / not affect

### ISSUE THREAD

**Issue by ananclub** [gogf/gf#3611]
### What do you want to ask?

As title, when run gf pack testpath packed/data.go -n packed -p / , use gf.Dump() list then packed res filename not start with / path, still start with testpath

**Comment by hailaz** [comment]
的确有bug
https://github.com/gogf/gf/blob/1793bf0863ca07ca4ac89654230fc3b06cfa991a/os/gres/gres_func_zip.go#L65
