### ISSUE TITLE
gf gen service -f CamelLower

### ISSUE THREAD

**Issue by Sanni13077** [gogf/gf#3617]
### Go version

go1.20.8

### GoFrame version

v2.7.1

### Can this bug be reproduced with the latest release?

Option Yes

### What did you do?

Run the "gf gen service -f CamelLower" command, and the subdirectories in the logic directory will be named using the CamelLower format.

### What did you see happen?

The generated file name is in the format "simple_file.go"

### What did you expect to see?

The generated file name is in the format "simpleFile.go"

**Comment by gqcn** [comment]
@Sanni13077 你好，我无法复现该问题，也许已经在新版本中修复，建议使用最新版本cli再试试。
