### ISSUE TITLE
gdb: issue The SQL is wrong when using "WhereNotIn", if an empty parameter is passed

### ISSUE THREAD

**Issue by developer-r2tech** [gogf/gf#3619]
### Go version

go version go1.21.9 linux/amd64

### GoFrame version

2.7.1

### Can this bug be reproduced with the latest release?

Option Yes

### What did you do?

var ids []int
dao.User.Ctx(ctx).WhereNotIn("id", ids).Count()

### What did you see happen?

SELECT COUNT(1) FROM `user` WHERE 0=1

### What did you expect to see?

SELECT COUNT(1) FROM `user` WHERE 1=1

**Comment by niluan304** [comment]
maybe better? 
```sql
SELECT COUNT(1) FROM `user` WHERE NOT 0=1;
```

**Comment by gqcn** [comment]
@developer-r2tech It is designed as this, if condition parameters are empty for `Where*` function, ORM will use `0=1` condition to warn you the given condition is empty. It does not filter the empty condition automatically as it might lead unexpected business issue. More refer to https://goframe.org/pages/viewpage.action?pageId=7301832
