### ISSUE TITLE
ORM Where 用MAP参数, 并且条件为link时候, 拼接sql会异常

### ISSUE THREAD

**Issue by IGGAbc** [gogf/gf#362]
简单例子:
where := gmap.New()
where.Set("s_time like ",r.GetString("s_time")+"%")

db := g.DB()
rd, err := db.Table("stats").Filter().Cache(c.cacheTimeout, c.cacheKey+"gets").Where(where).Limit(3).Select()
	if err != nil && err != sql.ErrNoRows {
		re.Error(400, err)
		return
	}
拼接成的SQL语句为

SELECT * FROM `stats` WHERE s_time like ='201910121505%' LIMIT 3
无法识别关键字 like

**Comment by johngcn** [comment]
@IGGAbc 请更新最新框架代码。
