### ISSUE TITLE
gdb: Is there any problem if the migrate function is not added? Or is it because its industry-level projects do not change the table from the code level, so it is not done?

### ISSUE THREAD

**Issue by caiwenju** [gogf/gf#3627]
### What do you want to ask?

不增加migrate功能是存在什么问题吗？还是说因为其业级项目不会从代码层级去变更表，所以不做了呢？

**Comment by hailaz** [comment]
后者

**Comment by niluan304** [comment]
related
[gqcn](https://github.com/gqcn) commented [on Oct 14, 2020](https://github.com/gogf/gf/issues/943#issuecomment-708390027)
`Sorry but I do not think it a good feature and will not be considered`
#943 #475 #779
