### ISSUE TITLE
页面模板渲染异常，直接显示html代码

### ISSUE THREAD

**Issue by linklin7** [gogf/gf#363]
代码：
	// 模糊匹配/html路由，用于前端history模式访问
	s.BindHandler("/html/*path", func(r *ghttp.Request) {
		// 访问静态html文件
		r.Response.WriteTpl("build/admin/index.html", g.Map{
			"title": "",
		})
	})

页面输出：

![image](https://user-images.githubusercontent.com/7196297/66725922-a42e0680-ee68-11e9-9a85-dc153ae52849.png)

**Comment by johngcn** [comment]
@linklin7 已修复，请更新到最新框架代码再试试。
