### ISSUE TITLE
\contrib\drivers\pgsql\v2: pgsql will report an error when inserting the data if it is an array.

### ISSUE THREAD

**Issue by jinmao88** [gogf/gf#3632]
### Go version

go .122

### GoFrame version

2.7.1

### Can this bug be reproduced with the latest release?

Option Yes

### What did you do?

插入的数据 如果字段类型是数组类型，[]int 这种 会报错

### What did you see happen?

![3475dfcd6901575174cc122f9b304334](https://github.com/gogf/gf/assets/50581550/7645444a-8e8d-47bd-84c1-0e1c03ded2cc)
![0f8d50323088b4f7e8594b5629de41b2](https://github.com/gogf/gf/assets/50581550/8f8f2a05-4aff-42f0-a788-865e87e94710)
![cf6fb9a61f20da9f73291565f07abdf2](https://github.com/gogf/gf/assets/50581550/f0f6286f-36f2-4a0a-842a-2f7ae391d553)

pgsql驱动内的函数 入参是NAME 无法触发switch 进行转换

### What did you expect to see?

希望能正常写入

**Comment by oldme-git** [comment]
请提供最小代码实现

**Comment by jinmao88** [comment]
type Member struct {
	Id     int   `json:"id"                 orm:"id"                  ` //
	Income []int `json:"income"             orm:"income"              ` // 月收入

}

func (r *Req) Add() error {
	m := dao.Member.Ctx(r.Ctx).Data(&Member{Income: []int{1, 1}})
	m.Insert()
	return nil
}
