### ISSUE TITLE
errors/gerror: The judgment result of gerror's Is() method is a bit counter-intuitive

### ISSUE THREAD

**Issue by lingcoder** [gogf/gf#3633]
### Go version

go version go1.22.3 windows/amd64

### GoFrame version

2.7.1

### Can this bug be reproduced with the latest release?

Option Yes

### What did you do?

这是gerror的源码部分：
func Is(err, target error) bool {
	if e, ok := err.(IIs); ok {
		return e.Is(target)
	}
	return false
}
由于标准库错误没有实现IIs接口，导致这里的判断直接变成false了。
参考下面的标准库的错误包 与 github.com/pkg/errors包的 判断对比。

### What did you see happen?

![image](https://github.com/gogf/gf/assets/34231795/5f2541a4-ba91-43e8-a490-2c53523cbe62)
我预期与标准库的errors.Is判断结果一致

### What did you expect to see?

结果相反

这是复现示例代码：
```go
package main

import (
	"errors"
	"github.com/gogf/gf/v2/errors/gerror"
	pkgerror "github.com/pkg/errors"
	"github.com/stretchr/testify/assert"
	"testing"
)

var ErrNotFound = errors.New("not found")

func TestGerrorIs(t *testing.T) {
	assert.True(t, pkgerror.Is(ErrNotFound, ErrNotFound), "pkg error 判断错误")
	assert.True(t, errors.Is(ErrNotFound, ErrNotFound), "std error 判断错误")
	assert.True(t, gerror.Is(ErrNotFound, ErrNotFound), "gerror 判断错误")

}
```

**Comment by oldme-git** [comment]
![33ad0ef30f01ba6a24eb13d139ba9b3](https://github.com/gogf/gf/assets/45782393/0e773351-65dc-47f5-baee-9103f3cd2099)
`error.is` 对应的应该是 `gerror.Equal`

**Comment by hailaz** [comment]
理论上加一个errors.Is判断即可
```go
// Is reports whether current error `err` has error `target` in its chaining errors.
// It is just for implements for stdlib errors.Is from Go version 1.17.
func (err *Error) Is(target error) bool {
	if Equal(err, target) {
		return true
	}
	nextErr := err.Unwrap()
	if nextErr == nil {
		return false
	}
	if Equal(nextErr, target) {
		return true
	}
	if e, ok := nextErr.(IIs); ok {
		return e.Is(target)
	}
        // return false
	return errors.Is(nextErr, target) // 这里是修改的
}
```

**Comment by hailaz** [comment]
```go

err1 := errors.New("permission denied")
fmt.Println(gerror.Is(err1, err1))// false
fmt.Println(gerror.Is(gerror.Wrap(err1, ""), err1))// 这样套一套能返回true，但有点多此一举


func Is(err, target error) bool {
	if e, ok := err.(IIs); ok {
		return e.Is(target)
	}
	return false // 这里不应该直接返回
}
```

**Comment by lingcoder** [comment]
> ```go
> err1 := errors.New("permission denied")
> fmt.Println(gerror.Is(err1, err1))// false
> fmt.Println(gerror.Is(gerror.Wrap(err1, ""), err1))// 这样套一套能返回true，但有点多此一举
> 
> 
> func Is(err, target error) bool {
> 	if e, ok := err.(IIs); ok {
> 		return e.Is(target)
> 	}
> 	return false // 这里不应该直接返回
> }
> ```

对的，同一个错误，Is都返回false，挺反直觉的
