### ISSUE TITLE
ORM更新操作 文档中第一种数值形式（Data("status=1")） 1.9.9版无效 

### ISSUE THREAD

**Issue by kxy000** [gogf/gf#365]
版本   github.com/gogf/gf v1.9.9

问题：

ORM链式更新中

其中Data是数值方法，用于指定写入/更新/批量写入/批量更新的数值。 支持多种形式的数值参数：

r, err := db.Table("user").Data("status=1").Update()    无效
r, err := db.Table("user").Data("status", 1).Update()
r, err := db.Table("user").Data(g.Map{"status" : 1}).Update()

第一种写法貌似无效，后面两种正常，使用第一种更新数据

例如 我的项目中
r, err := db.Table("user").Data("status=1").where("user_id = ?",1).Update() 

提示
data cannot be empty

**Comment by johngcn** [comment]
@kxy000 感谢反馈，已修复，将会在下一个小版本发布。

**Comment by johngcn** [comment]
@kxy000 请更新最新版本再试试。
