### ISSUE TITLE
gf/v2/net/ghttp: issue standard routing file flow download

### ISSUE THREAD

**Issue by Desdemo** [gogf/gf#3650]
### What do you want to ask?

api.go
```go
type Req struct {
	g.Meta `path:"/exportmethod:"post" summary:"导出"`
	OrderNoReq
}

//	type Res struct {
//		g.Meta `mime:"application/octet-stream"`
//	}
type Res []byte
```
中间件
```go
func (s *sMiddleware) MiddleFileByteResponse(r *ghttp.Request) {
	if strings.Contains(r.Request.URL.Path, "export") {
		r.Middleware.Next()
		r.Response.Header().Set("Content-Type", "application/octet-stream")
		r.Response.Header().Set("Content-Disposition", "attachment; filename="+"dataList.xlsx")
		r.Response.Header().Set("Content-Transfer-Encoding", "binary")
		r.Response.Write(r.GetHandlerResponse())
	} else {
		ghttp.MiddlewareHandlerResponse(r)
	}
}

```
怎么样才能实现文件流的下载

这两种方式都没有办法支持，也没有搜到，能给个示例吗？

**Comment by AZ000000** [comment]
I did a type conversion on it. Because I saw that the write method in the source code has processed array types.
`bytes := gfile.GetBytes("test.txt")
	s := g.Server()
	s.BindHandler("/", func(r *ghttp.Request) {
		r.Response.Writeln(gconv.SliceInt(bytes))
	})
	s.SetPort(8999)
	s.Run()`

Output results:
                   [113 113 113]
Is this the result you want to get

**Comment by Desdemo** [comment]
no, it is like 
![微信图片_20240620155651](https://github.com/gogf/gf/assets/31582776/02c25d4d-1ec0-4bb6-b5b0-3d093699d660)

**Comment by oldme-git** [comment]
@Desdemo You already got successful. That's just the matter of your api tools.

**Comment by Desdemo** [comment]
不是啊，我是给的是期望的示例啊，现在这个无法实现呢，我看之前也有问的，后面也没有答复。

**Comment by Desdemo** [comment]
https://github.com/gogf/gf/issues/1558

就像这个描述一样

**Comment by oldme-git** [comment]
> 不是啊，我是给的是期望的示例啊，现在这个无法实现呢，我看之前也有问的，后面也没有答复。

我已经试过了，是你 `http` 客户端的问题
