### ISSUE TITLE
根据数据库表生成的model中的Replace和Update无效

### ISSUE THREAD

**Issue by dangwy** [gogf/gf#366]
根据数据库表生成的model中的Replace和Update无效.
```go
func (r *TaskInfo) SaveTask() error {
	if e := r.SaveCache(); e != nil {
		return e
	}
	if _, e := r.Replace(); e != nil {
		return e
	}
	return nil
}
```
其中`r`结构在别调用前已值存在。

**Comment by dangwy** [comment]
忘了说：
Replace()方法会生成一条新数据，和insert的行为一样。
update()方法无效。

**Comment by johngcn** [comment]
@dangwy 你把自动生成的`TaskInfo`这个`struct`的定义贴出来看看呢。

**Comment by dangwy** [comment]
type TaskInfo struct {
	Id         int    `orm:"id,primary"     json:"id"`
	UserId     int    `orm:"user_id"        json:"user_id"`
	TaskType   int    `orm:"task_type"      json:"task_type"`
	TraceId    string `orm:"trace_id"       json:"trace_id"`
	BankId     int    `orm:"bank_id"        json:"bank_id"`
	Agency     string `orm:"agency"         json:"agency"`
}

**Comment by johngcn** [comment]
@dangwy 看样子自动生成的model也是正确的，你把`debug`打开吧，看下输出的`sql`是不是正确的。如果不正确你取一条参数出来给我，并且把建表的`sql`给我，我本地试试。
