### ISSUE TITLE
net/goai: issue The openAPI document api.json generated by gf has a problem with the properties={} parameter setting in each field.

### ISSUE THREAD

**Issue by qinains** [gogf/gf#3660]
### Go version

go version go1.22.0 windows/amd64

### GoFrame version

2.7.1

### Can this bug be reproduced with the latest release?

Option Yes

### What did you do?

1. 修改openAPI的UI
编辑：internal\cmd\cmd.go

```go
const MySwaggerUITemplate = `
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>test</title>
  </head>
  <body>
    <div id="openapi-ui-container" spec-url="{SwaggerUIDocUrl}" theme="light"></div>
    <script src="https://cdn.jsdelivr.net/npm/openapi-ui-dist@latest/lib/openapi-ui.umd.js"></script>
  </body>
</html>
`
s.SetSwaggerUITemplate(MySwaggerUITemplate)

// 启动Http Server
s.Run()
```

2. api文件如下：
api/v1/file.go
```go
package v1

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/net/ghttp"
)

type FileUploadReq struct {
	g.Meta `path:"/file" method:"post" mime:"multipart/form-data" tags:"工具" summary:"上传文件"`
	File   *ghttp.UploadFile `json:"file" type:"file" dc:"选择上传文件"`
}
type FileUploadRes struct {
	Name string `json:"name" dc:"文件名称"`
	Url  string `json:"url"  dc:"访问URL，可能只是URI"`
}
```

3. 启动server：gf run main.go

### What did you see happen?

生成的api.json文件的FileUploadReq部分为

```json
"focus-single.api.v1.FileUploadReq": {
    "properties": {
        "file": {
            "description": "选择上传文件",
            "format": "*ghttp.UploadFile",
            "properties": {},
            "type": "file"
        }
    },
    "type": "object"
},
```

文件上传组件显示不正常：
![微信截图_20240622163427](https://github.com/gogf/gf/assets/528630/d9a9cce8-7223-4b8d-9c4a-71c0b482e04d)

### What did you expect to see?

生成的api.json文件的FileUploadReq部分应该为

```json
"focus-single.api.v1.FileUploadReq": {
    "properties": {
        "file": {
            "description": "选择上传文件",
            "format": "*ghttp.UploadFile",
            "type": "file"
        }
    },
    "type": "object"
},
```

需要把“"properties": {},”去除。去除之后，才能在这个UI（<script src="https://cdn.jsdelivr.net/npm/openapi-ui-dist@latest/lib/openapi-ui.umd.js"></script>）中显示才正常。其他类型也是，需要在xxxReq中把生成的空的“"properties": {},”去除。

![微信截图_20240622163346](https://github.com/gogf/gf/assets/528630/97d68dea-95cc-456d-b41a-45f6e3927265)

**Comment by hailaz** [comment]
试试
go get -v github.com/gogf/gf/v2@2422c82

https://github.com/gogf/gf/pull/3662
