### ISSUE TITLE
关于使用WriteTpl的第二个参数为nil出现错误的问题

### ISSUE THREAD

**Issue by joyoes** [gogf/gf#367]
我在是思考所有的GET请求都返回静态文件html，觉得在每个控制器下都写WriteTpl太麻烦，所以就想在路由router.go文件下写了几行让所有的GET请求都返回静态文件的代码，代码如下：
```go
func init(){
s:=g.Server()
s.Group("/",func(g *ghttp.RouterGroup){
     g.GET("/*",func(r *ghttp.Request){
         r.Response.WriteTpl("login.html",nil)
     })
})
}
```
然后我访问了login之后就出现这个错误 ：assignment to entry in nil map
版本是：gf 1.9.9

**Comment by johngcn** [comment]
@joyoes 请更新最新版本再试试。

**Comment by joyoes** [comment]
@johngcn 刚刚测试了，已修复好了，谢谢！
