### ISSUE TITLE
regex regular matching rules do not take effect

### ISSUE THREAD

**Issue by swurtheone** [gogf/gf#3674]
### Go version

v2.5.7

### GoFrame version

v2.5.7

### Can this bug be reproduced with the latest release?

Option Yes

### What did you do?

设置数据校验规则regex正则匹配不生效
type PwdReq struct {
    g.Meta       `path:"*" tags:"*" method:"post" sm:"*" tags:"*"`
    Password     string `p:"password" dc:"密码" v:"regex:^(?=.*\\d)(?=.*[a-zA-Z]).{6,20}$"`
}

### What did you see happen?

请求出现 The Password value `123456s` must be in regex of: ^(?=.*\d)(?=.*[a-zA-Z]).{6,20}$

### What did you expect to see?

![image](https://github.com/gogf/gf/assets/31538827/b907eba4-1f19-4d56-9190-c5ce462699eb)

**Comment by oldme-git** [comment]
@swurtheone 
这并非是 `GoFrame` 的问题，`Go` 使用 `re2` 正则，不支持零宽断言。
That's not GoFrame's problem. Go regex uses `re2` and Zore-width is not supported by `re2`.
Docs: https://github.com/google/re2/wiki/Syntax
