### ISSUE TITLE
基于在中间件中产生的数据结果怎么才能在方法控制器中使用？

### ISSUE THREAD

**Issue by joyoes** [gogf/gf#368]
我学习了郭老师的洋葱模型中间件设计，这个模型和koa.js的原理是一样的。
由此我在思考能不能将一些通用性的逻辑性代码放在前置中间件中后，产生的数据结果供控制器使用。
比如：
在main.go文件中：
```go
func MiddlewareCORS(r *ghttp.Request) {
    r.Response.CORSDefault()
   resultData:="数据结果"
    r.Middleware.Next()
}

func main() {
    s := g.Server()
    s.Group("/user", func(g *ghttp.RouterGroup) {
        g.Middleware(MiddlewareCORS)
        g.ALL("/list", user.Hello)
    })
    s.SetPort(8199)
    s.Run()
}
```
在控制器user.go中：
```go
func Hello(r *ghttp.Request) {
    r.response.Write(resultData)
}
```
我在想有什么更好的解决方案在控制器中使用前置中间件中产生的resultData的值，请给个示例，谢谢！

**Comment by joyoes** [comment]
或者有其他更好的解决方案，跪求分享，谢谢！大家共同进步！

**Comment by joyoes** [comment]
我个人觉得中间件的处理非常好，如果能把通用性的代码设计在前置中间件中，并为控制器提供数据返回就更完善了！降低我们的开发成本

**Comment by joyoes** [comment]
我自己思考的其中一个思路是在中间件中直接设置：r.SetParam("resultData","yy")，然后直接在控制器中用r.GetParam("resultData")获得其值

**Comment by johngcn** [comment]
@joyoes 是的，通过`SetParam/GetParam`方法就可以了，这个原理和标准库的`context`一样的，只不过更方便一些。
