### ISSUE TITLE
gerror.NewCode has different returns in different gf versions

### ISSUE THREAD

**Issue by xiaoxintiaoda** [gogf/gf#3699]
### Go version

go version go1.22.0 darwin/arm64

### GoFrame version

2.7.2

### Can this bug be reproduced with the latest release?

Option Yes

### What did you do?

```go
# 2.7.0
var err1 = gerror.NewCode(gcode.New(1000, "测试", nil), "测试")
var err2 = gerror.NewCode(gcode.New(1000, "测试", nil), "测试")
fmt.Println(errors.Is(err1, err2)) // return true
```

```go
# 2.7.2
var err1 = gerror.NewCode(gcode.New(1000, "测试", nil), "测试")
var err2 = gerror.NewCode(gcode.New(1000, "测试", nil), "测试")
fmt.Println(errors.Is(err1, err2)) // return false
```

### What did you see happen?

在2.7.0版本和2.7.2版本表现有差异

### What did you expect to see?

在2.7.0版本和2.7.2版本应该都返回true

**Comment by shuqingzai** [comment]
See: #3640

**Comment by xiaoxintiaoda** [comment]
不好意思，那我想咨询一下，以下结果是预期内的，因为我们之前使用2.7.0版本，有一些就是使用的这种错误判断，判断结果都是true。如果后续2.7.2以及之后的版本，判断结果都是false，那可能我需要做一些修改
```go
# 2.7.2
var err1 = gerror.NewCode(gcode.New(1000, "测试", nil), "测试")
var err2 = gerror.NewCode(gcode.New(1000, "测试", nil), "测试")
fmt.Println(errors.Is(err1, err2)) // return false
```

**Comment by xiaoxintiaoda** [comment]
> See: #3640

我看了这个pr，但是pr内容是修改的gerror.Is 方法，我是直接使用的errors.Is方法判断的

**Comment by shuqingzai** [comment]
> > See: #3640
> 
> 我看了这个pr，但是pr内容是修改的gerror.Is 方法，我是直接使用的errors.Is方法判断的

从逻辑上来说，是符合预期，因为你初始化 gerror 时，`gerror.Error.error == nil` ，在标准库中，使用 `errors.Is` 且实现 `Unwrap` ，返回 nil 就会判定为 false

See: https://github.com/gogf/gf/blob/ba322ba0acbb835a379d10581bf03b30b7c4fefc/errors/gerror/gerror_error.go#L107

如果两个 code 完全一致，你应该可以尝试使用 `gerror.HasCode`
