### ISSUE TITLE
client 关闭时，server 无法接收到关闭请求

### ISSUE THREAD

**Issue by skiy** [gogf/gf#37]
### 1. What version of `Go` are you using (output of command: `go version`)?

<pre>
$ go version
go 1.12
</pre>

### 2. What version of `GoFrame` are you using?
v1.5.9

### 3. Can this issue be reproduced with the latest release?
对

### 4. What did you do?

当 client 结束进程时，server 并没有接收到任何消息。
```
	for {
			data, err := conn.Recv(-1)
			fmt.Println(string(data))
}
```

**Comment by johngcn** [comment]
@skiy 你参考下这个示例：https://github.com/gogf/gf/blob/master/geg/net/gtcp/gtcp_server_client1.go ，当客户端`Close`之后，服务端会出现`EOF`错误。

**Comment by johngcn** [comment]
@skiy 分开的`server`和`client`端代码请参考：https://github.com/gogf/gf/tree/master/geg/net/gtcp/server_client

**Comment by skiy** [comment]
找到原因了。
我 ```server``` 端接收到消息就把这个 ```conn Close``` 掉了，所以不会再收到 ```client``` 的关闭请求了。
是我逻辑的问题。
