### ISSUE TITLE
v1.9.9 gres资源管理问题，打包，引用后，文件刷新几次出现Not Modified

### ISSUE THREAD

**Issue by qq1196** [gogf/gf#370]
go 1.13，centos7，x86_64 GNU/Linux，gf v1.9.9 ，

使用gres资源管理，打包引用静态文件，

开始能正常显示图片，但刷新几次会出现 Not Modified

在win下出测试过，同样会出现Not Modified

**Comment by qq1196** [comment]
刚才回滚测试过，gf v1.9.7 静态文件正常，不管刷新几次都正常显示，
gf v1.9.8，gf v1.9.9，就不正常，刷新几次图片就无法显示，浏览器显示 Not Modified
应该是BUG

**Comment by qq1196** [comment]
package main

import (
	_ "web/boot"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/net/ghttp"
)

func main() {
	s := g.Server()
	s.BindHandler("/", func(r *ghttp.Request) {
		r.Response.Header().Set("Content-Type", "text/html; charset=utf-8")
		r.Response.Writeln(`<img src="/images/1.gif">`)
	})
	s.SetServerRoot(`public`)
	s.Run()
}


gf pack public boot/data.go -n boot
打包任意图片 如 public/images/1.gif
刷新几次后，图片就不显示了，
打开图片链接，
浏览器显示 Not Modified
 http://127.0.0.1/images/1.gif

**Comment by johngcn** [comment]
@qq1196 请更新最新版本再试试。
