### ISSUE TITLE
SQLite does not support generating descriptions using gen dao

### ISSUE THREAD

**Issue by herry-go** [gogf/gf#3700]
### Go version

 go1.21.11 linux/amd64

### GoFrame version

 v2.7.2

### Can this bug be reproduced with the latest release?

Option Yes

### What did you do?

SQLite does not support generating descriptions using gen dao

### What did you see happen?

![企业微信截图_17216303446377](https://github.com/user-attachments/assets/01cc0a3c-e6e3-467a-acf1-0ff07d072251)
![企业微信截图_17216303702828](https://github.com/user-attachments/assets/50150086-c6cc-4ead-a80d-d46d37f9ae7d)

### What did you expect to see?

Description automatically retrieves comments from ddl statements

**Comment by oldme-git** [comment]
@herry-go 
`SQLite` 不能使用 `SQL` 子句获取注释
`SQLite` cannot get comments using SQL clause.

**Comment by herry-go** [comment]
Whether it can be parsing from comments in DDL statements？
