### ISSUE TITLE
github.com/gogf/gf/v2/frame/g cannot get instance 

### ISSUE THREAD

**Issue by YoungBoyGod** [gogf/gf#3703]
### Go version

go 1.22.4 amd64

### GoFrame version

2.7.1

### Can this bug be reproduced with the latest release?

Option Yes

### What did you do?

i want to get client instance,but get null.

test one:
```
package gerritLogicV1

import (
	"HaiTangOps/internal/model/gerritModelV1"
	"HaiTangOps/internal/service"
	"context"
	//"github.com/andygrunwald/go-gerrit"
	"github.com/gogf/gf/v2/frame/g"
	"golang.org/x/build/gerrit"
)

type sGerritV1 struct{}

func New() *sGerritV1 {
	return &sGerritV1{}
}

func init() {
	service.RegisterGerritV1(New())
}
func (s *sGerritV1) GetGerritInstance(ctx context.Context, input *gerritModelV1.GetGerritInstanceInput) (output *gerrit.Client) {
	// todo 需要增加登录gerrit 的功能模块
	g.Log().Debug(context.Background(), "input", input)
	// 1.输入地址，用户名密码
	client := gerrit.NewClient(input.Url, gerrit.BasicAuth(input.Username, input.Password))
	g.Log("gerrit").Debug(ctx, "output", client)
	return client

}

2024-07-23 20:49:34.763 [DEBU] input {"Username":"aadmin","Password":"admin","Url":"http://192.168.10.211:8080"}
2024-07-23 20:49:34.763 [DEBU] {bc25aeb279d8e41780d46416e24a9e43} output {"HTTPClient":null}
2024-07-23 20:49:34.763 [INFO] {bc25aeb279d8e41780d46416e24a9e43} {"HTTPClient":null}
```
test two:
![image](https://github.com/user-attachments/assets/e54e33a0-318b-4a80-8b21-2c956358a7af)

### What did you see happen?

i donnt kown why i cannot get client instance use gf 
i try use gin ，it is ok。
so what is wrong ?

### What did you expect to see?

i want get the instance in gf
![image](https://github.com/user-attachments/assets/c3df15f4-b3a6-40b0-a831-6fa20440fe13)

**Comment by YoungBoyGod** [comment]
![image](https://github.com/user-attachments/assets/241b9d38-56b0-4163-bd81-8450d07615bc)
it seem run to  a loop

**Comment by oldme-git** [comment]
似乎你并没有使用到 gf 的某个组件？

**Comment by gqcn** [comment]
@YoungBoyGod 根据你的描述，该问题和`gerrit`包有关，建议咨询其开源项目。
