### ISSUE TITLE
frame/g: The random sorting method in gdb is not compatible with Sqlite

### ISSUE THREAD

**Issue by lingcoder** [gogf/gf#3705]
### Go version

go version go1.22.4 windows/amd64

### GoFrame version

2.7.2

### Can this bug be reproduced with the latest release?

Option Yes

### What did you do?

![0ad7afa188a91cb40294d9285a59ae3](https://github.com/user-attachments/assets/9102a0a5-645a-4bc8-8dad-c95d0be80c55)

sqlite中语法是  ORDER BY RANDOM()，mysql语法是  ORDER BY RAND()，goframe的代码里写死了只支持RAND()

### What did you see happen?

执行到此会报错

### What did you expect to see?

希望从驱动层面支持sqlite的随机排序

**Comment by flow6979** [comment]
Hey, i would like to work on this issue.
Thanks!!
