### ISSUE TITLE
cmd/gf: gf run watched

### ISSUE THREAD

**Issue by poneding** [gogf/gf#3707]
### Go version

go version go1.22.4 darwin/arm64

### GoFrame version

v2.7.2

### Can this bug be reproduced with the latest release?

Option No

### What did you do?

I dont know can this bug be reproduced with the latest release or not. 
I just run my project with `gf run main.go`.

### What did you see happen?

It always checked `watched file changes: CHMOD` and rebuild the project even if I save the file and never modify it again.
<img width="1306" alt="image" src="https://github.com/user-attachments/assets/6758bb35-3836-4a87-9dfc-ef3344e381fe">

### What did you expect to see?

I want to know why it always notify the changes. And how to avoid this.

**Comment by niluan304** [comment]
maybe the file has been updated by OS? like `modified time`.

try using other hot-compiled tool that can exclude file.

**Comment by poneding** [comment]
> maybe the file has been updated by OS? like `modified time`.
> 
> try using other hot-compiled tool that can exclude file.

I have no idea. When I reboot vscode this disappears. Next time this happens I think I'll try using the air tool, thanks.

**Comment by hailaz** [comment]
这种情况一般是IDE（vscode 或者 goland）导致，你可以做一个简单的测试，关闭所有的IDE，用系统提供的cmd 或者 shell 执行gf run命令，然后观察是否会复现。

**Comment by gqcn** [comment]
> 这种情况一般是IDE（vscode 或者 goland）导致，你可以做一个简单的测试，关闭所有的IDE，用系统提供的cmd 或者 shell 执行gf run命令，然后观察是否会复现。

@poneding Yes, as @hailaz said, the IDE can also watch and update your source files.
