### ISSUE TITLE
Simplify

### ISSUE THREAD

**Issue by HHC26** [gogf/gf#3717]
### What do you want to ask?

Can we further optimize the overall performance?
Because reducing the generation of some files can make the entire project smaller and more streamlined

**Comment by hailaz** [comment]
能否举些例子，细说具体方向或模块？

**Comment by HHC26** [comment]
> 能否举一些例子，细说具体方向或模块？

例如:
编写中大型项目时，使用gf ctrl 等指令 会生成较多的文件，部分文件名生成的很长，编译运行的时间也比较长

**Comment by gqcn** [comment]
> > 能否举一些例子，细说具体方向或模块？
> 
> 例如: 编写中大型项目时，使用gf ctrl 等指令 会生成较多的文件，部分文件名生成的很长，编译运行的时间也比较长

`gf ctrl`不是开发项目的必须指令，请根据场景选择使用。针对复杂API项目，其实一个API对应一个控制器会更好管理一些，看个人选择。
