### ISSUE TITLE
util/gutil: gconv struct to map bug, `omitempty` takes no effect

### ISSUE THREAD

**Issue by Golong-me** [gogf/gf#3721]
这是官方的案例
https://goframe.org/pages/viewpage.action?pageId=1114356

下面案例中，理论上nickname不应该出现在输出结果中
同样的案例，使用mapstructure库测试是没有问题的

```
package main

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/util/gconv"
)

func main() {
	type User struct {
		Uid      int
		Name     string `c:"-"`
		NickName string `c:"nickname, omitempty"`
		Pass1    string `c:"password1"`
		Pass2    string `c:"password2"`
	}
	user := User{
		Uid:   100,
		Name:  "john",
		Pass1: "123",
		Pass2: "456",
	}
	g.Dump(gconv.Map(user))
}
```

输出
```
{
    "Uid": 100,
    "password1": "123",
    "password2": "456",
    "nickname": "",
}
```

**Comment by wsy9981999** [comment]
这个时候还是用json标签把

**Comment by Golong-me** [comment]
> 这个时候还是用json标签把

这个和json没有关系，之所以结果是json是因为使用了g.Dump把map转换为了json。
问题的本质是map本身不应该含有nickname字段，在mapstructure库测试是没有问题的

**Comment by wwwfeng** [comment]
我看了一下这个gconv.Map 是有option参数的，比如：
```
			g.Dump(gconv.Map(user, gconv.MapOption{
						OmitEmpty: true,
					}))
```
设置参数以后输出的结果就是下面的样子，我不知道这是不是属于特性
```
{
    "password2": "456",
    "Uid":       100,
    "password1": "123",
}

```

**Comment by Golong-me** [comment]
看样子必须使用option选项才行

> 我看了一下这个gconv.Map 是有option参数的，比如：
> 
> ```
> 			g.Dump(gconv.Map(user, gconv.MapOption{
> 						OmitEmpty: true,
> 					}))
> ```
> 
> 设置参数以后输出的结果就是下面的样子，我不知道这是不是属于特性
> 
> ```
> {
>     "password2": "456",
>     "Uid":       100,
>     "password1": "123",
> }
> ```
