### ISSUE TITLE
WriteJsonExit returns 4 more characters null.

### ISSUE THREAD

**Issue by windf17** [gogf/gf#3723]
### Go version

go version go1.22.5 windows/amd64

### GoFrame version

v2.7.0

### Can this bug be reproduced with the latest release?

Option Yes

### What did you do?

// 登录成功后返回token
func PersonLoginAfter(r *ghttp.Request, respData gtoken.Resp) {
    if respData.Success() {
        r.Response.WriteJsonExit(g.Map{
            "state":   consts.SUCCESS,
            "message": "登录成功！",
            "data":    respData.GetString(gtoken.KeyToken), // 登录成功后data中存放了token
        })
    } else {
        r.Response.WriteJsonExit(g.Map{
            "state":   consts.ERROR,
            "message": "登录失败！",
        })
    }
}

为什么前端收到的json最后有4个字符null？？例如：
res: {"data":"lUZ5V4m1yfFIniYE5PNpLKCUPdYG2qcBrcYijM4klsS6wZIKfs0Py/JZ0xRcga1w","message":"登录成功！","state":1}null

然后就因为null这4个字符，前端反序列化失败，然后要做字符串截取去掉这4个字符，再反序列化，真奇怪！

另外我有个后置中间件，代码如下：
// HandleReturn 后置中间件：处理返回数据
func (s *middlewareService) HandleReturn(r *ghttp.Request) {
    r.Middleware.Next()
    err := r.GetError()
    if err != nil {
        r.Response.WriteJsonExit(g.Map{
            "state":   consts.ERROR,
            "message": err.Error(),
        })
    } else {
        r.Response.WriteJsonExit(r.GetHandlerResponse())
    }
}会是这个出问题了？

### What did you see happen?

现在前端收到的json数据是：
 {"data":"lUZ5V4m1yfFIniYE5PNpLKCUPdYG2qcBrcYijM4klsS6wZIKfs0Py/JZ0xRcga1w","message":"登录成功！","state":1}null

### What did you expect to see?

我期待前端收到的json数据是：
 {"data":"lUZ5V4m1yfFIniYE5PNpLKCUPdYG2qcBrcYijM4klsS6wZIKfs0Py/JZ0xRcga1w","message":"登录成功！","state":1}

**Comment by wlynxg** [comment]
Yes, the reason for null is that you mistakenly called the `r.Response.WriteJsonExit( r.GetHandlerResponse())` method in the middleware.

`r.GetHandlerResponse()` is only applicable to standard routes to get return data. 
But since you write the return data directly through `r.Response.WriteJsonExit`, you will get nil when you call `r.GetHandlerResponse()` in your middleware, and `nil` will be mapped to `null`.

**Comment by windf17** [comment]
so the right way?

**Comment by wlynxg** [comment]
You just need to not call `r.Response.WriteJsonExit(r.GetHandlerResponse())` in the middleware to solve the problem of `null` string.

**Comment by windf17** [comment]
> Yes, the reason for null is that you mistakenly called the method in the middleware.`r.Response.WriteJsonExit( r.GetHandlerResponse())`
> 
> `r.GetHandlerResponse()` is only applicable to standard routes to get return data. But since you write the return data directly through , you will get nil when you call in your middleware, and will be mapped to .`r.Response.WriteJsonExit``r.GetHandlerResponse()``nil``null`

so the right way?

**Comment by windf17** [comment]
> You just need to not call `r.Response.WriteJsonExit(r.GetHandlerResponse())` in the middleware to solve the problem of `null` string.

I tested that if I don't write the line "r.Response.WriteJsonExit(r.GetHandlerResponse())", the front end will not receive the return data.

**Comment by windf17** [comment]
My current solution is to write all normal data returns as r.Response.WriteJsonExit, return if error information is returned, let r.GetError receive the error, and then uniformly give the json returned by the error.

**Comment by windf17** [comment]
我找到了有关代码：
// 登录成功后返回token
func PersonLoginAfter(r *ghttp.Request, respData gtoken.Resp) {
	if respData.Success() {
		r.Response.WriteJsonExit(g.Map{
			"state":   consts.SUCCESS,
			"message": "登录成功！",
			"data":    respData.GetString(gtoken.KeyToken), // 登录成功后data中存放了token
		})
	} else {
		r.Response.WriteJsonExit(g.Map{
			"state":   consts.ERROR,
			"message": "登录失败！",
		})
	}
}
会不会是这样，我这WriteJsonExit了，然后还是执行了后置中间件？？
// HandleReturn 后置中间件：处理返回数据
func (s *middlewareService) HandleReturn(r *ghttp.Request) {
	r.Middleware.Next()
	err := r.GetError()
	if err != nil {
		r.Response.WriteJsonExit(g.Map{
			"state":   consts.ERROR,
			"message": err.Error(),
		})
	} else {
		
		r.Response.WriteJsonExit(r.GetHandlerResponse())
	}
}
这边GetError()，这里是nil。在这r.Response.WriteJsonExit(r.GetHandlerResponse())造成后面多了个null？

**Comment by wlynxg** [comment]
yes

**Comment by windf17** [comment]
> yes

func (r *ghttp.Request) GetHandlerResponse() interface{}
GetHandlerResponse retrieves and returns the handler response object and its error.

func PersonLoginAfter(r *ghttp.Request, respData gtoken.Resp) {
if respData.Success() {
r.Response.WriteJsonExit(g.Map{
"state": consts.SUCCESS,
"message": "登录成功！",
"data": respData.GetString(gtoken.KeyToken), // 登录成功后data中存放了token
})
} else {
r.Response.WriteJsonExit(g.Map{
"state": consts.ERROR,
"message": "登录失败！",
})
}
}
这里直接WriteJsonExit了，然后后置中间件还执行了，然后r.Response.WriteJsonExit(r.GetHandlerResponse())除了返回json数据还多了null？？
那么我该如何解决？？

**Comment by wlynxg** [comment]
If your `PersonLoginAfter` function uses the same standard routing format as your `AccountTypeGet` function, there won't be such an issue

**Comment by windf17** [comment]
// HandleReturn 后置中间件：处理返回数据
func (s *middlewareService) HandleReturn(r *ghttp.Request) {
	r.Middleware.Next()
	err := r.GetError()
	if err != nil {
		r.Response.WriteJsonExit(g.Map{
			"state":   consts.ERROR,
			"message": err.Error(),
		})
	} else {
		res := r.GetHandlerResponse()
		if res == nil {
			r.Response.WriteExit()
		} else {
			r.Response.WriteJsonExit(res)
		}
	}
}

I solved！If the handle returns using WriteJsonExit,
res := r.GetHandlerResponse()
The value of res is nil
So i cannot directly use r.Response.WriteJsonExit(res)

**Comment by windf17** [comment]
> If your `PersonLoginAfter` function uses the same standard routing format as your `AccountTypeGet` function, there won't be such an issue

yes, so i solved,  the code is :
// HandleReturn 后置中间件：处理返回数据
func (s *middlewareService) HandleReturn(r *ghttp.Request) {
	r.Middleware.Next()
	err := r.GetError()
	if err != nil {
		r.Response.WriteJsonExit(g.Map{
			"state":   consts.ERROR,
			"message": err.Error(),
		})
	} else {
		res := r.GetHandlerResponse()
		if res == nil {
			r.Response.WriteExit()
		} else {
			r.Response.WriteJsonExit(res)
		}
	}
}
