### ISSUE TITLE
基于GF框架获取用户真实IP的疑问

### ISSUE THREAD

**Issue by joyoes** [gogf/gf#373]
我想基于GF框架获取客户端用户的真实IP地址和MAC地址，但怎么获取都只能获取到NGINX的代理地址，但框架的调试输出都能正确获取IP地址呢，难道我使用r.Request.RemoteAddr不对头么？跪求大神给个解法，谢谢！
![Uploading QQ图片20191021211722.png…]()

**Comment by joyoes** [comment]
![QQ图片20191021211722](https://user-images.githubusercontent.com/16605854/67209055-3d50b480-f449-11e9-8d02-1a883fac9947.png)

**Comment by zcool321** [comment]
nginx需要加入透传ip
 proxy_set_header X-Real-IP $remote_addr;
 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

**Comment by joyoes** [comment]
![QQ图片20191021211722](https://user-images.githubusercontent.com/16605854/67248223-4e73e280-f496-11e9-88a5-069b8bf5a42f.png)
我的是已经设置了这两个属性了的，但还是没获取到，奇怪的是gf框架是怎么获取到的呢？

**Comment by joyoes** [comment]
![QQ图片20191021211722](https://user-images.githubusercontent.com/16605854/67248258-706d6500-f496-11e9-8fb9-c027d0f7b185.png)

**Comment by joyoes** [comment]
> nginx需要加入透传ip
> proxy_set_header X-Real-IP $remote_addr;
> proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

![QQ图片20191021211722](https://user-images.githubusercontent.com/16605854/67248345-bcb8a500-f496-11e9-8730-9166eed38013.png)

**Comment by joyoes** [comment]
@zcool321 在郭老师的指导下，知道了是使用r.GetClientIp才能获得客户端的IP地址，谢谢！
