### ISSUE TITLE
util/gmeta: I want the method field to support multiple request methods, such as post, put, and get

### ISSUE THREAD

**Issue by seedlings-calm** [gogf/gf#3743]
### Is your feature request related to a problem?

Option Yes

### Describe the solution you'd like

I want the method field to support multiple request methods, such as post, put, and get
 so that I can generate three interface documents at once.
 I don't know if this demand is reasonable or not

### Describe alternatives you've considered

Generate documents based on multiple request methods when parsing method indexes

**Comment by shuqingzai** [comment]
See: [在规范路由下，同一接口如何支持多种HTTP Method提交方式](https://goframe.org/pages/viewpage.action?pageId=116004928#id-%E8%A7%84%E8%8C%83%E8%B7%AF%E7%94%B1%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-%E5%9C%A8%E8%A7%84%E8%8C%83%E8%B7%AF%E7%94%B1%E4%B8%8B%EF%BC%8C%E5%90%8C%E4%B8%80%E6%8E%A5%E5%8F%A3%E5%A6%82%E4%BD%95%E6%94%AF%E6%8C%81%E5%A4%9A%E7%A7%8DHTTPMethod%E6%8F%90%E4%BA%A4%E6%96%B9%E5%BC%8F)
