### ISSUE TITLE
【功能建议】glog打印支持context

### ISSUE THREAD

**Issue by pibigstar** [gogf/gf#375]
> 很多时候一部分信息都放在了context中，如果打印信息可以包含context中内容，会对后面的问题排查非常有帮助

类似于这种
```go
glog.Ctx(ctx).Print()
```

**Comment by johngcn** [comment]
@pibigstar 好建议，其实你可以直接提PR的，在打印里面可以通过接口形式获取到`context`的参数内容，参考一下`glog.Logger`在参数打印时的接口断言判断。

**Comment by johngcn** [comment]
@pibigstar 能够再详细描述一下打印的效果吗？
