### ISSUE TITLE
gdb: The order in which Safe and OmitEmptyWhere are called causes OmitEmptyWhere to fail.

### ISSUE THREAD

**Issue by alanhi** [gogf/gf#3753]
### Go version

go version go1.22.4 windows/amd64

### GoFrame version

v2.7.2

### Can this bug be reproduced with the latest release?

Option Yes

### What did you do?

1. dao中增加自定义方法

```
func (dao tbUserDao) CtxTenant(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.Table()).Safe().Ctx(ctx).Where("`tenant_id` = ?", "888")
}
```

2. 查询接口调用

```
record, err := dao.TbUser.CtxTenant(ctx).
	Safe(false).
	OmitEmptyWhere().
	// Safe(false).
	Where(do.TbUser{
		Name: "",
	}).
	One()
```

### What did you see happen?

1. 调用顺序`.Safe(false).OmitEmptyWhere()`，sql中name条件存在

```
SELECT * FROM `tb_user` WHERE (`tenant_id` = '888') AND (`name`='') LIMIT 1
```

2. 调用顺序`.OmitEmptyWhere().Safe(false)`，sql中name条件不存在

```
SELECT * FROM `tb_user` WHERE `tenant_id` = '888' LIMIT 1
```

看起来是`.Safe(true).Where(xxx).Safe(false).OmitEmptyWhere()`这种形式会出现问题

### What did you expect to see?

fix

**Comment by wln32** [comment]
初步判断原因可能是Safe机制问题
