### ISSUE TITLE
database/gdb: connect issue with aliyunrds

### ISSUE THREAD

**Issue by chaegumi** [gogf/gf#3755]
### Go version

go version go1.22.1 windows/amd64 linux

### GoFrame version

v2.7.2

### Can this bug be reproduced with the latest release?

Option Yes

### What did you do?

**error config**
```
database:
    logger:
      level: "all"
      stdout: true
    default:
      link: "mysql:user:pwd@tcp(rdsid.mysql.rds.aliyuncs.com)/dbname?charset=utf8&loc=Local"
      debug: false
```
**correct config**
```
database:
    logger:
      level: "all"
      stdout: true
    default:
      type: "mysql"
      link: "user:pwd@tcp(rdsid.mysql.rds.aliyuncs.com)/dbname?charset=utf8&loc=Local"
      debug: false
```

### What did you see happen?

link with type cannot connect rds

### What did you expect to see?

link with type can connect rds

**Comment by houseme** [comment]
在ecs上链接还是本地呢？rds的网络权限开启了ecs访问吗？建议自查

**Comment by chaegumi** [comment]
不像是你说的问题吧，如果是你说的问题，那我不管哪个配置都应该不行才对。
你看我两个配置，把数据库类型简写到link参数不行，但是我独立写type就可以

link: "mysql:user:pwd@tcp(rdsid.mysql.rds.aliyuncs.com)/dbname?charset=utf8&loc=Local"
这样写不能读取到数据

但是我下边这样可以
type:"mysql",
link: "user:pwd@tcp(rdsid.mysql.rds.aliyuncs.com)/dbname?charset=utf8&loc=Local"

我也不知道什么原因

**Comment by gqcn** [comment]
@chaegumi Let me have a little check.

**Comment by gqcn** [comment]
@chaegumi 主要原因是里面缺少了端口引起了，目前你可以在地址中增加端口号绕过该问题，我这边会解决一下这个小细节，感谢反馈 ❤️

**Comment by chaegumi** [comment]
thanks
