### ISSUE TITLE
多域名时，能不能增加根据域名读取相关域名的ssl证书

### ISSUE THREAD

**Issue by qq1196** [gogf/gf#376]
多域名时，建议增加根据域名读取相关域名ssl证书

**Comment by johngcn** [comment]
@qq1196 这个可能比较复杂，欢迎大家在当前主题下讨论设计思路。

**Comment by gefire** [comment]
1. 支持导入多个证书
2. 解析SNI拿到请求域名并匹配证书
3. 如果同一个域名有多个证书的话，可以考虑证书的域名过期时间等，这种情况一般很少吧。
