### ISSUE TITLE
frame/g: issue g.client Can we add a method for customizing request header types

### ISSUE THREAD

**Issue by wisonlau** [gogf/gf#3760]
### Description

https://github.com/gogf/gf/issues/3758

我在这个问题里面提到,如果我想避免请求头首字母被改变,只能用go官方的方法.gf官方的包能不能出多一个方法兼容.

**Comment by gqcn** [comment]
@wisonlau 你好，
- 首先，在HTTP协议中，规范化的Header Key是首字母大写的，并且使用英文词连接符号`-`连接多个单词。
- 其次，在`goframe`的`gclient`包中，是通过标准库的`HTTP Header Set`方法来设置的`Header`，具体源码在这里 https://github.com/gogf/gf/blob/183395f0a0f59c1680ce0e78638dd541e4e1c84e/net/gclient/gclient_request.go#L329
- 最后，如果实在是想要自定义与众不同的`Header`，那么可以考虑使用`gclient`的前置中间件来实现，具体请参考文档 https://goframe.org/pages/viewpage.action?pageId=7301625
- 此外，给你一个示例吧：
```go
package main

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/net/gclient"
	"net/http"
)

func main() {
	c := g.Client()
	c.Use(func(c *gclient.Client, r *http.Request) (resp *gclient.Response, err error) {
		// 注意这里不要使用r.Header.Set方法设置Header，会被标准化转换为规范的Header Key
		r.Header["userid"] = []string{"10000"}
		resp, err = c.Next(r)
		return resp, err
	})
}
```
