### ISSUE TITLE
最不爽的是：每个框架都默认集成一个rbac权限管理功能插件，只有gf还没有

### ISSUE THREAD

**Issue by joyoes** [gogf/gf#377]
最不爽的是：每个框架都默认集成一个rbac权限管理功能插件，只有gf还没有，
什么时候才能有基于gf-casbin的插件啊？

**Comment by hsluoyz** [comment]
Can anyone contribute a GF middleware for Casbin and put it onto the list: https://casbin.org/docs/en/middlewares ?

**Comment by gqcn** [comment]
@hsluoyz People asked me times and times about Casbin into GF. I appreciate if any one implements and provides third party middleware with Casbin for GF. The middleware implementation can be referred to gf-jwt: https://github.com/gogf/gf-jwt
