### ISSUE TITLE
os/gtime: TimeZone is Error when  using NewFromTime function in gdb

### ISSUE THREAD

**Issue by weimx2023** [gogf/gf#3774]
### Go version

go version go1.22.5 windows/amd64

### GoFrame version

v2.7.2

### Can this bug be reproduced with the latest release?

Option Yes

### What did you do?

![image](https://github.com/user-attachments/assets/afa26403-daa8-4ef6-8f43-3769f111739d)
using NewFromTimeStamp function is right
![image (1)](https://github.com/user-attachments/assets/f5a29399-9c6b-46fb-a8a5-fc4e5f479cfa)

### What did you see happen?

the TimeZone is error

### What did you expect to see?

fix

**Comment by weimx2023** [comment]
when using query between start time and end time TimeZone of NewFromTime is also error

**Comment by wln32** [comment]
@weimx2023 请检查数据库数据是否正确，**2024-08-06 00:00:00**和**2024-08-05 16:00:00** 是sql显示问题，勿惊
我复现了你的代码，数据库插入的数据是一致的
```go
startTime, _ := time.Parse(time.RFC3339, "2024-08-05T16:00:00Z")

	gStartTime := gtime.NewFromTime(startTime)
	gStartTimestamp := gtime.NewFromTimeStamp(startTime.UnixMilli())
	fmt.Println("from time", gStartTime)
	fmt.Println("from time stamp", gStartTimestamp)
	g.
		DB().
		Model("test_time").
		Safe().
		Insert(g.Map{
			"my_time":      gStartTime,
			"my_timestamp": gStartTimestamp,
		})

mysql连接配置 mysql:root:123456@tcp(127.0.0.1:3306)/test?loc=Local&parseTime=true
表结构
CREATE TABLE `test_time` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `my_timestamp` timestamp NULL DEFAULT NULL,
  `my_time` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB

```
![image](https://github.com/user-attachments/assets/5c8e3cbf-8e7f-4439-906f-67e6530826d1)

**Comment by weimx2023** [comment]
Hi there，I tried it and the time in the database is indeed correct, but this displayed log might cause confusion during debugging. If I directly copy and paste the output SQL statement, the execution result might be different.

**Comment by wln32** [comment]
@gqcn 目前初步定位到问题在`gdb_func.go:920`行，格式化sql时，对time.Time类型没有使用带有时区信息的格式化

![image](https://github.com/user-attachments/assets/ad0cd3fd-7f20-4221-882c-a24759865a32)

修改time格式化后的效果如下， @weimx2023 以下效果是否满意
![image](https://github.com/user-attachments/assets/3c5e7bfb-90ed-4350-a58e-19f31bb910ff)

![image](https://github.com/user-attachments/assets/d983bff1-c9ae-4710-80f1-12a8c9c6af4b)

**Comment by gqcn** [comment]
@weimx2023 @wln32 其实这个也算是老生常态的问题了，程序的时区和数据库时区不一致，只要时区统一了，不是问题。程序在打印时间的时候不会做任何时区转换，那么主要就是时间对象的时间处理了。建议程序：
- 统一使用一种时区处理时间对象转换。
- 传递给数据库的时间对象统一时区。

**Comment by weimx2023** [comment]
> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> @gqcn At present, the problem has been initially located in the `gdb_func.go:920` line. When formatting sql, the time.Time type is not formatted with time zone information.
> 
> ![image](https://private-user-images.githubusercontent.com/49137144/369561990-ad0cd3fd-7f20-4221-882c-a24759865a32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNTgyMjUsIm5iZiI6MTcyNzI1NzkyNSwicGF0aCI6Ii80OTEzNzE0NC8zNjk1NjE5OTAtYWQwY2QzZmQtN2YyMC00MjIxLTg4MmMtYTI0NzU5ODY1YTMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDA5NTIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4YTNjYjMzMmQzMTc3MjFlYzE4Y2ZjMGRjYzViMTU4MTA5MTBjMjM5NTg4NWM3Mjc5MjllMjU3YTUyYTlhYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2SVG0anSIVe3dydtkYqxGztyvaXa_ITYlCdOiM-Q3WI)
> 
> The effect after modifying time formatting is as follows. @weimx2023 Are you satisfied with the following effect? ![image](https://private-user-images.githubusercontent.com/49137144/369565700-3c5e7bfb-90ed-4350-a58e-19f31bb910ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNTgyMjUsIm5iZiI6MTcyNzI1NzkyNSwicGF0aCI6Ii80OTEzNzE0NC8zNjk1NjU3MDAtM2M1ZTdiZmItOTBlZC00MzUwLWE1OGUtMTlmMzFiYjkxMGZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDA5NTIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0OTM5Yjk4NTA1MDZmZDA5MGY2ZDIyZjIwMTRhZTA2ZjNhYzI2Y2ZmMWQ0ZjYyYWVlMzc2N2Y0ZGYzZmNmNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kzed5UMMNgz427k1BgVEZQ-qF34djdP_IwKa-yczAPM)
> 
> ![image](https://private-user-images.githubusercontent.com/49137144/369565641-d983bff1-c9ae-4710-80f1-12a8c9c6af4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNTgyMjUsIm5iZiI6MTcyNzI1NzkyNSwicGF0aCI6Ii80OTEzNzE0NC8zNjk1NjU2NDEtZDk4M2JmZjEtYzlhZS00NzEwLTgwZjEtMTJhOGM5YzZhZjRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDA5NTIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljZDQxZTRmOGZiYzdkNzUwMzEzMTljMmVmODU0NjRmMmNlNWFjZTU5ODg4ODBjNjJjMTlmMDU5M2Q4MDgxMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mY6-9dvcwc7rZb6ovCEFh2BZgRWCEot1gS6YU6m-3tg)

@wln32 @gqcn Adding time zones to time is indeed a good idea, but I think it can be clearly explained in the notes. This way, users won't have any confusion when using it.

**Comment by wln32** [comment]
> @weimx2023 @wln32 其实这个也算是老生常态的问题了，程序的时区和数据库时区不一致，只要时区统一了，不是问题。程序在打印时间的时候不会做任何时区转换，那么主要就是时间对象的时间处理了。建议程序：
> 
> * 统一使用一种时区处理时间对象转换。
> * 传递给数据库的时间对象统一时区。
> 
> 若有其他问题欢迎继续提issue。

不太认同，打印sql语句应当原样输出时间，时区也是时间的一部分，而不是忽略掉，标准库的time类型String方法是带有时区信息的
不带时区的输出默认时间是本地时区，但对于一些项目来说，sql语句不带时区，在出现问题时，可能对于调试有困难
