### ISSUE TITLE
os/gtime: issue title great

### ISSUE THREAD

**Issue by Alilachukwu** [gogf/gf#3783]
### Go version

Go. Vision

### GoFrame version

3.5.6

### Can this bug be reproduced with the latest release?

Option Yes

### What did you do?

Good

### What did you see happen?

Good

### What did you expect to see?

Good

**Comment by Alilachukwu** [comment]
Good

**Comment by cyjaysong** [comment]
？？？？So, what exactly is the problem？？？？

**Comment by gqcn** [comment]
😰
