### ISSUE TITLE
It is recommended to optimize the naming

### ISSUE THREAD

**Issue by tianxia0079** [gogf/gf#3785]
### Description

比如从entity开始有个user. 
1 controller层的go可以统一规范为: userController
2 logic层的go可以统一规范为:userLogic
其他类似

否则,现在很多层的都叫user,开发工具里找起来极其费力. 希望可以参考一下java的命名规则,还是很方便的.

**Comment by gqcn** [comment]
@tianxia0079 再使用Go进行业务开发的时候，确实会遇到这样的痛点，不是没有想过你提的方案，但是在Go里面，Go官方并不推荐这么做，而是通过不同的`import path`来区分不同的包。因此GoFrame也沿用了Go官方的开发建议，并没有这么设计。还有另一方面原因，在通过使用GoFrame框架建议的工程规范来开发业务项目，这样的痛点其实也不是很明显。
