### ISSUE TITLE
net/ghttp: Use `ghttp.MiddlewareHandlerResponse` causes the responses value in the swagger document to be incorrect

### ISSUE THREAD

**Issue by nonlinearthink** [gogf/gf#3786]
### What do you want to ask?

I am using `ghttp.MiddlewareHandlerResponse`, but the output swagger document does not include the 'code', 'message', and 'data' fields, and I used the `swagger-generator` to generate the client's code, which strongly depends on the swagger document.

**Comment by UncleChair** [comment]
Middleware would not change the final doc. If you want to add a "common response", you can add one in the openapi config
``` go
openapi.Config.CommonResponse = api.CommonRes{}
```
or change response structure one by one in your `Standardized Routing`.

**Comment by nonlinearthink** [comment]
@UncleChair Thank you, I have resolved this problem through:

```go
openapi := s.GetOpenApi()
openapi.Config.CommonResponse = ghttp.DefaultHandlerResponse{}
openapi.Config.CommonResponseDataField = "Data"
```
