### ISSUE TITLE
gdb: custom driver is invalid

### ISSUE THREAD

**Issue by wanov** [gogf/gf#3787]
### Go version

go1.21 

### GoFrame version

2.7.0

### Can this bug be reproduced with the latest release?

Option Yes

### What did you do?

```golang
package main
import (
	"database/sql"
	"fmt"
	"github.com/gogf/gf/contrib/drivers/mysql/v2"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

func main() {
	if err := gdb.Register("MyBizDriver", &MyBizDriver{}); err != nil {
		panic(err)
	}
	s, err := g.Model("sys_log").One()
	fmt.Println(s, err)
}

type MyBizDriver struct {
	*mysql.Driver
}

func (d *MyBizDriver) Open(config *gdb.ConfigNode) (db *sql.DB, err error) {
	config.User = "aaaa"  // **bug: 这里就没执行**
	config.Pass = "bbbb"
	return d.Driver.Open(config)
}

func (d *MyBizDriver) decode(s string) string {
	// 执行字段解密处理逻辑
	// ...
	return s
}
```

config.yaml
```yaml
database:
  default:
    link: "MyBizDriver:root:123456@tcp(127.0.0.1:3306)/test"
    timezone: "Asia/Shanghai"
    debug: true
```

### What did you see happen?

The Open function is not executed

### What did you expect to see?

The Open function executed

**Comment by freesme** [comment]
Please refer to the document [ORM使用配置](https://goframe.org/pages/viewpage.action?pageId=1114245#:~:text=%E7%AE%80%E5%8C%96%E9%85%8D%E7%BD%AE%E9%80%9A%E8%BF%87%E9%85%8D%E7%BD%AE%E9%A1%B9link%E6%8C%87%E5%AE%9A%EF%BC%8C%E6%A0%BC%E5%BC%8F%E5%A6%82%E4%B8%8B%EF%BC%9A)，The parameter to this position in your configuration 'MyBizDriver' is the database type, which according to your code should be 'mysql'.

You can find details about Link parsing here:
https://github.com/gogf/gf/blob/c4327f62e7e058773a028e63aad349e6941341cf/database/gdb/gdb_core_config.go#L109-L121

**Comment by wanov** [comment]
> Please refer to the document [ORM使用配置](https://goframe.org/pages/viewpage.action?pageId=1114245#:~:text=%E7%AE%80%E5%8C%96%E9%85%8D%E7%BD%AE%E9%80%9A%E8%BF%87%E9%85%8D%E7%BD%AE%E9%A1%B9link%E6%8C%87%E5%AE%9A%EF%BC%8C%E6%A0%BC%E5%BC%8F%E5%A6%82%E4%B8%8B%EF%BC%9A)，The parameter to this position in your configuration 'MyBizDriver' is the database type, which according to your code should be 'mysql'.
> 
> You can find details about `Link` parsing here:
> 
> https://github.com/gogf/gf/blob/c4327f62e7e058773a028e63aad349e6941341cf/database/gdb/gdb_core_config.go#L109-L121

MyBizDriver is custom driver name, doc link: https://goframe.org/pages/viewpage.action?pageId=1114158

**Comment by freesme** [comment]
It seems that your code does not implement the `New()` method. During the registration process, this method is called to load the custom object you provide. If the `New()` method is not overridden, it will load the default `contrib/drivers/mysql/mysql.go#New()` method, and the `Open()` method will also use the default `contrib/drivers/mysql/mysql_open.go` implementation when called.

If you still have problems, here is a working example for reference:
https://github.com/gogf/gf/blob/c4327f62e7e058773a028e63aad349e6941341cf/example/database/mysql/driver-encrypt-decrypt-password/main.go

**Comment by wanov** [comment]
@freesme greet! It's better to look at the documentation than to see the demo. thank you!
