### ISSUE TITLE
net/ghttp: The new version of nested field parsing is invalid

### ISSUE THREAD

**Issue by shuqingzai** [gogf/gf#3789]
### Go version

go version go1.21.13 darwin/amd64

### GoFrame version

2.7.3

### Can this bug be reproduced with the latest release?

Option Yes

### What did you do?

在 `2.7.2` 以下代码运行正常，但是 `2.7.3` 解析请求参数错误

`config.yaml`

```yaml
server:
  address:     ":8199"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
```

`main.go`

```go
package main

import (
	"context"

	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/net/ghttp"
)

type ItemInput struct {
	ItemFirst
}

type ItemSecondThird struct {
	// SecondID ...
	SecondID uint64 `json:"secondId,string" dc:"SecondID" v:"required"`
	// ThirdID ...
	ThirdID uint64 `json:"thirdId,string" dc:"ThirdID" v:"required"`
}

type ItemFirst struct {
	// ID ID
	ID uint64 `json:"id,string" dc:"ID"`

	ItemSecondThird
}

type HelloReq struct {
	g.Meta `path:"/hello" method:"GET"`

	ItemInput
}
type HelloRes struct {
	ItemInput
}

type Hello struct{}

func (Hello) Say(ctx context.Context, req *HelloReq) (res *HelloRes, err error) {
	g.Log().Debugf(ctx, `receive say: %+v`, req)
	res = &HelloRes{
		ItemInput: req.ItemInput,
	}
	return
}

func main() {
	s := g.Server()
	s.Use(ghttp.MiddlewareHandlerResponse)
	s.Group("/", func(group *ghttp.RouterGroup) {
		group.Bind(
			new(Hello),
		)
	})
	s.Run()
}
```

### What did you see happen?

分别使用不同版本启动服务，得到不同的响应结果

使用请求

```bash
curl -X GET 'http://127.0.0.1:8199/hello?id=&secondId=157889372459384832&thirdId=157889372459384833' \
-H 'Host: 127.0.0.1:8199'
```

1. `2.7.2`

正确解析请求参数 `secondId`

```json
{"code":0,"message":"","data":{"id":"0","secondId":"157889372459384832","thirdId":"157889372459384833"}}
```
3. `2.7.3`

没有正确解析请求参数 `secondId` ，甚至说试多几次，有时候 `thirdId` 的值会被赋值到 `secondId` ，值被缓存？？

```json
{"code":0,"message":"","data":{"id":"0","secondId":"0","thirdId":"157889372459384833"}}
```

### What did you expect to see?

参数被正确解析

**Comment by wln32** [comment]
@shuqingzai @gqcn 
目前已经找到真实原因了，竟是slice扩容机制导致的，这个bug非常有意思
![image](https://github.com/user-attachments/assets/3d6cb923-473d-4955-8a86-7c1276e64547)


下面是我打印不同字段的切片的详细信息
可以看到最后两个字段，切片的地址是相同的，在before的时候，也就是调用structInfo.AddField之前，由于len<cap，
SecondID扩容之后变成[1 0 1 0]，由于ThirdID和SecondID的引用的相同的地址，ThirdID扩容会切片会变成[1 0 1 1]，
覆盖了SecondID的索引信息，导致参数解析失败
![image](https://github.com/user-attachments/assets/6325acd7-f880-48e6-ae6a-be834d983041)

@shuqingzai 如果对2.7.3没有特别需求，暂时退到2.7.2版本

**Comment by wln32** [comment]
> @shuqingzai @gqcn 目前已经找到真实原因了，竟是slice扩容机制导致的，这个bug非常有意思 ![image](https://private-user-images.githubusercontent.com/49137144/369721902-3d6cb923-473d-4955-8a86-7c1276e64547.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNDY3MDksIm5iZiI6MTcyNzA0NjQwOSwicGF0aCI6Ii80OTEzNzE0NC8zNjk3MjE5MDItM2Q2Y2I5MjMtNDczZC00OTU1LThhODYtN2MxMjc2ZTY0NTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIyVDIzMDY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzNjAzNTgxMDdkMjZlYzk5NzkzY2QzNjJlMzdiNWQyN2M4Mzc0YjgxNjY4YjE4OTcxNWZiYzZkNTU3MDQzY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.B7wWhBcWgWKUIlPoO0_AsBflR8q8hSqo83Fis5mP1ec)
> 
> 下面是我打印不同字段的切片的详细信息 可以看到最后两个字段，切片的地址是相同的，在before的时候，也就是调用structInfo.AddField之前，由于len<cap， SecondID扩容之后变成[1 0 1 0]，由于ThirdID和SecondID的引用的相同的地址，ThirdID扩容会切片会变成[1 0 1 1]， 覆盖了SecondID的索引信息，导致参数解析失败 ![image](https://private-user-images.githubusercontent.com/49137144/369721747-6325acd7-f880-48e6-ae6a-be834d983041.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNDY3MDksIm5iZiI6MTcyNzA0NjQwOSwicGF0aCI6Ii80OTEzNzE0NC8zNjk3MjE3NDctNjMyNWFjZDctZjg4MC00OGU2LWFlNmEtYmU4MzRkOTgzMDQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIyVDIzMDY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjYzExNjNjNWUyNDBlOTMyMGE5ZTBjMTZlZTU2YmQ5OGZiYTRiNGY2MDI4M2I3ZGUzMTA1ZTM3OWJiNjM4OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1iayo14olicpDtuLhPQ8162UqscD2aXvQaGLPnbXEOc)
> 
> @shuqingzai 如果对2.7.3没有特别需求，暂时退到2.7.2版本
