### ISSUE TITLE
关于gtoken对比gf-jwt的一些疑问

### ISSUE THREAD

**Issue by joyoes** [gogf/gf#379]
https://github.com/goflyfox/gtoken
号称gtoken有如下优势：
有效的避免了jwt服务端无法退出问题；
可以解决jwt无法作废已颁布的令牌；
用户扩展信息仍存储在服务端，可有效的减少传输空间；
gtoken支撑单点应用使用内存存储，也支持集群使用redis存储；
支持缓存自动续期，并且不需要客户端进行实现；
1、但如果用户扩展信息仍存储在服务端，同样也会增加服务端的压力呀
2、jwt服务端真的会有无法退出的问题吗？
3、难道JWT无法实现支持缓存自动续期？

**Comment by zcool321** [comment]
建议先了解下jwt机制，jwt主打是无状态并且没有在服务端存储任何信息；
jwt的优劣我网上找了一个文档可以参考（这种文章很多，可自行搜索）：https://www.cnblogs.com/yuanrw/p/10089796.html
其实了解他的优缺点你上面的问题就迎刃而解了；

问题1：jwt的数据都存储在token中，并且需要在header头携带，所以存储用户信息过多会导致http请求过大； 这个就需要平衡是存储在服务端还是传输了，只能说根据个人需求；gtoken建议存储在服务端；
问题2：由于jwt信息依赖http传输，所以无法真正退出客户端；
问题3：jwt有自动续期功能，但是为了安全，需要客户端额外开发实现，增加了客户端实现难度；

当然jwt已经广泛应用，他有他的特定使用场景和需求；

**Comment by zhaopengme** [comment]
1. gf-jwt 有好几种使用存储方式 header ,cookie,query等都可以,不一定要放到 header 里面
2.  jwt 是采用用户凭证,不是作为类似 sessio 的会话机制
3. gf-jwt  刷新 token,也就一个请求,肯定不会放到服务器端做.

**Comment by zhaopengme** [comment]
gtoken   支持缓存自动续期, 应该有安全风险吧.

**Comment by joyoes** [comment]
@zhaopengme @zcool321我认真思考了一下问题1，关于gf-jwt存储用户信息过多会导致http请求过大的问题：我的思路是把jwt的token做hash后存储在数据库，把hash传给客户端，这样就增加了安全性，也减少了http请求体量过大的问题

**Comment by zcool321** [comment]
> @zhaopengme @zcool321 我认真思考了一下问题1，关于gf-jwt存储用户信息过多会导致http请求过大的问题：我的思路是把jwt的token做hash后存储在数据库，把hash传给客户端，这样就增加了安全性，也减少了http请求体量过大的问题，两位大佬觉得我的这个想法好不好？

这样做已经失去了jwt的意义，数据库存储就需要进行维护，如登出，用户过期等；
而且你会发现改着改着就是已经实现的轮子了，有gsession，gf-jwt，gtoken先了解对比下吧；
