### ISSUE TITLE
How to get key value from another namespace in Apollo configuration?

### ISSUE THREAD

**Issue by cindoralla** [gogf/gf#3793]
### What do you want to ask?

Hello, I want to know how to get key value from another namespace in Apollo configuration center.
Thanks.

**Comment by gqcn** [comment]
@cindoralla Hello, you can use different configuration object that bound different apollo namespace. For examle:
```go
apolloNs11 := gcfg.NewWithAdapter(apollo.New(ctx, apolloConfigNs1))
apolloNs2 := gcfg.NewWithAdapter(apollo.New(ctx, apolloConfigNs2))
```
