### ISSUE TITLE
response.WriteHeader on hijacked connection from github.com/gogf/gf/net/ghttp.(*ResponseWriter).OutputBuffer (ghttp_response_writer.go:54)  Stack:

### ISSUE THREAD

**Issue by manyanxing** [gogf/gf#381]
### 1. What version of `Go` and system type/arch are you using?
1.12.9

### 2. What version of `GoFrame` are you using?
1.9.10

### 3. Can this issue be reproduced with the latest release?
no

### 4. What did you do?
2019-10-28 15:06:24.942 17656: http server started listening on [:80]
2019-10-28 15:06:40.325 [ERRO] http: response.WriteHeader on hijacked connection from github.com/gogf/gf/net/ghttp.(*ResponseWriter).OutputBuffer (ghttp_response_writer.go:54) 
Stack:
1.  github.com/gogf/gf/net/ghttp.(*ResponseWriter).OutputBuffer
    D:/Go_WorkSpace/mahjgoServer/vendor/pkg/mod/github.com/gogf/gf@v1.9.10/net/ghttp/ghttp_response_writer.go:54
2.  github.com/gogf/gf/net/ghttp.(*Response).Output
    D:/Go_WorkSpace/mahjgoServer/vendor/pkg/mod/github.com/gogf/gf@v1.9.10/net/ghttp/ghttp_response.go:239
3.  github.com/gogf/gf/net/ghttp.(*Server).handleRequest
    D:/Go_WorkSpace/mahjgoServer/vendor/pkg/mod/github.com/gogf/gf@v1.9.10/net/ghttp/ghttp_server_handler.go:166
4.  github.com/gogf/gf/net/ghttp.(*Server).defaultHttpHandle
    D:/Go_WorkSpace/mahjgoServer/vendor/pkg/mod/github.com/gogf/gf@v1.9.10/net/ghttp/ghttp_server_handler.go:36

### 5. What did you expect to see?

package main

import (
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/net/ghttp"
	"github.com/gogf/gf/os/gfile"
	"github.com/gogf/gf/os/glog"
)

func main() {
	s := g.Server()
	s.BindHandler("/ws", func(r *ghttp.Request) {
		ws, err := r.WebSocket()
		if err != nil {
			glog.Error(err)
			r.Exit()
		}
		for {
			msgType, msg, err := ws.ReadMessage()
			if err != nil {
				return
			}
			if err = ws.WriteMessage(msgType, msg); err != nil {
				return
			}
		}
	})
	s.SetServerRoot(gfile.MainPkgPath())
	s.SetPort(80)
	s.Run()
}

**Comment by tonyzzp** [comment]
我也遇到同样的问题

**Comment by johngcn** [comment]
@manyanxing @tonyzzp 请更新到最新的`v1.10.0`试试
