### ISSUE TITLE
database/ gdb:How to use a hook function to add the 'explain' keyword

### ISSUE THREAD

**Issue by weimx2023** [gogf/gf#3816]
### What do you want to ask?

How to use a hook function to add the 'explain' keyword before a query statement and obtain the execution results?
```
	var hook = gdb.HookHandler{
		Select: func(ctx context.Context, in *gdb.HookSelectInput) (result gdb.Result, err error) {
			result, err = in.Next(ctx)
			if err != nil {
				return
			}
			explainSQL := "EXPLAIN " + in.Sql
			g.Log().Debug(ctx, "HookHandler-----", explainSQL)
			// Run EXPLAIN
			// Save EXPLAIN result to file
			return
		},
	}
```

**Comment by gqcn** [comment]
@weimx2023 When you execute `explain` statement, you might need complete sql statement for that. But here in `select hook` there are prepared `sql` and `args`, so you should note the `Sql` and `Args` attributes in `in *gdb.HookSelectInput`.

Another way to meet your requirement is using customized driver that embeds basic mysql driver, and you can custom interface implements like `DoQuery/DoExec`, which might be more easy for you.

**Comment by weimx2023** [comment]
Thank you very much for your explanation. I have used the Raw method to execute the SQL statement with added 'explain', and I have obtained the correct results.
```
			explainSQL := "EXPLAIN " + in.Sql
			var records []*Record
			err = g.Model().Raw(explainSQL, in.Args).Scan(&records)
			if err != nil {
				return
			}
```
