### ISSUE TITLE
gf/v2: Please give me a usage scenario. Is this framework currently satisfactory?

### ISSUE THREAD

**Issue by JiaLiangoooo** [gogf/gf#3833]
### What do you want to ask?

非常感谢提供这么优秀的框架，我也阅读了相关demo和提供的文档，但是目前我在使用的时候有一个场景，不知道gf是否支持

`使用方式`：单仓多模
`使用场景`：两个服务，app1  app2， 两个只在一个宿主机上运行，假设app1的端口是1000，app2的端口是1002，不使用服务注册（资源很紧张），准备使用HTTP协议进行通信。
目前app1有一个接口
```
type HelloReq struct {
	g.Meta `path:"/user/hello" method:"get" tags:"UserService" summary:"Get the profile of current user"`
	Text   string `json:"text" v:"required"`
}
type HelloRes struct {
	Content string `json:"content"`
}

```

使用app2调用app1的hello协议。目前想到的只有使用 `g.Client().GetContent(ctx, `http://xxxxx:1000/user/hello`)` ，此时返回的是一个string，需要client端再做解析。

问题： 既然api可以多个模块之之间互相调用，是否支持直接生成一个app1中api的http客户端，对api接口直接调用. 像rpc调用直接可以返回`HelloRes `?

**Comment by gqcn** [comment]
@JiaLiangoooo 你好，首先框架是按照模块化低藕设计的，每个模块可以单独使用。你描述的场景其实是框架提供的单仓管理模式，也支持根据每个服务生成对应的客户端SDK。具体可以参考以下两篇文档：
- https://goframe.org/pages/viewpage.action?pageId=87246764
- https://goframe.org/pages/viewpage.action?pageId=93880327
