### ISSUE TITLE
关于gfsnotify模块的一些建议

### ISSUE THREAD

**Issue by kuiye** [gogf/gf#384]
1.希望gfsnotify可以添加通配符形式的文件监控形式
例如
/log/logs/game.*.txt
这样可以忽略一些不需要监控的文件

2.希望gfsnotify可以添加变化内容的callbak

**Comment by johngcn** [comment]
@kuiye 第2点麻烦详细描述一下。

**Comment by kuiye** [comment]
比如文件追加了1111内容
现在只能通过记录上一次的读取的节点和最新节点然后输出1111
希望是有个方法能直接抛出1111

**Comment by johngcn** [comment]
@kuiye 哈哈，那个没办法的，第一点倒是不错的建议。

**Comment by kuiye** [comment]
> @kuiye 哈哈，那个没办法的，第一点倒是不错的建议。

那能抛出最后的字节数吗

**Comment by kuiye** [comment]
那能抛出最后的字节数吗

**Comment by johngcn** [comment]
> 那能抛出最后的字节数吗

那个不是`gfsnotify`做的事情，你可以在注册的回调函数中调用`gfile`来获取。

**Comment by kuiye** [comment]
OK

**Comment by JGbooks** [comment]
希望能新增监控过滤器，例如：对linux系统的根目录进行监控时，可以配置忽略/dev,proc等非必要目录
