### ISSUE TITLE
os/gcron: Let gcron.AddSingleton supports singletons in distributed environments

### ISSUE THREAD

**Issue by LanceAdd** [gogf/gf#3846]
### Is your feature request related to a problem?

Option No

### Describe the solution you'd like

```
func AddSingleton(ctx context.Context, pattern string, enableDistributedSingleton boolean, job JobFunc, name ...string) (*Entry, error) {

```
```
	gcron.AddSingleton(gctx.GetInitCtx(), "@every 10s", true, func(ctx context.Context) {
		g.Redis().Incr(ctx, "task")
	}, "incr")
```

### Describe alternatives you've considered

When I have a lot of horizontally scaled service nodes, they are exactly the same, all running the same scheduled tasks, I want only one task to be executed at the same time, I don't want to introduce additional message queues like kafaka, and only use the existing redis to implement distributed locks, I can do this by using Redis Nx in the task code, but I'm not sure if it's necessary for Gcron to implement such a distributed singleton directly

**Comment by gqcn** [comment]
@LanceAdd You can control the singleton logic in your cron job.
