### ISSUE TITLE
gf/net/ghttp: A potential reflection code bug

### ISSUE THREAD

**Issue by weimx2023** [gogf/gf#3860]
### Go version

go version go1.22.5 windows/amd64

### GoFrame version

v2.7.2

### Can this bug be reproduced with the latest release?

Option Yes

### What did you do?

```
func (a *cRotation) Create(ctx context.Context, req RotationReq) (*RotationRes, error) {
	g.Log().Debug(ctx, "Creating rotation item")
	return &RotationRes{RotationId: 1}, nil
}
```
When the second parameter of the function is not a pointer type, this code segment throws an error, even though GoFrame currently requires the second parameter of the function to be a pointer type.
```
func createRouterFunc(funcInfo handlerFuncInfo) func(r *Request) {
	return func(r *Request) {
		var (
			ok          bool
			err         error
			inputValues = []reflect.Value{
				reflect.ValueOf(r.Context()),
			}
		)
		if funcInfo.Type.NumIn() == 2 {
			var inputObject reflect.Value
			if funcInfo.Type.In(1).Kind() == reflect.Ptr {
				inputObject = reflect.New(funcInfo.Type.In(1).Elem())
				r.error = r.Parse(inputObject.Interface())
			} else {
				inputObject = reflect.New(funcInfo.Type.In(1).Elem()).Elem() // This line of potential reflection may cause an exception.
				r.error = r.Parse(inputObject.Addr().Interface())
			}
			if r.error != nil {
				return
			}
			inputValues = append(inputValues, inputObject)
		}
		// Call handler with dynamic created parameter values.
		results := funcInfo.Value.Call(inputValues)
		switch len(results) {
		case 1:
			if !results[0].IsNil() {
				if err, ok = results[0].Interface().(error); ok {
					r.error = err
				}
			}

		case 2:
			r.handlerResponse = results[0].Interface()
			if !results[1].IsNil() {
				if err, ok = results[1].Interface().(error); ok {
					r.error = err
				}
			}
		}
	}
}
```

### What did you see happen?

goroutine 1 [running]:
reflect.elem(0x7a2185?)
	C:/Users/Administrator/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.windows-amd64/src/reflect/type.go:737 +0x9a
reflect.(*rtype).Elem(0xae3500?)
	C:/Users/Administrator/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.windows-amd64/src/reflect/type.go:741 +0x15
main.(*funcRegistry).call(0xc0001d9d78?, 0x1?, {0xc02698, 0xc0001fea20}, {0xb8693a, 0x5f})

### What did you expect to see?

Convert this line of code, or remove this logic.

old
```
		if funcInfo.Type.In(1).Kind() == reflect.Ptr {
				inputObject = reflect.New(funcInfo.Type.In(1).Elem())
				r.error = r.Parse(inputObject.Interface())
			} else {
				inputObject = reflect.New(funcInfo.Type.In(1).Elem()).Elem()
				r.error = r.Parse(inputObject.Addr().Interface())
			}
```
fixed
```
		if funcInfo.Type.In(1).Kind() == reflect.Ptr {
				inputObject = reflect.New(funcInfo.Type.In(1).Elem())
				r.error = r.Parse(inputObject.Interface())
			} else {
				inputObject = reflect.New(funcInfo.Type.In(1)).Elem()
				r.error = r.Parse(inputObject.Addr().Interface())
			}
```

**Comment by gqcn** [comment]
@weimx2023 Hello, the strict route registering requires the input request parameter object to be a pointer. The value type of object is not support.

**Comment by weimx2023** [comment]
@gqcn I know that currently the parameters do checksums and have to be passed in as pointers, but an if branch that could go wrong could be problematic in future versions, so I think it needs to be written in the correct form
