### ISSUE TITLE
gf/net/gclient: The DoRequestObj function does not process the query parameters on non-GET requests

### ISSUE THREAD

**Issue by LanceAdd** [gogf/gf#3861]
### Go version

go version go1.22.7 darwin/amd64

### GoFrame version

2.7.4

### Can this bug be reproduced with the latest release?

Option Yes

### What did you do?

```golang
package main

import (
	"fmt"
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gctx"
	"time"
)

type ChartUpdateReq struct {
	g.Meta  `path:"/chart/check/{id}" method:"post"`
	Id      string
	Code    string `p:"code"`
	Version string `json:"version"`
}

type ChartUpdateRes struct {
	Name         string    `json:"name"`
	Url          string    `json:"url"`
	Size         int64     `json:"size"`
	Md5          string    `json:"md5"`
	ChartCode    string    `json:"chartCode"`
	ChartVersion time.Time `json:"chartVersion"`
}

func main() {
	req := ChartUpdateReq{Code: "11", Id: "1"}
	res := &ChartUpdateRes{}
	err := g.Client().Prefix("http://127.0.0.1:50000").DoRequestObj(gctx.GetInitCtx(), req, res)
	fmt.Println(err)
	fmt.Println(res)
}

```
Now URL
```
http://127.0.0.1:50000/chart/check/1
```
Expect URL
```
http://127.0.0.1:50000/chart/check/1?code=11
```

### What did you see happen?

Query parameters (http://xxxx.com?code=11) are built only if content-type is not `application/json`and `application/xml`.

 I think it would be more rigorous for the user to tag the fields in request struct to mark the parameter types (query parameters /json/ path parameters). 

These tags are not handled in the current logic, and I'm not sure if this is for some special reason or if you want users to handle the logic themselves. If there is no special reason, I am ready to submit PR to implement my idea

### What did you expect to see?

Now URL
```
http://127.0.0.1:50000/chart/check/1
```
Expect URL
```
http://127.0.0.1:50000/chart/check/1?code=11
```

**Comment by wwwfeng** [comment]
`g.Meta  `path:"/chart/check/{id}" method:"post"``
method改为get 要不然就是post请求

**Comment by LanceAdd** [comment]
> `g.Meta `path:"/chart/check/{id}" method:"post"`` `method`改为`get` 要不然就是`post`请求
我知道改成get是会去处理查询的参数，但是我现在遇到的情况是需要post/put/patch这三类
现在就是在post的请求下，同时有查询参数、路径参数、请求体参数三种参数时，这时候并不会构建查询参数，只会处理路径参数和请求体参数，我希望他能在post中也去构建查询参数，使用tag标记下就可以区分，想问下这个在实现的时候是故意这么设计的还是没处理，如果只是没处理我就提个PR处理下

**Comment by LanceAdd** [comment]
@wwwfeng 我知道改成get是会去处理查询的参数，但是我现在遇到的情况是需要post/put/patch这三类
现在就是在post的请求下，同时有查询参数、路径参数、请求体参数三种参数时，这时候并不会构建查询参数，只会处理路径参数和请求体参数，我希望他能在post中也去构建查询参数，使用tag标记下就可以区分，想问下这个在实现的时候是故意这么设计的还是没处理，如果只是没处理我就提个PR处理下

**Comment by LanceAdd** [comment]
我看着这个DoRequestObj的注释上也说`DoRequestObj does HTTP request using standard request/response object.`但是其中的参数并未严格按照规范路由的解析流程，应该用tag标注出来每个参数是路径参数/查询参数/请求体参数然后再去解析这些吧

**Comment by gqcn** [comment]
> @wwwfeng 我知道改成get是会去处理查询的参数，但是我现在遇到的情况是需要post/put/patch这三类 现在就是在post的请求下，同时有查询参数、路径参数、请求体参数三种参数时，这时候并不会构建查询参数，只会处理路径参数和请求体参数，我希望他能在post中也去构建查询参数，使用tag标记下就可以区分，想问下这个在实现的时候是故意这么设计的还是没处理，如果只是没处理我就提个PR处理下

你好，目前`DoRequestObj`只会处理`path`和`body`参数，不会对请求结构体中的`in`标签进行解析，若有需要环境提pr来支持。

**Comment by LanceAdd** [comment]
> > @wwwfeng 我知道改成get是会去处理查询的参数，但是我现在遇到的情况是需要post/put/patch这三类 现在就是在post的请求下，同时有查询参数、路径参数、请求体参数三种参数时，这时候并不会构建查询参数，只会处理路径参数和请求体参数，我希望他能在post中也去构建查询参数，使用tag标记下就可以区分，想问下这个在实现的时候是故意这么设计的还是没处理，如果只是没处理我就提个PR处理下
> 
> 你好，目前`DoRequestObj`只会处理`path`和`body`参数，不会对请求结构体中的`in`标签进行解析，若有需要环境提pr来支持。

你好，我在修改现有DoRequestObj 支持这个issues，我个人希望直接使用规范路由请求体作为DoRequestObj的参数，这样方便大家在微服务远程调用中直接使用请求目标项目的req entity，现在其中关于上传文件这部分，现有DoRequestObj底层和其他request一样的`prepareRequest`，使用`@file:`,  `"upload-file=@file:"+path`这样的形式进行支持，但是规范路由中则是通过`ghttp.UploadFile`和`ghttp.UploadFiles`配合tag中`type:file`使用，是否需要保留现有的`@file`形式，我个人觉得DoRequestObj没必要去兼容这样的形式，但是不清楚大家有没有其他的想法，想问下各位
