### ISSUE TITLE
net/ghttp: 接口或 enums 越多，构建的二进制文件内容大小激增

### ISSUE THREAD

**Issue by shuqingzai** [gogf/gf#3863]
### Go version

go version go1.21.13 darwin/amd64

### GoFrame version

2.7.3

### Can this bug be reproduced with the latest release?

Option Yes

### What did you do?

当项目接口越多或 enums 越多时，编译文件会变得非常大，我不清楚是 ghttp 还是 enums 的问题，当接口只有少量时，不明显，但是对比使用其它 http 组件也大得很

### What did you see happen?

线上项目

1. 编译前期项目只有 “200M”（这其实很夸张了~~~）
![image](https://github.com/user-attachments/assets/f5f29f23-8c0b-42fa-9421-02fa57db02e6)

使用 [Zxilly/go-size-analyzer](https://github.com/Zxilly/go-size-analyzer) 分析，`rodata` 有 40多 M
![image](https://github.com/user-attachments/assets/b8e2e859-11ab-43f7-82df-bc3c5ecd7c7f)

2. 当我往项目添加更多接口，接口包含许多 enums 时，编译的二进制文件非常夸张（注意：这期间并没有添加其他更多的第三方包之类，最大的改动仅仅是添加更多接口与 enums

![image](https://github.com/user-attachments/assets/dca9d426-a1ed-4b17-b7da-473eb9510769)

最后完成了一个比较大的需求（多了 接口 和 enums），二进制文件居然达到 700MB ，这离得破 G 不远了

![image](https://github.com/user-attachments/assets/29eac8fe-bf49-47ac-8053-ef30c6081da0)

`__rodata __TEXT` 有 400多 M

![image](https://github.com/user-attachments/assets/1ff82c26-154e-4e60-82e5-a2a5c226d166)

### What did you expect to see?

编译文件的容量十分夸张

**Comment by ninjashixuan** [comment]
生成 enums 时注意不要扫描全部代码只扫描定义 enums 的文件，不然就生成一堆无用的。 接口多的问题生产环境不要配置openApiPath 自然不会生成 swagger 文档，因为接口多这些swagger openapi 这些文本不小。

**Comment by gqcn** [comment]
@shuqingzai @ninjashixuan 可以使用`prefixes`配置参数来控制只生成指定前缀的`enums`，具体请参考文档 https://goframe.org/docs/cli/gen-enums
