### ISSUE TITLE
database/gdb/gdb_func.go

### ISSUE THREAD

**Issue by cbtan** [gogf/gf#3866]
### Is your feature request related to a problem?
Option Yes

### Describe the solution you'd like

数据库是:   SQLSERVER 2008  r2
文件路径： database/gdb/gdb_func.go
函数名 ： getFieldsFromStructOrMap

`if ormTagValue != ""   && gregex.IsMatchString(regularFieldNameRegPattern, ormTagValue) {
				fields = append(fields, ormTagValue)
			} else {
				fields = append(fields, structField.Name())
			}`

### Describe alternatives you've considered

这里限制了不支持中文

**Comment by gqcn** [comment]
这个issue没有描述清楚，我猜测应该是需要ORM支持表名和字段名是中文字符。

**Comment by cbtan** [comment]
> 这个issue没有描述清楚，我猜测应该是需要ORM支持表名和字段名是中文字符。

对对对对对对对对对
