### ISSUE TITLE
goframe orm的一点建议

### ISSUE THREAD

**Issue by ghost** [gogf/gf#389]
之前用搭项目一直都用`gin` + `gorm`，非常喜欢`gorm`里面的preload方法，可以预加载其他表的数据，不用我再去使用`join`。我看了`GF`的文档好像没有找到这个，只有`join`可选。作者能不能考虑一下后期加入这个功能。

![图片](https://user-images.githubusercontent.com/22871086/68068353-c5f71b00-fd8e-11e9-9d6f-0a0dddf63a35.png)

**Comment by johngcn** [comment]
@0ytian 感谢建议，我研究一下
