### ISSUE TITLE
os/gcfg: Configure the caching mechanism?

### ISSUE THREAD

**Issue by dongdio** [gogf/gf#3909]
### What do you want to ask?

I am very strange that after modifying the configuration file, the startup program still reads the original configuration, even if the contents of the configuration file are deleted, it is still the original configuration,

config path: mainifest/config/config.yaml

Although the absolute path has been set, it is still invalid.
g.Cfg().GetAdapter().(*gcfg.AdapterFile).SetFileName("/xxx/xxx/xxx/config/config.yaml")

**Comment by gqcn** [comment]
You might using the packed config.yaml in youre resource manager. Please use `gres.Dump` to check.

**Comment by dongdio** [comment]
Surprised, it worked, thanks
