### ISSUE TITLE
使用 whereLT  decimal 类型列的问题

### ISSUE THREAD

**Issue by Weishan-Allen** [gogf/gf#3915]
### Go version

1.23.2

### GoFrame version

2.7.4

### Can this bug be reproduced with the latest release?

Option Yes

### What did you do?

使用	

var v []*entity.V
WhereLT(dao.x.Columns().a, gdb.Raw(dao.x.Columns().b)).Scan(&v)

数据库 a,b 均为 decimal 类型 且 a为0.00 并且b 是大于0.00的任意数
且表只有一条记录（应该关系不大）

### What did you see happen?

row 返回为0条记录

### What did you expect to see?

row 返回为1 

如果采用WhereGT 则可以正常返回 
var v []*entity.V
WhereGT(dao.x.Columns().b, gdb.Raw(dao.x.Columns().a)).Scan(&v)

数据库 a,b 均为 decimal 类型 且 a为0.00 并且b 是大于0.00的任意数
猜测应该是和 0值有关

**Comment by gqcn** [comment]
@Weishan-Allen 请给定可复现该问题的最小可运行代码。

**Comment by wwwfeng** [comment]
应该不是decimal的问题 `WhereLT(col,val)` 第二个参数是value 实际执行会变成一个值，然而你要求比较的是字段
应该使用`Where(gdb.Raw("`a`<`b`"))` 或 `Where(gdb.Raw("a<b"))`

**Comment by Weishan-Allen** [comment]
@gqcn  @wwwfeng  我修改了值证明了 确实如 @wwwfeng 所说一致，但打印出来sql非常有迷惑性。
``` go

type ScanTest struct {
	a float64
	b float64
}

func Test(ctx context.Context) {
	var scanTest *ScanTest
	err := dao.Test.Ctx(ctx).WhereLT("a", gdb.Raw("`b`")).Scan(&scanTest)
	if err != nil {
		return
	}
	// 日志:  [rows:0  ] SELECT `a`,`b` FROM `test` WHERE `a` < `b` LIMIT 1

	err = dao.Test.Ctx(ctx).WhereGT("b", gdb.Raw("`a`")).Scan(&scanTest)
	if err != nil {
		return
	}

	// 日志: [rows:1  ] SELECT `a`,`b` FROM `hg_test` WHERE `b` > `a` LIMIT 1
}
```

**Comment by Weishan-Allen** [comment]
这让我以为它正常的工作了，所以WhereGT or LT 不支持第二个参数使用gdb.Raw吗

**Comment by gqcn** [comment]
> 这让我以为它正常的工作了，所以WhereGT or LT 不支持第二个参数使用gdb.Raw吗

支持呀！你看你之前发的结果。

**Comment by Weishan-Allen** [comment]
> > 这让我以为它能正常工作了，所以 GT 或 LT 不支持使用 gdb.Raw 的个参数吗？
> 
> 支持呀！你看你之前得到的结果。

@gqcn 抱歉最近有点忙，我现在新开了一个项目 数据库表结构以及数据如下
![image](https://github.com/user-attachments/assets/7eb28ebe-0e56-494e-9a7b-0e16208aa700)

![image](https://github.com/user-attachments/assets/4f13ffea-491f-489f-b6ca-9f0ea2bd48d3)

很明显 a > b 的记录 和 b > a 的记录各一条

现在我写了个示例去查询 a < b  和 a > b 的例子 

```
type ScanTest struct {
	a float64
	b float64
}
func Test(ctx context.Context) {
	var LTTest = make([]ScanTest, 0)
	err := dao.WsTest.Ctx(ctx).WhereLT("a", gdb.Raw("`b`")).Scan(&LTTest)
	if err != nil {
		return err
	}

	var GTTest = make([]ScanTest, 0)
	err = dao.WsTest.Ctx(ctx).WhereGT("a", gdb.Raw("`b`")).Scan(&GTTest)
	if err != nil {
		return err
	}

	return nil
}
```
打印的日志:
```
2024-11-27 15:45:02.031 [DEBU] {200500558fc30b18c3c2490d602ca9fb} [  3 ms] [default] [toy] [rows:1  ] SHOW TABLES
2024-11-27 15:45:02.032 [DEBU] {200500558fc30b18c3c2490d602ca9fb} [  0 ms] [default] [toy] [rows:3  ] SHOW FULL COLUMNS FROM `ws_test`
2024-11-27 15:45:02.033 [DEBU] {200500558fc30b18c3c2490d602ca9fb} [  1 ms] [default] [toy] [rows:0  ] SELECT `a`,`b` FROM `ws_test` WHERE `a` < `b`
2024-11-27 15:45:02.033 [DEBU] {200500558fc30b18c3c2490d602ca9fb} [  0 ms] [default] [toy] [rows:2  ] SELECT `a`,`b` FROM `ws_test` WHERE `a` > `b`
```
这似乎并没有工作

**Comment by gqcn** [comment]
@Weishan-Allen 好的，我看看。
