### ISSUE TITLE
otelmetric v2.7.x version declaration relies on an incorrect golang version

### ISSUE THREAD

**Issue by muddydog** [gogf/gf#3917]
### Go version

go version go1.19.3 darwin/arm64

### GoFrame version

2.7.4

### Can this bug be reproduced with the latest release?

Option Yes

### What did you do?

想使用GF的指标监控功能，然后根据自己的golang版本（1.19），选择升级到了 GF v2.7.4 版本，并拉取了 contrib 中对应版本的 otelmetric 包。
`go get github.com/gogf/gf/contrib/metric/otelmetric/v2@v2.7.4`

编译项目时直接报错：
```
# github.com/prometheus/common/model
../../go/pkg/mod/github.com/prometheus/common@v0.48.0/model/metric.go:363:33: undefined: strings.CutPrefix
note: module requires Go 1.20
```

确认了一下 https://github.com/gogf/gf/blob/v2.7.4/contrib/metric/otelmetric/go.mod 中声明依赖的go版本为 1.18。
```
module github.com/gogf/gf/contrib/metric/otelmetric/v2

go 1.18

require (
	github.com/gogf/gf/v2 v2.7.4
	github.com/prometheus/client_golang v1.19.0
	go.opentelemetry.io/contrib/instrumentation/runtime v0.49.0
	go.opentelemetry.io/otel v1.24.0
	go.opentelemetry.io/otel/exporters/prometheus v0.46.0
	go.opentelemetry.io/otel/metric v1.24.0
	go.opentelemetry.io/otel/sdk v1.24.0
	go.opentelemetry.io/otel/sdk/metric v1.24.0
)
```

明显是错误的，应该是 1.20。这样的话 v2.7.x 版本的 otelmetric 就不可用了。

### What did you see happen?

如上

### What did you expect to see?

解决的思路：

1. 【保持依赖的Go版本为1.18】把 go.opentelemetry.io/otel 降到 v1.14.0 版本，把 go.opentelemetry.io/otel/exporters/prometheus 降到 v0.37.0 版本。
2. 更正GF v2.7.x版本依赖的go版本为 >= 1.20

**Comment by gqcn** [comment]
@muddydog Thanks for your feedback, we've promoted the minimum required golang version of goframe from `v1.18` to `1.20`.
