### ISSUE TITLE
gconv: The type conversion does not meet expectations

### ISSUE THREAD

**Issue by tianhendi** [gogf/gf#3918]
### Go version

go 1.22.6 windows/amd

### GoFrame version

2.7.4

### Can this bug be reproduced with the latest release?

Option Yes

### What did you do?

![微信图片_20241113151519](https://github.com/user-attachments/assets/b4409d44-a376-48df-8fa2-5568854b546b)

### What did you see happen?

浮点数类型的负数字符串，在执行类型转换后，负数变正了

### What did you expect to see?

能正常转换正负浮点数

**Comment by UncleChair** [comment]
@gqcn Found the float was not using minus in string
https://github.com/gogf/gf/blob/8c6db247b26e59c930e7fe07a1be6eb9e74cd991/util/gconv/gconv_int.go#L98
https://github.com/gogf/gf/blob/8c6db247b26e59c930e7fe07a1be6eb9e74cd991/util/gconv/gconv_int.go#L125-L129
