### ISSUE TITLE
orm insert 出现类似sql: expected 10 arguments, got 9的问题

### ISSUE THREAD

**Issue by zhengpeiqiang** [gogf/gf#392]
【代码片段】
![1](https://user-images.githubusercontent.com/37537489/68262166-65612a00-007d-11ea-856c-8ba06c4a6121.png)

【数据库该字段说明】
![2](https://user-images.githubusercontent.com/37537489/68262177-68f4b100-007d-11ea-8555-d666d6d36db6.png)

**Comment by johngcn** [comment]
@zhengpeiqiang 该问题是由于`gdb`将`[]byte`类型参数当做`slice`做了拆分导致的，我修复一下。

**Comment by johngcn** [comment]
@zhengpeiqiang 请更新到最新的`v1.10.0`试试。
