### ISSUE TITLE
cmd/gf: In the monorep-app created by using `gf init -a`, there is an error in the file `hack/hack.mk`

### ISSUE THREAD

**Issue by 0x7a7a** [gogf/gf#3939]
### Go version

go1.23.3

### GoFrame version

2.8.0

### Can this bug be reproduced with the latest release?

Option Yes

### What did you do?

gf init mymono/hello -a

### What did you see happen?

<img width="641" alt="image" src="https://github.com/user-attachments/assets/b57edf56-afac-49c3-87ff-808d26ccd90a">

### What did you expect to see?

`include hack-cli.mk` => `include hack/hack-cli.mk`

**Comment by 0x7a7a** [comment]
@gqcn The problem still exists, and the same situation occurs when creating a single repo.
<img width="608" alt="image" src="https://github.com/user-attachments/assets/b9c2f4d7-7c77-4075-ba89-502c90600be1">

**Comment by gqcn** [comment]
@0x7a7a Sorry, I cannot reproduce this issue, please confirm the cli version
<img width="830" alt="图片" src="https://github.com/user-attachments/assets/72e49e23-843b-4c65-adca-0457aad99b94">

**Comment by 0x7a7a** [comment]
@gqcn I'm sorry, after checking, I found it to be a problem with my gf cli version. 
Everything is working well now, thank you.
