### ISSUE TITLE
整个集成LDAP的插件呗

### ISSUE THREAD

**Issue by leopardxu** [gogf/gf#394]

**Comment by johngcn** [comment]
@leopardxu 麻烦描述一下你用到`LDAP`的场景呢。

**Comment by leopardxu** [comment]
开发一个公司内部使用的网站不都要集成LDAP嘛~~~

**Comment by ppabc** [comment]
@johngcn   有必要啊 LDAP 很常用，公司内网的项目

**Comment by forgethub** [comment]
请问有集成LDAP的计划吗

**Comment by gqcn** [comment]
@ppabc @leopardxu @forgethub 不好意思啊各位，暂时没这个计划，希望能有小伙伴贡献插件。

**Comment by forgethub** [comment]
我这段时间好好学习下，争取早日达到可以为开源项目添砖加瓦的能力
