### ISSUE TITLE
contrib/metric/otelmetric: More Prometheus monitoring for GC pause time and CPU usage

### ISSUE THREAD

**Issue by weimx2023** [gogf/gf#3958]
### What do you want to ask?

Here are some optimization metrics in Go based on business types:

Real-time Systems:

- GC pause time > 1ms needs optimization
- CPU usage > 5% needs optimization

Online Services:

- GC pause time > 10ms needs optimization
- CPU usage > 10% needs optimization

Batch Processing:

- GC pause time > 100ms needs optimization
- CPU usage > 20% needs optimization

Since GoFrame's Prometheus monitoring doesn't include these desired parameters, could you provide an example showing how to add these monitoring metrics? Thank you.

**Comment by gqcn** [comment]
@weimx2023 Hello, you may trace the source code here https://github.com/gogf/gf/blob/3797d0eee4a3fc015171c029a1f6d023aea7db38/contrib/metric/otelmetric/otelmetric_provider.go#L59 If the Metrics is necessary, it's appreciated if you can submit a PR to enhance this feature.
