### ISSUE TITLE
driver/pqsql: failed to execute 'go mod tidy'

### ISSUE THREAD

**Issue by byte911** [gogf/gf#3963]
### Go version

go version go1.23.3 darwin/arm64

### GoFrame version

v2.8.1

### Can this bug be reproduced with the latest release?

Option Yes

### What did you do?

Get the pgsql driver.

### What did you see happen?

`% go mod tidy

go: finding module for package github.com/gogf/gf/contrib/drivers/pysql/v2
go: demo imports
	github.com/gogf/gf/contrib/drivers/pysql/v2: module github.com/gogf/gf@latest found (v1.16.9), but does not contain package github.com/gogf/gf/contrib/drivers/pysql/v2
`

For the mysql driver. It runs ok.

### What did you expect to see?

Success after executed.

**Comment by gqcn** [comment]
@byte911 You should use goframe v2 instead of v1. Please check the import of `github.com/gogf/gf` in your codes, any `github.com/gogf/gf` should be replaced with `github.com/gogf/gf/v2`.

**Comment by byte911** [comment]
Sorry. It's my spelling error.

**Comment by byte911** [comment]
Sorry. It's my spelling error.
