### ISSUE TITLE
2.8 version ScanAndCount query problem

### ISSUE THREAD

**Issue by goodking-bq** [gogf/gf#3968]
### Go version

1.22.5

### GoFrame version

1.8。1

### Can this bug be reproduced with the latest release?

Option Yes

### What did you do?

当hook与ScanAndCount一起使用时，程序报错

![image](https://github.com/user-attachments/assets/bc9b4d4c-2bb2-4de3-a248-ea66bc4b573d)
相同的代码 在2.7版本没有问题。注释掉hook也没有问题。

### What did you see happen?

![image](https://github.com/user-attachments/assets/d1029636-28a6-4937-a748-9631c51239cb)

### What did you expect to see?

~

**Comment by gqcn** [comment]
@goodking-bq 收到反馈，请先回滚版本，咱们看看这个问题。
