### ISSUE TITLE
增加GetInt64()

### ISSUE THREAD

**Issue by CrazyRocks** [gogf/gf#397]
希望增加这个GetInt64()
SnowFlake做ID对应的是Bigint

**Comment by johngcn** [comment]
@CrazyRocks 如果是`ghttp.Request`对象的话在新版本中会增加`GetInt64`方法，当前你可以使用`r.GetVar().Int64()`来获得你想要的数据类型。

**Comment by johngcn** [comment]
@CrazyRocks 请更新到最新的`v1.10.0`试试。
