### ISSUE TITLE
gcache:add callback func before data expired when remove it 

### ISSUE THREAD

**Issue by tianyixueshi** [gogf/gf#3971]
### Is your feature request related to a problem?

Option Yes

### Describe the solution you'd like

I use  gcache stroe  a struct  contains a chan for  special web session used. when struct expired,  i cannt close then chann before it removed. 
so , can add a callback func   when removed it

### Describe alternatives you've considered

when set a cache,  can add a optional  call fun

**Comment by yzy613** [comment]
This is not recommended because gcache is designed as an interface. If this interface is opened, can the same operation be applied to redis?

**Comment by gqcn** [comment]
- One point is as @yzy613  said.
- Another point is, the custom callback function night delay the deleting of the expired item, which could cause timeout or unexpected issue.
