### ISSUE TITLE
gvalid 增加自定义验证

### ISSUE THREAD

**Issue by ZhangIvan** [gogf/gf#398]
查看gf的gvalid源码，发现都是靠正则类进行强大的验证功能，校验种类很齐全。
但好像未发现支持自定义方法去生成校验，虽然也可以在请求中去单独实现校验，可还是觉得gvalid有点不完美；

个人目前用得还是beego的valid，觉得挺好用的，gf若有空可以考虑下哦，感谢作者！

![image](https://user-images.githubusercontent.com/25630763/69028473-0e5c3d00-0a0d-11ea-96eb-2941928bba05.png)

**Comment by johngcn** [comment]
@ZhangIvan 这块之前有类似的`issue`建议，后续会增加自定义校验功能，目前可以考虑使用自定义正则校验实现。

**Comment by gqcn** [comment]
@ZhangIvan https://goframe.org/util/gvalid/customrule
