### ISSUE TITLE
建议gtime多一些使用的小例子

### ISSUE THREAD

**Issue by xinjiayu** [gogf/gf#399]
https://goframe.org/os/gtime/index

调用的方式，建议多写一些例子，虽然参考php，但是还是有一些不同的。

**Comment by xinjiayu** [comment]
https://goframe.org/os/gtime/index

这个页面下，增加一些使用的例子，比如：gtime.Now().Format("j")

**Comment by ppabc** [comment]
gtime 怎么加时间?有例子吗？比如我想加30分钟，加6小时，这个怎么加？
@johngcn johngcn

**Comment by ppabc** [comment]
gtime.Now()貌似获取的是机器的硬件时间，如何获取系统时间呢？系统时间和硬件时间不一样

**Comment by johngcn** [comment]
@ppabc 不太确定你所说的硬件时间是怎么回事，`gtime.Now`的行为和`time.Now`的行为是一致的，你可以看看`time.Now`是否满足你的期望。

**Comment by johngcn** [comment]
> gtime 怎么加时间?有例子吗？比如我想加30分钟，加6小时，这个怎么加？
> @johngcn johngcn
> fmt.Println(gtime.Now().Add(+6).Format("Y-m-d H:i:s"))
> 这样不行

`Add(time.Hour*6)`注意参数类型为`time.Duration`
