### ISSUE TITLE
希望 gstr 中增加 ReplaceI 忽视大小写的替换方法, 和 ContainsI 配合使用

### ISSUE THREAD

**Issue by IGGAbc** [gogf/gf#40]
希望 gstr 中增加 ReplaceI 忽视大小写的替换方法, 和 ContainsI 配合使用

**Comment by johngcn** [comment]
@IGGAbc 已增加 `ReplaceI/ReplaceIByArray/ReplaceIByMap`字符串大小写非敏感替换方法，请更新最新框架代码试试。
