### ISSUE TITLE
数据库读取数据，结构转化失败问题。

### ISSUE THREAD

**Issue by mszero** [gogf/gf#400]
### 1. What version of `Go` and system type/arch are you using?
1.12

### 2. What version of `GoFrame` are you using?
laster

### 4. What did you do?

从数据库中获取到数据，转化成JSON失败问题。是因为里面存在字符串，没有进行转化。

如
```go
type SkuList struct {
	ProductList
	// 增加数量
	Num int `json:"num"`
}

// 订单列表转化
type GetOrderList struct {
	Base
	UserID int `json:"user_id"`
	// 产品信息JSON字符串（string)类型
	SkuList []SkuList `json:"sku_list"`
}

res , ..... select()....
res.Structs(&dataList)
```
..以上没有办法转化。

**Comment by johngcn** [comment]
@mszero 给定完整的最小运行示例，可以把数据表结构，示例数据和程序发出来。此外，我看你的属性中有`SkuList []SkuList`，这个属性没办法转换，基本属性和对象可以。

**Comment by gqcn** [comment]
@mszero 问题信息不够明确，请提供更详细信息再`reopen`。
