### ISSUE TITLE
旧版本升1.9.10后报空指针

### ISSUE THREAD

**Issue by jetlwx** [gogf/gf#401]
### 1. What version of `Go` and system type/arch are you using?
go version
go version go1.12.7 linux/amd64

### 2. What version of `GoFrame` are you using?
const VERSION = "v1.9.10"

### 4. What did you do?
报错信息：(以下信息在更新至1.9.10后并重启电脑后出现)
----------|---------|---------|--------|---|------------------------------|-------------------------------------------------------------------|--------------
  default |  :9000  | default | GET    | 3 | /privilege/userAdmin/useradd | github.com/jetlwx/src/coamp/portal/app/api/privilege.UserAdminAdd |              
----------|---------|---------|--------|---|------------------------------|-------------------------------------------------------------------|--------------

2019-11-20 21:11:21.467 [ERRO] 500, "GET http localhost:9000 / HTTP/1.1" 0.255, [::1], "", "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/73.0.3683.103 Chrome/73.0.3683.103 Safari/537.36"
Stack:
1. runtime error: invalid memory address or nil pointer dereference
   1).  github.com/jetlwx/src/coamp/portal/app/api/portal.LoginIndex
    	/data/go/gopath/src/github.com/jetlwx/src/coamp/portal/app/api/portal/portal.go:16
----------------------------------------------------------------
对应错误行代码：portal.go:16
func LoginIndex(r *ghttp.Request) {
	r.Response.WriteTpl("login.html")
}
----------------------------------------------------------------------------
相应文件信息：
router.go
func init() {
	//	g.Server().BindHandler("/", a_k8s.PodIndex)
	s := g.Server()
	s.BindHandler("/", portal.LoginIndex)

boot.go

func init() {
	c := g.Config()
	s := g.Server()
	c.SetFileName("conf.toml")
	glog.SetStdoutPrint(true)
	s.SetAccessLogEnabled(true)
	s.SetErrorLogEnabled(true)
	s.SetLogStdout(true)
	g.SetDebug(true)
	s.SetServerRoot("public")
	s.SetPort(c.GetInt("http-port"))
	s.EnableAdmin()
	g.DB().SetDebug(true)
---------------------------------------------------------

**Comment by johngcn** [comment]
@jetlwx 信息量太少无法定位问题原因，建议使用goland逐步调试看哪个变量是空指针，也有可能是某个属性是空指针造成的这个错误。

**Comment by johngcn** [comment]
@jetlwx 请更新到最新的`v1.10.0`再试试呢。
