### ISSUE TITLE
database/gdb: pgsql driver cannot connect when using unix domain

### ISSUE THREAD

**Issue by d9ee** [gogf/gf#4018]
### Go version

1.23.4

### GoFrame version

2.8.1

### Can this bug be reproduced with the latest release?

Option Yes

### What did you do?

database:
  default:
    link:  "pgsql:username:password@unix(/run/postgresql)/dbname"

### What did you see happen?

Error: dial unix /run/postgresql/.s.PGSQL.sslmode=disable: connect: no such file or directory 

### What did you expect to see?

similar to  #3862 but pgsql

**Comment by gqcn** [comment]
@d9ee Thanks for your feedback, let me have a check.
