### ISSUE TITLE
gf官网建议

### ISSUE THREAD

**Issue by ZhangIvan** [gogf/gf#403]
在[gf官网](https://goframe.org)大部分文档中都是直接贴代码告之如何使用，新手的话可能无法直接感受具体运行流程，想起以前学习的时候，首先告诉我们的是方法的生命周期，流程怎么走的,嘿嘿；

建议作者劳累在路由版块新增点请求处理流程图，对新手更友好的理解gf的设计，加深代码理解，当然，其他的模块也可以看着弄下，如果不耽误时间的话，哈哈

推荐可以看下Python的哈
[Django](https://www.jianshu.com/p/a4ab257e87f1)
[Django](https://www.jianshu.com/p/17d8266bb265)

**Comment by johngcn** [comment]
@ZhangIvan 感谢建议，后续改进。
