### ISSUE TITLE
frame/g: session cookie setting of generic domain name does not take effect

### ISSUE THREAD

**Issue by bao-io** [gogf/gf#4053]
### Go version

go version go1.23.1 darwin/arm64

### GoFrame version

2.7.4

### Can this bug be reproduced with the latest release?

Option Yes

### What did you do?

```go
s := g.Server()
s.SetCookieDomain(".example.com")
```

### What did you see happen?

session的cookie首次设置，客户端接受到set-cookie头的domain好像不能设置泛域名，只能设置顶级或二三级域。

### What did you expect to see?

我希望session的cookie能够支持泛域名的设置

**Comment by wlynxg** [comment]
please assign it to me

**Comment by wlynxg** [comment]
The current problem has nothing to do with gf, the leading dot is removed by the go net/http library.
Reference code: https://github.com/golang/go/blob/95b433eed428afbb4ab32f0f2541774e939989c7/src/net/http/cookie.go#L251
Reason for removal: https://github.com/golang/go/commit/f1d61b959fc0f759a619025eebd3c76d8a897553

**Comment by bao-io** [comment]
> The current problem has nothing to do with gf, the leading dot is removed by the go net/http library. Reference code: https://github.com/golang/go/blob/95b433eed428afbb4ab32f0f2541774e939989c7/src/net/http/cookie.go#L251 Reason for removal: [golang/go@f1d61b9](https://github.com/golang/go/commit/f1d61b959fc0f759a619025eebd3c76d8a897553)

thank you for you help
