### ISSUE TITLE
golang.org/x/sys v0.0.0-20190924092210-98129a5cf4a0  这个包一直下载不了

### ISSUE THREAD

**Issue by trensy** [gogf/gf#409]
golang.org/x/sys v0.0.0-20190924092210-98129a5cf4a0  这个包一直下载不了

**Comment by trensy** [comment]
GOPROXY https_proxy http_proxy 都试过

**Comment by johngcn** [comment]
@trensy 报什么错？我刚试了可以，`proxy`是使用的`https://goproxy.io`

**Comment by trensy** [comment]
现在可以了
