### ISSUE TITLE
官网用户体验改进功能

### ISSUE THREAD

**Issue by gqcn** [gogf/gf#410]
## 菜单联动滚动功能

当用户点击页面的链接到官网内部的其他文档时，目前采用的是`AJAX`加载方式，并且左边的菜单会自动高亮，但是滚动条并不会自动联动到对应的菜单位置。

![image](https://user-images.githubusercontent.com/26347176/69900831-48392600-13b3-11ea-836c-f08ed5871230.png)

## `Markdown`顶部导航栏菜单浮动到右上角

目前菜单栏是置于最顶部，当用户往下进一步查看手册后，菜单栏即消失，希望能够浮动到右上角，或者做`fiexed`处理，目前没想到这两种方式哪种用户体验更好。

![image](https://user-images.githubusercontent.com/26347176/69900836-5be48c80-13b3-11ea-895d-554fcb2dcd7b.png)

**Comment by zhaopengme** [comment]
需要什么样的支持呢

**Comment by gqcn** [comment]
@zhaopengme 海亮已经做好了，只是没发布上线，所以这个issue一直挂着。

**Comment by gqcn** [comment]
@vance-liu 官网页面需要改进下支持移动端，能够支持一下吗？

**Comment by vance-liu** [comment]
ok，这几天我会抽时间搞

**Comment by vance-liu** [comment]
提了pr简单支持了移动端，[fit mobile](https://github.com/gogf/gf-home/pull/12)
