### ISSUE TITLE
给增加ghttp.Request.GetPostInt8方法

### ISSUE THREAD

**Issue by ccpwcn** [gogf/gf#411]
虽然现在已经有GetPostInt  GetPostInt32 GetPost64等方法了，但是如果能够再有GetPostInt8的话，对于节省CPU计算资源和内存空间资源还是很有用的，比如有些字段在数据库中是tinyint，那么在代码中使用太大的数据类型是一种浪费。

**Comment by johngcn** [comment]
@ccpwcn `Request`对象仅提供了常见了一些数据类型直接获取的方法，其他数据类型你可以使用`GetPostVar/GetVar`获取后转换，例如：`GetVar("id").Int8()`。

**Comment by ccpwcn** [comment]
666，这个好。
