### ISSUE TITLE
redis  DoVar 存进去int类型 

### ISSUE THREAD

**Issue by xiaomingping** [gogf/gf#415]
redis  DoVar 存进去int类型 取出来转换成int结果转换成51 
![image](https://user-images.githubusercontent.com/45221361/70120111-b711ca00-16a6-11ea-96ba-ef59b435bd51.png)
![image](https://user-images.githubusercontent.com/45221361/70120124-bed16e80-16a6-11ea-9552-bcdf903282a9.png)

**Comment by johngcn** [comment]
@xiaomingping 请更新到最新的`v1.10.0`试试。
