### ISSUE TITLE
数据库配置加表前缀选项

### ISSUE THREAD

**Issue by mushu1990** [gogf/gf#420]
1. What version of `GoFrame` are you using?

gf1.10.0

数据库配置可以加上表前缀选项吗？

当前没有表前缀的gdb使用方法：
`g.DB().Table("ca_user").All()`

加上表前缀配置后 prefix='ca_',   gdb使用方法：
`g.DB().Table("user").All()`

这样可以共享表前缀，以后更改表前缀后也不需要再改代码了，灵活性更高。

**Comment by johngcn** [comment]
@mushu1990 好的，我改进一下。

**Comment by johngcn** [comment]
@mushu1990 请更新到最新的版本再试试。
