### ISSUE TITLE
更新到v1.10.0后，version依然显示v1.9.10

### ISSUE THREAD

**Issue by zhangsure** [gogf/gf#423]
release2.md的内容，已经更新到v1.10.0
![image](https://user-images.githubusercontent.com/5119021/70400282-1d129e80-1a65-11ea-9f40-dc1b53f694f9.png)

但version.go的内容，仍然是v1.9.10
![image](https://user-images.githubusercontent.com/5119021/70400286-2b60ba80-1a65-11ea-92b6-8bfb0d7106a0.png)

```
package main

import (
    "github.com/gogf/gf"
    "github.com/gogf/gf/os/glog"
)

func main() {
    glog.Debug(gf.VERSION)
}
```
```
2019-12-09 09:18:18.481 [DEBU] v1.9.10
```

重新下载gf包也是同样结果。。。

**Comment by johngcn** [comment]
@zhangsure 请更新到最新的版本再试试。
