### ISSUE TITLE
关于通过 SessionID  获取session的问题

### ISSUE THREAD

**Issue by zwh123214** [gogf/gf#425]
看了文档，说是可以通过cookie或者Header传递SessionID 来获取 session，那么如果session不是从这里两个方法来，而是通过post/get参数来，那么如何通过这个 SessionID 去获取对应的  session？看了文档好像没有这个方法介绍

**Comment by johngcn** [comment]
@zwh123214 我完善一下。

**Comment by johngcn** [comment]
@zwh123214 我希望将这个功能改进一下使得更优雅，这个可能需要花一点时间。
