### ISSUE TITLE
热重启页面是否需要加个密码判断

### ISSUE THREAD

**Issue by lnz0212** [gogf/gf#430]
![image](https://user-images.githubusercontent.com/3981218/70767730-5d438b00-1d9d-11ea-8df4-10341d1930e6.png)

是否在配置文件加个密码设置，跟Get["password"]进行判断，如果一致显示热重启页面
否则，别人知道了可以随时Shutdown

**Comment by alpiny** [comment]
我是停用默认自带的热重启，然后自己从自己的逻辑去触发热重启命令。
`ghttp.RestartAllServer()`
你可以试一下

**Comment by johngcn** [comment]
@lnz0212 你可以使用全局中间件或者`HOOK`来处理一下。

**Comment by gqcn** [comment]
@lnz0212 其实实际项目中这个接口也很少用。
