### ISSUE TITLE
cron job 加入后 数据库default 信息读取不到~~

### ISSUE THREAD

**Issue by leopardxu** [gogf/gf#431]
### 1. What version of `Go` and system type/arch are you using?
go 1.12.7 windows

### 2. What version of `GoFrame` are you using?

1.10.0

**Comment by johngcn** [comment]
@leopardxu 请提供可复现问题的最小代码。

**Comment by leopardxu** [comment]
```
   cron, _ := gcron.Add("@weekly", func() {
        model.XXX()
    }, "XXX")
    cron.Start()
```
我就把如上代码放到了main函数里。
corn job 是不是要单独生成一个二进制调用？

**Comment by johngcn** [comment]
@leopardxu 你好，看你的代码没有问题，因为配置管理是独立的模块。能否提供可完整运行的代码示例，我本来可以复现试试。

**Comment by leopardxu** [comment]
cron, _ := gcron.Add("@weekly", func() {
		model.XXXX()
	}, "XXXX")
	cron.Start()
	g.Server().Run()

[database]
     [[database.default]]
        link="mysql:root:.....@tcp(XXXXXXXX:3306)/goadmin"

**Comment by leopardxu** [comment]
2019-12-30 10:21:26.921 [ERRO] empty database configuration for item name 'default'

**Comment by leopardxu** [comment]
XXXXXXX = g.DB("default").Table   这个方式应该是gf cli 上一个版本生成的

**Comment by gqcn** [comment]
@leopardxu 你在出错的地方添加试试这两个调用的结果是怎么样的：
```go
fmt.Println(g.Cfg().FilePath())
g.Cfg().Dump()
```
