### ISSUE TITLE
ORM操作建议

### ISSUE THREAD

**Issue by 0ytian** [gogf/gf#433]
现在我有个需求是，只获取数据库表里面某一列的数据，返回一个切片或者一个数组，我在ORM操作方法里面没找到这个方法，只看到获取单条记录的单个字段数据的方法Value()，后期会考虑加一下这个功能吗？比如方法名就叫做Column()

**Comment by johngcn** [comment]
@0ytian `g.DB().Table("xxx").Fields(column).All()`

**Comment by 0ytian** [comment]
@johngcn 我是想只把里面的值查出来，不带字段名，比如[]string{"1", "2", "3", "4"}

**Comment by gqcn** [comment]
@0ytian 与另外一个`issue`重复，参考另外一个`issue`的处理跟进：https://github.com/gogf/gf/issues/470
