### ISSUE TITLE
关于增加url反向生成的建议

### ISSUE THREAD

**Issue by deep-project** [gogf/gf#434]
希望可以增加通过路由别名，反向查找并生成url的功能。
设想示例：

s.Name("article").BindHandler("/article/:id", func(r *ghttp.Request) {
		........
	})

模板中：

{{makeUrl "article" 5}} -> /article/5

{{makeFullUrl "article" 5}} -> http://localhost/article/5

大概就是这个意思。

**Comment by alpiny** [comment]
刚才看了mux中的设计，也挺不错的，作者也可以参考一下
https://github.com/gorilla/mux

**Comment by dijing1987** [comment]
现在这个特性实现了吗？我翻阅文档未找到相关功能
