### ISSUE TITLE
模板加载异常

### ISSUE THREAD

**Issue by Tk4s** [gogf/gf#437]
我的环境为 go version go1.13.4 darwin/amd64
gf 1.10.0 为最终版本.
```
        s := g.Server()
	s.BindHandler("/", func(r *ghttp.Request) {
		r.Response.WriteTpl("client/a.html")
	})

	s.SetPort(6666)
	s.Run()
```
path/debug 为项目根目录

请求http://127.0.0.1:6666 报错为
```
19-12-18 10:15:21.404 [ERRO] [gview] cannot find template file "client/a.html" in following paths:
1. path/debug_code
2. path/debug_code/template
3. /var/folders/j1/3g27m2195dl6rx_5_lllsv8c0000gn/T/go-build280889112/b001/exe
4. /var/folders/j1/3g27m2195dl6rx_5_lllsv8c0000gn/T/go-build280889112/b001/exe/template 
```

添加html 文件template/client/a.html,  正常响应页面信息.

是时候展现真正的bug了..   go build -o client 生成执行文件.   
**!!!   执行文件的名字与WriteTpl 的首层目录名一致**

启动client 或者继续go run main.go.
再请求http://127.0.0.1:6666时报错
```
☁  ~  curl http://127.0.0.1:6666
runtime error: invalid memory address or nil pointer dereference%
```

最终问题在于gspath/gspath.go 的 Search 方法的 !os.IsNotExist(err), 因为读取到的是根目录的执行文件
path/debug_code/client/a.html,
这里虽然会报错, 但不是不存在, 而是报错不是一个文件夹
path/debug_code/client/a.html: not a directory

所以stat.IsDir() 是空指针,然后就报错啦.
那么不仅判断是否存在, 还要判断是否为nil 才对.

```
func Search()

if stat, err := os.Stat(path); !os.IsNotExist(err) {
    path = gfile.Abs(path)
    // Security check: the result file path must be under the searching directory.
    if len(path) >= len(v) && path[:len(v)] == v {
        filePath = path
        isDir = stat.IsDir()
        break
     }
 }
```

而导致问题的原因是gview_doparse.go 的254-259行, 会从根目录获取拼接文件名导致

**Comment by johngcn** [comment]
@Tk4s 感谢反馈，已修复，将会在下一个小版本发布。感觉这是标准库`os.IsNotExist`方法的一个坑。

**Comment by gqcn** [comment]
@Tk4s 请更新到最新代码再试试。
