### ISSUE TITLE
这个例子写了跟没写一样，glist 如何遍历有人会吗

### ISSUE THREAD

**Issue by welldonexing** [gogf/gf#439]

**Comment by johngcn** [comment]
@welldonexing 学习Go要懂得多看`godoc`，我把传送门发你吧：https://godoc.org/github.com/gogf/gf/container/glist

**Comment by welldonexing** [comment]
> @welldonexing 学习Go要懂得多看`godoc`，我把传送门发你吧：https://godoc.org/github.com/gogf/gf/container/glist

请问不pop 的情况下 如何按顺序遍历。 例子没有啊

**Comment by fxk2006** [comment]
> > @welldonexing 学习Go要懂得多看`godoc`，我把传送门发你吧：https://godoc.org/github.com/gogf/gf/container/glist
> 
> 请问不pop 的情况下 如何按顺序遍历。 例子没有啊

有问题你好好问，别总”拿来主义“

**Comment by welldonexing** [comment]
> > > @welldonexing 学习Go要懂得多看`godoc`，我把传送门发你吧：https://godoc.org/github.com/gogf/gf/container/glist
> > 
> > 
> > 请问不pop 的情况下 如何按顺序遍历。 例子没有啊
> 
> 有问题你好好问，别总”拿来主义“

你知道吗？

**Comment by fxk2006** [comment]
> > > > @welldonexing 学习Go要懂得多看`godoc`，我把传送门发你吧：https://godoc.org/github.com/gogf/gf/container/glist
> > > 
> > > 
> > > 请问不pop 的情况下 如何按顺序遍历。 例子没有啊
> > 
> > 
> > 有问题你好好问，别总”拿来主义“
> 
> 你知道吗？

人家给你传送门了啊，说了glist是一个链表，链表？复习一下数据结构啊

**Comment by welldonexing** [comment]
> > > > > @welldonexing 学习Go要懂得多看`godoc`，我把传送门发你吧：https://godoc.org/github.com/gogf/gf/container/glist
> > > > 
> > > > 
> > > > 请问不pop 的情况下 如何按顺序遍历。 例子没有啊
> > > 
> > > 
> > > 有问题你好好问，别总”拿来主义“
> > 
> > 
> > 你知道吗？
> 
> 人家给你传送门了啊，说了glist是一个链表，链表？复习一下数据结构啊
我都说了传送没没有啊，你没看吗

**Comment by welldonexing** [comment]
如果glist 真的有遍历例子 我还跑上来问什么

**Comment by fxk2006** [comment]
> 没

我擦，go doc不会看，学毛的go啊，为啥一个简单的都得给你搞一个例子？

**Comment by welldonexing** [comment]
> > 没
> 
> 我擦，go doc不会看，学毛的go啊，为啥一个简单的都得给你搞一个例子？

你能写不？  我就问你

**Comment by fxk2006** [comment]
> > > 没
> > 
> > 
> > 我擦，go doc不会看，学毛的go啊，为啥一个简单的都得给你搞一个例子？
> 
> 你能写不？ 我就问你

我写出来了怎么办？

**Comment by welldonexing** [comment]
> > > > 没
> > > 
> > > 
> > > 我擦，go doc不会看，学毛的go啊，为啥一个简单的都得给你搞一个例子？
> > 
> > 
> > 你能写不？ 我就问你
> 
> 我写出来了怎么办？

你不写你说几把啊，我本来就是问问题的，什么怎么办  我不能上来问？

**Comment by welldonexing** [comment]
国内项目就这素质吗？  哎算了  去官方库吧

**Comment by fxk2006** [comment]
> > > > > 没
> > > > 
> > > > 
> > > > 我擦，go doc不会看，学毛的go啊，为啥一个简单的都得给你搞一个例子？
> > > 
> > > 
> > > 你能写不？ 我就问你
> > 
> > 
> > 我写出来了怎么办？
> 
> 你不写你说几把啊，我本来就是问问题的，什么怎么办 我不能上来问？
```
package main

import (
	"container/list"
	"fmt"

	"github.com/gogf/gf/container/glist"
)

func main() {
	l := glist.New()
	l.PushBack(8)
	l.PushBack(2)
	l.PushBack(4)
	l.Iterator(func(e *list.Element) bool {
		fmt.Println(e.Value)
		return true
	})
}
```

**Comment by fxk2006** [comment]
> 国内项目就这素质吗？ 哎算了 去官方库吧

那你造一个轮子给我玩玩啊，好像你素质很高一样

**Comment by fxk2006** [comment]
> 国内项目就这素质吗？ 哎算了 去官方库吧

go的doc文件这么牛逼，自己不看，到处说别人不是，怪谁，我真服了

**Comment by welldonexing** [comment]
结贴

**Comment by tangzhenquan** [comment]
能不能对新人友好一点啊，会遍历就了不了吗？

**Comment by fxk2006** [comment]
> 能不能对新人友好一点啊，会遍历就了不起吗？

你学习态度不行，说真的，我没说了不起，了不起是你封给我的，我谢谢你！

**Comment by johngcn** [comment]
@welldonexing @fxk2006 不就一个小事儿么，不要浮躁，好好聊技术相互学习不挺好。我白天比较忙没办法详细回复，看到你们在这聊，我的邮件老是弹，可以看下`glist`里面的源码，有带删除和不带删除的遍历，不带删除的遍历参考方法`glist.FrontAll`和`glist.BackAll`，遍历效率是最高的，仅做参考：
```go
length := l.list.Len()
if length > 0 {
	values = make([]interface{}, length)
	for i, e := 0, l.list.Back(); i < length; i, e = i+1, e.Prev() {
		values[i] = e.Value
	}
}
```

**Comment by tangzhenquan** [comment]
> > 能不能对新人友好一点啊，会遍历就了不起吗？
> 
> 你学习态度不行，说真的，我没说了不起，了不起是你封给我的，我谢谢你！

我只看到你说别人拿来主义，激起了战火

**Comment by johngcn** [comment]
@welldonexing 仅作抛砖引玉，如果还有问题可继续回复，我晚点空了可以详细解答。

**Comment by welldonexing** [comment]
> @welldonexing @fxk2006 不就一个小事儿么，不要浮躁，好好聊技术相互学习不挺好。我白天比较忙没办法详细回复，看到你们在这聊，我的邮件老是弹，可以看下`glist`里面的源码，有带删除和不带删除的遍历，不带删除的遍历参考方法`glist.FrontAll`和`glist.BackAll`，遍历效率是最高的，仅做参考：
> 
> ```go
> length := l.list.Len()
> if length > 0 {
> 	values = make([]interface{}, length)
> 	for i, e := 0, l.list.Back(); i < length; i, e = i+1, e.Prev() {
> 		values[i] = e.Value
> 	}
> }
> ```

看来锁已经是拆开了的，就是说线程不安全了

**Comment by johngcn** [comment]
@welldonexing @fxk2006 @tangzhenquan 鉴于大家对这个话题比较感兴趣，因此我特意更新了一下官方的说明文档：https://goframe.org/container/glist/index 此外，`godoc`上也增加了该示例：https://godoc.org/github.com/gogf/gf/container/glist

![image](https://user-images.githubusercontent.com/26347176/71083577-54541e80-21ce-11ea-8f66-d8708201a7cd.png)

**Comment by Tk4s** [comment]
> > > 能不能对新人友好一点啊，会遍历就了不起吗？
> > 
> > 
> > 你学习态度不行，说真的，我没说了不起，了不起是你封给我的，我谢谢你！
> 
> 我只看到你说别人拿来主义，激起了战火

这人本来就是拿来主义, 学什么开发. doc里面函数写的清清楚楚, 刚毕业的学生吗, 等着老师嚼碎吃哦
