### ISSUE TITLE
静态html文件不是utf8格式情况下，乱码问题

### ISSUE THREAD

**Issue by bjq** [gogf/gf#44]
静态文件服务器，打开的文件是utf-8能正常显示，若文件编码是ANSI格式，打开后就是乱码。
如静态html文件，ansi格式保存：
  meta http-equiv="Content-Type" content="text/html; charset=gb2312"
  <title>金蝶EAS用户手册丛书---参考指南</title>

package main
import (
	"github.com/gogf/gf/g"
)
func main(){
	s := g.Server()
	s.SetIndexFolder(true)
	s.SetServerRoot("C:\\ HTML版")
	s.Run()
	}

注：另外go内置的静态文件服务器也是上述情况（乱码）。

**Comment by johngcn** [comment]
@bjq 应该不会，我不知道标准库是什么样，但是gf的web server不会对文件内容做编码转换，而是直接读取出来丢到返回的缓冲区中。因此你确定一下你的文件编码和你HTML的编码时一致的？我接下来也会测试一下。
