### ISSUE TITLE
模板引擎渲染无转义, 默认会造成xss 攻击

### ISSUE THREAD

**Issue by MarsKucoin** [gogf/gf#441]
gf 1.10.0
OSX  go 1.13

模板渲染应该默认为html 转义, 确认安全的数据才由用户进行回转, 但当前渲染并未进行数据转义,  导致可以执行进行xss 攻击. 
数据应该控制在输入与输出层

**Comment by gqcn** [comment]
@MarsKucoin 请更新到最新`gf`框架版本再试试，相关文档已更新：https://goframe.org/os/gview/xss
