### ISSUE TITLE
gstr.TrimLeftStr报错

### ISSUE THREAD

**Issue by arieslee** [gogf/gf#442]
### 1. What version of `Go` and system type/arch are you using?

MacOS mojava 10.14.4

### 2. What version of `GoFrame` are you using?

gf v1.10.0

go version go1.13 darwin/amd64

### 4. What did you do?

```
package main

import (
	"fmt"
	"github.com/gogf/gf/text/gstr"
)

func main() {
	a := "aaaaa_post"
	b := "aaaaa_"
	c := gstr.TrimLeftStr(a, b)
	fmt.Println(c)
}

```
Error info
```
panic: runtime error: slice bounds out of range [:6] with length 4

goroutine 1 [running]:
github.com/gogf/gf/text/gstr.TrimLeftStr(0x1118421, 0xa, 0x1117aae, 0x6, 0xc000072058, 0x0)
        /Users/sunmoon/go/pkg/mod/github.com/gogf/gf@v1.10.0/text/gstr/gstr_trim.go:56 +0xb1


```
这个问题很诡异呀~
```
package main

import (
	"fmt"
	"github.com/gogf/gf/text/gstr"
)


func main() {
	a := "aaa_post"
	b := "aaa_"
	c := gstr.TrimLeftStr(a, b)
	fmt.Println(c)
}


```
这样就不会报错，我只修改了a和b的值

**Comment by hailaz** [comment]
https://github.com/gogf/gf/blob/50018773b74a3ca17c1e3a7005ec02b6ccedeb19/text/gstr/gstr_trim.go#L55

当cut为str的开头且len(cut)>len(str)/2时，就报错。

**Comment by johngcn** [comment]
@arieslee 感谢反馈，已修复，将会在下一个小版本发布。

**Comment by johngcn** [comment]
@arieslee 请更新到最新的版本再试试。
