### ISSUE TITLE
debug 日志关不掉

### ISSUE THREAD

**Issue by jetlwx** [gogf/gf#446]
### 1. What version of `Go` and system type/arch are you using?

root@jet:tmp# /data/go/goroot/go/bin/go version
go version go1.12.7 linux/amd64

### 2. What version of `GoFrame` are you using?

root@jet:k8s# cat /data/go/gopath/src/github.com/gogf/gf/version.go 
package gf

const VERSION = "v1.10.1"
const AUTHORS = "john<john@goframe.org>"

### 4. What did you do?

问题：关不掉项目DEBUG日志，	g.DB().SetDebug(false)也是一样，关不掉

**Comment by johngcn** [comment]
@jetlwx 你好，我没有复现你所说的问题，请查看配置文件中是否有`debug`参数的配置。

**Comment by gqcn** [comment]
@jetlwx 长时间未活跃关闭，若有疑问可重新提issue。
