### ISSUE TITLE
表前缀功能bug

### ISSUE THREAD

**Issue by mushu1990** [gogf/gf#447]
1. What version of `GoFrame` are you using?

1.10.1

以下方法使用表前缀功能报错，表前缀未加上
![QQ图片20191223135403](https://user-images.githubusercontent.com/5515926/71338687-cee4bb80-258b-11ea-815f-fb81410398de.png)

**Comment by johngcn** [comment]
@mushu1990 你好，中文文档暂时还没有更新，你可以通过配置文件配置`prefix`配置即可。

**Comment by johngcn** [comment]
@mushu1990 感谢反馈，方法操作漏掉了前缀的添加，下一个小版本发布。

**Comment by johngcn** [comment]
@mushu1990 请更新到`gf`最新版本再试试。
