### ISSUE TITLE
建议向下兼容保留sql.ErrNoRows错误返回

### ISSUE THREAD

**Issue by joyoes** [gogf/gf#449]
在最新版中的改变：去掉查询数据为空时的sql.ErrNoRows错误返回，保留Struct/Structs/Scan方法在操作数据为空的该错误返回；
我们在测试中很多地方都是用sql.ErrNoRows错误返回的，如果要更新到最新版来测试又出现问题了，所以建议是保留sql.ErrNoRows错误返回，然后在文档中说明推荐用什么方法来错误返回，这样比较人性化点哈！

**Comment by johngcn** [comment]
@joyoes 我们项目中也是这样的，关于这个`sql.ErrNoRows`的问题在issue中有个讨论：https://github.com/gogf/gf/issues/349 ，另外针对于开发体验确实也不太好，需要太多的`sql.ErrNoRows``书写判断，因此在新版本中去掉了该错误返回，转而直接使用`len`方法或者新增的`r.IsEmpty`判断返回结果。你可以采用批量替换的方式来修改。
