### ISSUE TITLE
32位服务器下，gconv.String()方法在转换int类型大值时，会溢出

### ISSUE THREAD

**Issue by jroam** [gogf/gf#45]
问题:
32位服务器下，gconv.String()方法在转换int类型大值时，会溢出
64位服务器下，正常.

示例代码如下：
`
n1:=  gconv.String(gtime.Now().Millisecond())

fmt.Println(n1)
`

**Comment by johngcn** [comment]
@jroam 感谢反馈，已修复，请更新最新框架代码重试。
