### ISSUE TITLE
Bug: nl2br

### ISSUE THREAD

**Issue by CrazyRocks** [gogf/gf#450]
<nl2br>: error calling nl2br: runtime error: index out of range [3384] with length 3384

建议这个方式使用 for i:=0;i<len(str);i++ 方式
增加nl2p方式 

我现在我使用replace方式效率还行

**Comment by johngcn** [comment]
@CrazyRocks 能否给定可复现问题的代码？

**Comment by CrazyRocks** [comment]
${content|nl2br}
content 汉子超过3000

**Comment by johngcn** [comment]
@CrazyRocks 我试了没有复现，能否将`content`给我试试，或者给定可稳定复现问题的代码。
