### ISSUE TITLE
文档中有一处描述和实际运行对不上

### ISSUE THREAD

**Issue by chenyuwulu** [gogf/gf#452]
WEB服务开发->路由注册->注册方式->函数注册:
示例3中，在定义struct的时候使用params的标签来指定匹配绑定的参数名称，并且支持多个参数名称的绑定

直接传password3这种是无法获取到值的，传“password3,userpass2”的值才能获取到值，根据逗号分隔的描述并没实现

**Comment by johngcn** [comment]
@chenyuwulu 感谢反馈，文档正在更新中，文档会有一个大的改进。

**Comment by gqcn** [comment]
@chenyuwulu 你好，官网文档已大量更新，请查看最新文档试试。
