### ISSUE TITLE
sever静态文件能否自动开启 gzip 压缩

### ISSUE THREAD

**Issue by welldonexing** [gogf/gf#453]
比如设置一个开关，打开的时候，静态目录底下的.js 全部gzip

**Comment by johngcn** [comment]
@welldonexing 你好，目前`gf`还不支持针对于静态文件的`gzip`功能，欢迎提供PR或者实现建议。如果是动态请求的话，可以通过中间件实现`gzip`压缩。

**Comment by welldonexing** [comment]
哦哦 好吧 ，我以为在serachpath 那里加几句就行了
