### ISSUE TITLE
gf run 无法热编译项目

### ISSUE THREAD

**Issue by gxdvip** [gogf/gf#459]
gf run main.go 只能热编译 main.go 文件的修改，修改main.go 导入的包文件 如何才能热编译呢？

当前环境
系统：macOS  Catalina 10.15.2
GO：go version go1.13.5 darwin/amd64
gf-cli: v0.4.5

**Comment by johngcn** [comment]
@gxdvip 请下载最新的`cli`工具版本再试试。

**Comment by gxdvip** [comment]
完美解决
===== 升级了===== 
GoFrame CLI Tool v0.4.5, https://goframe.org
Built Detail:
  Go Version:  go1.13.5
  GF Version:  v1.10.1
  Git Commit:  1e1ad3c6073325e3f5515b28118113503359b942
  Built Time:  2020-01-05 12:49:09
