### ISSUE TITLE
gdb在MSSQL方言时，取分页记录采用了mysql的sql模式导致错误

### ISSUE THREAD

**Issue by zhang1986** [gogf/gf#462]
在数据库MSSQL时，分页取数sql语句生成错误，SELECT * FROM TableName WHERE 1=1 LIMIT 1
### 1. What version of `Go` and system type/arch are you using?
1.13.5

### 2. What version of `GoFrame` are you using?
1.10.1

### 3. Can this issue be reproduced with the latest release?
yes

### 4. What did you do?
use func All()

**Comment by johngcn** [comment]
@zhang1986 请更新到最新的`gf`版本再试试呢。
