### ISSUE TITLE
关于db初始化的问题

### ISSUE THREAD

**Issue by piaohao** [gogf/gf#47]
### 1. What version of `Go` and system type/arch are you using?
go 1.12 ubuntu18 64位

### 2. What version of `GoFrame` are you using?
1.5.16

### 3. Can this issue be reproduced with the latest release?
yes

### 4. What did you do?
a项目依赖gf，此项目为微服务的公共接口和model定义，只引用gf常见的工具；
b项目依赖gf，同时依赖b项目，但b项目启动的时候，db会初始化两次。

### 5. What did you expect to see?
希望db以及其他类似组件不要强制初始化，因为一个项目可能只想引用gf的工具集

**Comment by johngcn** [comment]
@piaohao 你好，我这没有复现，我用了3个项目，abc，其中ab都有数据库操作，c中仅调用ab，运行没有问题。测试项目：https://github.com/johngcn/testc ，另外两个是 https://github.com/johngcn/testa 和 https://github.com/johngcn/testb 都有数据库操作，你只需要下载运行https://github.com/johngcn/testc 即可，a和b都是被依赖的项目。

**Comment by piaohao** [comment]
此问题系gopath和gomodule冲突导致，不是gf的问题
