### ISSUE TITLE
字符串转time的加强

### ISSUE THREAD

**Issue by 15951836388** [gogf/gf#471]
![image](https://user-images.githubusercontent.com/14047483/72231443-5e631480-35f6-11ea-952c-2e35fdd5b140.png)

**Comment by johngcn** [comment]
@15951836388 你可以使用`gtime.NewFromStrFormat`方法：
```go
t := gtime.NewFromStrFormat("2019/2/1", "Y/n/j")
fmt.Println(t.Format("Y-m-d"), "2019-02-01"))
```
