### ISSUE TITLE
ghttp.Request.Method like post/POST depend on curl -X param send. How to check is POST,  and if supply the native method same like "r.IsAjaxRequest()"?

### ISSUE THREAD

**Issue by conero** [gogf/gf#474]
### 1. What version of `Go` and system type/arch are you using?

> go version go1.13.3 windows/amd64

### 2. What version of `GoFrame` are you using?

> github.com/gogf/gf v1.11.2

### 3. Can this issue be reproduced with the latest release?

> No, yet

### 4. What did you do?

```go
        // ……
	server.BindHandler("/mock/do.anything", func(r *ghttp.Request) {
		fmt.Println(r.Method)    // post/POST, it's possible to find out method
		// TIP: when I use [curl -X post] and  [curl -X POST], 
		//       it print post/POST like what you send.
		//r.IsAjaxRequest()
		//I found the [r.IsAjaxRequest()] method to 
		//      check ajax request, but how POST? Can the framework 
		//      supply the native method like "r.IsAjaxRequest()"
	})
```

### 5. What did you expect to see?

> ghttp.Request.Method like post/POST depend on curl -X param send. How to check is POST,  and if supply the native method same like "r.IsAjaxRequest()"?

**Comment by johngcn** [comment]
@conero 
It is not necessary at all retrieving parameters depending on HTTP Method like GET/POST, which is the same like stdlib `net/http`. There're commonly 3 parameter retrieving types: Query, Form and Body. You can retrieve parameters using `GetQuery*`, `GetForm*`, `GetBody*` methods from `r` object. But most of the time, simply using `Get` methods is enough, like `r.Get("name")`, `r.GetInt("id")`, `r.GetMap()`, etc.

Yep, there's a convenience method `IsAjaxRequest` method for checking whether `r` is a AJAX request. You can simply check whether `r` a certain HTTP Method request by comparing the `r.Method`, like `r.Method=="POST"` or `strings.EqualFold(r.Method, "POST")`, which is not necessary providing additional methods doing this.

GF is a most powerful Go framework project. More detail please refer to: https://godoc.org/github.com/gogf/gf/net/ghttp#Request 

Enjoy!

**Comment by conero** [comment]
@gqcn thanks. I got it. It's kind thought for that.
