### ISSUE TITLE
建议增加一个数据库迁移的功能

### ISSUE THREAD

**Issue by 986244073** [gogf/gf#475]
### 1. What version of `Go` and system type/arch are you using?
go1.13.5 darwin/amd64

### 2. What version of `GoFrame` are you using?
v1.11.2 

### 4. What did you do?
代码操作数据库

**Comment by gqcn** [comment]
类似于`PHP` `Laravel`框架的`migrate`功能。

**Comment by zhwei820** [comment]
个人建议不要开这个坑， 费力不讨好。 可以采用成熟的三方框架来管理数据库模型。 比如python 的django框架的migrations就很完善。
