### ISSUE TITLE
Does any existing application logic test examples?

### ISSUE THREAD

**Issue by ruinshe** [gogf/gf#483]
### 1. What version of `Go` and system type/arch are you using?
`go version go1.13.6 linux/amd64`

### 2. What version of `GoFrame` are you using?
`github.com/gogf/gf v1.11.4`

### 3. Can this issue be reproduced with the latest release?
Actually I just want to ask question, besides do you have issue templates for such as `help wanted` issues?

### 4. What did you do?
I'm figuring out the GF framework as a simple micro service and want to know whether there is an existing way to write / run test cases with `gf-cli`.

### 5. What did you expect to see?
It's better having a `gf test` command to run all test cases, including unit tests and integration tests (if they can be separated).

### 6. What did you see instead?
I have taken a look for the `gf --help` and didn't find test command. Currently I thinking is to write the test files and run all test cases through `go test` directly (actually same as what you mentioned in https://goframe.org/test/gtest/index).

**Comment by gqcn** [comment]
@ruinshe Hi, `gf-cli` does not and is not necessary providing any testing command, as the `go test` is good and surely enough for testing usage. There're lots of unit and benchmark testing cases in `GoFrame` source, and `GoFrame` has pretty good code coverage of the source.

`Go` suggests and manages the sources using package, so you can test a certain package under its source folder using `go test` command, like: `go test *.go`. And also your test all packages using command `go test -v ./...`, more detail please refer to command `go test -h` to see its help.

Yes, you can use package `gtest` writing your own unit testing cases for your package. Package `gtest` is very convenient and powerful. We are also using it in mass usage in our production environment.

**Comment by ruinshe** [comment]
Got it, actually I just use `go test -v ./...` now for running all test cases.

Closing this issue.
