### ISSUE TITLE
控制器基类shut方法定义错误

### ISSUE THREAD

**Issue by snail007** [gogf/gf#49]
控制器基类里面这样定义Shut 
`func (c *Controller) Shut()` ,https://github.com/gogf/gf/blob/master/g/frame/gmvc/controller.go#L35
但是注册方法里面却这样转换,`fshut = v.MethodByName("Shut").Interface().(func(*Request))`
https://github.com/gogf/gf/blob/master/g/net/ghttp/ghttp_server_service_object.go#L40
导致继承基类的控制器都不能注册,会报pnaic错误,类型转换错误,
panic: interface conversion: interface {} is func(), not func(*ghttp.Request)

**Comment by johngcn** [comment]
@snail007 那是因为你定义的是一个控制器，但是却使用了对象注册，建议你都使用对象注册，不使用控制器。具体请查看对象注册章节：https://goframe.org/net/ghttp/router/object

**Comment by snail007** [comment]
换了实现方式,已经解决
