### ISSUE TITLE
查数据库值为负数的时候却返回了正整数

### ISSUE THREAD

**Issue by ren-jimmy** [gogf/gf#491]
gf框架查数据库值为负数的时候却返回了正整数

![image](https://user-images.githubusercontent.com/25098996/73550689-fe86bd80-447f-11ea-91c0-6e88d88f0b5b.png)
![image](https://user-images.githubusercontent.com/25098996/73550771-25dd8a80-4480-11ea-9b18-3e1edefa4eed.png)

**Comment by ren-jimmy** [comment]
这个挺影响计算，麻烦下尽快修复

**Comment by gqcn** [comment]
@ren-jimmy 你好，我无法复现你所说的问题，能否把你打印出正整数的代码贴出来看看。

**Comment by ren-jimmy** [comment]
这个确实是我这边的问题，查出来的是-5，但是我转换为float64就变成了正数
![image](https://user-images.githubusercontent.com/25098996/73592175-6a296300-4532-11ea-8817-38f8651848cf.png)

**Comment by gqcn** [comment]
@ren-jimmy 使用`value["fee"].Float64()`试试。
