### ISSUE TITLE
希望事务改进

### ISSUE THREAD

**Issue by ren-jimmy** [gogf/gf#492]
大佬，感觉现在调用事务必须要传递TX耦合度太高，希望改进为begin之后把sql保存到context或存到其他地方，当执行commit再统一执行，进而不用传递TX。

**Comment by gqcn** [comment]
@ren-jimmy 其实`Begin`之后获得的`TX`对象也有`Table`方法创建基于当前事务的`Model`对象，通过该`Model`对象执行的`sql`其实是在事务上执行的，只有`commit`之后才会生效。此外也可以通过链式操作的`TX`方法切换当前操作的对象为事务对象，但是也是在事务上执行该`sql`，也是只有`commit`之后才生效。

**Comment by ren-jimmy** [comment]
但是这样耦合度太高，毕竟写代码为了解耦，肯定分了很多个方法，每个方法都要传递，这将是一个毁灭性的重复工作
