### ISSUE TITLE
请教一下，更新了gf框架到V1.11.4版本后r.id和r.setPost方法是不是不能用了？

### ISSUE THREAD

**Issue by joyoes** [gogf/gf#493]
请教一下，更新了gf框架到V1.11.4版本后r.id和r.setPost方法是不是不能用了？
是不是要把r.setPost改为r.setParam?
r.id应该改为什么呢？

**Comment by gqcn** [comment]
@joyoes 从`v 1.11`版本开始，明确了参数输入的提交方式为`Query`, `Form`, `Body`三种，不再通过HTTP Method来区分参数输入方式。此外，也有`Router`, `Param`方式，具体可以参考：https://goframe.org/net/ghttp/request/index

因此`SetPost`方式就没有意义了，因为可以通过POST方式提交的参数中既有`Query`，也有`Form`表单，甚至是直接把参数写到请求的`Body`中，你到底设置的是哪里的参数呢？所以你可以通过`SetForm`或者`SetParam`来设置参数，建议通过`SetParam`来设置自定义的参数，因为`Param`本来设计就是为了给开发者提供自定义的参数设置。

获取参数的时候直接`Get(xxx)`即可。

**Comment by joyoes** [comment]
谢谢我已经明白了！

**Comment by gqcn** [comment]
@joyoes 对了，`r.Id`去掉了，那个目前在框架中没有什么作用，并且由于存在并发安全控制，即使是原子操作但多少也会影响效率。

**Comment by joyoes** [comment]
好的，谢谢！我刚刚看到有一个是r.GetSessionId()也许可以代替这个r.id() 吧！
