### ISSUE TITLE
我看了gtoken和gf框架自身的gsession，感觉两个没什么区别呢

### ISSUE THREAD

**Issue by joyoes** [gogf/gf#494]
我看了gtoken和gf框架自身的gsession，感觉两个没什么区别呢，大家如何看啊？
我想可能只有一个区别就是gtoken可以用于app，更加通用吧！而gseesion在app端好像用不起！

**Comment by joyoes** [comment]
因为APP客户端需要携带token才能有权限访问服务器的数据，我是这么认为的，求指导！

**Comment by gqcn** [comment]
@joyoes `gf`的`session`特性是通过`gsession`模块实现的，也就是传统的通过客户端传递`sessionid`的方式来标识当前请求的客户端状态。这种方式大多数用在浏览器客户端，在APP端的话也可以通过`Header`或者`Query`的方式传递该`sessionid`，也有通过`JWT`方式来标识APP用户状态的方式。关于`gtoken`你可以咨询下狐狸大佬。

**Comment by joyoes** [comment]
好的，谢谢！

**Comment by zcool321** [comment]
gsession是浏览器session标准方案，gf也实现了redis集群模式支持；
jwt是分布式无状态解决方案；
gtoken是分布式无状态解决方案 并解决了jwt一些问题，但也带来服务端压力，需要个人权衡；
