### ISSUE TITLE
server配置SessionStorage的两种方式后请求的sessionId不一致

### ISSUE THREAD

**Issue by lucky0137** [gogf/gf#496]
如图，两种方式配置server的session存储方式，SetConfigWithMap没有问题每次sessionId一致，SetSessionStorage的配置方式每次请求的sessionId都不一致了，不知道是不是我哪里写的不对，请各位大佬指导下
![微信图片_20200205141327](https://user-images.githubusercontent.com/13485098/73815800-0482f280-4822-11ea-8e5c-95092a0dfaf1.png)
![微信图片_20200205141335](https://user-images.githubusercontent.com/13485098/73815816-0d73c400-4822-11ea-94aa-70807fa76ff5.png)

**Comment by gqcn** [comment]
@lucky0137 你好，我按照你说的单独使用这两个方法来配置`session`但是没有复现你所说的问题，我的测试代码如下：
```go
package main

import (
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/net/ghttp"
	"github.com/gogf/gf/os/gsession"
	"github.com/gogf/gf/os/gtime"
	"time"
)

func main() {
	s := g.Server()
	s.SetSessionMaxAge(2 * time.Minute)
	s.SetSessionStorage(gsession.NewStorageRedis(g.Redis()))
	s.Group("/", func(group *ghttp.RouterGroup) {
		group.GET("/set", func(r *ghttp.Request) {
			r.Session.Set("time", gtime.Timestamp())
			r.Response.Write("ok")
		})
		group.GET("/get", func(r *ghttp.Request) {
			r.Response.WriteJson(r.Session.Map())
		})
		group.GET("/clear", func(r *ghttp.Request) {
			r.Session.Clear()
		})
	})
	s.SetPort(8199)
	s.Run()
}
```
随后访问：
1. http://127.0.0.1:8199/set
1. http://127.0.0.1:8199/get
