### ISSUE TITLE
请尽量使用英文交流

### ISSUE THREAD

**Issue by gqcn** [gogf/gf#499]
We currently accept English and Chinese language in issue, but we encourage using English as possible as you can when discussing issues, for better globally communication. But more importantly, we expect your expression more clear and detailed as free as you can.

我们目前接受英文/中文提问，为了更好地国际化交流，我们鼓励大家尽可能使用英文进行问题讨论。不过更重要的是，我们期望您能更清晰地表达自己的观点。

**Comment by dongshanlang** [comment]
哈哈哈，why

**Comment by marsberrys** [comment]
中文也是国际语言啊

**Comment by HelloReboot** [comment]
> 

因为英文是强者的语言

**Comment by zhangyufei2008** [comment]
hi ,i have a problem.
![image](https://user-images.githubusercontent.com/38060686/159614075-4d769f0f-fd0e-4e91-a3a3-6d11a46fe790.png)

**Comment by zhangyufei2008** [comment]
who can help me .solving this problem

**Comment by abersheeran** [comment]
![image](https://user-images.githubusercontent.com/25364828/170626741-eccd5a47-d63a-4de3-8a56-7969d01d25ee.png)

官网都是以中文为主的，issue以英文为主的意义在哪儿🤔

**Comment by singi2016cn** [comment]
自信点，看不懂中文，他们可以学！

**Comment by BeYoug** [comment]
> ![image](https://user-images.githubusercontent.com/25364828/170626741-eccd5a47-d63a-4de3-8a56-7969d01d25ee.png)
> 
> 官网都是以中文为主的，issue以英文为主的意义在哪儿🤔

我也想说

**Comment by FireTiger23** [comment]
> 自信点，看不懂中文，他们可以学！

> 中文也是国际语言啊

就是 中文凭什么就不能是国际语言。。

**Comment by mqxqls** [comment]
必须中文

**Comment by rt005744** [comment]
自信点，看不懂中文，老外可以学！

**Comment by jiang834686379** [comment]
老外到我国的空间站也得老老实实用中文

**Comment by jiang834686379** [comment]
我国国际空间站用的都是中文，再说谷歌翻译多方便，为了这个事情还特意提出来说？

**Comment by jiang834686379** [comment]
作者这么说是对GoFrame不自信吗？想想为什么我国国际空间站用的都是汉语，只要你的框架足够优秀，就不用担心其他语系的使用者接受不了。自信点！

**Comment by Tiper-In-Github** [comment]
毕竟项目的开源的，使用英文有利于国际友人参与协作。虽然国际友人不一定看得懂中式英语，但这也是项目国际化的表现，至于楼上提到的自信的问题，我想这应该是以后考虑的事情。
After all, the project is open source, and using English is beneficial for international friends to participate in collaboration. Although international friends may not necessarily understand Chinglish, this is also a manifestation of the internationalization of the project. As for the issue of confidence mentioned upstairs, I think this should be considered in the future.

**Comment by hailaz** [comment]
那么多人都不看重点（表达的语言不是，表达的内容才是），只喜欢挑刺和制造争议，像个小孩。

**Comment by Cassianvale** [comment]
我非常同意这个观点，我认为使用英语作为社区交流的语言有以下好处：
1.能够让项目吸引到全球范围内的开发者和用户，有助于知识的传播和共享，让更多的人从中受益
2.贡献者可能来自世界各地，使用英语的话可以最大限度地减少沟通障碍
3.对于开发者来说，参与英语的技术交流可以提高个人英语水平，对职业发展也很有好处
这种做法主要是出于实用主义，使用英语作为交流语言并不反映缺乏文化自信，相反，它可以被视为在全球背景下维护和促进本地语言和文化的积极努力，是展示文化自信的重要方式！
