### ISSUE TITLE
gconv使用报错

### ISSUE THREAD

**Issue by zhangHongBo21** [gogf/gf#501]
错误代码如下
func main() {
	fmt.Println(gconv.String(1244454444))
}
只要使用gconv都会报错
信息如下
`# github.com/gogf/gf/container/gset
..\..\github.com\gogf\gf\container\gset\gset_any_set.go:18:6: Set redeclared in this block
	previous declaration at ..\..\github.com\gogf\gf\container\gset\gset.go:18:6
..\..\github.com\gogf\gf\container\gset\gset_any_set.go:26:6: New redeclared in this block
	previous declaration at ..\..\github.com\gogf\gf\container\gset\gset.go:26:25
..\..\github.com\gogf\gf\container\gset\gset_any_set.go:31:6: NewSet redeclared in this block
	previous declaration at ..\..\github.com\gogf\gf\container\gset\gset.go:31:28
..\..\github.com\gogf\gf\container\gset\gset_any_set.go:40:6: NewFrom redeclared in this block
	previous declaration at ..\..\github.com\gogf\gf\container\gset\gset.go:40:48
..\..\github.com\gogf\gf\container\gset\gset_any_set.go:53:17: (*Set).Iterator redeclared in this block
	previous declaration at ..\..\github.com\gogf\gf\container\gset\gset.go:53:6
..\..\github.com\gogf\gf\container\gset\gset_any_set.go:65:17: (*Set).Add redeclared in this block
	previous declaration at ..\..\github.com\gogf\gf\container\gset\gset.go:65:6
..\..\github.com\gogf\gf\container\gset\gset_any_set.go:119:17: (*Set).Contains redeclared in this block
	previous declaration at ..\..\github.com\gogf\gf\container\gset\gset.go:75:6
..\..\github.com\gogf\gf\container\gset\gset_any_set.go:127:17: (*Set).Remove redeclared in this block
	previous declaration at ..\..\github.com\gogf\gf\container\gset\gset.go:83:6
..\..\github.com\gogf\gf\container\gset\gset_any_set.go:135:17: (*Set).Size redeclared in this block
	previous declaration at ..\..\github.com\gogf\gf\container\gset\gset.go:91:6
..\..\github.com\gogf\gf\container\gset\gset_any_set.go:143:17: (*Set).Clear redeclared in this block
	previous declaration at ..\..\github.com\gogf\gf\container\gset\gset.go:99:6
..\..\github.com\gogf\gf\container\gset\gset_any_set.go:143:17: too many errors`

**Comment by gqcn** [comment]
@zhangHongBo21 你好，我没有复现你的问题，如果你使用的是`go.mod`，你可以尝试着把本地的缓存清理掉再试试：
```
go clean -modcache
```
也可以直接删 `$GOPATH`，这个操作比较有风险，自行评估下。
