### ISSUE TITLE
在版本为V1.11.4中查询数据库时的bug

### ISSUE THREAD

**Issue by joyoes** [gogf/gf#503]
我基于gmanger学习代码时，发现当输入错误的用户名时，返回服务器为500的错误，然后我通过倒查发现是gf框架的原因，具体如下：
在gdb_model.go文件中的第870-875行代码：
```go
func (m *Model) FindOne(where ...interface{}) (Record,error){
 if len(where)>0{
      return m.WherePri(where[0],where[1:]...).One()
}
return m.One()
}
```
当用户名输入错误时，查询不到数据，err不应该为nil返回，但是以上代码的err是为nil的，所以建议改为：
```go
func (m *Model) FindOne(where ...interface{}) (Record,error){
 if len(where)>0{
    one,err:=m.WherePri(where[0],where[1:]...).One()
   if err!=nil {
       return nil,err 
   }
      return one,nil
}
one,err:=m.One()
if err!=nil {
       return nil,err 
   }
return one,nil
}
```
类似还有其他查询也是一样的错误，建议都改进一下，谢谢！

**Comment by joyoes** [comment]
![微信图片_20200212230920](https://user-images.githubusercontent.com/16605854/74347881-bd31ce80-4dec-11ea-9066-7998d0c75bfd.png)

**Comment by gqcn** [comment]
@joyoes 只要`SQL`执行没问题返回的`error`都是`nil`，查不到数据`error`也是`nil`。

**Comment by joyoes** [comment]
@gqcn 在SQL执行无问题，查无数据的情况下，增加一个返回值为nil是否妥当？不然我们在获取返回值的时候，就必须增加一个判断是否有返回值的代码，会造成代码冗余！

**Comment by gqcn** [comment]
@joyoes 你参考下这个呢 https://github.com/gogf/gf/issues/349

**Comment by zcool321** [comment]
此功能为优化代码兼容问题，master已修复
