### ISSUE TITLE
"SearchPaths" in "config.toml" didn't work

### ISSUE THREAD

**Issue by lujscn** [gogf/gf#504]
### 1. What version of `Go` and system type/arch are you using?

go1.13.7 windows/amd64

### 2. What version of `GoFrame` are you using?

gf v1.11.4

### 3. Can this issue be reproduced with the latest release?
Yes

### config.toml
```
[server]
	Address         = ":8080"
	ServerRoot      = "public"
	SearchPaths     = ["public_default"]
```
OR
```
[server]
	Address         = ":8080"
	ServerRoot      = "public"
	SearchPaths     = "public_default"
```

### 5. What did you expect to see?

> SearchPaths     = ["public_default"]

 in "config.toml" works as 
```
s.AddSearchPath("public_default")"
```
in .go file

### 6. What did you see instead?
"SearchPaths" in "config.toml" didn't work

**Comment by gqcn** [comment]
@lujscn 已改进支持该配置，已经提交到`master`分支，将会在下一个版本发布。
