### ISSUE TITLE
ghttp  能否把静态目录设置到gres 打包资源里 

### ISSUE THREAD

**Issue by welldonexing** [gogf/gf#506]
即 我把我的网页打包到可执行文件里，不写出，即可访问

**Comment by gqcn** [comment]
@welldonexing Of course，当然可以拉！GF非常强大便捷！你可以参考一下`gres`资源管理模块，官方文档：https://goframe.org/os/gres/index 此外，推荐使用工具链通过`gf pack`进行打包。

**Comment by mmdet** [comment]
我也在找该问题的解决方法，但官方文档写的非常不细致。
