### ISSUE TITLE
ghttp bug ?

### ISSUE THREAD

**Issue by welldonexing** [gogf/gf#507]
比如我们  sv.GET("/now", func(c echo.Context)    此时访问 localhost/now  可以到达页面 ，但是如果 
 localhost/now/  则返回notfound   但是主流语言比如php 都会移除后面的/

**Comment by gqcn** [comment]
@welldonexing 我没有复现你所说的问题，你更新到最新的框架代码试试

**Comment by welldonexing** [comment]
echo 的问题 错怪gf了   可以close!
