### ISSUE TITLE
mssql在写入数据时存在调用数据库函数情况，比如date1=getDate()这种赋值，用struct或map更新时无法设置;另数据库字段datetime为null时，生成的JSON时间为0001-01-01 00:00:00，是否可以设置为null;再另struct中如何设置返回的数据格式，比如日期时间类型，字符串类型时null转成空字符串

### ISSUE THREAD

**Issue by zhang1986** [gogf/gf#509]
1.13
### 2. What version of `GoFrame` are you using?
v1.11.5-0.20200208031709-83dcc4a5e05d

### 3. Can this issue be reproduced with the latest release?
yes

**Comment by gqcn** [comment]
@zhang1986 你好，不看懂你的问题，麻烦再详细阐述一下，你这里似乎是多个问题？
