### ISSUE TITLE
建议gdb增加GetLastSql()方法

### ISSUE THREAD

**Issue by jroam** [gogf/gf#51]
### 建议gdb增加GetLastSql()方法

新增加方法希望能实现：获取最近执行的完整的sql语句字符串.

 如下:
`
rs,_:=db.Table("cd_orderform").Where("title like '九寨%'").OrderBy("orderform0 desc").Limit(0,3).Select()

sqls:=db.GetLastSql()

fmt.Println(sqls) // print : select * from cd_orderform where title like '九寨%' order by orderform0 desc limit 0,3
`

这样在开发时，对排查问题，很有帮助。

**Comment by johngcn** [comment]
@jroam 已增加`GetLastSql`方法，返回的是`*Sql`类型
