### ISSUE TITLE
gstr.TrimRight问题

### ISSUE THREAD

**Issue by dangwy** [gogf/gf#510]
```golang
func main() {
	body := "test:test@179.61.12.118:80"

	proxy := gstr.TrimLeft(body, "test:test@")
	proxyIP := gstr.TrimRight(proxy, ":80")
	//proxyIP := proxy2[:len(proxy2)-3]

	fmt.Print(proxyIP)
}
```
是strings.TrimRight()存在的问题。

期望输出应该是：179.61.12.118，但输出的是：179.61.12.11

**Comment by xushenghao** [comment]
TrimRight：TrimRight returns a slice of the string s, with all trailing Unicode code points contained in cutset removed.TrimRight returns a slice of the string s, with all trailing Unicode code points contained in cutset removed.To remove a suffix, use TrimSuffix instead。

propose：
        `body := "test:test@179.61.12.118:80"
	proxy := gstr.TrimLeftStr(body, "test:test@")
	proxyIp := gstr.TrimRightStr(proxy, ":80")
	glog.Info(proxyIp)`

**Comment by gqcn** [comment]
@dangwy Yep, @xushenghao is quite right. I see you actually need `gstr.TrimRightStr` instead of `gstr.TrimRight`, as `gstr.TrimRight` is used for cutting given **characters** from right to left but `gstr.TrimRightStr` cutting **strings.**

Here is the function prototype definitions for `gstr.TrimRight` and `gstr.TrimRightStr`:
```go
// TrimRight strips whitespace (or other characters) from the end of a string.
func TrimRight(str string, characterMask ...string) string {
	if len(characterMask) == 0 {
		return strings.TrimRight(str, defaultTrimChars)
	} else {
		return strings.TrimRight(str, defaultTrimChars+characterMask[0])
	}
}

// TrimRightStr strips all of the given <cut> string from the end of a string.
// Note that it does not strips the whitespaces of its end.
func TrimRightStr(str string, cut string) string {
	var lenStr = len(str)
	var lenCut = len(cut)
	for lenStr >= lenCut && str[lenStr-lenCut:lenStr] == cut {
		lenStr = lenStr - lenCut
		str = str[:lenStr]

	}
	return str
}
```

It is the same to functions `gstr.TrimLeft` and `gstr.TrimLeftStr`.

**Comment by dangwy** [comment]
Got it,tks.
