### ISSUE TITLE
在服务端返回JSON数据格式时，是否可以通过字段配置支持将null类型数据不返回到客户端以节省数据量

### ISSUE THREAD

**Issue by zhang1986** [gogf/gf#511]
### 1. What version of `Go` and system type/arch are you using?
1.13

### 2. What version of `GoFrame` are you using?
v1.11.5-0.20200208031709-83dcc4a5e05d

### 3. Can this issue be reproduced with the latest release?
yes

**Comment by gqcn** [comment]
@zhang1986 你可以了解一下`JSON`的`omitempty`标签，前提是你的属性是指针类型。
