### ISSUE TITLE
Table column name as constant variable when generation

### ISSUE THREAD

**Issue by ruinshe** [gogf/gf#512]
### 1. What version of `Go` and system type/arch are you using?

Latest go binary.
```
go version go1.13.8 linux/amd64
```

### 2. What version of `GoFrame` are you using?

```
github.com/gogf/gf v1.11.4
```

### 3. Can this issue be reproduced with the latest release?

Yes

### 4. What did you do?
I run the GF command line tool to generate the DB model by:

```sh
gf gen model
```

### 5. What did you expect to see?

Actually it's a feature request, not sure whether you will create a issue template for feature requests ;-)

I need a list of table column constants for `Where(where, args...)` function usage, e.g.

```go
var entity *model.Entity
model.Model.Where(models.Columns.Field+" like ?", fieldValue).M.Struct(&entity)
```

### 6. What did you see instead?

Didn't find such kind of constants, and currently I manually add the column constants when I used it into the model folder.

**Comment by gqcn** [comment]
@ruinshe Thanks, it's a good proposal! We mark it in next release.
