### ISSUE TITLE
Benchmark for rwmutex

### ISSUE THREAD

**Issue by kevinlincg** [gogf/gf#516]
why is the benchmark for rwmutex is below,

I though **Benchmark_Safe_RLockRUnlock-20**  should be same as **Benchmark_Safe_LockUnlock-20**.

But it is not.

> 
> Benchmark_Safe_LockUnlock-20        	1000000000	         0.830 ns/op	       0 B/op	       0 allocs/op
> Benchmark_Safe_RLockRUnlock-20      	328433829	         3.86 ns/op	       0 B/op	       0 allocs/op
> Benchmark_UnSafe_LockUnlock-20      	46278084	        21.9 ns/op	       0 B/op	       0 allocs/op
> Benchmark_UnSafe_RLockRUnlock-20    	92551172	        12.6 ns/op	       0 B/op	       0 allocs/op
>

**Comment by gqcn** [comment]
@kevinlincg Which package did you test? Can you provide the benchmark testing codes?

**Comment by kevinlincg** [comment]
I test rwmutex in internel.
and I run rwmutex_z_bench_test.go directly

**Comment by gqcn** [comment]
@kevinlincg Sorry there's parameter issue in the benchmark testing codes and I fixed this, you can pull the latest master branch and try again, here's my benchmark testing result:

The benchmark test is based on intel i5 4-cores CPU.

> I see youre using 20-cores CPU? Nice computer! 

![image](https://user-images.githubusercontent.com/26347176/75006393-8757ae80-54ac-11ea-884a-cec2e23d64f9.png)

**Comment by kevinlincg** [comment]
my question is UnSafe_LockUnlock and UnSafe_RLockRUnlick why not same???

I think it should be all 1000000000

in the code , they are same.

**Comment by gqcn** [comment]
@kevinlincg eh..Interesting..I wonder this too, I doubt if the go compiler does something we do not know, like inserting something else for RWMutex? 😈
