### ISSUE TITLE
建议改进gf上传文件的方式，增加单文件接收方法 , 另外接收方法提供save方法和filename属性

### ISSUE THREAD

**Issue by develop1024** [gogf/gf#518]

**Comment by gqcn** [comment]
@develop1024 已增加该功能特性，文档已更新，目前代码在`master`分支上：https://goframe.org/net/ghttp/client/demo/upload

**Comment by gqcn** [comment]
@develop1024 已增加该功能特性，文档已更新，目前代码在`master`分支上：https://goframe.org/net/ghttp/client/demo/upload

**Comment by xushenghao** [comment]
@gqcn 文档与实际不符合单文档获取函数r.FormFile(key)

**Comment by gqcn** [comment]
@develop1024 你更新到最新的`v1.11.5`再试试文档示例呢，之前在master分支上没打tag。你的代码那个方式稍微繁琐了点，所以新版本增加了封装，直接`Save`方法即可保存文件。
