### ISSUE TITLE
关于接入新的数据库

### ISSUE THREAD

**Issue by chenall** [gogf/gf#520]
背景:  原来用PHP/C 类语言比较多,  初学GO.  喜欢GO的简洁.  使用GF写了几个小程序. 现在需要用到特殊的数据库类型.

看了文档说 接入新的数据库相当方便.

我参考了源码里面的相关数据库实现方法自己添加了一个新的数据库类型,目前使用正常.

现在问题来了.

自己添加的数据库类型放在gogf框架的gdb目录里面,后续框架升级的话就麻烦了.

请问除了上面的方法,还有其它方法可以添加数据库类型吗, 不需要修改框架的.

**Comment by gqcn** [comment]
@chenall 你好，感谢对`GF`的支持，目前`gdb`模块还没有考虑过外部接入的设计，不过应该比较简单，你可以把你增加的数据库提个pr我看看。

**Comment by chenall** [comment]
大概说一下.
在gdb目录产新建一个gdb_xxx.go文件
然后从其它类似数据库的gdb_yyy.go文件中复制内容过来.
并替换里面接口名,
再修改 Open 函数,其它的按实际情况修改.

最后在gdb.go的New函数里面添加调用.

我尝试着把gdb_xxx.go外置到我的项目中,发现里面用到了一些gdb的私有函数和struct.
可以想办法去掉这些调用或访问, 如果只是使用DB接口应该问题不大,就是不知有没有其它影响,有空我再试试看.

当然后续如果能提供外部接口的话使用起来就会更加方便. 类似于 依赖注入 功能.

**Comment by gqcn** [comment]
@chenall 其实我早正有此意，我创建了一个新的issue来跟进这个事情，后期框架会更加通过接口的形式来设计组件，而不是绑定特定的三方数据库驱动来实现组件：https://github.com/gogf/gf/issues/522

**Comment by chenall** [comment]
期待新的版本,这个我就先关了.
