### ISSUE TITLE
remove mysql driver support from gdb, add installation interface for third-party database drivers

### ISSUE THREAD

**Issue by gqcn** [gogf/gf#522]
In order to reduce the dependences for third-party libraries, especially some heavy libraries like mysql driver, we should firstly remove mysql driver from GoFrame libraries.
1. remove mysql driver bound by package gdb
1. add installation interface or method for third-party driver installation.

**Comment by gqcn** [comment]
For simple and convenient usage purpose, I do not remove the build-in support for mysql driver, as the mysql driver is also quite independent. I've now added custom driver feature support for package `gdb`, that makes the developer more convenient registering custom driver into package `gdb`.

**Comment by chenall** [comment]
小试了一下，使用新的方法添加自定义数据库成功。
还有hook的功能，以后使用就比较方便了，感谢！
