### ISSUE TITLE
模板渲染问题

### ISSUE THREAD

**Issue by ztcjn** [gogf/gf#523]
请问下查询数据库返回的struct 这样的数据前端怎么取出其中的某个字段 
![image](https://user-images.githubusercontent.com/32876243/75601296-b1d0e980-5af4-11ea-9fcf-5eed5009ef7b.png)

![image](https://user-images.githubusercontent.com/32876243/75601315-d88f2000-5af4-11ea-97c3-f8ec3aeaba19.png)

**Comment by gqcn** [comment]
@ztcjn 看你这个方法返回的是数组，当赋值给一个模板变量后， 你可以通过`index`模板标签读取对应索引下的内容，也可以使用`range...end...`标签，所有标签都是来自于标准库的`text/template`包。

> 吐槽：Golang标准库的模板引擎不是特别好用。

**Comment by ztcjn** [comment]
能否给个demo， 我尝试很多次，都没办法读出正确的值
