### ISSUE TITLE
[gdb/question] how to get the pagination information when query

### ISSUE THREAD

**Issue by ruinshe** [gogf/gf#524]
### 1. What version of `Go` and system type/arch are you using?

```
go version go1.14 linux/amd64
```

### 2. What version of `GoFrame` are you using?

```
github.com/gogf/gf v1.11.4
```

### 3. Can this issue be reproduced with the latest release?

Just a question issue, and yes.

### 4. What did you do?

I didn't find the pagination related documents in the GoFrame official website, currently my requirement is to figure out how many rows matches the query.

For example, I write a SQL statement for query:

```go
model.Model.M.Page(requestPage.Page, requestPage.Size).Structs(&entities, where)
```

And this statement only returns `error` object and no total rows matched of the query, and I need another `count` action to get the result.

Just be curious that whether it's the expected solution in current stage of the GoFrame library?

### 5. What did you expect to see?

N/A

### 6. What did you see instead?

N/A

**Comment by gqcn** [comment]
@ruinshe Generally you need query twice to retrieve the rows and the matching count. let's sat you have a query condition variable like `where`, you can retrieve the rows by `rows, err := model.FindAll(where)` and then you can retrieve the matching count by ` count, err := model.FindCount(where)`, the result variable `count` can be used for your pagination.

**Comment by ruinshe** [comment]
@gqcn Okay, it's just my expectation before and I used this way to figure out the count, thanks for the confirmation.
