### ISSUE TITLE
options request support

### ISSUE THREAD

**Issue by xushenghao** [gogf/gf#526]
### 1. What version of `Go` and system type/arch are you using?

1.13  windows

### 2. What version of `GoFrame` are you using?

1.11.5

### 3. Can this issue be reproduced with the latest release?
yes

### 4. What did you do?

```
Request URL: http://127.0.0.1:9000/admin/home/login
Request Method: OPTIONS
Status Code: 404 Not Found
Remote Address: 127.0.0.1:9000
Referrer Policy: no-referrer-when-downgrade
```

### 5. What did you expect to see?

```
Request URL: http://127.0.0.1:9000/admin/home/login
Request Method: OPTIONS
Status Code: 200 OK
Remote Address: 127.0.0.1:9000
Referrer Policy: no-referrer-when-downgrade
```

### 6. What did you see instead?
 suggest：ghttp_server_router_serve.go  line 119 need  || method=="OPTIONS"
also need  reply http.StatusOK
```
if strings.EqualFold(item.router.Method, gDEFAULT_METHOD) || strings.EqualFold(item.router.Method, method) || method=="OPTIONS" {}
```

**Comment by gqcn** [comment]
@xushenghao Thanks for your proposal. The documentation is updated for the CORS feature of web server, please refer to: https://goframe.org/net/ghttp/router/middleware
