### ISSUE TITLE
关于gcache增加一个过期回调函数的一个小想法

### ISSUE THREAD

**Issue by XWR940711** [gogf/gf#527]
在cache设置时同时写入一个过期回调方法,当缓存过期执行该方法并把k,v,ex做为params传递.

**Comment by gqcn** [comment]
@XWR940711 感谢建议，我可以加个discuss标签，大家可以聊聊有无类似需求。

**Comment by xushenghao** [comment]
这个可以用作信息过期判断，用在消息超时，感觉有点意思

**Comment by XWR940711** [comment]
@gqcn 想问下框架的上下文参数存储.假设我在token中带有用户id,解密回来需要存储到request中该如何存储.我看了下只有SetParam,SetForm,SetQuery.好像都不太适合.gin是用Keys作上下文存储的,我在gf的Request中并未找到类似的对象.

**Comment by gqcn** [comment]
@XWR940711 参考下以下几个章节：
https://goframe.org/net/ghttp/request/context
https://goframe.org/net/ghttp/request/custom
