### ISSUE TITLE
全局跨域设置

### ISSUE THREAD

**Issue by aikaiqiang** [gogf/gf#53]
目前我知道可以通过Hook回调事件设置跨域
有没有配置参数全局设置呢？或者是针对特定路由设置

**Comment by johngcn** [comment]
@aikaiqiang 原本HOOK在注册的时候就可以指定路由，如果想要全局的，那么绑定`/*`路由即可。

**Comment by aikaiqiang** [comment]
明白了，我以为会有个ServerConfig 全局参数来配置的，没找到这个参数所以来咨询下；
Thinks ！！！
