### ISSUE TITLE
[gdb/mysql] keyword as column name makes query fail

### ISSUE THREAD

**Issue by ruinshe** [gogf/gf#530]
### 1. What version of `Go` and system type/arch are you using?

```
go version go1.14 linux/amd64
```

### 2. What version of `GoFrame` are you using?

```
github.com/gogf/gf v1.11.4
```

### 3. Can this issue be reproduced with the latest release?

Yes

### 4. What did you do?

Creates a simple table in MySQL including keyword as column, for example:

``` mysql
CREATE TABLE IF NOT EXISTS `configurations` (
  `key` varchar(128) PRIMARY KEY,
  `value` varchar(128)
) ENGINE = InnoDB;
```

Then generate the model, run simple query using the generated model:

```
// This function is written in the same package of the generated pacakge, i.e. app/model/configurations/

const keyCurrentSeasonID = "current_season_id"

// GetCurrentSeasonID - get currrent season id for other services.
func GetCurrentSeasonID() int {
	var row *Entity
	if err := Model.M.Scan(&row, "key like ?", keyCurrentSeasonID); err != nil {
		logger.Fatalf("error occurs when finding current season id: %v", err.Error())
		return -1
	}
	id, err := strconv.Atoi(row.Value)
	if err != nil {
		logger.Fatalf("error occurs when parsing current season id: %v", err.Error())
		return -1
	}
	return id
}
```

### 5. What did you expect to see?

The SQL should be executed normally without error, and returns the expected configuration item or `sql.ErrNoRows` if the configuration item is not filled in the DB.

### 6. What did you see instead?

When running the query, console shows:

```log
2020-03-03 21:30:53.913 [FATA] error occurs when finding current season id: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'key like ? LIMIT 1' at line 1, SELECT * FROM `configurations` WHERE key like 'current_season_id' LIMIT 1
```

**Comment by xushenghao** [comment]
The key field is the keyword of mysql,add ``(反引号)

**Comment by ruinshe** [comment]
Currently all the columns is not wrapped by `` although this is not the normal case for table design.

I choose a workaround: using another column name ;-)

**Comment by gqcn** [comment]
@ruinshe It does not support automatically adding char ` around the key words if given condition parameter is type of string but map/struct. Besides, it's not really good using key words as your field name.
