### ISSUE TITLE
请问有没有推荐的goframe中使用ES的方案

### ISSUE THREAD

**Issue by linhongzhao321** [gogf/gf#531]
RT，请问有没有推荐的goframe中使用ES的方案。我目前使用es官方的go客户端，但是很多东西要单独配置，又或者如日志模块，无法直接兼容。希望能获得一个推荐的实践方案
 #![image](https://user-images.githubusercontent.com/33045301/75871362-677aa000-5e47-11ea-9d70-6b05dd0919ab.png)

**Comment by gqcn** [comment]
@linhongzhao321 你好，`GoFrame`定位为通用的基础开发框架，提供比较通用的基础组件、工具链、开发模板和规范，像ES这种封装模块是不会有的。不过ES的接口都是基于Restful风格设计的，直接通过HTTP客户端请求即可，你可以参考下`GoFrame`框架里的HTTP客户端：https://goframe.org/net/ghttp/client/index

**Comment by linhongzhao321** [comment]
> @linhongzhao321 你好，`GoFrame`定位为通用的基础开发框架，提供比较通用的基础组件、工具链、开发模板和规范，像ES这种封装模块是不会有的。不过ES的接口都是基于Restful风格设计的，直接通过HTTP客户端请求即可，你可以参考下`GoFrame`框架里的HTTP客户端：https://goframe.org/net/ghttp/client/index

好的，感谢
