### ISSUE TITLE
关于在路由中使用gvalid

### ISSUE THREAD

**Issue by XWR940711** [gogf/gf#535]
在ghttp_server_router_group.go中新增一个Validate方法传入参数为[变量名:规则].这个方法里用(GetMap())取到所有的求参,然后进行验证.
在api接口的开发中,我是偏向验证前置.给人第一感觉就是清晰透明.
看一个接口流程,我想应该都是先找路由,再找控制器,然后找到服务层.我看官方的gf-demos跟gf-home里都是在控制器或者服务层进行检验并返回检验结果(err!=nil写哭),如果想知道这个接口全部参数需要找结构体或者map规则(有些无需验证的字段可能会被忽略).
优势:N个控制器(服务层)就要写N次验证,前置到路由上验规则只需要关注规则.在后续控制器(服务层)中就不需要关注传入数据是否合法(大胆写逻辑).关于验证失败后用户可以接管或者框架默认.(required-with的实现已经很好的解决的入参之间的关系,所以不会存在参数不可控)
劣势:emm..辛苦开发小组.做上去大家可用可不用.
Tip:在php的国产框架tp里是可以路由直接验证参数的(直接验证,场景验证,验证失败接管).以上只是我个人的想法.

**Comment by gqcn** [comment]
@XWR940711 能否描述得各个具体一点？如果能有参考的示例或者代码更佳。

**Comment by XWR940711** [comment]
假设当前router.go
当前:group.GET("/", ctlUser.Info).Middleware(middleware.Auth)//路由规则,中间件
期望group.GET("/login", ctlUser.Info).Middleware(middleware.CORS).Validate(map[string]string{
"passport":"required#账号不能为空",
"password":"required#密码不能为空",
})//规则,中间件,验证
在group下基础验证规则(跟Middleware(middleware.CORS)一样会被合并)
group.Validate(map[string]string{
"csrf":"required#csrf令牌不能为空",
}).
另外非常必要在ghttp.Request struct中增加一个上下文关键字.理由就是当前Request下只有params,form,query,router,这四样都属于外源性输入.内部生成均不符合其特性(workid,token解析参数等)
假设新增上下文关键词为Keys(gin框架的上下文关键字),新增两个方法SetKeys,GetKeys.
@gqcn

**Comment by gqcn** [comment]
@XWR940711 内部的上下文变量可以改进一下增加一个`Context`的`Map`来实现。至于前置与路由规则的校验绑定，仔细想了想不太合适。接口的数据校验交给具体的接口实现函数来处理比较合适，如果统一放到路由注册那块配置的话，容易引起管理混乱。
