### ISSUE TITLE
gconv strint转int：一个疑似bug的操作

### ISSUE THREAD

**Issue by rxrddd** [gogf/gf#541]
```
	fmt.Println(gconv.Int("0010"))//结果是8
	fmt.Println(strconv.Atoi("0010"))//结果是10
```

**Comment by welldonexing** [comment]
非常验证的bug

**Comment by welldonexing** [comment]
非常严重的bug

**Comment by gqcn** [comment]
@rxrddd @welldonexing `gconv.Int`支持自动识别八进制和十六进制的字符串转换为整型，你这里的字符串`0010`的前置0整型表示的是八进制，标准库方法`strconv.Atoi`是强制按照10进制转的：`Atoi is equivalent to ParseInt(s, 10, 0), converted to type int.`。此外还有0X开头的十六进制。你要注意`0010`和`10`在整型里面本身就是不同的概念哦。

你要将八进制字符串当作十进制用可以把前置`0`去掉再转，`gconv.Int`不会自动去掉的，严谨地讲，开发者传入给`gconv.Int`方法的参数都是有意义的。

这并不是BUG，反而是`gconv.Int`将细节处理得比较好的地方。

**Comment by welldonexing** [comment]
那如果强行10进制如何办
