### ISSUE TITLE
orm insert was cut by linefeeds 

### ISSUE THREAD

**Issue by starDemo** [gogf/gf#543]
### 1. What version of `Go` and system type/arch are you using?

go version go1.14 darwin/amd64

### 2. What version of `GoFrame` are you using?

v1.11.5
### 3. Can this issue be reproduced with the latest release?

Yes

### 4. What did you do?
Insert a markdown article into mysql,`mysql 5.7` data type is `mediumtext` 

```golang
func main() {
	content := gfile.GetContents("test.md")
	article := article_content.Entity{
		Id:      0,
		Title:   "test-article",
		Content: content,
	}
	_, err := article_content.Insert(article)
	if err != nil {
		glog.Error("insert data error：",err)
	}
}
```

### 5. What did you expect to see?

The whole data insert into db.

### 6. What did you see instead?

Insert data was cut after `\n`

**Comment by starDemo** [comment]
navicat bug 😅

**Comment by gqcn** [comment]
@starDemo I was sincerely wish it a bug.
