### ISSUE TITLE
Configuration file loaded incorrectly（[viewer]）

### ISSUE THREAD

**Issue by yongfly** [gogf/gf#545]
Item [viewer] loaded incorrectly in configuration file.

example config.toml:
[viewer]
  Path = "template"
  DefaultFile = "index.html"
  Delimiters = ["${", "}"]

These values have no effect when the project is started。

**Comment by xuanyanwow** [comment]
same question.
==================
同样出现该问题，默认配置文件是 "${"  "}"
使用的时候还是得用 {{.}}
