### ISSUE TITLE
gf框架如何开发微服务功能

### ISSUE THREAD

**Issue by bojiuyunkai** [gogf/gf#551]
想用gf开发rpc微服务，但是发现没有相关功能，譬如服务治理，服务发现，服务注册，rpc调用相关，是否后续会加入。

**Comment by gqcn** [comment]
@bojiuyunkai 你好，服务治理是比较复杂的一块，涉及到很多第三方工具的整合。`GoFrame`被设计为通用的基础开发框架，提供的都是基础包，基础框架内不会提供微服务治理的相关组件。不过未来可能会通过独立模块的形式提供一些微服务的组件。此外，推荐使用容器编排集群和独立封装RPC调用模块的方式来实现基础的服务治理能力。
