### ISSUE TITLE
glog是否考虑支持logrus的Fields特性

### ISSUE THREAD

**Issue by utopiaprince** [gogf/gf#553]
### 1. What version of `Go` and system type/arch are you using?
go version go1.13.7 darwin/amd64

### 2. What version of `GoFrame` are you using?
GoFrame CLI Tool v0.6.0, https://goframe.org
Install Path: /usr/local/bin/gf
Build Detail:
  Go Version:  go1.13.5
  GF Version:  v1.11.3
  Git Commit:  2079c3b19349f6dc3890c210e32503dd7d04dbeb
  Build Time:  2020-01-18 00:12:13

### 4. What did you do?
glogs是否能支持logrus的Fields特性，打印调试信息的时候，如果变量多需要手动组织Sprintf语句。
Logrus的Fields可以把日志以结构化的形式体现，更加方便添加、删除。
```
log.WithFields(log.Fields{
  "event": event,
  "topic": topic,
  "key": key,
}).Fatal("Failed to send event")
```

**Comment by gqcn** [comment]
@utopiaprince 你期望的结果是不是：
```go
glog.Print(g.Map{
    "event": event,
    "topic": topic,
    "key": key,
})
```

**Comment by utopiaprince** [comment]
有点出入，但是大概了解你的意思了。
我期望的是：
```
glog.WithFileds(g.Map{
    "event": event,
    "topic": topic,
    "key": key,
}).Info("xxxx")
```
按照你给的思路应该是：
```
glog.Info(g.Map{
    "event": event,
    "topic": topic,
    "key": key,
    "log": "xxxx",
})
```

**Comment by gqcn** [comment]
> 有点出入，但是大概了解你的意思了。
> 我期望的是：
> 
> ```
> glog.WithFileds(g.Map{
>     "event": event,
>     "topic": topic,
>     "key": key,
> }).Info("xxxx")
> ```
> 
> 按照你给的思路应该是：
> 
> ```
> glog.Info(g.Map{
>     "event": event,
>     "topic": topic,
>     "key": key,
>     "log": "xxxx",
> })
> ```

这是不是你想要的效果？`glog`设计需要考虑从简便和性能之间取一个平衡，所以对`map`类型的参数是直接支持的，按照`json`打印。

**Comment by utopiaprince** [comment]
恩，可以解决大部分问题。感谢您的解答。
