### ISSUE TITLE
默认全局配置不能支持多个文件

### ISSUE THREAD

**Issue by bojiuyunkai** [gogf/gf#555]
现在model等好几个地方默认都用的全局配置，但是全局配置只能指定一个config.toml配置文件，耦合了服务器，日志和数据库，有的业务场景数据库有十几个，而且是分环境的，目前配置都放到一个配置文件，不好管理。

**Comment by gqcn** [comment]
@bojiuyunkai 在`GoFrame`框架中，推荐一个单例配置管理对象对应一个配置文件，不过目前单例对象的名称仅对应名称，我改进下获取单例时默认查找单例名称对应的`toml`配置文件。下个版本发布。
