### ISSUE TITLE
g.Cfg().SetPath重新设置配置目录与初始化引入问题

### ISSUE THREAD

**Issue by arieslee** [gogf/gf#556]
### 1. What version of `Go` and system type/arch are you using?

+
go version go1.13 darwin/amd64

### 2. What version of `GoFrame` are you using?

gf v1.11.4

### 4. What did you do?

boot.go中我会执行一下g.Cfg().SetPath("/var/config")来设置一下配置文件所在的目录！
然后有一个名为attachmeng.go的model
在一个service中会调用attahment.Model.Where().One()

执行go run main.go就会报错说，找不到配置文件"panic: database init failed: "database" node not found, is config file or configuration missing?"
调试信息中显示
是因为调用了model/attachment.init方法

model/attachment/attachment_model.go:29  29行的内容为	
```
Model = &arModel{g.DB("default").Table(Table).Safe()}
```

能不能不自动执行model.init方法？

**Comment by gqcn** [comment]
@arieslee 你保证你的设置是先于使用即可。一般来说，将所有的设置放在`boot`包中，并且在`main`的引入时将`boot`的引入放置于所有包最前面，即不可能会产生任何问题。这都是约定俗成的。若有问题请继续回复，没有请关闭。

**Comment by arieslee** [comment]
> @arieslee 你保证你的设置是先于使用即可。一般来说，将所有的设置放在`boot`包中，并且在`main`的引入时将`boot`的引入放置于所有包最前面，即不可能会产生任何问题。这都是约定俗成的。若有问题请继续回复，没有请关闭。

现在的问题是，我把初始化设置放到boot中，不行，会报找不到config.toml的错误，但是，我把boot改成a 再引入就没有问题了

**Comment by gqcn** [comment]
@arieslee 会否还有问题？

**Comment by arieslee** [comment]
> @arieslee 会否还有问题？

刚才测试了，可以正常运行了，没有问题了
