### ISSUE TITLE
希望添加RabbitMQ的功能

### ISSUE THREAD

**Issue by duolabmeng6** [gogf/gf#562]
1.RabbitMQ 连接池
2.channel通道复用和不复用
3.断线重连
4.断线异常 通道异常 队列异常 可以捕获和处理

感谢~

**Comment by gqcn** [comment]
@duolabmeng6 你好，`GoFrame`为一个通用的基础开发框架，只提供通用的基础包，`RabbitMQ`不算是通用的模块，因此`gf`官方不会提供类似实现。你可以选择比较流行的第三方包使用，也可以为`gf`提供贡献，作为第三方社区包提供。
