### ISSUE TITLE
需要提供一个从时间戳转 gtime 的接口

### ISSUE THREAD

**Issue by KISSMonX** [gogf/gf#563]
目前是没有。
需要先调用原生的 time.Unix 转成 time
然后再从 time 转成 gtime， 很不优雅。

**Comment by gqcn** [comment]
@KISSMonX 当然，没有是不可能的，不可能是没有的：https://pkg.go.dev/github.com/gogf/gf/os/gtime?tab=doc#NewFromTimeStamp

**Comment by KISSMonX** [comment]
多谢，
我文档搜错关键词了。
