### ISSUE TITLE
model无法支持分表查询

### ISSUE THREAD

**Issue by bojiuyunkai** [gogf/gf#567]
go version go1.13.8 linux/amd64

### 2. What version of `GoFrame` are you using?

github.com/gogf/gf v1.11.6
### 3. Can this issue be reproduced with the latest release?

no

### 4. What did you do?

    Table = "user"
	// Model is the model object of user.
	Model = &arModel{g.DB("kernel").Table(Table).Safe()}
        Model.FindOne();

### 5. What did you expect to see?

Currently, the model only supports single table, but our business scenario is that a table is divided into n tables according to the primary key hash. Can the model support query according to a certain field sub-table?

**Comment by gqcn** [comment]
@bojiuyunkai Yep, GF's ORM does not support sub-tables currently. Any suggestion will be appreciated.
