### ISSUE TITLE
paramsMap是否需要出现在GetRequestMap的返回值中

### ISSUE THREAD

**Issue by XWR940711** [gogf/gf#570]
我在官方文档中看到对paramsMap的解释为自定义参数(paramsMap       map[string]interface{} // Custom parameters map.)而GetRequestMap的释义为GetRequestMap retrieves and returns all parameters passed from client as map.从客户端传递的所有参数.那自定义参数从GetRequestMap中返回不是很合理.

**Comment by gqcn** [comment]
@XWR940711 开发者可以在请求中自定义一些变量设置，自定义变量的获取优先级是最高的，可以覆盖原有的客户端提交参数。自定义变量往往也可以做请求流程的变量共享，但是需要注意的是该变量会成为请求参数的一部分，是对业务执行流程公开的变量。不需要公开的上下文变量，可以通过`Context`来设置。

**Comment by XWR940711** [comment]
@gqcn 那是否在文档以及代码的注释处重新描述或者定义一下这个概念而不是使用自定义参数这个描述词

**Comment by gqcn** [comment]
@XWR940711 你好，文档已更新：
1. 自定义变量 https://goframe.org/net/ghttp/request/custom
1. 上下文变量 https://goframe.org/net/ghttp/request/context

感谢你的建议，若有问题或建议欢迎随时反馈。
