### ISSUE TITLE
同一个模板不能再次被WriteTpl

### ISSUE THREAD

**Issue by GuardAngelY** [gogf/gf#576]
问题描述:
在WriteTpl一个模板页时 第一次能正常显示, 第二次及之后直接显示空页

错误地址:
跟进代码后发现是第二次进入时取得模板单例后在
Go/src/html/template/template.go
Parse -> checkCanParse
checkCanParse 抛出错误 html/template: cannot Parse after Execute

代码跟踪:
vendor/github.com/gogf/gf/net/ghttp/ghttp_response_view.go:61
github.com/gogf/gf/net/ghttp.(*Response).WriteTpl
-> github.com/gogf/gf/net/ghttp.(*Response).ParseTpl

vendor/github.com/gogf/gf/os/gview/gview_doparse.go:104
github.com/gogf/gf/os/gview.(*View).Parse

**Comment by gqcn** [comment]
@GuardAngelY 你好，我没有复现你说的问题，能否最小完整复现该问题的代码？

**Comment by GuardAngelY** [comment]
> @GuardAngelY 你好，我没有复现你说的问题，能否最小完整复现该问题的代码？

刚才新建了个空项目测试, 只有开启view的自动转义才会出现这样的问题
# Template.
[viewer]
    AutoEncode  =  true

最小复现代码
package main

import (
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/net/ghttp"
)

func main() {
	s := g.Server()
	s.BindStatusHandlerByMap(map[int]ghttp.HandlerFunc{
		404: func(r *ghttp.Request) { r.Response.WriteTpl("404.html") },
	})
	s.Run()
}

**Comment by gqcn** [comment]
@GuardAngelY 感谢反馈，已修复，请更新最新的master分支代码再试试，该修复将会随着`v1.12`版本发布。

**Comment by GuardAngelY** [comment]
@gqcn 感谢，已测试一切正常😋
