### ISSUE TITLE
ghttp_server_handler.go index out of range

### ISSUE THREAD

**Issue by liuheqi** [gogf/gf#578]
ghttp_server_handler.go line48~53为什么不用strings的trim呢？
在类似URL.PATH==“//////”这样的情况，会有index out of range 的panic

```
// 去掉末尾的"/"号
if r.URL.Path != "/" {
	for r.URL.Path[len(r.URL.Path)-1] == '/' {
		r.URL.Path = r.URL.Path[:len(r.URL.Path)-1]
	}
}
```

**Comment by gqcn** [comment]
@liuheqi 你好，非常感谢你能会这么关注实现细节，很少有小伙伴会这么仔细。这里主要是为了性能考虑，`strings`包的大部分方法比较注重`unicode`处理，也就是说即使你的字符串参数是中文其实也是支持得非常好，但是这种支持是有一定的性能损耗。如果是纯`ASCII`的话，像这里这么简单的逻辑，我这么处理性能大概会比用`strings`包的`TrimRight`方法高出十几倍的差距。

这里是我新增的基准测试源代码：https://github.com/gogf/gf/blob/master/net/ghttp/ghttp_z_bench_test.go 
以下为我本机运行截图：
![image](https://user-images.githubusercontent.com/26347176/77319340-a5355f00-6d49-11ea-95c2-c365a2ee78bc.png)


这里确实存在越界的问题，已修复。
