### ISSUE TITLE
gf版本1.11.6和1.11.7模版变量无法解析

### ISSUE THREAD

**Issue by 1307super** [gogf/gf#579]
升级到1.11.6和1.11.7后 模版变量，内置函数，自定义函数等无法解析

复现方式： 升级到1.11.6或者1.11.7
```go
func main() {
	//g.Server().Run()
	s := g.Server()
	s.BindHandler("/aaa", func(r *ghttp.Request){
		r.Cookie.Set("theme", "default")
		r.Session.Set("name", "john")
		content :=`Config:{{.Config.redis.cache}}, Cookie:{{.Cookie.theme}}, Session:{{.Session.name}}, Query:{{.Query.name}}`
		r.Response.WriteTplContent(content, nil)
	})
	s.SetPort(8199)
	s.Run()
}
```
会原样输出， 降级到1.11.5解决

**Comment by gqcn** [comment]
@1307super 你看下你有没有设置模板解析的分隔符号为`${`和`}`？你可以打开`GoFrame`框架的调试模式看看具体的模板引擎对象的配置是什么：https://goframe.org/frame/g/debug

**Comment by 1307super** [comment]
配置文件：
`[viewer]
    paths        = "template"
    defaultFile = "index.html"
    delimiters  =  ["${", "}"]
`
1.11.5:
![image](https://user-images.githubusercontent.com/35326304/77714563-45260d80-7014-11ea-9215-509a04e253a5.png)
解析正常

1.11.6:
![image](https://user-images.githubusercontent.com/35326304/77714624-70106180-7014-11ea-811f-4483ba7d4af9.png)
还是原样输出了{{.Config.redis.cache}}

1.11.7:
![image](https://user-images.githubusercontent.com/35326304/77714702-a4841d80-7014-11ea-8216-a4a660922cb5.png)
还是原样输出

**Comment by gqcn** [comment]
@1307super 你的模板引擎的分隔符号是这个：

**Comment by 1307super** [comment]
> @ 1307super你的模板引擎的分隔符号是这个：
> 
> ![图片](https://user-images.githubusercontent.com/26347176/77821664-ec936500-7126-11ea-88d0-c6933d27d2e2.png)

非常感谢

**Comment by zhenhua1** [comment]
> > @ 1307super你的模板引擎的分隔符号是这个：
> > ![图片](https://user-images.githubusercontent.com/26347176/77821664-ec936500-7126-11ea-88d0-c6933d27d2e2.png)
> 
> 非常感谢

请问你的模板能渲染出来吗？为什么我的模板渲染还是显示出源码，我这里没有用到解析变量只是渲染模板
![2df900a5eecd78631b8686d610d53ff](https://user-images.githubusercontent.com/22211474/77850979-b9c19d80-7208-11ea-9135-76c57a8dfa58.png)

**Comment by EricRun** [comment]
> > > @ 1307super你的模板引擎的分隔符号是这个：
> > > ![图片](https://user-images.githubusercontent.com/26347176/77821664-ec936500-7126-11ea-88d0-c6933d27d2e2.png)
> > 
> > 
> > 非常感谢
> 
> 请问你的模板能渲染出来吗？为什么我的模板渲染还是显示出源码，我这里没有用到解析变量只是渲染模板
> ![2df900a5eecd78631b8686d610d53ff](https://user-images.githubusercontent.com/22211474/77850979-b9c19d80-7208-11ea-9135-76c57a8dfa58.png)

图中的模板解析特征是 `${}`
