### ISSUE TITLE
github.com/gogf/gf/g/net/ghttp.(*Server).handleRequest处理path没考虑周全导致出错

### ISSUE THREAD

**Issue by snail007** [gogf/gf#58]
http: panic serving xxx:xxx runtime error: index out of rangegoroutine 49358 [running]:
net/http.(*conn).serve.func1(0xc4203e6000)
/usr/local/go/src/net/http/server.go:1726 +0xd0
panic(0xbfa3c0, 0x12dee50)
/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/gogf/gf/g/net/ghttp.(*Server).handleRequest(0xc420274400, 0xde0d40, 0xc4207161c0, 0xc420a8a300)
github.com/gogf/gf/g/net/ghttp/ghttp_server_handler.go:40 +0x58
40行

for r.URL.Path[len(r.URL.Path) - 1] == '/' {

如果r.URL.Path是空，就会导致访问数组越界。

**Comment by johngcn** [comment]
@snail007 奇怪了呢，还没遇到过r.URL.Path为空的情况，即使请求`http://www.xxx.com`的话也会有值的，默认是`/`。我还是加个判断吧。

**Comment by snail007** [comment]
我运行的时候偶尔就出来几次。

**Comment by johngcn** [comment]
@snail007 感谢反馈，已改进。
