### ISSUE TITLE
多实例下 最后一个start的实例的分组路由无法绑定

### ISSUE THREAD

**Issue by 1307super** [gogf/gf#581]
在main.go里 绑定分组域名没问题

在router.go里 获取第二个实例后使用分组路由不行，使用函数注册的方式可以

在main.go里绑定
![image](https://user-images.githubusercontent.com/35326304/77490809-f3944c00-6e76-11ea-970c-440e27b288e9.png)
![image](https://user-images.githubusercontent.com/35326304/77490825-01e26800-6e77-11ea-8f8e-3cea338141be.png)

在router.gol里绑定
![image](https://user-images.githubusercontent.com/35326304/77490850-17f02880-6e77-11ea-9386-9a60cf8e6e2e.png)

![image](https://user-images.githubusercontent.com/35326304/77490935-55ed4c80-6e77-11ea-87fc-ef934477ff5d.png)
![image](https://user-images.githubusercontent.com/35326304/77490945-5ab20080-6e77-11ea-8158-672d35536816.png)

可以看到 在main.go里没问题， 但是在router.go里获取api实例后使用分组路由不行， 使用函数注册的方式可以

打断点看到的错误
![image](https://user-images.githubusercontent.com/35326304/77491182-08bdaa80-6e78-11ea-8247-753806676252.png)

**Comment by kxy000** [comment]
。。。。手抖 更新了，发现多实例有问题。过来看才知道。。
