### ISSUE TITLE
failed to use ghttp client with basicAuth

### ISSUE THREAD

**Issue by starDemo** [gogf/gf#583]
### 1. What version of `Go` and system type/arch are you using?

go version go1.14 darwin/amd64

### 2. What version of `GoFrame` are you using?

v1.11.4
### 3. Can this issue be reproduced with the latest release?

Yes

### 4. What did you do?

```golang
func CheckHealth( brokerName string )  {
	client = ghttp.NewClient()
	client.SetBasicAuth("admin", "admin")
	reqUri := host + "/api/jolokia/read/org.apache.activemq:type=Broker,brokerName=" + brokerName +",service=Health/CurrentStatus"
	res, err := client.Get(reqUri)
	if err != nil {
		mlog.Error("CheckHealth error:",err)
		return
	}
	defer res.Close()
	data := res.ReadAllString()
	if res.StatusCode >= 300 {
		mlog.Error("CheckHealth response status error:",res.Status)
		return
	}
	fmt.Println(data)
}
```
use gf ghttp client to do requst with basicAuth failed,got 401 Unauthorized

### 5. What did you expect to see?

do request with auth pass

### 6. What did you see instead?

got 401 Unauthorized

**Comment by gqcn** [comment]
@starDemo 这块有单元测试，要不你试试最新框架代码。

**Comment by starDemo** [comment]
`v1.11.4` 版本有问题，后边版本修复了 群里反馈过
