### ISSUE TITLE
go搭建的静态服务器（前端用的vue），页面刷新或路由访问Not Found

### ISSUE THREAD

**Issue by baby315058688** [gogf/gf#584]
### 1. What version of `Go` and system type/arch are you using?
>go 1.14, windows 10/amd64

### 2. What version of `GoFrame` are you using?
> v1.11.3

### 4. What did you do?
>用goframe搭建了一个静态服务器（前端用的是vue），刷新或者访问其他路由地址都是404

![2](https://user-images.githubusercontent.com/33510725/77710516-38e88300-7009-11ea-9d41-5b59b3eef130.jpg)
![1](https://user-images.githubusercontent.com/33510725/77710517-3a19b000-7009-11ea-809d-f77c9d7afae0.jpg)

>nginx的做法是：

![404](https://user-images.githubusercontent.com/33510725/77710437-f030ca00-7008-11ea-961b-24a4e016c520.png)

### 5. What did you expect to see?
>应该进行什么操作能够正常访问，谢谢~

###

**Comment by gqcn** [comment]
@baby315058688 静态访问是支持`index.html`自动寻址的，你确定下你截图中的`home`和`demo`目录下有此静态文件存在。

**Comment by baby315058688** [comment]
因为用的是vue打包好的文件， 所以是没有home和demo目录的，

**Comment by baby315058688** [comment]
1

**Comment by baby315058688** [comment]
因为用的是vue打包好的文件，所以没有home和demo目录的。

> 以下是vue打包好的文件夹中的文件：

![1585532690(1)](https://user-images.githubusercontent.com/33510725/77867739-1eaddf80-726b-11ea-97e0-bea942e3a529.jpg)

我是把该打包文件夹中的文件放到了 gf 的 public 文件目录中，然后运行程序的。

> public文件夹的文件：

![1585533306(1)](https://user-images.githubusercontent.com/33510725/77868129-8fa1c700-726c-11ea-91b3-803ef41c104e.jpg)


在vue开发环境下是没有问题的， 任何页面都能正常访问。

**Comment by baby315058688** [comment]
已解决， 我后来看了一下ghttp的接口文档， 有server.AddStaticPath这个函数 将uri设置为静态文件服务的静态目录路径映射

**Comment by zut** [comment]
> 已解决， 我后来看了一下ghttp的接口文档， 有server.AddStaticPath这个函数 将uri设置为静态文件服务的静态目录路径映射

@Tongzp 我也是vue 打包好的dist文件放到 public里面, 想直接静态文件服务提供服务, 省得了nginx,

请问你是如何解决了? 麻烦给一下 例子? 谢谢

**Comment by icehomura** [comment]
我来提供一个笨办法
在`s.Run()`前面添加以下代码
```go
s.BindStatusHandler(404, func(r *ghttp.Request) {
	r.Response.Header().Set("Content-Type", "text/html")
	r.Response.ServeFile("frontend/dist/index.html") // 根据实际情况填写index.html文件的具体路径
})
```
