### ISSUE TITLE
日志接口设计是否冗余，以下是我的使用反馈

### ISSUE THREAD

**Issue by tianxia0079** [gogf/gf#587]
func log() {
	glog.Info("1")
	glog.Error("2")
	g.Log().Debug("debug")
	g.Log().Info("info")
	g.Log().Error("error")
}
前两个输出1 2，不会到日志文件，但是用起来简单直接，感觉和日志没啥关系。
其实日志主要用的是后面这三个。但是写法很麻烦。
问题1：
设置前面这两个函数的目的是什么？
问题2：
后面这三个的写法可以简洁点吗？

如果说，如果前两个的设计没什么意义的情况下，可以吧后面三个写法使用前面两张的写法来，前面的两个删除掉吧

**Comment by tianxia0079** [comment]
我去，才发现glog不是gf里的！
大佬，gf里日志写法，可以参考glog.Info("1")这样吗？
写法简单点

**Comment by tianxia0079** [comment]
看出来了！
glog.Error("...")
开发工具就到golang/glog包了，和gf的glog命名冲突了！

希望吧gf的glog包名改一下，别和golang的冲突！

**Comment by gqcn** [comment]
@tianxia0079 `gf`框架里面的日志组件可以通过`g.Log()`单例对象也可以通过`glog`包名来使用，两者区别详见官网文档。
