### ISSUE TITLE
解析模板出现无法解析

### ISSUE THREAD

**Issue by zhenhua1** [gogf/gf#593]
调用goframe中的Response.WriteTpl("admin/layout/main.html")，或者View.Display("admin/layout/main.html")，url访问都是将模板中的代码输出来了不能解析出模板内容

![MD`0 CQR)%{04JZM `C3T2J](https://user-images.githubusercontent.com/22211474/77844195-f5437400-71d6-11ea-8b98-3a40c58d6dd2.png)

**Comment by gqcn** [comment]
@zhenhua1 你用的是最新框架版本吗？

**Comment by zhenhua1** [comment]
是的，是不是最新版本有什么改动了，还是其他情况，正确的用法是什么，我这边需要怎么做。现在输出模板一直无法展示
![3b2a5a04018dc49722f9d8ac2d25c88](https://user-images.githubusercontent.com/22211474/77849112-c8558800-71fb-11ea-889d-b61baa731955.png)

**Comment by zhenhua1** [comment]
> @ zhenhua1你用的是最新框架版本吗？

是的，是不是最新版本有什么改动了，还是其他情况，正确的用法是什么，我这边需要怎么做。现在输出模板一直无法展示
![3b2a5a04018dc49722f9d8ac2d25c88](https://user-images.githubusercontent.com/22211474/77849207-8416b780-71fc-11ea-8135-3a9fa3a3434e.png)

**Comment by gqcn** [comment]
@zhenhua1 你参考下这个类似的问题：https://github.com/gogf/gf/issues/579

**Comment by zhenhua1** [comment]
> @zhenhua1 你参考下这个类似的问题：#579

我这边试了还是渲染模板会把html原样显示出来，我这里只是渲染模板没有变量解析，而且debug中没有任何报错
![Uploading 2df900a5eecd78631b8686d610d53ff.png…]()
![38532410dcfde920e525a793c3c46f5](https://user-images.githubusercontent.com/22211474/77851137-f0e47e80-7209-11ea-9459-29b2b1873257.png)

**Comment by zhenhua1** [comment]
> @zhenhua1 你参考下这个类似的问题：#579
gf框架最新版本模板渲染不出来，直接把模板中的html输出来了，这是什么问题，能说一下怎么解决吗
