### ISSUE TITLE
基于gf的TCP物联网设备采集服务框架。实现了多协议切换和粘包处理，通过go反射实现业务分发。

### ISSUE THREAD

**Issue by zxk69809** [gogf/gf#599]
安徽银通物联，基于gf的TCP物联网设备采集服务框架。实现了多协议切换和粘包处理，通过go反射实现业务分发。
补上代码
https://github.com/zxk69809/GoServer

_Originally posted by @zxk69809 in https://github.com/gogf/gf/issues/168#issuecomment-500661381_

**Comment by gqcn** [comment]
@zxk69809 感谢对gf的支持，你可以将案例提交到这里：https://github.com/gogf/gf/issues/168
