### ISSUE TITLE
协诚状态下使用redis抛错

### ISSUE THREAD

**Issue by zhangHongBo21** [gogf/gf#603]
```go
pool := grpool.New(100000)
	t := time.Now()
	g.Redis().SetMaxIdle(100)
	g.Redis().SetMaxActive(10000)
	fmt.Println(t.Format("2006-01-02 15:04:05"))
	conn := g.Redis().Conn()
	for i := 0; i < 1000000000; i++ {
		v := i
		pool.Add(func() {
       //随便写的命令
			_, err := conn.Do("SCARD", "Kuang:status_set")
			if err != nil {
				fmt.Println(v)
				panic(err)
			}
		})
	}
	tt := time.Now()
	fmt.Println(tt.Format("2006-01-02 15:04:05"))
        sigterm := make(chan os.Signal, 1)
	signal.Notify(sigterm, syscall.SIGINT, syscall.SIGTERM)
	<-sigterm
```

**Comment by zhangHongBo21** [comment]
![image](https://user-images.githubusercontent.com/51777470/78111567-7137f900-742f-11ea-89ab-2238bc65162e.png)

**Comment by zhangHongBo21** [comment]
补充一下，这个是我测试的代码，具体应用场景是开协诚，在协诚中可以复用一个连接，所有协诚完成之后关闭连接，sync没加不影响抛错，上来直接就抛错 短写

**Comment by gqcn** [comment]
@zhangHongBo21 问题在于你将同一个链接对象复用，这样可能会造成一些不可预料的错误，其实Redis底层已经实现了连接池，你这样既可：
```go
package main

import (
	"fmt"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/os/grpool"
	"os"
	"os/signal"
	"syscall"
	"time"
)

func main() {
	pool := grpool.New(100000)
	t := time.Now()
	g.Redis().SetMaxIdle(100)
	g.Redis().SetMaxActive(10000)
	fmt.Println(t.Format("2006-01-02 15:04:05"))
	for i := 0; i < 100; i++ {
		v := i
		pool.Add(func() {
			//随便写的命令
			_, err := g.Redis().Do("SCARD", "Kuang:status_set")
			if err != nil {
				fmt.Println(v)
				panic(err)
			}
		})
	}
	tt := time.Now()
	fmt.Println(tt.Format("2006-01-02 15:04:05"))
	sigterm := make(chan os.Signal, 1)
	signal.Notify(sigterm, syscall.SIGINT, syscall.SIGTERM)
}
```

**Comment by zhangHongBo21** [comment]
> @ zhangHongBo21问题在于你将同一个链接对象重叠，这样可能会造成一些不可预料的错误，其实Redis已经已经实现了连接池，你这样既可：
> 
> ```go
> 包主
> 
> 导入（
> 	 “ fmt ” 
> 	“ github.com/gogf/gf/frame/g ” 
> 	“ github.com/gogf/gf/os/grpool ” 
> 	“ os ” 
> 	“ os / signal ” 
> 	“ syscall ” 
> 	“时间”
> ）
> 
> func  main（）{
> 	 pool  ：= grpool。新的（100000）
> 	 t  ：=时间。现在（）
> 	G。Redis（）。SetMaxIdle（100）
> 	G。Redis（）。SetMaxActive（10000）
> 	fmt。的println（吨格式（“ 2006-01-02 15时04分05秒”））
> 	 为 我 ：=  0 ; 我< 100 ; 我++ {
> 		 v  ：= i
> 		池。加入（FUNC（）{
> 			 //随便写的命令
> 			_，ERR  ：=克Redis的（）。待办事项（“ SCARD ”，“旷：status_set ”）
> 			 如果！ERR = 零 {
> 				fmt。Println（v）
> 				 紧急（err）
> 			}
> 		}）
> 	}
> 	tt  ：=时间。现在（）
> 	fmt。的println（TT 格式（“ 2006-01-02 15时04分05秒”））
> 	 SIGTERM  ：=  化妆（瓒。OS 信号，1）
> 	信号。通知（SIGTERM，系统调用。SIGINT，系统调用。SIGTERM）
> }
> ```

不是我不想那么写，而是我试过了，会抛错。端口耗尽

**Comment by gqcn** [comment]
@zhangHongBo21 我试过了没有复现端口耗尽的问题，我用的是最新的`v1.12.1`版本。你试试？

**Comment by zhangHongBo21** [comment]
> @zhangHongBo21 我试过了没有复现端口耗尽的问题，我用的是最新的`v1.12.1`版本。你试试？

我知道大佬你为什么不会出现问题了，是因为循环次数的问题，端口号一台电脑有超过六万个，而我举的例子只有一百次，当然不会耗尽，而我本地的代码是循环超过十万次的，所以会端口耗尽

**Comment by zhangHongBo21** [comment]
我看了大佬封装redis的源码，有一个疑问，在异步处理的情况，我有一个协诚在redis池中取了一个链接，拼装管道中的命令，然后另一个协诚使用正常的  `g.Redis().Do()`方法，会不会意外关闭我管道所用的链接
![image](https://user-images.githubusercontent.com/51777470/78216533-aa826e80-74ec-11ea-8c90-e4f315882c75.png)

**Comment by zhangHongBo21** [comment]
捎带着还有个错误不知道咋处理，redis 报错  short write

**Comment by zhangHongBo21** [comment]
@gqcn

**Comment by gqcn** [comment]
@zhangHongBo21 我回头把数量改大点再试试哈

**Comment by gqcn** [comment]
@zhangHongBo21 你的`MaxActive`参数设置超过`Redis`允许的连接数限制了，你改成`100`试试。

**Comment by zhangHongBo21** [comment]
@gqcn 啊哈，尴尬，忘了，redis默认是一万链接数，
