### ISSUE TITLE
打包出二进制文件后，读取template目录问题

### ISSUE THREAD

**Issue by tianxia0079** [gogf/gf#604]
打包二进制时候template已经打包进去了，运行时想在exe同目录下放template目录，修改里面内容，实时生效。
请问可以做到吗，目前测试，是不生效的。
感谢回答

**Comment by gqcn** [comment]
@tianxia0079 由于优先是读取的资源管理中的内容，因此磁盘系统中的template目录下同名模板是不生效的。

**Comment by tianxia0079** [comment]
@gqcn 哪会加这个功能特性吗

**Comment by gqcn** [comment]
@tianxia0079 应该不会
