### ISSUE TITLE
ghttp post content bug

### ISSUE THREAD

**Issue by KiVirgil** [gogf/gf#605]
### 1. What version of `Go` and system type/arch are you using?

v1.14.1

### 2. What version of `GoFrame` are you using?

v1.12.1

### 3. Can this issue be reproduced with the latest release?
yes

### 4. What did you do?

```
var postData = `{
    "uid"         : 1,
    "sku_id"      : 10000,
    "amount"      : 19.99,
    "create_time" : "2020-03-26 12:00:00",
}`

j, _ := gjson.LoadJson(postData)

g.Client().RequestContent("POST", "http://127.0.0.1/xxxx", j.MustToJsonString())
```

then http server receive
`[{
    "uid"         : 1,
    "sku_id"      : 10000,
    "amount"      : 19.99,
    "create_time" : "2020-03-26 12:00:00",
}]`
this code is running OK in gf version v1.11.7.

**Comment by gqcn** [comment]
我看看

**Comment by gqcn** [comment]
@KiVirgil How does your server receive the JSON data? Can you provide the server codes receiving the JSON content?

**Comment by KiVirgil** [comment]
My fault, i have test this code with g.Server(), then it work well.
It might be the bug of "github.com/go-macaron/binding", because i use this tool to do data binding and validation.
I will close this issue, and thanks for your help
