### ISSUE TITLE
模板渲染问题

### ISSUE THREAD

**Issue by zhenhua1** [gogf/gf#606]
gf框架最新版本模板渲染不出来，直接把模板中的html输出来了，请问能详细剖析一下这个问题吗

**Comment by gqcn** [comment]
@zhenhua1 麻烦给一下可复现问题的最小代码我试试。

**Comment by gqcn** [comment]
@zhenhua1 或者你试试最新`master`分支的框架代码

**Comment by Ivy-1996** [comment]
这个问题我也遇到了，渲染模板直接输出的是html源码的文本格式,查看响应的Header
`Content-Type: text/plain; charset=utf-8`

**Comment by Ivy-1996** [comment]
需要自己手动设置才可以正常渲染
```golang
func Login(r *ghttp.Request) {
	r.Response.Header().Set("Content-Type", "text/html; charset=utf-8")
	r.Response.WriteTpl("login.html", g.Map{})
}
```

**Comment by zhenhua1** [comment]
> @zhenhua1 或者你试试最新`master`分支的框架代码

就是下述这位兄弟说的这样，看看咱们框架中能把这个问题给封装配置起来吗？这段时间，有好几个其他同事用咱们框架时，接连出现这种情况都不知道怎么解决，忘在下一个版本中能把这种设置给处理一下，谢谢

**Comment by gqcn** [comment]
> > @zhenhua1 或者你试试最新`master`分支的框架代码
> 
> 就是下述这位兄弟说的这样，看看咱们框架中能把这个问题给封装配置起来吗？这段时间，有好几个其他同事用咱们框架时，接连出现这种情况都不知道怎么解决，忘在下一个版本中能把这种设置给处理一下，谢谢

主要是我没复现你所说的情况，能给个复现该问题最小完整运行代码么？

**Comment by gqcn** [comment]
@zhenhua1 @Ivy-1996 这种情况一般是输出的内容没有被标准库的`net/http`自动识别到`mime`类型，可能是输出的内容头部有非HTML/XHTML/XML规范的代码。
