### ISSUE TITLE
go-micro 微服务中, 如何正确使用 ghttp.Server.defaultHandler 私有方法

### ISSUE THREAD

**Issue by hopher** [gogf/gf#608]
https://github.com/micro/go-micro 中 service.Handle 如何注入 gf Server defaultHandler?

```
func main() {
	// Create service
	service := web.NewService(
		web.Name("go.micro.api.greeter"),
	)

	service.Init()

	s := g.Server()
	// Register Handler
	// ...

	// s.defaultHandler 为一个实现 net/http Handler 接口 ServeHTTP 方法
	// 这里 defaultHandler 为私有方法, 有其它方式可以调用不?
	service.Handle("/", http.HandlerFunc(s.defaultHandler))

	// Run server
	if err := service.Run(); err != nil {
		log.Fatal(err)
	}
}
```

参考
- [gin 框架使用方法](https://github.com/micro/examples/blob/master/greeter/api/gin/gin.go)
- [net/http](https://golang.org/src/net/http/server.go)

**Comment by gqcn** [comment]
@hopher 你好，目前可以通过`s.Handler()`方法获得默认的入口方法，目前已改进`ghttp.Server`对象并增加了`http.ServeHTTP`接口方法的实现，已提交到`master`分支，预计最近这几天发布到小版本中。

**Comment by hopher** [comment]
@gqcn 

增加的 s.Handler 方法, s.config.Handler 是在 `g.Server().Run()` 调用时，才会判断

s.config.Handler == nil, 进行赋值 s.defaultHandler, 

但是在 go-micro 中，是不启动 g.Server().Run() 方法

github.com/gogf/gf/net/ghttp/ghttp_server.go - 307 行
```
	// Default HTTP handler.
	if s.config.Handler == nil {
		s.config.Handler = http.HandlerFunc(s.defaultHandler)
	}
```

github.com/gogf/gf/net/ghttp/ghttp_server.go
```
// Handler returns the request handler of the server.
func (s *Server) Handler() http.Handler {
	if s.config.Handler == nil {
		return http.HandlerFunc(s.defaultHandler)
	}
	return http.HandlerFunc(s.config.Handler)
}
```

建议: 

```
// Handler returns the request handler of the server.
func (s *Server) Handler() http.Handler {
	return s.config.Handler
}
```

**Comment by gqcn** [comment]
@hopher 那你用`master`分支吧，已经实现了`ServeHTTP`接口。

**Comment by mushu1990** [comment]
刚好有这个需求，就看到有人提issue了，好棒
