### ISSUE TITLE
server设置timeout无效

### ISSUE THREAD

**Issue by piaohao** [gogf/gf#61]
### 1. What version of `Go` and system type/arch are you using?
go 1.12, linux/amd64

### 2. What version of `GoFrame` are you using?
1.5.17

### 3. Can this issue be reproduced with the latest release?
yes

### 4. What did you do?
```
s.SetReadTimeout(5 * time.Second)
s.SetWriteTimeout(10 * time.Second)
s.SetIdleTimeout(10 * time.Second)
```
server设置timeout无效

**Comment by johngcn** [comment]
@piaohao 这个是标准库的逻辑实现的超时处理。如果在业务接口中`Sleep`不会触发超时控制，上传/下载大文件，或者网速比较慢的时候可能会触发超时，具体请查看这张图：
![04161522_Ke35](https://user-images.githubusercontent.com/26347176/55338032-5f491080-54d2-11e9-8560-527b9cb9fe64.png)

此外可以参考一下这篇文章：https://colobu.com/2016/07/01/the-complete-guide-to-golang-net-http-timeouts/

**Comment by piaohao** [comment]
gf是否能用hook实现超时拦截处理，如下：
```
timeout := make(chan bool, 1)
go func() {
    time.Sleep(10 * time.Second)
    timeout <- true
}()

select {
case <-ch:
    // 处理handler响应
case <-timeout:
    // 处理timeout响应
}
```
在高并发的场景下，如果客户端的请求连接长时间不释放，会导致服务器性能越来越差。

**Comment by johngcn** [comment]
@piaohao  你知道标准库的`net/http.Server`是来一个请求就创建一个`goroutine`来处理，并且你应该也知道一个死循环的`goroutine`是没有办法被主动驱逐的，你这里的`Sleep`是类似的道理。

**Comment by johngcn** [comment]
@piaohao HOOK不能拿来做这个事情，HOOK不是异步的，它是属于请求流程中同步处理逻辑的一部分，因此它和被处理的请求处于同一个`goroutine`中。
