### ISSUE TITLE
/tmp目录下会创建一系列可执行文件，是否有可能更改这些文件的位置？

### ISSUE THREAD

**Issue by linhongzhao321** [gogf/gf#610]
我发现我在服务器上运行goframe后，在`/tmp`目录下会出现
`go-build089371149  go-build339618739  go-build412463112  go-build523798692  gproc  gsessions`
这些文件，并且属主是我个人在服务器上的账号，这会导致其他人无法正常在服务器上运行项目。
请问
1. 这些文件的作用是什么？
2. 我是否有可能通过配置文件修改这些文件的路径？
3. 因为这个服务器需要多个人共同使用的，请问我是否可以直接通过修改这些文件权限为555解决，或有其他推荐的解决方案？

**Comment by linhongzhao321** [comment]
我在官方文档中没找到关于这一部分的描述

**Comment by linhongzhao321** [comment]
我发现在`gfile.go`下写死了这个目录，是否能发个新版本修正一下？使其可配置？ 
![image](https://user-images.githubusercontent.com/33045301/78630848-50f3b880-78cd-11ea-9505-d9ee692a8894.png)

**Comment by gqcn** [comment]
@linhongzhao321 `gproc`是目前进程间通信依赖的文件，未来版本会去掉。`gsession`是`SESSION`存放目录，可以通过`Server`的配置文件项修改。

此外，`gfile`中的`tempDir`是临时目录，那个是给临时方法`TempDir`用的，往往等同于`os.TempDir`，有的模块会将文件写入到临时目录，会用到它。
