### ISSUE TITLE
orm增加两个方法inc/dec

### ISSUE THREAD

**Issue by XWR940711** [gogf/gf#611]
inc("filed",step),dec("filed",step),自增/自减对应的字段以及步进值.

**Comment by gqcn** [comment]
@XWR940711 `Update("field+=step")`或者`Update("field-=step")`即可。

**Comment by XWR940711** [comment]
@gqcn .Update("field= field -/+ " + gconv.String(step))  step一般都是数字 做字符拼接还要多一步类型转换.感觉还是很有必要新增该方法去处理.例如 inc(filed string,step interface{})

**Comment by gqcn** [comment]
@XWR940711 单个字段的递增/减都好处理，你也可以用`Update("field+=?", step)`，只是批量的话会比较麻烦。

**Comment by arieslee** [comment]
> @XWR940711 单个字段的递增/减都好处理，你也可以用`Update("field+=?", step)`，只是批量的话会比较麻烦。

麻烦的是一次更新中有数量增/减，还有其他值更新，是吧？最近我也有这个困扰^_^

**Comment by XWR940711** [comment]
> > @XWR940711 单个字段的递增/减都好处理，你也可以用`Update("field+=?", step)`，只是批量的话会比较麻烦。
> 
> 麻烦的是一次更新中有数量增/减，还有其他值更新，是吧？最近我也有这个困扰^_^

对的.余额减少,累计消费额增加 现在就是执行两次update或者直接写sql做query = =

**Comment by gqcn** [comment]
> > > @XWR940711 单个字段的递增/减都好处理，你也可以用`Update("field+=?", step)`，只是批量的话会比较麻烦。
> > 
> > 
> > 麻烦的是一次更新中有数量增/减，还有其他值更新，是吧？最近我也有这个困扰^_^
> 
> 对的.余额减少,累计消费额增加 现在就是执行两次update或者直接写sql做query = =

你可以商用`Update("field1-=?, field2+=?", step1, step2)`
