### ISSUE TITLE
gvalid的验证问题

### ISSUE THREAD

**Issue by XWR940711** [gogf/gf#612]
### 1. What version of `Go` and system type/arch are you using?

go 1.14/win7 64bit

### 2. What version of `GoFrame` are you using?

github.com/gogf/gf v1.12.1

### 3. Can this issue be reproduced with the latest release?

v1.12.1 now

### 4. What did you do?
//重要重要重要---在middleware中使用了grpool.Add(func() {})//输出了glog.Println(r.GetMap())
//struct
type TixianApplysInput struct {
	// ApplyMoney 申请提现金额(分)
	ApplyMoney float64 `p:"apply_money" v:"required|integer|min:1#请填写提现金额|提现金额必须为整数|最低提现金额1分"`
}
//client params
apply_money:10.1

//Controller
	var data *TixianApplysRequest
	if err := r.Parse(&data); err != nil {
		if v, ok := err.(*gvalid.Error); ok {
			response.ErrorJson(r, 1, v.FirstString())
		}
	}

//response
最低提现金额1分/提现金额必须为整数 互跳 正确提示应该为(提现金额必须为整数)
修改apply_money:10 正确应该是通过验证,但是偶发提示(最低提现金额1分)
min:1错误报错若干次后触发无法恢复panic:
panic: multipart: NextPart: EOF

goroutine 341 [running]:
github.com/gogf/gf/net/ghttp.(*Request).parseForm(0xc0005ced80)
	C:/Go/bin/pkg/mod/github.com/gogf/gf@v1.12.1/net/ghttp/ghttp_request_param.go:229 +0x94d
github.com/gogf/gf/net/ghttp.(*Request).GetRequestMap(0xc0005ced80, 0x0, 0x0, 0x0, 0xc0004c1298)
	C:/Go/bin/pkg/mod/github.com/gogf/gf@v1.12.1/net/ghttp/ghttp_request_param_request.go:172 +0x5b
github.com/gogf/gf/net/ghttp.(*Request).GetMap(...)
	C:/Go/bin/pkg/mod/github.com/gogf/gf@v1.12.1/net/ghttp/ghttp_request_param.go:152
gf/app/service/middleware.CORS.func1()
	C:/Users/ky/Desktop/gf/app/service/middleware/cors.go:23 +0x1b8
github.com/gogf/gf/os/grpool.(*Pool).fork.func1(0xc0000056c0)
	C:/Go/bin/pkg/mod/github.com/gogf/gf@v1.12.1/os/grpool/grpool.go:111 +0x64
created by github.com/gogf/gf/os/grpool.(*Pool).fork
	C:/Go/bin/pkg/mod/github.com/gogf/gf@v1.12.1/os/grpool/grpool.go:105 +0x46

另外,字段类型为int 规则为required|min:0 那么required无法被执行(相当于被给了默认值)

**Comment by gqcn** [comment]
@XWR940711 怎么关闭掉了，问题解决了吗？

**Comment by ruanlianjun** [comment]
解决了吗，我也是同样的问题

**Comment by LonelySally** [comment]
> 解决了吗，我也是同样的问题

赶进度,最后自己手动写验证.互跳的原因是map在循环的时候是无序导致的.至于panic因为手动写验证了也就不存在了.

**Comment by youngsailor** [comment]
我也遇到了同样的问题，字段类型为int时，无法使用required

**Comment by gqcn** [comment]
@youngsailor @ruanlianjun @LonelySally 新版本`v1.16`已改进，具体详见文档：https://goframe.org/pages/viewpage.action?pageId=1114244
