### ISSUE TITLE
gstr.PosR系列方法使用问题

### ISSUE THREAD

**Issue by tianxia0079** [gogf/gf#613]
如下，通过pos系列方法截取中间字符串，返回的位置是吧一个中文按3字节计算，可是substr方法并没有这样。所以无法完成截取。
希望可以优化pos系列方法，返回真实的index无需考虑中文问题。
或者说，还有其他更优雅的方法完成截取吗？谢谢
```
       content:=`void("江苏南京市 中国电信");`
	intR := gstr.PosR(content, "\"")
	intL := gstr.PosI(content, "\"")
	content = gstr.SubStr(content, intL+1, intR)

```

**Comment by gqcn** [comment]
@tianxia0079 感谢建议，已改进提交到`master`分支，将会随着下一个小版本发布。
