### ISSUE TITLE
redis删除命令无效

### ISSUE THREAD

**Issue by tianxia0079** [gogf/gf#616]
conn := g.Redis().Conn()
	defer conn.Close()
	reply, err := conn.Do("DEL", sessionid)
	g.Log().Debug("退出时候 redis:", reply, err, sessionid)
使用这个进行删除，返回数量 1.也没有报错。但是数据库里这个key还是在，虽然里面值被清空了，但是希望真正执行del。

**Comment by gqcn** [comment]
@tianxia0079 你可以在`redis`终端通过`monitor`命令监控发生了什么指令操作细节。
