### ISSUE TITLE
框架选型：beego、gin、iris、echo、goframe？

### ISSUE THREAD

**Issue by misitebao** [gogf/gf#621]
作者大大，可以做一个GoFrame和其他Go语言框架的数据对比嘛？这样可以让用户更好的选择，同时也有更好的说服力。
Q：为什么提这个问题？
A：因为业务开发设计到框架选型的时候，就一定会在同类型的多种框架中选择一个合适的，想要从中找到一个“合适”的，那它必须要有相对于其他框架特有的优点，除了官网文档列举的那些优点以外，性能也是比较高的一个关注点，所以在这里恳请作者大大抽时间做一下这个吧。

**Comment by arieslee** [comment]
别问，问就是goframe

**Comment by sanrentai** [comment]
goframe 功能最多，不仅仅是web框架这么简单，支持tcp,udp等

**Comment by gqcn** [comment]
其实差别挺大的，我一直没抽时间来回答，感觉没太大必要，但是一直保留着这个issue。

**Comment by gqcn** [comment]
@arieslee @sanrentai @misitebao @chenall 抱歉回复晚了，这里有一篇社区小伙伴做的评估：https://goframe.org/pages/viewpage.action?pageId=3673375
