### ISSUE TITLE
分页方法使用bug反馈

### ISSUE THREAD

**Issue by tianxia0079** [gogf/gf#622]
分页方法如何用？这样用有bug，请核实
model := table.Order("id desc").Page(pageint, limit)
		total, _ = model.Count()
		results, _ := model.All();

查询第一页时候，total是对的，后面的页，total就是0.
希望升级page方法，返回三个数据，分别是：数据集合，总数，err

**Comment by gqcn** [comment]
@tianxia0079 参考以下用法：
```go
model := db.Table(table).Safe().Order("id")
all, err := model.Page(3, 3).All()
count, err := model.Count()
```
