### ISSUE TITLE
请教一下客户端提交json格式的多条数据到服务器上保存，最简单的方法是什么？

### ISSUE THREAD

**Issue by joyoes** [gogf/gf#629]
客户端提交的json数据格式如下，包括两条以上的数据，另外还包括关联成绩表的数据：
[
    {
        "Uid":1,
        "Name":"john",
        "Site_Url":"https://goframe.org",
        "NickName":"johng",
        "Pass1":"123",
        "Pass2":"456",
        "Scores":[
            {
                "id":"1",
                "result":60
            },
            {
                "id":"12",
                "result":70
            },
            {
                "id":"13",
                "result":20
            }
        ]
    },
    {
        "Uid":2,
        "Name":"smith",
        "Site_Url":"https://goframe.org",
        "NickName":"johng",
        "Pass1":"111",
        "Pass2":"222",
        "Scores":[
            {
                "id":"15",
                "result":100
            },
            {
                "id":"16",
                "result":80
            },
            {
                "id":"17",
                "result":80
            }
        ]
    }
]
请问一下，提交的两条数据要插入到个人信息表和成绩表中，最简单的办法应该怎么操作啊？求解答！比如说：要将以上的数据一次性插入到个人信息表和个人成绩信息表中，应该怎么操作？

**Comment by zcool321** [comment]
这个是业务文体，其实不是框架层面的；
建议：先批量插入个人信息，拿到个人信息唯一标识，再批量插入成绩表；为了可靠性可以加一层事务

**Comment by gqcn** [comment]
@joyoes 自己研究下吧。
