### ISSUE TITLE
glog. GetWriter问题

### ISSUE THREAD

**Issue by lijunfeng** [gogf/gf#63]
glog的GetWriter提供默认的文件IO，不建议为空；或者增加个公开方法返回logger.getFilePointer()，这样以便于将日志组件和其它例如xorm集成。

**Comment by johngcn** [comment]
@lijunfeng 已完成改进，随着下一版本发布。

**Comment by johngcn** [comment]
@lijunfeng 代码已发布，开发文档过段时间才会更新。

**Comment by johngcn** [comment]
@lijunfeng `Writer`的文档终于更新了 https://goframe.org/os/glog/writer
