### ISSUE TITLE
english documentation?

### ISSUE THREAD

**Issue by sundowndev** [gogf/gf#631]
Is this framework restricted to Chinese people?

**Comment by gqcn** [comment]
@sundowndev Nope, it's mainly used by Chinese teams currently, so it's well documented now in Chinese in https://goframe.org . English documentation is not available currently, but the comments and GoDoc( https://godoc.org/github.com/gogf/gf ) are all in English. Any English documentation contribution is appreciated.

**Comment by vitr** [comment]
It is really misleading to compare gf with Django, Laravel or SpringBoot and not having English docs. Are you going to start the translation soon?

**Comment by notjulian** [comment]
Hi @gqcn,
is it planned the translation of the doc in english ?

thanks

PS: english documentation, will really speed up the adoption if any ... think at "the history" of vue.js ...

**Comment by sundowndev** [comment]
@gqcn If the website was open source, it'd be easier for contributors to translate it, but it's not. There seem to be no starting point, like this isn't even a project goal. The fact that this issue is closed says it all.
