### ISSUE TITLE
Error: fetching tables failed:  sql: unknown driver "sqlite3" (forgotten import?)

### ISSUE THREAD

**Issue by hijxyz** [gogf/gf#634]
PS E:\gopath\src\fdc\wg_server> gf gen model
path './app/model' is not empty, files might be overwrote, continue? [y/n]: y
Error: fetching tables failed:
 sql: unknown driver "sqlite3" (forgotten import?)

I'm using sqlite as the database, and this problem occurs when I use the command gf gen model to generate the interface.

my database config is
[database]
    type = "sqlite"
    link = "app/model/wg_db.db"

**Comment by gqcn** [comment]
@hijxyz Database sqlite and oracle are not support in gf gen model command in default as it needs cgo and gcc, you can manually make some changes to the source codes and do the building.
