### ISSUE TITLE
官网关于文件上传的说明有问题

### ISSUE THREAD

**Issue by alienyan** [gogf/gf#639]
这一页：https://goframe.org/net/ghttp/client/demo/upload

> 此外，r.GetUploadFiles方法的第二个参数支持随机自动命名上传文件。

这一段说明有错误，应该是Save方法的第二个参数才是选择是否自动命名，而不是GetUploadFiles方法

**Comment by gqcn** [comment]
@alienyan 感谢指正，已修改。
