### ISSUE TITLE
gdb对postgresql的支持问题

### ISSUE THREAD

**Issue by lijunfeng** [gogf/gf#64]
在那里设置数据库模式？默认是是public但是不能修改。

**Comment by johngcn** [comment]
@wenzi1 你清楚吗？

**Comment by lijunfeng** [comment]
我看你的代码里schema用于切换数据库了，postgresql中这个是指定模式的。

**Comment by johngcn** [comment]
@lijunfeng 这个和`Open`方法如何使用传递的参数有关系，需要研究下第三方`pg`引擎如何设置，你也可以看下`Open`那块的代码，欢迎提PR。我可能需要把手上的其他事情完成后再看这个。

**Comment by johngcn** [comment]
@lijunfeng 不知道你是否已解决，可以通过`linkinfo`配置来解决，若无问题我就关闭这个issue了

**Comment by lijunfeng** [comment]
只能类似这样 var results, _ = db.GetAll("SELECT * FROM qh_court_exposure_middleware.v_xww_fmy_zbaj LIMIT 10") 必须指定schema才行。

**Comment by johngcn** [comment]
@lijunfeng 好的，我终于明白你的意思了。这块需要在不同的数据库上增加方法支持数据库切换才行。`USE`方法在`pgsql`上不是切换数据库的操作：http://timmurphy.org/2009/11/17/use-schema_name-in-postgresql/

**Comment by johngcn** [comment]
@lijunfeng  该特性在`v1.8.0`已发布。
