### ISSUE TITLE
提个需求，能不能将orm中添加生成数据库表的操作。类似Django Orm

### ISSUE THREAD

**Issue by lx37506** [gogf/gf#644]

**Comment by lx37506** [comment]
这样对从python转过来的开发者会更友好一些

**Comment by gqcn** [comment]
@lx37506 你指的是`migrate`功能对吧？

**Comment by lx37506** [comment]
> @ lx37506你指的是`migrate`功能对吧？

是的，makemigraion和migrate功能。再请教一下已有的django项目的数据库是不是可以直接使用工具链生成数据库模型用Goframe重构呢？

**Comment by gqcn** [comment]
@lx37506 `gf cli`有自动根据数据库生成模型的命令，具体详见：https://github.com/gogf/gf-cli

**Comment by sanrentai** [comment]
@gqcn 目前gf cli 可以根据数据库生成模型，能否做到反过来呢，就是根据model生成 sql table
