### ISSUE TITLE
gcompress zip 同时压缩多个文件时生成目录

### ISSUE THREAD

**Issue by jetlwx** [gogf/gf#647]
### 1. What version of `Go` and system type/arch are you using?
go version go1.14.1 linux/amd64

### 2. What version of `GoFrame` are you using?
const VERSION = "v1.12.1"

### 3. Can this issue be reproduced with the latest release?
利用gcompress 压缩文件，源为同目录 的多个文件，但用zip命令解压缩时，会每个文件生成一个目录 
```go
//获取指定目录 带有关键字的文件列表
func (l *file) LogFiles(parentPath string, dirName string, keyword string) (list []string) {
	files, err := ioutil.ReadDir(parentPath + "/" + dirName)
	if err != nil {
		comm.Jlog.Error(err)
		return nil
	}
	for _, v := range files {
		if !v.IsDir() {
			if strings.Contains(v.Name(), keyword) {
				list = append(list, v.Name())
			}
		}
	}
	return list
}

//压缩文件
func (l *file) Logzip(filepaths []string, parentPath string, dirName string) (string, error) {
	hostName, err := os.Hostname()
	if err != nil {
		comm.Jlog.Error(err)
		return "", err
	}
	if err := os.Chdir(parentPath + "/" + dirName); err != nil {
		comm.Jlog.Error(err)
		return "", err
	}
	//storePath := parentPath + "/" + dirName + "/" + hostName + "_" + dirName + "_" + time.Now().Format("20060102150405") + ".zip"
	storePath := hostName + "_" + dirName + "_" + time.Now().Format("20060102150405") + ".zip"
	if err := gcompress.ZipPath(strings.Join(filepaths, ","), storePath); err != nil {
		comm.Jlog.Error(err)
		return "", err
	}

	return storePath, nil
}

```

**Comment by jetlwx** [comment]
[root@jet test]# zipinfo jet_idc-fang-esf_20200429172231.zip 
Archive:  jet_idc-fang-esf_20200429172231.zip
Zip file size: 380784444 bytes, number of entries: 8
-rw-r--r--  2.0 unx      202 bX stor 20-Apr-29 16:24 catalina_idc-fang-esf-559b48d685-kxctm.2020-04-28.log./catalina_idc-fang-esf-559b48d685-kxctm.2020-04-28.log
d---------  2.0 unx        0 bX stor 20-Apr-29 17:22 catalina_idc-fang-esf-559b48d685-kxctm.2020-04-28.log
-rw-r--r--  2.0 unx 258885261 bX stor 20-Apr-29 16:26 esf-info_idc-fang-esf-559b48d685-kxctm.log.2020-04-28./esf-info_idc-fang-esf-559b48d685-kxctm.log.2020-04-28
d---------  2.0 unx        0 bX stor 20-Apr-29 17:22 esf-info_idc-fang-esf-559b48d685-kxctm.log.2020-04-28
-rw-r--r--  2.0 unx 121883753 bX stor 20-Apr-29 16:24 idc-fang-esf-559b48d685-kxctm_localhost_access_log.2020-04-28.txt./idc-fang-esf-559b48d685-kxctm_localhost_access_log.2020-04-28.txt
d---------  2.0 unx        0 bX stor 20-Apr-29 17:22 idc-fang-esf-559b48d685-kxctm_localhost_access_log.2020-04-28.txt
-rw-r--r--  2.0 unx    12960 bX stor 20-Apr-29 16:24 localhost_idc-fang-esf-559b48d685-kxctm.2020-04-28.log./localhost_idc-fang-esf-559b48d685-kxctm.2020-04-28.log
d---------  2.0 unx        0 bX stor 20-Apr-29 17:22 localhost_idc-fang-esf-559b48d685-kxctm.2020-04-28.log
8 files, 380782176 bytes uncompressed, 380782176 bytes compressed:  0.0%

**Comment by gqcn** [comment]
@jetlwx 感谢反馈，已修复。
