### ISSUE TITLE
Recommendation on gf gen model

### ISSUE THREAD

**Issue by writethesky** [gogf/gf#649]
It is recommended to add a parameter that specifies the naming convention.
For example, the database field design specification USES underscore naming, and the API return json specification USES camel's hump naming. After this automatic entity generation, I need to manually modify the json rules for the struct. Is generated by the entity and model, the package name if an underscore, the editor will have been submitted to the yellow warning: "do not conform to the golang naming convention", although does not affect the use, is obsessive-compulsive disorder looks a bit uncomfortable

**Comment by gqcn** [comment]
@writethesky It will add name style configuration for tags in auto generated model codes.
