### ISSUE TITLE
Can you add web gzip function?

### ISSUE THREAD

**Issue by an94er** [gogf/gf#652]
As the say,add web gzip function,I do not want to nginx befrore the web server,thank you!

如题，能不能加上gzip压缩功能呢，我不想加个nginx在服务前面啦，否则用模板引擎出来的网页好多空行，对于seo有挺大问题的，谢谢了

**Comment by hailaz** [comment]
https://golang.org/pkg/compress/gzip
w.Header().Set("Content-Encoding", "gzip")
w.Header().Set("Vary", "Accept-Encoding")
