### ISSUE TITLE
Custom error 502

### ISSUE THREAD

**Issue by qq1196** [gogf/gf#654]
Go Version:  go1.14
GF Version:  v1.12.2
Centos7

404   output display   “404” 
That's right

502  output display   “Bad Gateway+502”
I think that's wrong 
Redundant output  “Bad Gateway”

```go
package main

import (
    "github.com/gogf/gf/frame/g"
    "github.com/gogf/gf/net/ghttp"
)

func main() {
    s := g.Server()
    s.BindStatusHandlerByMap(map[int]ghttp.HandlerFunc {
        404 : func(r *ghttp.Request){r.Response.Writeln("404")},
        502 : func(r *ghttp.Request){r.Response.Writeln("502")},
    })
    s.SetPort(8199)
    s.Run()
}
```

**Comment by gqcn** [comment]
@qq1196 Please use `r.Response.WriteOver("502")` instead. More details please refer to source codes.
