### ISSUE TITLE
自定义编译时内置变量获取不到

### ISSUE THREAD

**Issue by staberAi** [gogf/gf#655]
# 自定义编译时内置变量
[compiler.VarMap]
        author = "john"
        email  = "john@goframe.org"

 使用： gbuild 获取不到
        g.Dump(gbuild.Info())
	g.Dump(gbuild.Map())

**Comment by gqcn** [comment]
@staberAi 
> Package gbuild manages the build-in variables from "gf build".

`gbuild`模块仅当使用`gf build`编译时有效，并且是试验性特性，具体详见源码。

**Comment by lucianlv** [comment]
gf build编译后也获取不到
