### ISSUE TITLE
gres 中 Readdir() 参数为0时报错

### ISSUE THREAD

**Issue by LiuBo1975** [gogf/gf#658]
第三方库调用 gres 中 http.File 接口中的 Readdir() 报错。
根据接口定义：
`If n <= 0, Readdir returns all the FileInfo from the directory in a single slice. In this case, if Readdir succeeds (reads all the way to the end of the directory), it returns the slice and a nil error. If it encounters an error before the end of the directory, Readdir returns the FileInfo read until that point and a non-nil error.`
 
Readdir() 中的
`if count < 0 || count > len(files) `  应改为 `if count <= 0 || count > len(files) `

**Comment by gqcn** [comment]
@LiuBo1975 Thanks for your feedback. It is fixed in current `master` branch, and will be released in next release version.
