### ISSUE TITLE
go build main.go打包后自动删除build下的二进制文件

### ISSUE THREAD

**Issue by tianxia0079** [gogf/gf#659]
第一步打包二进制资源文件：
gf pack public,template boot/data.go --name boot
第二步打包可执行程序
gf build main.go    

希望第二步自动删除第一步生成的data.go。因为开发时候用不动了，而且每次手动删除，麻烦。
gf build 命令给个参数，可以删除data.go也可以。

**Comment by gqcn** [comment]
@tianxia0079 `build`只会做`build`的事情，你可以通过自建`Makefile`来解决。
