### ISSUE TITLE
SHOW FULL COLUMNS 执行性能问题

### ISSUE THREAD

**Issue by yongfly** [gogf/gf#662]
gf升级至1.12.2后，项目编译运行时，SQL日志中经常出现SHOW FULL COLUMNS FROM语句，该语句执行的频度较高，基本每次执行查询都会出现，有如下疑问请大神解惑：
1、频度过高肯定会影响系统执行性能，是否有开关可以关闭？
2、获取数据表的数据列信息一般都用于哪些方面，该功能对ORM处理的优势在哪里？

**Comment by gqcn** [comment]
@yongfly 你好，`SHOW FULL COLUMNS FROM`语句用于获取表结构，主要用于字段过滤，以及根据数据库字段类型将获取的结果字段值自动转换为Golang类型。该语句结果是带缓存的，只有第一次查询该表时会执行，后续不会再执行该语句。我不太清楚每次都执行该语句的原因是什么，你可以调试一下看看是否缓存没有起作用？

**Comment by yongfly** [comment]
经测试，该语句是缓存执行的，对系统性能影响可以忽略不计，谢复。
