### ISSUE TITLE
关于出现/dev/stdout报错问题

### ISSUE THREAD

**Issue by yongfly** [gogf/gf#663]
write /dev/stdout: input/output error
   1).  gochat/app/service/back.UserList
    	*/app/service/back/user.go:134
系统运行一段时间，经常会出现以上错误信息，然后系统不再接受请求。定位到user.go第134行发现，一般都是查询语句，如model.count()。分析问题应该是后端打印SQL语句时，出现写入错误，不能确定该问题是如何出现的。我的gf版本是1.12.2，升级前1.11一直没有出现过这个问题。

**Comment by gqcn** [comment]
@yongfly 你好，看错误似乎是输出到标准输出的时候报错的，像是一个系统错误。我没有遇到过该问题，且第一次收到该反馈，你可以自己研究下。

**Comment by sanrentai** [comment]
@yongfly 你是在用windows系统吗？我在把go程序转换成系统服务后出现过这个问题，所有的标准输出都会导致。

**Comment by yongfly** [comment]
@sanrentai 是部署在linux上的应用。记得gf1.11版本之前没有出现过这个问题，后来升级后这个问题就出现了。分析其原因，gf在做日志输出到stdout时，如果ssh登录的客户端或因为超时等原因断线后，gf程序输出到stdout好像就找不到这个ssh登录连接，因此出现stdout写入错误，gf程序会直接崩溃导致服务停止，目前这个问题一直存在。@gqcn

**Comment by gqcn** [comment]
@yongfly 你这个问题很奇怪，`v1.12`和`v1.11`在标准输出上没有改动，迄今为止所有的版本标准输出都是使用的`os.Stdout`，你看看是不是Golang版本有差别。此外，我可以在新版本上将标准数据的这个错误检测去掉，禁止`panic`影响业务处理。

**Comment by yongfly** [comment]
@gqcn 很有可能是Golang的问题，中间将Golang版本升级过一次。这个问题应该具有普遍性，有必要对os.Stdout的输出panic进行处理，避免影响业务服务。谢谢反馈，期待新版本改进！
