### ISSUE TITLE
数据库配置stdout输出问题

### ISSUE THREAD

**Issue by yongfly** [gogf/gf#664]
[database]
    debug = true
    [database.logger]
      level = "all"
      stdout = false
如上设置，当数据库debug设置为true时，即时此时stdout设置为false，但SQL仍然在stdout上输出。
如果将debug设置为false，此时日志记录文件却不记录SQLdebug日志信息。

**Comment by gqcn** [comment]
@yongfly 可能是你配置文件，你可以参考下以下配置：
```toml
[database]
    debug = true
    link  = "mysql:root:12345678@tcp(127.0.0.1:3306)/test?parseTime=true&loc=Local"
    [database.logger]
        level  = "all"
        stdout = false
```

**Comment by sanrentai** [comment]
配置文件
`[logger]
    path   = "./log/db" 
    level  = "all"
    stdout = false`
代码
`g.DB("default").SetLogger(g.Log("logger"))`
我是这样实现的

**Comment by yongfly** [comment]
以上问题一直存在，请关注：
当debug=true时，数据库SQL日志会直接输出到stdout，而不管stdout=false设置任何值。
@gqcn 我就是这样设置的，当debug=true时SQL日志会直接打印到stdout，而当debug=false时，数据库的SQL日志中却没有记录SQL日志信息。

**Comment by gqcn** [comment]
> 以上问题一直存在，请关注：
> 当debug=true时，数据库SQL日志会直接输出到stdout，而不管stdout=false设置任何值。
> @gqcn 我就是这样设置的，当debug=true时SQL日志会直接打印到stdout，而当debug=false时，数据库的SQL日志中却没有记录SQL日志信息。

我使用以下配置，`stdout=false`时不会输出到标准输出，使用的`gf`版本为`v1.13.1`：
```toml
[database]
    debug = true
    link  = "mysql:root:12345678@tcp(127.0.0.1:3306)/test?parseTime=true&loc=Local"
    [database.logger]
        level  = "all"
        stdout = false
```

**Comment by houseme** [comment]
https://github.com/gogf/gf/pull/1686
