### ISSUE TITLE
 gjson转换数据不对

### ISSUE THREAD

**Issue by wehnhew** [gogf/gf#665]
body := "{\"id\": 413231383385427875}"
	if dat, err := gjson.DecodeToJson(body); err == nil {
		fmt.Println(dat.MustToJsonString())
	}
上面输出是 {"id":413231383385427900}，跟源数据对不上，精度丢失了

**Comment by KISSMonX** [comment]
json 整数最大值是有限制的, 并不能到达 int64
想传这么大, 就转字符串吧.

**Comment by gqcn** [comment]
@wehnhew 其实标准库的`json`包里面`decoder`有个`UserNumber`方法可以将整型当做字符串处理，但是，转换为其他类型如`toml`, `yaml`的时候也会被当做字符串，所以当时是默认关闭了这个特性。需要再仔细研究一下。
![image](https://user-images.githubusercontent.com/26347176/81827723-a164d280-956b-11ea-9852-3a1c2f702695.png)

**Comment by wehnhew** [comment]
> json 整数最大值是有限制的, 并不能到达 int64
> 想传这么大, 就转字符串吧.
> 搜索一下相关的文档. 😸


> @wehnhew 其实标准库的`json`包里面`decoder`有个`UserNumber`方法可以将整型当做字符串处理，但是，转换为其他类型如`toml`, `yaml`的时候也会被当做字符串，所以当时是默认关闭了这个特性。需要再仔细研究一下。
> ![image](https://user-images.githubusercontent.com/26347176/81827723-a164d280-956b-11ea-9852-3a1c2f702695.png)


数据源不是我们的，改不了那个数据为字符串，只能用正则替换这么长的数字加个双引号吗？

**Comment by wehnhew** [comment]
@KISSMonX @gqcn 

数据源不是我们的，只能用正则替换这些超长的数字加个双引号再转成json结构体了吗？

**Comment by wnstar** [comment]
@gqcn 加一个参数开启的时候把大于int64的数值转为big.Int 怎么样
