### ISSUE TITLE
插件开发规范出来没有呀？我想基于goframe开发分享相关的插件

### ISSUE THREAD

**Issue by joyoes** [gogf/gf#666]
插件开发规范出来没有呀？我想基于goframe开发分享相关的插件，
比如命名规则，调用接口规范等等

**Comment by gqcn** [comment]
@joyoes 你好，目前`Plugin`特性还是一个实验性特性，只有一个接口定义，并且只有`Swagger`功能用到了，所以暂时还没有正式发布也还没文档。由于大部分功能特性通过中间件即可实现，插件机制类似于`Nginx`的`mod`功能，还不是很完善，优先级也不是很高，如果有应用实践来推动就不错，欢迎提建议和贡献。
