### ISSUE TITLE
打印日志采用滚动切分,切分的时候提示文件正在被使用,如何解决这个问题

### ISSUE THREAD

**Issue by chenarmy** [gogf/gf#667]
### 1. 您当前使用的`Go`版本，及系统版本、系统架构？

1.14

### 2. 您当前使用的`GoFrame`框架版本？

1.12.1

### 4. 问题描述？

Windows下开发,日志采用异步滚动切分
![输入图片说明](https://images.gitee.com/uploads/images/2020/0511/122026_45ceb14c_92380.png "屏幕截图.png")

![输入图片说明](https://images.gitee.com/uploads/images/2020/0511/122051_bd2215d3_92380.png "屏幕截图.png")

### 5. 您期望得到的结果？

按文件名进行切割日志文件

**Comment by gqcn** [comment]
@chenarmy 看样子windows下有这么个问题，需要研究一下。可能需要花点时间。

**Comment by hailaz** [comment]
本来想解决这个bug，但发现了一些问题
1.切分日志的检测时间与切分时间不兼容，例如设置切分时间为5分钟，结果每小时（默认检测时间）才检测一次是否需要切分。
2.切分日志功能目前读取日志文件修改时间，而不是读取日志文件的创建时间
3.（当前的bug就是在这产生的）切分日志功能目前是重命名当前文件到新文件，我认为应该把日志输出切换到新的文件
4.切分日志的命名样式，太长的数字影响阅读，应该适当加些标点符号

**Comment by gqcn** [comment]
@chenarmy 请更新使用最新版本，若问题继续请重提issue。
