### ISSUE TITLE
出现这个错误是什么原因啊?半天没整明白

### ISSUE THREAD

**Issue by joyoes** [gogf/gf#669]
![20200512](https://user-images.githubusercontent.com/16605854/81662533-4bf7cb00-9470-11ea-9736-eea97676ddf6.png)

**Comment by gqcn** [comment]
@joyoes 看你这截图我也没整明白。。😂

**Comment by KISSMonX** [comment]
这问题描述........￣□￣｜｜
无法 import gf , 写的明明白白. 
你得检查下是否 go.mod 没有设置, 或者没有  go get
