### ISSUE TITLE
中间件鉴权问题。

### ISSUE THREAD

**Issue by zuozhehao** [gogf/gf#676]
```golang
s := g.Server()

s.Group("/", func(group *ghttp.RouterGroup) {

    group.Middleware(middle.Auth)

}
```
使用以上测试，任意请求都经过鉴权。发现public 目录下文件还是可以直接访问。

**Comment by gqcn** [comment]
@zuozhehao The middleware is not executed during static file service. You may considering using HOOK feature instead: https://goframe.org/net/ghttp/router/hook . The HOOK feature hooks all requests to server including dynamic and static services.
