### ISSUE TITLE
gjson 不能直接转换为map [string]string

### ISSUE THREAD

**Issue by chenall** [gogf/gf#677]
json.ToStruct cannot convert to map[string]string

### 1. What version of `Go` and system type/arch are you using?
go version go1.13.4 windows/amd64

### 2. What version of `GoFrame` are you using?
v1.12.2

### 3. Can this issue be reproduced with the latest release?
yes

### 4. What did you do?

```
var jsondata = `
 {
   "title": {"l1":"标签1","l2":"标签2"}
}
`

func Test_json(t *testing.T) {
	t.Run("gjson test map[string]interface{}", func(t *testing.T) {
		json, err := gjson.LoadContent(jsondata)
		tx := struct {
			Title map[string]interface{}
		}{}
		err = json.ToStruct(&tx)
		gtest.Assert(err, nil)
		t.Log(tx)
	})

	t.Run("gjson_test map[string]string", func(t *testing.T) {
		json, err := gjson.LoadContent(jsondata)
		tx := struct {
			Title map[string]string
		}{}
		err = json.ToStruct(&tx)
		gtest.Assert(err, nil)
		t.Log(tx)
	})
}
```

### 5. What did you expect to see?

```
{
	"Title": {
		"l1": "标签1",
		"l2": "标签2"
	}
}
```
### 6. What did you see instead?
>cannot convert value "map[%!d(string=l1):%!d(string=标签1) %!d(string=l2):%!d(string=标签2)]" to type "map[string]string"

**Comment by gqcn** [comment]
@chenall 已改进，不过建议你使用`map[string]interface{}`

**Comment by chenall** [comment]
太有效率了,赞!

主要是因为在实际使用中, 这个已知是string类型的,想说直接使用map[string]string 会比较方便一些.
