### ISSUE TITLE
dl static file always break while progress reached around 53%

### ISSUE THREAD

**Issue by haobaojiang** [gogf/gf#678]
### 1. What version of `Go` and system type/arch are you using?

go version 1.11.13 windows/386

### 2. What version of `GoFrame` are you using?

1.12.3
### 3. Can this issue be reproduced with the latest release?
yes

### 4. What did you do?

- config.toml
```
[server]
	Address     = ":8199"
	ServerRoot  = "./patch"
	ServerAgent = "gf-app"
	LogPath     = "./log"
```
- file patch folder
```
99.zip  (41mb)
```
- go server side code
```
g.Server().Run()
```
- dl client : IE broshwer

### 5. What did you expect to see?

no error
### 6. What did you see instead?
dl request broken while progress around 57%

 [ERRO] read tcp 192.168.3.96:5634->x.x.x.x:8199: wsarecv: An existing connection was forcibly closed by the remote host.

**Comment by gqcn** [comment]
@haobaojiang Does the server reached `WriteTimeout`, that is `60s` in default: https://github.com/gogf/gf/blob/master/net/ghttp/ghttp_server_config.go#L243

**Comment by shen1l** [comment]
> @haobaojiang Does the server reached `WriteTimeout`, that is `60s` in default: https://github.com/gogf/gf/blob/master/net/ghttp/ghttp_server_config.go#L243

not  timeout. the network is fine.
I tried using windows IIS, it works fine . the below go stanrd library works as well.
```
 fs := http.FileServer(http.Dir("./static"))
  http.Handle("/", fs)

  log.Println("Listening on :3000...")
  err := http.ListenAndServe(":3000", nil)
  if err != nil {
    log.Fatal(err)
  }
```
the issue only comes with gf, plz try the below link, the link
http://121.201.102.80:8199/99.zip

**Comment by gqcn** [comment]
@shen1l @haobaojiang I think, your issues are all surely caused by `WriteTimeout`. Configure it with bigger one and have a try.

**Comment by haobaojiang** [comment]
works now ..thank you
