### ISSUE TITLE
gvalid验证规则问题

### ISSUE THREAD

**Issue by mushu1990** [gogf/gf#679]
1. What version of `GoFrame` are you using?
1.12.3

![image](https://user-images.githubusercontent.com/5515926/82300472-79e98c00-99e9-11ea-98dc-51bf36ddaf82.png)

使用checkmap方法不能验证json格式, 试了下interger规则也不能验证。

**Comment by gqcn** [comment]
@mushu1990 那是因为这个字段为非必须参数，空值表示没有传递，所以没有任何校验，当然是通过的。

**Comment by mushu1990** [comment]
(长宽2:1)
但是这样有非json值也是可以通过的

**Comment by qq380998880** [comment]
纯数字也被认为是正确的json,虽然不是常规json对象.如果你输入123,456就会报错应该.

**Comment by mushu1990** [comment]
> 纯数字也被认为是正确的json,虽然不是常规json对象.如果你输入123,456就会报错应该.

![image](https://user-images.githubusercontent.com/5515926/82525205-5fd3b900-9b63-11ea-9bc3-a5b6c7bb2a7d.png)
事实是不会报错的
