### ISSUE TITLE
无法删除服务端的调试输出信息

### ISSUE THREAD

**Issue by choose6** [gogf/gf#680]
### 1. What version of `Go` and system type/arch are you using?
go version go1.13.4 windows/amd64

### 2. What version of `GoFrame` are you using?
v1.12.3

### 4. What did you do?

我在配置文件中设置了
[server]
	LogStdout = false

在启动参数加了
gf.debug=false

依然无法屏蔽这条输出

### 5. What did you expect to see?

我想要去掉服务端启动后的第一条输出
2020-05-19 20:54:32.412 [DEBU] [ghttp] SetServerRoot path: xxxxx

**Comment by sanrentai** [comment]
`s := g.Server()
s.SetLogStdout(false)
s.Logger().SetStdoutPrint(false)`
