### ISSUE TITLE
Grouped routes are not binded to the `g.Server().Handler`

### ISSUE THREAD

**Issue by dustier** [gogf/gf#682]
### 1. What version of `Go` and system type/arch are you using?
`go version go1.14.1 windows/amd64`

### 2. What version of `GoFrame` are you using?
`goframe: v1.13.0`

### 3. Can this issue be reproduced with the latest release?
Yes.

### 4. What did you do and see and expect?
**Binding handler:**

```go
s := g.Server()
s.BindHandler("POST:/login", func(r *ghttp.Request) {
		r.Response.Write("login handler")
	})
s.Group("/", func(group *ghttp.RouterGroup) {
	group.GET("/test", func(r *ghttp.Request) {
		r.Response.Write("for authenticated handler testing")
	})
})
```
But the `routesMap` of `g.Server().Handler()` is:
```
$ fmt.Printf("%+v\n", g.Server().Handler())
$ output:
routesMap:map[%POST:/login@default:[{source:C:/Users/{Project Folder}/router/router.go:19 handler:0xc0000b0600}]]
```
It seems that the handler is not binded to the route `/test`.
Is it a bug or did I made mistakes above?

### 5. More information?
When I test the http server with `httptest` or [httpexpect](https://github.com/gavv/httpexpect), it seems to mock a running server with the handler(e.g. `httptest.NewServer(handler)` and `httpexpect.NewBinder(handler)`), and i cant get the `/test` route. While in the real world (with `g.Server().Run()`), server performs as expected.

**Comment by gqcn** [comment]
@dustier It uses lazy registering design for the group routes, that they're not really registered to server when route function of the group is called but is lazily registered when server starts. It is necessary for hierarchical group registering.

**Comment by dustier** [comment]
@gqcn So is there any way to register grouped routes manually? It's necessary for testing with both standard library `httptest` and `httpexpect` as mentioned.
谢谢回复
