### ISSUE TITLE
Cannot upload file on Linux

### ISSUE THREAD

**Issue by mingzaily** [gogf/gf#686]
### 1. What version of `Go` and system type/arch are you using?

go version go1.14.3 linux/amd64

### 2. What version of `GoFrame` are you using?

v1.12.3

### 3. Can this issue be reproduced with the latest release?

Yes

### 4. What did you do?

Use `ghttp` client to upload file `ghttp.post`, although it can be uploaded normally on Windows, it cannot be uploaded on Linux no matter using relative path or absolute path. The file is saved through `files.save`

### 5. What did you expect to see?

Normal uploads are also available on Linux

### 6. What did you see instead?

Normal uploads are also available on Linux

**Comment by gqcn** [comment]
@mingzaily It is OK in the unit testing cases, so please check your saved target directory path, and the returned error of function `Save`.

**Comment by mingzaily** [comment]
> @mingzaily It is OK in the unit testing cases, so please check your saved target directory path, and the returned error of function `Save`.

I'm pretty sure the path is right.
I mentioned this in the WeChat group, neither relative path nor absolute path.

**Comment by mingzaily** [comment]
> @mingzaily It is OK in the unit testing cases, so please check your saved target directory path, and the returned error of function `Save`.

Then I use the same path, through the [resty](https://github.com/go-resty/resty) encapsulated HTTP requests can be successful

**Comment by mingzaily** [comment]
> @mingzaily It is OK in the unit testing cases, so please check your saved target directory path, and the returned error of function `Save`.

There is no error in the file.save function

**Comment by gqcn** [comment]
@mingzaily Can you provide me the source codes that can reproduce the issue?

**Comment by mingzaily** [comment]
> @mingzaily Can you provide me the source codes that can reproduce the issue?

of course.
The first part is my code for using `GHTTP`
```golang
func SendXmlFile(gameId int, areaName string, filePath string) error {
	path := filepath.FromSlash(filePath)
	fmt.Println(path)
	data := g.Map{
		"gameName":    gameId,
		"area":        areaName,
		"file":        "@file:" + path,
		"contentType": "json",
	}
	if r, err := ghttp.Post(httpURL + "uploads", data); err != nil {
		panic(err)
	} else {
		defer r.Close()
		return response(r.Request.URL.String(), data, r.ReadAll())
	}
	return nil
}
```
The second part is my code for using `resty`
```golang
func SendXmlFile(gameId int, areaName string, filePath string) error {
	path := filepath.FromSlash(filePath)
	data := g.MapStrStr{
		"gameName":    strconv.Itoa(gameId),
		"area":        areaName,
		"contentType": "json",
	}
	if r, err := resty.New().R().SetFile("file", path).SetFormData(data).Post(httpURL + "uploads"); err != nil {
		panic(err)
	} else {
		return response(r.Request.URL, data, r, path)
	}
}
```
I guarantee that the `filepath` parameter is the same on both sides of the code

**Comment by gqcn** [comment]
@mingzaily What is your variable `path` looks like here when uploading failed?

![image](https://user-images.githubusercontent.com/26347176/83151847-ab6fff00-a12f-11ea-8083-c2f111e7a4e9.png)

**Comment by mingzaily** [comment]
> @mingzaily What is your variable `path` looks like here when uploading failed?
> 
> ![image](https://user-images.githubusercontent.com/26347176/83151847-ab6fff00-a12f-11ea-8083-c2f111e7a4e9.png)

`runtime/files/2020-05-27/test.xml`
I've also tried absolute paths `/data/golang/runtime/files/2020-05-27/test.xml`
absolute and relative paths can be successful on the windows system

**Comment by mingzaily** [comment]
> @mingzaily What is your variable `path` looks like here when uploading failed?
> 
> ![image](https://user-images.githubusercontent.com/26347176/83151847-ab6fff00-a12f-11ea-8083-c2f111e7a4e9.png)


I have seen the source code, if the path error will report an error `no such or file`

**Comment by gqcn** [comment]
@mingzaily I've tried your source codes, it goes OK.

**Comment by mingzaily** [comment]
@gqcn But it does exist, you can look at the WeChat group about my chat record, change a encapsulation can be, this is [my code](https://send.firefox.com/download/464b864e8f23cedb/#PQve6ZjkPjFo_JVN0wSNuQ)
