### ISSUE TITLE
视图怎么显示表单提交没有通过的错误信息

### ISSUE THREAD

**Issue by zhenhua1** [gogf/gf#688]
视图中怎么显示通过form表单提交的数据在服务端进行规则验证后没有通过的错误信息在视图中展示出来。就是有没有类似于beego的flash这种东西。表单验证错误的信息在视图中给显示出来

**Comment by gqcn** [comment]
@zhenhua1 表单校验会有`error`返回，你可以自己选择输出到返回内容中。

**Comment by zhenhua1** [comment]
> @zhenhua1 表单校验会有`error`返回，你可以自己选择输出到返回内容中。

这样也行，不知道咱们能否把这种验证错误的消息自动写入到视图中，比如laravel的Yii的他们的框架都有这种功能，看看咱们是否考虑把这种给迭代到下一个版本，这样会更方便。在视图中可以使用error,warning,success这类来接收显示出来

**Comment by gqcn** [comment]
> > @zhenhua1 表单校验会有`error`返回，你可以自己选择输出到返回内容中。
> 
> 这样也行，不知道咱们能否把这种验证错误的消息自动写入到视图中，比如laravel的Yii的他们的框架都有这种功能，看看咱们是否考虑把这种给迭代到下一个版本，这样会更方便。在视图中可以使用error,warning,success这类来接收显示出来

这个你可以自己封装一下，不算通用的功能。
