### ISSUE TITLE
gjson Set bug

### ISSUE THREAD

**Issue by touchboy** [gogf/gf#689]
j := gjson.New(nil)
	var dqmUserRoels []model.User
	db.Find(&dqmUserRoels)
	j.Set("data",dqmUserRoels)
	fmt.Println(j.ToJsonString())  //The output json will add an additional <nil>

	jsonStu, err := json.Marshal(dqmUserRoels)
	fmt.Println(string(jsonStu))  //The output is correct

**Comment by gqcn** [comment]
@touchboy Can you provide runnable codes that can reproduce the issue?
