### ISSUE TITLE
从redis里通过DoVar读取数据后进行类型转换不一致

### ISSUE THREAD

**Issue by arden** [gogf/gf#690]
```
func Test_GetPushStat(t *testing.T) {
    // 获取推送数
    pushTaskUserStatRedisKey := fmt.Sprintf("hdcj:admin:push_task:push_stat:%v", 24)
    println(pushTaskUserStatRedisKey)
    result, err := g.Redis("typush").DoVar("HGETALL", pushTaskUserStatRedisKey)
    if err == nil {
        pushSuccessCount := gconv.Uint(result.MapStrVar()["push_success_count"])
        pushErrorCount := gconv.Uint(result.MapStrVar()["push_error_count"])
        println(pushSuccessCount)
        println(pushErrorCount)

        pushSuccessCount = result.MapStrVar()["push_success_count"].Uint()
        pushErrorCount = result.MapStrVar()["push_error_count"].Uint()
        println(pushSuccessCount)
        println(pushErrorCount)
    }
}
```
gconv.Uint(result.MapStrVar()["push_success_count"])  和 result.MapStrVar()["push_success_count"].Uint() 取出来的值是不一样的，直接调用Uint()方法转出来的数据不正确，按理来说redis里存储的都是数字，转换出来也应该是正常的数字才符合逻辑。

**Comment by gqcn** [comment]
@arden Can you provide runnable codes that can reproduce the issue?

**Comment by arden** [comment]
@gqcn Test_GetPushStat method is test runnable codes.

**Comment by gqcn** [comment]
> @gqcn Test_GetPushStat method is test runnable codes.

能提供可复现该问题的最小化完整代码吗？

**Comment by arden** [comment]
可以直接创建一个gf的简单工程，连接一下Redis，创建一个hash key, 然后里面添加一个字段，值为整数，然后调用写个简单的测试用例，从redis里读取这个值，分别调用

**Comment by arden** [comment]
这两个从redis里获取值的方法，对比一下输出结果就会发现输出的数据是不一致的。

**Comment by gqcn** [comment]
@arden 感谢反馈，已经改进并提交到`master`分支，将会随着下一个版本发布。
