### ISSUE TITLE
Parse 转换 无法解析相关数据结构

### ISSUE THREAD

**Issue by zut** [gogf/gf#692]
```go
[][]uint
map[string]interface{}  //目前我遇到这两种 都无法解析
```
map 还是很常用的, 希望尽快增加.

![image](https://user-images.githubusercontent.com/65200714/83118720-50271800-a101-11ea-9e78-233d2ded131c.png)

相关文档: https://goframe.org/net/ghttp/request/struct

**Comment by gqcn** [comment]
@zut 我试了一下`map[string]interface{}`是支持的，而`[][]uint`这种不支持，不是常见类型，暂时支持的优先级不高。如果有朋友提供PR则最好。
