### ISSUE TITLE
基于RPC的开发是怎么实现的呀？

### ISSUE THREAD

**Issue by joyoes** [gogf/gf#693]
基于RPC的开发是怎么实现的呀？
我看了官网只有web方面的实例，缺少RPC的实例

**Comment by gqcn** [comment]
@joyoes 你好，`gf`本身可以用于`HTTP`接口的开发(包括`JsonRpc`)，但是例如常见的`gRPC`, `Thrift`等二进制通信协议要么本身有着完善的框架，要么有成熟的第三方封装框架，此时可以结合`gf`强大的模块功能来使用，其实并不冲突。
