### ISSUE TITLE
Parse不能校验int required

### ISSUE THREAD

**Issue by fulltimelove** [gogf/gf#699]
```
type ExampleQueryInput struct {
	Cid int    `v:"required#cid can not be empty"`
}
```
GetStruct 反射创建Stuct时会为其生成0值
```
if elem.Kind() == reflect.Ptr {
		if !elem.IsValid() || elem.IsNil() {
			e := reflect.New(elem.Type().Elem()).Elem()
			elem.Set(e.Addr())
			elem = e
		} else {
			...
	}
```
导致CheckStruct比较时   不能区分int类型是传入的0，还是int默认的0值
```
if required {
		return !(value == "")
	} else {
		return true
	}
```
value会为"0"

**Comment by gqcn** [comment]
@fulltimelove 你可以使用`min`规则
![image](https://user-images.githubusercontent.com/26347176/83513974-52c0ad80-a505-11ea-93f8-fcdc138de125.png)

**Comment by fulltimelove** [comment]
> @fulltimelove 你可以使用`min`规则
> ![image](https://user-images.githubusercontent.com/26347176/83513974-52c0ad80-a505-11ea-93f8-fcdc138de125.png)

可否在GetStruct和CheckStruct之间配合r.GetRequestMap来解决默认值required的问题?

**Comment by csrgxtu** [comment]
```golang
type searchStruct struct {
    PageNum   int    `p:"pageNum" v:"required|integer#pageNum is required|pageNum should be int"`
}
```
r.Parse 方法不能校验Int类型。

**Comment by gqcn** [comment]
> ```go
> `p:"pageNum" v:"required|integer#pageNum is required|pageNum should be int"`
> ```

当不能校验时，你提交的`pageNum`参数是什么？

**Comment by gqcn** [comment]
> > @fulltimelove 你可以使用`min`规则
> > ![image](https://user-images.githubusercontent.com/26347176/83513974-52c0ad80-a505-11ea-93f8-fcdc138de125.png)
> 
> 可否在GetStruct和CheckStruct之间配合r.GetRequestMap来解决默认值required的问题?

能否再具体描述一下？

**Comment by fulltimelove** [comment]
> > > @fulltimelove 你可以使用`min`规则
> > > ![image](https://user-images.githubusercontent.com/26347176/83513974-52c0ad80-a505-11ea-93f8-fcdc138de125.png)
> > 
> > 
> > 可否在GetStruct和CheckStruct之间配合r.GetRequestMap来解决默认值required的问题?
> 
> 能否再具体描述一下？

抽时间尝试了下，改动太大，暂时先放弃了
另外文档能否更新下，我看id-number验证规则已经改名resident-id...

**Comment by ticktap** [comment]
@gqcn 可否再加一个大于，小于的规则，min和max是大于或等于，小于或等于。

**Comment by gqcn** [comment]
> @gqcn 可否再加一个大于，小于的规则，min和max是小于或等于，大于或等于。

麻烦新提一个issue记录一下，和这个issue分开便于管理新功能进度。

**Comment by slemon** [comment]
最终中问题有什么解决方法吗？min解决不了问题，gin用 指正的方式来判断 int 默认值是0的问题

**Comment by gqcn** [comment]
@slemon @fulltimelove 你可以将属性改为指针类型则可使用`required`规则，同时`gf`框架也是非常非常强大滴支持指针类型属性转换的，例如:
```go
type ExampleQueryInput struct {
	Cid *int    `v:"required#cid can not be empty"`
}
```
