### ISSUE TITLE
数据库ORM中如果where包含两个 slise 的时候sql语句错误

### ISSUE THREAD

**Issue by laobu** [gogf/gf#701]
**1. 您当前使用的Go版本，及系统版本、系统架构？**
go v1.12 

**2. 您当前使用的GoFrame框架版本？**
gf v1.12.2

**3. 问题描述？**

orm链式操作

```
result, err := g.DB().Table("sys_organ").Where(g.Map{
				"id":g.Slice{3,4,5,6},
				"pid":pid,
				"status > -1":nil,
				"type":g.Slice{1,2},
		}).All()
```

得到的sql语句
SELECT * FROM `sys_organ` WHERE `id` IN(3,4,5,6,1) AND `pid`=1 AND `type` IN(2) AND status > -1

id 和 type in   的数据错误
`

**Comment by gqcn** [comment]
@laobu 感谢反馈，已经修复并提交到`master`分支，随着下一个版本发布。
