### ISSUE TITLE
parse方法好像不能解析指针字段，如*int，该怎么区分0和nil的区别？

### ISSUE THREAD

**Issue by ticktap** [gogf/gf#707]
```golang
type user struct {
	ID *int `json:"id"`
}
param := &user {}
	if err := r.Parse(param); err != nil {
		return err
	}
println(*param.ID)
```
报错：`runtime error: invalid memory address or nil pointer dereference`

把*int改为int是正常的解析的

**Comment by gqcn** [comment]
@ticktap 我使用`master`分支没有复现，要不你试试`master`分支。

**Comment by ticktap** [comment]
试了下，`Json`参数可以正确解析，`Query String`参数不能

**Comment by gqcn** [comment]
@ticktap 已改进，请尝试最新的`master`分支。
