### ISSUE TITLE
Domain name routing registration method

### ISSUE THREAD

**Issue by qq1196** [gogf/gf#708]
Whether to consider supporting pan domain name routing registration?

ackage main

import (
    "github.com/gogf/gf/frame/g"
    "github.com/gogf/gf/net/ghttp"
)

func main() {
    d := g.Server().Domain("*.a.com")
    d.BindHandler("/", func(r *ghttp.Request) {
        r.Response.Write("Hello World!")
    })
    g.Server().Run()
}

**Comment by gqcn** [comment]
@qq1196 你好，模糊域名支持会额外对性能有所损耗，并且这块的需求不高，因此暂未提上日程实现，感兴趣可以提PR。
