### ISSUE TITLE
郭神，能不能在框架里增加一个类似laravel的env模块

### ISSUE THREAD

**Issue by ayamzh** [gogf/gf#711]
写PHP的时候一直用的LARAVEL框架，laravel框架把配置文件中，需要区分环境的如db redis的配置拆到.env文件里管理
xxxx.config.php里通过env函数获取.env里的环境变量
'debug' => env('APP_DEBUG', false),
'db_host' => env('DB_HOST', ""),

.env里
APP_DEBUG=true
DB_HOST=127.0.0.1

config在版本库里维护，而env单独维护保证服务账号密码类配置的安全，且config里只维护和环境无关的配置像，和环境有关的通过env函数动态获取。

参考文档：[https://learnku.com/docs/laravel/5.7/configuration/2243#introduction](url)

**Comment by wwek** [comment]
https://github.com/gogf/gf/issues/347
和我提的一样 就是DotEnv支持

之前我抽时间弄了个pr，不过发现和模板引擎有冲突，单测没跑过
单测没过，加上实现我个人觉得不是很优雅，pr取消了
谁有时间完善下pr发出来审核

**Comment by mingzaily** [comment]
我也需要，config文件夹下放所有xxx.config.go，根目录下读取.env文件

**Comment by feng99** [comment]
https://goframe.org/pages/viewpage.action?pageId=7296348
看看这里的   根据环境变量 加载不同的配置文件
