### ISSUE TITLE
centos7部署二进制文件覆盖的问题

### ISSUE THREAD

**Issue by XWR940711** [gogf/gf#720]
gf build命令打包出来的二进制文件用rz -y命令替换服务器文件时提示失败,必须要执行rm命令将文件删除后再上传,执行命令nohub ./ &或者直接./ &运行都是无法替换的.想问下是什么原因造成的,有没有什么快捷的方式去处理.

**Comment by kuiye** [comment]
你是不在运行中啊

**Comment by XWR940711** [comment]
> @XWR940711 这个跟`gf`没关系，可能是你的文件权限问题吧。

用gf-cli init初始化一个项目.然后什么都不处理直接打包放服务器运行也是无法替换的.服务器是centos7.4

**Comment by XWR940711** [comment]
> 你是不在运行中啊

肯定是在运行的啊.不然怎么做到热重启/热更新.其实在运行的时候rm -rf掉二进制文件访问依然是正常的.这个问题的核心关键点在于不停机热更新.
