### ISSUE TITLE
事务处理支持

### ISSUE THREAD

**Issue by diluga** [gogf/gf#723]
有事务化处理的支持吗？比如要依次执行A和B，先执行A再执行B，只有A、B同时成功才能继续，其他情况会发生回滚。

**Comment by gqcn** [comment]
@diluga 你指的是ORM的Transaction吗？https://goframe.org/database/gdb/transaction

**Comment by diluga** [comment]
这个是数据库场景，我说的是比较通用的，比如一个新建资源操作，需要先建立数据库字段，之后调用其他系统API实现DNS记录创建(拿到返回值)，之后再将前面一步的内容更新到数据库中，这几个操作是依照顺序依次串行的，如果其中一个步骤失败，则回滚，或者调用回调函数(回收垃圾资源)。我是想看gf能否提供类似的一个调用框架或是方法接口的封装，这类的需求应该也是比较常见的。

**Comment by gqcn** [comment]
@diluga gf里面没有这样的，这种事务处理比较复杂，可能还会涉及到分布式事务处理、第三方服务组件的依赖，gf只是一个通用的基础开发框架。
