### ISSUE TITLE
发现一个gtcp有趣的bug 

### ISSUE THREAD

**Issue by tianxia0079** [gogf/gf#724]
例子：
官方的例子：https://goframe.org/net/gtcp/conn/index 使用示例2，回显服务
这样改动：
	c, err := gtcp.NewConn(DynamicIP+":"+gconv.String(util.Get_tcp_port()), 5*time.Second)
把超时时间设置为5s，首次链接如果服务器端不启动，超时5s重试。
如果链接成功后，吧服务器端断开，超时时间不生效， 好像超时时间参数无效了！

**Comment by tianxia0079** [comment]
我具体改后的代码如下：
第一次失败等了5s。重试时候，感觉没有等5s。疯狂报错链接失败，不是应该等5s再告诉失败吗？
```
start:
	// Client
	fmt.Println("DynamicIP " + DynamicIP)
	c, err := gtcp.NewConn(DynamicIP+":"+gconv.String(util.Get_tcp_port()), 5*time.Second)
	if err != nil {
		retry++
		g.Log().Line(true).Error("和服务器链接失败了", err)

		//重试告警
		if retry%retryMAX == 0 {
			fmt.Println("重试" + gconv.String(retry) + "次后失败请及时处理！")

		}
		goto start
	} else {
		connectOK = true
		retry = 0
		//链接成功通知 第一次也通知，重试后也通知
		g.Log().Line().Info("和动态公网端建立长连接成功!")
	}

```

**Comment by tianxia0079** [comment]
@gpcn
补充完成 服务器端和客户端代码如下：
https://gitee.com/dwxdfhx/yunAIYI_nginxUpdate/tree/master/app/service

**Comment by tianxia0079** [comment]
线上执行日志，有图有真相：
![image](https://user-images.githubusercontent.com/50256566/84585772-ad330580-ae45-11ea-8a50-1985a66f729f.png)

**Comment by gqcn** [comment]
@gqcn 连接服务端超时一般是网络问题引起的，例如防火墙，如果服务端已经关闭了连接客户端能够检测得到端口是否打开，那么就会立刻返回错误。从你截图的错误来看，服务端似乎已经关闭连接了，不会超时的。
