### ISSUE TITLE
Can gdb avoid SHOW FULL COLUMNS FROM TABLE command？？

### ISSUE THREAD

**Issue by chenghonour** [gogf/gf#726]
**Background: model.SetDebug(true)**

Found that every query will be executed: **SHOW FULL COLUMNS FROM TABLE**, this is executed for more than 160ms each time, can you avoid executing this command?

In addition, model.SetDebug(true) has been set. But execute "where" queries, such as model.Table("order").Where("no","1069"), the console does not print any SQL execution commands

**Comment by gqcn** [comment]
@chenghonour The `SHOW FULL COLUMNS FROM TABLE` runs just once to retrieve the table columns from database for each table, and its result will be cached into memory. The debugging sql information outputs to logging only before the sql is committed to database.
