### ISSUE TITLE
How to use gf swagger

### ISSUE THREAD

**Issue by yeshxm** [gogf/gf#731]
I have executed "gf swagger -o". But no files was built.
How to produce the swagger files?

**Comment by gqcn** [comment]
@yeshxm 
1. Please install the latest cli tool from: https://github.com/gogf/gf-cli
1. Use `gf swagger -h` to retrieve the help.

**Comment by yeshxm** [comment]
Thank you very much.

发送自 Windows 10 版邮件应用

发件人: John Guo
发送时间: 2020年6月15日 21:06
收件人: gogf/gf
抄送: yeshxm; Mention
主题: Re: [gogf/gf] How to use gf swagger (#731)

@yeshxm
1. Please install the latest cli tool from: https://github.com/gogf/gf-cli
2. Use gf swagger -h to retrieve the help.
