### ISSUE TITLE
gtcp 读写数据超时时间设置和疑似重大bug，请排查

### ISSUE THREAD

**Issue by tianxia0079** [gogf/gf#732]
有些场景下，读写超时超时需要及时发行，测试发现，现在 read  recv方法超时时间好像在10分钟左右。有点长。
希望可以支持设置timeout。

**Comment by tianxia0079** [comment]
我也不太理解为什么看到的是10分钟。有图有真相：
![image](https://user-images.githubusercontent.com/50256566/84585390-f6815600-ae41-11ea-9674-aa041e9b0190.png)

看报错，获取返回数据，等了10分钟多。

**Comment by tianxia0079** [comment]
// NewConnByNetConn creates and returns a TCP connection object with given net.Conn object.
func NewConnByNetConn(conn net.Conn) *Conn {
	return &Conn{
		Conn:           conn,
		reader:         bufio.NewReader(conn),
		recvDeadline:   time.Time{},
		sendDeadline:   time.Time{},
		recvBufferWait: gRECV_ALL_WAIT_TIMEOUT,
	}
}


看这段源码，读时间超时默认是1毫秒。真实情况下，阻塞了10多分钟。
希望排查下，是不是框架的bug。

**Comment by gqcn** [comment]
@tianxia0079 读取数据超时控制可以使用`RecvWithTimeout`方法。我刚重新`review`了一下代码没有发现`bug`，如果问题继续存在你可以提供复现该问题的最小完整可运行的代码我试试，以便高效发现问题解决问题。
