### ISSUE TITLE
在go-micro中, 如果不用g.server.run() 如何让router生效.

### ISSUE THREAD

**Issue by cuczhangyi** [gogf/gf#739]
### 1. What version of `Go` and system type/arch are you using?

go 1.14, windows

### 2. What version of `GoFrame` are you using?

gf v1.13.1

### 3. Can this issue be reproduced with the latest release?
yes

在使用go-micro的使用, 由于注册服务,不调用g.server.run, 所以通过routergroup 注册的方法都不能响应, 请问有什么好的办法解决吗?

func Prods(r *ghttp.Request){
	r.Response.Write(g.Map{
		"code":200,
		"data":ProdService.NewProdList(5),
	})
}

func main(){

	s := g.Server()
	s.Group("/v1", func(group *ghttp.RouterGroup) {
		group.ALL("/prods", Prods)
	})
	hlder := s.Handler()
	etcdReg := etcd.NewRegistry(
		registry.Addrs("127.0.0.1:2379"))
	server:= web.NewService(web.Address(":8001"),web.Handler(hlder),web.Registry(etcdReg),web.Name("产品服务 "))
	server.Run()

}

**Comment by gqcn** [comment]
@cuczhangyi You can use `s.Start()`. 😄

**Comment by cuczhangyi** [comment]
> @cuczhangyi You can use `s.Start()`. 😄

got it . thanks
