### ISSUE TITLE
在GF中怎么设置可以在客户端隐藏server等关键的信息

### ISSUE THREAD

**Issue by joyoes** [gogf/gf#740]
![QQ图片20200616150519](https://user-images.githubusercontent.com/16605854/84742464-0b491f80-afe3-11ea-894d-1b01800dc1c6.png)
如上图，在客户端的HTTP请求中能发现服务器使用的编程语言这些关键性的信息，我觉得在安全方面是非常危险的，要如何隐藏啊？另外还有哪些信息是可以隐藏的呀？

**Comment by gqcn** [comment]
@joyoes 你在配置文件中将`ServerAgent`设置为空即可，空的值不会设置到Header中，`GF`自动添加的Header信息仅此一个。
