### ISSUE TITLE
websocket如何做负载均衡

### ISSUE THREAD

**Issue by Eric-chy** [gogf/gf#743]
现在做那种类似于股票实时波动的app，用的websocket，现在用户量有点大，想多搞几台机器做下负载，现在有情况就是我要一台机器上的消息推送给所有客户端，这种情况下fd如何保存，如何推送其他机器保存的fd，比如我第一台机器维持了1万个连接，第二台维持了一万个，我现在第一台机器连接的某个用户发了一个红包，我要让第一台机器和第二台机器的所用用户都能抢这个红包，这种情况应该怎么推送消息？第一台机器怎么将消息推给第二台机器连接的用户？

**Comment by gqcn** [comment]
@Eric-chy 你这个不是属于框架层面的问题。不过我可以给你几个建议，一个是通过消息队列订阅/发布，一个是通过节点间广播通信。剩下自己研究一下哈。
