### ISSUE TITLE
提两个建议，关于数据校验（表单验证）

### ISSUE THREAD

**Issue by cos800** [gogf/gf#744]
看文档 https://goframe.org/util/gvalid/index 内置规则有个integer
但是平常校验一些id，page之类的参数，经常是需要大于0的正整数。

自定义错误，有没有可能像ThinkPHP那样
```go
params := map[string]interface{} {
    "passport"  : "",
    "password"  : "123456",
    "password2" : "1234567",
}
rules := map[string]string {
    "passport|帐号"  : "required|length:6,16",
    "password|密码"  : "required|length:6,16|same:password2",
    "password2|密码2" : "required|length:6,16",
}
if e := gvalid.CheckMap(params, rules); e != nil {
    fmt.Println(e.Maps())
}
```
输出错误时，把『passport 不能为空』替换成『帐号不能为空』
go语言还不太熟悉，大概是这个意思。

**Comment by arieslee** [comment]
可以自定义错误信息的 [https://goframe.org/util/gvalid/check](url)

**Comment by gqcn** [comment]
@cos800 可以通过自定义错误消息来实现，其实现在很多参数处理都是通过结构体的`tag`而不是`map`，因此`tp`那样的使用方式比较有局限性。
