### ISSUE TITLE
郭神，建议增加个事件机制

### ISSUE THREAD

**Issue by ayamzh** [gogf/gf#748]
也是参考laravel的event机制:https://learnku.com/docs/laravel/5.7/events/2280#manually-registering-events

在框架启动时注册event与listener
```php
/**
 * 应用程序的事件监听器映射。
 *
 * @var array
 */
protected $listen = [
    'App\Events\OrderShipped' => [
        'App\Listeners\SendShipmentNotification',
    ],
];
```
当事件触发时event(eventobj),会串行执行所有的listener。实现业务的解耦。类似观察者模式。
自己尝试搞了搞，对GO不太熟悉。实现的不太优雅。没法根据struct的完全限定名来实例化对象，只能绑定事件时就实例化struct。。希望老大能提供个更好的方案
```go
	// 事件容器
	app := base.NewApp()
	// 绑定事件
	app.Bind("*ev.MazhengEvent", new(listener.MazhengListener).Handle)
	app.Bind("*ev.MazhengEvent", new(listener.MazhengListener2).Handle)

	// 创建事件
	l := new(ev.MazhengEvent)
	l.Name = "xxxxx"

	//触发事件
	app.Fire(l)
```
..希望老大有更好的方案提供。

**Comment by cos800** [comment]
这个需求我支持！！！精神中支持

**Comment by gqcn** [comment]
@ayamzh 建议不错，可以提供独立的事件模块，例如`gevent`，结合`gmap`+`list`+`gqueue`来实现。`map`+`list`可以实现事件生产与消费注册，并且支持多端消费；`gqueue`可以实现基于内存的并发安全队列。此外，事件的过期机制可能需要好好考虑一下。
