### ISSUE TITLE
ORM的Count方法希望增加一个清除limit的功能

### ISSUE THREAD

**Issue by 804657038** [gogf/gf#750]
![图片](https://user-images.githubusercontent.com/23028100/85002580-a5e26380-b187-11ea-940d-d69fd4b439c7.png)
这样就能在查询完列表后很便捷的快速使用Count方法去获取总数来分页了

**Comment by gqcn** [comment]
@804657038 请参考链式操作安全章节：https://goframe.org/database/gdb/chaining/create
