### ISSUE TITLE
请问配置文件可以区分开发环境和正式环境吗？

### ISSUE THREAD

**Issue by siyue8899** [gogf/gf#751]
比如我有2个配置文件
config_dev.toml
config_pro.toml

使用 
```go
 g.Cfg().SetFileName("config_dev.toml") //运行在boot.go 里面也不行框架直接先去加载 config.toml 了
```
框架启动的时候默认直接读 config.toml  了。

怎么能区分呢。。。

**Comment by gqcn** [comment]
@siyue543241338 如果你想要把生产和配置的文件放到项目文件中管理，那么你可以将不同环境的配置文件使用不同的目录来存放，然后参考一下配置管理的目录修改章节：https://goframe.org/os/gcfg/index

**Comment by Eric-chy** [comment]
我是在config里面设置了
[env]
	app_status     = "dev"
然后在boot的init里
env := g.Cfg().GetMap("env")["app_status"].(string)
	g.Cfg().SetFileName("config." + env + ".toml")
然后你可以写config.dev.toml,   config.idc.toml,不同环境的时候把config里面的app_status改成对应的就行了

**Comment by boostbob** [comment]
mark

**Comment by siyue543241338** [comment]
> 我是在config里面设置了
> [env]
> app_status = "dev"
> 然后在boot的init里
> env := g.Cfg().GetMap("env")["app_status"].(string)
> g.Cfg().SetFileName("config." + env + ".toml")
> 然后你可以写config.dev.toml, config.idc.toml,不同环境的时候把config里面的app_status改成对应的就行了

...没折腾这玩意了,我直接用dockerfile 打包 自动部署到线上环境去跑了
