### ISSUE TITLE
建议系统panic增加对sentry的支持

### ISSUE THREAD

**Issue by mushu1990** [gogf/gf#753]
1. What version of `GoFrame` are you using?

go13.1

建议系统panic增加对sentry的支持。系统报错日志可以对接sentry。
github: https://github.com/getsentry/sentry-go
gin整合：https://docs.sentry.io/platforms/go/gin/

**Comment by gqcn** [comment]
@mushu1990 其实对接蛮简单的，如果只是想对接`http server`的`panic`，可以直接通过后置中间件检查`r.GetError()`即可，因为`gf`框架的`http server`已经优雅地捕获了`panic`。如果是想捕获整个进程的`panic`，将启动函数放到`sentry-go`的闭包方法中即可，内部猜测应该使用的是`panic-recover`实现捕获。

**Comment by mushu1990** [comment]
@gqcn 好的 感谢。我先试下。

**Comment by pingyeaa** [comment]
在中间件中加入以下代码就可以捕获了。
```go
func Sentry(r *ghttp.Request) {
	r.Middleware.Next()

	err := r.GetError()
	if err != nil {
		raven.CaptureMessage(gerror.Stack(err))
	}
}
```
