### ISSUE TITLE
gconv.int64()  is a big Bug!!!!!!

### ISSUE THREAD

**Issue by Charntent** [gogf/gf#762]
### 1. What version of `Go` and system type/arch are you using?
v1.11.7/Linux

### 2. What version of `GoFrame` are you using?
v1.11.7

### 3. Can this issue be reproduced with the latest release?

Yes

### 4. What did you do?
My Code :
	lessTime := gconv.Int64(cloudConfig.ConfigMap.Get("sysConfig.lessTime"))
   The Apollo Value sysConfig.lessTime = 600
    After gconv.Int64,The Value is 3158070,My God !

### 5. What did you expect to see?
Fix The Bug!!!!!!!!!!!!!!!!

### 6. What did you see instead?

I See The  gconv.Int64() Is A Big Bug!!!

**Comment by Charntent** [comment]
maybe    gmap function Set() is a bug
ConfigMap is a gmap 
ConfigMap.Set(k, v.NewValue)

v.NewValue is a apollo config

when I use lessTime := gconv.Int64(cloudConfig.ConfigMap.Get("sysConfig.lessTime"))

I get a error Result

**Comment by gqcn** [comment]
@Charntent Happy the Dragon Boat Festival! You shocked me with the amazing title. Can the issue be reproduced with the latest version of `gf`? Or could you provide the complete and shortest codes that can reproduce the issue you mentioned?
