### ISSUE TITLE
作者有没有基于GF实现微服务框架的计划呀？

### ISSUE THREAD

**Issue by misitebao** [gogf/gf#763]

**Comment by gqcn** [comment]
@misitebao Golang最大的使用场景是服务化接口场景，特别是微服务场景中。GF被设计为一款简单便捷通用化的框架，高性能模块化轻量级，主库提供的模块都是常用和核心的，没有过多的封装。在微服务化接口开发中可以结合GF一起使用，两者并不冲突，甚至可以把GF当做更实用化、接地气的Golang标准库扩展。

**Comment by misitebao** [comment]
感谢大佬的解答
