### ISSUE TITLE
admin/restart 平滑重启报错

### ISSUE THREAD

**Issue by mushu1990** [gogf/gf#764]
### 1. What version of `GoFrame` are you using?
1.13.1

`
 runtime error: index out of range [1] with length 1
   1).  github.com/gogf/gf/net/ghttp.forkReloadProcess
        D:/GoProject/go123/pkg/mod/github.com/gogf/gf@v1.13.1/net/ghttp/ghttp_server_admin_process.go:117
   2).  github.com/gogf/gf/net/ghttp.restartWebServers
        D:/GoProject/go123/pkg/mod/github.com/gogf/gf@v1.13.1/net/ghttp/ghttp_server_admin_process.go:199
   3).  github.com/gogf/gf/net/ghttp.RestartAllServer
        D:/GoProject/go123/pkg/mod/github.com/gogf/gf@v1.13.1/net/ghttp/ghttp_server_admin_process.go:59
   4).  github.com/gogf/gf/net/ghttp.(*utilAdmin).Restart
        D:/GoProject/go123/pkg/mod/github.com/gogf/gf@v1.13.1/net/ghttp/ghttp_server_admin.go:52
   5).  github.com/gogf/gf/net/ghttp.(*Middleware).Next.func1.6
        D:/GoProject/go123/pkg/mod/github.com/gogf/gf@v1.13.1/net/ghttp/ghttp_request_middleware.go:95
   6).  github.com/gogf/gf/net/ghttp.niceCallFunc
        D:/GoProject/go123/pkg/mod/github.com/gogf/gf@v1.13.1/net/ghttp/ghttp_func.go:75
   7).  github.com/gogf/gf/net/ghttp.(*Middleware).Next.func1
        D:/GoProject/go123/pkg/mod/github.com/gogf/gf@v1.13.1/net/ghttp/ghttp_request_middleware.go:94
   8).  github.com/gogf/gf/util/gutil.TryCatch
        D:/GoProject/go123/pkg/mod/github.com/gogf/gf@v1.13.1/util/gutil/gutil.go:26
   9).  github.com/gogf/gf/net/ghttp.(*Middleware).Next
        D:/GoProject/go123/pkg/mod/github.com/gogf/gf@v1.13.1/net/ghttp/ghttp_request_middleware.go:47
   10). github.com/gogf/gf/net/ghttp.(*Server).ServeHTTP
        D:/GoProject/go123/pkg/mod/github.com/gogf/gf@v1.13.1/net/ghttp/ghttp_server_handler.go:111
`

**Comment by gqcn** [comment]
@mushu1990 感谢谢反馈，已修复，请更新到最新的master分支再试试。

**Comment by cainiaoer** [comment]
新版只能重启一次，而且没什么效果，重启之前在控制器里的assigns内容调整了下，重启后模板里的对应内容没有变化，只是pid变了，第二次重启就一直提示server is restarting
gf版本：1.13.2

**Comment by cainiaoer** [comment]
> @mushu1990 感谢谢反馈，已修复，请更新到最新的master分支再试试。

新版只能重启一次，而且没什么效果，重启之前在控制器里的assigns内容调整了下，重启后模板里的对应内容没有变化，只是pid变了，第二次重启就一直提示server is restarting
gf版本：1.13.2

**Comment by skanger** [comment]
碰到了同样问题，没有效果

**Comment by gqcn** [comment]
@mushu1990 @cainiaoer @skanger 请通过`go get -u github.com/gogf/gf@master`使用最新的`master`分支代码再试试，经测试在`Mac`和`Linux`下是没有问题的，以下是测试代码：
```go
package main

import (
	"github.com/gogf/gf/frame/g"
)

func main() {
	s := g.Server()
	s.SetConfigWithMap(g.Map{"Graceful": true})
	s.EnableAdmin()
	s.SetPort(8199)
	s.Run()
}
```
需要注意的是，平滑重启不能使用`Goland`和`go run`命令运行，因为那样本身有一个无法控制的父进程。

**Comment by skanger** [comment]
已正常使用
