### ISSUE TITLE
日志能否提供下sentry

### ISSUE THREAD

**Issue by Eric-chy** [gogf/gf#766]
公司前端还有php都是用sentry记录异常日志，除了文件存储的方式，能否提供下sentry记录日志的方式，自己能接入sentry但是感觉肯定没有大神写的好，就是想能够在配置文件或者设置里选择日志驱动或者说日志记录方式，可以选择文件或者sentry之类的方式去记录

**Comment by gqcn** [comment]
@Eric-chy 自己实现下吧，`gf`不会提供对特定日志系统的封装，那样耦合会太高。
