### ISSUE TITLE
gxml 自定义类型 转换错误

### ISSUE THREAD

**Issue by chenall** [gogf/gf#771]
### 1. What version of `Go` and system type/arch are you using?

go version go1.13.4 windows/amd64

### 2. What version of `GoFrame` are you using?

v1.13.2-0.20200628152309-09eba58927fe

### 3. Can this issue be reproduced with the latest release?

yes

### 4. What did you do?

```
type Cdata string

func TestGxml(t *testing.T) {
	d := struct {
		T1 Cdata  `c:"server" json:"service"`
		T2 string `c:"test"`
	}{
		T1: "test1",
		T2: "test2",
	}

	gm := gconv.MapDeep(d)
	xmldata, err := gxml.Encode(gm, "xml")
	if err != nil {
		t.Fatal(err)
	}
	gtest.AssertEQ(xmldata, []byte("<xml><server>test1</server><test>test2</test></xml>"))
}
```

### 5. What did you expect to see?

```
<xml><server>test1</server><test>test2</test></xml>
```

### 6. What did you see instead?
```
<xml><Cdata>test1</Cdata></server><test>test2</test></xml>
```

**Comment by gqcn** [comment]
@chenall `gxml`基于的是`github.com/clbanning/mxj`，底层通过反射执行转换，你这个问题比较复杂，因为你给定的是一个自定义类型`Cdata`，底层反射机制无法识别如何转换，所以转换时会采用类型名称`Cdata`作为标签。你可以将`type Cdata string`调整为`type Cdata = string`别名的方式解决。此外，最后结果里面的`</server>`标签似乎是一个BUG，已经给`mxj`包提了issue：https://github.com/clbanning/mxj/issues/71

**Comment by chenall** [comment]
原本是打算使用自定义类型的 MarshalXML 方法来实现自定义xml转换发现转换错误.

那就等mxj包修正这个BUG了. 暂时先用其它方案解决下.

**Comment by gqcn** [comment]
@chenall 已经解决了，你更新最新的`master`分支再试试呢？

**Comment by chenall** [comment]
测试了最新版本,问题已经解决
