### ISSUE TITLE
orm事务操作 *gdb.TX 里面insert方法没有更新create_at, update_at等字段

### ISSUE THREAD

**Issue by ticktap** [gogf/gf#772]
```
db.Transaction(func(tx *gdb.TX) error {
    ...
    result, err := tx.Insert("user", user)
    ...
})
```
`create_at`, `update_at`的值为0000-00-00 00:00:00，可以顺便看看`delete_at`是否有效

**Comment by gqcn** [comment]
@ticktap 不好意思，文档忘了说明仅对链式操作下有效。

**Comment by ticktap** [comment]
好的，希望能在事务中添加此功能

**Comment by gqcn** [comment]
@ticktap 事务中通过`tx.Table(xxx).Insert(xxx)`操作即可。

**Comment by ticktap** [comment]
@gqcn 好的，感谢！

**Comment by Insua** [comment]
@gqcn 您好 能否自定义 时间字段，原系统的数据表是从laravel 迁移的，字段名是created_at updated_at

**Comment by gqcn** [comment]
@Insua 不支持，主要是为了统一约束名称方便维护，如果实在有必要可以单独提个issue跟踪。
