### ISSUE TITLE
自定义时间类型报错

### ISSUE THREAD

**Issue by ticktap** [gogf/gf#777]
```golang
type MyTime struct {
	time.Time
}
// 或者
type MyGTime struct {
	gtime.Time
}

type User struct {
    ServiceDate    MyTime `json:"service_date"`
}

user ：= &User{}
if err := g.DB().Table("user").Scan(&user); err != nil {
		...
}
```
请问能否通过自定义时间类型，覆盖`MarshalJson`方法来自定义时间格式？ 以上`MyTime `或者`MyGTime `，会报错：`slice element conversion failed: reflect.Value.Convert: value of type string cannot be converted to type model.MyTime`

**Comment by gqcn** [comment]
@ticktap 既然是这样，那么只有请出隐藏已久的大杀器了🔫，我一般不会轻易向人展示（忘了写文档）。
#### 1. 请先更新到最新的`master`分支，调整了一些细节
```
go get -u github.com/gogf/gf@master
```
#### 2. 使用`UnmarshalValue`接口，该接口需要开发者自定义类型的`Unmarshal`功能，性能非常非常非常高效，没有任何反射，用于`gconv`模块进行`Struct/Structs`转换，属于高级特性，关注性能不需要便捷性的时候可以考虑这个接口
```go
package main

import (
	"fmt"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/os/gtime"
	"github.com/gogf/gf/util/gconv"
	"time"
)

type MyTime struct {
	time.Time
}

type MyTimeSt struct {
	ServiceDate MyTime
}

func (st *MyTimeSt) UnmarshalValue(v interface{}) error {
	m := gconv.Map(v)
	t, err := gtime.StrToTime(gconv.String(m["ServiceDate"]))
	if err != nil {
		return err
	}
	st.ServiceDate = MyTime{t.Time}
	return nil
}

func main() {
	st := &MyTimeSt{}
	err := gconv.Struct(g.Map{"ServiceDate": "2020-10-10 12:00:01"}, st)
	fmt.Println(err)
	fmt.Println(st)
}
```

#### 3. 其实你自己定义的`MyTime`也可以实现`UnmarshalValue`接口
```go
package main

import (
	"fmt"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/os/gtime"
	"github.com/gogf/gf/util/gconv"
	"time"
)

type MyTime struct {
	time.Time
}

type MyTimeSt struct {
	ServiceDate MyTime
}

func (t *MyTime) UnmarshalValue(v interface{}) error {
	gt, err := gtime.StrToTime(gconv.String(v))
	if err != nil {
		return err
	}
	t.Time = gt.Time
	return nil
}

func main() {
	st := &MyTimeSt{}
	err := gconv.Struct(g.Map{"ServiceDate": "2020-10-10 12:00:01"}, st)
	fmt.Println(err)
	fmt.Println(st)
}
```

#### 4. 更多细节请自行品味

**Comment by ticktap** [comment]
@gqcn 很强大的功能，如果支持自定义类型，改写MarshalJson就更好了，主要是用来struct转json的。

**Comment by gqcn** [comment]
> @gqcn 很强大的功能，如果支持自定义类型，改写MarshalJson就更好了，主要是用来struct转json的。

`MarshalJson`是标准库自带的，用在标准库的`encoding/json`包中。

**Comment by ticktap** [comment]
@gqcn 问题是orm的`scan`方法不支持自定义的时间类型，
```golang
type MyTime struct {
	gtime.Time
}
```
会报错：`slice element conversion failed: reflect.Value.Convert: value of type string cannot be converted to type model.MyTime`

**Comment by gqcn** [comment]
@ticktap 你没有实现`UnmarshalValue`接口吧？我还特意写了一个单元测试你可以看看：https://github.com/gogf/gf/blob/8b7860941294d0f948ca98d31e447896771ada23/database/gdb/gdb_z_mysql_struct_test.go#L344

**Comment by ticktap** [comment]
@gqcn 好的，感谢解答
