### ISSUE TITLE
ORM框架增加AutoMigrate功能

### ISSUE THREAD

**Issue by sanrentai** [gogf/gf#779]
在go中定义struct 运行时自动修改数据库的表结构

在gorm框架中有该功能

希望GF也能提供。

**Comment by gqcn** [comment]
@sanrentai `migrate`功能其实有的小伙伴提过，`gf`的`orm`一直没有增加该功能，主要是考虑到：
1. 是通过代码生成数据表虽然对一两个人开发的项目比较方便，但是是一种不太严谨的做法，在团队开发中往往都是独立设计数据表，然后单向将数据表字段更新到开发语言的`class/struct`中。
1. 该功能需要复杂的`tag`定义，当项目逻辑比较复杂时不便于维护，不符合`gf`框架简便、轻量、强大、易维护的设计理念。

**Comment by botsphp** [comment]
我建议可以取个巧，写一个插件，将 gf 生成的表结构，映射一份到gorm 的模式定义中，通过 gorm 的功能来实现迁移。这样可以相互独立，实现也简单。

**Comment by sanrentai** [comment]
github.com/sanrentai/automigrate

目前实现了 mssql 的功能。

**Comment by botsphp** [comment]
@sanrentai 这样要迁移的东西太多了
