### ISSUE TITLE
gvalid  进行正则 check 的时候会去除字符串空格

### ISSUE THREAD

**Issue by jssyjam** [gogf/gf#781]
我有一个字符串需要判断是否为小写字符开头 regex:^[a-z]。以空格开头的字符也可以通过 gvalid  的 check 校验

**Comment by gqcn** [comment]
@jssyjam 请更新到最新的`master`代码再试试。

**Comment by jssyjam** [comment]
最新版本里，这个问题又回去了

ruleItems := strings.Split(strings.TrimSpace(rules), "|")
