### ISSUE TITLE
中间件能取得当前执行的结构体和方法吗？

### ISSUE THREAD

**Issue by lshfong** [gogf/gf#783]
s.Group("/", func(group *ghttp.RouterGroup) {
		group.Middleware(MiddlewareAuth)
		group.ALL("/{.struct}/{.method}", new(admin.User))
	})
func MiddlewareAuth(r *ghttp.Request) {
在这里怎么取得访问要执行的/{.struct}和{.method}，现在我是用url来切片，但是感觉不科学
	r.Middleware.Next()
}

**Comment by chenall** [comment]
使用r.Get方法就可以了

**Comment by gqcn** [comment]
@lshfong 哈哈，通过`r.URL.Path`来解析有何不可么。

**Comment by lshfong** [comment]
暂时还是用URL切片吧
