### ISSUE TITLE
mqtt

### ISSUE THREAD

**Issue by lx37506** [gogf/gf#784]
网络服务里面已经有了TCP UDP WebSocket等功能了，是不是可以再添加一个MQTT Broker呢？，现在非常多的场景是物联网相关的，并且阿里云的物联网平台对go并不友好，获取设备发布信息还要使用消息队列或者通道来获取。

**Comment by gqcn** [comment]
@lx37506 `gf`是一款很轻量的框架，只提供了一些非常基础且常用的模块，你的需求不是`gf`需要做的事情，不过欢迎你基于`gf`实现一个`mqtt`的实现封装包，可以作为`gf`的社区模块提供。
