### ISSUE TITLE
empty slice use in orm query

### ISSUE THREAD

**Issue by Insua** [gogf/gf#786]
When I use ```Where("id IN(?)", sliceWhere)``` to query, if sliceWhere is empty, It will appear strings: negative Repeat count.
So if empty slice can convert to ```0 = 1``` to make query false like other orm

gf version 1.31.1

**Comment by gqcn** [comment]
@Insua Thanks for your feedback. Please update your imported `gf` version to the latest codes of the master branch using `go get -u github.com/gogf/gf@master` and have another try.

**Comment by Insua** [comment]
Great!
