### ISSUE TITLE
配置文件由于带 BOM 导致异常

### ISSUE THREAD

**Issue by chenall** [gogf/gf#787]
### 1. What version of `Go` and system type/arch are you using?

go version go1.13.4 windows/amd64

### 2. What version of `GoFrame` are you using?

v1.13.2-0.20200708125356-0f6f571ccbc3

### 3. Can this issue be reproduced with the latest release?

yes

### 4. What did you do?

使用Windows的记事本修改配置文件会自动在文件头添加 UTF-8 BOM,修改完就会启动失败.

重现方法
修改config.toml的文件编码,改为UTF-8 WITH BOM,再次启动就会报错.

目前我的解决方法

修改 encoding\gjson\gjson_api_new_load.go文件
在LoadContent 函数的return语句之前添加如下代码,过滤掉BOM编码.

```
	if content[0] == 0XEF && content[1] == 0xBB && content[2] == 0xBF {
		content=content[3:]
	}
```

不知这个方法是否优雅,有没有其它更好的方案.

PS: 英文不好就不发PR了.

**Comment by gqcn** [comment]
@chenall 你这个问题还挺难遇到的，编码不规范，码农两行泪，windows 记事本是原罪，欢迎感兴趣的小伙伴提供PR。

**Comment by chenall** [comment]
我目前主要使用的是Windows系统,
平常使用NOTEPAD2或NOTEPAD++修改配置,没有发现问题.
偶然间直接使用记事本打开修改了一下,竟然报错了..

**Comment by sanrentai** [comment]
我遇到过同样的问题，项目在本地运行一切正常，到服务器上就闪退，当时这个问题查了1上午

**Comment by gqcn** [comment]
@chenall @sanrentai 要不你们谁来提供一个PR吧，注意也要增加单元测试。
