### ISSUE TITLE
GoFrame平滑重启的问题

### ISSUE THREAD

**Issue by lijunfeng** [gogf/gf#788]
`APP_PATH`/config/config.toml

```toml
[server]
    Graceful    = "true"
```

`APP_PATH`/main.go
```go
func main() {
	ghttp.SetGraceful(true)
        g.Server().Run()
}
```

![image](https://user-images.githubusercontent.com/3746302/87136289-e425fb00-c2cd-11ea-8568-27cfd67af56c.png)

测试http://127.0.0.1:8199/debug/admin/restart时输出server is restarting
排查一直在
![image](https://user-images.githubusercontent.com/3746302/87136543-3c5cfd00-c2ce-11ea-8017-5b2dc8424eda.png)

一开始以为是MACOS的问题，放到CENTOS7下也是这个问题，请教一下这是什么问题？那位给指点一下。

**Comment by gqcn** [comment]
@lijunfeng 其实这个问题和这个`graceful`的配置没什么关系，`graceful`的配置只是用于配置是否打开本地的`10000`来进行平滑重启，其实默认信号量是开启的，也是可以实现平滑重启。请使用`go run`命令来运行你的程序，不要通过`Goland`运行，因为`Goland`本身也带了子父进程的控制，会有影响。
