### ISSUE TITLE
config.toml使用logger.Flags为什么报错呢

### ISSUE THREAD

**Issue by lshfong** [gogf/gf#789]
[logger]
        Path   = "./log"
        Level  = "all"
        Stdout = true 
        Flags=log.LstdFlags  
报错：
(last key parsed 'logger.Flags'): expected value but found "log" instead
但是我在main中使用SetFlags是正常的

**Comment by gqcn** [comment]
@lshfong It does not support flags configuration in file. Duplicated issue with https://github.com/gogf/gf/issues/684 .

**Comment by lshfong** [comment]
Know the
