### ISSUE TITLE
怎么区别生产环境还是开发环境

### ISSUE THREAD

**Issue by 986244073** [gogf/gf#790]
怎么区别生产环境还是开发环境?
gf run main.go 的时候 可以加上dev 或者 prod 区别生产环境还是开发环境呢

**Comment by gqcn** [comment]
@986244073 其实有个`gmode`模块，只是没有写文档，你可以通过手动、环境变量、启动参数来设置当前的环境状态，除了默认提供了4种常见环境的常量以及方法设置，开发者可自定义环境名称，感兴趣可以看最新的`master`代码中的`gmode`包源码。

**Comment by chenall** [comment]
测试了一下,不增加额外配置的情况下,如果在本机永远是 DEVELOP 

因为gdebug.CallerFilePath 总是存在,

样子的话这个gmode,还需要手动设置才靠普.  我目前是使用 tag来判断.

**Comment by gqcn** [comment]
> 测试了一下,不增加额外配置的情况下,如果在本机永远是 DEVELOP
> 
> 因为gdebug.CallerFilePath 总是存在,
> 
> 样子的话这个gmode,还需要手动设置才靠普. 我目前是使用 tag来判断.

你可以通过环境变量或者启动参数来设置当前运行环境，具体参考下源代码，目前这块没文档的，感兴趣的话下个版本的加上文档说明。
