### ISSUE TITLE
gf v1.13.1 orm func FindOne and One not used limit

### ISSUE THREAD

**Issue by gionna** [gogf/gf#794]
```go
// One retrieves one record from table and returns the result as map type.
// It returns nil if there's no record retrieved with the given conditions from table.
//
// The optional parameter <where> is the same as the parameter of Model.Where function,
// see Model.Where.
func (m *Model) One(where ...interface{}) (Record, error) {
	if len(where) > 0 {
		return m.Where(where[0], where[1:]...).One()
	}
	all, err := m.All()
	if err != nil {
		return nil, err
	}
	if len(all) > 0 {
		return all[0], nil
	}
	return nil, nil
}
```

**Comment by gqcn** [comment]
@gionna Thanks for your feedback. It's now fixe, improved and committed to the master branch. Please pull the latest master branch and have another try.

**Comment by gionna** [comment]
@gqcn then go run main 
panic: empty database configuration

goroutine 1 [running]:
github.com/gogf/gf/frame/gins.Database.func1(0xe9a3e0, 0xc0001d75c0)
	/opt/gopath/pkg/mod/github.com/gogf/gf@v1.13.2-0.20200715011503-183f631190fb/frame/gins/gins_database.go:98 +0xc2a
github.com/gogf/gf/container/gmap.(*StrAnyMap).doSetWithLockCheck(0xc0001a3660, 0xc0000b2150, 0x22, 0xe3acc0, 0xc0001d7620, 0x0, 0x0)
	/opt/gopath/pkg/mod/github.com/gogf/gf@v1.13.2-0.20200715011503-183f631190fb/container/gmap/gmap_hash_str_any_map.go:217 +0x185
github.com/gogf/gf/container/gmap.(*StrAnyMap).GetOrSetFuncLock(0xc0001a3660, 0xc0000b2150, 0x22, 0xc0001d7620, 0x2, 0xc0000b2150)
	/opt/gopath/pkg/mod/github.com/gogf/gf@v1.13.2-0.20200715011503-183f631190fb/container/gmap/gmap_hash_str_any_map.go:254 +0xa0
github.com/gogf/gf/frame/gins.Database(0xc0001a3680, 0x1, 0x1, 0x445401, 0xc0001a3680)
	/opt/gopath/pkg/mod/github.com/gogf/gf@v1.13.2-0.20200715011503-183f631190fb/frame/gins/gins_database.go:33 +0x177
github.com/gogf/gf/frame/g.DB(0xc0001a3680, 0x1, 0x1, 0x188cfc0, 0xc0000a0000)
	/opt/gopath/pkg/mod/github.com/gogf/gf@v1.13.2-0.20200715011503-183f631190fb/frame/g/g_object.go:91 +0x3f
cashier/app/model/advert_push.init()
	/data/www/go/cashier/app/model/advert_push/advert_push_model.go:24 +0x63
exit status 2

**Comment by gqcn** [comment]
@gionna Sorry, an unexpected bug when changing codes, it's now fixed. Please pull the latest master branch codes.

**Comment by gionna** [comment]
@gqcn  Thinks
