### ISSUE TITLE
str.SnakeCase 处理 md5 这样的字段时，会出现 "md_5"

### ISSUE THREAD

**Issue by botsphp** [gogf/gf#795]
建议改成 md5

**Comment by gqcn** [comment]
@botsphp https://stackoverflow.com/questions/58009622/whats-the-correct-way-to-treat-numbers-in-snake-case

**Comment by botsphp** [comment]
大家可以讨论下

https://stackoverflow.com/questions/1175208/elegant-python-function-to-convert-camelcase-to-snake-case
https://github.com/go-gorm/gorm/issues/1093

我也找了些文档，目前看大家遵循的还是 Md5 => 'md5'

**Comment by gqcn** [comment]
@botsphp 嗯，好像没有统一的标准，你可以看看能不能直接给`gf`提供PR。

**Comment by botsphp** [comment]
我自己做了一个简单的修改，但我改的是 gf-cli，因为 gstr 是仓库的包，我担心改动引起不兼容的情况。

我的 pr 在https://github.com/gogf/gf-cli/pull/42

**Comment by gqcn** [comment]
@botsphp 你可以给主库提pr啊，加个方法比如`SnakeNumCase`之类的。

**Comment by botsphp** [comment]
> @botsphp 你可以给主库提pr啊，加个方法比如`SnakeNumCase`之类的。

ok，没问题，今天我整理一下现有的标准，提一个 pr

**Comment by botsphp** [comment]
https://github.com/gogf/gf/pull/815
