### ISSUE TITLE
关于gcfg动态修改配置文件的需求

### ISSUE THREAD

**Issue by Jerry-fmcheng** [gogf/gf#796]
1、版本：
go version 1.11.4
gf version  1.13.1
2、需求描述：
需要支持配置中心下发配置参数，配置参数需要持久化（动态修改）到配置文件中保存，否则服务重启之后仍然是老的配置信息；
另外，期望gcfg支持修改某一个或者某几个配置项，其他的配置项不会丢失。

**Comment by gqcn** [comment]
@gqcn 请更新最新的`master`分支代码，已增加`Set`方法可动态修改配置对象中指定路径的配置。

**Comment by Jerry-fmcheng** [comment]
今天早晨更新了master测试，发现在启动服务的时候frame发生了panic: empty database configuration，堆栈如下：
goroutine 1 [running]:
vendor/github.com/gogf/gf/frame/gins.Database.func1(0xb1dc80, 0xc0002312f0)
	D:/gf-icc/src/vendor/github.com/gogf/gf/frame/gins/gins_database.go:98 +0xc20
vendor/github.com/gogf/gf/container/gmap.(*StrAnyMap).doSetWithLockCheck(0xc0001f55b0, 0xc0002b26f0, 0x22, 0xaed900, 0xc00024c450, 0x0, 0x0)
	D:/gf-icc/src/vendor/github.com/gogf/gf/container/gmap/gmap_hash_str_any_map.go:217 +0x1b7
vendor/github.com/gogf/gf/container/gmap.(*StrAnyMap).GetOrSetFuncLock(0xc0001f55b0, 0xc0002b26f0, 0x22, 0xc00024c450, 0x2, 0xc0002b26f0)
	D:/gf-icc/src/vendor/github.com/gogf/gf/container/gmap/gmap_hash_str_any_map.go:254 +0xa7
vendor/github.com/gogf/gf/frame/gins.Database(0xc000250100, 0x1, 0x1, 0x1296801, 0xc000250100)
	D:/gf-icc/src/vendor/github.com/gogf/gf/frame/gins/gins_database.go:33 +0x17e
vendor/github.com/gogf/gf/frame/g.DB(0xc000250100, 0x1, 0x1, 0x11b1980, 0x9d612f16e8604332)
	D:/gf-icc/src/vendor/github.com/gogf/gf/frame/g/g_object.go:91 +0x46

**Comment by Jerry-fmcheng** [comment]
定位了下，如果是gins.Database做了如下修改：
 		// It firstly searches the configuration of the instance name.
 		nodeKey, _ := gutil.MapPossibleItemByKey(Config().GetMap("."), gVIEWER_NODE_NAME)
 		if nodeKey == "" {
 			nodeKey = gDATABASE_NODE_NAME
 		}
 		if len(m) == 0 {
 		if m = Config().GetMap(nodeKey); len(m) == 0 {
 			panic(fmt.Sprintf(`database init failed: "%s" node not found, is config file or configuration missing?`, gDATABASE_NODE_NAME))
 		}
请问这里为什么要和viewer绑定？优先将database的配置项放到viewer里面去？

**Comment by gqcn** [comment]
> ```go
> i
> ```

这是新版本改动的一个bug，已修复，请更新到最新的`master`再试试。
