### ISSUE TITLE
github.com/gogf/gf/os/gfcache  page 404

### ISSUE THREAD

**Issue by shoaly** [gogf/gf#799]
### 1. What version of `Go` and system type/arch are you using?

go version go1.12.5 windows/amd64

### 2. What version of `GoFrame` are you using?

 GF v1.13.2

### 3. Can this issue be reproduced with the latest release?
yes, when i visit https://github.com/gogf/gf/os/gcache, page 404

**Comment by shoaly** [comment]
package main

import (
    "github.com/gogf/gf/frame/g"
    "github.com/gogf/gf/net/ghttp"
)

func main() {
    s := g.Server()
    s.BindHandler("/", func(r *ghttp.Request) {
        r.Response.Write("哈喽世界！")
    })
    s.Run()
}

when i try this demo, and run 
go get github.com/gogf/gf/frame/g
go get github.com/gogf/gf/net/ghttp

prompt : 
package github.com/gogf/gf/os/gfcache: cannot find package "github.com/gogf/gf/os/gfcache" in any of: ...

**Comment by shoaly** [comment]
已经解决, 换成go mod模式之后 就可以正常的依赖了....怪怪的

**Comment by gqcn** [comment]
@shoaly The functions of package `gfcache` are moved to package `gfile`, and the `gfcache` is removed in new version of `gf`. Use the latest version of `gf` and it all goes well.
