### ISSUE TITLE
mysql链式查询跨库关联在调用TableFields时报错

### ISSUE THREAD

**Issue by Jerry-fmcheng** [gogf/gf#804]
1、版本：
go version 1.11.4
gf version 1.13.1

2、问题描述：
在进行跨数据库查询时，调用gdb.Model.All->...->TableFields是报错，原因是过程中传递的表名，程序将.前面的数据库名删除掉了，比如一开始表名为phoenix_alarm.alarm_resource，直接传递给TableFields函数的表名是alarm_resource
这样一来，TableFields直接在本数据库中SHOW FULL COLUMNS FROM `alarm_resource`，但是找不到该表就报错了。
但是，尽管报错，后面的查询结果还是可以正常查出来。

希望大佬能优化一下，就是跨库查询，传递给TableFields的表名要带上传递的数据库名。

调用的堆栈如下：
Error: Error 1146: Table 'datacenter.alarm_resource' doesn't exist 
Stack:
1.  vendor/github.com/gogf/gf/database/gdb.(*Core).writeSqlToLogger
    D:/gf-icc/src/vendor/github.com/gogf/gf/database/gdb/gdb_core.go:776
2.  vendor/github.com/gogf/gf/database/gdb.(*Core).DoQuery
    D:/gf-icc/src/vendor/github.com/gogf/gf/database/gdb/gdb_core.go:63
3.  vendor/github.com/gogf/gf/database/gdb.(*Core).DoGetAll
    D:/gf-icc/src/vendor/github.com/gogf/gf/database/gdb/gdb_core.go:158
4.  vendor/github.com/gogf/gf/database/gdb.(*DriverMysql).TableFields.func1
    D:/gf-icc/src/vendor/github.com/gogf/gf/database/gdb/gdb_driver_mysql.go:114
5.  vendor/github.com/gogf/gf/os/gcache.(*memCache).GetOrSetFunc
    D:/gf-icc/src/vendor/github.com/gogf/gf/os/gcache/gcache_mem_cache.go:250
6.  vendor/github.com/gogf/gf/database/gdb.(*DriverMysql).TableFields
    D:/gf-icc/src/vendor/github.com/gogf/gf/database/gdb/gdb_driver_mysql.go:105
7.  vendor/github.com/gogf/gf/database/gdb.(*Model).getSoftFieldName
    D:/gf-icc/src/vendor/github.com/gogf/gf/database/gdb/gdb_model_time.go:65
8.  vendor/github.com/gogf/gf/database/gdb.(*Model).getSoftFieldNameDelete
    D:/gf-icc/src/vendor/github.com/gogf/gf/database/gdb/gdb_model_time.go:60
9.  vendor/github.com/gogf/gf/database/gdb.(*Model).getConditionOfTableStringForSoftDeleting
    D:/gf-icc/src/vendor/github.com/gogf/gf/database/gdb/gdb_model_time.go:125
10. vendor/github.com/gogf/gf/database/gdb.(*Model).getConditionForSoftDeleting
    D:/gf-icc/src/vendor/github.com/gogf/gf/database/gdb/gdb_model_time.go:92
11. vendor/github.com/gogf/gf/database/gdb.(*Model).All
    D:/gf-icc/src/vendor/github.com/gogf/gf/database/gdb/gdb_model_select.go:34
12. app/model/dc_channel_base.(*arModel).All

**Comment by Jerry-fmcheng** [comment]
请问这个有进展吗？

**Comment by Jerry-fmcheng** [comment]
要修改的代码应该在如下这个位置，但是我不太确定这里为啥要根据.分割，然后去掉前面的数据库名？如果我删除掉这个逻辑会不会引入什么问题？
`// getConditionOfTableStringForSoftDeleting does something as its name describes.
func (m *Model) getConditionOfTableStringForSoftDeleting(s string) string {
	var (
		field  = ""
		table  = ""
		array1 = gstr.SplitAndTrim(s, " ")
		**array2 = gstr.SplitAndTrim(array1[0], ".")**
	)
	if len(array2) >= 2 {
		table = array2[1]
	} else {
		table = array2[0]
	}
	field = m.getSoftFieldNameDelete(table)
//...
}`

**Comment by Jerry-fmcheng** [comment]
很遗憾，中午直接验证了一把SQL，发现SHOW FULL COLUMNS FROM语句后面并不支持携带数据库名，如下：
[SQL] SHOW FULL COLUMNS FROM `phoenix_alarm.alarm_policy_rules`
[Err] 1146 - Table 'phoenix_alarm.phoenix_alarm.alarm_policy_rules' doesn't exist

所以这个应该就是作者为啥在调用这个sql之前要去掉数据库名的原因了吧。所以这个问题修改感觉有点麻烦，要先切换到对应的库执行才可以，即最终构造的SQL如下，才能正常执行：
USE phoenix_alarm;SHOW FULL COLUMNS FROM `alarm_policy_rules`

**Comment by gqcn** [comment]
@Jerry-fmcheng 你好，这个并不是目前最高优先级的工作，排期在处理。
