### ISSUE TITLE
建议: 数据库参数参数支持:var占位符

### ISSUE THREAD

**Issue by chenall** [gogf/gf#811]
目前数据库的参数使用"?"作为占位符.

大部份情况下够用了,但是在一些特殊的情况下就比较麻烦.

希望 可以支持使用":var"作为占为符.

用":Var"会比较直观,使用map方式作为参数,不必考虑参数位置的问题,达到类似如下的效果

```go
args := g.Map{":id":1,":name":"name",":date":"20200721"}
GetAll("select * from tab where id=:id and name=:name",args)
GetAll("select * from tab1 where sid=:id d=:date",args)
```

**Comment by gqcn** [comment]
@chenall 好的，进入排期吧。

**Comment by chenall** [comment]
感谢,就等排上之后再做一些测试.

**Comment by gqcn** [comment]
@chenall 如果你能直接提供PR当然更好，不过这个涉及到的gdb底层细节可能比较繁琐。

**Comment by sanrentai** [comment]
其实加了以后，也是转换成 ？，？，？  进行处理

**Comment by gqcn** [comment]
@sanrentai 嗯，内部其实应该也会自动化转换为`?`占位符号，只是开发者无感知了。

**Comment by chenall** [comment]
是最终还是要转化成 ?，？没错

只是个人觉得用:var占位符对开发者比较友好，而且直观。

另外还有个优点，用:var占位符可以不用像?，?那样参数数量需要匹配。

比如ps 用手机敲的就用个伪代码，大致如下 有两个地方需要的参数是一样的。
select * from tab where id=:id and sid=:id
用?必须需要写两个参数。
