### ISSUE TITLE
gredis support tls

### ISSUE THREAD

**Issue by xbkaishui** [gogf/gf#813]
### 1. What version of `Go` and system type/arch are you using?
go version go1.14.4 darwin/amd64

### 2. What version of `GoFrame` are you using?

v1.13.1

### 3. Can this issue be reproduced with the latest release?
Yes 

Currently gredis is not support tls, I want to make a pull request to enhance it

**Comment by xbkaishui** [comment]
please assign to me if possible ？

**Comment by xbkaishui** [comment]
my suggestion is add some parameter in the configStr 
like ?idleTimeout=600&tls=true&skipVerify=true 

is that ok ?

**Comment by gqcn** [comment]
@xbkaishui It's awesome! Thanks!

**Comment by xbkaishui** [comment]
no problem
