### ISSUE TITLE
用gorm中的insert插入数据时会多生成字段(struct方式)

### ISSUE THREAD

**Issue by jroam** [gogf/gf#819]
### 1. What version of `Go` and system type/arch are you using?
go 1.14  windows10

### 2. What version of `GoFrame` are you using?
gf1.13.2

### 4. What did you do?

struct对像:
ResetPasswordTokenAt mysql.NullTime `orm:"reset_password_token_at"`

### 5. What did you expect to see?
会生成多余的sql的字段.

如果是:
ResetPasswordTokenAt gtime.Time   `orm:"reset_password_token_at"`
就不会多生成。

**Comment by jroam** [comment]
很紧急，麻烦了。

**Comment by gqcn** [comment]
@jroam 更新到最新的`master`分支代码再试试？

**Comment by jroam** [comment]
已经ok了。
