### ISSUE TITLE
[help] how to prometheus with goframe?

### ISSUE THREAD

**Issue by csrgxtu** [gogf/gf#820]
is there an example showing how to use goframe with prometheus client?

**Comment by gqcn** [comment]
@csrgxtu The great `gf` has implemented the interface `http.Handler`, how you integrate prometheus into `net/http.Server`, how you can do the same integrating with `gf`.

**Comment by botsphp** [comment]
> is there an example showing how to use goframe with prometheus client?

```go
	// prometheus metrics api
	// prometheus 集成方法
	g.Server().BindHandler("/metrics", func(r *ghttp.Request) {
		promhttp.Handler().ServeHTTP(r.Response.Writer, r.Request)
	})
```
