### ISSUE TITLE
gcmd scan问题

### ISSUE THREAD

**Issue by qinyuguang** [gogf/gf#824]
go v1.14.4
gogf v1.13.1

gcmd模块的scan方法，在读取的内容中含有空格时，空格后的内容不会存入返回结果中

这与fmt包中的scan*行为一致，建议修改或者增加个方法来读取包含空格的内容

**Comment by gqcn** [comment]
@qinyuguang 是的，原本也是封装的`fmt.Scan*`相关方法，这也是比较标准的字符串读取方式，感兴趣的话你可以自行研究提供PR。
