### ISSUE TITLE
goframe平滑重启问题

### ISSUE THREAD

**Issue by liao725636367** [gogf/gf#830]
### 1. What version of `Go` and system type/arch are you using?

go version go1.13.11 linux/amd64

### 2. What version of `GoFrame` are you using?

github.com/gogf/gf v1.13.2

### 3. Can this issue be reproduced with the latest release?

yes

### 4. What did you do?
1. 我将goframe二进制文件设置为systemd 服务配置文件如下
![image](https://user-images.githubusercontent.com/10095973/88480498-d7b9c780-cf88-11ea-94f4-017c63296e80.png)
并执行 systemctl start cps.service 启动了 服务
2. 我使用jemeter  开了20个线程对我的服务进行并发请求，并断言是否返回了正常结果，jemeter显示没有出现错误请求
 
![image](https://user-images.githubusercontent.com/10095973/88480763-73980300-cf8a-11ea-94d4-cf7a541f5f93.png)

3. 我尝试使用   systemctl reload  cps.service 平滑重启我的服务

4.jemeter显示有错误请求
![image](https://user-images.githubusercontent.com/10095973/88480740-5400da80-cf8a-11ea-8b69-4a6a5933b6cc.png)

基本都是502错误

![image](https://user-images.githubusercontent.com/10095973/88480913-56176900-cf8b-11ea-8fdb-bf8b0629ede2.png)

### 5. What did you expect to see?

我希望 平滑重启不 会造成部分访问失败

### 6. What did you see instead?

但是jemeter告诉我 有部分请求失败,请教如何才能解决这个问题

 我的配置文件server部分如下
![image](https://user-images.githubusercontent.com/10095973/88480846-edc88780-cf8a-11ea-958f-db4c01e2b6ca.png)
我在日志文件里面也找不到任何的错误日志
作为对比我也尝试了对nginx的平滑重启进行并发测试，它是可以正常工作的，不会造成请求丢失问题

**Comment by liao725636367** [comment]
我知道这是由于 父进程不可控的问题，但是请问能不能支持 master worker模式的优雅重启呢，我相信大部分用户都是会使用 systemd, upstart, supervisor 这些工具作为守护进程运行项目 如果goframe 能支持 是最好的，也可能是我技术有限，因为虽然我虽然找到了一个符合我需求的库  github.com/jpillora/overseer  但是我不知道如何才能配合goframe能够正常的工作

**Comment by goldenwind** [comment]
请问，最后解决方案是什么可以分享下吗？
