### ISSUE TITLE
orm改进建议

### ISSUE THREAD

**Issue by jroam** [gogf/gf#831]
### 1. What version of `Go` and system type/arch are you using?
gf 1.14
 

### 2. What version of `GoFrame` are you using?

gf1.13.2

### 4. What did you do?
```
db := g.Database()
	db.SetDebug(true)
	user := db.Table("users")
	usersDetail := &UserDetail{}

	usersDetail.UserName = "张三y"
	usersDetail.Age = 20
	usersDetail.Address = ""
	rs, err := user.OmitEmpty().Where("id=", 3).Save(usersDetail)
```

OmitEmpty() 能过虑为空的值。
但是,会把Address这一项也过滤掉了.

所以，
希望改进成：
 默认过滤没有值的选项，但故意设为空的值也能更新到数据库里。

**Comment by chenall** [comment]
字符串的空值也就是"",不管你有没有设置都是一样的.
就是数值型的的空值就是0,和你手工设置=0 效果是一样的.

对于这个问题,我觉得你可以把Address修改为指针类型

**Comment by jroam** [comment]
这里的Address字段只是举一个例，下次有可能就是其它字段，或其它几个字段。

**Comment by gqcn** [comment]
@jroam 你这个问题啊，很常见，许多人都问过，其实你的意思是只想过滤数据参数结构体中某部分为空的字段，并不是所有都过滤，那你这里使用`OmitEmpty`并不是很合适，你可以参考下字段过滤：https://goframe.org/database/gdb/chaining/fields-filter 。另外也可以考虑@chenall 的方案，将结构体属性设置为指针，并且通过`gconv.Struct`或者`gf`框架里面其他模块的`Struct`方法赋值，不过较繁琐一些了。
