### ISSUE TITLE
gtimer是否缺少了一个Reset方法?

### ISSUE THREAD

**Issue by XWR940711** [gogf/gf#833]
目前有Start,Stop,Close.少一个重置计时时间.假设有一个N秒一次的定时任务,经过一段时间后重新设定到N秒上.

**Comment by gqcn** [comment]
@XWR940711 由于`gtimer`是基于多层时间轮的设计，定时器`Timer`对象中会包含多个时间轮对象，并且`Timer`管理着很多定时任务，如果是针对于`Timer`对象的`Reset`操作成本会比较大，没有太大意义。不过你可以按照`Entry`任务来执行`Reset`操作，而不是针对于`Timer`对象，这样可操作性和性能都会很不错。目前`Entry`对象没有该方法，感兴趣可以提PR。

**Comment by XWR940711** [comment]
> @XWR940711 由于`gtimer`是基于多层时间轮的设计，定时器`Timer`对象中会包含多个时间轮对象，并且`Timer`管理着很多定时任务，如果是针对于`Timer`对象的`Reset`操作成本会比较大，没有太大意义。不过你可以按照`Entry`任务来执行`Reset`操作，而不是针对于`Timer`对象，这样可操作性和性能都会很不错。目前`Entry`对象没有该方法，感兴趣可以提PR。

已提交PR,请测试下,新增一个状态码.
