### ISSUE TITLE
Web模式下路由问题咨询

### ISSUE THREAD

**Issue by heyangfan** [gogf/gf#834]
假定我们访问/user/info 来获取用户的信息,访问是ok的.
但是在某些情况下,假如用户或者前端生成链接出现domain//user/info 两个斜杠的时候,会访问失败.
我的期望是如果出现//user/info 两个斜杠仍然能正常解析到/user/info,请问该如何配置或者如何解决.
go version 1.14
gf version 1.13.2

**Comment by gqcn** [comment]
@heyangfan 之前也有其他的小伙伴反馈，现在已改进，请更新到最新的`master`分支再试试。

**Comment by heyangfan** [comment]
ok.
已经更新到master,测试没什么问题,非常感谢.
