### ISSUE TITLE
mysql connection not supprt timezone Location params

### ISSUE THREAD

**Issue by xbkaishui** [gogf/gf#837]
### 1. What version of `Go` and system type/arch are you using?

 go version go1.14.4 darwin/amd64

### 2. What version of `GoFrame` are you using?

v1.13.2

### 3. Can this issue be reproduced with the latest release?

yes

### 4. What did you do?

connect mysql use defualt params, the default Location of go mysql-driver use UTC timezone, it's bad for us
and it also support custom timezone https://github.com/go-sql-driver/mysql/blob/1fbca2aabb09915d4f1006d01b271ad7778eec4f/dsn.go#L43 

### 5. What did you expect to see?

user can config timezone by themself 

### 6. What did you see instead?

just default utc timezone

**Comment by xbkaishui** [comment]
please assign to me if it is acceptable

**Comment by xbkaishui** [comment]
please assign to me if it is acceptable

**Comment by XWR940711** [comment]
config.toml->database:link="mysql:username:pwd@tcp(hostname:port)/database?parseTime=true&loc=Asia%2FShanghai"

**Comment by xbkaishui** [comment]
let me try thanks

**Comment by gqcn** [comment]
@xbkaishui Yep, use the configuration as @XWR940711 mentioned. You can find more detailed referring to documentation: https://goframe.org/database/gdb/config
