### ISSUE TITLE
建议增加一个RowsToRecord的方法

### ISSUE THREAD

**Issue by wenzi1** [gogf/gf#839]
目前gdb中有一个： `func (c *Core) rowsToResult(rows *sql.Rows) (Result, error)` 方法，建议增加一个sql.Rows的单条数据转换的方法，供外部使用,类似于： `func RowsToRecord(rows *sql.Rows) (Record, error)`

**Comment by gqcn** [comment]
@wenzi1 好像提供在`gdb`包中也对开发者来说没啥用啊？你可以自己在项目代码中自行封装一个工具方法。

**Comment by wenzi1** [comment]
由于数据量比较大，我想在查询完数据后在循环中每次取出一条数据去处理。 当然自己封装下也可以，就是觉得应该会经常用到

**Comment by gqcn** [comment]
@wenzi1 有个`Chunk`方法啊
```go
// Chunk splits an Result into multiple Results,
// the size of each array is determined by <size>.
// The last chunk may contain less than size elements.
func (r Result) Chunk(size int) []Result
```
