### ISSUE TITLE
文件分隔符问题

### ISSUE THREAD

**Issue by mushu1990** [gogf/gf#841]
1. What version of `GoFrame` are you using?

1.13.1

能否把gfile包的Separator常量分隔符统一为 /
如果路径存储在数据库中的话，windwos迁移到linux路径会识别错误。统一为兼容模式是否会更好。
或者把Separator改成可修改的变量也行。
感谢！

**Comment by gqcn** [comment]
@mushu1990 已改进，试试最新的`master`。
