### ISSUE TITLE
hook exitall 后 middleware还会继续执行（第一次提问题，不知道说算清不清楚）

### ISSUE THREAD

**Issue by wangzhufei** [gogf/gf#842]
#### 附一会打印内容
正常登录打印
```
00:16:21 [DEBU] BaseController.go:71: checkLogin:1yfa6mu0ppr6vv1lns9iac4k2mdb595t8h0v,   currSessionId: 1yfa6mu0ppr6vv1lns9iac4k2mdb595t8h0v
00:16:21 [DEBU] BaseController.go:37: ControllerInit0000000000000000000000000000
00:16:21 [INFO] auth.go:24: [2:][[::1]]接口请求method:POST	 uri:/tool/get_sys_robot_info	 param:
```
帐号在其他地方登录时打印
```
00:16:27 [DEBU] BaseController.go:71: checkLogin:1yfa6mu0ppr6vv1lns9iac4k2mdb595t8h0v,   currSessionId: 1jc4kzq0pp5kqmc4k3dcax2chw1v6eb437a6
00:16:27 [DEBU] BaseController.go:77:  帐号在其他地方登录:1yfa6mu0ppr6vv1lns9iac4k2mdb595t8h0v
00:16:27 [INFO] auth.go:24: [0:][[::1]]接口请求method:POST	 uri:/login	 param:{}
```
####----------------------------------------------------------------------------------------------------

###  问题说明
1、当我触发 “帐号在其他地方登录” 时当（3）存在时，不会输出会输出（1）内容 ，但是会输出（4）内容
2、 当我把（3）去除，留（2）位置，依然会输出（4）内容

###  router 部分
```go
s := g.Server()
s.Use(middleware.CORS, middleware.Auth)
//登录
s.Group("/", func(group *ghttp.RouterGroup) {
	loginController := new(controllers.LoginController)
	group.Hook("/login", ghttp.HOOK_BEFORE_SERVE, loginController.ControllerInit)
	group.Hook("/logout", ghttp.HOOK_BEFORE_SERVE, loginController.ControllerInit)
	group.ALL("/login/", loginController.Login)
	group.ALL("/logout", loginController.Logout)
})
```

### 2. 控制器部分
```go
type BaseController struct {
	gmvc.Controller
	curUser   models.User //当前用户信息
	userAgent string      // 客户端信息
}
// 控制器初始账号数据
func (c *BaseController) ControllerInit(r *ghttp.Request) {
	c.Init(r)
	user := c.Session.Get(models.USER_SESSION_MARK, nil)
	if user != nil {
		gconv.Struct(user, &c.curUser)
	}
	//判断是否登录
	c.checkLogin()  
	// 没有c.Request.ExitAll()，会打印
	g.Log().Debug("ControllerInit0000000000000000000000000000")  -------------------------（1）
        r.ExitAll()  -----------------------------------------------------（2）
}
//检查是否登录
func (c *BaseController) checkLogin() {
	var sessionId string
	sessionKey := strconv.Itoa(c.curUser.Id)
	currSessionId := c.Request.Session.Id()
	utils.GetCache(sessionKey, &sessionId)
	IsAllowMultipleLogin := g.Cfg().GetBool("server.isAllowMultipleLogin", false)
	g.Log().Debugf("checkLogin:%+v,   currSessionId: %+v",sessionId, currSessionId)
	if len(sessionId) == 0 {
		utils.SetCache(sessionKey, currSessionId, 0)
	} else if IsAllowMultipleLogin == false {
		// 检测帐号 是否在多个地方登录
		if sessionId != currSessionId {
			g.Log().Debugf(" 帐号在其他地方登录:%+v",sessionId)
			c.Result(enums.CodeLoginOther,  "帐号在其他地方登录:"+ c.curUser.LastLoginIp, "")
			c.Request.ExitAll()  -----------------------------------------------------（3）
		}
	}
}
//请求返回json
func (c *BaseController) Result(code enums.ResultCode, msg string, data interface{}) {
	result := &models.Result{Code: code, Data: data, Msg: msg}
	c.Response.WriteJsonExit(result)
}
```
### 中间件部分
```go
// 鉴权中间件，只有登录成功之后才能通过
func Auth(r *ghttp.Request) {
	path := r.URL.Path
	user := GetSessionUser(r)
	g.Log().Infof("[%v:%v][%v]接口请求method:%v\t uri:%v\t param:%+v", user.Id, user.Account, r.GetClientIp(), r.Method, path, r.GetBodyString())----------------------------------------------------（4）
	if r.IsFileRequest() {
		r.Middleware.Next()
		return
	}
	r.Middleware.Next()
	r.ExitAll()  // 这边使用就会完全结束k
}
```

**Comment by gqcn** [comment]
@wangzhufei 你的程序启动时候的路由表贴上来看看呢？

**Comment by wangzhufei** [comment]
// 你可以将路由注册放到一个文件中管理，
// 也可以按照模块拆分到不同的文件中管理，
// 但统一都放到router目录下。
func init() {
	s := g.Server()

	s.Use(middleware.CORS, middleware.Auth)
	s.AddStaticPath(g.Cfg().GetString("database.sqlDownloadPath", "/mysql_back"), g.Cfg().GetString("database.backDir", "mysql_back"))
	s.AddStaticPath("/", g.Cfg().GetString("server.ServerRoot", "views"))
	s.AddStaticPath("/dashboard", g.Cfg().GetString("server.ServerRoot", "views"))

	//登录
	s.Group("/", func(group *ghttp.RouterGroup) {
		loginController := new(controllers.LoginController)
		group.Hook("/login", ghttp.HOOK_BEFORE_SERVE, loginController.ControllerInit)
		group.Hook("/logout", ghttp.HOOK_BEFORE_SERVE, loginController.ControllerInit)
		group.ALL("/login/", loginController.Login)
		group.ALL("/logout", loginController.Logout)
	})

	//菜单
	s.Group("/menu", func(group *ghttp.RouterGroup) {
		menuController := new(controllers.MenuController)
		group.Hook("/*", ghttp.HOOK_BEFORE_SERVE, menuController.ControllerInit)
		group.ALL("/list", menuController.List)
		group.ALL("/edit", menuController.Edit)
		group.ALL("/getParentMenuList", menuController.GetParentMenuList)
		group.ALL("/delete", menuController.Delete)
		group.ALL("/menuTree", menuController.MenuTree)
	})

	//节点
	s.Group("/server_node", func(group *ghttp.RouterGroup) {
		serverNodeController := new(controllers.ServerNodeController)
		group.Hook("/*", ghttp.HOOK_BEFORE_SERVE, serverNodeController.ControllerInit)
		group.ALL("/list", serverNodeController.List)
		group.ALL("/edit", serverNodeController.Edit)
		group.ALL("/delete", serverNodeController.Delete)
		//group.ALLde/start", serverNodeController.Start)
		//group.ALLde/stop", serverNodeController.Stop)
		group.ALL("/action", serverNodeController.Action)
		group.ALL("/install", serverNodeController.Install)
	})

	s.EnableAdmin("/system/tool/admin")
}

**Comment by wangzhufei** [comment]
这个是大概内容

**Comment by wangzhufei** [comment]
package boot

import (
	"gfWeb/app/models"
	_ "gfWeb/app/models"
	"gfWeb/app/service/utils"
)

func init() {

	// session改为内存方式(默认为内存+文件)
	//s.SetConfigWithMap(g.Map{
	//	"SessionStorage": gsession.NewStorageMemory(),
	//})
	//初始化日志
	utils.InitLog()
	//初始化缓存
	utils.InitCache()
	models.InitCron()
}

----------------------------------------main--------
package main

import (
	_ "gfWeb/boot"
	_ "gfWeb/router"
	"github.com/gogf/gf/frame/g"
)


func main() {
	s := g.Server()
	s.Run()
}

**Comment by wangzhufei** [comment]
SERVER  | DOMAIN  | ADDRESS | METHOD |                      ROUTE                      |                                       HANDLER                                       |    MIDDLEWARE      
|---------|---------|---------|--------|-------------------------------------------------|-------------------------------------------------------------------------------------|-------------------|
  default | default | :8199   | ALL    | /*                                              | gfWeb/app/service/middleware.CORS                                                   | GLOBAL MIDDLEWARE  
|---------|---------|---------|--------|-------------------------------------------------|-------------------------------------------------------------------------------------|-------------------|
  default | default | :8199   | ALL    | /*                                              | gfWeb/app/service/middleware.Auth                                                   | GLOBAL MIDDLEWARE  
|---------|---------|---------|--------|-------------------------------------------------|-------------------------------------------------------------------------------------|-------------------|
  default | default | :8199   | ALL    | /debug/pprof/*action                            | github.com/gogf/gf/net/ghttp.(*utilPProf).Index-fm                                  |                    
|---------|---------|---------|--------|-------------------------------------------------|-------------------------------------------------------------------------------------|-------------------|
  default | default | :8199   | ALL    | /debug/pprof/cmdline                            | github.com/gogf/gf/net/ghttp.(*utilPProf).Cmdline-fm                                |                    
|---------|---------|---------|--------|-------------------------------------------------|-------------------------------------------------------------------------------------|-------------------|
  default | default | :8199   | ALL    | /debug/pprof/profile                            | github.com/gogf/gf/net/ghttp.(*utilPProf).Profile-fm                                |                    
|---------|---------|---------|--------|-------------------------------------------------|-------------------------------------------------------------------------------------|-------------------|
  default | default | :8199   | ALL    | /debug/pprof/symbol                             | github.com/gogf/gf/net/ghttp.(*utilPProf).Symbol-fm                                 |                    
|---------|---------|---------|--------|-------------------------------------------------|-------------------------------------------------------------------------------------|-------------------|
  default | default | :8199   | ALL    | /debug/pprof/trace                              | github.com/gogf/gf/net/ghttp.(*utilPProf).Trace-fm                                  |                    
|---------|---------|---------|--------|-------------------------------------------------|-------------------------------------------------------------------------------------|-------------------|
  default | default | :8199   | ALL    | /forbid/*                                       | gfWeb/app/controllers.(*BaseController).ControllerInit-fm                           | HOOK_BEFORE_SERVE  
|---------|---------|---------|--------|-------------------------------------------------|-------------------------------------------------------------------------------------|-------------------|
  default | default | :8199   | ALL    | /forbid/forbid_log                              | gfWeb/app/controllers.(*ForbidController).ForbidLogList-fm                          |                    
|---------|---------|---------|--------|-------------------------------------------------|-------------------------------------------------------------------------------------|-------------------|
  default | default | :8199   | ALL    | /forbid/set_forbid                              | gfWeb/app/controllers.(*ForbidController).SetForbid-fm                              |                    
|---------|---------|---------|--------|-------------------------------------------------|-------------------------------------------------------------------------------------|-------------------|
  default | default | :8199   | ALL    | /login                                          | gfWeb/app/controllers.(*LoginController).Login-fm                                   |                    
|---------|---------|---------|--------|-------------------------------------------------|-------------------------------------------------------------------------------------|-------------------|
  default | default | :8199   | ALL    | /login                                          | gfWeb/app/controllers.(*BaseController).ControllerInit-fm                           | HOOK_BEFORE_SERVE  
|---------|---------|---------|--------|-------------------------------------------------|-------------------------------------------------------------------------------------|-------------------|
  default | default | :8199   | ALL    | /logout                                         | gfWeb/app/controllers.(*LoginController).Logout-fm                                  |                    
|---------|---------|---------|--------|-------------------------------------------------|-------------------------------------------------------------------------------------|-------------------|
  default | default | :8199   | ALL    | /logout                                         | gfWeb/app/controllers.(*BaseController).ControllerInit-fm                           | HOOK_BEFORE_SERVE  
|---------|---------|---------|--------|-------------------------------------------------|-------------------------------------------------------------------------------------|-------------------|
  default | default | :8199   | ALL    | /menu/*                                         | gfWeb/app/controllers.(*BaseController).ControllerInit-fm                           | HOOK_BEFORE_SERVE  
|---------|---------|---------|--------|-------------------------------------------------|-------------------------------------------------------------------------------------|-------------------|
  default | default | :8199   | ALL    | /menu/delete                                    | gfWeb/app/controllers.(*MenuController).Delete-fm                                   |                    
|---------|---------|---------|--------|-------------------------------------------------|-------------------------------------------------------------------------------------|-------------------|
  default | default | :8199   | ALL    | /menu/edit                                      | gfWeb/app/controllers.(*MenuController).Edit-fm                                     |                    
|---------|---------|---------|--------|-------------------------------------------------|-------------------------------------------------------------------------------------|-------------------|
  default | default | :8199   | ALL    | /menu/getParentMenuList                         | gfWeb/app/controllers.(*MenuController).GetParentMenuList-fm                        |                    
|---------|---------|---------|--------|-------------------------------------------------|-------------------------------------------------------------------------------------|-------------------|
  default | default | :8199   | ALL    | /menu/list                                      | gfWeb/app/controllers.(*MenuController).List-fm                                     |                    
|---------|---------|---------|--------|-------------------------------------------------|-------------------------------------------------------------------------------------|-------------------|
  default | default | :8199   | ALL    | /menu/menuTree                                  | gfWeb/app/controllers.(*MenuController).MenuTree-fm                                 |                    
|---------|---------|---------|--------|-------------------------------------------------|-------------------------------------------------------------------------------------|-------------------|
  default | default | :8199   | ALL    | /resource/*                                     | gfWeb/app/controllers.(*BaseController).ControllerInit-fm                           | HOOK_BEFORE_SERVE  
|---------|---------|---------|--------|-------------------------------------------------|-------------------------------------------------------------------------------------|-------------------|
  default | default | :8199   | POST   | /resource/checkurlfor                           | gfWeb/app/controllers.(*ResourceController).CheckUrlFor-fm                          |                    
|---------|---------|---------|--------|-------------------------------------------------|-------------------------------------------------------------------------------------|-------------------|
  default | default | :8199   | ALL    | /resource/delete                                | gfWeb/app/controllers.(*ResourceController).Delete-fm                               |                    
|---------|---------|---------|--------|-------------------------------------------------|-------------------------------------------------------------------------------------|-------------------|
  default | default | :8199   | ALL    | /resource/edit                                  | gfWeb/app/controllers.(*ResourceController).Edit-fm                                 |                    
|---------|---------|---------|--------|-------------------------------------------------|-------------------------------------------------------------------------------------|-------------------|
  default | default | :8199   | ALL    | /resource/getParentResourceList                 | gfWeb/app/controllers.(*ResourceController).GetParentResourceList-fm                |                    
|---------|---------|---------|--------|-------------------------------------------------|-------------------------------------------------------------------------------------|-------------------|
  default | default | :8199   | ALL    | /resource/list                                  | gfWeb/app/controllers.(*ResourceController).List-fm                                 |                    
|---------|---------|---------|--------|-------------------------------------------------|-------------------------------------------------------------------------------------|-------------------|
  default | default | :8199   | ALL    | /resource/resourceTree                          | gfWeb/app/controllers.(*ResourceController).ResourceTree-fm                         |                    
|---------|---------|---------|--------|-------------------------------------------------|-------------------------------------------------------------------------------------|-------------------|

**Comment by gqcn** [comment]
@wangzhufei 我没有复现你所说的问题，建议你更新到最新的版本自己排查下原因。

**Comment by chamhaw** [comment]
我也有类似的问题，exitAll 还是走到了后面 middleware
<img width="671" alt="image" src="https://user-images.githubusercontent.com/93499036/207562656-80932fdc-dcd9-43d4-8638-e9e32d3d9b09.png">

注册顺序 debug 看了下，是正确的
<img width="235" alt="image" src="https://user-images.githubusercontent.com/93499036/207562809-95145c6a-cda8-48b8-9057-fddcffbe95c4.png">
