### ISSUE TITLE
能不能加一个内存分页插件

### ISSUE THREAD

**Issue by 986244073** [gogf/gf#846]
和mybatis plus 一样 可以返回total  page size data:[] 的数据

**Comment by gqcn** [comment]
@986244073 具体一点呢？

**Comment by stone1970** [comment]
他的意思应该是对分页数据的封装，包含了totalElements总条目，pageSize页大小，totalPage总页数，currentPage当前页等。
我看到官方文档有 r.GetPage 对分页连接的封装，却没有对分页数据的封装，还找了蛮久

**Comment by gqcn** [comment]
@986244073 @stone1970 我怕我理解得不对，有类似的参考么，发个连接呢？

**Comment by stone1970** [comment]
> @986244073 @stone1970 我怕我理解得不对，有类似的参考么，发个连接呢？

https://learnku.com/docs/laravel/7.x/pagination/7495
https://docs.spring.io/spring-data/jpa/docs/2.3.2.RELEASE/reference/html/#repositories.special-parameters

**Comment by gqcn** [comment]
@986244073 @stone1970 其实`gdb.Model`的链式方法中有`Page`方法用于分页数据查询；另外有专门的`gpage`包，并且`ghttp.Request`也有`GetPage`方法简化使用，用于展示分页。

**Comment by 986244073** [comment]
> @986244073 @stone1970 其实`gdb.Model`的链式方法中有`Page`方法用于分页数据查询；另外有专门的`gpage`包，并且`ghttp.Request`也有`GetPage`方法简化使用，用于展示分页。

是orm的分页吗

**Comment by 986244073** [comment]
我的意思是对orm 查询出来结果的进行分页 自动加上total page size

**Comment by 986244073** [comment]
在做了吗

**Comment by gqcn** [comment]
@986244073 你想要的是类似`all, total := db.Model(xxx).Page(page, size).List()`这样的效果吗？

**Comment by 986244073** [comment]
对

**Comment by gqcn** [comment]
@986244073 那先排个期吧。

**Comment by LonelySally** [comment]
> @986244073 那先排个期吧。

他说的是mybiats的分页插件返回的结构是这样的
{
        "total": 0,
        "page": 1,
        "pageSize": 0,
        "totalPage": 0,
        "lists": []
}

**Comment by gqcn** [comment]
> > @986244073 那先排个期吧。
> 
> 他说的是mybiats的分页插件返回的结构类似这样的
> {
> "total": 0,//记录总数
> "page": 1,//当前页
> "pageSize": 0,//每页记录数
> "totalPage": 0,//合计页数
> "lists": []//当前页列表
> }

倒是可以实现的，不难，期望能有小伙伴直接提供PR吧。

**Comment by lusson-luo** [comment]
@gqcn 这个功能如果要做的话，怎么去做呢，可以给个实现思路吗？

**Comment by lusson-luo** [comment]
我可以抽空做一下

**Comment by lusson-luo** [comment]
我提交了 pr #2635
