### ISSUE TITLE
connector.go:48: net.Error from Dial()': dial tcp  xxx.xxx.xxx.xxx socket: too many open files

### ISSUE THREAD

**Issue by dayaya** [gogf/gf#849]
### 1. What version of `Go` and system type/arch are you using?
v1.13.7

### 2. What version of `GoFrame` are you using?
v1.11.4

linux 系统的打开文件数已经设置为60000，运行一段时间后就会出现。。

**Comment by gqcn** [comment]
@dayaya 具体一点，你用的什么包，什么操作引起的，你是否有手动调用`Close`方法？

**Comment by dayaya** [comment]
好像是开启了http服务，很多次连接后就会出现。

open /tmp/log/2020-08-04.log: too many open files
2020-08-04 05:01:02.497 [ERRO] http: Accept error: accept tcp [::]:9011: accept4: too many open files; retrying in 5ms
Stack:
1.  github.com/gogf/gf/net/ghttp.(*gracefulServer).doServe
    C:/Users/93255/go/pkg/mod/github.com/gogf/gf@v1.11.4/net/ghttp/ghttp_server_graceful.go:138
2.  github.com/gogf/gf/net/ghttp.(*gracefulServer).ListenAndServe
    C:/Users/93255/go/pkg/mod/github.com/gogf/gf@v1.11.4/net/ghttp/ghttp_server_graceful.go:70
3.  github.com/gogf/gf/net/ghttp.(*Server).startServer.func1
    C:/Users/93255/go/pkg/mod/github.com/gogf/gf@v1.11.4/net/ghttp/ghttp_server.go:541

open /tmp/log/2020-08-04.log: too many open files
2020-08-04 05:01:02.502 [ERRO] http: Accept error: accept tcp [::]:9011: accept4: too many open files; retrying in 10ms
Stack:
1.  github.com/gogf/gf/net/ghttp.(*gracefulServer).doServe
    C:/Users/93255/go/pkg/mod/github.com/gogf/gf@v1.11.4/net/ghttp/ghttp_server_graceful.go:138
2.  github.com/gogf/gf/net/ghttp.(*gracefulServer).ListenAndServe
    C:/Users/93255/go/pkg/mod/github.com/gogf/gf@v1.11.4/net/ghttp/ghttp_server_graceful.go:70
3.  github.com/gogf/gf/net/ghttp.(*Server).startServer.func1
    C:/Users/93255/go/pkg/mod/github.com/gogf/gf@v1.11.4/net/ghttp/ghttp_server.go:541
Socket error Event: 32 Error: 10053.
Connection closing...Socket close.

Connection closed by foreign host.

**Comment by dayaya** [comment]
@gqcn 
func Json(r *ghttp.Request, errCode int, msg string, data interface{}) {

	obj := g.Map{}

	if errCode == 0 {
		obj["status"] = "SUCCESS"
		if data != nil {
			obj["data"] = data
		}
	} else {
		obj["status"] = "ERROR"
		obj["msg"] = msg
	}

	//fmt.Println("响应", obj)
	//fmt.Println("响应", r.Response)

	_ = r.Response.WriteJson(obj)
	r.Exit()
}

所有的http服务，我都调用了这个方法返回， 这个里的  r.Exit() 应该就会关闭连接吧？ @dayaya

**Comment by gqcn** [comment]
@dayaya `ghttp.Server`基于的是`net/http.Server`，标准库内部会自动处理网络连接，你是不是压测的时候出现的？可以把最大文件打开句柄设置到65535试试。

**Comment by dayaya** [comment]
开始出现问题后，我查了一下打开句柄数是1024
后面我就设置成了 60000，但是运行几天后，又出现这个了（开始没设置之前1天左右就会出现）
现在是生产环境。 @gqcn

**Comment by dayaya** [comment]
@gqcn 
func Json(r *ghttp.Request, errCode int, msg string, data interface{}) {

	obj := g.Map{}

	if errCode == 0 {
		obj["status"] = "SUCCESS"
		if data != nil {
			obj["data"] = data
		}
	} else {
		obj["status"] = "ERROR"
		obj["msg"] = msg
	}

	//fmt.Println("响应", obj)
	//fmt.Println("响应", r.Response)

	_ = r.Response.WriteJson(obj)
	**err := r.Request.Response.Body.Close()**
	if err != nil {
		fmt.Println("关闭错误", err)
	}
	r.Exit()
}

我在http服务响应代码中，添加了这一行：r.Request.Response.Body.Close()，然后该进行打开的句柄数据保持在一个定的数量上了（之前一直增长，不减少）。
好像这样之后，问题解决了。
你们的样例代码中没有包含这个。。

**Comment by dayaya** [comment]
我在跑几天看看。。是否真的解决此问题。

**Comment by dayaya** [comment]
最终测试 再r.Exit() 前加上 r.Body.Close() 就没有这样的问题了。打开的句柄数没有增加了。
