### ISSUE TITLE
orm 在没有连接池预热的情况瞬间事物并发卡死

### ISSUE THREAD

**Issue by siyue8899** [gogf/gf#854]
``` go
[database]
    [[database.default]]
        host         = ""
        port         = "3306"
        user         = ""
        pass         = ""
        name         = "demo"
        type         = "mysql"
        debug        = "true"
        charset      = "utf8mb4"
        maxIdle      = "1"
        maxOpen      = "20"
        maxLifetime  = "30"

func Hello(r *ghttp.Request) {
    _ = g.DB().Transaction(func(tx *gdb.TX) error {
        //延迟1s模拟耗时事物
        time.Sleep(time.Second)
        _, err := tx.Table(user.Table).Data("name","siyue").Insert()
        return err
    })
    r.Response.Writeln("Hello World!")
}

//建表语句 mysql 8.0
//CREATE TABLE `user` (
//`id` int(11) NOT NULL AUTO_INCREMENT,
//`name` varchar(255) DEFAULT NULL,
//PRIMARY KEY (`id`)
//) ENGINE=InnoDB AUTO_INCREMENT=2489 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```
压测命令
wrk -t4 -c100 -d10s  --latency    http://127.0.0.1:8199/

服务刚启动的时候直接用压测工具瞬间并发连接池瞬间满了然后卡死事物不执行,
如果提前手动请求一次预热在用压测工具就正常

**Comment by XWR940711** [comment]
尝试下在boot.go中对g.DB做一次ping操作然后执行压测.

**Comment by siyue8899** [comment]
> 尝试下在boot.go中对g.DB做一次ping操作然后执行压测.

ping 就是预热了.....,和作者qq交流说是底层驱动导致的问题具体还不知道啥原因

**Comment by XWR940711** [comment]
> > 尝试下在boot.go中对g.DB做一次ping操作然后执行压测.
> 
> ping 就是预热了.....,和作者qq交流说是底层驱动导致的问题具体还不知道啥原因

就是规避这个问题.gf的mysql连接池本身就是go-sql-driver/mysql.可以用原生的测试下.

**Comment by XWR940711** [comment]
> > 尝试下在boot.go中对g.DB做一次ping操作然后执行压测.
> 
> ping 就是预热了.....,和作者qq交流说是底层驱动导致的问题具体还不知道啥原因

就是规避这个问题.gf的mysql连接池本身就是go-sql-driver/mysql.可以用原生的测试下.gdb包的初始化在init中.只有被引用了才会触发.

**Comment by Insua** [comment]
> 尝试下在boot.go中对g.DB做一次ping操作然后执行压测.

如何预热g.DB 能指教一下吗？

**Comment by XWR940711** [comment]
> > 尝试下在boot.go中对g.DB做一次ping操作然后执行压测.
> 
> 如何预热g.DB 能指教一下吗？

因为包里是func init()进行初始化的 所以只要调用一次包就可以

**Comment by gqcn** [comment]
抱歉，我回头有一次看了一下这个issue，还是没有找到原因，底层的mysql-driver直接使用也有这样的问题。期望知晓原因的小伙伴可以帮大家解答一下。

**Comment by chenkby** [comment]
@gqcn 遇到类似的问题，我有2个定时程序，1个用来写入队列，1个用来读队列。队列用的是本地的beanstalkd，跟数据库没关系。2个程序执行过程中都会写入数据库。当运行一段时间后，达到MaxOpenConnCount值时，读队列的程序会卡死在
`g.DB().Transaction(func(tx *gdb.TX) error {`
这里。但是写队列的程序仍然可以继续写入（但不会超过MaxOpenConnCount）。

因为会卡死，所以我加了个超时控制，超时后重新把数据放入队列执行：

`	ctx, cancel := context.WithTimeout(context.Background(), time.Second*5)
	defer cancel()
	err := g.DB().Ctx(ctx).Transaction(func(tx *gdb.TX) error {`

加上超时后，重新进队列也没问题。此时，我把写队列程序关掉，只保留读队列，此时看数据库
`show full PROCESSLIST;`
已经降下来了，但是写队列程序还是会进入超时，就算数据库有空闲的情况下，它也没有新建连接。

**Comment by housemecn** [comment]
> @gqcn 遇到类似的问题，我有2个定时程序，1个用来写入队列，1个用来读队列。队列用的是本地的beanstalkd，跟数据库没关系。2个程序执行过程中都会写入数据库。当运行一段时间后，达到MaxOpenConnCount值时，读队列的程序会卡死在
> `g.DB().Transaction(func(tx *gdb.TX) error {`
> 这里。但是写队列的程序仍然可以继续写入（但不会超过MaxOpenConnCount）。
> 
> 因为会卡死，所以我加了个超时控制，超时后重新把数据放入队列执行：
> 
> ` ctx, cancel := context.WithTimeout(context.Background(), time.Second*5) defer cancel() err := g.DB().Ctx(ctx).Transaction(func(tx *gdb.TX) error {`
> 
> 加上超时后，重新进队列也没问题。此时，我把写队列程序关掉，只保留读队列，此时看数据库
> `show full PROCESSLIST;`
> 已经降下来了，但是写队列程序还是会进入超时，就算数据库有空闲的情况下，它也没有新建连接。

上次还打算查 上下文里的超时是怎么设置的，并发上去里 时不时的出现，超时取消的情况

**Comment by gqcn** [comment]
各位小伙伴莫急，小问题，我瞅瞅 :-)

**Comment by gqcn** [comment]
@Insua @chenkby @LonelySally @siyue8899 @housemecn 请各位升级到`v1.15.6`再试试😊。
