### ISSUE TITLE
Feature wanted:  i18n support  `fmt` grammer 

### ISSUE THREAD

**Issue by skanger** [gogf/gf#855]
### 1. What version of `Go` and system type/arch are you using?

go version go1.14.4 darwin/amd64

### 2. What version of `GoFrame` are you using?

github.com/gogf/gf v1.13.2

### 3. Can this issue be reproduced with the latest release?

yes

### 4. What did you do?

It's a feature want.

Can we support  i18n with `fmt` grammer?

in en.toml 
`BalanceNotEnough =  "your balance  %f  is not enough, need %f"`

in main.go
`i18n.TWithVar(content, "en",  99.8, 101.1)`

中文描述:
能不能增加一个新功能
让i18n增加fmt语法支持？

 en.toml 内容 
`BalanceNotEnough =  "your balance  %f  is not enough, need %f"`

main.go 内容
`i18n.TWithVar(content, "en",  99.8, 101.1)`

谢谢

**Comment by gqcn** [comment]
@skanger It's done, and will be released in `v1.14.0`。
