### ISSUE TITLE
checkDataType方法中对配置文件格式的判断错误

### ISSUE THREAD

**Issue by wenzi1** [gogf/gf#856]
### 1. What version of `Go` and system type/arch are you using?
v1.13

### 2. What version of `GoFrame` are you using?
v1.3.2

### 4. What did you do?
config.toml的内容为：
```
bb           = """
                    dig := dig;                         END;"""
```
当config.toml中包含类似的内容后在encoding.gjson.gjson_api_new_load.go中的checkDataType方法会将该文件类型判断为yml，导致导入config.toml时报错

### 5. What did you expect to see?

checkDataType方法应该将文件识别为toml类型

### 6. What did you see instead?
实际上将文件识别为了yml类型

**Comment by wenzi1** [comment]
对于config文件类型的判断能否改为由外部传入的方式，目前使用正则表达式这种方式来判断的话如果遇到yml和toml相似的内容的话还是会有问题

**Comment by gqcn** [comment]
@wenzi1 是的，正则判断并不是完全严谨，目前新增了`LoadContentType`方法用来指定加载的配置内容格式。
