### ISSUE TITLE
[gjson] dynamically build JSON, array operation exception

### ISSUE THREAD

**Issue by francisxie** [gogf/gf#857]
# 1.What version of `Go` and system type/arch are you using?
    go version go1.14.6 windows/amd64
# 2.What version of `GoFrame` are you using?
    github.com/gogf/gf v1.13.3
# 3.Can this issue be reproduced with the latest release?
    yes
# 4.What did you do?
``` go
	j := gjson.New(nil)

	j.Set("processors.0.set.0value", "{{_ingest.timestamp}}")
	j.Set("processors.0.set.0field", "ingest_timestamp")
	j.Set("description", "Adds a field to a document with the time of ingestion")
	fmt.Println(j.MustToJsonString())
````
预想结果
``` json
{
	"description": "Adds a field to a document with the time of ingestion",
	"processors": [
		{
			"set": {
				"field": "ingest_timestamp",
				"value": "{{_ingest.timestamp}}"
			}
		}
	]
}
```
实际结果
![image](https://user-images.githubusercontent.com/22124363/89502517-b3b37d00-d7f7-11ea-8e57-10f7ab36c6f4.png)

**Comment by gqcn** [comment]
@francisxie Please use the latest codes of master branch and have another try.
