### ISSUE TITLE
[WIP]请问模板引擎是否有计划支持类似thinkphp的模板继承功能？

### ISSUE THREAD

**Issue by kxy000** [gogf/gf#86]
目前在用gf 试着重写公司的后台，原来用thinkphp，里面有个模板继承功能，官方文档：https://www.kancloud.cn/manual/thinkphp5/125014

目前用原生的template模板基本可以实现，但这样 gf自带的一些模板方法貌似就不能用了，不知道大大是否有计划支持类似的功能？对于一些后台布局 会非常省力。

**Comment by johngcn** [comment]
@kxy000 好的，没问题，后面会增加支持。

**Comment by kxy000** [comment]
赞~~  感谢感谢

**Comment by johngcn** [comment]
@kxy000 `layout`模板布局开发文档已更新：https://goframe.org/os/gview/layout
