### ISSUE TITLE
tcp获取响应时间无法自定义

### ISSUE THREAD

**Issue by tianxia0079** [gogf/gf#871]
方法支持自定义超时时间。
经测试发现，当tcp断开后，recv方法需要等很长时间才能返回err。
希望可以支持自定义超时时间，一定时间内没有响应立即返回err

func (c *Conn) Recv(length int, retry ...Retry) ([]byte, error)

**Comment by gqcn** [comment]
@tianxia0079 看下接口文档，有以下方法：
```go
RecvWithTimeout(length int, timeout time.Duration, retry ...Retry) (data []byte, err error)
```
