### ISSUE TITLE
[Help] How to validate optional params?

### ISSUE THREAD

**Issue by csrgxtu** [gogf/gf#873]
1st, with following schema:
```go
type SearchTaskReqSchema struct {
	PageNum       int64  `p:"page_num" v:"required|min:1#page_num is required" json:"page_num"`
	PageSize      int64  `p:"page_size" v:"required|between:1,100#page_size is required" json:"page_size"`
	ParentProject int64  `p:"parent_project" v:"between:1,1#parent_project must between 1, 1"  json:"parent_project,omitempty"`
}
```
2nd, if i dont provide the optional param: ParentProject, goframe validator will return following:
The ParentProject value must be between 1 and 1

Question: how can i specify optional parameters?

**Comment by gqcn** [comment]
@csrgxtu If the attribute value has no `required*` validation rule and is an empty string or nil pointer, it is considered as an optional validation value and all its validation is ignored for this attribute. Please refer to the following document:
- https://goframe.org/util/gvalid/checkmap
- https://goframe.org/util/gvalid/checkstruct
