### ISSUE TITLE
1.13.3 mysql 插入新数据  错误  1.13.2 正常

### ISSUE THREAD

**Issue by jinmao88** [gogf/gf#880]
### 1. What version of `Go` and system type/arch are you using?

go 1.15 
win10

### 2. What version of `GoFrame` are you using?

gf 1.13.3

1.13.3插入数据
某一个时间段传空值提示

Incorrect datetime value: ''

1.13.2 没问题

**Comment by gqcn** [comment]
@jinmao88 你用master分支试试呢，不行的话把代码提交上来我试试。

**Comment by jinmao88** [comment]
试了 一样，
代码发QQ了
