### ISSUE TITLE
tx.Insert("menu", data)  不会自动更新create_at、update_at

### ISSUE THREAD

**Issue by renfan** [gogf/gf#881]
### 1. What version of `Go` and system type/arch are you using?
go version go1.14.4 darwin/amd64

### 2. What version of `GoFrame` are you using?
github.com/gogf/gf v1.13.1

### 4. What did you do?
`res, err := tx.Insert(menu.Table, entity)`
后面我又试了一下改成
`res, err := tx.Table(menu.Table).Data(entity).Insert()`
或者`res, err := tx.Table(menu.Table).Insert(entity)`
是可以的

### 5. What did you expect to see?

![image](https://user-images.githubusercontent.com/3666795/91409296-d0335a00-e877-11ea-8773-f934e1c75bfc.png)

### 6. What did you see instead?
![image](https://user-images.githubusercontent.com/3666795/91409209-b2fe8b80-e877-11ea-8f0b-b174799db594.png)

**Comment by renfan** [comment]
我觉得只提供一种解决方案就可以了
`tx.Table(menu.Table).Data(entity).Insert()`

其他简写方式没什么必要，反而还要多记一种写法。。

**Comment by gqcn** [comment]
@renfan 试试最新的master分支

**Comment by renfan** [comment]
still not work after I changed to master branch `github.com/gogf/gf v1.13.5-0.20200830165942-f54593037b09`
![image](https://user-images.githubusercontent.com/3666795/91665325-4f9a8500-eb27-11ea-885f-defd30498be9.png)

**Comment by gqcn** [comment]
@jianchenma Jack, would you please follow up this?

**Comment by jianchenma** [comment]
@gqcn @renfan done!

**Comment by renfan** [comment]
![image](https://user-images.githubusercontent.com/3666795/91800248-3db9fe80-ec5b-11ea-9a6e-a842cd933e93.png)
@jianchenma well done!
