### ISSUE TITLE
oracle 执行one命令，转换成真正的sql没有去掉limit，oracle报错

### ISSUE THREAD

**Issue by wxc318** [gogf/gf#890]
### 1. What version of `Go` and system type/arch are you using?

go version 1.14      system   win10  64位     oracle  11.2  

### 2. What version of `GoFrame` are you using?

gf@v1.13.3

### 3. Can this issue be reproduced with the latest release?

是

### 4. What did you do?

连接oracle  11.2 ，执行如下代码，报错
```go
r, err := g.DB().Table("USER_INFO").Where("ID", 3).One()
	if err != nil {
		panic(err)
	}
	fmt.Println("ENAME:", r.Map()["ENAME"])
```
报错如下：
```
dpiStmt_execute: ORA-00933: SQL command not properly ended, SELECT * FROM USER_INFO WHERE ID=3 LIMIT
```

### 5. What did you expect to see?

gf应该判断出oracle后， 把limit 去掉， 然后用rownum 替代

### 6. What did you see instead?

limit 还在gf生成的sql中， oracle 不支持 limit 关键字

**Comment by gqcn** [comment]
@wenzi1 蚊子可以看看么？

**Comment by gqcn** [comment]
@wxc318 请使用最新的master分支代码再试试。

**Comment by wxc318** [comment]
我用最新的master 代码  1.13.4  问题还是一样的
panic: dpiStmt_execute: ORA-00933: SQL command not properly ended, SELECT ENAME FROM USER_INFO WHERE ID=2 LIMIT 1
@gqcn

**Comment by wenzi1** [comment]
这个是bug,我已经改完了，还没提交，下周一提交

**Comment by wenzi1** [comment]
已提交 #897

**Comment by wxc318** [comment]
已经提交了吗，我刚把本地的最新版本删掉又下载运行了一次，问题依旧啊 @wenzi1

**Comment by wenzi1** [comment]
还没合并呢

**Comment by gqcn** [comment]
@wxc318 你需要`go get -u github.com/gogf/gf@master`使用最新的`master`分支试试。

**Comment by wxc318** [comment]
用最新的master分支测试通过
