### ISSUE TITLE
Redesign the Middleware 

### ISSUE THREAD

**Issue by xbkaishui** [gogf/gf#892]
I proposal to redesign the server middleware function,  the current implement cant pass response in the params, it's not easy to add more funcationality

for example, the orignal like

``` go
s.BindMiddlewareDefault(ApmMiddleware)

func ApmMiddleware(r *ghttp.Request) {
	r.Middleware.Next()
}

```

I want to change like this 
```  go
s.BindMiddlewareDefault(ApmMiddleware)

func ApmMiddleware(req *ghttp.Request, res *ghttp.Response) {
	r.Middleware.Next(req,res )
}

```
then, we can modify the request and monitor the response

**Comment by gqcn** [comment]
@xbkaishui The `Request` object already contains the request and response object.

**Comment by xbkaishui** [comment]
Good thanks
