### ISSUE TITLE
提个orm的需求

### ISSUE THREAD

**Issue by ZhangIvan** [gogf/gf#893]
当前orm查询后输出的都是统一的时间格式，有个想法，通过tag的方式动态定义时间的输出格式，这样orm查询出的数据api对外可以有不同的时间格式输出；

 建议是和gtime模块关联，gtime挺好用的；
请大佬评估可行性，谢谢！

![image](https://user-images.githubusercontent.com/25630763/92197467-6aad2200-eea4-11ea-821a-63a68be50d69.png)

**Comment by gqcn** [comment]
@ZhangIvan ORM的`tag`其实非常少，目的就是为了简便，大道至简，如果是需要在展示的时候输出不同的时间格式，`gtime`支持各种格式化语法，自行处理吧。此外，如果想对自定义的数据结构进行自定义的转换，可以对该结构实现`MarshalJSON`接口方法即可。
