### ISSUE TITLE
Model.Fields问题

### ISSUE THREAD

**Issue by zhenhua1** [gogf/gf#896]
title_class.Model.Fields("*,concat(path,',',id) as paths").All()
这样查询出来的数据返回的结果集中没有paths，如果我要用paths需要怎么获取

**Comment by gqcn** [comment]
@zhenhua1 我试了是有的

**Comment by zhenhua1** [comment]
> @zhenhua1 我试了是有的，使用的是最新的`master`分支

![ad38159f69313f5dadf7297b9cb345d](https://user-images.githubusercontent.com/22211474/92489219-1bf3e500-f222-11ea-883d-eeaafb5a60cb.png)
这是我这边操作的结果，怎么都没有paths，您能说一下您的具体操作方式吗，能截一下图吗。为什么我这边不行能。gf版本我已经升级到V1.13.4了

**Comment by zhwei820** [comment]
> > @zhenhua1 我试了是有的，使用的是最新的`master`分支
> 
> ![ad38159f69313f5dadf7297b9cb345d](https://user-images.githubusercontent.com/22211474/92489219-1bf3e500-f222-11ea-883d-eeaafb5a60cb.png)
> 这是我这边操作的结果，怎么都没有paths，您能说一下您的具体操作方式吗，能截一下图吗。为什么我这边不行能。gf版本我已经升级到V1.13.4了

用gf的 最新master分支看看？

**Comment by zhenhua1** [comment]
> > > @zhenhua1 我试了是有的，使用的是最新的`master`分支
> > 
> > 
> > ![ad38159f69313f5dadf7297b9cb345d](https://user-images.githubusercontent.com/22211474/92489219-1bf3e500-f222-11ea-883d-eeaafb5a60cb.png)
> > 这是我这边操作的结果，怎么都没有paths，您能说一下您的具体操作方式吗，能截一下图吗。为什么我这边不行能。gf版本我已经升级到V1.13.4了
> 
> 用gf的 最新master分支看看？
![a263134c143b52cabfe3905d831fd96](https://user-images.githubusercontent.com/22211474/92607016-2ecfed80-f2e6-11ea-8760-b3cfa721bc91.png)

首先看一下这写的有问题没。我这试了怎么都不行。也不知道怎么解决了。现在都有点失望了，我看咱们的版本是v1.13.4,，我能用这个版本试验成功吗，我现在用的是go module管理代码的

**Comment by gqcn** [comment]
@zhenhua1 可能是因为返回的是`Entity`对象，这样返回的数据结构就限制死了，你可以这样使用原生的`gdb.Model`查询方法，返回`gdb.Result`类型：
```go
title_class.Model.M.Fields("*,concat(path,',',id) as paths").All()
```

**Comment by zhenhua1** [comment]
> @zhenhua1 可能是因为返回的是`Entity`对象，这样返回的数据结构就限制死了，你可以这样使用原生的`gdb.Model`查询方法，返回`gdb.Result`类型：
> 
> ```go
> title_class.Model.M.Fields("*,concat(path,',',id) as paths").All()
> ```

谢谢您，问题正如您所说的必须用原生的，目前框架中这样的查询不能用返回Entity对象的操作
