### ISSUE TITLE
文件上传是否可以上传apk文件

### ISSUE THREAD

**Issue by chuguofei** [gogf/gf#898]

**Comment by chuguofei** [comment]
// 上传apk
func (controller *Controller) UploadApk(r *ghttp.Request) {
	r.ParseMultipartForm(100<<20+512)
	files := r.GetUploadFile("file")
	names, err := files.Save("./upload")
	if err != nil {
		r.Response.WriteExit(err)
	}
	r.Response.WriteExit("upload successfully: ", names)
}

**Comment by gqcn** [comment]
@chuguofei 服务端对上传的文件类型不会做限制的。

**Comment by chuguofei** [comment]
小点的文件可以上传，上传几十MB的程序奔溃

**Comment by gqcn** [comment]
@chuguofei 注意哦：上传文件大小受到`ghttp.Server`的`ClientMaxBodySize`配置影响：https://godoc.org/github.com/gogf/gf/net/ghttp#ServerConfig 默认支持的上传文件大小为`8MB`。
