### ISSUE TITLE
gdb链接池问题

### ISSUE THREAD

**Issue by 804657038** [gogf/gf#900]
我config.toml中设置了MaxLifetime，但是连接池还会一直在保持链接，不会关闭，导致连接数攒满

**Comment by LonelySally** [comment]
是否使用了db的Query方法?

**Comment by 804657038** [comment]
> 
> 
> 是否使用了db的Query方法?

使用地方使用这个Query

**Comment by 804657038** [comment]
> 
> 
> 是否使用了db的Query方法?

是的，有的地方只能自己写sql语句

**Comment by 804657038** [comment]
> Query

请问，有何良策

**Comment by LonelySally** [comment]
> > Query
> 
> 请问，有何良策

Query方法使用后需要Close.如果你执行sql语句不需要结果集,建议改成Exec即可.

**Comment by 804657038** [comment]
> 
> 
> > > Query
> > 
> > 
> > 请问，有何良策
> 
> Query方法使用后需要Close.如果你执行sql语句不需要结果集,建议改成Exec即可.

给力 给力 完成了
