### ISSUE TITLE
gmap偶发性死锁问题

### ISSUE THREAD

**Issue by zhangHongBo21** [gogf/gf#901]
主要是在websocket中做链接记录功能

示例代码 
```go
// 链接列表
var memeberList = gmap.New(true)

type Controller struct {
	gmvc.Controller
	ws *ghttp.WebSocket
}

//func (c *Controller) pong(appdata string) error {
//	b := ""
//	if appdata == "ping" {
//		b = "pong"
//	}
//	return c.ws.WriteMessage(ghttp.WS_MSG_PONG, []byte(b))
//}

func (c *Controller) WsHandler() {
	var (
		err error
	)
	// 完成http应答，在httpheader中放下如下参数
	if ws, err := c.Request.WebSocket(); err == nil {
		c.ws = ws
	} else {
		g.Log().Error(err)
		return
	}
	userId := c.ws.RemoteAddr().String() + gconv.String(grand.N(10, 1000))
	if err != nil {
		glog.Println("升级WS出错", err)
		return // 获取连接失败直接返回
	}
	memeberList.Set(c.ws, userId)
	//c.ws.SetPingHandler(c.pong)
	for {
		if _, _, err := c.ws.NextReader(); err != nil {
			//健康检查，失去连接立即跳出
			break
		}
		// 只能发送Text, Binary 类型的数据,下划线意思是忽略这个变量.
		msgType, data, err := c.ws.ReadMessage()
		if err != nil {
			break
		}
		fmt.Println(c.ws.RemoteAddr().String(), string(data[:]))
		// []byte(string)
		if err = c.ws.WriteMessage(msgType, []byte("pong")); err != nil {
			break
		}
	}
	//当前连接失去连接，关闭连接并且移除记录信息
	glog.Info(userId, "断开链接")
	memeberList.Remove(c.ws)

	err = c.ws.Close()
	if err != nil {
		panic(err)
	}
}
func main() {
	
	pprofHandler := http.NewServeMux()
	pprofHandler.Handle("/debug/pprof/", http.HandlerFunc(pprof.Index))
	server := &http.Server{Addr: ":9897", Handler: pprofHandler}
	go server.ListenAndServe()
	s := g.Server()
	s.Group("/", func(group *ghttp.RouterGroup) {
		c := new(Controller)
		group.ALL("/", c)
	})
	s.SetPort(1777)
	s.Run()
}

```

然后代码会在`memeberList.Remove(c.ws)`处发生死锁 导致程序卡死

**Comment by zhangHongBo21** [comment]
![image](https://user-images.githubusercontent.com/51777470/92850632-4232a400-f41f-11ea-9e92-bff5a4ae72c5.png)

**Comment by gqcn** [comment]
@zhangHongBo21 你使用的gf版本是多少？使用最新的版本试试呢？gf的单元测试有data race的测试的。

**Comment by zhangHongBo21** [comment]
@gqcn 经过几天的测试 还是一样会出现 偶发性死锁

**Comment by gqcn** [comment]
> @gqcn 经过几天的测试 还是一样会出现 偶发性死锁

最新的版本也会有这样的问题么？我反复仔细看了几遍你的代码，似乎没什么毛病。要不你自己写个`benchmark`测试加上`-race`选项测试下？`gf`的所有模块都经过数据竞争测试的。

**Comment by zhangHongBo21** [comment]
`func TcpClient() {
	data := new(event)

	for {
		//订阅redis队列中数据，空数据情况下最长等待十分钟
		
		memeberList.RLockFunc(func(m map[interface{}]interface{}) {
			for user := range m {
				w, ok := user.(*ghttp.WebSocket)
				if ok {
					err := w.WriteMessage(ghttp.WS_MSG_TEXT, returnDatastr)
					if err != nil {
						glog.Notice(w.RemoteAddr(), "断开链接")
						err = w.Close()
						if err != nil {
							panic(err)
						}
						memeberList.Remove(w)
					}
				}
			}
		})
		
	}
}
`

**Comment by zhangHongBo21** [comment]
@gqcn 上面补充了一个伪代码，主要是有个死循环在不断的广播数据

**Comment by gqcn** [comment]
@zhangHongBo21 你在锁函数里面使用锁，就会死锁了：

**Comment by zhangHongBo21** [comment]
那个是我病急乱投医瞎写的，最原版的代码rlockfunc里面是没有remove的，我是照着大神你出的那个demo写的remove然后会出现死锁，我大概猜测了一下是有并发进入了gmap的set，然后凑巧有链接断开失效了，跳出WsHandler中的死循环并准备移除map中的链接时候 底下的rlockfunc也在抢锁，三个锁抢占导致死锁了

**Comment by zhangHongBo21** [comment]
@gqcn 最终我解决了死锁的问题，是我代码逻辑的问题
