### ISSUE TITLE
SQLite 数据库数据插入的时候，如果设置了自增加ID，就会插入失败

### ISSUE THREAD

**Issue by xinjiayu** [gogf/gf#903]
从 SQLite 的 2.3.4 版本开始，如果将一个表中的一个字段声明为 INTEGER PRIMARY KEY，那么只需向该表的该字段插入一个 NULL 值，这个 NULL 值将自动被更换为比表中该字段所有行的最大值大 1 的整数；如果表为空，那么将被更换为 1。

而通过gf代码生成工具生成model的时候，会把设置的自增长ID也会放到实体声明的结构体里。基于实体对象进行提交的时会就会报错。

**Comment by sanrentai** [comment]
sqlserver 也有同样的问题，遇到自增列，基于实体对象进行提交的时报错

**Comment by gqcn** [comment]
@xinjiayu 不好意思，这个issue我才看到，能否把你的`sqlite`生成表结构给我试试，如果可以的话，你也可以直接给`gf-cli`提交PR，应该进行简单的判断即可。

**Comment by gqcn** [comment]
@sanrentai 能否提交一个简单的复现问题的代码？你也可以直接联系我的微信 389961817 ，我可以在线协助你解决问题。如果可以的话，也欢迎你直接提供PR。
