### ISSUE TITLE
gcache的限制数量

### ISSUE THREAD

**Issue by 15951836388** [gogf/gf#904]
HeroCache          = gcache.New(100)

一直add，HeroCache          的数量会超过100

可以 强制不能超过设定数量吗？

数量超过，就删掉快到期的，保持数量

**Comment by gqcn** [comment]
@15951836388 `gcache`的`LRU`实现并不是严格的，因为严格去检查的话就会影响性能，而是采用的每秒定时异步检查清理的方式。

**Comment by 15951836388** [comment]
每秒检查没问题。但实际使用时发现，数量长期在限制数量以外

**Comment by gqcn** [comment]
> 每秒检查没问题。但实际使用时发现，数量长期在限制数量以外

只要数量在降低就是正常的，但是如果数量增长得太快，使得内存不断增长无法稳定就是有问题的。
