### ISSUE TITLE
gf-cli可否支持驼峰法json配置

### ISSUE THREAD

**Issue by ddpmz** [gogf/gf#905]
比如我数据库是delete_at,但是我api接口想要得到deleteAt
```
type Entity struct {
    DeleteAt  *gtime.Time `orm:"delete_at"  json:"deleteAt"`  // 删除时间  
}
```
gf-cli的代码在：https://github.com/gogf/gf-cli/blob/master/commands/gen/gen_model.go#L258

**Comment by gqcn** [comment]
@renfan 原本这么设计的目的是为了统一返回的数据结构风格，所以是没有提供这种书写风格的选项的，如果感兴趣可以提供PR，其他同学感兴趣也可以提供PR，我自己的话应该不会去实现它。
