### ISSUE TITLE
[BUG] gconv.String( type WrapStringType string) fail

### ISSUE THREAD

**Issue by RelicOfTesla** [gogf/gf#907]
```go
	type WrapString string
	wrapStr := WrapString("aa")
	vPtr := interface{}(wrapStr)
	fmt.Println(`{`+gconv.String(vPtr)+"}", gconv.String(vPtr) == "aa")  // false...
	v := reflect.ValueOf(vPtr)
	fmt.Println(v.Kind(), v)

```

**Comment by gqcn** [comment]
@RelicOfTesla That is, type `WrapString` is a custom type, which is different from type `string`. The `gconv.String(vPtr)` returns `"aa"` not `aa`, so `gconv.String(vPtr) == "aa"` is false. You can use type alias to make your custom type `WrapString` equals to type `string` like follows:
```go
package main

import (
	"fmt"
	"github.com/gogf/gf/util/gconv"
	"reflect"
)

func main() {
	type WrapString = string
	wrapStr := WrapString("aa")
	vPtr := interface{}(wrapStr)
	fmt.Println(`{`+gconv.String(vPtr)+"}", gconv.String(vPtr) == "aa") // false...
	v := reflect.ValueOf(vPtr)
	fmt.Println(v.Kind(), v)
}
```

**Comment by RelicOfTesla** [comment]
.Kind() == reflect.String..... please try convert to raw string...don't use json string..

**Comment by gqcn** [comment]
@RelicOfTesla OK, I do did some improvement for string type converting for function `gconv.String`, please use the latest master branch of `gf` and have another try.
