### ISSUE TITLE
希望可以加一个模板继承的功能

### ISSUE THREAD

**Issue by develop1024** [gogf/gf#909]

**Comment by gqcn** [comment]
@develop1024 具体一点呢？

**Comment by develop1024** [comment]
![image](https://user-images.githubusercontent.com/52775415/93854599-a0496c00-fce8-11ea-99d2-a086946d131a.png)

这是原生的go实现模板继承的方式。


目前goframe的支持的是在模板中引入其它模板文件，但是有些需求无法满足，
问题一：比如一个视图函数返回的一个a.html模板，a模板中的某一个区域是通过template引入的b.html中define语句块
那么如果我b.html语句块中有写变量需要渲染目前是渲染不出来的

问题二：目前的引入其它模板文件来实现代码复用，比如说我有些公共区域，不如导航栏，菜单栏，底部区域，页面很多的话每个页面都需要去引入这些板块

希望添加模板继承功能， 写成类似与Django, flask等框架的模板继承方式，那样会很好用，我也会爱死这个框架，虽然现在项目都是前后端分离了，模板这块被轻视了，但是我们搞后端的通常管理后台都是由自己去写，希望添加这么一个功能，感激不尽

**Comment by develop1024** [comment]
![image](https://user-images.githubusercontent.com/52775415/93856400-8fe6c080-fceb-11ea-8462-d5d3585e0f92.png)

目前我是用go原生这块来写继承的

**Comment by gqcn** [comment]
@develop1024 模板分离/嵌套以及不同子模板间传递模板变量当然都是支持的，文档地址：https://goframe.org/os/gview/layout
