### ISSUE TITLE
ORM字段获取和设置

### ISSUE THREAD

**Issue by zuozhehao** [gogf/gf#910]
ORM在存和取能对字段进行处理不。

比如IP 、时间存入的时候字段转换为整型，取出转换为字符串。

**Comment by gqcn** [comment]
@zuozhehao 存入时根据数据表类型自动转换的，取出的时候转为了`gdb.value`类型，可以随意转换类型。

**Comment by zuozhehao** [comment]
> @zuozhehao 存入时根据数据表类型自动转换的，取出的时候转为了`gdb.value`类型，可以随意转换类型。

`gdb.value`类型，可以随意转换类型，这个很赞。

如果能在模型上设置某个字段的处理函数，那就更好了。

特别是列表数据的时候，如果在视图遍历过程中处理，有多个页面就感觉比较繁琐。

**Comment by gqcn** [comment]
> > @zuozhehao 存入时根据数据表类型自动转换的，取出的时候转为了`gdb.value`类型，可以随意转换类型。
> 
> `gdb.value`类型，可以随意转换类型这个很赞。
> 
> 如果能在模型上设置某个字段的处理函数，那就更好了。
> 
> 特别是列表数据的时候，如果在视图遍历过程中处理，有多个页面就感觉比较繁琐。

针对列表中特定字段的类型转换，我没想到好的改进方案，你如果有比较好的建议，欢迎讨论
