### ISSUE TITLE
数据库ORM这个模块能否可以单独使用？

### ISSUE THREAD

**Issue by xuelabi123** [gogf/gf#911]
想在其他框架下使用ORM这个模块，我该如何导入？谢谢

**Comment by gqcn** [comment]
@xuelabi123 你好，当然是可以的。`gf`是模块化设计的，除了`g`模块之外，其他模块都可以选择性引入。由于`Golang`是静态编译型语言，你用到什么模块或者什么方法，才会在编译的时候自动连接这些内容到你的二进制文件中。只不过在`go.mod`里面你需要下载整个`gf`框架的内容。

**Comment by xuelabi123** [comment]
ok，🙏
