### ISSUE TITLE
SHOW FULL COLUMNS FROM ...will be error

### ISSUE THREAD

**Issue by RAGGA-TIME** [gogf/gf#912]
```
SELECT a.login as acc_id, a.credit, ifnull(b.profit, 0) as profit, ifnull(c.in_amt,0) as in_amt, ifnull(d.out_amt, 0) as out_amt FROM `tb_userrecord` a LEFT JOIN (select sum(profit) as profit,`login`,`cmd` from tb_2020 where cmd<=1 group by login) b ON (b.login=a.login) LEFT JOIN (select sum(profit) as in_amt,`login`,`cmd` from tb_2020 where cmd=6 and profit > 0 group by login) c ON (c.login=a.login) LEFT JOIN (select sum(profit) as out_amt,`login`,`cmd` from tb_2020 where cmd=6 and profit < 0 group by login) d ON (d.login=a.login) WHERE a.login=123456788 LIMIT 1
```
when i select this sql use by gdb.Will report an error
```
[default] SHOW FULL COLUMNS FROM (select
Error: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(select' at line 1
Stack:
```
The result can be returned normally，But 8 to 10 records will be error
```go
table := "tb_userrecord a"
	field := `a.login as acc_id, a.credit, ifnull(b.profit, 0) as profit, 
	ifnull(c.in_amt,0) as in_amt, ifnull(d.out_amt, 0) as out_amt`
	where := g.Map{}
	where["a.login"] = params.AccId
	rs, err := g.DB().Table(table).Fields(field).
	LeftJoin("(select sum(profit) as profit, login, cmd from tb_2020 where cmd<=1 group by login) b", "b.login=a.login").
	LeftJoin("(select sum(profit) as in_amt, login, cmd from tb_2020 where cmd=6 and profit > 0 group by login) c", "c.login=a.login").
	LeftJoin("(select sum(profit) as out_amt, login, cmd from tb_2020 where cmd=6 and profit < 0 group by login) d", "d.login=a.login").
	Where(where).FindOne()
	if err != nil {
		return nil, err
	}
	return rs, nil
```
this is my code
Help solve the trouble. Thank You！！！

**Comment by gqcn** [comment]
@RAGGA-TIME The SQL is .. a little bit complicated using ORM chaining operations. Try using `g.DB().Query(xxx)` or `g.DB().GetOne(xxx)` instead.

**Comment by RAGGA-TIME** [comment]
> @RAGGA-TIME The SQL is .. a little bit complicated using ORM chaining operations. Try using `g.DB().Query(xxx)` or `g.DB().GetOne(xxx)` instead.

gf release v1.13.1

SELECT a.*, b.score, b.subjects FROM `user_mstr` a 
INNER JOIN (
select sum(x.score) as score,`x`.`subjects` as subjects,`x`.`u_id` as u_id from user_score as x where x.subjects = '语文' group by x.u_id
) b ON (b.u_id = a.u_id)

this sql i wanna use ORM operations to select but will be error like this
 [DEBU] [163 ms] SHOW FULL COLUMNS FROM `user_mstr`
2020-09-23 10:33:46.135 [ERRO] [ 41 ms] SHOW FULL COLUMNS FROM (select
Error: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(select' at line 1

it just SHOW FULL COLUMNS will be error
result can be returned normally
i think use left join / inner join encounter parentheses they will be SHOW FULL COLUMNS

It would be best if can solve this error~ Thank you
