### ISSUE TITLE
springboot have context-path in config file,how to set this  in gf?

### ISSUE THREAD

**Issue by wghdir** [gogf/gf#917]
springboot have context-path in config file,how to set this  in gf?

**Comment by gqcn** [comment]
@wghdir Please give more details about `context-path`?

**Comment by wghdir** [comment]
application.yml
server:
  port: 8081
  context-path: /YzmSvr

all the api in this application must access with YzmSvr,i see like  application name.
if the server have a api info.do
you can access http://127.0.0.1:8081/YzmSvr/info.do
how to easy implement,thanks

**Comment by wenzi1** [comment]
这不是组路由就可以实现么

**Comment by gqcn** [comment]
> application.yml
> server:
> port: 8081
> context-path: /YzmSvr
> 
> all the api in this application must access with YzmSvr,i see like application name.
> if the server have a api info.do
> you can access http://127.0.0.1:8081/YzmSvr/info.do
> how to easy implement,thanks

You mean router group? Like:
```go
package main

import (
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/net/ghttp"
)

func main() {
	s := g.Server()
	s.Group("/YzmSvr", func(group *ghttp.RouterGroup) {
		group.ALL("/info.do", func(r *ghttp.Request) {
			r.Response.Write("hello world")
		})
	})
	s.SetPort(8199)
	s.Run()
}
```

**Comment by LonelySally** [comment]
> > application.yml
> > server:
> > port: 8081
> > context-path: /YzmSvr
> > all the api in this application must access with YzmSvr,i see like application name.
> > if the server have a api info.do
> > you can access http://127.0.0.1:8081/YzmSvr/info.do
> > how to easy implement,thanks
> 
> You mean router group? Like:
> 
> ```go
> package main
> 
> import (
> 	"github.com/gogf/gf/frame/g"
> 	"github.com/gogf/gf/net/ghttp"
> )
> 
> func main() {
> 	s := g.Server()
> 	s.Group("/YzmSvr", func(group *ghttp.RouterGroup) {
> 		group.ALL("/info.do", func(r *ghttp.Request) {
> 			r.Response.Write("hello world")
> 		})
> 	})
> 	s.SetPort(8199)
> 	s.Run()
> }
> ```

其实就是全局路由前缀.跟分组稍微有点区别,是对全局的路由都生效的一种配置.应该是要通过handle去实现.
