### ISSUE TITLE
How to get custom rule's attribute

### ISSUE THREAD

**Issue by Insua** [gogf/gf#922]
Custom rule has been released,that's great! So I make one rule named foo:bar,In rule xxx foo I want to get bar's value.
How to get it?

**Comment by gqcn** [comment]
@Insua The validation function type is defined as:
```go
// RuleFunc is the custom function for data validation.
// The parameter <value> specifies the value for this rule to validate.
// The parameter <message> specifies the custom error message or configured i18n message for this rule.
// The parameter <params> specifies all the parameters that needs. You can ignore parameter <params> if
// you do not really need it in your custom validation rule.
type RuleFunc func(value interface{}, message string, params map[string]interface{}) error
```
The parameter `value` specifies the value for this rule to validate.

**Comment by Insua** [comment]
the value I dump is this param which I input, but I want to get the rule name with attribute
for example I register one rule named foo then I pass the rule name with attribute as foo:bar,so I want to get bar attribute,how can

**Comment by gqcn** [comment]
> the value I dump is this param which I input, but I want to get the rule name with attribute
> for example I register one rule named foo then I pass the rule name with attribute as foo:bar,so I want to get bar attribute,how can

Well, it is not supported, let me improve this later.

**Comment by gqcn** [comment]
@Insua Done: https://goframe.org/util/gvalid/customrule
