### ISSUE TITLE
db.Query 的一个bug

### ISSUE THREAD

**Issue by mir355** [gogf/gf#923]
* 版本 1.13.7
* 场景：
执行db.Query 返回 rows 类型结果，
* 描述：

我使用db.Query方法执行sql
```go
rows, err := db.Query(sql,args)
```

我的sql语句在mysql中可执行，但经过db.Query调用就报错了，查下看源码发现db.Query方法中有如下两句

```go
sql, args = formatSql(sql, args)  
sql, args = c.DB.HandleSqlBeforeCommit(link, sql, args)
```

猜测是其中一句把sql语句格式搞乱了，我跳过这两句，用如下方法可以执行成功

```go
link, err := db.Slave()
rows, err := link.Query(sql,ags)
```

**Comment by gqcn** [comment]
@mir355 麻烦提供一下可复现问题的代码呢，我本地运行试试。

**Comment by mir355** [comment]
我的sql语句是从外部sql文件中读取的，我测试问题是在方法 formatSql(sql, args)中的如下两句，去掉这两句就可以执行了
```
        sql = gstr.Replace(sql, "\n", " ")
	sql, _ = gregex.ReplaceString(`\s{2,}`, ` `, sql)
```
我的sql文件中会有换行符及sql注释标识。
非常感谢你的及时回复，祝gf成为最流行的Go 框架。

**Comment by gqcn** [comment]
> 我的sql语句是从外部sql文件中读取的，我测试问题是在方法 formatSql(sql, args)中的如下两句，去掉这两句就可以执行了
> 
> ```
>         sql = gstr.Replace(sql, "\n", " ")
> 	sql, _ = gregex.ReplaceString(`\s{2,}`, ` `, sql)
> ```
> 
> 我的sql文件中会有换行符及sql注释标识。
> 非常感谢你的及时回复，祝gf成为最流行的Go 框架。

I see..确实有这样的问题，我已在master分支上去掉了，感谢反馈。
