### ISSUE TITLE
how to set request validation's i18n language in current request (如何在当前请求中设置请求校验的报错信息的i18n语言)

### ISSUE THREAD

**Issue by icecreamlee** [gogf/gf#926]
gf version: v1.13.1

request validation is use defaultManager.Translate(), can't change i18n language without affecting other requests. how to do that?
看源码中请求校验用的是 defaultManager.Translate()，无法做到动态更改i18n语言而不影响其他的请求。有什么办法可以解决此问题？

**Comment by gqcn** [comment]
@icecreamlee Well, you may retrieve the i18n content using `g.I18n().GetContent`, and then do the validation using custom error message passed from `Check*` functions.
