### ISSUE TITLE
Server need provide interface to get Port(s) it's listening

### ISSUE THREAD

**Issue by forrestjgq** [gogf/gf#927]
### 1. What version of `Go` and system type/arch are you using?

go version go1.15.2 linux/amd64

### 2. What version of `GoFrame` are you using?

v1.13.2

### 3. Can this issue be reproduced with the latest release?
yes

### 4. What did you do?

s := g.Server()
s.SetPort(0)
s.Run()

### 5. What did you expect to see?
When SetPort(0) is called, system will assign a port for Server and I expect that:
1. interface could be provided by Server to get port(s) it's listening, including a random port
2. route list printed after server running should correctly print port(s)

Reason:
- It's very useful while I run multiple unit test in parallel and each starts a server.
- If 0 is set, I don't know which port is currently in use.
- If a specified port is set, binding failure will be thrown.

So I must mannually specify each test a single, unique port, which I can't be sure that that port is not taken by system in any time on any machine.

### 6. What did you see instead?
I can't get listening port while SetPort(0)

**Comment by gqcn** [comment]
@forrestjgq It is..useful indeed. I wrote unit testing cases by specifying certain random port to the server as well, and I happened facing the issue you're now facing. But I do not think this improvement is urgent, so I wish someone can commit a PR to do this.
