### ISSUE TITLE
[BUG] ghttp.Request.Parse() 不能校验 int类型 require

### ISSUE THREAD

**Issue by orchie** [gogf/gf#929]
### 2. What version of `GoFrame` are you using?

gf -v
GoFrame CLI Tool v0.7.7, https://goframe.org
Install Path: D:\gopath\bin\gf.exe
Build Detail:
  Go Version:  go1.13.4
  GF Version:  v1.13.1
  Git Commit:  1db1828b35c15b4a92cd144c33e636eb52d7ec07
  Build Time:  2020-06-14 21:01:20

### 4. What did you do?

```
type DeleteWorkerData struct {
	ID     int    `v:"required"`
	UserID string `v:"required" json:"user_id"`
}
func Delete(r *ghttp.Request) {
	var err error
	var data *DeleteWorkerData
	if err = r.Parse(&data); err != nil {
		response.JsonExit(r, 1, err.Error())
	}
}
```

### 6. What did you see instead?
int类型的 require校验无效 ,string的有效.

**Comment by zhengchalei** [comment]
go语言默认情况下 int 是为0 
所以我一般判断 min:1

不知道有没有其他的好的办法

**Comment by bohea** [comment]
如果取值可以是0的话， 用min:1就不行了 @zhengchalei

**Comment by fulltimelove** [comment]
可以用指针   #699        https://github.com/gogf/gf/issues/699#issuecomment-657596205

**Comment by gqcn** [comment]
@orchie @fulltimelove Yep, only pointer attribute can work for you.
