### ISSUE TITLE
（403）自定义配置和框架默认配置冲突 

### ISSUE THREAD

**Issue by TeaR7** [gogf/gf#930]
### 1. What version of `Go` and system type/arch are you using?

go version go1.13.6 windows/amd64

### 2. What version of `GoFrame` are you using?

github.com/gogf/gf v1.13.7

### 3. Can this issue be reproduced with the latest release?

yes

### 4. What did you do?

``` golang
	s.BindStatusHandler(403, func(r *ghttp.Request) {
		Result.Common(r, 403, "禁止访问！", false, nil)
               // just output a json response like {code:403,msg:"禁止访问",success:false}
	})
```

### 5. What did you expect to see?

``` json
{"code":403,"message":"禁止访问","data":null,"success":false,"timestamp":1601454222699}
```

### 6. What did you see instead?

```json
Forbiden{"code":403,"message":"禁止访问","data":null,"success":false,"timestamp":1601454222699}
```

###  recommend

希望默认配置可以有地方配置，用来去除。或者是通过接口调用，可以让用户覆盖其实现

**Comment by gqcn** [comment]
@TeaR7 Use `r.Response.ClearBuffer()` in your custom HTTP-Status callback function to clear the output buffer content that is already wrote by the request handler.
