### ISSUE TITLE
自定义全局异常处理和默认处理冲突

### ISSUE THREAD

**Issue by TeaR7** [gogf/gf#931]
### 1. What version of `Go` and system type/arch are you using?

go version go1.13.6 windows/amd64

### 2. What version of `GoFrame` are you using?

github.com/gogf/gf v1.13.7

### 3. Can this issue be reproduced with the latest release?

yes

### 4. What did you do?

``` golang
//注册如下中间件
func GlobalErrorMiddleware(r *ghttp.Request) {
	defer func() {
                // 全局异常处理，允许开发者抛出异常，以指定的统一格式返回给前端
		if err := recover(); err != nil {
			info, _ := gjson.New(err).ToJsonString()
			Result.Common(r, 500, info, false, nil)
		}
	}()
	r.Middleware.Next()
}

调用如下接口
// @summary 测试接口
// @tags    测试
// @produce json
// @Router  /test/hello [GET]
// @success 200 {nil} Http.JsonResponse "执行结果"
func Hello(r *ghttp.Request) {
	panic("我是一个异常！")
	Result.OkMsg(r, "Hello GF")
}
```

### 5. What did you expect to see?

{"code":500,"message":"我是一个异常！","data":null,"success":false,"timestamp":1601454222699}

### 6. What did you see instead?

我是一个异常！

###  recommend

看起来是因为 gogf/gf@v1.13.7/net/ghttp/ghttp_func.go:56 niceCallFunc 已经帮我们捕获了这个异常，但是实际上走到我们的自己的全局异常处理中间件时，已经没有异常可以捕获了，因此不触发我们自己的全局异常

希望处理方法
1.允许用户使用自己的全局异常处理
2.将默认的全局异常处理最先注册，这样执行顺序（由于defer倒序）就会变成先经过用户自定义的所有中间件，然后如果还有未处理异常，才由框架接手

**Comment by gqcn** [comment]
@TeaR7 Please refer to document: https://goframe.org/net/ghttp/error
