### ISSUE TITLE
REST标准下，GF对返回值的自动处理异常

### ISSUE THREAD

**Issue by TeaR7** [gogf/gf#932]
1. What version of Go and system type/arch are you using?
go version go1.13.6 windows/amd64

2. What version of GoFrame are you using?
github.com/gogf/gf v1.13.7

3. Can this issue be reproduced with the latest release?
yes

### 4. What did you do?

在严格REST标准下，我们实现接口如下，

若业务异常，HTTPCODE设置为500（r.Response.WriteStatus(500)）
若数据库资源找不到，HTTPCODE设置为404（r.Response.WriteStatus(404)）

并返回标准JSON，告知原因

```golang
r.Response.WriteJson(JsonResponse{
		Code:      500,
		Message:   "当前资源获取异常",
		Result:    nil,
		Success:   false,
		Timestamp: time.Now().UnixNano() / 1e6,
	})
```

### 5. What did you expect to see?

```json
{"code":500,"message":"当前资源获取异常！","data":null,"success":false,"timestamp":1601477483020}
```

### 6. What did you see instead?

```json
Internal Server Error{"code":500,"message":当前资源获取异常！","data":null,"success":false,"timestamp":1601477483020}
```

**Comment by TeaR7** [comment]
找了找……惊讶的发现处理的地方好像是同一个地方= =。

如果简便处理的话，是否添加一个配置，例如，自动异常处理：默认开启（不过这样不是很合适，最好的方式是能自动检测，兼容这些……）

**Comment by gqcn** [comment]
@TeaR7 Is this same as https://github.com/gogf/gf/issues/930 ?
