### ISSUE TITLE
按照gf-demos的代码跑路由分组 报路由分组已经存在

### ISSUE THREAD

**Issue by sjfxy** [gogf/gf#933]
按照gf-demos的代码跑路由分组 报路由分组已经存在
### 1. What version of `Go` and system type/arch are you using?
 go1.13.8 windows/amd64

go version go1.13.8 windows/amd64

### 2. What version of `GoFrame` are you using?
Build Detail:
  Go Version:  go1.14
  GF Version:  v1.13.6
  Git Commit:  7e48c36f43a0a35724d4b77f653b02d6e82b2856
  Build Time:  2020-09-22 20:58:40

### 4. What did you do?
 ```go
s.Group("/", func(group *ghttp.RouterGroup) {
		ctlUser := new(user.Controller)
		ctlChat := new(chat.Controller)
		//group.Middleware() 使用中间件
		group.Middleware(middleware.CORS)
		group.ALL("/user", ctlUser)
		group.ALL("/chat", ctlChat)
		group.Group("/", func(group *ghttp.RouterGroup) {
			group.Middleware(middleware.Auth)
			group.ALL("/user/profile", ctlUser, "Profile")
		})
```

### 5. What did you expect to see?
服务正常启动

### 6. What did you see instead?
```
 duplicated route registry "ALL:/user/profile" at E:/gopcp/example.v2/src/gf/router/router.go:39 , already registered at E:/gopcp/example.v2/src
/gf/router/router.go:35
```

**Comment by gqcn** [comment]
@sjfxy There's a configuration item `RouteOverWrite` of `Server`: https://github.com/gogf/gf-demos/blob/9e8d8c6ba74f38bf1634e1f04a2cbe7ac751b68e/config/config.example.toml#L8 Did you miss it in your `config.toml`?

**Comment by sjfxy** [comment]
OK Thanks you much Gf GIN is the most comfortable gf GIN I use no matter the code habits or style is very good


I hope the author will continue to promote and I am using gf's library. I like it very much. Thank you






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "John Guo"<notifications@github.com&gt;; 
发送时间: 2020年10月11日(星期天) 晚上8:53
收件人: "gogf/gf"<gf@noreply.github.com&gt;; 
抄送: "神秘人物"<986244259@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [gogf/gf] 按照gf-demos的代码跑路由分组 报路由分组已经存在 (#933)





 
@sjfxy There's a configuration item RouteOverWrite of Server: https://github.com/gogf/gf-demos/blob/9e8d8c6ba74f38bf1634e1f04a2cbe7ac751b68e/config/config.example.toml#L8 Did you miss it in your config.toml?

**Comment by sjfxy** [comment]
is good
