### ISSUE TITLE
gtcp的NewServer 建议增加keep-alive设置项

### ISSUE THREAD

**Issue by macnie** [gogf/gf#937]
go 的默认keep-alive为15秒。目前gf的gtcp 的 服务端和客户端没有办法设置keep-alive。

建议增加设置项。

**Comment by gqcn** [comment]
@macnie 标准库好像不支持的，可以通过一些第三方的包实现创建支持自定义设置`TCP OPTION`的`net.Conn`接口对象，然后通过`gtcp.NewConnByNetConn`方法接入到`gtcp`包进行管理。另外，`heartbeat`不香吗？

**Comment by macnie** [comment]
go 的标准库是支持的。我已经实现了。是用标准库实现的。建议gtcp也增加一下自定义的功能。gtcp会更强大一些。

```go
l := net.ListenConfig{
		Control:   nil,
		KeepAlive: 4 * time.Hour,
	}
	s, err := l.Listen(context.Background(), "tcp", p.Host+":"+p.Port)
	if err != nil {
		glog.Error(err)
	}
	// Listening loop.
	for {
		if orgConn, err := s.Accept(); err != nil {
			glog.Error(err)
			break
		} else if orgConn != nil {
			go func() {
				c := gtcp.NewConnByNetConn(orgConn)
}()
}
}

**Comment by gqcn** [comment]
@macnie 好的，我先排期一下，优先期望能有小伙伴提供PR。

**Comment by mark-jiang-gp** [comment]
没什么用吧.keep-alive除非客户端服务器是直连 真的有认这样吗,浪费开发的工期
