### ISSUE TITLE
session.setId doesn't work properly

### ISSUE THREAD

**Issue by dhunter13** [gogf/gf#940]
### 1. What version of `Go` and system type/arch are you using?
go 1.15.2

### 2. What version of `GoFrame` are you using?
1.13.7

### 3. Can this issue be reproduced with the latest release?
yes

### 4. What did you do?
        r.Session.SetId("afjsdfjksdlfjsdlfj")
	r.Session.Set("time", "abc")
	g.Dump(r.Session.Id())

### 5. What did you expect to see?

session id set as i want

### 6. What did you see instead?

session id value appear not the setted value

**Comment by gqcn** [comment]
@dhunter13 Please update and use the `master` branch codes and have a try again.
