### ISSUE TITLE
cookie generated by session could not be removed with middleware or hook

### ISSUE THREAD

**Issue by dhunter13** [gogf/gf#942]
### 1. What version of `Go` and system type/arch are you using?
1.15.2

### 2. What version of `GoFrame` are you using?
1.13.7

### 4. What did you do?
use middleware or hook remove cookie generated by session,  like 

s.BindHookHandlerByMap("/auth", map[string]ghttp.HandlerFunc{
		ghttp.HOOK_BEFORE_OUTPUT: func(r *ghttp.Request) {
			r.Cookie.Remove("mall-token")
		},
	})

### 5. What did you expect to see?

cookie is removed

### 6. What did you see instead?
cookie still send to client

**Comment by gqcn** [comment]
@dhunter13 Update and use the `master` branch of `gf`, there added a configuration `SessionCookieOutput` for ghttp.Server which is used for controlling whether outputting session id to cookie.
