### ISSUE TITLE
[P0]两点建议,大大有空看到请回复下

### ISSUE THREAD

**Issue by LonelySally** [gogf/gf#945]
1.关于g.Db,当sql的debug开启时会输出一条条sql日志,目前是这样的
~~~ 
[ 12 ms] [default] SHOW FULL COLUMNS FROM `users_source 
~~~
希望能在链式操作上开放一个接口手动设置一个unique.让其输出变成
~~~ 
[ 12 ms] [uniquestr] SHOW FULL COLUMNS FROM `users_source` 
//伪代码:
db.Table(table).SetUniqueStr(guid.S()).One()
~~~
基本每次http请求都会对上下文设置一个workid,让sql日志也实现关联.
2.关于gvalidate.go语言的特性会对数值类型自动设置默认值0,直接导致了required的验证失效,对于数值类型的required验证希望能做成对入参的has+empty+类型验证.例如对如下的money字段验证
~~~
例1:?money=1&uid=1//`p:"money" v:"required " 通过
例2:?uid=1//`p:"money" v:"required " 不通过
例3:?money=&uid=1//`p:"money" v:"required " 不通过
~~~

**Comment by gqcn** [comment]
@LonelySally 第一点建议很不错，后续可以加上`Context`上下文的支持，其实内置的`logger`已经支持了的，只是需要增加上下文变量输入即可，so easy。第二点的话建议使用`min:1`这样的规则来校验数值类型的必需。

**Comment by LonelySally** [comment]
> @LonelySally 第一点建议很不错，后续可以加上`Context`上下文的支持，其实内置的`logger`已经支持了的（配置文件也支持上下文配置，请参考：https://goframe.org/os/glog/context ），只是需要增加上下文变量输入即可，可以增加一个`Ctx`链式方法，so easy。第二点的话建议使用`min:1`这样的规则来校验数值类型的必需。

被默认值0分割的区域是有两块部分,用`min:1`的判断是片面的,要考虑负数因素在里面.
还有一个是关于ORM的Save方法的问题,ON DUPLICATE KEY UPDATE分前半组和后半组,现在产生的sql两组的VALUES是一致的,如何做到字段差异,假设状态(Status),不存在则插入(Status=1 这个可以走默认值)存在则更新为多状态情况(Status=2甚至3 4....).直白点说就是Insert与Update的字段数不对等情况该如何处理,目前还是手写sql...

**Comment by LonelySally** [comment]
还有一个关于ORM的Save问题.当ON DUPLICATE KEY UPDATE 前后数据一样样时该怎么处理.目前还是手写.伪代码如下情况
~~~
INSERT INTO `users_source`(`id`,`source`,`users_id`,`status`) VALUES(20,'user_tenant','4','1') ON DUPLICATE KEY UPDATE `status`=2
~~~

**Comment by LonelySally** [comment]
> @LonelySally 第一点建议很不错，后续可以加上`Context`上下文的支持，其实内置的`logger`已经支持了的（配置文件也支持上下文配置，请参考：https://goframe.org/os/glog/context ），只是需要增加上下文变量输入即可，可以增加一个`Ctx`链式方法，so easy。第二点的话建议使用`min:1`这样的规则来校验数值类型的必需。

sql日志的关键点其实还是在于跟request关联起来.实际开发中能让后置中间件中获取到本次*ghttp.Request的相关sql记录才是最理想化的.这样能组成request+sql+response为一体的关联日志.

**Comment by LonelySally** [comment]
![image](https://user-images.githubusercontent.com/26945597/96087789-0182ea80-0ef7-11eb-86af-19b7dbd43a4c.png)
类似这样的输出结果.啰嗦了这么多,希望别嫌烦.

**Comment by gqcn** [comment]
> > @LonelySally 第一点建议很不错，后续可以加上`Context`上下文的支持，其实内置的`logger`已经支持了的（配置文件也支持上下文配置，请参考：https://goframe.org/os/glog/context ），只是需要增加上下文变量输入即可，可以增加一个`Ctx`链式方法，so easy。第二点的话建议使用`min:1`这样的规则来校验数值类型的必需。
> 
> 被默认值0分割的区域是有两块部分,用`min:1`的判断是片面的,要考虑负数因素在里面.

那你使用指针属性吧。

**Comment by gqcn** [comment]
> 还有一个关于ORM的Save问题.当ON DUPLICATE KEY UPDATE 前后两组数据不一样时该怎么处理.目前还是手写.伪代码如下情况
> 
> ```
> INSERT INTO `users_source`(`id`,`source`,`users_id`,`status`) VALUES(20,'user_tenant','4','1') ON DUPLICATE KEY UPDATE `status`=2
> ```
> 
> 是否应该改成
> 
> ```
> g.Table(table).Data(insertData).Save(updateData)
> ```

`Save`方法会覆盖前面的。

**Comment by gqcn** [comment]
> > @LonelySally 第一点建议很不错，后续可以加上`Context`上下文的支持，其实内置的`logger`已经支持了的（配置文件也支持上下文配置，请参考：https://goframe.org/os/glog/context ），只是需要增加上下文变量输入即可，可以增加一个`Ctx`链式方法，so easy。第二点的话建议使用`min:1`这样的规则来校验数值类型的必需。
> 
> sql日志的关键点其实还是在于跟request关联起来.实际开发中能让后置中间件中获取到本次*ghttp.Request的相关sql记录才是最理想化的.这样能组成request+sql+response为一体的关联日志.

`Request`对象有个`GetCtx`方法用于获取标准化的上下文对象，随后将此对象在方法间传递，这个也是`Golang`标准的上下文参数传递方式。

**Comment by LonelySally** [comment]
> > > @LonelySally 第一点建议很不错，后续可以加上`Context`上下文的支持，其实内置的`logger`已经支持了的（配置文件也支持上下文配置，请参考：https://goframe.org/os/glog/context ），只是需要增加上下文变量输入即可，可以增加一个`Ctx`链式方法，so easy。第二点的话建议使用`min:1`这样的规则来校验数值类型的必需。
> > 
> > 
> > 被默认值0分割的区域是有两块部分,用`min:1`的判断是片面的,要考虑负数因素在里面.
> 
> 那你使用指针属性吧。试试看。

目前我是把他们先当做string去接收做required验证,之后在判断类型,最后gconv转成想要的数据类型.就像列子里写的money,它也可以是负数那么`min:1`显然是不成立的.

**Comment by LonelySally** [comment]
> > 还有一个关于ORM的Save问题.当ON DUPLICATE KEY UPDATE 前后两组数据不一样时该怎么处理.目前还是手写.伪代码如下情况
> > ```
> > INSERT INTO `users_source`(`id`,`source`,`users_id`,`status`) VALUES(20,'user_tenant','4','1') ON DUPLICATE KEY UPDATE `status`=2
> > ```
> > 
> > 
> > 是否应该改成
> > ```
> > g.Table(table).Data(insertData).Save(updateData)
> > ```
> 
> `Save`方法参数会覆盖前面的`Data`方法参数。

对的,所以并不能实现业务场景中最常用的实现.假设代码如下:
users_id,id,source三者唯一
~~~
g.Table(table).Data(g.Map{
			"users_id": uid
			"id":       unique,
			"source":   source,
                        "status":1,
		}).Save(g.Map{"status":2,})
~~~
生成的sql应该是这种新式(不存在status设置为1,存在更新为2)
~~~
INSERT INTO `users_source`(`id`,`source`,`users_id`,`status`) VALUES(20,'user_tenant','4','1') ON DUPLICATE KEY UPDATE `status`=2
~~~

**Comment by LonelySally** [comment]
> > > @LonelySally 第一点建议很不错，后续可以加上`Context`上下文的支持，其实内置的`logger`已经支持了的（配置文件也支持上下文配置，请参考：https://goframe.org/os/glog/context ），只是需要增加上下文变量输入即可，可以增加一个`Ctx`链式方法，so easy。第二点的话建议使用`min:1`这样的规则来校验数值类型的必需。
> > 
> > 
> > sql日志的关键点其实还是在于跟request关联起来.实际开发中能让后置中间件中获取到本次*ghttp.Request的相关sql记录才是最理想化的.这样能组成request+sql+response为一体的关联日志.
> 
> `Request`对象有个`GetCtx`方法用于获取标准化的上下文对象，随后将此对象在方法间传递，这个也是`Golang`标准的上下文参数传递方式。

目前就是这么处理的,每个service都要传入*ghttp.Request到处跑,感觉挺别扭的.真实的想法是在http进来的时候创建的goroutine初始化处做一个日志收集者,当前goroutine内产生的日志都会被收集者所收集,当*ghttp.Request被response的时候收集者将收集到的日志输出.

**Comment by LonelySally** [comment]
> > > > @LonelySally 第一点建议很不错，后续可以加上`Context`上下文的支持，其实内置的`logger`已经支持了的（配置文件也支持上下文配置，请参考：https://goframe.org/os/glog/context ），只是需要增加上下文变量输入即可，可以增加一个`Ctx`链式方法，so easy。第二点的话建议使用`min:1`这样的规则来校验数值类型的必需。
> > > 
> > > 
> > > sql日志的关键点其实还是在于跟request关联起来.实际开发中能让后置中间件中获取到本次*ghttp.Request的相关sql记录才是最理想化的.这样能组成request+sql+response为一体的关联日志.
> > 
> > 
> > `Request`对象有个`GetCtx`方法用于获取标准化的上下文对象，随后将此对象在方法间传递，这个也是`Golang`标准的上下文参数传递方式。
> 
> 目前就是这么处理的,每个service都要传入_ghttp.Request到处跑,感觉挺别扭的.真实的想法是在http进来的时候创建的goroutine初始化处做一个日志收集者,当前goroutine内产生的日志都会被收集者所收集,当_ghttp.Request被response的时候收集者将收集到的日志入库/落盘输出.

**Comment by LonelySally** [comment]
另外想问下sql的日志怎么输出到kafaka之类的日志中间件中？

**Comment by gqcn** [comment]
> 另外想问下sql的日志怎么输出到kafaka之类的日志中间件中？

你可以使用一些独立的第三方工具采集日志文件。从代码层面考虑的话，你可以获取数据库`Logger`对象后`DB.GetLogger()`自定义数据库的Logger Writer: https://goframe.org/os/glog/writer

**Comment by gqcn** [comment]
@LonelySally 别关呀，我留着排期开发。

**Comment by gqcn** [comment]
链路跟踪：https://goframe.org/pages/viewpage.action?pageId=3673684
