### ISSUE TITLE
valid request param error

### ISSUE THREAD

**Issue by Lolioy** [gogf/gf#947]
I use the latest version of gf.
This is an error when I use `eg: ghttp.request.Parse(&params)`

![image](https://user-images.githubusercontent.com/66720509/96247236-71b76c00-0fdc-11eb-9407-96270bbd7c93.png)

It's right when removing the `min` attr

**Comment by gqcn** [comment]
@Lolioy Yes, that is the error that the `min` validation rule is not met. Anything wrong?

**Comment by Lolioy** [comment]
@gqcn But why does the following error occur

**Comment by gqcn** [comment]
@Lolioy It's the default error if the value does not pass the `min` rule.
