### ISSUE TITLE
关于struct 转xml 输出与标准实现不一致的问题

### ISSUE THREAD

**Issue by sanrentai** [gogf/gf#948]
### 1. What version of `Go` and system type/arch are you using?

1.14

### 2. What version of `GoFrame` are you using?

v1.13.7

### 3. Can this issue be reproduced with the latest release?

yes

### 4. What did you do?

```go
type Response struct {   

	XMLName struct{}   `xml:"ResultBean"` //当struct有XMLName 属性时，go标准库会把它的xml tag解析成XML的root    

	Code    string     `xml:"code"`   

	Msg     string     `xml:"message"`   

	Data    FaPiaoInfo `xml:"data"`   

}   

resp := Response{  

		Code: "0000",

		Msg:  "成功",  

		Data: FaPiaoInfo{  

			Fph: "123123",  

		},  

	}  

	gds, _ := gparser.VarToXml(resp)  

	fmt.Printf("%s\n", gds)  

	xds, _ := xml.Marshal(resp)  

	fmt.Printf("%s\n", xds)  

```

### 5. What did you expect to see?

```xml
<ResultBean><code>0000</code><message>成功</message><data><fph>123123</fph></data></ResultBean>
```

### 6. What did you see instead?
```xml
<doc><ResultBean>{}</ResultBean><code>0000</code><data><fph>123123</fph></data><message>成功</message></doc>
```

**Comment by gqcn** [comment]
@sanrentai 你好，`gf`框架并没有使用标准库的`xml`包，而是使用`https://github.com/clbanning/mxj`作为底层的编码/解析包。`mxj`包会根据`map`的层级生成`xml`的层级，并且也支持`xml`标签，但是它并不支持`XMLName`这种骚属性，使得层级关系以及结构生成更清晰易懂。你可以使用`gparser.VarToXml(resp, "ResultBean")`生成你想要的结构。

此外，如果你感兴趣，可以自行去`mxj`包的issue里面提个建议。

**Comment by sanrentai** [comment]
gparser.VarToXml(resp, "ResultBean") 可以。
