### ISSUE TITLE
校验的一个困惑

### ISSUE THREAD

**Issue by yviscool** [gogf/gf#949]
```go
type GetById struct {
	Id *int `p:"id" v:"required|integer#id不能为空|id必须为整数"`
}
```
然后

```go
	var idInfo *request.GetById
	if err := r.Parse(&idInfo); err != nil {
		if v, ok := err.(*gvalid.Error); ok {
			c.Status(r, 400)
			c.Fail(r, v.FirstString())
		}
	}
```
我访问`http://localhost:8080/api/v1/admin/get?id=zjl`
然后为什么 id 为 string 可以通过验证 integer 不生效

**Comment by gqcn** [comment]
@yviscool 因为`string`的参数被转换为了`0`，`0`的话是`integer`。

**Comment by yviscool** [comment]
@gqcn 所以只能再通过 min 判断了？

**Comment by gqcn** [comment]
> @gqcn 所以只能再通过 min 判断了？

你可以考虑这样试试：
```go
type GetById struct {
	Id *g.Var `p:"id" v:"required|integer#id不能为空|id必须为整数"`
}
```

**Comment by yviscool** [comment]
> > @gqcn 所以只能再通过 min 判断了？
> 
> 你可以考虑这样试试：
> 
> ```go
> type GetById struct {
> 	Id *g.Var `p:"id" v:"required|integer#id不能为空|id必须为整数"`
> }
> ```
