### ISSUE TITLE
gvalid的json验证规则

### ISSUE THREAD

**Issue by LonelySally** [gogf/gf#952]
版本1.13.7
go1.14+
~~~
//结构体
type TestJson struct {
	Rule string `p:"rule" v:"required|json # 请填写规则|请输入正确的规则"`
}
//控制器
func Index(r *ghttp.Request) {
	var testJson *TestJson
	if err := r.Parse(&testJson); err != nil {
		g.Dump(err)
		return
	}
	g.Dump(testJson)
}
//请求url
http://127.0.0.1:8199/?rule=1234

//console输出
{
        "rule": "1234"
}
~~~

正常来说应该会在console输出错误而不会打印testJson.是否是写法错误?
json的验证使用的是gjson.Decode 直接只用该方法
~~~
de, err := gjson.Decode([]byte("1xxx"))
g.Dump(de)
g.Dump(err)
//console输出
1

null
~~~

**Comment by LonelySally** [comment]
顺便问下使用r.GetRemoteIp的话ng要怎么配置?我按照官网手册的ng配置获取回来一直是127.0.0.1.

**Comment by gqcn** [comment]
@LonelySally 试试最新的`master`分支呢，不过注意`1234`也是有效的`json`格式。

**Comment by gqcn** [comment]
> 顺便问下使用r.GetRemoteIp的话ng要怎么配置?我按照官网手册的ng配置获取回来一直是127.0.0.1.

`r.GetRemoteIp`没办法设置的，这个`RemoveIp`是从`RemoteAddr`中解析的，是当前连接的客户端IP，前置代理的话这里就是`127.0.0.1`了。我猜想你需要的可能是`r.GetClientIp`。

**Comment by LonelySally** [comment]
> @LonelySally 试试最新的`master`分支呢，不过注意`1234`也是有效的`json`格式。

是的所以我做了第二步的验证.[]byte("1xxx") err是空的
