### ISSUE TITLE
cookie默认有效期是1年，如果要浏览器就消失怎样设置？

### ISSUE THREAD

**Issue by puzhengwu** [gogf/gf#959]
cookie默认有效期是1年，如果要浏览器就消失怎样设置？

**Comment by housemecn** [comment]
如以下是MSDN上的说明

如果不指定该 Cookie 的过期限制，则该 Cookie 将不会保留在客户端计算机上，当用户会话到期时该 Cookie 即到期。

**Comment by puzhengwu** [comment]
主要是session也延用了cookie一年的有效期就不对了，就应该关闭浏览器就失效，所以cookie框架层面黓认不要设有效期

**Comment by gqcn** [comment]
@puzhengwu 有道理，欢迎提供PR。

**Comment by gqcn** [comment]
@puzhengwu @housemecn 哈哈，其实已经改进了，cookie在设置的时候maxAge传递0就是随着session过期。目前`master`分支已经有了，下个版本发布吧。

**Comment by puzhengwu** [comment]
刚才用1.15.1测试了下session默认写入的cookie还是一年的有效期，这样关闭浏览器再打开session还是存在，cookie的Expires初始时最好不要赋值即为浏览器关闭即删除

**Comment by gqcn** [comment]
@puzhengwu 增加了一个`SessionCookieMaxAge`配置，配置为`0`即可，使用`master`分支代码试试呢。

**Comment by puzhengwu** [comment]
@gqcn 刚刚测试了下SessionCookieMaxAge(0),生成的cookie正常了，然后又试了下session生命周期的控制，通常get方法应该要重置生命周期，比如有效期30分钟(测试用的10秒)，如果用户一直在操作，一直在读取session那么session就不要失效，session还是有它的特性的，不同于普通cache

**Comment by gqcn** [comment]
@puzhengwu `go get -u github.com/gogf/gf@master` 再试试。
