### ISSUE TITLE
中间件与路由验证的顺序性问题

### ISSUE THREAD

**Issue by LonelySally** [gogf/gf#961]
1.在中间件中执行如下代码
~~~
        g.Dump(r.GetRouterVar("id").Int64())
	g.Dump(r.Router.Uri)
	r.Middleware.Next()
	g.Dump(r.Router.Uri)
	g.Dump(r.GetRouterVar("id").Int64())
~~~
假设路由规则为`/api/member/:id`
构建如下url请求 `/api/member/14`
console输出
~~~
0
/*

/api/member/:id
14
~~~
要在中间件中做鉴权该怎么处理,鉴权只能前置不能后置.

2.能否在路由规则的路由参数上限定类型.例如
a:`/api/member/:id.(Number)`
b:`/api/member/:id.(String)`
`/api/member/14`=>a
`/api/member/test`=>b
不加类型则按照现有的匹配模式执行

**Comment by gqcn** [comment]
@LonelySally 不好意思，我看了一下，你这个应该是全局中间件。全局中间件是可以独立使用的，因此在它执行的时候还未执行业务的路由，所以你打印出来的`r.Router.Uri`是空的。我想你需要的是分组路由中间件，这是最常见的使用方式，这个中间件是绑定到路由方法上的，必定会有路由参数：https://goframe.org/net/ghttp/router/middleware

**Comment by LonelySally** [comment]
> @LonelySally 不好意思，我看了一下，你这个应该是全局中间件。全局中间件是可以独立使用的，因此在它执行的时候还未执行业务的路由，所以你打印出来的`r.Router.Uri`是空的。我想你需要的是分组路由中间件，这是最常见的使用方式，这个中间件是绑定到路由方法上的，必定会有路由参数：https://goframe.org/net/ghttp/router/middleware

好的.那执行顺序是不是可以理解为:全局中间件->路由解析->路由中间件.请问下哪里有有框架时序图?我在官网找不到

**Comment by gqcn** [comment]
> > @LonelySally 不好意思，我看了一下，你这个应该是全局中间件。全局中间件是可以独立使用的，因此在它执行的时候还未执行业务的路由，所以你打印出来的`r.Router.Uri`是空的。我想你需要的是分组路由中间件，这是最常见的使用方式，这个中间件是绑定到路由方法上的，必定会有路由参数：https://goframe.org/net/ghttp/router/middleware
> 
> 好的.那执行顺序是不是可以理解为:全局中间件->路由解析->路由中间件.请问下哪里有有框架时序图?我在官网找不到

请查看文档：https://goframe.org/net/ghttp/router/middleware
![image](https://user-images.githubusercontent.com/26347176/97303954-0d2ac580-1896-11eb-8395-8acfe5d524e1.png)
