### ISSUE TITLE
How to add flag on session cookies

### ISSUE THREAD

**Issue by kenticny** [gogf/gf#962]
### 1. What version of `Go` and system type/arch are you using?

go1.14.4 darwin/amd64

### 2. What version of `GoFrame` are you using?

v1.13.4

### 3. Can this issue be reproduced with the latest release?

YES

### 4. Description

I need to add `HTTP ONLY`, `SECURE` or `SAMESITE` on session cookies, but I have neither found the specifics method to set the flags, nor the corresponding settings in `ServerConfig` Cookie options. So Is there any way to set the Session cookie's flag?

**Comment by housemecn** [comment]
This sample configuration (https://goframe.org/net/ghttp/config/example) is worth seeing.

**Comment by kenticny** [comment]
@housemecn I see the configuration struct just support to set `CookieMaxAge`, `CookiePath` and `CookieDomain`, and does not support the `HttpOnly`, `SECURE` or `SameSite` options.

**Comment by housemecn** [comment]
```
type Request struct {
	*http.Request
	Server          *Server                // Server.
	Cookie          *Cookie                // Cookie.
	Session         *gsession.Session      // Session.
	Response        *Response              // Corresponding Response of this request.
	Router          *Router                // Matched Router for this request. Note that it's not available in HOOK handler.
	EnterTime       int64                  // Request starting time in microseconds.
	LeaveTime       int64                  // Request ending time in microseconds.
	Middleware      *Middleware            // Middleware manager.
	StaticFile      *StaticFile            // Static file object for static file serving.
	context         context.Context        // Custom context for internal usage purpose.
	handlers        []*handlerParsedItem   // All matched handlers containing handler, hook and middleware for this request.
	hasHookHandler  bool                   // A bool marking whether there's hook handler in the handlers for performance purpose.
	hasServeHandler bool                   // A bool marking whether there's serving handler in the handlers for performance purpose.
	parsedQuery     bool                   // A bool marking whether the GET parameters parsed.
	parsedBody      bool                   // A bool marking whether the request body parsed.
	parsedForm      bool                   // A bool marking whether request Form parsed for HTTP method PUT, POST, PATCH.
	paramsMap       map[string]interface{} // Custom parameters map.
	routerMap       map[string]string      // Router parameters map, which might be nil if there're no router parameters.
	queryMap        map[string]interface{} // Query parameters map, which is nil if there's no query string.
	formMap         map[string]interface{} // Form parameters map, which is nil if there's no form data from client.
	bodyMap         map[string]interface{} // Body parameters map, which might be nil if there're no body content.
	error           error                  // Current executing error of the request.
	exit            bool                   // A bool marking whether current request is exited.
	parsedHost      string                 // The parsed host name for current host used by GetHost function.
	clientIp        string                 // The parsed client ip for current host used by GetClientIp function.
	bodyContent     []byte                 // Request body content.
	isFileRequest   bool                   // A bool marking whether current request is file serving.
	viewObject      *gview.View            // Custom template view engine object for this response.
	viewParams      gview.Params           // Custom template view variables for this response.
}
```

是否可以通过`net/http`包`Request->AddCookie()`设置呢？

**Comment by housemecn** [comment]
`r.Request.AddCookie()`

**Comment by gqcn** [comment]
@kenticny @housemecn Hi, do you guys see `SetHttpCookie`: https://github.com/gogf/gf/blob/master/net/ghttp/ghttp_server_cookie.go#L103

**Comment by housemecn** [comment]
> @kenticny @housemecn Hi, do you guys see `SetHttpCookie`: https://github.com/gogf/gf/blob/master/net/ghttp/ghttp_server_cookie.go#L103
666/:strong

**Comment by kenticny** [comment]
@housemecn @gqcn 
I need to add the `samesite` tag on `session cookie`, but the `SetHttpCookie`  seems not override the session cookie. And I cannot find where to set the `Set-Cookie` header in source code, Could you give me some help?

**Comment by kenticny** [comment]
@gqcn @housemecn 
I need to set `SAMESITE` tag on `session cookie`, but I found the `SetHttpCookie` seems not override the session cookie. So, I should disable `SessionCookieOutput`, and manage the session cookie manully. Is this right? Or Do I have any other solution about this question?

**Comment by gqcn** [comment]
> @gqcn @housemecn
> I need to set `SAMESITE` tag on `session cookie`, but I found the `SetHttpCookie` seems not override the session cookie. So, I should disable `SessionCookieOutput`, and manage the session cookie manully. Is this right? Or Do I have any other solution about this question?

Yep, disable the `SessionCookieOutput` configuration, and  you can manually set and get the session cookie if necessary.

**Comment by kenticny** [comment]
@gqcn @housemecn 
Thanks for help. Problem is solved, and I closed the issue.

Finally, I think it should be have extra server options to setting session cookie, such as following:
```
type ServerConfig struct {
   // session cookie options
   SessionCookieSecure      bool
   SessionCookieHttpOnly   bool
   SessionCookieSameSite  string
}
```
