### ISSUE TITLE
[P0]windows gf init 项目后，gf run main.go报错

### ISSUE THREAD

**Issue by liserven** [gogf/gf#964]
windows gf init 项目后，gf run main.go报错
刚生成项目目录
![image](https://user-images.githubusercontent.com/34682164/97148599-5c91c880-17a6-11eb-8c4b-e34dcc95ed17.png)
运行的时候报错
![image](https://user-images.githubusercontent.com/34682164/97148521-3bc97300-17a6-11eb-9c27-bf11b1abd9a7.png)

**Comment by housemecn** [comment]
怎么不用gf build
