### ISSUE TITLE
配置文件能不能区分本地，线上？

### ISSUE THREAD

**Issue by lemayi** [gogf/gf#966]
比如在config目录下面，添加一个product.toml，打包的时候自动打包product.toml。本地开发的时候调用develop.toml

**Comment by housemecn** [comment]
可以去看一下已关闭的is,有人提供了解决方法

**Comment by housemecn** [comment]
> 比如在config目录下面，添加一个product.toml，打包的时候自动打包product.toml。本地开发的时候调用develop.toml

参考这个 https://github.com/gogf/gf/issues/751

**Comment by gqcn** [comment]
@lemayi 可以参考下 @housemecn 说的。

**Comment by lemayi** [comment]
@gqcn 非常感谢

**Comment by Lolioy** [comment]
@lemayi 如果是用docker之类的部署环境，可以根据传入参数判断是本地还是线上环境，然后将配置复制一份并且重命名为config.toml，这样无需修改原来的任何代码
