### ISSUE TITLE
[P0]tcp network add tcp4 or tcp6 support

### ISSUE THREAD

**Issue by NinthKnight** [gogf/gf#968]
When use the gtcp or ghttp, it create socket or bind socket use argument such as "tcp" just like this:
![image](https://user-images.githubusercontent.com/40989241/97406042-92b08300-1933-11eb-8862-6613b6566bf6.png)
![image](https://user-images.githubusercontent.com/40989241/97406072-9e9c4500-1933-11eb-9731-7ef37ffa8d0d.png)

But if you not use tcp4, it will use AF_INET6 to create socket or bind socket.
![image](https://user-images.githubusercontent.com/40989241/97406455-37cb5b80-1934-11eb-933a-8c817dfc3e7f.png)

 then you will bind a port which had been bind by other application without any error。(You can write a c++ application for test use raw socket.)
just like this:
![image](https://user-images.githubusercontent.com/40989241/97406539-5598c080-1934-11eb-95b8-b2b5cf21a0d1.png)
if you use tcp4 just like this:
![image](https://user-images.githubusercontent.com/40989241/97406606-706b3500-1934-11eb-8b98-cea7a75269b6.png)

Then bind a binded port(which create by other application used AF_INET), it can be error just like this:
![image](https://user-images.githubusercontent.com/40989241/97406950-f0919a80-1934-11eb-896c-824ed5ec0024.png)

Can GF support a function that we can choose "tcp4" or "tcp6" for this problem?
Thanks Dalao!

英语too poor..请多包涵

**Comment by gqcn** [comment]
@NinthKnight Why you closed this issue?

**Comment by NinthKnight** [comment]
> @NinthKnight Why you closed this issue?

点错了 - -！
