### ISSUE TITLE
gtime在对time的零值格式化时不正确

### ISSUE THREAD

**Issue by jroam** [gogf/gf#969]
### 1. What version of `Go` and system type/arch are you using?

go.1.15

### 2. What version of `GoFrame` are you using?

gf1.14.1

### 4. What did you do?

like:
g.Dump(time.Time{}.String())
g.Dump("=>" + gtime.NewFromTime(time.Time{}).String() + "<=")

### 5. What did you expect to see?
一个有值，一个没有值，
在有些要求零值的datatime字段时会报错。

### 6. What did you see instead?

希望看看。

**Comment by gqcn** [comment]
@jroam Yes, it's an empty string when you convert or print out `gtime.Time`. But if you do really want an initialized value, you cat do like this `gtime.NewFromTime(time.Time{}).Time.String()`.
