### ISSUE TITLE
[P0]1.14.2版本中能否加个配置不让orm维护updated_at,created_at字段

### ISSUE THREAD

**Issue by jialeo** [gogf/gf#971]
因为当前项目记录的是毫秒时间戳，gf不支持，想自己维护updated_at，created_at。
能否加入一个配置选项关闭这个特性？

**Comment by lemayi** [comment]
确实应该加个配置选项

**Comment by gqcn** [comment]
@jialeo 后面有计划支持整型的类型。不想再增加更多配置了，`gf`期望一切尽可能简便。

**Comment by housemecn** [comment]
暂时可以通过 Unscoped() 方法控制

**Comment by ayamzh** [comment]
其实有必要加一个 laravel的create_at 也是可配置的，尽量不要代码层面对DB有强约束。

**Comment by gqcn** [comment]
@lemayi @jialeo @ayamzh @housemecn `develop`分支上增加了`TimeMaintainDisabled`配置，可通过配置手动关闭时间维护功能。此外，之前已经有配置可以修改时间字段名称。

**Comment by housemecn** [comment]
> @lemayi @jialeo @ayamzh @housemecn `develop`分支上增加了`TimeMaintainDisabled`配置，可通过配置手动关闭时间维护功能。此外，之前已经有配置可以修改时间字段名称。

👍👍👍👍👍👍

**Comment by jialeo** [comment]
@housemecn 官网文档没有加上，希望加到文档上面去

**Comment by gqcn** [comment]
@lemayi @jialeo @ayamzh @housemecn 感谢各位，文档已更新：https://itician.org/pages/viewpage.action?pageId=1114139
