### ISSUE TITLE
如何配置不用redis

### ISSUE THREAD

**Issue by Schr0dingerCat** [gogf/gf#972]
请问大大，如何配置，不使用redis？？
本地windows下小系统，使用mssql数据库，数据量跟访问都不大，用不到redis。
运行了下例子，里面有设置redis，电脑安装redis后，能正常运行。
现在我想不要redis，然后我把配置里的redis删掉，运行失败。
如何能够不使用redis？？

**Comment by housemecn** [comment]
缓存那里是不是适配了redis，看下默认配置文件 猜测是缓存配置问题

**Comment by gqcn** [comment]
@Schr0dingerCat 哥，你检查下代码肯定哪里使用了Redis的，你不使用肯定不会引入的。

**Comment by Schr0dingerCat** [comment]
@gqcn @housemecn 谢谢各位了，翻了下gfast的各个文档，终于找到在哪里开关了。
是在配置文件config.toml 文件的 [gToken] CacheMode = 1 ，赋值为1是不使用redis
