### ISSUE TITLE
orm中的scanlist扫描结果不准确

### ISSUE THREAD

**Issue by jroam** [gogf/gf#973]
### 1. What version of `Go` and system type/arch are you using?
go1.15.2

### 2. What version of `GoFrame` are you using?

gf1.14.2

### 4. What did you do?

orm的scanlist扫描出来的结果，不准确。 相同的日期字段的值会丢失掉。

### 6. What did you see instead?
sql文件和示例代码在附件里. 

[demosgf.zip](https://github.com/gogf/gf/files/5465198/demosgf.zip)

**Comment by gqcn** [comment]
@jroam Please `go get -u github.com/gogf/gf@master` and try again.
