### ISSUE TITLE
官方案例无法 将JSON转换为struct

### ISSUE THREAD

**Issue by ckbabby** [gogf/gf#974]
### 1. What version of `Go` and system type/arch are you using?

go version go1.15.2 windows/amd64

### 2. What version of `GoFrame` are you using?

github.com/gogf/gf v1.14.2

### 3. Can this issue be reproduced with the latest release?
yes

### 4. What did you do?

package main

import (
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/net/ghttp"
)

type RegisterReq struct {
	Name string
	Pass string
}

func main() {
	s := g.Server()
	s.BindHandler("/", func(r *ghttp.Request) {
		var req *RegisterReq
		err := r.Parse(&req)
		g.Dump(err)
		g.Dump(req)
	})
	s.SetPort(8199)
	s.Run()
}

curl -d '{"name":"john","pass":"123"}' "http://127.0.0.1:8199/"
当我Post 提交JSON时返回结果这样
null

{
        "Name": "",
        "Pass": ""
}

**Comment by fulltimelove** [comment]
curl -d "{\"name\":\"john\",\"pass\":\"123\"}" "http://127.0.0.1:8199/"

**Comment by ckbabby** [comment]
多谢了，测试过可以了
