### ISSUE TITLE
v1.14.2 中修改 GetQueryMap 造成不兼容

### ISSUE THREAD

**Issue by botsphp** [gogf/gf#975]
https://github.com/gogf/gf/commit/9c3b978b5082d0ed96cc5e93b1a053000232b302#diff-eb762e46d30690a42f51379fb0f404cecc67574f086a87a3f019ce0bffd3815a

大致看了一下，现在把 `r.parseBody()` 放到了 Get 请求中，目前的页面存在 Post 搜索的情况，出现不兼容的问题。
想问一下这个地方是基于什么考虑的。

**Comment by gqcn** [comment]
@botsphp 是为了区分`r.Parse/ParseQuery/ParseForm`。

**Comment by botsphp** [comment]
@gqcn 之前的版本用 GetQueryMap，可以获取到 post 请求中的参数，现在改成了只支持 get，造成之前业务中使用 GetQueryMap的地方，现在都失效了。

存在的场景获取参与，优先级是 Post>Get。

**Comment by gqcn** [comment]
> @gqcn 之前的版本用 GetQueryMap，可以获取到 post 请求中的参数，现在改成了只支持 get，造成之前业务中使用 GetQueryMap的地方，现在都失效了。
> 
> 存在的场景获取参与，优先级是 Post>Get。

你的场景可以使用`r.GetMap`。
