### ISSUE TITLE
I set the LevelPrefixes but it doesn't work in db(MySQL).

### ISSUE THREAD

**Issue by klarkxy** [gogf/gf#985]
### 1. What version of `Go` and system type/arch are you using?
go version go1.15.3 linux/amd64

### 2. What version of `GoFrame` are you using?

github.com/gogf/gf v1.14.2

### 3. Can this issue be reproduced with the latest release?
Yes

### 4. What did you do?
main.go
``` go
var myLogColor = map[int]string{
	glog.LEVEL_DEBU: color.Gray.Sprint("DEBUG"),
	glog.LEVEL_INFO: color.White.Sprint("INFO"),
	glog.LEVEL_NOTI: color.Green.Sprint("NOTIFY"),
	glog.LEVEL_WARN: color.Yellow.Sprint("WARNING"),
	glog.LEVEL_ERRO: color.Red.Sprint("ERROR"),
	glog.LEVEL_CRIT: color.Cyan.Sprint("CRITICAL"),
	glog.LEVEL_PANI: color.Blue.Sprint("PANIC"),
	glog.LEVEL_FATA: color.Magenta.Sprint("FATAL"),
}

func init() {
	glog.SetStack(true)
	glog.SetLevel(glog.LEVEL_ALL)
	glog.SetLevelPrefixes(myLogColor)
}
func main() {
	s := g.Server()
	s.Use(middleware.CORS)
	s.Use(middleware.MiddlewareLog)
	s.Group("/api", api.Router)

	glog.Debug("Hello World.")

	s.Run()
}
```
The API
```go
// Home  [GET]/api/home/home
func Home(r *ghttp.Request) {
	db := work.Model
	res, err := db.All()
	if err != nil {
		r.Response.WriteJson(res)
	} else {
		r.Response.Writeln(err)
	}
}

```

And the console show like this:
![image](https://user-images.githubusercontent.com/6316992/98463576-26693580-21f7-11eb-843d-1a3460118934.png)
I perfer to get the log like the upper one, but the db's log is still old.
The DB is MySQL.
我希望显示效果是类似于上面的，灰颜色的[DEBUG]，但db里打印的日志仍然是[DEBU]

**Comment by gqcn** [comment]
@klarkxy The logger in `gdb.DB` is not the default logger in package `glog`. Use `db.GetLogger()` to retrieve the logger of db.
