### ISSUE TITLE
gredis hscan json数据获取

### ISSUE THREAD

**Issue by lemayi** [gogf/gf#986]
go：1.15.3
gf: 1.14.2
platform: MacOS

redis cli：
HSCAN post_digg_9 0 match "9::*" count 2

输出：
0
9::1
{"action":1,"time":1604767519}
9::2
{"action":1,"time":1604767519}

gf代码:
v, _ := redis.DoVar("HSCAN", "post_digg_9", 0, "match", "9::*", "count", 1)
fmt.Println(v)

输出：
["0","[\"OTo6MQ==\",\"eyJhY3Rpb24iOjEsInRpbWUiOjE2MDQ3Njc1MTl9\",\"OTo6Mg==\",\"eyJhY3Rpb24iOjEsInRpbWUiOjE2MDQ3Njc1MTl9\"]"]

请问要怎么解析出json。分别获取到action，time的值呢？

**Comment by gqcn** [comment]
@lemayi My dear friend, please refer to following example:
```go
v, _ := redis.DoVar("HSCAN", "post_digg_9", 0, "match", "9::*", "count", 1)
fmt.Println(v.Map())
```
