### ISSUE TITLE
v1.14.2 请求输入使用结构绑定存在兼容问题

### ISSUE THREAD

**Issue by mikenut** [gogf/gf#989]
使用结构体进行输入参数绑定时存在兼容问题。

```
type ChargeReq struct {
	Trace        string `p:"trace"  v:"required#miss-trace"`
	SupplierCode string `p:"supplierCode"  v:"required#miss-supplierCode"`
	Topic        string `p:"topic"  v:"required#miss-topic"`
	Message      struct {
		SupplierCode  string `p:"supplierCode"  v:"required#miss-supplierCode"`
		OrderItemCode string `p:"orderItemCode"  v:"required#miss-orderItemCode"`
	} `p:"message"  v:"required#miss-message"`
	Sign string `p:"sign" v:"required#miss-sign"` // 签名
}
```

以上结构体存在嵌套形式，在 v1.13.7 中可以通过校验，但在 v1.14.2 中嵌套内容无法绑定，Message 中 SupplierCode 和 OrderItemCode 无法获取参数内容。

输入：trace=trade_1604985510205&sign=cc7299a86e3a42c8b56c1ee5215a18a7&topic=suning_order_virtual_resend&supplierCode=123&message={"orderItemCode":"0012987","supplierCode":"123"}

**Comment by gqcn** [comment]
@mikenut Bug fixed, please `go get -u github.com/gogf/gf` to use the latest version.
