### ISSUE TITLE
websocket 并发写会出异常

### ISSUE THREAD

**Issue by sanrentai** [gogf/gf#990]
### 1. What version of `Go` and system type/arch are you using?

go 1.15

### 2. What version of `GoFrame` are you using?

gf 1.14.2

### 3. Can this issue be reproduced with the latest release?

yes

ghttp.WebSocket 是否考虑加个读写锁?

type WsConn struct {
	*websocket.Conn
	Mux sync.RWMutex
}
 
 
wsConn.Mux.Lock() //加锁
	err=wsConn.Conn.WriteMessage(websocket.TextMessage,msgByte)
wsConn.Mux.Unlock() //解锁

**Comment by LonelySally** [comment]
使用chan去写消息不需要加锁.

**Comment by sanrentai** [comment]
使用chan确实不错。

**Comment by LonelySally** [comment]
> 使用chan确实不错。

go的chan本身是其语言的一大特点,即分前后也包原子.既然用go了,能用语言特性方面处理还是用特性最优.

**Comment by sanrentai** [comment]
https://studygolang.com/articles/31639

这个例子不错，按这个实现做的。
