### ISSUE TITLE
GetOrSetFuncLock 使用db查询时会卡住

### ISSUE THREAD

**Issue by fengzhongyun1992** [gogf/gf#991]
### 1. What version of `Go` and system type/arch are you using?

go version go1.15 windows/amd64

### 2. What version of `GoFrame` are you using?

v1.14.2

### 3. Can this issue be reproduced with the latest release?

yes

### 4. What did you do?

```
func Hello(r *ghttp.Request) {

    data,_ := gcache.GetOrSetFuncLock("count", func() (interface{}, error) {
        db := g.DB()
        count,err := db.Table("config").Count() // 卡住了
        fmt.Println(count)
        return count,err
    }, 0);
    
    r.Response.Writeln(data)
}
```
v1.3 版本，这样操作没有问题，v1.4 在GetOrSetFuncLock执行数据库操作就卡住不动了。使用 GetOrSetFunc 是正常的

**Comment by gqcn** [comment]
@fengzhongyun1992 Bug fixed, please `go get -u github.com/gogf/gf` to use the latest version.
