### ISSUE TITLE
查询builder语句转原始sql语句

### ISSUE THREAD

**Issue by dwdcth** [gogf/gf#992]
### 2. What version of `GoFrame` are you using?

v1.14.2

### 3. Can this issue be reproduced with the latest release?

yes

### 5. What did you expect to see?

`db.Table("user").Where("uid > ?", 1).Limit(0, 10)`
如上语句是否可以提供一个ToSql语句，生成sql语句

另外怎么用orm做子查询

**Comment by arieslee** [comment]
> ### 2. What version of `GoFrame` are you using?
> v1.14.2
> 
> ### 3. Can this issue be reproduced with the latest release?
> yes
> 
> ### 5. What did you expect to see?
> `db.Table("user").Where("uid > ?", 1).Limit(0, 10)`
> 如上语句是否可以提供一个ToSql语句，生成sql语句
开启debug就可以打印sql语句了
`g.DB.SetDebug(true)`

**Comment by gqcn** [comment]
> ### 2. What version of `GoFrame` are you using?
> v1.14.2
> 
> ### 3. Can this issue be reproduced with the latest release?
> yes
> 
> ### 5. What did you expect to see?
> `db.Table("user").Where("uid > ?", 1).Limit(0, 10)`
> 如上语句是否可以提供一个ToSql语句，生成sql语句
> 
> 另外怎么用orm做子查询

ToSql这种场景不多啊，算了吧。

目前ORM不支持子查询，复杂的查询直接用SQL吧。
