### ISSUE TITLE
关于gconv.int 数字转换的问题

### ISSUE THREAD

**Issue by chenall** [gogf/gf#993]
目前的gconv.int会`智能判断`数字格式 
比如
0x 开头16进制
0  开头8进制

16进制还比较经常用到，8进制就几乎用不到，很多时候普通前导0的10进制数字会被当成8进制进行转换导致结果异常。

希望能有一个开关或什么好的方法可以避免这种情况。

**Comment by gqcn** [comment]
@chenall 啥情况下你会有前导0的整型？

**Comment by chenall** [comment]
目前碰到的主要是一些支付交易的接口(参数都是字符型的)。
要求 金额是 12位分的数字
比如 000000000020

**Comment by gqcn** [comment]
@chenall 你使用`gconv.Int(gstr.TrimLeft(xxx, "0"))`来处理吧。

**Comment by chenall** [comment]
主要是用 gconv.struct 转换会比较麻烦。
记得好像是会直接异常的样子，我明天再详细试下。

**Comment by gqcn** [comment]
@chenall 你在使用`gconv.Struct`之前先把参数`gstr.TrimLeft`一下撒。
