### ISSUE TITLE
[P0]gmap.ListMap 转字符串没有按照顺序排序

### ISSUE THREAD

**Issue by macnie** [gogf/gf#994]
```
		data := gmap.NewListMap(true)
		data.Set("CmdCode", "NB01")
		data.Set("Params", "hahaha")
		data.Set("IMEI", "78903422555")
		data.Set("BMEI", "a")

		fmt.Println("打印结果：",data.String())
		fmt.Println("我的期望",`{"CmdCode":"NB01","Params":"hahaha","IMEI":"7","BMEI":"a"}`)
```

执行结果：
--------------------------
打印结果： {"BMEI":"a","CmdCode":"NB01","IMEI":"78903422555","Params":"hahaha"}
我的期望 {"CmdCode":"NB01","Params":"hahaha","IMEI":"7","BMEI":"a"}

gjson.New(listmap).ToJsonString() 也会出现这个问题。

**Comment by gqcn** [comment]
除此之外，得检查所有排序map在抓换为字符串或者JSON时是否支持排序。
