### ISSUE TITLE
gf1.13.4     UpdateTime *gtime.Time is nil submit is error

### ISSUE THREAD

**Issue by 85315518** [gogf/gf#996]
### 1. What version of `Go` and system type/arch are you using?

  UpdateTime *gtime.Time

go 1.3.4 , linux/amd64

### 2. What version of `GoFrame` are you using?

    go 1.3.4

### 4. What did you do?

    时间问题
![image](https://user-images.githubusercontent.com/35963731/99162655-142d5100-273b-11eb-9ea5-c17f50adbfdb.png)

更新时间，刚录入时这个时间按理是没有的，不能有。另外有些时间，比如说审批时间,刚开始申请都没有审批，是不能有审批时间，审批了才能有时间。

**Comment by housemecn** [comment]
没有默认值的 你可以加上 omitempty 方法
参考https://goframe.org/database/gdb/model/fields-filter#tip4

**Comment by gqcn** [comment]
@85315518 如楼上所说，此外，如果你的时间属性参数值为`nil`，写入的时候将会转换为`null`。

**Comment by 85315518** [comment]
我试过，不行，自己把空值给库字段，系统报数据类型不匹配


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gogf/gf"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月19日(星期四) 晚上8:33
收件人:&nbsp;"gogf/gf"<gf@noreply.github.com&gt;;
抄送:&nbsp;"海"<85315518@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [gogf/gf] gf1.13.4     UpdateTime *gtime.Time is nil submit is error (#996)





 
@85315518 如楼上所说，此外，如果你的时间属性参数值为nil，写入的时候将会转换为null。

**Comment by gqcn** [comment]
> 我试过，不行，自己把空值给库字段，系统报数据类型不匹配
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "gogf/gf" <notifications@github.com&gt;; 发送时间:&nbsp;2020年11月19日(星期四) 晚上8:33 收件人:&nbsp;"gogf/gf"<gf@noreply.github.com&gt;; 抄送:&nbsp;"海"<85315518@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 主题:&nbsp;Re: [gogf/gf] gf1.13.4 UpdateTime *gtime.Time is nil submit is error (#996) @85315518 如楼上所说，此外，如果你的时间属性参数值为nil，写入的时候将会转换为null。 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

如果还有问题的话可以把代码和sql提交上来，我试试。
