### ISSUE TITLE
启动报错 日志空对象

### ISSUE THREAD

**Issue by ruziyi** [gogf/gf#999]
### 1. What version of `Go` and system type/arch are you using?

go1.14.8 windows/amd64

### 2. What version of `GoFrame` are you using?

v1.14.2

### 3. Can this issue be reproduced with the latest release?
不能稳定复现

### 4. What did you do?

一开始日志配置是这样的

![image](https://user-images.githubusercontent.com/7804644/99338693-acecd980-28bf-11eb-9530-4f10b9416e3f.png)

正常手动启动没有问题, 用pm2 启动报错
![image](https://user-images.githubusercontent.com/7804644/99338889-0b19bc80-28c0-11eb-9437-980a1f5d06a9.png)
但有时又好了

**Comment by gqcn** [comment]
@ruziyi 感谢反馈，做了下容错处理。报错的时候你可以打开调试模式，可以打印出详细的报错信息。
